### ISSUE TITLE
Low resolution .ico [Windows 10]

### ISSUE THREAD

**Issue by CHarrisMedia** [Foundry376/Mailspring#10]
Original version had the same issue, please see following screenshot. https://i.imgur.com/Y9ERlY7.png

I believe it may be being compiled with the wrong .ico image?

**Comment by bengotow** [comment]
Ahh that does look awful. Will see what happened - thanks!

**Comment by bengotow** [comment]
Version 1.0.1 started shipping a few minutes ago, so this should be fixed now. Let me know if you still see this after updating!

**Comment by patrickheeney** [comment]
@bengotow Should [this](https://github.com/Foundry376/Mailspring/blob/master/app/build/create-signed-windows-installer.js#L17) be updated as well? The new url doesn't work but the [old one](http://edgehill.s3.amazonaws.com/static/nylas.ico) does.

**Comment by bengotow** [comment]
Ahh good catch! That should definitely be updated. Will fix.
