### ISSUE TITLE
Feature Request: Add an option to block only remote (src="http://") inline images and allow CID images

### ISSUE THREAD

**Issue by lazylionca** [Foundry376/Mailspring#1000]
Hi 

Most email clients will blocking downloading images, but they don't block downloading CID Embedded Images (Inline Images). 

Not only does this allow for privacy violation but it will allows spammers to spam again.

I realize Mailspring probably uses these for Read Receipts and tracking but protecting my privacy is more important than knowing if someone clicked on my email or not. Actually those read notifications are getting annoying.

Can we have the option to disable the read notifications.

Can we have a a way to block CID images from loading without permission same as regular non embedded images.

Thanks all

**Comment by bengotow** [comment]
Hey - technically CID images are fine - the data for the image is actually in the message. It's remote images (eg: https://myserver.com/tracking-pixel.gif) that you want to block. Mailspring currently only has one option to block all images regardless of source, but we could block only remote images separately in the future.
