### ISSUE TITLE
imap

### ISSUE THREAD

**Issue by lazylionca** [Foundry376/Mailspring#1001]
Hi guys

Loving the program but I'm still having the issue where imap account just stop syncing. 
Probably every two days I have to remove and re-add my imap accounts and it's getting tedious.

Is there some log file that I can send you that will help resolve this?

**Comment by bengotow** [comment]
Yep please go to Developer > Show Mailsync Logs and attach the `mailsync-**.log` files you find in that folder, that'll help narrow this down quite a bit. Also include your email provider, typically these are related to a single service.

**Comment by lazylionca** [comment]
[mailsync-527a26b6.log](https://github.com/Foundry376/Mailspring/files/2259224/mailsync-527a26b6.log)

This email server is a Zimbra instance running in house on our own servers. 
I run mailspring on three different machines: two Windows 10 and 1 OSX.

**Comment by lazylionca** [comment]
[mailsync-39f7e85d.log](https://github.com/Foundry376/Mailspring/files/2324610/mailsync-39f7e85d.log)

Hope this helps.

**Comment by Bergg** [comment]
Might be related to #386, and/or #238 since you're using a zimbra server. Have you tried to rebuild the cache instead of deleting/adding the account?

**Comment by lazylionca** [comment]
Reset Cache works. Thank you. But it is annoying to have to do every day on multiple computers.
Especially since it rebuilds the contacts list with all the old email addresses that are no longer valid.
