### ISSUE TITLE
Feature Request: Add "Mark as Spam" to right-click menu

### ISSUE THREAD

**Issue by amorris28** [Foundry376/Mailspring#1011]
##### Are there any related issues?
Not that I can see

...

##### What operating system are you using?
Ubuntu 18.04
...

##### What version of Mailspring are you using?
1.4.0

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
The gmail web app allows you to "Mark as Spam" without opening the email.
...

**Comment by dixonge** [comment]
I agree that this would be a nice option  +1

**Comment by bengotow** [comment]
Hey! This is a great idea and it shouldn't be too hard to add - I'll see if I can get this in to the next patch release.

**Comment by bengotow** [comment]
Hey! This has shipped in a recent release, going to mark this as closed!
