### ISSUE TITLE
Move to the next message rather than back to the inbox after archive or delete

### ISSUE THREAD

**Issue by dublav** [Foundry376/Mailspring#1023]
##### Are there any related issues?

No

##### What operating system are you using?

MacOS

##### What version of Mailspring are you using?

1.4.1

**Bug?**

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Include an option in settings so that, when reading a message, after clicking to archive or delete, the next message is displayed rather than going back to the inbox.  This is possible in Gmail and Newton.

**Comment by bengotow** [comment]
Hey! There's no button to do this in the interface, but you can actually bind keyboard shortcuts to "Remove and Show Previous" and "Remove and Show Next" which offer what you're looking for. If you use the Gmail shortcut set, it's `{` and `}` or you can choose your own in Preferences > Shortcuts.

(The "Remove" action is "Archive" for Gmail accounts and "Trash" for other accounts, unless you've enabled "Swipe gesture and backspace / delete move messages to trash" under Preferences > General.) 

Hope that helps!

**Comment by dublav** [comment]
Fantastic response, thanks so much Ben.  Keep up the good work

--
@lav <http://twitter.com/lav>
+353 87 241 1514
