### ISSUE TITLE
Activate cursor in the body-text field when initiating a reply

### ISSUE THREAD

**Issue by dublav** [Foundry376/Mailspring#1024]
##### Are there any related issues?

No

##### What operating system are you using?

MacOS

##### What version of Mailspring are you using?

1.4.1

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

After initiating a reply or reply-all, automatically activate the cursor in the body-text field (to avoid the messy situation of using keyboard shortcuts when you think you’re typing a message). This is in Gmail and Newton

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
