### ISSUE TITLE
Cannot send email with attachement

### ISSUE THREAD

**Issue by jkarun** [Foundry376/Mailspring#1026]
I configured SMTP and IMAP settings in windows 10. I can receive email and send mail with out attachment. I am facing mail delivery issue when  I try to send email with document.

screenshot of this issue:
![mail spring issue](https://user-images.githubusercontent.com/12997707/44091439-099b4f6e-9feb-11e8-9e4d-4081bcf81bd7.JPG)

**Comment by jkarun** [comment]
Issue - Can not send email with attachment in windows10

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - could you open the Mailsync logs by choosing Developer > Show Mailsync Logs from the menu? (The files are the ones like mailsync-****.log in the folder that appears) and email those files to ben@foundry376.com? I've seen a few other scattered reports of this and I'd love to get to the bottom of it, but I'll probably need the information in those logs to narrow this down.

Thanks!

**Comment by oxmynx** [comment]
I had the same problem yesterday. I am going to send you the logs as advised.
