### ISSUE TITLE
 [feature] Support for kerberos / GSSAPI authentication for IMAP #3485 

### ISSUE THREAD

**Issue by arthurlogilab** [Foundry376/Mailspring#103]
It would be really nice if Nylas-mail could support kerberos (GSSAPI) tokens for authentication.

##### Are there any related issues?

no

##### What operating system are you using?
Linux (Debian/Ubuntu)

##### What version of Mailspring are you using?
1.0.2

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
In most desktop email clients on linux, we frequently use Thunderbird with this feature : https://twiki.cern.ch/twiki/bin/view/AFSService/ConfigureYourEmailClientForKerberosAuthentication mutt has it too, offlineimap too. etc.

**Comment by bengotow** [comment]
I think this is supported on Mac and Windows, on Linux we most likely just need to ship the appropriate sasl2 plugin.

**Comment by bengotow** [comment]
(Should be fixed by f82c88367b26746aa8e365156e0601b952de6635, will check)

**Comment by arthurlogilab** [comment]
awesome ! thanks for the speedy response. Do you want me to test out the travis built deb before the release ?

**Comment by arthurlogilab** [comment]
I would imagine 1.0.5 would include the patch referenced above, but I can't seem to login with keberos to my imap server. 

In the interface, I have to enter a fake password to click on connect, maybe that forces mailspring to switch to plaintext login/password

On the server side I get: 

```
Oct 19 10:35:39 cassiopeia cyrus/imap[11067]: badlogin: [IP] plaintext arthur SASL(-13): user not found: checkpass failed
```
With thunderbird with kerberos configured I get 
```
Oct 19 10:35:43 cassiopeia cyrus/imaps[15868]: login: [IP] arthur GSSAPI+TLS User logged in SESSIONID=<cyrus-ID>
```

**Comment by bengotow** [comment]
Hey @arthurlogilab sorry for the delay—are you still seeing this problem? I think in 1.0.6 I added a libsasl plugin we'd forgotten, so you might want to try that version. Cheers—

**Comment by bocekm** [comment]
@bengotow, I've installed the 1.0.7 rpm and I can't see an option to use Kerberos/GSSAPI when adding an IMAP account. Is it hidden somewhere? :)
![screenshot from 2017-11-06 11-20-27](https://user-images.githubusercontent.com/9884110/32436542-a79e1bcc-c2e4-11e7-8e17-8fbff279c52b.png)

**Comment by bengotow** [comment]
Hey! Ahh it should be automatic—if your server responds with `GSSAPI` as one of the allowed auth mechanisms, Mailspring will use it. (It was broken on Linux before because we weren't shipping the right plugins for libsasl2)

**Comment by bocekm** [comment]
Unfortunately, the authentication fails. See log below. It's kind of strange that even though I want to use GSSAPI the form requires password. So I have typed in some random password.

```
----------IMAP----------
* OK IMAP4 ready
1 CAPABILITY
* CAPABILITY ACL BINARY CATENATE CHILDREN CONDSTORE ENABLE ESEARCH ID IDLE IMAP4rev1 LIST-EXTENDED LITERAL+ MULTIAPPEND NAMESPACE QUOTA RIGHTS=ekt********* SASL-IR SEARCHRES UIDPLUS UNSELECT WITHIN ESORT I18NLEVEL=1 SORT THREAD=ORDEREDSUBJECT LIST-STATUS XLIST AUTH=PLAIN AUTH=GSSAPI
1 OK completed
2 LOGIN mbocek *********
�2 NO LOGIN failed

```

**Comment by bocekm** [comment]
IMHO the best would be adding fourth option (Kerberos/GSSAPI) to the _Security_ dropdown, apart from the SSL/TLS, STARTTLS and None. When choosing it I would expect the Password field to get inaccessible.

By the way, I guess the Password field can be removed from the previous window, given that GSSAPI doesn't need any password. Currently it's mandatory to fill in some value.
![screenshot from 2017-11-06 18-43-19](https://user-images.githubusercontent.com/9884110/32455383-689a90ca-c322-11e7-9c27-0198da9ce6b8.png)

**Comment by arthurlogilab** [comment]
@bengotow thanks for the follow up and pointing to mailcore2, should we create an issue there to be able to follow the progress on this feature request ? 

@bocekm I agree with you, it would be nice to avoid getting users to type a password that they usually don't have to type in the mail client

**Comment by arthurlogilab** [comment]
Hi,

This is still not working with 1.2.1 : 

```
----------IMAP----------
* OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE STARTTLS AUTH=GSSAPI AUTH=PLAIN SASL-IR] imap.logilab.fr Cyrus IMAP git2.4.17+0-Debian-2.4.17+nocaldav-0~deb8u1 server ready
1 STARTTLS
1 OK Begin TLS negotiation now
2 LOGIN arthur *********
2 NO Login failed: authentication failure
```

I've added an issue to mailcore2 (link above)

**Comment by haniayoub** [comment]
this is still not working, is there any plan to fix it?

**Comment by arthurlogilab** [comment]
My company would probably be interested in getting a pro subscription https://getmailspring.com/pro but without this, we can't use mailspring at all, and we have no workaround.

**Comment by arthurlogilab** [comment]
It seems that since august 2018 the SMTP part is now working with kerberos, could this feature now b made available for IMAP ?

**Comment by arthurlogilab** [comment]
bump ?
