### ISSUE TITLE
Window icon is missing on Linux

### ISSUE THREAD

**Issue by iblazhko** [Foundry376/Mailspring#1032]
OS: Ubuntu Budgie Linux 18.04
Mailspring 1.4.2

-----

### Description

Window icon is missing in some places, e.g. in the workspace overview:
<https://drive.google.com/open?id=1IGcbosAq0l92W-h7VNLUqvJq60j_bfCr>

In some other places, e.g. in task switcher, icon is OK.

### Comments

Looking at the code, it appears that the `icon` property of the `BrowserWindow` object is not set. Maybe this is the problem.

Have a look for an example of this in the Tusk Evernote client:

https://github.com/klauscfhq/tusk/blob/9d3704b573d6aae25e995fc6148e6172707ad96b/index.js
LL 49-68:

```javascript
new electron.BrowserWindow({
//...
icon: process.platform === 'linux' && path.join(__dirname, 'static/Icon.png'),
});
```

Tusk window icon is displayed properly.

**Comment by bengotow** [comment]
@sgerner pushed a PR for this one and it'll ship in the next release. 🎉

**Comment by CalebJohn** [comment]
OS: Xubuntu 18.04
Mailspring 1.5.5

This appears to still be an issue but only if mailspring was installed with the snap package. Installing with the .deb has the correct icons. My guess is that the sandboxing prevents the snap package from placing the icon file in `/usr/share/pixmaps` or prevents the file from being read.

In my case, the applications menu showed the correct icon (it comes from the .desktop file) but all other places (alt-tab, window buttons, etc.) only showed the default missing-icon icon.

**Comment by miun173** [comment]
@CalebJohn I'm experience the missing icon too, i installed using snap package, is there a way to fix this manually? Thanks

**Comment by CalebJohn** [comment]
I couldn't find a simple way using the snap package, and settled for using the .deb. Sorry I couldn't be more help.

**Comment by akshayvinchurkar** [comment]
on ubuntu 18.04 I am still facing the issue generic icon is showing
