### ISSUE TITLE
[Feature request] Color code for accounts and highlight in editor

### ISSUE THREAD

**Issue by sthagedorn** [Foundry376/Mailspring#1035]
Related to #526 a color code for each account would be helpful:

In the editor, the `FROM` field could be highlighted with the respective color. Hence, when using e.g. an account for work and another one for private mails, one can easily see which account is being used.

**Comment by rjhilgefort** [comment]
Just on-boarded and this is the first thing I've found that's "missing" that I would expect. It's too easy to not realize what account you're sending from or received.

+1 for this feature.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved (via #2240), so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
