### ISSUE TITLE
Custom ports support for IMAP

### ISSUE THREAD

**Issue by jose-sanchezm** [Foundry376/Mailspring#104]
My IMAP server has non standard ports for both IMAP and SMTP but I can't use them since the UI doesn't allow to select arbitrary numbers during the init wizard. Could you please replace the combobox with a text field so we can put whatever port we need?

**Comment by emper0r** [comment]
+1 with that, 

I'm using davmail and I have to start service as root, so it will be very usefull if was started as user using more that 1024 ports. so I supported this issue to useful if will be fixed.

Thanks in advance

**Comment by bengotow** [comment]
Hey! Thanks for filing this - this will actually be an option in 1.0.3 which will ship in an hour or two. Stay tuned! You can check out the full changelog here: https://github.com/Foundry376/Mailspring/blob/master/CHANGELOG.md

**Comment by emper0r** [comment]
Cool! ... downloaded and tested!... works very well imap/smtp , you rock! and can close the bug/feature
can confirm raw html window with correct size
