### ISSUE TITLE
make .deb i386 build available

### ISSUE THREAD

**Issue by zeph** [Foundry376/Mailspring#1045]
Hi guys, 
very simple... I see in your CI/CD setup the i386 binary is available 
but not exposed for download... would you mind making it available? 

Best, 
GMS

**Comment by CodeMouse92** [comment]
Unfortunately, [Electron discontinued support for 32-bit Linux](https://www.electronjs.org/blog/linux-32bit-support), which in turn means we cannot support it either.

*Sigh*. The era of 32-bit computing has more or less officially ended. *Plays taps.*
