### ISSUE TITLE
False open notification when replying

### ISSUE THREAD

**Issue by sparkbuzz** [Foundry376/Mailspring#1049]
##### Are there any related issues?

...

##### What operating system are you using?
MacOS High Sierra
...

##### What version of Mailspring are you using?
1.4.2
...

--

**Bug?**

Sometimes, when I open a tracked email, and reply to it, I get a false "New Open" notification. It seems like the body that is copied in the reply is triggering the notification. This only happens once per message, then the problem goes away.

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Using Gmail
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Open MailSpring, select a sent message, and reply to it. Note sometimes a "new open" notification appears.

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by pyeguy** [comment]
I'm getting this too on Ubuntu + gmail 

It's not always reproducible but often when I open an email I send  w/ tracking enabled a read receipt notification appears..  Is there someway to have persistent caching for just the 1x1px image on emails that you have sent?

**Comment by dinoboy197** [comment]
Yes, I also get this on Ubuntu linux 18.04.

**Comment by SDezineUK** [comment]
Not limited to just Gmail.  I am seeing this on Windows using various imap accounts.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
