### ISSUE TITLE
Dark Theme: Copy/pasting plain text from another message into composer applies white color

### ISSUE THREAD

**Issue by AF08** [Foundry376/Mailspring#1053]
When using the dark theme, every time I copied a body text from another mail (also from mailspring) to the one I'm writing, the font color changed to the color of the background (black) making it looks like an empty email when the recipient opened it. So I have to select the copied text, change the font color, every time before I press send. 
This behaviour does not happen when I'm using the white background theme

...

**Comment by bengotow** [comment]
Hey! Ahh this is a good catch - I'll see if we can address this soon. In the meantime, I think you can use `Shift-Control-V` to paste (paste and ignore formatting) and that'll strip the color automatically.

**Comment by AF08** [comment]
Cheers!

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!
