### ISSUE TITLE
gmail labels

### ISSUE THREAD

**Issue by lowercase00** [Foundry376/Mailspring#1057]
Hello.

Are there any plans to include Gmail labels on Mailspring?
Airmail "Starry Night XL" is probably the one that does it the best.

What I would like to see different is:
Possibility to resize the "from" and "subject column".
Possibility to change the font size.
Possibility to have labels and subject on the same line.

Thanks a lot.

##### Are there any related issues?

...

##### What operating system are you using?

...

##### What version of Mailspring are you using?

...

--

**Bug?**

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by phamhung77** [comment]
I can use Gmail labels without any problem. Do you face to any issue?

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—Mailspring already supports Gmail labels fairly completely. If you don't see labels, you may need to verify that you used the "Gmail" option to connect your account. Hope that helps!
