### ISSUE TITLE
Using mailspring as default mail client in Ubuntu 16.04

### ISSUE THREAD

**Issue by saminnet** [Foundry376/Mailspring#106]
Every time I tick the check box to have mailspring as default mail box, after going back to inbox it automatically unchecks itself.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—can you try updating to 1.0.4 which was just released and see if it resolves the problem for you? I believe 1.0.2 and earlier had a bug where the checkbox didn't work on Linux. Will re-open if this is still happening for you1
