### ISSUE TITLE
Feature: excluding labels in search

### ISSUE THREAD

**Issue by lundibundi** [Foundry376/Mailspring#1060]
##### What version of Mailspring are you using?

Latest Arch Linux [AUR package](https://aur.archlinux.org/packages/mailspring) 1.4.2

**Feature Request**

I'd want to have excluding labels search. i.e. in Gmail you can `!in:label` or `-in:label` that will show all emails without this label, but unfortunately I haven't found such feature in mailspring. Perhaps it is possible?

Thanks for the awesome email client.

**Comment by bengotow** [comment]
Hey! Hmm this is a good idea. Right now it's not possible to exclude search results using the `-` syntax, but I think it would be possible to add. I'll see what it'd take to do this!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—I implemented the "NOT" operator in search today (f6a008b) so this will work in the next release. One important caveat is that you have to say "A NOT B" (so your example of in:inbox NOT is:starred) will work fine, but you can't say "NOT is:starred" by itself. There are a lot of scenarios where a "not" query could return millions of results which wouldn't be ideal.

The next release is scheduled to go out tomorrow - stay tuned!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
