### ISSUE TITLE
SMTP: 503 AUTH command used when not advertised

### ISSUE THREAD

**Issue by leroyshirtoFH** [Foundry376/Mailspring#1061]
Hi,

When attempting to set up a new IMAP mailbox, SMTP fails to connect with the error `503 AUTH command used when not advertised`

Example Working SMTP settings from Thunderbird.

```
server: example.com
port: 587
connection security: STARTTLS
Auth mode: Normal Password
username: myUsername
```

I am trying to understand what is different. I am assuming its somthing to do with the auth mode?
Below are the connections logs with some sensitive info redacted.

```
----------SMTP----------
220 example.com (mrcorpsys101) ESMTP Mon, 03 Sep 2018 10:51:31 +0200
EHLO MY_HOSTNAME
250-example.com Hello MY_HOSTNAME [192.168.1.1]
250-SIZE 157286400
250-8BITMIME
250-PIPELINING
250-STARTTLS
250 HELP
STARTTLS
220 TLS go ahead
EHLO MY_HOSTNAME
250-example.com Hello MY_HOSTNAME [192.168.1.1]
250-SIZE 157286400
250-8BITMIME
250-PIPELINING
250 HELP
AUTH PLAIN bXlVc2VybmFtZTpteVBhc3N3b3Jk=
503 AUTH command used when not advertised

SMTP Last Response Code: 503

SMTP Last Response: AUTH command used when not advertised


mailsmtp Last Error Code: MAILSMTP_ERROR_BAD_SEQUENCE_OF_COMMAND

mailsmtp Last Error Location: 10

mailsmtp Last Auth Type: 0
```

##### What operating system are you using?
`Linux Antergos 4.18.5-arch1-1-ARCH`

##### What version of Mailspring are you using?
`1.4.2-f587b7b7`

**Bug?**

##### Is this an email sync or connection issue?
Connection issue

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP/SMTP

Thanks
Leroy

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - do you know what SMTP server software your host is using? ( It doesn't seem to say... ) This might be one of those scenarios where I need to go set up a VM with the same SMTP server.  I think that Mailspring is assuming that the response to the second EHLO (after it switches to SSL) will include "250-AUTH", but it looks like it's missing...

**Comment by bengotow** [comment]
Hey folks! Mailspring now supports SMTP without auth (though you must link the IMAP account with empty strings for SMTP username/password)

**Comment by tanisc** [comment]
Hi, I am getting a similar error. I select STARTTLS but it tries to use PLAIN.

```
504 5.3.3 AUTH mechanism PLAIN not available
SMTP Last Response Code: 504
SMTP Last Response: 5.3.3 AUTH mechanism PLAIN not available
```
The username has slashhhhhh "\". Can it be related?
