### ISSUE TITLE
Gmail Sync problem

### ISSUE THREAD

**Issue by Basher17** [Foundry376/Mailspring#1066]
Hi, since the last update I am facing a Gmail sync problem. To fix the error I tried to re-authenticate as a normal IMAP account using a Gmail app password but did not work. Then, I tried to allow insecure SSL connections and that option let me read and sync the mailbox but I cannot reply to emails.
Also my girlfriend is facing the same issue on a different PC, so I would exclude a PC-related issue.

P.s: we are both using AdGuard for Windows and Avast Premier, but disabling one or both of them does not seem to solve the issue.

##### Are there any related issues?

no

##### What operating system are you using?

Windows 10 1803 x64

##### What version of Mailspring are you using?

1.4.2-f587b7b7

--

**Bug?**

##### Is this an email sync or connection issue?

Yep, seems to be a Gmail sync issue

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Yep, Gmail accounts.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

<img width="607" alt="mailspring_issue" src="https://user-images.githubusercontent.com/33296576/45263329-9ae19780-b427-11e8-99ef-b0499ea5e2ae.png">

...

--

**Feature Request?**

...

**Comment by Huntermountain** [comment]
Ok, I hadn't thought about the AVAST scanner before seeing it mentioned here. Temporarily disabling the shields seems to solve the issue for now.

**Comment by bengotow** [comment]
Hey @Huntermountain — glad you got this sorted out! It's actually a little concerning that you get certificate errors without AVAST turned off - it sounds like AVAST may be tampering with the IMAP traffic. (Hopefully in the name of security or identifying spam / phishing?) I'll see if we can add this info to the knowledgebase.

**Comment by dustydingo** [comment]
This issue actually persists even if you temporarily disable the shields. If you subsequently try to login you will again have to disable the security and reconnect each of the services. We would probably have to exclude specific URLs, although I am not sure which ones are causing this interference.
