### ISSUE TITLE
mailspring cannot connect to non-gmail.com Gmail accounts

### ISSUE THREAD

**Issue by arsdragonfly** [Foundry376/Mailspring#1068]
##### Are there any related issues?

...

##### What operating system are you using?

...Manjaro Linux latest

##### What version of Mailspring are you using?

...1.4.2

--

**Bug?**

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...Gmail

logging in with my zheyushn@umich.edu account through Gmail Oauth2 doesn't work, showing Connection Error - Unable to connect to the server / port you provided. (IMAP)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by kdzapp** [comment]
Bump! When will this be released?

**Comment by arsdragonfly** [comment]
@kdzapp  Which version are you using? I'm using 1.5.3-420ce003 and it's been fixed for me already.

**Comment by kdzapp** [comment]
Whoops, it's working once updated! Thanks!

**Comment by bengotow** [comment]
x
