### ISSUE TITLE
XDG desktop file source

### ISSUE THREAD

**Issue by kirbyfan64** [Foundry376/Mailspring#1069]
Why is the source for the .desktop file (used on Linux) not inside this repository? I was going to submit some appstream metadata as a PR, but I noticed the XDG desktop file isn't present here, but it *is* present in the Linux packages.

**Comment by bengotow** [comment]
Hmm I think it's here: https://github.com/Foundry376/Mailspring/blob/master/app/build/resources/linux/mailspring.desktop.in. It just has a different extension because it's a template we modify at build time. Pull requests definitely welcome!

**Comment by kirbyfan64** [comment]
Ah, sorry!
