### ISSUE TITLE
Mailspring does not launch in background on Linux

### ISSUE THREAD

**Issue by krupenja** [Foundry376/Mailspring#1070]
##### Are there any related issues?

No.

##### What operating system are you using?

Manjaro Linux, fully updated, kernel 4.18.6-1.

##### What version of Mailspring are you using?

1.4.2-f587b7b7

**Bug?**

##### Is this an email sync or connection issue?

No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N/A.

**Steps to reproduce**

1. Install Mailspring.
2. Try launching Mailspring using `mailspring -g --args --background`.

Mailspring launches in foreground even though it should launch in background.

**Comment by bengotow** [comment]
Hey! I'm not sure if this applies, but you'll need to add an account to mailspring before it'll launch in the background. I think if it's launching to the "welcome assistant", it always launches in the foreground. Also could you try just `mailspring --background`? That works for me on Ubuntu linux.

**Comment by krupenja** [comment]
Yep, confirm that works with `mailspring --background`. Closing this issue.

**Comment by dinnymate** [comment]
Sorry, but this is still not fixed. It actually never worked. It opens a window even with the `--background` flag. And it's not the welcome assistant.

**Comment by emanuelserpa** [comment]
not working here
