### ISSUE TITLE
Email body being display incompletely and incorrectly

### ISSUE THREAD

**Issue by appukuttan-shailesh** [Foundry376/Mailspring#1072]
Email body not being displayed completely. The body of the text seems to be quite arbitrarily cut down. I have attached snapshots of the email being displayed on MailSpring and on Thunderbird. When I re-sent the email via Thunderbird to my own account, the email now displayed properly in MailSpring.

##### Are there any related issues?
Note: This is different from the issue reported here: https://github.com/Foundry376/Mailspring/issues/802

...

##### What operating system are you using?
Ubuntu 16.04 LTS 64-bit

##### What version of Mailspring are you using?
MailSpring 1.4.2

--
**Bug?**

##### Is this an email sync or connection issue?
No

...
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not sure
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Email displayed on MailSpring:
------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/24866517/45548913-360eae80-b826-11e8-8676-5efe86c53760.png)
------------------------------------------------------------------

Same email opened via Thunderbird (had to mark out parts):
------------------------------------------------------------------
![screenshot from 2018-09-14 13-53-38](https://user-images.githubusercontent.com/24866517/45548942-52125000-b826-11e8-9ac1-669b4d529d50.png)
------------------------------------------------------------------
...

**Comment by bengotow** [comment]
Wow this is super interesting - the text actually appears with large chunks missing? It seems like this must be a problem with the HTML of the email being mangled or containing CSS that is resulting in it being hidden somehow. If the email isn't too private, could you forward it to me at ben@foundry376.com from Thunderbird? Would be super helpful to see what the source of the message looks like and see if there's anything odd in the HTML right after "providing some"

**Comment by appukuttan-shailesh** [comment]
Hope you received my email (sent it the same day) and have some leads on the issue.

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
