### ISSUE TITLE
Excel Mime types are sent as application/octet-stream

### ISSUE THREAD

**Issue by peterhatz** [Foundry376/Mailspring#1073]
I've noticed attaching Excel files (xls and xlsx) are sent as `application/octet-stream` whereas other mail clients send as `application/vnd.ms-excel` and `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` (respectively). Not sure if there is a "standard" or are developers free to choose?

##### Are there any related issues?
I couldn't find any.

##### What operating system are you using?
Ubuntu/Pop!_OS 18.04

##### What version of Mailspring are you using?
1.4.2

--

**Bug?**

##### Is this an email sync or connection issue?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![excelattachedfilemimetype](https://user-images.githubusercontent.com/13877079/45584493-acd7a480-b917-11e8-8f1c-b86701049603.png)

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
No

**Comment by bengotow** [comment]
Hey! This is pretty interesting - do you know if this blocks some recipients from being able to open the file or is just a little odd? I'll leave this open for a bit and see if we can tie it to any bug reports.

**Comment by peterhatz** [comment]
Hey Ben,

Thanks for getting back to me. Basically, I've created a Service that allows people to email in Excel files and it creates a Cloud Datawarehouse in AWS for them automatically.

Part of it looks at the Mime header to figure out the file type so it can handle it correctly. Some email clients set it to the Office Mime types though I guess I'll have to be creative :-) and figure out how to process correctly using "Content-Type: application/octet-stream".

Cheers,
Peter

On Sep 18 2018, at 4:09 am, Ben Gotow <notifications@github.com> wrote:

Hey! This is pretty interesting - do you know if this blocks some recipients from being able to open the file or is just a little odd? I'll leave this open for a bit and see if we can tie it to any bug reports.
