### ISSUE TITLE
Is Mailspring dead (again)?

### ISSUE THREAD

**Issue by purefan** [Foundry376/Mailspring#1075]
I'm asking @Foundry376 since I haven't seen any reply from them to the issues, if they are not managing this project then who is? 

I think it has great potential but perhaps they're understaffed for this, if that's the case I suggest they grant access to more users so we can actually move this project forward, right now the documentation is still a copy-paste with broken links and a lot of internal information is missing, just check the Issues section and you will see that people are interested and trying out Mailspring but hitting walls and finding no help from the creators

**Comment by synsa** [comment]
I agree 100% with your statements @purefan. This project has a lot of potential and I can see that there are a number of potential contributors that would love to help push this project forward -- myself included.

**Comment by bengotow** [comment]
Hey folks! Sorry, just getting back from vacation today—gonna take a day or two to dig though all the issues, but it should be back under control soon. @purefan @synsa if you could file issues with development questions I'd be happy to answer them (or better, add info to the documentation!) Would definitely like to have more folks able to contribute! I've been tagging things as "Good First Issues", will see if I can do that a bit more!

**Comment by purefan** [comment]
Thanks @bengotow ! I hope you had a good time :)
