### ISSUE TITLE
Moving from drafts folder back to inbox brings up the undo option for last action

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#108]
##### Are there any related issues?

...

##### What operating system are you using?
MacOS 10.12.6

##### What version of Mailspring are you using?
1.0.3

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Start at inbox
Go to drafts folder
Go back to inbox
No matter how long ago last action was performed on a thread, black box to undo it pops back up

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey good catch! That's a fun one. All this reactive programming making things too declarative. Should be fixed in the next release.
