### ISSUE TITLE
invalid UTF-8 byte error with Yandex on Mac with 1.4.2 version.

### ISSUE THREAD

**Issue by ovgeorge** [Foundry376/Mailspring#1093]
The invalid byte corresponds to pound symbol £, but I could not find corresponding offending letter in my folder. 

Here logs:

98839 [2018-09-25 22:30:12.428] [main] [info] ------------- Starting Sync (*******@yandex.ru) ---------------
98839 [2018-09-25 22:30:12.454] [background] [info] Marking all folders as `busy`
98839 [2018-09-25 22:30:12.454] [metadata] [info] Metadata delta stream starting...
98839 [2018-09-25 22:30:12.456] [background] [info] Syncing folder list...
98839 [2018-09-25 22:30:27.430] [metadataExpiration] [info] Scanning for expired metadata
98839 [2018-09-25 22:30:27.430] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
98839 [2018-09-25 22:30:42.647] [background] [info] Sleeping after exception: {"debuginfo":"syncFoldersAndLabels - fetchAllFolders","key":"ErrorConnection","retryable":true,"what":"std::exception"}
98839 [2018-09-25 22:32:42.652] [background] [info] Marking all folders as `busy`
98839 [2018-09-25 22:32:42.656] [background] [info] Syncing folder list...
98839 [2018-09-25 22:32:42.846] [background] [info] Syncing folder list...
98839 [2018-09-25 22:32:42.875] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 14634, Heavy: false
98839 [2018-09-25 22:32:42.905] [background] [info] - remote=0, local=0
98839 [2018-09-25 22:32:42.939] [background] [info] syncFolderUIDRange for Sent, UIDs: 4646 - 5050, Heavy: false
98839 [2018-09-25 22:32:42.974] [foreground] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 14634, Heavy: false
98839 [2018-09-25 22:32:43.003] [foreground] [info] - remote=0, local=0
98839 [2018-09-25 22:32:43.017] [foreground] [info] Idling on folder INBOX
98839 [2018-09-25 22:32:43.097] [background] [info] - remote=400, local=400
98839 [2018-09-25 22:32:43.136] [background] [info] syncFolderUIDRange for Drafts, UIDs: 1 - 5440, Heavy: false
98839 [2018-09-25 22:32:43.167] [background] [info] - remote=8, local=8
98839 [2018-09-25 22:32:43.189] [background] [info] syncFolderUIDRange for Trash, UIDs: 1 - 8571, Heavy: false
98839 [2018-09-25 22:32:43.228] [background] [info] - remote=228, local=228
98839 [2018-09-25 22:32:43.247] [background] [info] syncFolderUIDRange for Spam, UIDs: 1 - 2256, Heavy: false
98839 [2018-09-25 22:32:43.277] [background] [info] - remote=36, local=36
98839 [2018-09-25 22:32:43.290] [background] [info] syncFolderUIDRange for Archives|2010, UIDs: 1 - 77, Heavy: false
98839 [2018-09-25 22:32:43.321] [background] [info] - remote=76, local=76
98839 [2018-09-25 22:32:43.337] [background] [info] syncFolderUIDRange for Archives|2011, UIDs: 1 - 562, Heavy: true
98839 [2018-09-25 22:32:46.771] [background] [info] - remote=561, local=482
98839 [2018-09-25 22:32:46.776] [background] [critical] 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.316] invalid UTF-8 byte at index 1: 0xA3
 ***

98839 [2018-09-25 22:32:46.835] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** in mailsync  nlohmann::detail::serializer::dump_escaped(__1::string const&, bool)
 *** in mailsync  nlohmann::detail::serializer::dump(nlohmann::basic_json const&, bool, bool, unsigned int, unsigned int)
 *** in mailsync  nlohmann::detail::serializer::dump(nlohmann::basic_json const&, bool, bool, unsigned int, unsigned int)
 *** in mailsync  nlohmann::detail::serializer::dump(nlohmann::basic_json const&, bool, bool, unsigned int, unsigned int)
 *** in mailsync  nlohmann::detail::serializer::dump(nlohmann::basic_json const&, bool, bool, unsigned int, unsigned int)
 *** in mailsync  nlohmann::basic_json::dump(int, char, bool) const
 *** in mailsync  MailModel::bindToQuery(SQLite::Statement*)
 *** in mailsync  Message::bindToQuery(SQLite::Statement*)
 *** in mailsync  MailStore::save(MailModel*, bool)
 *** in mailsync  MailProcessor::insertMessage(mailcore::IMAPMessage*, Folder&, long)
 *** in mailsync  MailProcessor::insertFallbackToUpdateMessage(mailcore::IMAPMessage*, Folder&, long)
 *** in mailsync  SyncWorker::syncFolderUIDRange(Folder&, mailcore::Range, bool, __1::vector*)
 *** in mailsync  SyncWorker::syncNow()
 *** in mailsync  runBackgroundSyncWorker()
 *** in mailsync  main::$_5::operator()() const
 ***

**Comment by purefan** [comment]
looks like a bug in mailsync, only @bengotow (sorry to dump even more work on you man xD ) has access to that part of Mailspring.

Do any of your folders have any accentuated characters?

**Comment by ovgeorge** [comment]
No they don't have any accentuated characters, although it may occur in mail. How can I help you to debug it (or, if it matter of, say, only one letter) figure out which one and delete it?

**Comment by purefan** [comment]
From my end I think there's nothing I can check since the error happens in mailsync, I do appreciate your offer though, its people like you that drives us :)

**Comment by ovgeorge** [comment]
@purefan I could debug it myself if you could point me towards some manual.

**Comment by bengotow** [comment]
Hey folks - just a quick heads up that the `invalid UTF-8 byte at index 0` bug will be fixed in the next release this week. This turned out to be a tricky one and the app doesn't retry the connection because the error is actually thrown within the error handling logic for the sync worker. Stay tuned!

**Comment by bengotow** [comment]
Hey folks! This shipped today in 1.7.2 - you can download the update from our website at getmailspring.com/download or choose "Check for Updates" in the app's menu. Enjoy the update!
