### ISSUE TITLE
Linux download links not working on https://getmailspring.com

### ISSUE THREAD

**Issue by kapad** [Foundry376/Mailspring#11]
The links for Linux .dep and .rpm packages on the website don't work. 

If mailspring will only be distributed using snap, then maybe, the page needs to be more clear. I thought clicking the .deb icon, will download the .deb package. 
![image](https://user-images.githubusercontent.com/2017355/31153843-f70c5e78-a8c0-11e7-8197-2e2b2486279a.png)

**Comment by V3XATI0N** [comment]
It says the Snap is coming soon, but I hope that doesn't mean to imply that .deb packages /aren't/ coming soon, I use a deb-based distro that doesn't support snaps.

**Comment by ldartez** [comment]
none of the links/images work. however, the download URLs are https://updates.getmailspring.com/download?platform=linuxDeb for debian and https://updates.getmailspring.com/download?platform=linuxRpm for redhat based systems. The RPM url works, though the icon does not work. The .deb (the one i need!) give me an error: This XML file does not appear to have any style information associated with it. The document tree is shown below.

**Comment by ldartez** [comment]
Okay, the link to the deb package seems to actually be: 
https://mailspring-builds.s3.amazonaws.com/client/20839f9b/linux/mailspring-1.0.0-amd64.deb

The "linuxDeb" link above points to _almost_ the correct URL; the 'M' in mailspring should not have been capitalized.

**Comment by kapad** [comment]
@ldartez The workaround works. Thanks :+1:

**Comment by bengotow** [comment]
Hey folks! For the moment I've taken down the builds above—linux builds are coming soon but aren't quite ready yet. I'm still creating binaries and testing them (so there /are/ builds on S3) but there are some pretty significant known issues on different linux distros. Stay tuned! Should only be another day or two.

**Comment by ldartez** [comment]
I just want to note that the two URL's in my first comment above now work again and point to the respective 1.0.1 versions of the binaries.

**Comment by bengotow** [comment]
Hey folks—I've gone ahead and put the links on the download page (so you can download .deb and .rpm packages for Linux.) I was hoping to wait until we had a Snapcraft package, because it will enable autoupdates for Linux users. Currently, you need to come back to the downloads page and get it again when a new version is released. The Snap is taking more time than I expected to get working, so this will do for now! Gonna go ahead and close this.
