### ISSUE TITLE
[Arch Linux] GMX brokes gmail with error while syncing

### ISSUE THREAD

**Issue by onliniak** [Foundry376/Mailspring#1102]
##### Are there any related issues?

Yes, but any of them help me resolve problem. 

##### What operating system are you using?

Arch Linux with kernel 4.18.9

##### What version of Mailspring are you using?

1.4.2-1

##### Is this an email sync or connection issue?

Email sync

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

GMX

##### Bug 

1. Create new account (Mailspring ID)
2. Add new Gmail account via browser (Gmail or G Suite)
3. Wait few minutes for sync.
4. All works.
5. Add new GMX account (via icon)
6. Error while syncing (gmx only)
6.1. What ? I use both accounts in RainLoop webmail and Thunderbird and all works.
7. Delete gmx account.
8. Add this same account via imap.
9. Error while syncing …
10. Quit and open Mailsprings 
11. I cannot sync with gmail.
12. Go to accounts Edit → Preferencer → Accounts
13. Mailsprings is broken, I need delete cache and start from the beginning.

**Comment by franco27** [comment]
I am with the Windows version and I have a GMX account.  I do not have the problems you describe.  With the Windows version, my GMX mail account is working properly.  if it helps in the resolution!

**Comment by onliniak** [comment]
For me this is problem with specific OS too. Exactly with way how Arch Linux implement libcrypt. But I am not expert in UNIX-like systems.

**Comment by onliniak** [comment]
//I will edit later
//English is not my native language

I mean → It works when I auth via Oauth (Google apps), but not works when I use IMAP. In log file I have only gmail. When I try create new account something corrupt my Mailspring. So I forget about something library or I have wrong permissions. Permissions are OK (allow read/write for everybody). Library … everyone in Linux-like issues speaks about libsecret (no libcrypt), so here is problem ? Or install script (I install via AUR) ? Tomorrow I try diffrent way to install.

We know, that this isn't problem with Mailspring/GMX itself (thanks for reply) because Windows (another OS) is OK. Also I know, that I am able to connect with another mail app, so this is not problem with my GMX account configuration.

Tomorrow I will try connect to Gmail or another mail via IMAP (not app). Propably they will corrupt my Mailspring too. 

Now I have to looking for more info about Mailspring directory/folder/cache itself … and IMAP.

**Comment by franco27** [comment]
6 months or 1 year ago I installed Mailspring on Linux Ubuntu. I don't remember having this problem. it was before the redesign of the message editor. I don't know the version number anymore.

**Comment by onliniak** [comment]
<a href="https://i.imgur.com/2BzyG8o.png">
  <img src="https://imgur.com/2BzyG8ol.png" />
</a>

it could help …

**Comment by onliniak** [comment]
OK, fixed in 1.5.6-1
