### ISSUE TITLE
Linux (Fedora and Ubuntu) segfault on start up on glibc 2.28

### ISSUE THREAD

**Issue by german-rios-gonzalez** [Foundry376/Mailspring#1108]
Hi, please update to electron 2.0.8 or above to avoid this issue #https://github.com/electron/electron/issues/13972 currently all electron based apps with version bellow to 2.0.8 are broken for the next version of Fedora (29) and Ubuntu

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—I'll see if I can ship the next version on 2.0.11. Stay tuned 👍

**Comment by sgerner** [comment]
@Al2Me6, [Here's a DEB](https://drive.google.com/open?id=1FyFPZo_s8kZGnw0JfXplQDS3XZ0PpBrQ) built with electron 2.0.11 while you're waiting. Sorry, if you're on a Red Hat distro, you'll have to build it yourself, but it's fairly straightforward. Just clone the repo, follow the [instructions](https://github.com/Foundry376/Mailspring/blob/master/CONTRIBUTING.md), and run 'npm run-script build'.
