### ISSUE TITLE
[Feature Request] Ability to change outgoing email / composer font

### ISSUE THREAD

**Issue by bengotow** [Foundry376/Mailspring#111]
From support: One of the things that was incredibly frustrating with Nylas Mail was the inability to set an outgoing message font. In particular, it's quite a nuisance when communicating with users who currently work using Microsoft Outlook. Is there a plugin to set the outgoing message font or a way to set this within Mailspring. I'd just like to make sure a sans-serif Helvetica or Arial is used.

**Comment by bengotow** [comment]
Version 1.1.0 shipped today which includes an overhauled composer and support for popular fonts!  You can't choose any font, just fonts that are common and likely to be installed on your recipient's computer (For now the options are the same as on Gmail.)

You can't set a font as the default for new emails, but honestly I'm not sure that's a great idea - users should really allow their emails to be read in the font-of-choice of the recipient rather than specifying one all the time. That said, if it's a popular request it'd be a good starter issue for someone looking to contribute!

**Comment by amarendra** [comment]
@bengotow Right. In fact that's one of the first things I look in a email client whether I can see all the emails (IN/OUT both) in my favourite font which is EB Garamond (Gmail's Garamond font is a mess even in web gmail interface - with its spacing all over and the normal size being too small, medium too big).

Would love to see this addition.

**Comment by tmanok** [comment]
GMail supports 11 fonts, but it would be nice to see a method of using system fonts (MacOS currently has about 151 **without counting styles** as of Mojave and HTML5 supports about 88 **with counting styles**).

**Comment by glenn2223** [comment]
> You can't set a font as the default for new emails, but honestly I'm not sure that's a great idea - users should really allow their emails to be read in the font-of-choice of the recipient rather than specifying one all the time. That said, if it's a popular request it'd be a good starter issue for someone looking to contribute!

Not so much fussed about forcing it upon the recipient, just what I see as I'm typing it. Maybe, next level, an option to set a default font across my Mailspring (when one isn't forced upon me in an email by the sender 😄)
