### ISSUE TITLE
Mail Rules matches name, not email.

### ISSUE THREAD

**Issue by KristerV** [Foundry376/Mailspring#1110]
Are there any related issues? no
What operating system are you using? Arch Linux
What version of Mailspring are you using? 1.4.2
Bug
Is this an email sync or connection issue? no
Is the issue related to a specific email provider (Gmail, Exchange, etc.)? no

### What I'm trying to do

I have a @krister.ee hosted by mailbox.org. If I get an email it's addressed to either of the 3:

- anything@krister.ee
- My Name <anything@krister.ee>
- Random Person <random@othercompany.com>

"Anything" means I've got a catch-all set up.

So I want to create a rule that moves any email not containing krister.ee as a recipient to the spam folder.

### How I did it

I create a mail rule and use "Process entire mailbox" to see results:

![image](https://user-images.githubusercontent.com/2750622/46458050-2c40f100-c7bd-11e8-8a3d-dcb41f09a1cd.png)

### What I expected

- **inbox** anything@krister.ee
- **inbox** My Name <anything@krister.ee>
- **moved** Random Person <random@othercompany.com>

### What actually happened

- **inbox** anything@krister.ee
- **moved** My Name <anything@krister.ee> - WRONG
- **moved** Random Person <random@othercompany.com>

### What else I've tried

- Searching the knowledgebase
- Googling for any tips
- Using "Macthes expression" with negative lookahead regex (btw, there is NO info whatsoever if this field is actually for regex)
- Other combinations of rules

### What I think is the bug

Seems to me like the rule matches correctly only if the To field has no name (only email). If there is a `Name Infront <of@email.com>` then the name is matched, but not email..

**Comment by bengotow** [comment]
Hey! Thanks for filing this—I dug in to this today and it looks like you're definitely right. I think the `does not contain` expression is currently implemented as `any of the To components does not contain` , when it should read `all of the To components do not contain`. So if a name is present, and the name doesn't match while the email does, it returns `true`.

I'll get this fixed today. 👍  Thanks for the detailed bug report!

**Comment by bengotow** [comment]
Hey! The fix for this shipped in v1.5.4 this afternoon. Mailspring should auto-update in the next few hours and you can also download the update directly from https://getmailspring.com/download. Happy new years!
