### ISSUE TITLE
Mailspring Pro Annual Upgrade Issue

### ISSUE THREAD

**Issue by ithinkmatt** [Foundry376/Mailspring#1111]
##### Are there any related issues?

**Not that I could fine.**

...

##### What operating system are you using?

**Windows 10**

...

##### What version of Mailspring are you using?

**1.42**

...

--

#####Bug?

**I am unable to change to an annual subscription. I can only pay monthly and would like to move from Free to Pro Paid Annually. It would be more beneficial for Mailspring to allow annual payments to users without having a manual process that involves Mailspring support. Especially, with having a small team that can't respond to assist in completing these upgrades.**

##### Is this an email sync or connection issue?

**No**

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

**No**

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

**Yes, if you use Mailspring you will find no easy option to upgrade to annual.**

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by LeBaux** [comment]
Fact that question about **how to send developers money** is unanswered for a month is worrisome... to say the least. I’m contemplating premium too, but the state of github issues is exactly assuring.

**Comment by ithinkmatt** [comment]
The developer responded on Twitter on October 6th. His response was something like: I'll see if I can add the formal support of annual payments into the next version. Manual processing annual payments was creating some other issues.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
