### ISSUE TITLE
Contact Sidebar @gmail.com Addresses

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#1114]
##### Are there any related issues?

Don't think so.
...

##### What operating system are you using?
Linux desktop 4.18.9-1-MANJARO #1 SMP PREEMPT Thu Sep 20 04:58:28 UTC 2018 x86_64 GNU/Linux
...

##### What version of Mailspring are you using?
1.4.2-1
...

--

**Bug?**

##### Is this an email sync or connection issue?
No

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
anyone with @gmail.com email

![image](https://user-images.githubusercontent.com/25718989/46570689-90290c80-c9ab-11e8-9712-a817b5415b5d.png)

...

--
If a user has an @gmail.com email and the contact sidebar is used, we get information for google.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—this is definitely a bug. Will get this fixed in the next release!

**Comment by bengotow** [comment]
Hey! The fix for this shipped in v1.5.4 this afternoon. Mailspring should auto-update in the next few hours and you can also download the update directly from https://getmailspring.com/download. Happy new years!
