### ISSUE TITLE
Block tracking from Streak CRM (failed)

### ISSUE THREAD

**Issue by noirrak** [Foundry376/Mailspring#1115]
Hello,
Blocking tracking for Streak CRM does not work correctly. Is it possible to fix this?
![45346](https://user-images.githubusercontent.com/20505787/46573961-bf844d00-c99c-11e8-9097-f165753b0ef3.jpg)

Tracking code from Streak CRM:
```
<div hspace=3D"streak-pt-mark" style=3D"max-height:1px"><img alt=3D""=
 style=3D"width:0px;max-height:0px;overflow:hidden" src=3D"https://mailfoog=
ae.appspot.com/t?sender=XXXXXXXXXXXXXXXXXXXXXXXXXXXX&amp;type=3D=
zerocontent&amp;guid=XXXXXXXXXXXXXXXXXXXXXXXXXX"><font color=3D=
"#ffffff" size=3D"1">=E1=90=A7</font></div>
```

**Comment by bengotow** [comment]
Hey! This actually looks like it's working correctly? Are you seeing that the tracking is occurring even if you don't click "Show Images"? That bar appears when you disable automatic image loading and Streak will only be able to track you if you click "Show Images"

**Comment by bengotow** [comment]
Hey folks! I know it's been a while since this one was filed. I signed up for Streak and sent myself a tracked email (source below) and verified that Mailspring now blocks the image from loading correctly.

```
<div dir="ltr">This is just a test<div><br></div><div>Here&#39;s a link <a href="http://appstoreconnect.apple.com/">http://appstoreconnect.apple.com</a></div><div><br></div><div>Ben</div></div><div hspace="streak-pt-mark" style="max-height:1px"><img alt="" style="width:0px;max-height:0px;overflow:hidden" src="https://mailfoogae.appspot.com/t?sender=abWFya0Bmb3VuZHJ5Mzc2LmNvbQ%3D%3D&amp;type=zerocontent&amp;guid=96e35e14-986f-4196-807a-728613e3b09e"><font color="#ffffff" size="1">ᐧ</font></div>
```
