### ISSUE TITLE
office 365 account not working on Mailspring

### ISSUE THREAD

**Issue by cnazario3** [Foundry376/Mailspring#1116]
I'm using Ubuntu 18.04 and for some reason while adding my o365 account Im getting an error message.

----------IMAP----------
* OK The Microsoft Exchange IMAP4 service is ready. [QgBOADYAUABSADAANQBDAEEAMAAwADAANwAuAG4AYQBtAHAAcgBkADAANQAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
2 LOGIN "christian.nazario.rodriguez@disney.com" *********
2 NO LOGIN failed.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - unfortunately, this looks like a pretty generic password error. Could you try setting up an Office 365 app password and see if that does the trick? https://support.office.com/en-us/article/create-an-app-password-for-office-365-3e7c860f-bda4-4441-a618-b53953ee1183

**Comment by cnazario3** [comment]
That's the problem it looks like a password issue but no, I can log in with my corporate password in the web page

**Comment by bengotow** [comment]
I think this will be resolved by #258

**Comment by xsv-root** [comment]
Issue not resolved.

**Comment by awvalenti** [comment]
Office 365 app password worked for me! Thanks!

It would be nice mentioning that step on this screen:

![image](https://user-images.githubusercontent.com/834921/82359564-6c7ad480-99de-11ea-9450-b42e17e3ecb0.png)
