### ISSUE TITLE
[Feature Request] Option to disable smooth scrolling

### ISSUE THREAD

**Issue by alexozer** [Foundry376/Mailspring#1125]
I'm using Mailspring 1.4.2 on Arch Linux.

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
Most other webmail technically.

It would be nice if you could disable smooth scrolling like in chromium and firefox. I usually turn this off in web browsers since I find the inertia annoying and find two-finger scrolling with a touchpad to be perfectly smooth anyway.

**Comment by bengotow** [comment]
Hey! OK - so I'm not sure how offhand, but this /should/ be possible. If you run Mailspring from the command line, arguments you pass fall through to Chromium / Electron, so if you have a Chromium flag you use, you may be able to launch Mailspring with it.

Just to sanity check, you can try `mailspring --lang=de` — I'm working on a bunch of localization stuff for the next release, but in the current shipping version you should see dates start to use the German month names:

<img width="123" alt="image" src="https://user-images.githubusercontent.com/1037212/46996728-8fdaf080-d0d2-11e8-8216-2079be3abeca.png">

**Comment by bailtree** [comment]
the flag is --disable-smooth-scrolling :)

**Comment by CodeMouse92** [comment]
I've created a question and answer on our new knowledge base:

https://community.getmailspring.com/t/disable-smooth-scrolling/773

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
