### ISSUE TITLE
Error on IIS in Asp.net Core 2.1

### ISSUE THREAD

**Issue by satishgupta4s** [Foundry376/Mailspring#1132]
When  publish asp.net core 2.1 project and upload on iis server then error occurs ....

Error.
An error occurred while processing your request.
Request ID: 0HLHH0B0DTGAH:00000001

Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.

Development environment should not be enabled in deployed applications, as it can result in sensitive information from exceptions being displayed to end users. For local debugging, development environment can be enabled by setting the ASPNETCORE_ENVIRONMENT environment variable to Development, and restarting the application.

Please solve problem

**Comment by bengotow** [comment]
Hey! Thanks for filing this, I don't think this issue is related to Mailspring? This app doesn't use ASP.NET and this seems to be an IIS specific deployment issue.
