### ISSUE TITLE
Mailspring missed some new email notification and cannot display each email individually

### ISSUE THREAD

**Issue by linuxiaobai** [Foundry376/Mailspring#1134]
##### Are there any related issues?

...Not sure

##### What operating system are you using?

...Ubuntu 16.04.5

##### What version of Mailspring are you using?

...1.4.2 (snap)

--

**Bug?**

##### Is this an email sync or connection issue?

...Yes

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...Exchange

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...Not applicable

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

1. The Mailspring organizes emails by conversation by default. But I want all the emails displayed individually. I know there is a expand conversation button, but I need a global setting to change.
2. I added some rules in outlook 2013 so that some specific emails will come to my personal folder (eg. project xxxx). When I received such emails, Mailspring seems never give notification. But when a new email come into inbox folder, I receive the notification.
Thanks in advance for your help.

**Comment by bengotow** [comment]
Hey! Mailspring only supports threaded display and only runs notifications for messages that arrive in your inbox. Sorry for the hassle!
