### ISSUE TITLE
Update Plugin Development Page

### ISSUE THREAD

**Issue by Samuel3** [Foundry376/Mailspring#1137]
##### Are there any related issues?

...

##### What operating system are you using?

Windows 10 x64 1803

##### What version of Mailspring are you using?

1.4.2-f587b7b7

--

**Bug?**

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Today I wanted to write a custom plugin for MailSpring but the documentation is hopeless out of date. Can you please update this section? Creating and importing a new plugin does really nothing.

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

As far as I know has Thunderbird a good documentation for writing plugins.

**Comment by retorquere** [comment]
Is there an overview of Mailspring plugins so I could see which would be the best launching board?

**Comment by jporminal** [comment]
Hi. I know the plugin documentation is still outdated but are there any working Mailspring plugins I could look into?  I tried to follow `phishing-detection` plugin but I couldn't get it to work.

**Comment by CodeMouse92** [comment]
The new home for this sort of thing will be the official plugin development discussion board here: https://community.getmailspring.com/c/development/plugins-dev/17

Plugins can be shared here: https://community.getmailspring.com/c/plugins/8

We also have this feature suggestion: https://community.getmailspring.com/t/plugin-theme-catalog/318

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
