### ISSUE TITLE
[Feature Request] Add 'Hide menu bar' menu item

### ISSUE THREAD

**Issue by Andrewsudarikov** [Foundry376/Mailspring#114]
##### Are there any related issues?

...

##### What operating system are you using?
Elementary OS

##### What version of Mailspring are you using?
1.0.3

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No plugins

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No, it concerns application's interface, not email accounts. 

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Hidden menubar in the previous (1.0.2) version was great for sleek Elementary OS look. Now it is impossible to hide, so it is a bit of visual clutter some people will find unnecessary. Let the user decide if he wants to see the menubar all the time by creating a menu item or a checkbox in the Preferences, just like Firefox and Thunderbird do.

**Comment by JunnanZ** [comment]
Second this. Is there any way to hide menu bar? There is even a menu bar on message composing window.

**Comment by bengotow** [comment]
Haha sorry guys–this was just changed yesterday by folks who were confused that it didn't show the menu bar on Linux. I guess this is highly distro-specific.  We probably need to make the flag changed in https://github.com/Foundry376/Mailspring/pull/84 saved into the app's configuration, or intelligently selected based on your distro.

**Comment by JunnanZ** [comment]
@bengotow Thanks. For now, is there a hack that can remove the menu bar?

**Comment by lamarios** [comment]
I'm interested in this one too. If there's a temporary work around that'd be great.

**Comment by rhoconlinux** [comment]
Hey guys, sorry but this is not distro specific. Mailspring shows the same behavior in Ubuntu, Suse, Elementary and Arch, as far as I checked. There is no hide menu option, so the feature request is valid. 

Is there any clue on how to hack this? Any dev that may  throw us a hint?

Thanks!

**Comment by atersolis** [comment]
You just need to toggle the developer tools (Ctrl+Alt+I) and paste this in the console : 
`require('electron').remote.getCurrentWindow().setAutoHideMenuBar(true)`
Then you can toggle the menu bar using Alt.
You need to do this everytime you restart Mailspring though.

**Comment by atersolis** [comment]
You can make this permanent by using a plugin :
create a folder for the plugin : 'hide-menu-bar'
create a file called 'package.json' in that folder : 
```` json
{
  "name": "hide-menu-bar",
  "main": "./main",
  "engines": {
    "mailspring": ">=1.0.8"
  },
  "description": "Plugin for mailspring : hide the menu bar (Alt to toggle)",
  "license": "MIT"
}
````

then create a file called 'main.es6' in the same folder :  
```` javascript
import electron from 'electron';

export function activate() {
	let win = electron.remote.getCurrentWindow();
	win.setMenuBarVisibility(false);
	win.setAutoHideMenuBar(true);
}
````

then in Mailspring : 
Developer >> Install plugin 
and select the 'hide-menu-bar' folder.

**Comment by ponyesteves** [comment]
Thanks for posting the plugin it works great for main window. I would like to do the same for the mail composer window. 
I've tried some alternatives but didn't work, for example this one. I use blur because I didn't find an event for window.open or similar.  
In my example seems like it always grab de main window. 
 

```js
import electron from 'electron';

export function activate() {
  hideMenu(true)
}
const hideMenu = (mainWindow) => {
  [electron.remote.getCurrentWindow()]
  .map(win => {
    win.setMenuBarVisibility(false)
    win.setAutoHideMenuBar(true)
    mainWindow ? win.addListener('blur', () => hideMenu(false)) : null
  })
}
```


![image](https://user-images.githubusercontent.com/4960589/33993345-d9d49df8-e0b4-11e7-8eac-c5515425bfab.png)

**Comment by bengotow** [comment]
Hey folks - in the next release I'm adding a preference for this, as well as a new option to use the "right corner hamburger menu" and completely custom window controls. I think this will improve things a lot, especially on distros like Elementary where the standard window frame is very tall.

New options:
<img width="958" alt="image" src="https://user-images.githubusercontent.com/1037212/34469806-1311b00e-eedb-11e7-9ca7-e922b4725a55.png">

"Right corner hamburger" option - note the system window frame is not used at all, so it'll look like this (or your selected theme) on all Linux distros:
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/1037212/34469818-2f88a3f0-eedb-11e7-999c-40a51a50dece.png">

**Comment by johnathon-b** [comment]
Is there an easier way to reset Mailspring without re-install? I was impatient and tried the plugin model which broke Mailspring. Wondering if there is an easier way to revert for further skin and plugin dev.

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and a lot of other small improvements. You can grab the latest version from https://getmailspring.com/download.

@johnathon-b you should be able to uninstall the plugin by removing `%APPDATA%\Mailspring\packages` and re-launching the app, but keep in mind the app keeps running in the background to provide notifications, so you have to exit it from the menu and not just close the window. Hope that helps!

**Comment by lamarios** [comment]
Hi,

Unfortunately the release version doesn't work for me (i3wm / compton / mate). The menu bar is still showing.

 The small plug in showed in earlier comments by @atersolis work fine though.

**Comment by cbrasser** [comment]
I'm having the same issue with xfce4, the option provided in the preferences does not work, setting it manually via the js console does.

**Comment by dinhokusanagi** [comment]
this app has a bug in the taskbar icon gets two dots
![mail](https://user-images.githubusercontent.com/43162113/45606608-e940f880-ba1c-11e8-9575-f5971ddafff4.png)

**Comment by ponyesteves** [comment]
Hi @bengotow, 
                       right-hand menu is a great option for Linux users. But there might be performance issues since it takes at least 4 more times to open the composer vs the default menu. The auto-hide option works fine on the main frame but not on the composer.  Meanwhile I am using this [workaround plugin for auto-hidding](https://github.com/ponyesteves/auto-hide-composer-bar-mailsspring) menu bar on composer.

```javascript
import e from 'electron'

export function activate() {
  const app = e.remote.getGlobal('application')
  e.remote.ipcMain.on('new-window', (_event, data) => {
    const composer_window = app.windowManager.get(data.windowKey)

    composer_window.browserWindow.setAutoHideMenuBar(true)
    composer_window.browserWindow.setMenuBarVisibility(false)
  })
}
```
![auto-hide](https://user-images.githubusercontent.com/4960589/49016923-45836f80-f166-11e8-9146-236e39441703.gif)

Should this be a reported as a new Issue? I'll be glad to help
