### ISSUE TITLE
Spell Check Not Working

### ISSUE THREAD

**Issue by liamdevine82** [Foundry376/Mailspring#1140]
##### Are there any related issues? No

...

##### What operating system are you using? Mac OS High Sierra 10.13.06

...

##### What version of Mailspring are you using? 1.4.2

...

--

**Bug?**

##### Is this an email sync or connection issue? No

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? No

...

##### Is the issue reproducible with a particular attachment, message, signature, etc? Yes
![screen shot 2018-10-17 at 11 40 00](https://user-images.githubusercontent.com/43671364/47081379-586b6180-d202-11e8-818a-6348e500676a.png)

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

As you can see from the attachment the spell check on Mailspring is not working. I have paid for the pro features and am not really getting the features that should be included as a basic subscription.

**Comment by phamhung77** [comment]
It doesn't work to me either in Mailspring, even spellcheck works perfectly in the Mail app.

**Comment by bengotow** [comment]
Wow so I think I may have figured this out - do either of you have the "Interface Scaling" set to something <1? It looks like if you change the interface scaling setting to make everything smaller:
<img width="523" alt="image" src="https://user-images.githubusercontent.com/1037212/47968356-cd6dd200-e01d-11e8-8768-de18d05c7909.png">

The red squiggles are rounded out of existence - so the words are still misspelled and right clicking them suggests fixes, but the underlines don't show! Will see if I can fix this.
