### ISSUE TITLE
Wrong time from received e-mails

### ISSUE THREAD

**Issue by xQsme** [Foundry376/Mailspring#1141]
This might have been said before, sorry for not going through all the issues.
Let's say i send an e-mail at 18:10, receive a reply at 18:15, the reply shows as sent at 17:15 and is positioned as if it was sent before the first e-mail.
I'm in Portugal (GMT+0)

**Comment by phamhung77** [comment]
Just to make sure your receiver is in the same time zone with you. In reply, you can see the time zone next to the date - time. It can also be because of the receiver's setting too.

**Comment by xQsme** [comment]
seems like it's a problem with my machine as skype is also reporting wrong times
