### ISSUE TITLE
SMTP: 220 We do not authorize the use of this system to transport unsolicited, and/or bulk e-mail

### ISSUE THREAD

**Issue by jsx-ccb** [Foundry376/Mailspring#1145]
Greetings!

I am trying to connect to my company mail account. As you see, response code is OK, but there is a message with a related issue.

##### Are there any related issues?

 No

##### What operating system are you using?

Ubuntu 18.04

##### What version of Mailspring are you using?

1.4.2-f587b7b7

--

**Bug?**

##### Is this an email sync or connection issue?

```
----------IMAP----------
* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
1 STARTTLS
1 OK Begin TLS negotiation now.
2 LOGIN [<snip>]
2 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY NAMESPACE NOTIFY SPECIAL-USE COMPRESS=DEFLATE QUOTA] Logged in
3 COMPRESS DEFLATE
3 OK Begin compression (0.001 + 0.000 secs).
4 ENABLE QRESYNC
* ENABLED QRESYNC
4 OK Enabled (0.001 + 0.000 secs).
5 NAMESPACE
* NAMESPACE (("INBOX." ".")) NIL NIL
5 OK Namespace completed (0.001 + 0.000 secs).
6 LIST "INBOX." "*"
* LIST (\HasNoChildren \UnMarked \Junk) "." INBOX.spam
* LIST (\HasNoChildren \UnMarked \Drafts) "." INBOX.Drafts
* LIST (\HasNoChildren) "." INBOX.Junk
* LIST (\HasNoChildren \UnMarked \Trash) "." INBOX.Trash
* LIST (\HasNoChildren \UnMarked \Sent) "." INBOX.Sent
* LIST (\HasNoChildren \Archive) "." INBOX.Archive
6 OK List completed (0.001 + 0.000 secs).
7 LIST "" "INBOX"
* LIST (\HasChildren) "." INBOX
7 OK List completed (0.001 + 0.000 secs).


----------SMTP----------
220-[<snip>] ESMTP Exim 4.91 #1 Thu, 18 Oct 2018 11:22:04 -0500 
220-We do not authorize the use of this system to transport unsolicited, 
220 and/or bulk e-mail.
QUIT

SMTP Last Response Code: 220

SMTP Last Response: [<snip>] ESMTP Exim 4.91 #1 Thu, 18 Oct 2018 11:22:04 -0500 
We do not authorize the use of this system to transport unsolicited, 
and/or bulk e-mail.
```

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

**Comment by albertpinot** [comment]
I have this problem. Help please.

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this - it sounds like this mail server has some anti-spam protections in place that are outside Mailspring's control. It's likely that this response is being generated because the mail server doesn't trust the IP address block your request is coming from, or you haven't enabled IMAP+SMTP correctly with the provider. (I know Yandex, for example, requires that you have added a phone number to your account and verified it before allowing you to send mail through SMTP.)

Unfortunately you'll need to reach out to your mail provider for more information. Cheers—
