### ISSUE TITLE
Ubuntu 18.10 segmentation fault

### ISSUE THREAD

**Issue by RomanKlopsch** [Foundry376/Mailspring#1146]
Current behavior
In Ubuntu 18.10 when i launch Boostnote i have this error: [1] 7816 segmentation fault (core dumped) boostnote.
It s an Electon problem from the last glibc version 2.28.
VsCode have the same error and fixed this on the last version 1.28.0.

Steps to reproduce
Install with deb package
Launch
Error : segmentation fault (core dumped)

Environment
Version : last
OS Version and name : Ubuntu 18.10

**Comment by Al2Me6** [comment]
See issue #1108

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
