### ISSUE TITLE
emoji typeahead for :100: is too agressive, at least for minute values

### ISSUE THREAD

**Issue by simonv3** [Foundry376/Mailspring#1148]
##### What operating system are you using?
Ubuntu 18.04.1
...

##### What version of Mailspring are you using?
1.5.0-92ed66b8

**Bug?**
##### Is the issue reproducible with a particular attachment, message, signature, etc?

When I type in an hour and it happens to be ten minutes on the hour, I can't type anything else except for this the :100: emoji. 
![screenshot from 2018-10-22 16-08-06](https://user-images.githubusercontent.com/485583/47324457-afaf6e80-d614-11e8-83d7-22199d7772e1.png)

Steps to reproduce:

1. reply to an e-mail
2. Start typing, type an hour value and then type `:10`. You can't choose not to type 100.

**Comment by bengotow** [comment]
Wow - this is super annoying! I'm surprised nobody has caught this yet. I'll get this fixed in the next release.

**Comment by simonv3** [comment]
Thanks @bengotow!

**Comment by bengotow** [comment]
Hey! The fix for this shipped in v1.5.4 this afternoon. Mailspring should auto-update in the next few hours and you can also download the update directly from https://getmailspring.com/download. Happy new years!

**Comment by simonv3** [comment]
Thanks!
