### ISSUE TITLE
Syncworker crash when deleting search results

### ISSUE THREAD

**Issue by instantepiphany** [Foundry376/Mailspring#115]
##### Are there any related issues?

No.

##### What operating system are you using?
Windows 10.

##### What version of Mailspring are you using?
Just updated to 1.03-f82c88.

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
It has only happened on an IMAP provider, but will update if it happens on Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Not applicable.

Bug description:
When deleting all mail found in a search, the following happens sometimes:
```
Error: SyncWorker crashed with null (code 1) Objectlog: "4812 [2017-10-11 16:01:02.172] [background] [info] 🔸 Updating message 1483=1483 with subject: MAKE IT has sold out — Watch it online instead!
↵4812 [2017-10-11 16:01:02.174] [background] [info] 🔸 Updating message 1484=1484 with subject: Watch Adobe MAKE IT Online
↵4812 [2017-10-11 16:01:02.176] [background] [info] 🔸 Updating message 1485=1485 with subject: Building brand identities
↵4812 [2017-10-11 16:01:02.178] [background] [info] 🔸 Updating message 1486=1486 with subject: Get a deep-dive into creative skills
↵4812 [2017-10-11 16:01:02.180] [background] [info] 🔸 Updating message 1487=1487 with subject: Adobe Stock now in Microsoft PowerPoint
↵4812 [2017-10-11 16:01:02.182] [background] [info] 🔸 Updating message 1488=1488 with subject: How to design business websites
↵4812 [2017-10-11 16:01:02.184] [background] [info] 🔸 Updating message 1489=1489 with subject: Catch up on Adobe MAKE IT with videos on demand
↵4812 [2017-10-11 16:01:02.186] [background] [info] 🔸 Updating message 1490=1490 with subject: An email on emails
↵4812 [2017-10-11 16:01:02.200] [foreground] [info] Idling on folder INBOX
↵"provider: "imap"
rawMessage: "Error: Account is missing required fields:imap_*"
stack: ""
__proto__: Objectconstructor: function Object()hasOwnProperty: function hasOwnProperty()isPrototypeOf: function isPrototypeOf()propertyIsEnumerable: function propertyIsEnumerable()toLocaleString: function toLocaleString()toString: function toString()valueOf: function valueOf()__defineGetter__: function __defineGetter__()__defineSetter__: function __defineSetter__()__lookupGetter__: function __lookupGetter__()__lookupSetter__: function __lookupSetter__()get __proto__: function __proto__()set __proto__: function __proto__()
module.exports.ErrorLogger.reportError @ C:\Users\Jordan\AppData\Local\Mailspring\app-1.0.3\resources\app.asar\src\error-logger.js:114
```

**Comment by instantepiphany** [comment]
Actually, this might be a duplicate of #56, except in #56 that issue is marked as specific to Gmail, this happens on my private IMAP provider. @bengotow or other contributors feel free to close if you feel this is a duplicate.

**Comment by nickolasclarke** [comment]
I cannot find a similar error in my log, but deleting messages from silently fails for me. I get the success message that they were moved to the trash, but once I return to the inbox, they are still present. Deleting from the inbox directly does work however. I am also using a provider other than gmail over imap.

**Comment by bengotow** [comment]
Hey folks—we haven't seen any reports of this in several months so I'm gonna go ahead and close this. It was likely fixed by another patch and we just didn't tie it back to this. Thanks!
