### ISSUE TITLE
participant field if raw email incorrectly reflected

### ISSUE THREAD

**Issue by muradm** [Foundry376/Mailspring#1150]
##### OS: Arch Linux + Gnome, Version: 1.5.0-92ed66b8 (as per comments, bug is cross-platform)

**Bug**

Email (for me `from`, but may affect `to`, `cc` etc.) header, at least, incorrectly displayed, if contains just raw email address. Screenshots:

![image](https://user-images.githubusercontent.com/2050575/47339623-d7eaac00-d6ac-11e8-9d40-7ae1b0b257e4.png)

![image](https://user-images.githubusercontent.com/2050575/47339690-15e7d000-d6ad-11e8-902f-858d4b8c594d.png)

If the source of email, has:
```
From: someone@domain.com
```
The above screenshots reflect how it is treated. Basically because it is raw form but not generally used extended form like `Some One <someone@domain.com>`, `mailspring` says that message from `NIL`.

Expected behavior would be, to reflect raw email, not `NIL`.

Looking with developer tools, and how `participant` component is generated, I suspect that this may impact indexing, searching etc. For instance, search suggestion shows many `NIL`s.

![image](https://user-images.githubusercontent.com/2050575/47340036-15036e00-d6ae-11e8-94a2-d5088691fe8d.png)

Same mail as displayed in Web Outlook for example:

![image](https://user-images.githubusercontent.com/2050575/47340399-29943600-d6af-11e8-8d0b-c2b764badd10.png)

Because, no decoration in email header field, it uses email address as is.

**Comment by evromalarkey** [comment]
Had the same problem in 1.5.0, when I was replying to mail

**Comment by arvislacis** [comment]
Same problem for Linux Mint 19 snap package (Mailspring 1.5.0-92ed66b8).

**Comment by db369** [comment]
Same problem here. Also Linux Mint 19, deb install.

**Comment by TeamKinetic** [comment]
+1 for Windows 10

**Comment by andreshg112** [comment]
Same here!
Zorin 12.04 (Ubuntu 16.04)

**Comment by harm0nic** [comment]
Can also confirm this issue. Ubuntu 18.04, mailspring v. 1.5.0.

**Comment by carlwgeorge** [comment]
Nobody else needs to confirm they are affected, I think the developers get it at this point.  Stop sending the rest of us notifications.  If you must indicate you're affected as well, +1 the original post.

**Comment by muradm** [comment]
Fix to come soon: [comment](https://github.com/Foundry376/Mailspring/issues/1153#issuecomment-433559584) and [commit](https://github.com/Foundry376/Mailspring/commit/8c95ead2cd9b55a7cdae01e122f0aa272e179c75)

**Comment by d3sandoval** [comment]
This is still happening to me on group "aliases":
![image](https://user-images.githubusercontent.com/7872348/47605069-c7e60b80-d9cf-11e8-86f1-a28737139bb9.png)

The email address I'm sending it to is a gSuite "Group": https://support.google.com/a/answer/2727156?hl=en

I have the latest version: 1.5.1-da141eaf

Thanks for the quick response on this issue!

**Comment by muradm** [comment]
Updated to 1.5.2-31660463. Same story. @bengotow, should mails be re-indexed? If yes, how? By re-adding account?

**Comment by muradm** [comment]
As per [comment](https://github.com/Foundry376/Mailspring/issues/1153#issuecomment-436918953) re-indexing is required.
