### ISSUE TITLE
German translations are bad

### ISSUE THREAD

**Issue by tobias-kuendig** [Foundry376/Mailspring#1151]
The german translations provided with the lastest verson are pretty bad.

For example, the `New Open` notification title is translated as `Neuer Eröffnungskurs` which actually means something along the lines of `New beginner course`.

The menus are completely uncomprehensibe as well since they don't use the usual wording: `Undo` is `Wiederrufen`, which is usually translated as `Rückgängig`. `Paste` is `Einsetzen`, which is usually translated as `Einfügen`. The list goes on and on.

It looks like these translations were done automatically. This does not work since the "computer context" is not taken into account.
I suggest you revert these changes until better translations are available. This gives new users a pretty bad picture of an otherwise great app!

**Edit:** Is it not possible to choose another language manually?

**Comment by SimonVanacco** [comment]
It is indeed impossible to change the language manually from the program settings menu at this time, and i found some translations in my language to be very bad as well. 

You could try and read this: https://github.com/Foundry376/Mailspring/blob/master/LOCALIZATION
It will tell you how to run Mailspring in a specific locale & how you can help translate Mailspring in your language, if you wish to give the project some of your time.

**Comment by bengotow** [comment]
Hey folks! Thanks - yeah I’ll get an option in to preferences to change the language selection. @DarkSmile92 I really appreciate the help improving the translations.

When we ship the option to choose a language, I think I’ll also make the app default to English for any language that hasn’t been manually reviewed by a contributor. It looks like the automatic translations very from very good in some languages to super awful in others.

Thanks!

**Comment by DarkSmile92** [comment]
Always glad to help improving awesome projects :-)

**Comment by bengotow** [comment]
Hey folks! Going ahead and closing this - we've received lots of improvements to the German translations and they should be pretty good now!
