### ISSUE TITLE
NIL showing instead of address name since upgrade to 1.5.0

### ISSUE THREAD

**Issue by TeamKinetic** [Foundry376/Mailspring#1153]
##### What operating system are you using?

windows 10

##### What version of Mailspring are you using?

1.5.0

**Bug?**
Emails are now showing NIL as the recipient/sender names since I update this morning eg.
To: NIL <myemailaddress>

**Comment by avano** [comment]
The same on ubuntu 16.04, happening since upgrade to 1.5.0 from 1.4.2

**Comment by palefire19** [comment]
+1

**Comment by mcescalante** [comment]
This is also happening for me on all incoming mail since updating. Picture: ![](https://cl.ly/ce3a1a8429a2/Image%202018-10-23%20at%2012.49.44%20PM.png)

**Comment by jerm** [comment]
FWIW i'm only seeing this on emails w/o friendly names, and only on _new_ emails. 

I'm seeing expected (read: blank) behavior on emails that were indexed pre-upgrade.

**Comment by timdorr** [comment]
I'm also seeing this for emails with blank subject lines.

**Comment by nfntp** [comment]
+1 on Mac OSX 10.14 Mojave and Mailspring 1.5.0

**Comment by nemm** [comment]
Same thing on Windows 10

**Comment by remokon** [comment]
+1 on Ubuntu 18.04, Mailspring version 1.5.0

**Comment by tharvan** [comment]
And this NIL text is used when composing / replying to such and email through mailspring. So the recipient is getting puzzled a bit: "why do you call me NIL?". On Mac, version 1.5.0.

**Comment by phamhung77** [comment]
This needs to fix asap. @bengotow agreed?

**Comment by lecooliver** [comment]
+1 on Kubuntu 18.10, Mailspring 1.5.0

**Comment by LukasDustee** [comment]
Same issue here. Windows 10, Mailspring version 1.5.0

**Comment by Al2Me6** [comment]
+1 Kubuntu 18.10, Mailspring 1.50.
Interestingly this happens only for some accounts, mostly for addresses without a specified name.

**Comment by anshumansaagar** [comment]
+1 Ubuntu 18.04 version 1.5.0

**Comment by iaz3** [comment]
Same here, windows 10, mailspring v1.5.0, some senders are showing up as NIL. This didn't happen in previous versions.

**Comment by etekinbas** [comment]
Same as MacOSx High Sierra, Mailspring Version 1.5.0

**Comment by eclipsed-ninja** [comment]
I have raised a PR https://github.com/Foundry376/Mailspring/pull/1176 , which seems to sort out the issue. I am unsure whether this is a proper solution or not as I have not explored the codebase properly.

**Comment by eclipsed-ninja** [comment]
@bengotow I've updated to 1.5.1 and still seeing a lot of NIL as name (previous emails), do i need to do a fresh setup again ?

**Comment by twillmott-goji** [comment]
> @bengotow I've updated to 1.5.1 and still seeing a lot of NIL as name (previous emails), do i need to do a fresh setup again ?

I had to go to Manage Accounts > Rebuild Cache... in order for the fix to work. Can confirm the NIL issue is resolved on v1.5.2 on Mac 10.13.6

**Comment by bengotow** [comment]
Hey folks—thanks for all the feedback about this. It sounds like the 1.5.1 upgrade and rebuilding the email cache do the trick. I'm going to close this! Happy holidays—
