### ISSUE TITLE
Add Mailspring to Linux repo to be able to update through sudo apt-get upgrade

### ISSUE THREAD

**Issue by sgtcoder** [Foundry376/Mailspring#1156]
##### Are there any related issues?

...

##### What operating system are you using?
Debian 9.5 + XFCE 4.12
...

##### What version of Mailspring are you using?
1.5.0
...

--

**Bug?**
N/A
##### Is this an email sync or connection issue?
N/A

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
N/A

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
N/A

...

--

**Feature Request?**
Yes
##### Does this feature exist in another mail client or tool you use?
Yes, it's just added to the Linux repos. So hoping to have a 3rd party repo I can add to my sources.list
...

**Comment by bengotow** [comment]
Hey! There’s currently no plan to provide Mailspring through individual update managers - the Snapscraft release runs on most Linux distros and automatically updates if you want to give that a shot!

**Comment by codermjb** [comment]
I ended up launching my own repo server with a CRON job that pulls updates for all the debs that no one provides repos for. So now I can just update through apt easily.

**Comment by phylophyl** [comment]
> Hey! There’s currently no plan to provide Mailspring through individual update managers - the Snapscraft release runs on most Linux distros and automatically updates if you want to give that a shot!

I have never succeeded running snapd apps on Debian 9, nor 10 so far with an encrypted LVM system. So that i can't use so far Mailspring on Debian 10. On can see that snapcraft community is having hard time to make snapd apps works on Debian 10 because of Apparmor specifically. This is a problem as a premium user who was betting a lot on Mailspring use. Flatpack or Appimage are working fine on the other hand.

**Comment by phylophyl** [comment]
> I have never succeeded running snapd apps on Debian 9, nor 10 

A system restart will make the snap work.

**Comment by CodeMouse92** [comment]
This issue should be effectively resolved if we implement this related feature: https://community.getmailspring.com/t/flatpak-distribution-on-linux/68

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
