### ISSUE TITLE
Mailspring 1.5.0 (259) fails to start - failed to create gtkfilechooser.ini symbolic link

### ISSUE THREAD

**Issue by Ads20000** [Foundry376/Mailspring#1157]
Mailspring 1.5.0 (259) fails to start on Ubuntu 18.10 with snapd 2.35.5

```
$ snap run mailspring
ln: failed to create symbolic link '/home/adam/snap/mailspring/259/.config/gtk-2.0/gtkfilechooser.ini': File exists
```

Nothing comes up in `journalctl -f` when I try to run Mailspring.

##### Are there any related issues?

The same error also comes up in the following (but I'm filing this error as a separate issue):
https://github.com/Foundry376/Mailspring/issues/8#issuecomment-355202005
https://github.com/Foundry376/Mailspring/issues/798#issuecomment-378576225
https://github.com/Foundry376/Mailspring/issues/933#issuecomment-401230118

##### What operating system are you using?

```
$ snap version
snap    2.35.5+18.10
snapd   2.35.5+18.10
series  16
ubuntu  18.10
kernel  4.18.0-10-generic

$ snap info core
tracking:     beta
refresh-date: 7 days ago, at 09:42 BST
  beta:      16-2.35.5                   (5742) 92MB -
installed:   16-2.35.5                   (5742) 92MB core
```

##### What version of Mailspring are you using?

```
$ snap info mailspring 
tracking:     stable
refresh-date: today at 08:18 BST
  beta:      1.5.0 (259) 170MB -
installed:   1.5.0 (259) 170MB -
```

--

**Bug?**

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

**Comment by bengotow** [comment]
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of Electron and/or snapcraft. Feel free to bump this or re-open a new issue if you run in to this again.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
