### ISSUE TITLE
Menubar theming issue on Linux

### ISSUE THREAD

**Issue by Al2Me6** [Foundry376/Mailspring#1158]
It seems that the new version of Electron now uses the system theme for the menubar on GTK. However, it does not seem to use the text color, resulting in unreadable text (black on black) if a dark theme is selected.

Kubuntu 18.10, Mailspring 1.50

**Comment by bengotow** [comment]
Hey! Wow interesting–this seems like a big oversight on the Electron front. Is this picture here accurate? https://github.com/electron/electron/issues/9681 (Where just the selected highlighted item appears black-on-black?) or is it /all/ the menu bar text?

**Comment by alecbcs** [comment]
Same issue here with Mailspring 1.5.2 on Solus. The menu bar is completely black.
![image](https://user-images.githubusercontent.com/19558067/48040055-a81fb780-e134-11e8-9c56-b6393e0f59c1.png)

**Comment by emilioestebanez** [comment]
I have the same issue on Ubuntu 18.10 using the default theme (Yaru)

**Comment by luchmhor** [comment]
Same for me: black on black using kde with Adapta for qt5 and gtk3. Changing the mailspring theme doesn't affekt the dark menu bar with dark text.

**Comment by GulajavaMinistudio** [comment]
Same here in VS Code, and Gitkraken, what kind of bugs is this ? 

![screenshot_2018-11-24_17-02-15](https://user-images.githubusercontent.com/11639412/48966926-ddb91180-f00b-11e8-9f0f-45cdb9d7ac07.png)

![screenshot_2018-11-24_17-03-26](https://user-images.githubusercontent.com/11639412/48966935-ed385a80-f00b-11e8-8004-2efda057530e.png)

**Comment by alexandru-calinoiu** [comment]
Visual studio has a work around for it, you can choose not to use the system menubar. Is something like this possible in mailspring?

**Comment by rawl28** [comment]
Same issue here witha dark theme on Fedora 29

**Comment by bengotow** [comment]
Hey folks—v1.5.4 just shipped earlier today and now uses the latest version of Electron (4.0.0). Could you give the new version a spin and see if it addresses this issue?

**Comment by Al2Me6** [comment]
Just tested... unfortunately no change.

Kubuntu 18.10, Plasma 5.14.4

**Comment by bengotow** [comment]
hmm thanks for checking, that's good to know—we'll probably need to push this upstream to Electron and see what's going on!

**Comment by bengotow** [comment]
hey folks—it looks like this patch (https://github.com/electron/electron/pull/16223) was included in Electron 4.0.1 which I think may fix this issue? I'll bump to 4.0.1 in the next release and we can verify.

**Comment by Al2Me6** [comment]
Thank you, confirmed fixed in 1.5.6!
