### ISSUE TITLE
Add Icon for Notifications [Linux / KDE]

### ISSUE THREAD

**Issue by murat-cileli** [Foundry376/Mailspring#1160]
Add application icon to notifications. Otherwise it's hard to distinguish notifications that came from MailSpring.

**Comment by bengotow** [comment]
Hey! On Linux we use Electron’s Notification module to post notifications, it seems like we might just need to pass some additional configuration? (Or maybe this is fixed in 1.5.1 now that we’re correctly setting the window icons?) would be a good first issue for someone on Linux to investigate!

**Comment by varlesh** [comment]
@bengotow
Mailspring  not show icon `MenuItem-Inbox-Full-NewItems` (with new mail status) if app closed to tray - used icon `MenuItem-Inbox-Full`, BUT if app minimized - icons worked correctly and icon `MenuItem-Inbox-Full-NewItems` applied.
It's bug reproduced on all KDE users:
https://github.com/Foundry376/Mailspring/issues/1042

**Comment by Stefanitsky** [comment]
Same problem:
[Screenshot](https://imgur.com/QKc9Cesl.png)
Desktop environment: XFCE

**Comment by arkraft** [comment]
@varlesh @Stefanitsky I think you guys are referring to a totally unrelated problem. This is not about the tray icon but about the notification popup. When a new mail arrives, the popup is shown without any icon. But the notification popup can show an icon, it's just not configured right now and no icon is provided for the notification.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
