### ISSUE TITLE
False open tracking

### ISSUE THREAD

**Issue by spartero** [Foundry376/Mailspring#1162]
For a week, I am observing that if I have an email with the option of "open trancking" activated, every time I open the program I receive a notification that at that moment the mail has been opened, after I follow it, I think that this is a false opening (it happens to me in all the emails that I have sent in the last week). With which, over time you can not tell which of the mail openings is real. This happens to me with version 1.5, like the one before it.

regards

**Comment by MikeSharkey1** [comment]
This happens to be all the time. Very misleading, as it tells me my recipient opens when it's actually me... Annoying!

**Comment by melmups** [comment]
Having the same issue. Opening an email will trigger a notification that the recipient has opened the email

**Comment by bengotow** [comment]
Hey folks! This should be resolved in the release that went out this morning - there was an issue where Mailspring wasn't properly updating the message in your Sent folder so clicking it would trigger the read receipts. Thanks for your patience!
