### ISSUE TITLE
Errors with Gmail Sync

### ISSUE THREAD

**Issue by osharifali** [Foundry376/Mailspring#1166]
##### Are there any related issues?

...

##### What operating system are you using?

... Windows

##### What version of Mailspring are you using?

... 1.5.0

--

**Bug?**
My gmail does not sync anymore. I constantly get "Mailspring encountered errors syncing this account .... Try Reconnecting." Was not having this problem yesterday before I updated. 

##### Is this an email sync or connection issue?
Yes, logs attached

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
NA
[mailsync-logs.zip](https://github.com/Foundry376/Mailspring/files/2513331/mailsync-logs.zip)

...

--

**Feature Request?**
NA
##### Does this feature exist in another mail client or tool you use?

...

**Comment by bengotow** [comment]
Hey there! Thanks for filing this - it looks like this should be fixed in the latest release. Thanks!

**Comment by bengotow** [comment]
Hey there! Thanks for filing this - it looks like this should be fixed in the latest release. Thanks!
