### ISSUE TITLE
French Translation : weird :)

### ISSUE THREAD

**Issue by phylophyl** [Foundry376/Mailspring#1167]
Hi,

Mailspring is translating from English "Date" to French by the following : "Rendez-vous amoureux"
That means literally : "Appointment with a lover". This appears when you are forwarding an email after the Object line.

The correct translation is :
EN = FR
Date = Date

**Comment by gwelr** [comment]
https://github.com/Foundry376/Mailspring/blob/master/app/lang/fr.json#L160 
@phylophyl you could submit a patch easily, except if you are on a date... :-)

**Comment by phylophyl** [comment]
Thank you @gwelr, luckily enough, i was not :) 
Submitted

**Comment by bengotow** [comment]
Thanks for submitting a patch! That was definitely an awkward translation...
