### ISSUE TITLE
No way to update sender identity / "From" name after linking account

### ISSUE THREAD

**Issue by phylophyl** [Foundry376/Mailspring#1169]
I am trying to update an account label to correct an error. The update is not reflected when i am writting an email with this account, so that the "From" value stays not correct. Any solution, is it a bug, do i need to delete and create the same account ?

PS : sent also to zendesk support without an answer since september 22nd (premium account)

**Comment by gwelr** [comment]
https://github.com/Foundry376/Mailspring/blob/master/app/lang/fr.json#L160 
@phylophyl you could submit a patch easily, except if you are on a date... :-)

**Comment by bengotow** [comment]
Hey! Thanks for filing this, sorry you had trouble with Zendesk, I'll see what happened!

The "Account Labels" in Mailspring are just for organizing the accounts - so you could label your accounts "Work" and "Gmail", for example. The name that is shown when you go to send an email is the "Sender Identity" or "Phrase" and you actually can't change that from the Preferences UI yet. It's the name that you enter when you first link the account, along with the email address. 

I'll see if I can add that to Mailspring's preferences. I don't think there's any reason we couldn't allow you to edit the sender identity as well.

Thanks for being a Pro user!

**Comment by bengotow** [comment]
Hey! The fix for this shipped in v1.5.4 this afternoon. Mailspring should auto-update in the next few hours and you can also download the update directly from https://getmailspring.com/download. Happy new years!
