### ISSUE TITLE
[Feature Request] Team Collaboration on Emails

### ISSUE THREAD

**Issue by dsog** [Foundry376/Mailspring#1179]
One of the *best* features I like about Spark is being able to collaborate with other team members on emails either by crafting the message together, or asking questions, etc. It would be great if Mailspring can support this feature.

https://sparkmailapp.com/teams/private_team

Thanks,
Khaled

**Comment by CodeMouse92** [comment]
While this sounds like a *really cool idea*, the amount of infrastructure involved in supporting this feature would be significant. Right now, we're still focusing on Mailspring's core functionality and many long-standing stability fixes. Thus, I don't foresee this happening in the near future.

If you still think this is a good idea, please create a new topic in the Feature Suggestions category on our [Discourse](https://community.getmailspring.com). This may be a good candidate for a third-party plugin!
