### ISSUE TITLE
Enhancement - Fluid layout

### ISSUE THREAD

**Issue by enx1998** [Foundry376/Mailspring#1182]
It would be great if all emails related windows (composer, preview pane etc...) could have a fluid layout instead a boxed one, because, in some cases horizontal scroll bar are shown.

Thanks Vincenzo

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - we actually experimented with a completely fluid message viewer a while back, but forcing all messages to display in a fluid way causes some suuuuper ugly things to happen to messages that contain HTML Tables. We have to tell the browser to aggressively break words, etc. to make things fluid and that can cause display to be less than ideal. Showing the horizontal scroll bar kind of sucks, but I think it may be the best we can do for now. Thanks!
