### ISSUE TITLE
add an imap account laposte.net : fail

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#1194]
Windows 10 x64 + Mailspring 1.5.1(First installation and no update)

There have been no other installations of previous versions of Mailspring on this computer where there is the problem.
_additional information: On my other computer, version 1.4x of Mailspring installed and updated to version 1.5.0 (I have not yet updated to 1.5.1) this email account was added previously with version 1.4x and I did not notice any problem after update 1.5.0._

1/ since a new installation 1.5.1, it was impossible for me to add an email account @laposte.net (French mail https://www.laposte.net/accueil)
2/ I click on add an account and I click on IMAP
3/ an error message is displayed
4/attach the log files
![mailspring 2018-10-29 16 22 18](https://user-images.githubusercontent.com/31793920/47664518-84da9280-db9f-11e8-9afd-82a960686099.png)

[118929-3256-1yged19.5j7n.log](https://github.com/Foundry376/Mailspring/files/2526121/118929-3256-1yged19.5j7n.log)
[118929-4644-qhcyy5.dirwc.log](https://github.com/Foundry376/Mailspring/files/2526122/118929-4644-qhcyy5.dirwc.log)

**Comment by franco27** [comment]
I solved this problem:
1 / I uninstalled version 1.5.1
2/ I installed version 1.4.2 and added my mail account laposte and yahoo #1193 
3/I upgraded to 1.5.0 and then version 1.5.1

**Comment by bengotow** [comment]
Great! Glad you were able to get this resolved.

**Comment by franco27** [comment]
In previous versions, it was not necessary to tick "allow unsecured SSL" which is next to SSL/TLS.

Now it is necessary to tick this parameter otherwise the email account cannot be added.
