### ISSUE TITLE
Please provide option to choose language for user interface manually

### ISSUE THREAD

**Issue by intradesign** [Foundry376/Mailspring#1199]
I think the possibility to translate Mailspring is great. But worse than no translation is a bad translation. I would prefer to continue using Mailspring in English and only use the German translation if it is good (to which I would also like to contribute).

Question: Can I change the translation directly in my installation by replacing or overwriting the (or a) language file somewhere in my installation (macOS), or do I have to wait for a new release of the Mac binaries to see a new translation?

Many thanks and many greetings
Timo

**Comment by SimonVanacco** [comment]
You could contribute for the translations if you know how to use Github and want to help out the Mailspring project. 
The language switch is a popular request and i hope will be added soon too.

**Comment by bengotow** [comment]
Hey! I totally agree we need this—folks are contributing PRs and cleaning up the translations fast (which has been super awesome), but I think it should definitely be an option.

I think that you'll need to restart Mailspring to change the language, which is a little unfortunate, but definitely better than nothing. Stay tuned!

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
