### ISSUE TITLE
Can't search Mailspring GitHub repo because it's a fork of Nylas Mail

### ISSUE THREAD

**Issue by b0o** [Foundry376/Mailspring#12]
GitHub doesn't allow you to search the code of a forked repository for some odd reason, forcing you to search the parent repo instead. Since Mailspring has diverged so much from Nylas, those search results would be very inaccurate.

Since Mailspring will never be submitting Pull Requests back to Nylas, it seems unnecessary to keep it as a fork.

On GitHub's help site, they say:

> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support. If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network.

([Source](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork))

**Comment by bengotow** [comment]
Hey @b0o thanks for reporting this - the search thing is definitely a bummer. I'll check with a few folks and see if there would be any downsides but it sounds like breaking it off would be a good idea.

**Comment by bengotow** [comment]
I've requested that Github detach this repo from nylas/nylas-mail—stay tuned!

**Comment by erlend-sh** [comment]
Any news on this? Might be worth poking them about it again.

**Comment by bengotow** [comment]
Yeah... poking again now!

**Comment by b0o** [comment]
It seems they've detached the repo! Closing this.
