### ISSUE TITLE
Tray icon not showing

### ISSUE THREAD

**Issue by Scaum** [Foundry376/Mailspring#1207]
Hi,

After updating my system from Fedora 28 to Fedora 29, the mailspring icon isn't shown in system tray anymore.
I guess this could be an issue with Gnome 3.30, but might be wrong there.

Just wanted to let you know a bout that (very) minor issue !

**Comment by MickaelTH** [comment]
Same with LinuxMint 19, no icon at all but click on the space where the icon is supposed to be launch the program.

**Comment by denivic** [comment]
Same thing with Ubuntu 18.04.1 except I don't have an empty space where the icon is supposed to be, it has simply disappeared. I can't click and get the program to open like @MickaelTH can.

**Comment by cubetastic33** [comment]
Same issue here on Arch Linux with KDE Plasma. Just a single dot shows.

**Comment by Rygi3l** [comment]
> Same with LinuxMint 19, no icon at all but click on the space where the icon is supposed to be launch the program.
I have this issue too.

**Comment by vtruong68** [comment]
Still an issue in Manjaro 18 on Cinammon. Icon is invisible on boot. Disabling and re-enabling the tray icon in preferences as @jfneto mentioned temporarily solves the problem until the next boot.

**Comment by carmenfdezb** [comment]
Installing `libappindicator-gtk3` solved this issue for me. I use Fedora 30 KDE

**Comment by allopislozano** [comment]
![screenshot5](https://user-images.githubusercontent.com/13063550/60491605-7225d980-9ca9-11e9-96df-866871e191a5.png)
For me the icon doesn't show at all

**Comment by ramanic** [comment]
Installing appmenu-gtk-module solved the issue for me in Arch Linux (KDE).

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
