### ISSUE TITLE
Interface really slow

### ISSUE THREAD

**Issue by neddy70** [Foundry376/Mailspring#121]
Hi,

Is anyone else having trouble with the interface being really slow? I'm trying to go through my inbox and delete or archive emails I've dealt with, and there is a delay of a few seconds between archiving each email, it makes it a bit slow to get through them... Initially I only had a couple accounts active in Mailspring and it was fine, but after adding my work email which has a bit more email in it, it really slowed down.

I'm happy to provide any details I can, I just didn't know where to start in this case.

As a side note, I'm pretty happy to see this app coming along. I loved Nylas, and I was disappointed when I heard it was not being developed. The new sync engine seems fast, it pulled down all my emails pretty quickly.

Cheers.

##### What operating system are you using?
MacOs 10.13

##### What version of Mailspring are you using?
Version 1.0.3 (1.0.3)

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - definitely going to leave this open and see if we can collect some more cases of this happening. Do you have any software installed (like antivirus, etc.) that might be interfering with the app?

**Comment by neddy70** [comment]
Thanks for the quick reply! I don't have any antivirus software, or anything else that I think would interfere with it. 

I've actually deleted the preferences plist, and delete the Application support folder to reset Mailspring and it seems to be working better. For now, I've only added back one of my accounts, I'll will try it for a day and then add the other accounts back...

Cheers

**Comment by neddy70** [comment]
I think this can be closed. It looks like this is related to a memory leak in MacOS High Sierra.

**Comment by kinduff** [comment]
+1

Installed using Snap, version 1.4.2 under Arch Linux. It's a beautiful email client but painfully slow. Is there something we could provide to report this issue currectly? Benchmarks? Debug info?

**Comment by denravonska** [comment]
I just tried the Snap package for version 1.5.1 and it is much slower than the deb on Ubuntu 18.04.

**Comment by nickallevato** [comment]
Same. Lagging all over the place.

**Comment by LoneWolfHT** [comment]
Also super slow for me after the last update

**Comment by VladVin** [comment]
Mailspring 1.6.0 is extremely slow. When I type a text message it freezes and doesn't show the typed characters. OS: Ubuntu 18.04. Installation: deb package.

**Comment by LoneWolfHT** [comment]
> Mailspring 1.6.0 is extremely slow. When I type a text message it freezes and doesn't show the typed characters. OS: Ubuntu 18.04. Installation: deb package.

Same here. I think this is the issue we're having: https://github.com/Foundry376/Mailspring/issues/720

**Comment by jmaybe** [comment]
For me (using latest version, but not on that computer right now so unknown version #), it seems to only slow to a crawl when replying to extremely long ‘reply-all’ threads. It slows to the point of unusability - extreme lag in response of any sort - keystrokes, scroll, etc... However, to test if that was the case I stopped working with that particular thread and created a new message to one person and it worked flawlessly.

**Comment by gammacray** [comment]
Hi there, cool that you left this open. I'm on Windows 10, have been using mailspring for almost a year and love it! However, just today I started expriencing some problematic typing lag. It's really strange, it doesn't happen in other programs. I'll tinker and find the source of it if I can, and report back if I do. Meantime I thought it would be good to mention it here in case it's been solved already elsewhere.

Thanks for all the work on this amazing software.

**Comment by joaomarccos** [comment]
Same here. Very slow behavior when the number of emails increase. Get stucked sometime while 'Caching mail'

**Comment by LoneWolfHT** [comment]
I think they're trying to move issue reports to the Discourse forum now (I link to an issue there below)
This was what was causing the lag for me: https://community.getmailspring.com/t/significant-lag-on-large-threads/183
