### ISSUE TITLE
Form label too long in french on macOS first sign in screen

### ISSUE THREAD

**Issue by Bigood** [Foundry376/Mailspring#1215]
##### What operating system are you using?
macOS 10.13.5 (17F77)

##### What version of Mailspring are you using?
Version 1.5.1 (1.5.1) - French language

**Bug?**
The e-mail label is too long and collapses. The password collapses too, and the password placeholder disappeared. Seen on the first sign in screen.

Same problem might be visible for others languages.

![image](https://user-images.githubusercontent.com/11982534/47990091-ed1cfd00-e0e6-11e8-9298-3734e1269300.png)

**Comment by Bigood** [comment]
Same issue on login screen: 
![image](https://user-images.githubusercontent.com/11982534/47990757-9e706280-e0e8-11e8-93c6-81ff3e397233.png)

**Comment by bengotow** [comment]
Oh man good catch—thank you for reporting this! I'll see if I can fix this ASAP.

**Comment by bengotow** [comment]
Should be resolved in a few minutes when the deployment completes—I've verified we use the shorthand version of "Email" and "Password" in all the languages supported by the ID service.

**Comment by Bigood** [comment]
How fast! Thanks for the fix, closing.
