### ISSUE TITLE
How can I create that rule

### ISSUE THREAD

**Issue by andi2garcia** [Foundry376/Mailspring#1217]
Hi,
I'm just looking forward this feature but unfortunately I can't get it.
I have 4 email accounts (and even more), some from businesses, some from school...
I need to:
When I send an email (per example, as school account selected on left panel) to automatic swap the sender to my business account by following a rule that I create.
I would call this "Outgoing email rules".
It has to check when an email is being send, that the email applies for all the required rules.

In this case, the full process would be:
1. I'm checking my school email.
2. Suddenly, I remember that I've to send an email to work. So I click on left panel "New Message" Icon.
3. I write my email and send it to a @mywork.com direction.
4. I click on send. So... The outgoing rule check's the email. The filter requires that "Every email sent out from all accounts, if match *@mywork.com, it has to be sent as myworkemail@mywork.com".
5. I don't get frustrated as I'm sending emails by school email to my boss.
6. Mailspring get's this feature so we keep payin' with happiness for it!!

Thanks in advance! Hope I clarified it.

**Comment by bengotow** [comment]
Hey! Great to hear from you—this is a cool idea! Unfortunately it's not something you can build with the current mail rules, which are just for filtering incoming mail and not outgoing mail.

That said, part of the plan for early next year is to expand and document Mailspring's plugin architecture, and this would be a really feasible plugin. If you're comfortable writing a few lines of Javascript, you could add a small bit of code that runs when you send your messages and warns you if you're sending to the wrong account.

Stay tuned! I'll let you know when the revamped plugin support launches and we can make this plugin.

**Comment by bengotow** [comment]
(Going to close this for now until it's possible to build!)
