### ISSUE TITLE
Papercut: Welcome Screen Placed Between Screens

### ISSUE THREAD

**Issue by jGleitz** [Foundry376/Mailspring#122]
When launching Mailspring for the first time on my two-monitor setup, the welcome screen is placed at the centre of all monitors—that is, partly on every screen— instead of the centre of one monitor.

![mailspring welcome](https://user-images.githubusercontent.com/4305652/31437691-6ecd623e-ae86-11e7-911f-cefccb4ce91f.png)

Minor issue, but you know what they say, the first expression counts :smile:

I noticed this behaviour for a few other apps on my system, too (but not for all!). This could indicate that apps have to handle the case manually. I’m using Budgie as Desktop Environment.

##### Are there any related issues?

no

##### What operating system are you using?
Ubuntu 17.04

##### What version of Mailspring are you using?
1.0.3

##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no

##### Is the issue reproducible with a particular attachment, message, signature, etc?

no

**Comment by bengotow** [comment]
Hah! Wow that's... unfortunate... I believe we ask Electron for the window to be "centered" but that's not exactly what I meant. If anyone wants to take a crack at fixing this, I think this is the line that needs to be changed to use Electron's `screens` API and position the window more intelligently: https://github.com/Foundry376/Mailspring/blame/master/app/internal_packages/onboarding/lib/onboarding-root.jsx#L41

**Comment by egoistonly** [comment]
Same issue. Not only _Welcome_ screen but _Add account_ dialog
![snapshot-2017-10-13-16-56-55-double](https://user-images.githubusercontent.com/10616956/31549704-a8e6996a-b037-11e7-8cec-ddf6348f2fe8.png)
