### ISSUE TITLE
Entered text is lost on heavily threaded emails and blank email is sent

### ISSUE THREAD

**Issue by sikand** [Foundry376/Mailspring#1221]
##### Are there any related issues?

...

##### What operating system are you using?

openSUSE 42.3 (x86_64)
VERSION = 42.3
CODENAME = Malachite

##### What version of Mailspring are you using?

1.5.2-31660462

...

--

**Bug?**

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes, but the content is confidential so I can't attach it. The issue is that when the message is long and there are a lot of threaded replies, the typed text can be lost and a blank email is sent.

If I do a bunch of <CR> and then type the message, I don't have this problem.

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by sikand** [comment]
Correction: Only the typed text is lost. The included thread is not lost. Screenshot attached.

![20181107_154219](https://user-images.githubusercontent.com/10038382/48168451-1767e980-e2a4-11e8-8ab7-48ba35aaf815.jpg)

**Comment by sikand** [comment]
I can consistently replicate this issue. It is causing me much embarassment. I am a Pro User and habve been paying for months, how do I get support ??

**Comment by sikand** [comment]
I'm getting this in the latest 1.5.3 as well

**Comment by bengotow** [comment]
Hey! I've confirmed that this is related to #948 and I'm going to merge it into that issue and follow up there. Thanks for reporting this @sikand.
