### ISSUE TITLE
Make the composer a bit more distraction free

### ISSUE THREAD

**Issue by ploum** [Foundry376/Mailspring#1222]
The composer window is a bit cluttered, the following screenshot speaks for itself.

<img width="471" alt="screenshot 2018-11-08 at 10 27 07" src="https://user-images.githubusercontent.com/1233155/48189657-fbfeec00-e340-11e8-8717-601f956822f1.png">

1. Allow plain-text composing and, with plain-text composing enabled, remove all the formatting bar in the composer.

2. the bottom bar is so crowded. Maybe it would worth an option to disable those quick access, having those rare options only from the menu and having only a "send" and "attach file"

**Comment by bengotow** [comment]
Hey! Yeah it's definitely getting crowded there... I think we can do plain text support in an upcoming release. In the meantime, it might be cool to see if a theme could hide those buttons for you :-) I think they're all individually selectable via CSS...

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved (plain text mode was implemented), so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
