### ISSUE TITLE
Read receipts and Link tracking always cannot work in Mac OS

### ISSUE THREAD

**Issue by luweidut** [Foundry376/Mailspring#1224]
##### Are there any related issues?

... **No**

##### What operating system are you using?

... **Mac OS Mojave 10.14.1**

##### What version of Mailspring are you using?

... **1.5.2**

--

 **I'm a pro user. I always use Mac os system. I use university email (imap/smtp).
 But I found that the Read receipts and link tracking always cannot work in macos system.
When I send email, the read receipt and link tracking are enabled, but I cannot receive any message  from read opening or link opening. In addition, in UI, the sent  email have not read eye.
I want to know this is bug? or I need preinstall some java runtime environment?**

...

**Comment by bengotow** [comment]
Hey @luweidut — thanks for reaching out! If this is still happening, could you go to Developer > Show Mailsync Logs in Mailspring's menu and send me the `mailsync-****.log` files it shows to ben@foundry376.com? I can take a look and see if the app is having trouble with your university mail system.
