### ISSUE TITLE
Ctrl+shift click

### ISSUE THREAD

**Issue by ShiiroSan** [Foundry376/Mailspring#1228]
Hello, it's look likes we cannot use ctrl shift and click to select all mail between the one selected.

**Comment by bengotow** [comment]
Hey @ShiiroSan! If you have a single message selected, you can press just shift and click to select all the messages in between your current selection and the clicked message. (Note that in the "wide" single panel Mailbox view, you need to click the checkbox to the left of a message to make an initial selection.)

If you press Command on a Mac or the Windows key on Windows, you can add / remove individual messages from the selection by clicking them.

Let me know if those aren't working for you! We should definitely be more explicit about this in the knowledge base.

**Comment by ShiiroSan** [comment]
Hello, 

Indeed! In fact, I was trying to multi select with ctrl pressed. Thanks a lot for the info! :)
