### ISSUE TITLE
SMTP Last Response Code: 535 (authentication failed)

### ISSUE THREAD

**Issue by ItorSnow** [Foundry376/Mailspring#1232]
Hi, Mailscpring v 1.5.2 on Ubuntu 18.10 

I try in Thunderbird it work.

Thank you.

----------IMAP----------
* OK Dovecot ready.
1 CAPABILITY
* CAPABILITY IMAP4rev1 SASL-IR SORT THREAD=REFERENCES MULTIAPPEND UNSELECT LITERAL+ ID IDLE CHILDREN NAMESPACE LOGIN-REFERRALS UIDPLUS LIST-EXTENDED I18NLEVEL=1 QUOTA AUTH=PLAIN AUTH=LOGIN AUTH=GSSAPI AUTH=CRAM-MD5
1 OK Capability completed.
2 LOGIN phorntepk "*********"
2 OK Logged in.
3 CAPABILITY
* CAPABILITY IMAP4rev1 SASL-IR SORT THREAD=REFERENCES MULTIAPPEND UNSELECT LITERAL+ ID IDLE CHILDREN NAMESPACE LOGIN-REFERRALS UIDPLUS LIST-EXTENDED I18NLEVEL=1 QUOTA
3 OK Capability completed.
4 NAMESPACE
* NAMESPACE (("" ".")) NIL NIL
4 OK Namespace completed.
5 LIST "" "*"
* LIST (\HasNoChildren) "." "Archive"
* LIST (\HasNoChildren) "." "Deleted Messages"
* LIST (\HasNoChildren) "." "Drafts"
* LIST (\HasChildren) "." "Mailspring"
* LIST (\HasNoChildren) "." "Mailspring.Snoozed"
* LIST (\HasNoChildren) "." "Sent"
* LIST (\HasNoChildren) "." "Sent Messages"
* LIST (\HasNoChildren) "." "Spam"
* LIST (\HasNoChildren) "." "Trash"
* LIST (\HasNoChildren) "." "INBOX"
5 OK List completed.

----------SMTP----------
220 gms.tgs-enterprise.com ESMTP Postfix
EHLO phorntepk-t480
250-gms.tgs-enterprise.com
250-PIPELINING
250-SIZE 52428800
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
STARTTLS
220 2.0.0 Ready to start TLS
EHLO phorntepk-t480
250-gms.tgs-enterprise.com
250-PIPELINING
250-SIZE 52428800
250-VRFY
250-AUTH LOGIN PLAIN CRAM-MD5 GSSAPI
250-ETRN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
AUTH PLAIN cGhvcm50ZXBrAHBob3JudGVwawBQaG9ybnRlcCs0MDEwMDA4OC8n
535 Error: authentication failed

SMTP Last Response Code: 535

SMTP Last Response: Error: authentication failed

mailsmtp Last Error Code: MAILSMTP_ERROR_AUTH_LOGIN

mailsmtp Last Error Location: 10

mailsmtp Last Auth Type: 2

**Comment by ItorSnow** [comment]
Update: Now v1.1.5 is working :D

**Comment by bengotow** [comment]
Great! Glad it worked in 1.1.5. Thanks!
