### ISSUE TITLE
Support for responding to calendar events

### ISSUE THREAD

**Issue by kansi** [Foundry376/Mailspring#1235]
##### What operating system are you using?

Manjaro linux

##### What version of Mailspring are you using?

version 1.5.2

##### Email service
Exchange

--

**Feature Request?**

##### The current state
Currently when an email is received with a calendar event as an attachment its not detected as a calendar event so I cannot respond to the invite. 

##### What I did

I tried writing a plugin which could detect the attachments,
```js
main.es6
...
  ExtensionRegistry.MessageView.register(OutlookCalendarEvent);
...
```

```js
import { MessageViewExtension,
         Actions,
         AttachmentStore } from 'mailspring-exports';

export default class OutlookCalendarEvent extends MessageViewExtension {
    static renderedMessageBodyIntoDocument({ document, message, iframe }) {
        message.files.map(file => {
            if (file.contentType === "text/calendar") {
                var filepath = AttachmentStore.pathForFile(file);
                fetch(filepath).then(response => {
                    var filedata = response.text()
                    console.log('FOUND FILE', filedata)
                })

                console.log("FOUND CALENDAR EVENT", file, filepath);

                var div = document.createElement('div');
                div.className = 'btn';
                div.innerText = 'Accept event invite';

                // iframe.insertAdjacentHTML('afterend', '<div class="btn">Accept invite</div>');
                document.body.append(div);

            };
        });

    };
}

```

Though the above adds a button under the displayed message, after some inspection I found that the above approach is not that accurate i.e. it would make more sense to have another element type to handle such attachments as done [here](https://github.com/Foundry376/Mailspring/blob/master/app/internal_packages/attachments/lib/message-attachments.jsx#L83)

##### What I would like
I would be great if the calendar event attachment is detected and the relevant action buttons are shown to the user. I am willing to take up this task if someone is willing to help me out a little.

PS: I am using [MineTime](https://www.minetime.com/) for calendar and as an end goal I would like to see the accepted events reflected there!

**Comment by Ancillas** [comment]
It looks like this is already on the [roadmap](https://github.com/Foundry376/Mailspring/blob/master/ROADMAP.md) for summer, 2019.

**Comment by frigaut** [comment]
Thanks Mailspring for implementing this (version 1.6.2-278bf219)!!

**Comment by ashb** [comment]
I see "Accept" etc buttons, but I find clicking these doesn't update the status of my calendar in Google.

Any idea where to start debugging this?

**Comment by donnfelker** [comment]
@ashb I'm also noticing this behavior as well. I'm a PRO user too.

**Comment by elliottash** [comment]
this feature doesn't work for me either -- how do i add calendar invites from mailspring to google calendar?

**Comment by yousefamar** [comment]
This problem affects me too (Mailspring + GCal). Seeing as this issue is closed, is there another one that flags the problem?
