### ISSUE TITLE
Cannot Scroll in Server Setup Page After Error

### ISSUE THREAD

**Issue by jGleitz** [Foundry376/Mailspring#124]
If there was an error during the server setup, an error message is shown at the top of the welcome wizard. This shifts the content down, and the buttons thus get out of reach. The window cannot be scrolled, so the user must go back and forth to use the UI again:

![cannot sign in blurred](https://user-images.githubusercontent.com/4305652/31438822-0c19488e-ae8a-11e7-958d-11eff7ce752e.png)

##### Are there any related issues?

The error i encounter is reported in #123

##### What operating system are you using?
Ubuntu 17.04

##### What version of Mailspring are you using?
1.0.3

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
SMTP/IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?

no

**Comment by bengotow** [comment]
Hey thanks for reporting this—yeah, we definitely need to clean this up. This screen is supposed to show error strings from the mailsync client, but if mailsync fails to launch it shows all sorts of garbage. Will see if I can fix this in the next release.
