### ISSUE TITLE
When will Mailspring become fully OpenSource/Libre

### ISSUE THREAD

**Issue by asddsaz** [Foundry376/Mailspring#1241]
Is there any roadmap/time estimate on when Mailspring will become fully [free software](https://en.wikipedia.org/wiki/Free_softwarehttps://www.wikipedia.org/wiki/Free_software) [1](https://github.com/Foundry376/Mailspring/blob/master/ROADMAP.md#why-is-mailsync-closed-source)?

My understanding is that the current blocker is the workload, but can't you just disable issues and ignore pull requests?
For issues most people come here anyway.

**Comment by bengotow** [comment]
Hey! There hasn't been much interest on this front recently.  I think when I add Calendar support next year that'll be entirely on the open-source side (hopefully with lots of community contribution) and I'll see how it goes! A few folks have reached out about the C++ codebase and I've connected them with the source for their projects and experiments, but by and large it's much harder to work with and probably unlikely to benefit from being open sourced. Will keep you posted!

**Comment by beppe9000** [comment]
> the C++ codebase [...] it's much harder to work with and probably unlikely to benefit from being open sourced

The C++ codebase itself may not benefit directly but mailspring will see benefit from improved transparency and build reproducibility.
