### ISSUE TITLE
[Feature request] Add a feature to let users create folders

### ISSUE THREAD

**Issue by caiodev** [Foundry376/Mailspring#1242]
Please, let users be able to create folders and folders within folders. That'll be a great feature to add to Mailspring. Thank you

**Comment by DanPii** [comment]
Hi. I've got the same problem.
Coming from Thunderbird I have a complex folder structure with subfolders.  In Mailspring they are shown "flat" and not "nested".
Also, when creating new folders with this syntax _ExistingFolder/A_, Mailspring shows them "flat".

![image](https://user-images.githubusercontent.com/16837118/51855358-58b0e800-232d-11e9-9afa-ac427715279e.png)

Is there a way to show them "nested".

Thanks,
Daniel

**Comment by mjmfighter** [comment]
@DanPii I just figured out how to make them show "nested".  You need to create a folder called `u1`  (Without the sub folders).  Once you do that, the it will go to a nested folder structure.

**Comment by DanPii** [comment]
@mjmfighter thanks for the feedback. unfortunately that doesn't work for me. I already have an IMAP folder called `u1`. So I can't add another one. In Thunderbird and my Webinterface it is displayed correctly.

**Comment by alfonsomunozpomer** [comment]
As far as I can tell nested folders in many clients (Apple Mail, Thunderbird, Evolution...) use dots in their names to create nested folders. If you have a `folder1` folder and you create a nested one e.g. `folder2` using any of the above clients it is created as `folder1.folder2`. It’d be great if Mailspring did the same.

**Comment by bengotow** [comment]
Hey folks - this is now better supported in Mailspring 1.20.0 (April 2026)! You can create new folders and subfolders directly from the left sidebar — right-click a folder to see a "New Subfolder…" option, or use the new "•••" menu on sidebar items. The UX for creating nested folders has also been significantly improved and the app will auto-detect the separator you need to use.
