### ISSUE TITLE
Action icons disappearing

### ISSUE THREAD

**Issue by Taogrin** [Foundry376/Mailspring#1250]
##### Are there any related issues?

Couldn't find any

##### What operating system are you using?

Windows 8 64-bit

##### What version of Mailspring are you using?

1.5.3-420ce003

--

**Bug?**

Icons of actions on the top bar when viewing email start to disappear and reappear when hovered. They also tend to flicker when hovering mouse over other icons. See the screenshots below.

##### Is this an email sync or connection issue?

Software issue

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
It seems like only I have this issue because my brother also uses Mailspring and he doesn't have this problem.

![screenshot 2018-11-28 15-59-59](https://user-images.githubusercontent.com/28709832/49160660-8d052980-f327-11e8-9270-ab3f53ae1b4a.jpg)
![screenshot 2018-11-28 16-00-20](https://user-images.githubusercontent.com/28709832/49160661-8d052980-f327-11e8-92e0-115e85bb6ef5.jpg)
![screenshot 2018-11-28 16-00-32](https://user-images.githubusercontent.com/28709832/49160663-8d052980-f327-11e8-9ea7-7ce0c3575059.jpg)

--

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—are you using the built-in "Dark" theme? It seems like this might be a CSS issue with the theme, but it seems to be working alright for me. Maybe you have a third-party theme installed? (If so, let me know which one! Maybe we can fix it)

**Comment by Taogrin** [comment]
Well, it happens like that with every theme. I have recently seen that it happens with VSCode also so it may be because of Electron. Maybe its something with my drivers, although I have the newest for the monitor installed

**Comment by bengotow** [comment]
Oh wow - that's super interesting. It sounds like it may be an issue with your graphics card being incompatible with Chromium in some way. I'll look through the Electron project's open issues and see if that narrows it down at all!

**Comment by Taogrin** [comment]
Thank you for response. I will also look today for some solutions

**Comment by Taogrin** [comment]
Managed to find out the issue. I have 2 GPUs and I updated the wrong one. Thank you though for the responses.
