### ISSUE TITLE
[Feature Request] Support that e-mail registration without IMAP/SMTP authentication.

### ISSUE THREAD

**Issue by khpark0203** [Foundry376/Mailspring#1252]
I want to use Mailspring in my office.
But our company don't have SMTP authentication.
So SMTP error always occurs and I don't register my mail.
( Error comment : Please check your SMTP ID and password. )
Please add function that registration without IMAP/SMTP authentication.
Thank you.

This is log
------------------------------
500 5.5.1 Command unrecognized

SMTP Last Response Code: 500

SMTP Last Response: 5.5.1 Command unrecognized

mailsmtp Last Error Code: MAILSMTP_ERROR_UNEXPECTED_CODE

mailsmtp Last Error Location: 10

mailsmtp Last Auth Type: 0

**Comment by Bergg** [comment]
So what kind of protocol does your server use then?

**Comment by bengotow** [comment]
Hi @khpark0203 thanks for reaching out — the latest release of Mailspring (1.5.3) does support SMTP without authentication, but I think the IMAP/SMTP settings form may autofill an SMTP password when you type in your IMAP password. Can you try manually emptying the SMTP password field? That will tell Mailspring that it should not authenticate with your SMTP server.

**Comment by khpark0203** [comment]
I tried what you said, but I failed.
I success Mozilla Thunderbird and Microsoft outlook program and Android gmail app.
I see the information that is our company SMTP server don't need log-in setting.
So, I clean SMTP Username and Password. It was failed...
What should I do?

Thank you

**Comment by bengotow** [comment]
Hey folks! Going to go ahead and close this because Mailspring now supports SMTP without a username and password.
