### ISSUE TITLE
Can't upgrade: TypeError: Cannot read property &#x27; items &#x27; of undefined

### ISSUE THREAD

**Issue by rosslaird** [Foundry376/Mailspring#1253]
##### Are there any related issues?

Nothing similar that I can see on the board.

##### What operating system are you using?

Arch

##### What version of Mailspring are you using?

1.5.3-420ce003

--

**Bug?**

##### Is this an email sync or connection issue?

Nope. I just can't upgrade. Every time I get the same error, after I enter my credit card details:

    TypeError: Cannot read property &#x27; items &#x27; of undefined

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Nope

##### Is the issue reproducible with a particular attachment, message, signature, etc?

It happens every time I try to upgrade (on two different Arch machines). I enter my credit card details, hit the Upgrade button, and I get this:

![screenshot](https://user-images.githubusercontent.com/75513/49259132-f602a500-f3ec-11e8-87c0-d2f8bba86351.png)

I live in Canada, where the postal (zip) codes are six digits instead of 5. I wonder if that could be the issue? It's the only thing I can think of that might be different. Then again, the \&#x27; character is the apostrophe, right? So there might be something different going on.

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Nope.

**Comment by jhubbardsf** [comment]
I'm having the same issue. I'm in America with a 5 digit zip code and using Mailspring 1.5.3 on OS X 10.14.2.

**Comment by bengotow** [comment]
Hey folks—thank you for reporting this. I really appreciate you upgrading to Mailspring Pro.

It looks like this happens if you upgrade to Mailspring Pro and allow your subscription to lapse? When Stripe cancels your plan it deletes the subscription object and Mailspring is unable to switch you back to Pro if you decide to upgrade again later.

Does that sound about right? I'll see if I can get this fixed this afternoon. Thanks!

**Comment by jhubbardsf** [comment]
Yup, my CC changed and I forgot to update it so this sounds right.

**Comment by bengotow** [comment]
The fix for this has been deployed. Thanks again for using Mailspring Pro!
