### ISSUE TITLE
label displayed by "syncking your mailbox" is garbled.

### ISSUE THREAD

**Issue by kometchtech** [Foundry376/Mailspring#126]
##### Are there any related issues?

https://github.com/Foundry376/Mailspring/issues/16
##### What operating system are you using?
...Windows 10 Pro 1703

##### What version of Mailspring are you using?
... 1.0.3

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...Gmail / other IMAP account

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
![syncing](https://user-images.githubusercontent.com/5137077/31440918-7c539b94-aecc-11e7-9cda-51150533d483.JPG)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Ahh good catch - this isn't converting IMAP's UTF7 mailbox names to UTF8. Fixed by 797f86c698aa3ae031f6cf06d081033c555ad2f6

**Comment by kometchtech** [comment]
Thank you.
I confirmed that it was fixed in 1.0.4.
