### ISSUE TITLE
Advanced search not working

### ISSUE THREAD

**Issue by federicoiosue** [Foundry376/Mailspring#1260]
##### Are there any related issues?

Nope

##### What operating system are you using?

MacOS Mojave 10.14.2 (18C54)

##### What version of Mailspring are you using?

1.5.2

**Bug?**

##### Is this an email sync or connection issue?

Nope, the email content is synchronized correctly

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Nope. Tested both with Gmail and Exchange accounts, separately and restoring local data between attempts.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

1. Installed Mailspring
2. Added account (Gmail or Exchange)
3. Tried advanced search queries: all works correcly except than *has:attachment*

![mailspring](https://user-images.githubusercontent.com/487104/49724121-dbd88a80-fc68-11e8-9046-ff1a2cd93bc0.png)

![mailspring_has_attachment copia](https://user-images.githubusercontent.com/487104/49724127-df6c1180-fc68-11e8-9e06-74d49775efb5.png)

**Comment by bengotow** [comment]
Hey—thanks for reporting this! It looks like `has:attachment` is definitely broken. I'll see if I can get this fixed in the next release. I think that `has:attachment` may only work for messages that Mailspring has fetched the full content for (the last three months of mail), but it looks like the query conversion is broken. Stay tuned!

**Comment by federicoiosue** [comment]
Thanks for the feedback I'll wait for the fix.
Great job!

**Comment by bengotow** [comment]
Hey! The fix for this shipped in v1.5.4 this afternoon. Mailspring should auto-update in the next few hours and you can also download the update directly from https://getmailspring.com/download. Happy new years!

**Comment by mchaisso** [comment]
This seems still broken in Ubuntu 1.5.5-b7939d38

**Comment by bengotow** [comment]
Hey folks - @Chrismarsh opened a new issue to track the problem and it'll be resolved in the next release. Stay tuned!
