### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by toma3757** [Foundry376/Mailspring#1261]
Hi!
I forgot my Mailspring ID password and tried to reset it but that seems impossible now.
I got the "Reset your Mailspring ID Password" email, I click the link, fill the forms and got this error:
"Sorry, you must arrive at this page by clicking a reset link."
Any suggestions?
Thanks

**Comment by bengotow** [comment]
Hey @toma3757 thanks for reporting this—let me go through this and see what's going on!

**Comment by bengotow** [comment]
Hi @toma3757, I've gone through the password reset flow a few times and it's working for me. Can you verify that when you click the link in the email you see your `emailAddress` and a `key` in the URL bar? It sounds like the URL must be malformed in some way and those two parts of the link are missing?

**Comment by toma3757** [comment]
Dear @bengotow,
Now it's working, i did the same things but actually it was successfully reseted.
Thanks!

**Comment by ex1st** [comment]
Hello @bengotow, doesn't work again.
