### ISSUE TITLE
Extra line above signature in replies

### ISSUE THREAD

**Issue by NikolaiSzabados** [Foundry376/Mailspring#1264]
##### Are there any related issues?

No

...

##### What operating system are you using?
Windows 10 Pro
...

##### What version of Mailspring are you using?
1.53-420
...

--

**Bug?**

##### Is this an email sync or connection issue?

No

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I have an HTML signature set. When composing a new email, the number of blank lines above the signature is as expected (two).

When composing a reply, an additional blank line is automatically added (so 3 in total) which means always deleting a blank line before sending a reply

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
HTML sigs display consistently in all other email clients I've used.
...

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - I've been able to reproduce this and I'll see what's going on. It definitely seems like it should be two at all times.

**Comment by bengotow** [comment]
Hey! The fix for this shipped in v1.5.4 this afternoon. Mailspring should auto-update in the next few hours and you can also download the update directly from https://getmailspring.com/download. Happy new years!

**Comment by NikolaiSzabados** [comment]
Thanks for the quick fix; it's these small things that affect the speed of reading/writing email! Happy New Year!
