### ISSUE TITLE
Add support for AutoCrypt Level 1

### ISSUE THREAD

**Issue by jeroen7s** [Foundry376/Mailspring#1265]
https://autocrypt.org/index.html
seems to be implemented in EnigMail and MailPile, as well as K9-mail
seems like the first proper way to secure emails without dealing with manual key sharing issues like regular PGP

**Comment by bengotow** [comment]
Hey! I think this would be great. I'm hoping to bring built-in support for message signing (and possibly encryption) to Mailspring in 2019, will see if we can use this. For now I'm going to merge this in to #25 where the broader PGP / security discussion is!
