### ISSUE TITLE
Encountered an error while syncing

### ISSUE THREAD

**Issue by marcvk** [Foundry376/Mailspring#1266]
##### Are there any related issues?
I don't think so, the issues with similar titles all have different descriptions or stack traces.

##### What operating system are you using?
Arch Linux, 4.19.2-arch1-1-ARCH

##### What version of Mailspring are you using?
1.5.3-420ce003

**Bug?**
Yes

##### Is this an email sync or connection issue?
email sync

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I can login, sync my inbox (and others folders), but after a while, I'm guessing it takes a while before it gets to the problematic folder/message it issues the error message.

The problem is with gmail. I've tried clearing the cache, but after a while I get the same error.

"Encountered an error while syncing marc@bowtie.nl"

##### Is the issue reproducible with a particular attachment, message, signature, etc?
It always seems to crash on the All Mail folder, it's 100% reproducible.

See stacktrace below:

28321 [2018-12-11 16:37:49.880] [main] [info] Identity created at 1544290798 - using ID Schema 1
28321 [2018-12-11 16:37:49.881] [main] [info] ------------- Starting Sync (marc@bowtie.nl) ---------------
28321 [2018-12-11 16:37:49.885] [background] [info] Fetching XOAuth2 access token from Gmail for 78ca6026
28321 [2018-12-11 16:37:49.885] [metadata] [info] Metadata delta stream starting...
28321 [2018-12-11 16:37:50.191] [background] [info] Marking all folders as `busy`
28321 [2018-12-11 16:37:50.193] [background] [info] Syncing folder list...
28321 [2018-12-11 16:37:51.458] [background] [info] Syncing folder list...
28321 [2018-12-11 16:37:52.601] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/All Mail: modseq 18264986 to 18264986, uidnext 430626 to 430626
28321 [2018-12-11 16:37:54.222] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** ??:?     MailUtils::idForFile(Message*, mailcore::Attachment*)
 *** ??:?     File::File(Message*, mailcore::Attachment*)
 *** ??:?     MailProcessor::retrievedMessageBody(Message*, mailcore::MessageParser*)
 *** ??:?     SyncWorker::syncMessageBody(Message*)
 *** ??:?     SyncWorker::syncMessageBodies(Folder&, mailcore::IMAPFolderStatus&)
 *** ??:?     SyncWorker::syncNow()
 *** ??:?     runBackgroundSyncWorker()
 *** (unknown)  clone
 ***

**Comment by marcvk** [comment]
[mailsync-78ca6026.zip](https://github.com/Foundry376/Mailspring/files/2668351/mailsync-78ca6026.zip)

**Comment by bengotow** [comment]
Hey @marcvk — thanks for reporting this (and for the logs!) I love when we're able to track these sort of things down. Looking at that method, it looks like you must have an email in your mailbox which has an attachment that has no MIME part Content-ID or Unique-ID and Mailspring is using them to create a stable way to refer to the attachment. I think we can work around this - will get this fixed in the next release!

**Comment by marcvk** [comment]
Hi @bengotow thank for the quick response and fix! And happy to help get this sorted.
Do you want me to test this before you release it?

**Comment by bengotow** [comment]
Hey! The fix for this shipped in v1.5.4 this afternoon. Mailspring should auto-update in the next few hours and you can also download the update directly from https://getmailspring.com/download. Happy new years!
