### ISSUE TITLE
MailSpring Could not store your password securely

### ISSUE THREAD

**Issue by fly1688** [Foundry376/Mailspring#1267]
##### Are there any related issues?

MAC 10.14.1 in the master branch of the system, execute yarn install, and then yarn start the program by telling MailSpring Could not store your password password

##### What operating system are you using?

MacOS 10.14.1

##### What version of Mailspring are you using?

master

--

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this doesn't usually cause problems on macOS... could you try opening the app "Keychain Access" on your computer (it may be in Applications/Utilities) and verify that you're able to unlock your `login` keychain?

<img width="243" alt="image" src="https://user-images.githubusercontent.com/1037212/50133364-2006f480-0240-11e9-84e5-0ade3607305a.png">

Mailspring stores your email passwords there, and usually as long as your Mac keychain is set up properly that works.

**Comment by Jesterjke** [comment]
Had the same issue on macOS 10.14.3 building from master, not sure what exactly helped, but eventually solved by removing app completely (including cache and data folders), removing Mailspring entry from the keychain and then logout/login.
