### ISSUE TITLE
Send email sometimes not work

### ISSUE THREAD

**Issue by paulux84** [Foundry376/Mailspring#1269]
Sometimes send an email cause no message is sent and new email form appear with no text...so i lost my message and must rewrite the email from scratch

**Comment by bengotow** [comment]
Hey @paulux84 thanks for filing this! Sorry to hear you ran in to this. We actually just fixed this in #948 and the fix will ship this week. Stay tuned! a27710f57064a1d97448df8ff84052d2a7f45ef5

**Comment by bengotow** [comment]
Hey folks—the fix for this shipped in v1.5.4 this afternoon. Mailspring should auto-update in the next few hours and you can also download the update directly from https://getmailspring.com/download. Happy new years!
