### ISSUE TITLE
Invalid rendering of special (romanian) characters in contact information

### ISSUE THREAD

**Issue by oserban** [Foundry376/Mailspring#127]
##### What operating system are you using?
Ubuntu 16.05

##### What version of Mailspring are you using?
1.0.3

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

My name as probably other names contains a special character in Romanian (Ț, ț, Ș, ș). At the moment, this is not rendered properly in the side bar contact information (contact selection dropdown, etc.) and a ? appears instead. I am sure this is a font issue, but it is slightly annoying. 

This works fine in the compose area.

**Comment by bengotow** [comment]
Hey! Thanks for filing this—I'll see if we can reproduce this and get it fixed in the next version.

**Comment by oserban** [comment]
The latest version fixes the issue somehow
