### ISSUE TITLE
Support multiple consecutive spaces in composed emails

### ISSUE THREAD

**Issue by M-Pixel** [Foundry376/Mailspring#1270]
##### What version of Mailspring are you using?

1.5.3-420ce003

--

When I type multiple spaces in a row in an email, which I might do for several reasons (spacing images out, using 2-space-after-period writing style, code snippets...), they are collapsed down into a single space once the email is sent.  Whether through `<pre>` or `&nbsp;`, please support the ability to send emails that contain `[^ ] +[^ ]` instead of just `[^ ] [^]`.

##### Does this feature exist in another mail client or tool you use?

Yes, most if not all.

**Comment by bengotow** [comment]
Hey! Wow, thanks for filing this - I can't believe I hadn't noticed this! I was able to reproduce the problem and you're definitely right. An email sent from Gmail includes &nbsp spaces:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/1037212/50132390-cbfa1100-023b-11e9-9b6c-34b79f2d7d7e.png">

And one sent from Mailspring contains whitespace, but the spaces are collapsed when rendered as HTML:

<img width="374" alt="image" src="https://user-images.githubusercontent.com/1037212/50132386-c56b9980-023b-11e9-9041-457afba9f250.png">

My go-to approach is to copy Gmail, so I'll see if I can make Mailspring's composer insert &nbsp; as well. Stay tuned!

**Comment by bengotow** [comment]
Hey folks—the fix for this shipped in v1.5.4 this afternoon. Mailspring should auto-update in the next few hours and you can also download the update directly from https://getmailspring.com/download. Happy new years!
