### ISSUE TITLE
Plain text mail composer editor

### ISSUE THREAD

**Issue by MurzNN** [Foundry376/Mailspring#1273]
Some users prefer to compose email in plain text mode, so many email apps have option for disable rich-text editors (by default, or on demand when editing mail) and compose mail in plain text via simple editor. Will be good to have same feature in Mailspring too, because now I can't find the way to disable wysiwyg editor when composing mail.

**Comment by bengotow** [comment]
Hey! Thanks for filing this - I think we'll definitely add this at some point in the future. Merging this in to #52. Cheers!
