### ISSUE TITLE
[Feature Request] Embeded Images, css and js should be disabled by default

### ISSUE THREAD

**Issue by oserban** [Foundry376/Mailspring#128]
For security reasons, the embedded images, css and js should be disabled.
The user should be shown a menu/button to download them if the source is trusted.

**Comment by bengotow** [comment]
Hey @oserban — this is something you're welcome to disable in Preferences > General, but most users prefer having these features enabled by default. If we turn them off, I'll get like a hundred emails from folks asking why they don't see any pictures in their messages.

It should be noted though that Javascript in messages is **never** allowed.
