### ISSUE TITLE
"Terms of Service" and "Privacy Policy" links do not work

### ISSUE THREAD

**Issue by Schyken** [Foundry376/Mailspring#1280]
##### What operating system are you using?
Linux (openSUSE Tumbleweed 2018-22-18)
...

##### What version of Mailspring are you using?
1.5.3-420ce003
...

**Bug?**
The "Terms of Service" and "Privacy Policy" links in the Mailspring client for account creation do not work.

![image](https://user-images.githubusercontent.com/20944747/50372351-75b60680-058a-11e9-942b-83d7224a9fa5.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—will get this fixed ASAP! I'm not sure what happened here, but it looks like this must have broken in a recent Electron upgrade.

**Comment by Schyken** [comment]
Fantastic! Much appreciated, thanks for the quick action as well. Best email client around, you are all doing great!

**Comment by bengotow** [comment]
Hey folks—the fix for this shipped in v1.5.4 this afternoon. Mailspring should auto-update in the next few hours and you can also download the update directly from https://getmailspring.com/download. Happy new years!
