### ISSUE TITLE
"Terms of Service" and "Privacy Policy" links on first-use signup screen don't work

### ISSUE THREAD

**Issue by stuartlangridge** [Foundry376/Mailspring#1281]
##### Are there any related issues?

...

##### What operating system are you using?
Ubuntu 18.04
...

##### What version of Mailspring are you using?
1.5.3
...

--

**Bug?**

On the first use of Mailspring, on the screen where I must sign up for a Mailspring ID, it has "By creating an account, you agree to the Mailspring Terms of Service and Privacy Policy". "Terms of Service" and "Privacy Policy" are both links (they are in a slightly lighter grey, and I get a hand cursor on hover) but clicking them doesn't do anything, either in the app itself or opening pages in the system browser.

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No
--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by bengotow** [comment]
Merging this in to #1280
