### ISSUE TITLE
Can't insert pictures in email

### ISSUE THREAD

**Issue by Yonezpt** [Foundry376/Mailspring#1283]
I am using MS 1.5.3 on Win7x64 and for the life of me I cannot find a way - documented or not - on how I can insert images in my email replies. I can attach images just fine, but if I want those images to be shown in the email itself there appears to be absolutely no way to do it using MailSpring. I had to drop the MS email client and use the web version of hotmail just so that I could insert images in my emails.

Is this a bug, intended and/or undocumented?

**Comment by bengotow** [comment]
Hey @Yonezpt! Thanks for filing this—right now you can add images inline by copy-pasting or dragging and dropping into the draft body (JPG or GIF images, less than 5MB will appear inline), but the "add attachment" button always attaches images to the end of the draft. I'll see if we can make this a bit more intuitive in the future!

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
