### ISSUE TITLE
Cannot disable email tracking

### ISSUE THREAD

**Issue by Yonezpt** [Foundry376/Mailspring#1289]
I am unable to find in the settings how I can disable email read tracking. I am using MailSpring 1.5.4 on Win7x64 and no documentation mentions anything about how this kind of tracking can be turned off.

I am not interested in knowing when others read my email especially when default email clients no longer load external images by default, rendering this feature quite useless.

How can I stop tracking when users read my emails?

**Comment by bengotow** [comment]
Hey! Thanks for filing this—here's what you need to know:

- To stop others from knowing if you read their emails: Go to Mailspring's preferences and in the General tab uncheck "Automatically load images in viewed messages."

<img width="524" alt="image" src="https://user-images.githubusercontent.com/1037212/50543244-5299e100-0ba0-11e9-9c9f-c7080109c504.png">

- To stop Mailspring from adding open and link tracking to emails you send, click both of these blue icons in the composer to turn those features off. Once it's turned off, they'll remain off in new drafts until you turn them back on again:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/1037212/50543250-765d2700-0ba0-11e9-91c6-847fc26eddd7.png">

Hope that helps!
