### ISSUE TITLE
Change Images in Empty Inbox?

### ISSUE THREAD

**Issue by ponmy** [Foundry376/Mailspring#1293]
Is it possible to change and/or remove the images which appear when the inbox is empty?  Possibly through the themes tool?
![snip_20181230174406](https://user-images.githubusercontent.com/43487371/50552923-8d604f80-0c5a-11e9-8fce-86dafa053a45.png)

**Comment by bengotow** [comment]
Hey! This isn't currently possible, but theoretically a theme could probably use a complex `::after` CSS rule to add a custom empty image. Will see if we can add better support for this soon!
