### ISSUE TITLE
1.5.4: E-mail text is black against dark grey background with Dark theme

### ISSUE THREAD

**Issue by krupenja** [Foundry376/Mailspring#1294]
##### Are there any related issues?

Not sure.

##### What operating system are you using?

Ubuntu 18.10

##### What version of Mailspring are you using?

1.5.4-1d923cf4, DEB package

##### Steps to reproduce

1. Open Mailspring.
2. Change theme to Dark.
3. Open any non-HTML e-mail.

The text is black against dark grey background, almost unreadable. This is a regression, have not seen this before 1.5.4.

**Comment by MichaelTunnell** [comment]
I am having the exact same issue. I have been using the Dark Theme for a while and it worked great until a couple days ago it started doing this making it VERY hard to read without highlighting.

**Operating System**: I am using KDE Neon (based on Ubuntu LTS)

**Mailspring Version**: 1.5.4 - using the .snap by foundry376✓

**Steps to reproduce**: same as above, simply open the app and turn to dark theme to see the error of text being very hard to read.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this guys—will see if we can get this fixed ASAP. Going to merge this in to #1290

**Comment by MichaelTunnell** [comment]
I am following up because I recently switched back to the dark theme after upgrading to Mailspring 1.5.5 and the dark theme works just fine again so thank you very much! :sunglasses: :+1:
