### ISSUE TITLE
Mailspring 1.5.4 rpm package

### ISSUE THREAD

**Issue by mthomos** [Foundry376/Mailspring#1297]
Where is the rpm package ?

**Comment by mthomos** [comment]
Basically it's here but the link doesn't appear in releases

https://github.com/Foundry376/Mailspring/releases/download/1.5.4/mailspring-1.5.4-0.1.x86_64.rpm

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - it looks like GitHub is... angry about it for some reason?

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1037212/50612221-14e1d480-0e8e-11e9-9e7d-052c470e1412.png">

Will do as it says and see if it fixes it.
