### ISSUE TITLE
Compose window shows menu bar

### ISSUE THREAD

**Issue by jbreitbart** [Foundry376/Mailspring#1301]
I have turned of the title bar in the settings, but when I compose a new email it still shows the menu bar. Here is a screenshot:

![screenshot von 2019-01-04 11 53 21](https://user-images.githubusercontent.com/881727/50685038-fe678480-1017-11e9-8666-98b348a4d354.png)

I would expect that the setting also turns it of for all Mailspring windows.

**Comment by ukrsup** [comment]
I have the same behavior.
App version: 1.7.6

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
