### ISSUE TITLE
Listed as a proprietary software on Snapcraft

### ISSUE THREAD

**Issue by avronr** [Foundry376/Mailspring#1303]
![image](https://user-images.githubusercontent.com/32333507/50724562-a747d980-1115-11e9-944c-0a39cfae053e.png)

Hey,

The application is listed as a proprietary software on snapcraft store whereas the license on github page is GPL.

Regards,
Abraham Raji

**Comment by paride** [comment]
Only the UI is released under the GPL, the "Sync Engine" is proprietary, unfortunately. See https://github.com/Foundry376/Mailspring/blob/master/LICENSE-mailsync.md.
