### ISSUE TITLE
Copy-pasting content from received email to composer has wrong style

### ISSUE THREAD

**Issue by federicoiosue** [Foundry376/Mailspring#1309]
##### Are there any related issues?

Not sure if is related to [this](https://github.com/Foundry376/Mailspring/issues/641) or [this](https://github.com/Foundry376/Mailspring/issues/1053) older issue or [this](https://github.com/Foundry376/Mailspring/issues/1290) one that is more recent due to Electron version change.

##### What operating system are you using?

MacOS Mojave

##### What version of Mailspring are you using?

1.5.5

**Bug?**

##### Is this an email sync or connection issue?

Nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Nope, it's a generalized issue

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Copy text from any received message and paste into composer results in dark color. Selecting it and setting black (or whatever) color from text formatting fixes it.

![mailspring_e_mailspring_e_mailspring_ _content_color_copy-paste_test](https://user-images.githubusercontent.com/487104/50823605-a640c300-1334-11e9-9d93-87f02c71b74c.png)

**Comment by federicoiosue** [comment]
I'm reporting in new issue just because some time has passed and they're still not marked as closed. Eventually close this one.

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!
