### ISSUE TITLE
High RAM consumption and message "Syncing your mailbox..." never disappear

### ISSUE THREAD

**Issue by thbtmntgn** [Foundry376/Mailspring#131]
Hi guys,

I've been using Mailspring since a week now.
I can send/receive emails and search in my email archive.

All my emails seem to be there but Mailspring is still syncing the only account I added: the message "**_Syncing your mailbox..._**" never disappear.

Like in issue #91, it seems that there is a problem with memory.
I saw Mailspring using almost 12 of the 16 GB of RAM my computer have and I saw the swap memory at more than 50GB.

##### Are there any related issues?

Yes, issue #91 is related to the high RAM consumption

##### What operating system are you using?
macOS High Sierra 10.13

##### What version of Mailspring are you using?
1.0.3

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I synced only one account

##### Is the issue reproducible with a particular attachment, message, signature, etc?

<img width="1022" alt="capture d ecran 2017-10-11 a 21 50 24" src="https://user-images.githubusercontent.com/18198843/31463968-30cc3268-aed0-11e7-9fe3-1e046a9a41dd.png">
<img width="1016" alt="capture d ecran 2017-10-11 a 21 53 06" src="https://user-images.githubusercontent.com/18198843/31463969-30f17c12-aed0-11e7-8d48-40644cdd3c54.png">
<img width="1018" alt="capture d ecran 2017-10-11 a 21 53 33" src="https://user-images.githubusercontent.com/18198843/31463970-311b10ae-aed0-11e7-843e-dcdd0c1e33ed.png">

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No

**Comment by bengotow** [comment]
Merging into #91 since this seems to be a dup!
