### ISSUE TITLE
Problem with adding imap account

### ISSUE THREAD

**Issue by lukaszgadek** [Foundry376/Mailspring#1310]
...

##### What operating system are you using?
Ubuntu mate 18.10
...

##### What version of Mailspring are you using?
1.5.5 edge
...

--

**Bug?**
I try to add imap account but i still has problem with it:
![image](https://user-images.githubusercontent.com/46481010/50831698-0b53e300-134c-11e9-9bc8-daa6abc26415.png)
LOG:
`----------IMAP----------
* OK serwer1422072.home.pl IdeaImapServer 0.83.183 ready
1 CAPABILITY
* CAPABILITY IMAP4rev1 LITERAL+ CHILDREN I18NLEVEL=1 IDLE SORT SORT=DISPLAY UIDPLUS UNSELECT QUOTA MOVE WITHIN LIST-EXTENDED LIST-STATUS SPECIAL-USE XLIST STARTTLS AUTH=PLAIN AUTH=LOGIN
1 OK Completed
2 LOGIN "lukasz.gadek@itd24.pl" *********
* CAPABILITY IMAP4rev1 LITERAL+ CHILDREN I18NLEVEL=1 IDLE SORT SORT=DISPLAY UIDPLUS UNSELECT QUOTA MOVE WITHIN LIST-EXTENDED LIST-STATUS SPECIAL-USE XLIST STARTTLS
2 OK Completed
3 LIST "" ""
* LIST (\Noselect) "." ""
3 OK Completed
4 XLIST "" "*"
* XLIST (\HasNoChildren \) "." "Archiwum"
* XLIST (\HasNoChildren \Draft) "." "DRAFTS"
* XLIST (\HasNoChildren \) "." "Drafts"
* XLIST (\HasNoChildren \Inbox) "." "INBOX"
* XLIST (\HasNoChildren \Sent) "." "SENT"
* XLIST (\HasNoChildren \Spam) "." "SPAM"
* XLIST (\HasNoChildren \Trash) "." "TRASH"
* XLIST (\HasNoChildren \) "." "Wersje robocze"
4 OK Completed
XLIST (\HasNoChildren \) "." "Archiwum"`

When i did add gmail account it passed without problem. But on normal imap i cant do that ;/

Anyone did solve this problem ?

**Comment by lukaszgadek** [comment]
I did change system:

![image](https://user-images.githubusercontent.com/46481010/50884092-312fc500-13ea-11e9-8d8f-0e5b5c1cd31e.png)

And still the same problem...

> ----------IMAP----------
* OK serwer1422072.home.pl IdeaImapServer 0.83.183 ready
1 CAPABILITY
* CAPABILITY IMAP4rev1 LITERAL+ CHILDREN I18NLEVEL=1 IDLE SORT SORT=DISPLAY UIDPLUS UNSELECT QUOTA MOVE WITHIN LIST-EXTENDED LIST-STATUS SPECIAL-USE XLIST STARTTLS AUTH=PLAIN AUTH=LOGIN
1 OK Completed
2 LOGIN "lukasz.gadek@itd24.pl" *********
* CAPABILITY IMAP4rev1 LITERAL+ CHILDREN I18NLEVEL=1 IDLE SORT SORT=DISPLAY UIDPLUS UNSELECT QUOTA MOVE WITHIN LIST-EXTENDED LIST-STATUS SPECIAL-USE XLIST STARTTLS
2 OK Completed
3 LIST "" ""
* LIST (\Noselect) "." ""
3 OK Completed
4 XLIST "" "*"
* XLIST (\HasNoChildren \) "." "Archiwum"
* XLIST (\HasNoChildren \Draft) "." "DRAFTS"
* XLIST (\HasNoChildren \) "." "Drafts"
* XLIST (\HasNoChildren \Inbox) "." "INBOX"
* XLIST (\HasNoChildren \Sent) "." "SENT"
* XLIST (\HasNoChildren \Spam) "." "SPAM"
* XLIST (\HasNoChildren \Trash) "." "TRASH"
* XLIST (\HasNoChildren \) "." "Wersje robocze"
4 OK Completed
XLIST (\HasNoChildren \) "." "Archiwum"

> 

I should make some changes in mail account or what?

**Comment by dtokarczyk** [comment]
This issue is duplicate #967

**Comment by bengotow** [comment]
Hey @lukaszgadek this has been fixed in 1.5.6. Enjoy the update!
