### ISSUE TITLE
[Feature Request] Desktop Actions Menu

### ISSUE THREAD

**Issue by alecbcs** [Foundry376/Mailspring#1311]
##### What operating system are you using?

Solus (Linux)

##### What version of Mailspring are you using?

1.5.5

---

**Feature Request?**

Currently Mailspring only supports actions through the system tray icon. It would really useful if we could expose those same actions through the desktop file as well to enable the same actions menu by right-clicking the desktop icon. As part of Solus we are [trying to improve desktop actions on Linux](https://dev.getsol.us/T7289).
For example how Firefox exposes the "new tab" action.

![screenshot from 2019-01-08 16-03-04](https://user-images.githubusercontent.com/19558067/50864480-67743280-135f-11e9-9351-36c9f9246f56.png)

![screenshot from 2019-01-08 16-03-33](https://user-images.githubusercontent.com/19558067/50864511-7ce95c80-135f-11e9-8fd5-1f22e3250d70.png)

![screenshot from 2019-01-08 16-07-51](https://user-images.githubusercontent.com/19558067/50864581-b4f09f80-135f-11e9-9554-ca80aaae2883.png)

**Comment by bengotow** [comment]
Hey! I'd be happy to accept a pull request for this if anyone wants to tackle it!

**Comment by Phylu** [comment]
@CodeMouse92 Please close this directly instead of moving to discourse as already resolved with the open PR.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
