### ISSUE TITLE
Not showing emails I have sent in the sent folder (Office 365 business account).

### ISSUE THREAD

**Issue by Shickmo** [Foundry376/Mailspring#132]
##### Are there any related issues?
No

##### What operating system are you using?
Ubuntu Mate 17.04

##### What version of Mailspring are you using?
1.03-f82c8836

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
This is an Office 365 business account.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No basically I just sent an email to a friend of mine, saw the read receipt notification pop up, so I know they received the message but it was not saved to the send folder. I also confirmed that there was not a sync of the sent folder or anything going on so it doesn't appear like it just hadn't shown up yet it just wasn't showing at all in sent.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes, all of them to my knowledge :) .

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—I think Mailspring is probably choosing the wrong Sent folder. Can you try downloading the shiny new v1.0.4 release (getmailspring.com/download)? It includes the ability to manually select your Sent folder, and that might do the trick for you: https://foundry376.zendesk.com/hc/en-us/articles/115002039131-Mailspring-isn-t-showing-the-correct-messages-in-my-Sent-or-Drafts-or-Trash-folder-

**Comment by bengotow** [comment]
(Also, if that does turn out to be the issue, could you let me know what the correct sent folder was in that list in Preferences > Folders? We should definitely make it correct by default.)

**Comment by Shickmo** [comment]
Hi @bengotow ,

I can confirm that upgrading to 1.0.4 resolved the issue and to clarify I didn't have to manually select the Send Folder it picked it up automatically :) . Thanks so much for the insanely quick turn around on this.
