### ISSUE TITLE
Inline / attachment images not displayed by recipient

### ISSUE THREAD

**Issue by martinkoutecky** [Foundry376/Mailspring#1325]
With MS 1.5.5 on Linux, when I copy&paste an image (tried from two different sources) into a message, it appears correctly in the composer, but is not displayed by the recipient (tried a Gmail account and another account accessed using Roundcube). When the same image is sent as an attachment, roundcube shows its correct preview, but then fails opening it saying "The image ... cannot be displayed because it contains errors." When the file is downloaded it displays fine. It can be accessed here: https://i.imgur.com/Thcrxc7.png.

##### What operating system are you using?

Sabayon Linux, using the Debian build converted through the alien tool.

##### What version of Mailspring are you using?
1.5.5

**Comment by bengotow** [comment]
Hey @martinkoutecky sorry for the delay replying here - could you do me a favor and try this in the latest version of Mailspring? If you could paste in the image and send an email to ben@foundry376.com I can inspect the raw MIME of the message that is delivered and see what's going on. Thanks!

**Comment by p3k** [comment]
hi @bengotow i am experiencing a similar issue with version 1.7.2-4522b259 on ubuntu (see below for more details).

when i copy&paste an image from my personal google photos collection into a mailspring message it is display while editing, but “disappears” after sending / being opened by the recipient.

when i download / save and then attach the image via file chooser the image is displayed at the recipient’s side.

this is what two messages look like in a gmail inbox listing showing the differences between a message with attached image (test 3), and one with pasted image (test 4):

![image](https://user-images.githubusercontent.com/16631/74022461-e4783e00-499d-11ea-97cf-d363b80c872c.png)

this is what the raw messages look like in my imap directory:

## test 3 (attached image, showing at recipient)

```plain
→ less Maildir/Sent/cur/1581071227.M949544P29648.zicke\,S=210023\,W=212774:2\,S
Date: Fri, 7 Feb 2020 11:27:01 +0100
From: =?utf-8?Q?Tobi_Sch=C3=A4fer?= <sender@redacted>
To: "=?utf-8?Q?recipient=40redacted?=" <recipient@redacted>
Message-ID: <redacted@getmailspring.com>
Subject: test 3
X-Mailer: Mailspring
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="5e3d3b75_7f73a292_3227"

--5e3d3b75_7f73a292_3227
Content-Type: multipart/alternative; boundary="5e3d3b75_2d5f855d_3227"

--5e3d3b75_2d5f855d_3227
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
Content-Disposition: inline



--5e3d3b75_2d5f855d_3227
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

<br>
--5e3d3b75_2d5f855d_3227--

--5e3d3b75_7f73a292_3227
Content-Type: image/jpeg
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="=?utf-8?Q?IMG=5F20200206=5F092357.jpg?="

/9j/4AAQSkZJRgABAQAAAQABAAD/4QAqRXhpZgAASUkqAAgAAAABADEBAgAHAAAAGgAAAAAAAABH
b29nbGUAAP/bAIQAAwICCgoKCAoKCgoKCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI
CggICAgKCgoICA0NCggNCAgJCAEDBAQGBQYIBgYKDQgICAgICAgICA0ICAgICAgICAgICAgICAgI
… (lots of more lines)
WuyjE4oggDQhpPWRPzRSMgJEATeOfO8eKucJptIfP4s3jHT5KajAM0CJayY6kz5wEWDFp3Jv5LfE
xVwzYLmizXEiI0Jm/fCA4ctdYwIseg0HjyV/FsEA76z1WZVrm3+qI20WLyrLSNMf0z3/ACUK7wzD
hwcTs4i3K36qVnR//9k=

--5e3d3b75_7f73a292_3227--
```

## test 4 (pasted image, not showing at recipient)

```plain
→ less Maildir/Sent/cur/1581071319.M668192P29648.zicke\,S=1494\,W=1528:2\,S
Date: Fri, 7 Feb 2020 11:28:34 +0100
From: =?utf-8?Q?Tobi_Sch=C3=A4fer?= <sender@redacted>
To: "=?utf-8?Q?recipient=40redacted?=" <recipient@redacted>
Message-ID: <redacted@getmailspring.com>
Subject: test 4
X-Mailer: Mailspring
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="5e3d3bd2_3b957a7d_3227"

--5e3d3bd2_3b957a7d_3227
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit
Content-Disposition: inline



--5e3d3bd2_3b957a7d_3227
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

<div><img src=3D=22https://lh3.googleusercontent.com/iPpOI=46njD-uv6epJla=
RAa7dEmAmP54t-Ra9eKVt-awyTEGfRTbcwt5oS5Q2crfpzm1ndZVg=5F7M1UokxzSIxTERaAR=
PnuujBi1adOJL12hu6=46vIc7ni1LBe7wGHqKYb6XK212VhQuL0pNJEkKt6mATaV9jvBIW1Sd=
NnCA=46NQ61HOATV5BuAldXAe=5Fvfl-rjO7pBBagjCRyp0b87L=46qpMoYp6C2ZU0Kf2v-cw=
o579B2Rykfxj4Ix-vDxzaoycSl5=5FgwG1KEDJ8Mpuushd=5FpEZRzqDcj2vcch=5FTQ3Xj5e=
LViEoZByP4JPL=5F5wTK11PR9epENDrW5v3W=46cA4igXwi-sVdvrkBMNWwD53=5FuSm77nJ2=
1Gs9U3SI4TuSm8MEiph4Gt9MD27uTJrfDKPw0LjIo=465aqn8iw05IsgsB5Al4rHPlivQj=46=
QLGPBbCrXhY5VZET1-pxfuzJce2--62wfQEQwxc=46k6U7mjGUrnpRlI0befH1E=46z-RjZcS=
2=46IUfKwl=5FdNSNotx6z=46uhTG-NmO5YO9=46iUoYHzMo5n9jQKcA9uNheGCPVOqqaINhW=
0r0DrBR23GwNZKPSj8ynjl13eNcaW1Wgvijo4iUinLq1OqBBcOYutaR7k9LJvJJpwnsknAnqp=
jKExBevzjv7wBA=5FQiQm0iUWCPwK3SSQ288Vbe1znYKRTD=5FdnU6Cu=5Fco1Yk=3Dw1700-=
h956-no=22></div>
```

interestingly, the url in the `<img src>` attribute seems to be fine – if i decode the quoted printable format i get the correct url which can be opened without issues:

https://lh3.googleusercontent.com/iPpOIFnjD-uv6epJlaRAa7dEmAmP54t-Ra9eKVt-awyTEGfRTbcwt5oS5Q2crfpzm1ndZVg_7M1UokxzSIxTERaARPnuujBi1adOJL12hu6FvIc7ni1LBe7wGHqKYb6XK212VhQuL0pNJEkKt6mATaV9jvBIW1SdNnCAFNQ61HOATV5BuAldXAe_vfl-rjO7pBBagjCRyp0b87LFqpMoYp6C2ZU0Kf2v-cwo579B2Rykfxj4Ix-vDxzaoycSl5_gwG1KEDJ8Mpuushd_pEZRzqDcj2vcch_TQ3Xj5eLViEoZByP4JPL_5wTK11PR9epENDrW5v3WFcA4igXwi-sVdvrkBMNWwD53_uSm77nJ21Gs9U3SI4TuSm8MEiph4Gt9MD27uTJrfDKPw0LjIoF5aqn8iw05IsgsB5Al4rHPlivQjFQLGPBbCrXhY5VZET1-pxfuzJce2--62wfQEQwxcFk6U7mjGUrnpRlI0befH1EFz-RjZcS2FIUfKwl_dNSNotx6zFuhTG-NmO5YO9FiUoYHzMo5n9jQKcA9uNheGCPVOqqaINhW0r0DrBR23GwNZKPSj8ynjl13eNcaW1Wgvijo4iUinLq1OqBBcOYutaR7k9LJvJJpwnsknAnqpjKExBevzjv7wBA_QiQm0iUWCPwK3SSQ288Vbe1znYKRTD_dnU6Cu_co1Yk=w1700-h956-no

please let me know if i could provide more information to track down this issue.

## system details:

```sh
→ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

→ uname -a
Linux macke 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

→ printf 'Desktop: %s\nSession: %s\n' "$XDG_CURRENT_DESKTOP" "$GDMSESSION"
Desktop: GNOME-Flashback:GNOME
Session: regolith
```

**Comment by p3k** [comment]
@bengotow i also allowed myself to send a test mail with pasted image to your e-mail address.
