### ISSUE TITLE
App Icon Badge Is Barely Noticeable 

### ISSUE THREAD

**Issue by lots0logs** [Foundry376/Mailspring#1328]
As the title says, you really cannot tell that the badge is displayed on the icon:

![screenshot from 2019-01-21 01-14-47](https://user-images.githubusercontent.com/4675662/51458443-c9974500-1d1a-11e9-8b69-2527d619b01d.png)

Making it a brighter color and a bit larger would solve the issue.

##### Are there any related issues?
N/A

##### What operating system are you using?

Linux (Arch w/ Cinnamon DE)

##### What version of Mailspring are you using?

1.5.5

--

**Bug?**

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

N/A

**Comment by arkraft** [comment]
What would be the better solution?
The same icon as is used by Mac: 
![image](https://user-images.githubusercontent.com/7426376/53370009-d8da6580-394c-11e9-8e90-bfd433242eb6.png)

or just a bigger dot:
![image](https://user-images.githubusercontent.com/7426376/53370087-13440280-394d-11e9-9406-774847941c69.png)

**Comment by lots0logs** [comment]
Personally, I like the first one :thinking:

**Comment by xclabit** [comment]
I also like the first icon @arkraft . An also related issue is the badge is shown after every sync even when no new mail has arrived: https://github.com/Foundry376/Mailspring/issues/1017
