### ISSUE TITLE
Build out the installation package click no response

### ISSUE THREAD

**Issue by liweiSm** [Foundry376/Mailspring#1329]
Compile the installation package click no response, this is why? There is no exception information in the build process.  How can I find my error?
Version：Mailspring-1.5.0

---> Packaging for 140s
---> Packaging for 141s
---> Done Successfully. Built into: /Users/chainhold/Desktop/liv/workspace/Mailspring-1.5.0/app/dist/Mailspring-darwin-x64

Running "create-mac-zip" task
>> Created /Users/chainhold/Desktop/liv/workspace/Mailspring-1.5.0/app/dist/Mailspring.zip

Running "create-mac-dmg" task
>> Created /Users/chainhold/Desktop/liv/workspace/Mailspring-1.5.0/app/dist/Mailspring.dmg

Done, without errors.

**Comment by bengotow** [comment]
Hey! This looks like the app is building successfully - can you check `/Users/chainhold/Desktop/liv/workspace/Mailspring-1.5.0/app/dist` and see if the files are there?
