### ISSUE TITLE
[Feature Request] Inline images in signature editor

### ISSUE THREAD

**Issue by axllent** [Foundry376/Mailspring#133]
Mailspring 1.0.3 / Ubuntu

It would be great if the signature editor supported inline images.

**Comment by SoftExpert** [comment]
More info, if needed:
 - I tested with 1.0.1-1.0.4 on Ubuntu 16.04.
 - The signature editor allows to put define inline images. 
`<img `**`src="data:image/png;base64, ...."`**` />`
 - The inline images are correctly displayed when composing the message.
 - The inline images are stripped of their content when mail is sent - only the empty img tag is received.
Please fix this.

**Comment by SoftExpert** [comment]
To complete my previous findings: if I modify the inline image definition by adding ALT attribute
`<img `**`alt="signature"`**` src="data:image/png;base64, ...." />`
Gmail will create a small structure for it, but the image is still not displayed:
![ALT structure added by Google](https://images.imgbox.com/20/47/yS3BrkkH_o.png)

To alleviate the issue, it seems that the best option would be to host the image freely somewhere on the net.
The better option would be to automatically embed it in the sent message.

**Comment by bengotow** [comment]
Hey! The new signature editor in 1.0.10 allows you to add an image and handles uploading the image to a Mailspring server where it's publicly available. Enjoy!
