### ISSUE TITLE
[Feature Request] Smart Folder, AutoSort

### ISSUE THREAD

**Issue by philrdubois** [Foundry376/Mailspring#1332]
##### Are there any related issues?

...

##### What operating system are you using?
On Arch Linux, 
...

##### What version of Mailspring are you using?
with Mailspring 1.5.5-b7939d38; 
...

--

**Bug?**

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
A feature is requested: Smart Folders. 
##### Does this feature exist in another mail client or tool you use?
AquaMail on the Android uses this feature. It allows you to see a directory with all Starred and Unread emails in there. There's also the option to also show the last X days of emails.
...

**Another feature:**
Autosort emails based on rules set out beforehand.

You can create rules such as "emails that contain __" or "subjects that start with __" in order to automatically have your emails organized into directories and subdirectories. 

...

**Thanks for listening.**

**Comment by bengotow** [comment]
Merging into #514
