### ISSUE TITLE
Lists of contacts

### ISSUE THREAD

**Issue by pablosolar** [Foundry376/Mailspring#1333]
Hi all, 

Is there any feature in Mailspring to define lists of contacts and then sending emails introducing just the name of one list? For example, 'Group1' includes 14 contacts, so just typing 'Group1' in recipients is needed when sending the email.

Thanks in advance

**Comment by bengotow** [comment]
Hey! Thanks for reaching out—this is actually coming fairly soon with contacts and calendar features we're working on this year. Stay tuned! Merging this in to #86

**Comment by bengotow** [comment]
Hey folks! I'm happy to announce that Mailspring 1.7.0 shipped earlier today, which includes a full address book accessible from **Window > Contacts** in the menu. Enjoy!
