### ISSUE TITLE
Feature request: AutoSync between clients

### ISSUE THREAD

**Issue by d3sd1** [Foundry376/Mailspring#1339]
Hi there!
I have a laptop and desktop computers, so I check mail wherever it takes.
The problem is that when I do, the other MailSpring client app gets "fake messages" on the left screen, and the laptop does never gets notified about "x opened a new mail" when desktop does.
Any solutions? Or it's just a bug/new feature?

**Comment by CodeMouse92** [comment]
Hello,

I cannot quite tell from your description. Are you talking about something like this?

https://community.getmailspring.com/t/sync-templates-signatures-accounts-etc-accross-multiple-devices/265/1

If not, please [post a new Feature Suggestion on our Discourse](https://community.getmailspring.com/c/features/12).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!
