### ISSUE TITLE
[Feature Request] Improve Email Composer

### ISSUE THREAD

**Issue by callaginn** [Foundry376/Mailspring#134]
**I have several feature requests related to composing and formatting emails.**

I often use emails to document summaries of opened and closed Github issues. Unfortunately, most email clients suck at this...so I'm often copying / pasting stuff from Github just to grab some semblance of formatting. Apple Mail and Airmail seem to do the best job at this so far.

# Three Editing Modes
## A. Markdown (mentioned in #19)
Postbox has Markdown plugins and Airmail has it built in. Airmail has the slickest implementation of this I've seen. And formatting code blocks would be another necessity related to this.

## B. HTML Code
Sometimes I paste code directly into an email either for email design testing or formatting purposes. I believe both Postbox and Airmail have this feature.

#### Master Stylesheet
This feature exists in zero email clients, but I've always wanted it. I'm a stickler for how stuff is formatted. Implementation of this may be tricky though. What if you allowed custom stylesheets that are inlined when you send your email?

## C. GUI Editor
This would be the default editor. Apple Mail has a pretty good one...but you could also pull some inspiration from software such as Slack. And I suspect Slack is inserting Markdown via their editor behind the scenes...which is an interesting idea.

#### This editor would need a formatting toolbar with the following options:
- Font Sizes: h1 to h6
- Typeface: list of web-safe and Google Fonts only
- Text Color: predefined text colors. Don't want to give people too many options.
- Larger Emojis: current emojis are way too small
- Tables, tables, tables: I look forward to any email client with a GUI table editor. For example, something like the Dropbox Paper table editor would be awesome.
- Horizontal Rules: either add to the GUI or use formatting shortcuts like typing 3 hyphens inserts an Outlook compatible table-based horizontal rule?
- Buttons: it'd be awesome if you could easily insert some sort of bulletproof buttons

**Comment by bengotow** [comment]
Hey! Thanks for filing this - as you've noted Markdown and plaintext editors are already separate feature requests. Building the composer is actually a huge pain because of all the plugins and hotkeys folks expect. (eg: type a `-` and it automatically enters list mode, etc.) We're looking at replacing the entire thing with an out-of-the-box solution, but 99.9% of those don't allow you to edit arbitrary text, only text created in their editor. That would mean no editing quoted text and no editing drafts created in other programs (at least without a "conversion" step). 

If you're interested in helping out I'm super interested in contributions that improve the editor. Happy to chat more if you want to tackle plaintext or markdown! Merging this into #19 and #52

**Comment by monstercreative** [comment]
Hi @bengotow 
I actually just found your Mail client and really love it's simplicity. If you do add one(which I think it needs) I hope you can keep it simple/clean like the rest of the software. Something like this would be great. 
https://www.jqueryscript.net/text/jQuery-Based-WYSIWYG-style-Markdown-Editor-Markdown.html 
![screenshot 2017-12-20 23 15 08](https://user-images.githubusercontent.com/12746432/34233164-acac8486-e5db-11e7-9e70-e13383bb0da5.png)
maybe an 'html' or '<>' section would help some?
A simple set of selectors in preferences could work, like for 'H1, H2, H3, H4, H5, H6, P, Quotes, etc'.

Keep up the GREAT work guys, love it so far.

**Comment by bengotow** [comment]
Hey! Thanks for the feedback - I'm actually working on (some) of the stuff above for the next update. We're ditching the custom contenteditable wrapper that the client has used for years in favor of the new DraftJS solution from Facebook, which is really nice and extensible. There are still a bunch of rough edges to work out (allowing people to create inline replies from arbitrary received emails is a real pain), but it'll look something like this:

<img width="838" alt="image" src="https://user-images.githubusercontent.com/1037212/34233325-f6a1c7c0-e5a1-11e7-86d6-88748b412735.png">

**Comment by mnstrtom** [comment]
ooh nice! where's the beta 😋 haha! Any idea when the general release is due?

Thomas Joyce
02392 412 444 (tel:02392412444) / 07400 412 444 (tel:07400412444)
Monster Creative (https://www.monstercreative.co.uk) & Monster Print Store (https://www.monsterprintstore.co.uk)

Please note - Our offices will be closed from Friday 22nd December, opening again on Monday 8th January.
For critical only support in this period, please email support@monstercreative.co.uk (mailto:support@monstercreative.co.uk) or leave a message on 02392 412 444 (tel:02392412444) and someone will come back to you asap.

**Comment by toddleo** [comment]
As I mentioned in #19 , without Markdown support, I have to paste rendered content from other Markdown editors. However, 90% of formats(inline, multi-line code area, line breaker and others ) are lost, left only bold and font. It would be great to support full-format content pasting! :smile_cat:

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts (`__`, `*`, `**`, `- ` for lists, single and triple \` for code blocks) and a lot of other small improvements. It also supports pasting HTML from other programs and preserves a wider range of basic styles. I'll be expanding the markdown support in the editor to include the link syntax and the header syntax soon, and I think that'll pretty much close this out. (Though there are some other great ideas here I think we could tackle separately in the future!)

Going to go ahead and close this, but watch out for the few remaining markdown shortcuts in the next few minor releases.

You can grab the latest version from https://getmailspring.com/download.
