### ISSUE TITLE
Bullet list and numbered list edition is broken 

### ISSUE THREAD

**Issue by gdepourtales** [Foundry376/Mailspring#1347]
#### Are there any related issues?
Did not find any

##### What operating system are you using?
Linux (Linux 4.20.5-arch1-1-ARCH #1 SMP PREEMPT Sat Jan 26 12:59:18 UTC 2019 x86_64 GNU/Linux)
XWindow and i3

##### What version of Mailspring are you using?
1.5.5-b7939d38

--

**Bug?**

##### Is this an email sync or connection issue?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
In any case, Here's how to reproduce

- Create a new message
- Add a bullet list with some items
![image](https://user-images.githubusercontent.com/810628/52042781-4a85e600-253e-11e9-8d70-9bf559bf8cf9.png)
- Select all the lines of the list and click on Numbered list. The list get scrambled
![image](https://user-images.githubusercontent.com/810628/52042813-5ec9e300-253e-11e9-9d54-740562d0e4b6.png)

If you go on with the same steps the list moves to the right
![image](https://user-images.githubusercontent.com/810628/52042907-a6506f00-253e-11e9-8514-d2253b99b8b9.png)

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
No

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
