### ISSUE TITLE
Stuck in Login after reinstall

### ISSUE THREAD

**Issue by bimtauer** [Foundry376/Mailspring#1348]
I'm using Kubuntu 18.04 and reinstalled mailspring. Now when trying to log in to my existing account I get stuck with this: 
![image](https://user-images.githubusercontent.com/30375389/52127712-2d7f0f00-2633-11e9-99b4-d222742887c7.png)

Same happens when I try to set up a new mailspring account. 

Pre-story: I reinstalled because I had forgotten my gnome-keyring password. So after resetting gnome-keyring, mailspring would still open but not sync. I was hoping to fix this with a clean install. Now I have this problem. I've tried installing both with snap and pqkg from the .deb file. 

Happy for any help! I'd love to use mailspring again cause in the short time I had it, it really grew on me!

**Comment by bimtauer** [comment]
Update: After another reinstall via Snap I can login to my mailspring account, but am now stuck in this menu: 
![screenshot_20190201_162649](https://user-images.githubusercontent.com/30375389/52132434-7210a780-263f-11e9-95e9-5e67a2e1a77a.png)
None of the choices there allow me to actually open mailbird. Tried deleting my account and set it up again and land in this menu again.

**Comment by bimtauer** [comment]
Fixed with a complete reset of the keyring

**Comment by ivan-nginx** [comment]
Can you please say in details how to reset (change) keyring password?

**Comment by bimtauer** [comment]
Hey Ivan, I believe I purged the keyring entirely and reinstalled it cause I could not figure out how to reset the password.

**Comment by ivan-nginx** [comment]
Thank's dude for answering, I'm already find [solution](https://www.systutorials.com/240997/how-to-change-the-gnome-keyring-password/) which working for me on Fedora desktop.
