### ISSUE TITLE
not accepting correct IMAP password for AOL account

### ISSUE THREAD

**Issue by Miyazono1** [Foundry376/Mailspring#1351]
##### Are there any related issues?

no.

##### What operating system are you using?

Ubuntu 18.10

##### What version of Mailspring are you using?

1.5.5 snap

--

**Bug?**

##### Is this an email sync or connection issue?

no.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

maybe?

##### Is the issue reproducible with a particular attachment, message, signature, etc?

the stars are my email. the log shows this:
----------IMAP----------
* OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=XOAUTH2 AUTH=PLAIN CHILDREN ID LITERAL+ NAMESPACE UIDPLUS MOVE] IMAP4rev1 Hello
1 LOGIN "*********@aol.com" *********
1 NO [AUTHENTICATIONFAILED] LOGIN Invalid credentials

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by howdev** [comment]
This problem happens with me too. can't sign in to aol

**Comment by howdev** [comment]
Thunderbird does fine because, it there is popup for two step login. It doesn't happen in Mailspring

**Comment by CodeMouse92** [comment]
Mailspring does not support two-step login (two-factor authentication), but you can create an App Password to login: https://community.getmailspring.com/t/two-factor-authentication-app-passwords/235
