### ISSUE TITLE
Dynamic SHORTCODE or variable insertion possible in signature? 

### ISSUE THREAD

**Issue by ReessKennedy** [Foundry376/Mailspring#1355]
New Mailspring user here on a Mac and using it with Gmail. 

**ISSUE:** Is there a method to use something like {{recipient_email}} or [email] in the HTML signature and have Mailspring insert the recipients email before sending? 

This would allow me to insert my own custom tracking code with the other open source tool I use for tracking. Thanks for the help ... or any ideas!

**Comment by CodeMouse92** [comment]
Duplicate of #174
