### ISSUE TITLE
UI not loading (blank)

### ISSUE THREAD

**Issue by svliantiss** [Foundry376/Mailspring#1358]
##### Are there any related issues?

At first my mails we're not sending so I cleaned the cache and now when I load up Mailspring everything is empty and I can't access or see any of the UI elements below the toolbar.
Closest Issue #1341 

##### What operating system are you using?
Linux, Manjaro (GNOME)

##### What version of Mailspring are you using?

1.5.5-b7939d38

When I startup Mailspring it loads everything for a few seconds (picture1) then everything dissapears (picture 2). Reinstalling Mailspring does not work and causes the same issue.
1.
![screenshot from 2019-02-08 13-14-09](https://user-images.githubusercontent.com/38691414/52477845-acc89180-2ba3-11e9-8f4b-c1b590f84279.png)
2.
![screenshot from 2019-02-08 13-14-12](https://user-images.githubusercontent.com/38691414/52477860-b6ea9000-2ba3-11e9-8af5-b22ea3911f1a.png)

##### Is this an email sync or connection issue?

Yes and no (I can't see it)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No (and I can't test that)

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No (and I can't test that)

**Comment by cpacchierotti** [comment]
Try to delete ~/.config/Mailspring.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this. Next time this happens, could use the menu to open Developer > Show Developer Tools and see if there are errors in the console there? If you could post them here it'd help narrow this down. I'll check to see if there have been any automatic reports as well.

**Comment by svliantiss** [comment]
I left my computer off during the weekend and upon rebooting the issue just disappeared. (I did reboot beforehand to try and fix it, but it didn't work.) I can't replicate the issue anymore. when I clear my cache now it just works fine.
