### ISSUE TITLE
Emoji rendred as an empty box in JSON translations

### ISSUE THREAD

**Issue by Gaspacchio** [Foundry376/Mailspring#1359]
I just noticed, while I was working on the French version, that a line contains a white square: is it supposed to be an emoji?

https://github.com/Foundry376/Mailspring/blob/26b22ba2a5d332e746a5eb3b35c38f7b6a2acd57/app/lang/en.json#L479

**Comment by cpacchierotti** [comment]
Indeed, I see it as an emoji :)
It is maybe an encoding problem of your browser?

**Comment by Gaspacchio** [comment]
It shows like this in Visual Studio Code too, using UTF-8 encoding:

![capture du 2019-02-08 17-58-07](https://user-images.githubusercontent.com/43613824/52493171-1d36d900-2bcb-11e9-97ce-4ee07f0d5844.png)

**Comment by Gaspacchio** [comment]
Indeed, I just launched Firefox Dev Edition to check the line, and it is displayed as an emoji. The problem appears to be on the side of VS Code and Chromium...

![screenshot_2019-02-08 foundry376 mailspring](https://user-images.githubusercontent.com/43613824/52493465-c8e02900-2bcb-11e9-8f5d-f649f7260d07.png)

**Comment by Gaspacchio** [comment]
I guess I'll close it and submit an issue to @Microsoft/vscode
