### ISSUE TITLE
Can't sync gmail account anymore

### ISSUE THREAD

**Issue by SinisaG** [Foundry376/Mailspring#1364]
##### Are there any related issues?

I did not find anything specifically related to that. 

##### What operating system are you using?

Linux Mint 18.1 Serena

##### What version of Mailspring are you using?

1.5.5

**Bug?**

##### Is this an email sync or connection issue?

This is a **sync issue**. Logs report an auth error. More specifically 

```JSON
{
   "debuginfo":"XOAuth2 token expired and the server did not provide a valid response to refresh.",
   "key":"invalid-xoauth2-resp",
   "retryable":false,
   "what":"std::exception"
}
```
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Don't know, I use it only to sync Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No. 

##### Additional info

Nothing changed since I was able to sync last (Friday, 8.2.2019) and now I am not. Not on the client or on my email account. 

**I love the mail client. Great work guys! <3** And thanks for your help. I'll also try a few things and post if I have any success.

**Comment by adambullmer** [comment]
Had what I think is the same issue this morning. Try going to Preferences > Accounts and see if reconnecting / reauthorizing your accounts resolves the problem

**Comment by SinisaG** [comment]
@adambullmer: Solved. Thanks a lot! :wave: 

Did not expect it, as I did not change the password in between, but maybe something else changed. 

Either way, closing the issue. :)

**Comment by adambullmer** [comment]
It's possible gmail went and invalidated tokens, or you and I authorized mailspring around the same time and the tokens just have an expiry time baked in. Either way, happy to hear that fixed it for ya

**Comment by SinisaG** [comment]
If token can/should be fetch automatically, this can be considered as bug though.
