### ISSUE TITLE
Fix CI builds

### ISSUE THREAD

**Issue by Gaspacchio** [Foundry376/Mailspring#1365]
##### Are there any related issues?

No

#### Continous Integration Issue

Both AppVeyor & Travis CI are reporting errors about build errors:

**On Travis:**
``` console
$ openssl aes-256-cbc -K $encrypted_faf2708e46e2_key -iv $encrypted_faf2708e46e2_iv -in app/build/resources/certs.tar.enc -out app/build/resources/certs.tar -d;
iv undefined
The command "openssl aes-256-cbc -K $encrypted_faf2708e46e2_key -iv $encrypted_faf2708e46e2_iv -in app/build/resources/certs.tar.enc -out app/build/resources/certs.tar -d;" failed and exited with 1 during .
```

**On AppVeyor:**
``` console
C:\OpenSSL-Win32\bin\openssl.exe : iv undefined
At line:1 char:1
+ C:\OpenSSL-Win32\bin\openssl.exe aes-256-cbc -K $env:encrypted_faf270 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (iv undefined:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
``` console
tar : /usr/bin/tar: This does not look like a tar archive
At line:3 char:1
+ tar xvf app/build/resources/certs.tar --directory=app/build/resources ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (/usr/bin/tar: T...e a tar archive:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
/usr/bin/tar
: Exiting with failure status due to previous errors

```
We should try to fix these errors, as it prevents PRs to be correctly checked.

**Comment by bengotow** [comment]
Hey! Yeah I definitely need to look in to this... It seems this happens with pull requests from other repos since they don't have access to the secrets used to prepare release-ready copies of the app. I think that we need to detect this and run some sort of unsigned / test build.

**Comment by Foundry376** [comment]
It looks like the best solution here is to only run part of the CI flow on pull requests. It's a bit tricky to do this with Travis, so I'll investigate using CircleCI instead. It seems they're offering a better service than Travis these days and we could configure certain tasks in a "workflow" to run on PRs. (Like the lint step, but not the publish step.)

**Comment by bengotow** [comment]
I've set up CircleCI for PRs to run the lint task and for now we'll disable travis on PRs. Will hopefully move off of Travis entirely soon, but that'll be a larger task.

**Comment by Gaspacchio** [comment]
Nice move! Tanks for the quick support.
