### ISSUE TITLE
Cannot download mailsync.tar.gz from aws

### ISSUE THREAD

**Issue by whatsthecraic** [Foundry376/Mailspring#1367]
Hi there,
the following error is fired when trying to build v1.5.6 from src:

-- Downloading the last released version of Mailspring mailsync --
Sorry, an error occurred while fetching the Mailspring Mailsync build for your machine
(https://mailspring-builds.s3.amazonaws.com/client/4cb1851/linux/mailsync.tar.gz)

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>C26062000A4E1B92</RequestId><HostId>dIWYeAV5l7e+HsgxwrGclcnPUB+F/SBZg/w/B1jIHiNTHzwrURswFeqw96fw8uHW3tZqalE1IkY=</HostId></Error>

**Comment by alasher** [comment]
I am also experiencing this issue when building from source on macOS.

**Comment by alasher** [comment]
I found a short-term workaround for this issue, but I've only tested this on macOS. I was able to find a copy of the "mailspring" binary within the latest release of the Mailspring app here: Mailspring.app/Contents/Resources/app.asar.unpacked/mailsync. I debugged the app and found it's supposed to be placed inside Mailspring/app/mailsync, so I copied it to there. So far it's working fine.

**Comment by bengotow** [comment]
Hey folks - yep putting the files from the production version of the app in place should work fine. I’ll see why these aren’t getting pushed to S3.

**Comment by bengotow** [comment]
Hey! This has been fixed as part of the 1.5.7 release. It turns out the version.txt file on our server had been updated with a 7-character commit hash instead of an 8 character commit hash, so it wasn't working for the 1.5.6 release.
