### ISSUE TITLE
An unknown error has occurred (mailsync: 1) when trying to connect Gmail account.

### ISSUE THREAD

**Issue by ilovecats516** [Foundry376/Mailspring#1369]
##### Are there any related issues?

No.

...

##### What operating system are you using?

Windows 8.1

##### What version of Mailspring are you using?

1.5.6-4cb1851b

**Bug?**
Yes.

##### Is this an email sync or connection issue?

Yes.

 There are no logs,
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Yes, Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N/A

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by returntrip** [comment]
I cannot reconnect gmail either, wondering if this issue is because of Google's new Oauth verification process:

https://support.google.com/cloud/answer/9110914#check-verification

https://mastodon.xyz/@HerraBRE/101624272130394476

**Comment by aia832003** [comment]
Same here. But curiously not seeing it on my Gsuite work account. Just my personal email.

**Comment by MuTaTeD** [comment]
Same here, the application gives message at least 10 times a day that cannot connect to Gmail server with option to Retry & Manage. Manage takes you to OAuth and when I try Retry it starts working correctly until the next time...

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this. Mailspring was recently re-approved for  "restricted access to Gmail / IMAP via OAuth". Google made it much more difficult to get approved and is manually auditing apps that use the Gmail APIs.  I don't think this was meant to cause a disruption in sync, but it seems that for some folks, you may need to go to Mailspring's Preferences > Accounts and click the "Re-authorize"  button for the account. Sorry for the hassle!

**Comment by ilovecats516** [comment]
@bengotow The "done-pending-release" label, does that mean it will be fixed in the next update? I just tried connecting my Google account again and it returned the same error.

**Comment by ilovecats516** [comment]
It still doesn't work. I get the same error.

**Comment by aia832003** [comment]
Same here. Latest update on Fedora Linux.

**Comment by aia832003** [comment]
Still present in mailspring-1.5.7-0.1.x86_64.rpm

**Comment by ilovecats516** [comment]
@bengotow Pinging to keep relevant.

**Comment by altblog** [comment]
Pls fix it!

**Comment by jsf15** [comment]
Same issue here on ubuntu 18.10

**Comment by ilovecats516** [comment]
It works for me now! I reinstalled it and set my accounts up again and now it works.

**Comment by ilovecats516** [comment]
If the issue persists for any of you, feel free to reopen the issue.

**Comment by aia832003** [comment]
This seems fixed for my standard Gmail account but still getting an error message and retry option using my work G-Suite address. Not sure it helps but this is only happening with my laptop and I have to resume from sleep on Dell XPS 13. Desktop running the same OS and Mailspring version is not seeing this bug. 
![fedora](https://user-images.githubusercontent.com/11007827/54086558-60927d80-4318-11e9-8af2-b1c82426974f.png)

**Comment by aia832003** [comment]
This is still happening. Can we reopen this issue?

**Comment by ilovecats516** [comment]
Sure.

**Comment by ilovecats516** [comment]
Updates?

**Comment by bengotow** [comment]
Hey folks! I believe the fix for this shipped in 1.7.x this month. @aia832003 it sounds like you may be seeing Mailspring have sync issues when you resume from sleep? If your machine takes a long time to reconnect to the network (for example if it spends 20-30 seconds trying to get on wifi or is behind a Boingo hotspot or something else that intercepts and breaks network traffic), that may be causing it to think that your account credentials are incorrect. You may just need to click "Try Again" in that case - I'm not sure what we could do on the app side.

Anyway! I'm going to close this for now—you can download the update from our website at getmailspring.com/download or choose "Check for Updates" in the app's menu. Enjoy the update!
