### ISSUE TITLE
Unable to update (Niether auto nor manully)

### ISSUE THREAD

**Issue by n00d1e5** [Foundry376/Mailspring#1370]
I am now using version 1.5.6-4cb1851b, which is downloaded long time ago (definitely more than 3 days).

I found that you have a new release 1.5.6-4cb1851 3 days ago.

I tried with the software build-in update checker, nothing found.
I tried to download the execution package and launch it, it just open the version which installed in my PC.

So, how could I update without deleting any parameters nor configure files.

PS. Windows 10 system.

Thanks in advanced.

**Comment by bengotow** [comment]
Hi @n00d1e5 thanks for posting—it sounds like your current version `1.5.6-4cb1851b` matches the currently released version `1.5.6-4cb1851b`? On Windows Mailspring should auto-update within 24 hours of the new release going out so it may have automatically updated.

Hope that helps—there will be another update in a few days (to 1.6.0) and we can see if you run in to this again.
