### ISSUE TITLE
CTRL+F when viewing thread (outlook shortcuts)

### ISSUE THREAD

**Issue by slinkymanbyday** [Foundry376/Mailspring#1372]
Version: 1.5.6-4cb1851b
Shortcuts: Outlook
Platform: Linux (Fedora 29, installed using RPM)

CTRL+F when viewing thread is used to forward and to search. These shortcuts should be unique

I suggest CTRL+F for search (as it's quite universal) and CTRL+SHIFT+F for forwarding (although probably not srictly outlook shortcut)

**Comment by bengotow** [comment]
Oooof that's no good at all. Good catch! The shortcuts should definitely be unique. It looks like we use `Ctrl-Shift-F` for forwarding in all the other shortcut sets, but Outlook does actually use `Ctrl-F` and `Ctrl-Shift-F` runs find and replace. I'll get this fixed.

**Comment by bengotow** [comment]
Hey! This has been fixed in 1.6.0 which shipped today. The app should auto-update, but you can also get the new version manually from https://getmailspring.com/download. Thanks - enjoy the app!
