### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by fly1688** [Foundry376/Mailspring#1382]
##### Are there any related issues?

I use the master branch, and when I execute yarn run build, I report "Fatal error: Cannot find module '.. / build/Release/volume. The node '"

##### What operating system are you using?

macOS 10.14.3

##### What version of Mailspring are you using?

master

--

**Bug?**

##### Is this an email sync or connection issue?

no
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

--

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by bengotow** [comment]
Hey! Can you paste the full console output? Unfortunately that error doesn't make much sense — is `build/Release/volume` part of a path on your local machine? It's not anything built in to the project structure or scripts. Maybe there's a space in your path and it's getting confused by that somehow?

**Comment by fly1688** [comment]
.
