### ISSUE TITLE
Stop Running in Background

### ISSUE THREAD

**Issue by johnyradio** [Foundry376/Mailspring#1383]
After closing mailspring, several mailspring tasks continue running in background. 

Plz close fully, or give the option. 

![mailspring-task](https://user-images.githubusercontent.com/6564280/53306438-e525cc00-3841-11e9-8598-9d76ea70beab.jpg)

**Comment by bengotow** [comment]
You can quit Mailspring by choosing Exit from the menu on Windows, or by right clicking it's icon in the task bar.

By default mailsync continues when you close the app's window so that you get notifications, etc. I'll see if I can put this in the knowledgebase!
