### ISSUE TITLE
spam folder also listed in inbox for IMAP email account

### ISSUE THREAD

**Issue by CareF** [Foundry376/Mailspring#1389]
I got system notification for spam email and spam emails are also listed in inbox: 

![deepinscreenshot_select-area_20190226222939](https://user-images.githubusercontent.com/11715538/53463977-a85efe00-3a16-11e9-9eb2-46a96e2063d8.png)

Although it's recognized as spam email. 

##### What operating system are you using?
Arch Linux

##### What version of Mailspring are you using?
1.5.6

**Comment by CodeMouse92** [comment]
It looks like you need to configure your Junk folder in Preferences > Folders.
