### ISSUE TITLE
Reset Password not working

### ISSUE THREAD

**Issue by gocarlos** [Foundry376/Mailspring#139]
##### Are there any related issues?

...
No 
##### What operating system are you using?
...
Ubuntu 14.04, Web
##### What version of Mailspring are you using?
...
1.0.3
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
no
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
no
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
when logging in, click on "fergot your password"
one should get a  mail but nothing happens. 
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! You're totally right about this one... it looks like I actually never wired up the forgot password form in production. Sorry for the hassle—will get this fixed.

**Comment by bengotow** [comment]
Hey! This was fixed earlier today - you can visit https://id.getmailspring.com/forgot to reset your password. Thanks!

**Comment by toma3757** [comment]
Hi!

I forgot my Mailspring ID password and tried to reset it but that seems impossible now.
I got the "Reset your Mailspring ID Password" email, I click the link, fill the forms and got this error:
"Sorry, you must arrive at this page by clicking a reset link."
