### ISSUE TITLE
Major Bug: Lost Paragraph Whitespace

### ISSUE THREAD

**Issue by johnyradio** [Foundry376/Mailspring#1395]
Steps:

1. Compose email, containing blank paragraphs between text
![image](https://user-images.githubusercontent.com/6564280/53593788-54efcb80-3b4e-11e9-8d09-d17a43ea6204.png)

2. Close, saving to Drafts

3. Re-open same draft. 

4. Blank paragraphs are LOST. 
![image](https://user-images.githubusercontent.com/6564280/53594049-d9dae500-3b4e-11e9-9730-cf98557aabb0.png)

**Comment by krupenja** [comment]
Can confirm that I am seeing this as well occasionally.

**Comment by johnyradio** [comment]
This is a MAJOR BUG. 
i cannot use this client for professional emails if it ruins my formatting.

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this - is there anything specific about the emails you see this behavior on? I've tried creating multiple paragraph emails and also pasting in content from Word, etc., but I haven't been able to re-create this yet.

**Comment by johnyradio** [comment]
Seems Mailspring does paragraphs differently than the rest of the world.

Maybe

   1.

   Carriage return vs
   2.

   Line feed vs
   3.

   Form feed


Some apps combine them.

Word adds unknown junk. Please test with notepad.

Pasting from notepad to mailspring, or vice versa, creates problems.

**Comment by krupenja** [comment]
I was getting this two or three times when pasting a text copied from Word. I have tried to reproduce this using different texts/steps but cannot seem to do so. I am going to let you know if this resurfaces.

**Comment by johnyradio** [comment]
Unclear. You're getting it, but can't reproduce it? Sounds contradictory.

Again, plz try with plain text, not Word.

I'm plagued by this with every email.

>

**Comment by johnyradio** [comment]
Prolly related:
Copy text from compose-screen, and paste back into same compose screen. **Line-feeds are lost.** 

images attached. 
![3](https://user-images.githubusercontent.com/6564280/54496626-c2ba2800-48ae-11e9-84fc-0c4e275976f6.png)

![5](https://user-images.githubusercontent.com/6564280/54496631-d5ccf800-48ae-11e9-8909-1c137523b1c7.png)

![6](https://user-images.githubusercontent.com/6564280/54496632-d9f91580-48ae-11e9-8fc5-4e1286863bae.png)

[mailspring-linefeed-bug.zip](https://github.com/Foundry376/Mailspring/files/2975602/mailspring-linefeed-bug.zip)

**Comment by Ragura** [comment]
Adding to this, it also happens to mails that are received from others. The sender used whitespace between paragraphs, but aside from a carriage return, no other whitespace on Mailspring's end, making the mails much harder to read.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved (see #1874), so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
