### ISSUE TITLE
Bug: Incorrect Bad-Address Alert

### ISSUE THREAD

**Issue by johnyradio** [Foundry376/Mailspring#1397]
valid email address:

![image](https://user-images.githubusercontent.com/6564280/53596755-54a6fe80-3b55-11e9-91c0-8a674a8cc65e.png)

on send, gives incorrect alert:

![image](https://user-images.githubusercontent.com/6564280/53596778-6688a180-3b55-11e9-879e-24782b4c4b2b.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - looks like it got thrown off by the leading single-quotes on the address there. I'll see if we can get that fixed.

**Comment by bengotow** [comment]
Hey! This has been fixed in 1.6.0 which shipped today. The app should auto-update, but you can also get the new version manually from https://getmailspring.com/download. Thanks - enjoy the app!

**Comment by johnyradio** [comment]
Thx!
