### ISSUE TITLE
Gmail 'Sent' Folder is Wrong Folder

### ISSUE THREAD

**Issue by johnyradio** [Foundry376/Mailspring#1399]
**Mailspring "Sent" folder:**

![image](https://user-images.githubusercontent.com/6564280/53598219-009e1900-3b59-11e9-94bb-3b585c4b01f6.png)

**Gmail 'Sent' folder:**

![image](https://user-images.githubusercontent.com/6564280/53598252-0f84cb80-3b59-11e9-9bbc-0a12098b23eb.png)

**Comment by ilovecats516** [comment]
![capture](https://user-images.githubusercontent.com/30846409/53856317-45291a80-3f86-11e9-849e-c22e7cb6d63b.PNG)

Have you tried changing the Sent folder here to the folder you want?

**Comment by johnyradio** [comment]
Hi, i checked those settings, and appeared correct. I didn't change any. I'll check again. thx!
Question: can open-tracking raise spam flags in recipient email-client?

thx!

**Comment by bengotow** [comment]
Hey! Yeah changing the folder from Preferences > Folders is probably the right move. Sometimes other mail clients create secondary Sent folders and Mailspring isn't sure which one to use by default.

**Comment by johnyradio** [comment]
Seems your default is "Gmail/Sent", which makes sense.

>
But apparently the correct one is just "Sent".

**Comment by bengotow** [comment]
Hey folks—just a heads up that I think the fix for #1244 will address this. Mailspring could actually /create/ a `Gmail/Sent` folder by accident, and then it'd subsequently think that it was the better Sent folder. Stay tuned!
