### ISSUE TITLE
Problem: No Horizontal Scrollbar when Preview-Pane is Truncated

### ISSUE THREAD

**Issue by johnyradio** [Foundry376/Mailspring#1403]
If the message in preview pane is too wide, there's no visual indication to user, and no scrollbar. 

![mailspr-horiz](https://user-images.githubusercontent.com/6564280/53687115-6d461e80-3ce5-11e9-83e6-56d40e8f3274.JPG)

**Comment by bengotow** [comment]
Hey folks! This is fixed now and we actually had the opposite issue for a bit #1743, going to go ahead and close this.
