### ISSUE TITLE
app request ::: https://imgur.com/gallery/jm62rSe        server load reduction most email, QR integration browser/email client for mobile copy and paste reduction

### ISSUE THREAD

**Issue by c4pt000** [Foundry376/Mailspring#1409]
server load reduction most email, QR integration browser/email client for mobile copy and paste reduction
https://www.reddit.com/r/pcmasterrace/comments/ay7uhc/to_reduce_time_and_energy_waste_with_copy_and/

https://imgur.com/gallery/jm62rSe

**Comment by c4pt000** [comment]
https://www.reddit.com/r/pcmasterrace/comments/ay7uhc/to_reduce_time_and_energy_waste_with_copy_and/

**Comment by c4pt000** [comment]
> server load reduction most email, QR integration browser/email client for mobile copy and paste reduction
> https://www.reddit.com/r/pcmasterrace/comments/ay7uhc/to_reduce_time_and_energy_waste_with_copy_and/
> 
> 
> https://imgur.com/gallery/jm62rSe
>

**Comment by bengotow** [comment]
Hi there - we don't plan to enable easy QR code generation from links, etc. in emails because most users click the links or copy/paste them into their browser on the same computer. There is no need to take a picture of the QR code because there is no need to transfer the link to another computer or device to open it.

**Comment by c4pt000** [comment]
so how do you import from your laptop or desktop to a mobile quickly without retyping the entire link or piece of information for entry into a browser?

**Comment by c4pt000** [comment]
you take a photo, then type it in from a photo taken with the mobile?

**Comment by c4pt000** [comment]
or do you email it to yourself from your desktop or laptop then copy and paste once receiving it on your mobile?

**Comment by c4pt000** [comment]
![QR-code-save-server-electricity](https://user-images.githubusercontent.com/46433702/107724623-47d43480-6cb2-11eb-8264-5a17c89f1dd4.png)

discovered QR functionality in chrome

88.0.4324.150

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
