### ISSUE TITLE
Hotkey for refresh

### ISSUE THREAD

**Issue by mtxr** [Foundry376/Mailspring#1412]
##### Are there any related issues?

Couldn't find any

##### What operating system are you using?

Linux, Fedora 29

##### What version of Mailspring are you using?

Version [1.5.7-2057ca30](https://github.com/Foundry376/Mailspring/releases/tag/1.5.7)

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

As an user, I would like to be able to force refresh whenever I want without going to Menu>Fike>Sync Now.

Consider a Hotkey please.

**Comment by Gaspacchio** [comment]
I totally agree. We should go for `Ctrl + R` as it is standard in most apps and browsers.

**Comment by StarScape** [comment]
Hey, I've never contributed to MailSpring but I'd love to take this on if I can.

**Comment by mtxr** [comment]
Yes. Me too! With some guidance I believe you could solve this one

**Comment by bengotow** [comment]
Thanks for contributing a PR @StarScape! This is great - there will be a new release going out in a few days and I'll make sure this get shipped!

**Comment by mtxr** [comment]
I'll close this issue since it's released

**Comment by JanGunzenhauser** [comment]
If like me you want the add a custom shortcut for this (instead of default `F5`), change the `keymap.json` file to include this (in my case binding `Ctrl + R`):

```
 "window:sync-mail-now": "ctrl+r"
```

Open `Preferences>Shortcuts>Edit Custom Shortcuts` to get to the folder containing this file.
