### ISSUE TITLE
Cannot sync on Gmail

### ISSUE THREAD

**Issue by wijayaadhisurya** [Foundry376/Mailspring#1416]
##### Are there any related issues?

It's like Issue #1401, but on Gmail.

##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?

v1.5.7-2057ca30

**Bug?**

##### Is this an email sync or connection issue?

Yes, mailspring can get email headers, but failed to load its contents.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Yes, mine happens on Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I tried re authenticate 3 times, doesn't solve the problem. On lower left, it keeps showing scanning messages test

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - could you go to the Developer menu of Mailspring and click "Show Mailsync Logs"? If you could email me the mailsync-****.log files to ben@foundry376.com I'll take a look and see if the sync engine is crashing or getting stuck on your mailbox somehow!

**Comment by RorixRebel** [comment]
Same issue here, sadly the logs i have are the ones when i installed the app so nothing is being generated if i "sync new email now".

i do see that something is triggered but no real action is done.

`mailsync-bridge.es6:194 Sending `wake` to all mailsync workers...
sendSyncMailNow @ mailsync-bridge.es6:194
WindowEventHandler.AppEnv.commands.add @ window-event-handler.es6:110
dispatch @ command-registry.es6:57
WindowEventHandler._electron.ipcRenderer.on.args @ window-event-handler.es6:61
emit @ events.js:182
EventEmitter.emit @ domain.js:442
topLevelDomainCallback @ domain.js:121
mailsync-process.es6:300 Sending to mailsync ? {type: "wake-workers"}
mailsync-process.es6:300 Sending to mailsync ? {type: "wake-workers"}
mailsync-process.es6:300 Sending to mailsync ? {type: "wake-workers"}`

**Comment by wijayaadhisurya** [comment]
Sorry, it was my mistake. I was in Indonesia. I think it was because gmail outage (https://www.businessinsider.sg/is-gmail-down-google-drive-tuesday-night-2019-3/?r=US&IR=T). Sorry.
