### ISSUE TITLE
[Feature Request] Replace the OS native titlebar on Linux

### ISSUE THREAD

**Issue by Naatan** [Foundry376/Mailspring#142]
Please provide your own titlebar if you're going to fully theme an app. I know this is a fork of Nylas and so not necessarily an oversight on your part, but it would still be great if this could be addressed. At the moment it looks like you're loading a web page into a window wrapper, which is effectively what is happening but could we at least pretend it's not? ;)

**Comment by bengotow** [comment]
(This only applies to Windows, where the thin white bar is always used, and Linux, where we gave up on trying to find a style everyone could agree on.) PRs welcome!

**Comment by Naatan** [comment]
I'm confused on "find a style everyone could agree on", the style should be that of the theme Mailspring uses. The whole point is that it matches the theme.

**Comment by bengotow** [comment]
Hey! Lemme see if I can find the thread - basically there's no consistent style / positioning of the close / minimize / maximize controls on Linux and if irc folks thought the HTML+CSS one looked a bit off. Also I think the menu bar no longer appeared under the bar (since it was in HTML / CSS). We should definitely try it again because the theme-ability is a huge win!

**Comment by jGleitz** [comment]
Well, I guess having the position of the window controls matching the rest of the system is a requirement all Linux user can agree on. But if completely client-side decorated windows should be achieved on Windows and Mac, themes will have to handle window controls on the right and the left anyway. So this is not much of an additional burden—apart from detecting where the controls should go—, is it?

**Comment by Naatan** [comment]
You could always make it a pref: Use custom titlebar or not. For those who don't like your implementation they can just use the native titlebar or open a ticket which can then be handled case by case.

**Comment by Naatan** [comment]
Fwiw, the UI is a bit crude but this is how we do it with Komodo:

![image](https://user-images.githubusercontent.com/278649/31514832-f832c7c8-af60-11e7-9856-7faf0f1ae928.png)

**Comment by oxysoft** [comment]
god I fucking hate softwares who do this, it is absolutely disgusting. **Definitely** needs to be a setting. Also damn I've never seen someone so hellbent on this software feature, this is a first to me,

**Comment by bengotow** [comment]
Haha whoa there @oxysoft it's just a menu bar it'll be ok. We can always make it a setting if there are two (roughly evenly split) schools of thought here.

Been thinking about this more, and it'd definitely be nice if we could find a nice set of options / styles and do the HTML+CSS window frame on Linux. Right now we have some flags we pass to the window constructor differently based on the platform, and it's hard to get them right and make sure we don't break them refactoring things: https://github.com/Foundry376/Mailspring/blame/master/app/src/browser/window-launcher.es6#L29

**Comment by bengotow** [comment]
This has landed in the PR above.

Hey folks - in the next release I'm adding a preference for this, as well as a new option to use the "right corner hamburger menu" and completely custom window controls. I think this will improve things a lot, especially on distros like Elementary where the standard window frame is very tall.

New options:
<img width="958" alt="image" src="https://user-images.githubusercontent.com/1037212/34469806-1311b00e-eedb-11e7-9ca7-e922b4725a55.png">

"Right corner hamburger" option - note the system window frame is not used at all, so it'll look like this (or your selected theme) on all Linux distros:
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/1037212/34469818-2f88a3f0-eedb-11e7-999c-40a51a50dece.png">

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and a lot of other small improvements. You can grab the latest version from https://getmailspring.com/download.

**Comment by ahmadnassri** [comment]
Can this also be added to Windows?
