### ISSUE TITLE
app request ::: https://imgur.com/gallery/jm62rSe server load reduction most email, QR integration browser/email client for mobile copy and paste reduction #1409     closed #703

### ISSUE THREAD

**Issue by c4pt000** [Foundry376/Mailspring#1420]
![s1](https://i.imgur.com/dt05YOk.png)

**Comment by c4pt000** [comment]
https://www.reddit.com/r/pcmasterrace/comments/ay7uhc/to_reduce_time_and_energy_waste_with_copy_and/


https://imgur.com/gallery/jm62rSe











p.s im starving and crazy and want to buy new computer equipment


1C4XqNoP9QMPQicKBW4R4Dfmpz67YN7qCW

![s1](https://i.imgur.com/MVirCFO.png)

**Comment by c4pt000** [comment]
https://github.com/c4pt000/QR-code-Encryption-layer-for-QR-codes-in-plainsight/blob/master/README.md

**Comment by c4pt000** [comment]
https://www.reddit.com/r/pcmasterrace/comments/ay7uhc/to_reduce_time_and_energy_waste_with_copy_and/

**Comment by Gaspacchio** [comment]
@c4pt000, I think you need a break..... If one of your previous issues has been closed, and @bengotow has explained why, don't open a new one but instead try to argue to get it reopened (#1409). Or else, implements the functionality in a pull request.

**Comment by Gaspacchio** [comment]
Maybe you could get this title sorted out too, it would certainly help to better understand the pros and cons of you suggestion!

**Comment by bengotow** [comment]
Hey folks! Thanks for filing this - as I mentioned earlier, reading your email on your computer and opening links in the emails on your phone (via QR code) isn't a common case we're worried about. On macOS the clipboard is shared between your devices (so copy on mac, paste on phone works to transfer the link) and most browsers (Chrome, Firefox, Safari) also allow you to open the page on your computer and then see / retrieve the tab from your phone. (For example: https://lifehacker.com/chrome-now-syncs-open-tabs-across-your-devices-5910463)
