### ISSUE TITLE
Delete & Backspace key on windows defaults to archive

### ISSUE THREAD

**Issue by lski** [Foundry376/Mailspring#1426]
As a windows user when an email(s) are selected in the list and I press the 'delete' button (or in fact backspace) I would expect an item to be deleted (or put into Trash if I was American lol) but the behaviour is to Archive the email. This seem counter-intuitive to me. In fact Ive only been using MailSpring for a week and Ive done it several times already, then rushing to click the undo button prior to then doing it again and right clicking for delete.

I am aware I can press the # key, but that is not intuitive to a windows/linux user so muscle memory just pushes me to the delete button lol.

I would suggest maybe a checkbox option, if you dont want screw up people already used to the behaviour of achieving.

All in all though great product, this is a miniscule thing. Thank you :)

##### Are there any related issues?
Ive checked and couldnt find anybody else with a similar issue. Searching on delete button, delete key, backspace, backspace key and backspace button. I apologise if this has already been discussed etc. I did spend a while searching for it first. And if it is already an option, and Ive missed it again sorry.

##### What operating system are you using?
Windows 10 (1809)

##### What version of Mailspring are you using?
1.6.0-10f5c95c
(Small tip btw, software Ive made before I found making the version number clickable with a copy icon. Then the version number gets placed placed on the clipboard, makes people more likely to add it in bugs :) Or just a submit a bug in the menu that opens a semi pre-filled github issue. I have never done that though so not sure if github provides the ability, anyway I digress lol).

##### Is this an email sync or connection issue?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I am using Gmail only, but doubt it is related.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Just reproducible by doing it

**Feature Request?**
Yes it can be considered a feature request.

##### Does this feature exist in another mail client or tool you use?
Yes most (em Client, Windows Mail, Microsoft Outlook and Gmails web interface itself)

**Comment by lski** [comment]
I have since found the key map file, I do feel its a little confusing and maybe an improvement to the docs and also maybe making the settings less Mac Orientated for us Linux/Windows lovers :) So will close this.

But good work so far really nice product in general 👍

**Comment by gdinit** [comment]
This is #1 search engine hit for me, so I will comment on this long closed issue, just to capture my feedback, and prevent creating a new issue.

Like the OP, I have customized it on my own installation now, via Preferences > Shortcuts screen, however I too argue:
"DELETE key = item _deletion_" is a logical default keybinding to implement in the project.

To be clear:
"DELETE key = item _archival_" is not a logical default keybinding in my book.
