### ISSUE TITLE
Bug: X'ing quoted text doesn't remove it

### ISSUE THREAD

**Issue by johnyradio** [Foundry376/Mailspring#1434]
instead of removing it, it just expands it. 

![1](https://user-images.githubusercontent.com/6564280/54873912-f361fc00-4d9d-11e9-81c8-76ea3d9df9f6.png)

**Comment by bengotow** [comment]
Good catch - looks like this was a result of a minor change that was made during the conversion to TypeScript. Will be fixed in the next release!

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!
