### ISSUE TITLE
[Feature] Ask for confirmation when resetting settings

### ISSUE THREAD

**Issue by Natrox** [Foundry376/Mailspring#1443]
Please add a confirmation dialog when resetting setting using "Preferences > General > Reset Accounts and Settings". I accidentally pressed this button and it wiped everything without warning.

Version: 1.6.0-10f5c05c
OS: Kubuntu 18.10, Linux kernel 5.0.1

**Comment by mtxr** [comment]
Can I work on this one?

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
