### ISSUE TITLE
Recipients name with hyphen not detected correctly

### ISSUE THREAD

**Issue by MikoMagni** [Foundry376/Mailspring#1445]
##### What operating system are you using?

macOS Mojave 10.14.4

##### What version of Mailspring are you using?

Version 1.6.0 (1.6.0)

**Bug?**

##### Is this an email sync or connection issue?

no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

no

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Composing an email to a recipient with a name with a hyphen triggers the "Are you sure?" alert.   

"The message is addressed to a name that doesn't appear to be a recipient ("ann")"

See example:

![Screen Shot 2019-04-01 at 11 44 47 am](https://user-images.githubusercontent.com/2527231/55298358-ba203080-541c-11e9-9db1-820553d46c1a.png)

**Feature Request?**

No

...

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this definitely seems like something we should be able to fix easily. Will make sure it's resolved in the next release!

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!
