### ISSUE TITLE
Cannot add more than 1 Gmail account

### ISSUE THREAD

**Issue by axllent** [Foundry376/Mailspring#145]
Mailspring 1.0.3 / 1.0.4 - Ubuntu

Other than the same issues reported in #110, when I do kill the process and restart Mailspring I get my initial (Gmail) account set up.  The problem is trying to add another account - it verifies / authenticates (oauth), I get the "Successfully connected to Google! Adding your account to Mailspring..." notification, but when it disappears (returning me to my inbox as if it has added it) the account isn't actually added.

I have deleted all the old settings / mailbox data (`~/.config/Mailspring`) several times on both 1.0.3 and 1.0.4 but the same issue happens on both. I have also tried with different Gmail accounts, but it all has the same result, only 1 (the first) account.

**Comment by bengotow** [comment]
Hey! Can you try this again with the latest release and let me know if you're still having trouble? We've fixed a bunch of related bugs so this may be fixed.

**Comment by axllent** [comment]
Hi @bengotow . No sorry, this still doesn't work in 1.0.7 (latest). As explained above, It goes through the process of adding an account as expected, authenticates, says it is adding, and then nothing. Also no console debug errors, nor errors in the /tmp/Mailspring*.log files.

**Comment by axllent** [comment]
@bengotow I've just tested on two separate Ubuntu machines with 1.0.8, and both with a clean start (removed `.config/Mailspring` before), and both still have this issue. After I have added my first account I cannot add another (Gmail accounts).

Please re-open the issue and it clearly isn't solved.

**Comment by codermjb** [comment]
I have the same issue. I can add one Gmail Account, but not another one. I have 4 Gmail accounts. I would be glad to pay for your service too, but it doesn't even work.

I am running CentOS 7.5. One GMail account works, just not more than one. Keeps authenticating, but doesn't add.

**Comment by bryanhughes** [comment]
I am having the same issue and am also evaluating the product and would gladly pay for it, if it works. I am using Ubuntu 16.04. I was able to add a Gsuite (i.e. gmail) account but not my gmail account. The account that I was able to add does NOT have 2-factor. The account that I am trying to add does and I never get challenged.

I decided to play around and I removed the account without 2-factor which I was able to add so there were no accounts, then added the one with the 2-factor. At this point Mindspring crashes because it is trying to log into the account. Next I deleted the account and tried to add back the one that worked. Unfortunately that now longer works. 

I have attached the logs.

[mailsync-2add7516.log](https://github.com/Foundry376/Mailspring/files/2195096/mailsync-2add7516.log)

**Comment by mhamzas** [comment]
Does it resolve the issue @codermjb Because I am still facing the same issue.

**Comment by codermjb** [comment]
@mhamzas yes, it has been working since the July 16th update. Please be sure you are using the latest. I have 4 Gmail accounts (1 personal and 3 Google Apps/Business accounts), and it's been working really well for me in Debian 9 on two machines.

**Comment by codermjb** [comment]
This is now no longer working in Debian 10. With version 1.6.3

**Comment by zenfulcoder** [comment]
I am still having this issue in 1.7.1. Did the fix make it over?

**Comment by DecentMakeover** [comment]
Not able to add more than one gmail account.

**Comment by VoltrefferNL** [comment]
I'm experiencing the same. Not problems on one machine but I can't add additionals on my laptop.

**Comment by DrSh4dow** [comment]
same problem over here, Im on manjaro xfce and use the snap installation.

**Comment by peterrobertz** [comment]
+1 cannot add another (simple imap) account, just one

**Comment by romanakash** [comment]
Same problems on Ubuntu 18.04

**Comment by yashjahit-21705201** [comment]
Reporting the same, cannot add Microsoft 365 account. It successfully connects and then when it goes back to inbox it still shows me my personal Gmail account

**Comment by nmahadkar** [comment]
This is new 1.7.4  rolling back to 1.7.2 resolves the issue.

**Comment by VoltrefferNL** [comment]
> This is new to 1.7.4 rolling back to 1.7.2 resolves the issue.

Can confirm this solution.

**Comment by mi-git-hub** [comment]
> This is new to 1.7.4 rolling back to 1.7.2 resolves the issue.

Can confirm this too. Issue met when trying to connect to an Office 365 enterprise account.

**Comment by PockelHockel** [comment]
Same issue on Ubuntu 19.10

**Comment by mateenkhalil** [comment]
> 
> 
> > This is new to 1.7.4 rolling back to 1.7.2 resolves the issue.
> 
> Can confirm this solution.

Worked like a charm!!
