### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by nickallevato** [Foundry376/Mailspring#1452]
Mailspring is extremely slow now. Used to not be!

No 'standard' ticket request because there is more information in that template than needs to be conveyed.

On both Ubuntu 18 systems!

**Comment by cpacchierotti** [comment]
You really need to provide more information (i.e., the Mailspring log, Mailspring version).

**Comment by nickallevato** [comment]
No, the developers need to figure it out, not the user. It's 2018, not 2008.

**Comment by nickallevato** [comment]
Here, I fixed it for you.

![image](https://user-images.githubusercontent.com/6791120/55585461-f33df680-56e3-11e9-8b8f-84faa60be808.png)

**Comment by Armstrongzcl** [comment]
> Here, I fixed it for you.
> 
> ![image](https://user-images.githubusercontent.com/6791120/55585461-f33df680-56e3-11e9-8b8f-84faa60be808.png)

Please respect the authors! You should show more information then they improve it.

**Comment by sampotts** [comment]
Nice attitude 🤦‍♂️ 

> No, the developers need to figure it out, not the user. It's 2018, not 2008.

To figure it out they need data otherwise they're working blind. No matter the year, this is required. It's called [debugging](https://en.wikipedia.org/wiki/Debugging).

**Comment by bengotow** [comment]
Hey folks! Thanks for filing this—if you're finding that Mailspring is slow it's worth narrowing down whether the app's general UI / javascript is slow (eg: typing in the composer or scrolling, etc.) or whether it's database access is slow (searching, time from clicking on a folder or label or thread and seeing results). Mailspring automatically vacuums it's database every two weeks to improve query performance and it may be that you need to let that happen for it to become snappy again. This is especially necessary if you regularly delete a lot of mail.

Overall I've been pretty happy with the performance improvements that the last few versions of Chromium + Electron have brought Mailspring, and performance-related complaints have dropped enough that improving perf isn't a major focus right now. If there's a particular interaction that is slow for you please file a ticket with more detail and we can do some profiling! 🏎

**Comment by bengotow** [comment]
Haha oh man I just noticed the edited repo picture. lol, the internet these days.
