### ISSUE TITLE
Mailspring is now showing GUI

### ISSUE THREAD

**Issue by Saderius** [Foundry376/Mailspring#1454]
##### Are there any related issues?

I don't think so.

##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?

Newest (today's update)

--

**Bug?**

##### Is this an email sync or connection issue?

Hey, I gotta say that I trully love Mailspring and the idea behind it!
but recently I ran into some issues. App is not showing any GUI on desktop, even though alt+tab shows its window.
After restart it showed problem with .json file and forced me to login again. After that GUI once again disappeared and (it seems like that) all by connected accounts are gone.
Any protips or solutions how to use it again?
Just before json problem I've seen update prompt in app (easy to recognize even on very small window).

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

nope

##### Is the issue reproducible with a particular attachment, message, signature, etc?

nope

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

nope

**Comment by bengotow** [comment]
Hey! This is pretty interesting - it sounds like Mailspring's window was probably open but offscreen in some way. Maybe you had an external monitor plugged in and then disconnected it and the window was off in negative space somewhere? 

If this is still happening I'd try doing this and see if that resolves the issue: https://www.technipages.com/bring-off-screen-window-back-onto-screen.

If it does, let me know! Maybe there's a way we can make this behavior the default.
