### ISSUE TITLE
Mail Rules don't work

### ISSUE THREAD

**Issue by Andrewsudarikov** [Foundry376/Mailspring#146]
##### Are there any related issues?

...

##### What operating system are you using?
Elementary OS

##### What version of Mailspring are you using?
1.0.4
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No plug-ins

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
GMAIL

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I created a rule to attach a label to emails from a certain address. After creating the rule I pushed "Process entire mailbox" button. It showed the progress of processing with a number of messages, but nothing happened, the labels weren't applied. Restarting didn't help, creating a new rule didn't help.

**Comment by bengotow** [comment]
Hey! Been working on this today - it should be fixed in the next release by 1950f5b3569b5a3c188dfb90d66b3e63e5248ef5.
