### ISSUE TITLE
Replying to a received email causes mailspring to send multiple replies

### ISSUE THREAD

**Issue by Raggertooth** [Foundry376/Mailspring#1465]
I am using a MacBook with current macOs.
I have just downloaded Mailspring from the website.
Everytime I reply to an email, Mailspring sends 3 to 4 replies instead of the one.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - that's pretty unusual. Could you post a reply with the type of email account you linked (Gmail, Outlook, etc.) and also check and see if you see the duplicates in Mailspring, in your web mail interface, or both?

**Comment by Raggertooth** [comment]
It was occurring to Outlook.com<http://Outlook.com> account.
I have cancelled my subscription as it was an issue.

From what I read online, this is not an unusual issue as has been reported before.

Regards
Mark

Mark Padginton
045 00 88 145

On 27 May 2019, at 08:00, Ben Gotow <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey! Thanks for reporting this - that's pretty unusual. Could you post a reply with the type of email account you linked (Gmail, Outlook, etc.) and also check and see if you see the duplicates in Mailspring, in your web mail interface, or both?
