### ISSUE TITLE
Mail Tracker tells me receiver read mail whenever I open mail

### ISSUE THREAD

**Issue by Furqan136** [Foundry376/Mailspring#1470]
##### Are there any related issues?
No.
##### What operating system are you using?
KDE Neon 5.15(Latest)
##### What version of Mailspring are you using?
1.6.1-aceed8e5 (Latest)
**Bug?**

##### Is this an email sync or connection issue?
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
##### Is the issue reproducible with a particular attachment, message, signature, etc?
Yes

If I ever open a sent mail that has tracking on, The program thinks the receiver has opened it and sends me a notification that the receiver has opened my mail even though I was the one viewing it.

**Comment by sasokess** [comment]
Same problem on macOS Mojave

**Comment by Chinmay19** [comment]
Same problem on Ubuntu 18.04

**Comment by bengotow** [comment]
Hey folks! I was able to track this down for a similar issue and it should be fixed by a38445c72336ce23cfed679d8034c482863886b2.

**Comment by Furqan136** [comment]
Great!
This will work if I switch devices too, right?

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!
