### ISSUE TITLE
Encountered an error while syncing

### ISSUE THREAD

**Issue by Xenorio** [Foundry376/Mailspring#1477]
##### Are there any related issues?

I don't think so, it seems like issues with similar titles have a different problem

##### What operating system are you using?

Pop!_OS 19.04

##### What version of Mailspring are you using?

1.6.1-aceed8e5

--

**Bug?**

##### Is this an email sync or connection issue?

Yes, it's an email sync issue. Logs are [here](https://drive.google.com/open?id=1ZHEU6cns0v5_mzBS5diF8G6iDXFZfpt0)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I'm having the issue with Gmail. I can't test other providers.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I don't know, it just says that it can't sync my mails

--

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this is pretty interesting. Both the Google auth token request and the request to Mailspring's metadata service seem to be failing with invalid responses that aren't JSON:

4226 [2019-04-25 12:41:24.823] [main] [info] ------------- Starting Sync (xenorio.management@gmail.com) ---------------
4226 [2019-04-25 12:41:24.826] [background] [info] Fetching XOAuth2 access token from Gmail for XXX
4226 [2019-04-25 12:41:24.853] [metadata] [critical] 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.316] invalid UTF-8 byte at index 0: 0x80
 ***

4226 [2019-04-25 12:41:24.855] [background] [critical] 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.316] invalid UTF-8 byte at index 1: 0xAE
 ***

4226 [2019-04-25 12:41:24.869] [metadata] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

4246 [2019-04-25 12:41:24.966] [main] [info] ------------- Starting Sync (xxx) ---------------
4246 [2019-04-25 12:41:24.968] [metadata] [info] Metadata delta stream starting...
4246 [2019-04-25 12:41:24.969] [background] [info] Fetching XOAuth2 access token from Gmail for XXX
4246 [2019-04-25 12:41:24.995] [metadata] [critical] 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.316] invalid UTF-8 byte at index 1: 0x9A
 ***

4246 [2019-04-25 12:41:24.997] [background] [critical] 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.316] invalid UTF-8 byte at index 0: 0xB0
 ***

4246 [2019-04-25 12:41:25.014] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***


4266 [2019-04-25 12:41:25.111] [main] [info] ------------- Starting Sync (xxx) ---------------

4266 [2019-04-25 12:41:25.137] [metadata] [critical] 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.316] invalid UTF-8 byte at index 0: 0x80
 ***

4266 [2019-04-25 12:41:25.143] [background] [critical] 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.316] invalid UTF-8 byte at index 1: 0xAE
 ***
```

I haven't seen this before — is there any chance you're behind a proxy or your network is filtering requests and redirecting them to a login page or something like that?

**Comment by Xenorio** [comment]
I'm not using any kind of proxy or vpn at all.

I'm using a Pi-Hole tho (local dns server that blocks ads), but it doesn't block any gmail related stuff and certainly not your metadata server. And if it was, it would just route the request to nothing, so there wouldn't be anything invalid coming back because nothing could come back at all

Also, other mail clients work completely fine. I switched to Geary until this issue is resolved, and there were no errors whatsoever. I'd really like to switch back to Mailspring tho.

**Comment by Xenorio** [comment]
Alright, this just got really weird. I just opened Mailspring again to look if i can maybe see the data it gets in the dev console, and it just magically started working again.

Didn't update or change anything at all.

Well, guess i can close this now...
