### ISSUE TITLE
 Turkish character problem

### ISSUE THREAD

**Issue by algkmn** [Foundry376/Mailspring#1481]
In some emails (not all) I have a Turkish character problem (Ğ, ğ, Ş, ş, İ, ı, Ç, ç). Mail subject has not the issue, only mail body has. I use both macOS and Windows. There is no issue for these emails on Browser, macOS Mail, Windows Mail or Microsoft Outlook.

Example 1: https://i.vgy.me/pqoAmu.png
Example 2: https://i.vgy.me/4H1WBk.png

**Comment by CodeMouse92** [comment]
The image links are broken, and the description doesn't describe the problem such that we can diagnose. Closing.
