### ISSUE TITLE
BUG: Broken .ics calendar invites

### ISSUE THREAD

**Issue by jerm** [Foundry376/Mailspring#1487]
##### What operating system are you using?

OSX Mojave 10.14.4

##### What version of Mailspring are you using?

1.6.1-aceed8e5

--

**Bug?**

##### Is this an email sync or connection issue?

no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Not sure

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes. 

Whenever I receive a .ics calendar invite, all i get in Mailspring is an "Unknown Attachment" box with an option to download it.  (screenshot: http://share.jermops.com/0fbf94bc3cec)

By way of comparison, it shows up as "invite.ics" in Gmail, with the added bonus of it getting parsed: (screenshot) http://share.jermops.com/28fb3b2c9754

Obviously the latter bit would be a feature request, but Mailspring doesn't even recognize this as an ics file, and thus dealing with it in Mailspring requires downloading the file and renaming it to something with an ics extension before being able to use it. 

--

**Comment by bengotow** [comment]
Hey! I just ran in to this earlier today and I think we can get it fixed in the next release. Stay tuned @jerm!

**Comment by jerm** [comment]
Sweet, thanks!
