### ISSUE TITLE
Emails from https://fullstackbulletin.com/ can't be displayed

### ISSUE THREAD

**Issue by mhatvan** [Foundry376/Mailspring#1496]
#### Issue Description

All emails that I receive are displayed fine, except for the ones from https://fullstackbulletin.com/
(see attached screenshot below)
It doesn't matter if its side-by-side mode or double clicked modal view mode.
In Mozilla Thunderbird, which I used before, they were displayed correctly.

##### What operating system are you using?
Ubuntu 19.04

##### What version of Mailspring are you using?
Version 1.6.1-aceed8e5

**Bug?**

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![Mailspring FullstackBulletin Display Issue](https://user-images.githubusercontent.com/16797721/57584336-8257de80-74da-11e9-99cb-f691e71050d4.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this is pretty interesting. We recently switched to a method of sizing emails that uses the new DOM ResizeObserver API and has been working really nicely. I'll see if I can reproduce this!

**Comment by bengotow** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1037212/58430360-b00e5d00-806e-11e9-9150-b48ae5553125.png">

Reproduced! So this is interesting—the email's html and body specify some aggressive width and height sizing:
```
    height: 100% !important;
    width: 100% !important;
```

When Mailspring goes to display the email, it makes the iframe 0px tall and then asks `what is the intrinsic scroll height of the body?` That usually tells it how large it needs to make the iframe in order for the content to fully display.

However, it also adds `overflow-y: hidden`, which totally overrides any sort of intrinsic size when combined with `height: 100% important`. I think we need to not disable the scrollbars within the iframe until AFTER the sizing of the email is complete.

Will see if I can get this fixed. Thanks!

**Comment by mhatvan** [comment]
@bengotow no problem, cool that you were able to find out the core issue so fast ;)

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!
