### ISSUE TITLE
Subject becomes no subject (Japanese)

### ISSUE THREAD

**Issue by kometchtech** [Foundry376/Mailspring#15]
##### Are there any related issues?

...
no
##### What operating system are you using?
...
Windows 10 Pro 1703
##### What version of Mailspring are you using?
...
1.0.0
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
no
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
Gmail
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
Japanese subject of subject is not recognized, it becomes no subject.
When you check Gmail you will see that there is a subject.

Mailspring
![subject](https://user-images.githubusercontent.com/5137077/31171057-6fc83ca6-a939-11e7-946c-005d6659d29f.JPG)

Gmail
![gmail](https://user-images.githubusercontent.com/5137077/31171105-92e548e6-a939-11e7-8e5a-cfb03efc893e.JPG)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Thanks for reporting this! Merging into #21.
