### ISSUE TITLE
Garbled characters in the setting item folder

### ISSUE THREAD

**Issue by kometchtech** [Foundry376/Mailspring#150]
##### Are there any related issues?

...
https://github.com/Foundry376/Mailspring/issues/126
https://github.com/Foundry376/Mailspring/issues/16
##### What operating system are you using?
...Windows 10 Pro 1703

##### What version of Mailspring are you using?
...1.0.4

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
![folders](https://user-images.githubusercontent.com/5137077/31542450-fbe1802a-b04c-11e7-81fc-fb5f772cb2e4.JPG)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Ahh good catch! Will fix this for the next release.

**Comment by bengotow** [comment]
Addressed in 6fa52ca823ac91ad1469304ab1ba7e802d935c63

**Comment by kometchtech** [comment]
I confirmed that it was fixed in 1.0.5.
Thank you for fixing.
