### ISSUE TITLE
[bug]Dark theme: compose message, text style dropdown list grey text on grey

### ISSUE THREAD

**Issue by athelas64** [Foundry376/Mailspring#1500]
##### Are there any related issues?

not found

##### What operating system are you using?
Windows 10 1903

##### What version of Mailspring are you using?
1.6.1

--

**Bug?**
Font and size selectors in the compose message field are not readable, because they are rendered as dark grey on light grey. See attached files.
![2019-05-17_00h41_53](https://user-images.githubusercontent.com/2703018/57891814-114b5a80-783d-11e9-82bf-9830a13d25c9.png)
![2019-05-17_00h41_57](https://user-images.githubusercontent.com/2703018/57891815-13151e00-783d-11e9-8c84-0fb37b88c0ae.png)

**Comment by bengotow** [comment]
Wow this is pretty interesting - thanks for filing the report. It looks like Windows is helpfully "styling" the dropdown with the current theme's text color, but not adopting the current theme's background color. I'll take a look and see if we can fix this.

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!
