### ISSUE TITLE
Authentication Error IMAP while configuration

### ISSUE THREAD

**Issue by Craftsman381** [Foundry376/Mailspring#1503]
##### Are there any related issues?

... NO

##### What operating system are you using?

... UBUNTU 18

##### What version of Mailspring are you using?

... 1.6.1

--

**Bug?**

##### Is this an email sync or connection issue?

... YES

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

... IMAP Authentication ERROR 

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
----------IMAP----------
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
1 LOGIN "hr@ibit.com.pk" *********
1 NO [AUTHENTICATIONFAILED] Authentication failed.

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...I am using thunderbird its working perfectly there.

**Comment by TheSHEEEP** [comment]
Same here. Worked just fine, but suddenly stopped being able to sync emails.
Had to uninstall, and when reinstalling, was greeted with this error upon re-registering my email.

Honestly, this software is just way too buggy to use, unfortunately.
