### ISSUE TITLE
Reading pane 100% width

### ISSUE THREAD

**Issue by dalibor983** [Foundry376/Mailspring#1504]
Is there any way to make view port of reading pane to fill full pan width.

![image](https://user-images.githubusercontent.com/226822/58001416-b2efd780-7adb-11e9-9a82-3a0e66f162c0.png)

I want view port to fill those red zones left and right.

**Comment by Armstrongzcl** [comment]
Try to modify the line 4 in `Mailspring/app/internal_packages/message-list/styles/message-list.less`,
`@message-max-width: 800px;` 
change `800px` to `100%`
then rebuild it.

**Comment by Armstrongzcl** [comment]
Another way is to  choose or modify a theme to meet your requirement.

**Comment by dalibor983** [comment]
@Armstrongzcl Thanks. I will try.
