### ISSUE TITLE
File attachment button location change.

### ISSUE THREAD

**Issue by biplabro** [Foundry376/Mailspring#1508]
OS: Ubuntu 18.04.2
Kernel: 5.1.3
MailSpring Version: 1.6.1

![Mailspring](https://user-images.githubusercontent.com/35135009/58313215-a72d4980-7e2a-11e9-83a8-5c3dd78bfe48.png)

Please change the "attach files" icon far away from the "DELETE button". Shifting the attachment button to the left might help us, the user. From a UI point of view I found it very troublesome. A few times i have accidentally removed a whole formatted & typed email before sending, just by mistakenly hitting the delete button instead of the attach button.

**Comment by bengotow** [comment]
I think this would be a great idea. I honestly can't remember why it's over there by the delete button, it's just been there for years. Will make this change in the next release!

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!
