### ISSUE TITLE
Mailspring (both snap and .deb) on Ubuntu 18.04 hanging on Signing in to Mailspring 

### ISSUE THREAD

**Issue by pdiveris** [Foundry376/Mailspring#1510]
Mailspring 1.6.1 on Linux

Using either the snap or .deb on Ubuntu 18.04 Mailspring hangs on signing in to Mailspring. Account exists, app works on the Mac. I have repeatedly uninstalled, purged config, manually deleted ~/.config/Mailspring. Nothing helps. If I can't find a solution in the next few days I am going to sadly have to cancel my pro subscription and look for another email client. 

![Screenshot from 2019-05-29 11-27-09](https://user-images.githubusercontent.com/1022373/58550137-090ff980-8205-11e9-8ca7-db45a0e09b02.png)

**Comment by pdiveris** [comment]
I see..

**Comment by akdor1154** [comment]
Seeing this here, Ubuntu 18.10.

**Comment by pdiveris** [comment]
It got magically fixed in Version 1.6.2 (1.6.2). Never the less I am apalled by the deafening silence from the developers. Not even an acknowledgement that an issue was reported. Iam stuck with MailSpring because it's the only one that looks good and it's nice when it works across all three platforms I am using but I am seriously considering a fork.

**Comment by akdor1154** [comment]
But I am on 1.6.2...
