### ISSUE TITLE
The close, minimize, and maximize button doesn't match my gtk theme

### ISSUE THREAD

**Issue by Fatih20** [Foundry376/Mailspring#1528]
Pretty much that. No need to explain further.

**Comment by bengotow** [comment]
Hey! The buttons will only match your system theme if you choose to use the system window frame from Preferences > Appearance. By default the buttons (and the whole title bar, really) are "themed" by the Mailspring theme (which allows them to be dark in dark mode, etc.)

**Comment by CodeMouse92** [comment]
I've added a Q&A here: https://community.getmailspring.com/t/match-gtk-theme/601
