### ISSUE TITLE
Doesn't start in background

### ISSUE THREAD

**Issue by goransimic** [Foundry376/Mailspring#153]
Mailspring doesn't respect "--background" argument and always opens in foreground. Ubuntu 17.10.

**Comment by bengotow** [comment]
This would be a great starter issue for anyone interested in contributing to Mailspring! We parse the `--background` option here (https://github.com/Foundry376/Mailspring/blame/master/app/src/browser/application.es6#L84) and then presumably that value is lost or never used at some point.

**Comment by rustamzh** [comment]
@goransimic92, it's working for me. Try "mailspring -b" instead
OS: Manjaro 17.0.5

**Comment by goransimic92** [comment]
@rustamzh, I have tried both arguments and it's same thing. Both Ubuntu 17.04 and 17.10.

**Comment by goransimic92** [comment]
Not sure why, but this is working for me also now with latest updates to Ubuntu 17.10 and Mailspring 1.0.5.

**Comment by ET-Bent** [comment]
Why not make this an in app option?

**Comment by Void97** [comment]
I can confirm this issue, in Manjaro 17.0.6 both "-b" and "--background" flags don't work, causing Mailspring to launch in foreground.

**Comment by bengotow** [comment]
Hey folks! Launching at system start is already an option in Preferences > General and starts the app in the background. (Though on Linux it checks for `/usr/share/applications/mailspring.desktop` - we may need to rework it to support the Snapcraft release, and it may not actually be possible inside of the AppArmor sandbox.)

The current flag is `--background`. I just checked  v1.0.11 and it seems to work fine on macOS. It also works on Ubuntu 16 for me—when I type `mailspring --background` on a command prompt using the latest Snapcraft release, the menu bar item for Mailspring appears in the system tray and the main window does not appear. The app also does not appear in the dock. Clicking `System Tray > Open Inbox` displays the inbox immediately (just a sanity check that it was running in the background.)

I'm not sure what would cause this to not work. Is it possible that `mailspring` is actually an alias on your command prompt, and is calling the underlying executable without forwarding it's arguments? Try typing `mailspring mailto:hello@world.com` and check that you see a new composer pre-filled with that address.

Also note that the app will only launch in the background if you've completed the onboarding flow (signed in to your Mailspring ID, linked an account, etc.)

**Comment by goransimic92** [comment]
For me it's not an alias, because it directly targets `/usr/bin/mailspring` with `--background` argument in autostart file. 

But something strange is happening because now sometimes it starts in background and sometimes it doesn't. It looks like sometimes there is something happening in between where it ignores argument and starts in front.

**Comment by Void97** [comment]
That's strange, deleting mailspring auto-generated entry from startup programs and manually adding `/usr/bin/mailspring -b` seems to solve the problem. I don't think the issue was caused by an alias though, since `mailspring mailto:hello@world.com` launches a pre-filled composer as expected.

**Comment by goransimic92** [comment]
@bengotow If I quit Mailspring while it's opened in front and start again with `--background` option, it doesn't respect it. But if i quit Mailspring while it's closed to system tray it respects `--background` option.

**Comment by cybermaxpower** [comment]
> deleting mailspring auto-generated entry from startup programs and manually adding `/usr/bin/mailspring -b` seems to solve the problem.

This fix worked for me on ubuntu mate thank you :-)

**Comment by wonx** [comment]
In Ubuntu 18.04.1 LTS, using the snap version with the -b or --background options still launch to the foreground, even when manually running it from "/snap/bin/mailspring -b".

**Comment by Rygi3l** [comment]
Bump. Anybody have a solution?

**Comment by Rygi3l** [comment]
Linux Mint 19 - `mailspring --background` is working good. One bug is that mailspring hasn't icon in tray.

**Comment by ecavicc** [comment]
Manjaro KDE - I had the same problem but I solved it this way: I excluded mailspring from session restore at startup.

**Comment by fcastilloec** [comment]
On Linux, this is an issue, the background option doesn't work.
The output of `mailspring --help` told me that the `-b, --background` option is a boolean, so I start the app with `mailspring -b true` and now it starts in the background always. This is a bug since `boolean` should mean that the flag itself would be enough for it to start in the background, but for whatever reason, it needs something else after the flag for it to work.

**Comment by phongkyanh** [comment]
> @bengotow If I quit Mailspring while it's opened in front and start again with `--background` option, it doesn't respect it. But if i quit Mailspring while it's closed to system tray it respects `--background` option.

this happens the same to me

> On Linux, this is an issue, the background option doesn't work.
> The output of `mailspring --help` told me that the `-b, --background` option is a boolean, so I start the app with `mailspring -b true` and now it starts in the background always. This is a bug since `boolean` should mean that the flag itself would be enough for it to start in the background, but for whatever reason, it needs something else after the flag for it to work.

i tried but it still cannot work.

**Comment by phongkyanh** [comment]
wow! the command -b is actually worked. I just quit mailspring (even in the tray icon) then restart the OS then everything works fine now.
my command is: `/usr/bin/mailspring -b %U`

**Comment by Tasty213** [comment]
This is still an issue as i experienced it after installing from AUR, by modifying the command run by autostart to 
```
mailspring -b %U
```
Works correctly (does ask for a password though)

Seems to be most likely an issue with the installing scripts

**Comment by Tayyib** [comment]
Windows 10 user here. Same issue and nothing works...

**Comment by GGimenez96** [comment]
> @bengotow If I quit Mailspring while it's opened in front and start again with `--background` option, it doesn't respect it. But if i quit Mailspring while it's closed to system tray it respects `--background` option.

Same here.

**Comment by drmuelr** [comment]
Same here on Windows 10.

**Comment by kerozoli** [comment]
Same here Ubuntu 20.04 snap

**Comment by kinghat** [comment]
> This is still an issue as i experienced it after installing from AUR, by modifying the command run by autostart to
> 
> ```
> mailspring -b %U
> ```
> 
> Works correctly (does ask for a password though)
> 
> Seems to be most likely an issue with the installing scripts

this works with the snap on kde manjaro autostart setup as well :+1:

**Comment by elliotwutingfeng** [comment]
I got mine working by setting the `Exec=` field to `/usr/bin/mailspring --background` instead of `/usr/bin/mailspring --background %U`. I'm using the AUR version on Manjaro GNOME.

**Comment by CodeMouse92** [comment]
This is underway with #2259

**Comment by Phylu** [comment]
I am taking over this issue.
