### ISSUE TITLE
Facebook links are missing the www in 

### ISSUE THREAD

**Issue by coliff** [Foundry376/Mailspring#1530]
##### What operating system are you using?

Windows 10 64-bit

##### What version of Mailspring are you using?

Latest (1.6.2)

##### Issues

- Hovering over the social links (to Facebook, Twitter etc) in the sidebar doesn't show the link/pointer cursor as expected.
- Facebook links are missing the www leading to an unnecessary redirect. (https://facebook.com/example/) should be (https://www.facebook.com/example/)

**Comment by bengotow** [comment]
Hey! If anyone is interested in taking a quick look at this, I think 1) should be a CSS change and 2) is probably a matter of finding where we say something to the effect of `"http://facebook.com/" + username` and updating the URL.

**Comment by alemagio** [comment]
Hi i would like to work on this.

**Comment by alemagio** [comment]
Hi, i tried to reproduce the issue. 
Same version and same OS but i wasn't able to.
The Facebook URL has the leading "www" and the cursor pointer shows correctly hovering the twitter or facebook link in the signature.

Can you provide a screenshot?

**Comment by coliff** [comment]
> The Facebook URL has the leading "www" and the cursor pointer shows correctly hovering the twitter or facebook link in the signature.
It's not in the signature, it's the sidebar.

![image](https://user-images.githubusercontent.com/1212885/60420848-a060d600-9c23-11e9-9f09-fe3f601e0d57.png)

**Comment by alemagio** [comment]
Thanks for the answer.

Link to the PR.
[https://github.com/Foundry376/Mailspring/pull/1559](url)

Hope is everything fine, if not I'll fix it asap.

**Comment by VincentPloquien** [comment]
This should probably be closed as #1559 has been merged?

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
