### ISSUE TITLE
Thai characters appear as boxes in Title bar

### ISSUE THREAD

**Issue by jeffmcneill** [Foundry376/Mailspring#1532]
##### What operating system are you using?

Debian 9

##### What version of Mailspring are you using?

1.6.1-aceed8e5

**Bug?**

The Thai characters render in the list and preview pane, but the title bar of the app replaces the Thai characters with boxes. See attached image.

![image](https://user-images.githubusercontent.com/3119827/59767207-fbadd280-92cb-11e9-863a-6ba802509d80.png)

**Comment by bengotow** [comment]
Hey there! Thanks for reporting this—I /think/ that this is an issue with the default font used for the window titles on Debian 9 not supporting Thai characters at all. Could you confirm if you're able to see Thai characters in title bars elsewhere? (Maybe try saving a file with a thai name and opening it in an editor that shows the document name up there?)

**Comment by jeffmcneill** [comment]
There are no problems in other apps with Thai font support in the title bars. The same emails as displayed in Gmail/Chrome show proper Thai font rendering. Inkscape has no problem. VSCode has no problem. Files app has no problem.

**Comment by jeffmcneill** [comment]
By "needs-reproduction" can I help with that or does that mean someone else needs to try?

**Comment by jeffmcneill** [comment]
Nevermind, no longer using Mailspring
