### ISSUE TITLE
Unable to drag and drop messages to a label

### ISSUE THREAD

**Issue by timdorr** [Foundry376/Mailspring#1533]
##### What operating system are you using?

macOS 10.14.5

##### What version of Mailspring are you using?

1.6.2 (This did not occur in earlier versions)

**Bug?**

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I only have Gmail accounts, but it happens on all 3.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Any message is not draggable.

A GIF is worth a billion words:

![Jun-19-2019 14-56-50](https://user-images.githubusercontent.com/17882/59792696-c8a31900-92a2-11e9-937d-6b82f36bf58d.gif)

I am able to move the message to another label with the menu button and shortcut. It is only the dragging action that appears to not work.

**Comment by curtisgibby** [comment]
I see the same behavior on 1.6.2 in Linux Mint. Reverting to 1.6.1 allows dragging to move messages as expected.

**Comment by thatguypark** [comment]
Same issue here (macOS 10.12.6).   I can use the "Move to Folder..." option, but I'm trying to clean up my inbox with about 200 emails, and the menu option is just way too slow.

Any easy way to revert it back to 1.6.1?

**Comment by davidhiendl** [comment]
Same problem since 1.6.2, Drag&Drop for labels not working on Manjaro/KDE.

**Comment by feeria** [comment]
Same problem since 1.6.2 Windows 10.

**Comment by Fefolet** [comment]
Same here

**Comment by dkooij** [comment]
I have the same issue (Windows 10)

**Comment by CharlesElliottGH** [comment]
Same in 1.6.2 in Windows 10 for me as well.

**Comment by mkusinski** [comment]
Confirm on Windows 10. Mailspring 1.6.2

**Comment by jidj85** [comment]
Same issue here. How can i revert to 1.6.1 in ubuntu?

**Comment by ernstae** [comment]
I'm seeing the same issue in Manjaro Linux and 1.6.2-278bf219 fwiw

**Comment by curtisgibby** [comment]
Woo! Thanks, @bengotow! Any idea when 1.6.3 with this fix will be released?

**Comment by sampotts** [comment]
Still an issue in 1.6.3 sadly. Was it tested?

**Comment by curtisgibby** [comment]
1.6.3 is out now, and fixes this issue for me. :medal_sports:

**Comment by sampotts** [comment]
Yep, it does for me too. I deleted my previous comment. I was trying to drag an email from one account to a label in another account it seemed which was causing the issue.

**Comment by timdorr** [comment]
Yep, fixed for me too. Thanks, Ben!
