### ISSUE TITLE
Mailspring freezes when insering links

### ISSUE THREAD

**Issue by luriomer** [Foundry376/Mailspring#1535]
##### What operating system are you using?
Ubuntu 18.04 LTS **and** Windows 10
(the bug happens in both, on completely different computers)

##### What version of Mailspring are you using?

1.6.2-278bf219

**Bug?**

When trying to insert http links to an email body, the entire application freezes and the only way to proceed is to kill the process and relaunch.
It happens 100% of the time.

##### Is this an email sync or connection issue?

Not to my understanding.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I don't think so, but I only use Gmail so I did not try with a different account.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No, it happens for all composed\replied or forwarded messages.

**Comment by bengotow** [comment]
Wow that's no good at all. I tried reproducing this but I haven't had any luck yet. Are you pasting multiple links at once within a larger block of text, or just a simple string like "https://github.com/Foundry376/Mailspring/issues/1535"? Will keep trying at this one.

**Comment by luriomer** [comment]
I'm just pasting the http link directly from the browser. If I use the "add link" tool it is fine, but manually inserting any link, even http://www.google.com will cause the app to freeze.

**Comment by bengotow** [comment]
Hey folks! This was fixed back in July and I forgot to close the ticket. Turns out this was caused by a regular expression lookahead causing infinite recursion. Fun times. Thanks for filing @luriomer!

**Comment by luriomer** [comment]
Great, NP.
