### ISSUE TITLE
Linux / Snap : signature and templates not working

### ISSUE THREAD

**Issue by phylophyl** [Foundry376/Mailspring#1538]
When editing a new email, templates and signatures can't be inserted in the text box.
Selecting and clicking on a signature has no effect.
Selecting and clicking on a template shows nothing.

This problem occurs with the snap and amd64.deb version with the mailspring 1.6.2 version.
The problem does not exist with the 1.5.5.

...

##### What operating system are you using?

Debian Buster 10

##### What version of Mailspring are you using?

mailspring 1.6.2

**Comment by bengotow** [comment]
Hey @phylophyl! Thanks for reporting this—I was able to reproduce this and it'll be fixed tonight by the 1.6.3 release by e492429548012a48ef42645b2d80ae7f5050a464.

**Comment by phylophyl** [comment]
Awesome @bengotow

**Comment by phylophyl** [comment]
It works thank you.
