### ISSUE TITLE
No Notification and Sound

### ISSUE THREAD

**Issue by goransimic92** [Foundry376/Mailspring#154]
##### Are there any related issues?

No.

##### What operating system are you using?
Ubuntu 17.10.

##### What version of Mailspring are you using?
1.0.4.

--

**Bug?**

##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

There is no notification and sound when receiving new mail.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Any chance you’re testing this by sending an email to yourself? Mailspring does not display notifications when the email is from you.

You may also want to check Preferences > General and make sure you’ve installed the package required for notifications.

**Comment by goransimic92** [comment]
I was sending mail from my outlook mail on web to my gmail. And "zenity" is installed already.

**Comment by tchiotludo** [comment]
Same here on Ubuntu 17.04 with zenity installed.
If have the same behaviour on Nylas, the notification is really instable (sometime works, sometime not)

**Comment by mamantoha** [comment]
Same here on KDE neon(based on Ubuntu 16.04) with Plasma 5.11

**Comment by tchiotludo** [comment]
I'm on Ubuntu 17.04 for myself

**Comment by bengotow** [comment]
This is /probably/ going to be fixed by a84b63d1f54cb107d4af27c8531983f4bf8553a3, but we'll need to check and see. One quick way to make sure the notification dependencies are installed correctly is to open the Developer Tools in the Mailspring window and type `new Notification("Hello World")` on the console. If you don't get anything, it's something that won't be fixed by the update that we'll need to investigate a bit more.

**Comment by goransimic92** [comment]
With fix from that commit both notification and sound work fine.

**Comment by mamantoha** [comment]
I can confirm that it fixed in 1.0.6

**Comment by denis-kisel** [comment]
Work for me:
http://i.imgur.com/ZNunuKK.png
then
http://i.imgur.com/jnrENm5.png
