### ISSUE TITLE
Calendar preview has no close button

### ISSUE THREAD

**Issue by mslourens** [Foundry376/Mailspring#1541]
I am using Mailspring 1.6.2 and tried the Calendar Preview via Developer => Calendar Preview. It opens the calendar with all my Google Calendars, but there is no close button. So I have to close the window using the icon on the taskbar, which is not very user friendly. Please add some chrome to the Calendar Preview window with a fullscreen, minimize and at least a close button. 

To fix this, you only have to change the window options in `src/browser/window-manager.ts` to `frame: true`. I would also hide the menu, but am not sure where to do that...

**Comment by bengotow** [comment]
Gooood catch on this one. Thanks for pointing this out! If you want to submit a quick PR, I /think/ the change would go here: https://github.com/Foundry376/Mailspring/blob/master/app/src/browser/window-manager.ts#L264

**Comment by mslourens** [comment]
I created the PR: https://github.com/Foundry376/Mailspring/pull/1545
