### ISSUE TITLE
Feature request: Option to open attached file in desktop application directly

### ISSUE THREAD

**Issue by esp3dk** [Foundry376/Mailspring#1548]
Dear developers.
Thank you for a great email app with a simple and fast working interface. I have just started using Mailspring and am really delighted. 

However there are always room for improvements. I receive a lot of files I have to edit. As it works now I first have to save the file, then open it (I have automatic opening of the folder after download marked in the settings) before I start editing. Further if I have been working on various documents send to me belonging in different folders I will end up with a lot of instances of the file browser open adding to the clutter of my desktop(s).

I would therefore like to suggest to add an option to directly open an attachment in the default desktop app; as it would do in most desktop mail clients and in any browser based client when running them in a Firefox browser (one of the reasons I prefer Firefox). In practice this could be implemented as a dedicated button next to the "View" and "Save/download" button or an option when clicking on the "Save/Download" button. I think this option would make life easier for many users.

##### Are there any related issues?

Not that I have been able to find

...

##### What operating system are you using?
Linux, Manjaro 18, Cinnamon Desktop

...

##### What version of Mailspring are you using?
1.6.2-268bj219
...

--

**Bug?**

NO

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
Yes:
Option to open attachment directly in a desktop app without first having to save it or second best option in the same instance as when saving it i.e. not being necessary to open the file in an app via the file browser.

##### Does this feature exist in another mail client or tool you use?
Yes it works in Thunderbird, Evolution and Geary and any webapp run in Firefox.
...

**Comment by esp3dk** [comment]
UPS

**Comment by bengotow** [comment]
Hey @esp3dk! I think you can actually double-click the filename or image preview of an attachment to open it in your default desktop app. Could you see if that works? I'll also see if we can add a contextual menu for this to make it a bit more clear.

EDIT: It looks like this works for all attachments /except/ for inline images. I'll see if I can fix that as well.

**Comment by esp3dk** [comment]
Hi @bengotow 
Thanks for your answer. I can confirm that it works at - least with office files, which are the ones I use mostly. I am happy the feature is already there. This makes my work flow so much easier. Thanks again.

I think it deserves an article in your help/support section. I suggest an entry inthe "Getting started" menu (https://foundry376.zendesk.com/hc/en-us/sections/115000521592-Getting-Started). I am sure many others will appreciate this.

Keep up the good work. I am looking forward to follow the development of this app.
