### ISSUE TITLE
Calendar Preview doesn't handle timezones correctly 

### ISSUE THREAD

**Issue by rsalevsky** [Foundry376/Mailspring#1555]
Thanks for introducing the ICS preview feature. This is really cool! Unfortunately the preview doesn't handle timezones correctly. I got a appointment from a US based colleague 9AM MDT but it showed it to me 9AM CEST instead of 5PM CEST. See the attached screenshot
![Screenshot from 2019-07-02 13-43-03](https://user-images.githubusercontent.com/4128547/60510659-3e11df00-9cd0-11e9-9e85-7099ad3489f7.png)
.

##### Are there any related issues?

No

##### What operating system are you using?

openSUSE Leap 15.1

##### What version of Mailspring are you using?

1.6.3

--

**Bug?**

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

No

**Comment by rahulghanate** [comment]
May not be a configurable timezone option but it should at least use system timezone to identify event times.

**Comment by oshunluvr** [comment]
Errors here too:
![Annotation 2019-12-17 134312](https://user-images.githubusercontent.com/13033630/71029179-79646680-20d4-11ea-997c-e525c3c61359.png)
![Annotation 2019-12-17 134331](https://user-images.githubusercontent.com/13033630/71029181-7b2e2a00-20d4-11ea-8b5b-a8ce1d36f6cc.png)

**Comment by ashb** [comment]
![image](https://user-images.githubusercontent.com/34150/74370689-6ec20700-4dcf-11ea-88c1-a133d519ea89.png)

**Comment by david-sitsky** [comment]
I get the same issue - appointments created by US employees are rendered in their local time but shows AEAT (Australian Eastern tz).  Timezone adjustments are not made.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
