### ISSUE TITLE
[Feature Request] Ability to set a Master Password

### ISSUE THREAD

**Issue by molaeiali** [Foundry376/Mailspring#1561]
I think it is useful to have a master password, that could be asked on start up

Maybe I give my laptop to some friend to check something in browser, or play a game, I don't want him to read my emails easily 😅

Just a lock password, or a pin is useful

There is a similar addon for thunderbird that do this:

https://addons.thunderbird.net/en-US/thunderbird/addon/master-password/

**Comment by bengotow** [comment]
Merging in to #440! This is one of those things that is easy to do from a UI perspective but very difficult to actually make "real." I'm hesitant to add something that looks like a lock screen that is easily circumvented, or doesn't reflect that the files on disk are actually unencrypted and browsing to the right folder would let you view them all. Will take a look at the Thunderbird implementation though!
