### ISSUE TITLE
[Feature Request] Add ability to block remote content

### ISSUE THREAD

**Issue by nvesely** [Foundry376/Mailspring#1568]
**Feature Request?**

Remote content allows anyone who's email I happen to open learn my IP address, and see when I open their email. Further, it may contain malicious code. A cursory glance suggests [this file](https://github.com/Foundry376/Mailspring/blob/149b389508f59ef382c21900fc7b45aa5599caad/app/internal_packages/message-list/lib/message-item-body.tsx) defines the `webPreferences` for loading all messages, and it looks like JS is disabled, which covers that issue at least.

Ideally, remote content could be blocked outright, then particular senders could be whitelisted, or particular messages could reloaded with their remote content at the click of a button.

Implementing such a mechanism might require a bit of thought. In the meantime, an all-or-nothing switch would be hugely appreciated.

##### Does this feature exist in another mail client or tool you use?

Default behavior in many email clients.

**Comment by rufoa** [comment]
Mailspring already has this feature

Preferences > General > Reading > Untick "Automatically load images in viewed messages"

Emails containing images then get a "load images once" / "whitelist sender" option at the top

**Comment by nvesely** [comment]
Thanks! Does this option make a distinction between when the image gets attached to/embedded in the email and when it's stored remotely?

**Comment by rufoa** [comment]
Yes, it handles that correctly!

**Comment by nvesely** [comment]
Lovely
