### ISSUE TITLE
[Feature Request] Option to exclude email thread when replying.

### ISSUE THREAD

**Issue by debabratadas-zz** [Foundry376/Mailspring#157]
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes

**Feature Request:** An option in preferences which allow to reply to email without including original email thread.

**Comment by bengotow** [comment]
Hey there! It's been a few years and you can now exclude email quoted text by clicking the small X next to the "•••" control in the composer. Enjoy!
