### ISSUE TITLE
'x' message selection not working

### ISSUE THREAD

**Issue by werkshy** [Foundry376/Mailspring#1572]
Trying to select the message using keyboard shortcuts isn't working, either in the main inbox view or in a search. I am using 'Gmail' shortcut theme so 'x' is my shortcut for 'select this message'

Steps to repeat:
1. Load inbox
2. Use cursor keys to highlight a message
3. Press 'x'

Expected result: current message is selected, multiple messages can be selected by pressing 'x'  on different messages
Actual result: pressing 'x' does nothing.

Most other shortcuts work (e.g. 'e' to archive). 
The other selection shortcuts ('* a' etc) do work.

##### What operating system are you using?

MacOS

##### What version of Mailspring are you using?

1.6.3

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No (probably not). My provider is Gmail. I can select messages using cmd-click, so selection generally does work, it's just the keyboard shortcut that doesn't work.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No, this is for all messages.

**Comment by bengotow** [comment]
Hey! For `* a`, make sure you press shift when you type the first character (8). It looks like it's working for me but I'm also curious if it's dependent on your keyboard layout. (It might be "shift-8 a" and not "* a")

It's a little unclear, but for multiple selection to work you need to use Mailspring in Single Panel mode, where there's a row of checkboxes shown in the thread list. I'll see if we can make this more obvious in the next release but I'm afraid we probably won't be able to change it soon so I'm gonna go ahead and close this. Thanks!
