### ISSUE TITLE
Sign in to mail service which requests web page authorization

### ISSUE THREAD

**Issue by baselakasha** [Foundry376/Mailspring#1581]
##### Are there any related issues?

...

##### What operating system are you using?
Linux Debian

##### What version of Mailspring are you using?

1.6.3

--

**Bug?**

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
Yes, must mail apps.

I am trying to connect my college email to the mailspring app. 
My college email service shows me a web login page to authorize me.
Normally when I log in to other mail apps I choose "other service" then I type my email and password, it redirects me to that login page to login. 

How to do that in mailspring?

**Comment by bengotow** [comment]
Hey! Right now we support this for Google Apps for Business, but it sounds like you may have an Office 365 school email?

**Comment by baselakasha** [comment]
@bengotow  Yes, I actually use an Office365 college email.

**Comment by bengotow** [comment]
Hey! Sounds good - merging this in to #258
