### ISSUE TITLE
Mailspring does not open any outside links

### ISSUE THREAD

**Issue by Hypocrite** [Foundry376/Mailspring#1587]
##### Are there any related issues?
https://github.com/Foundry376/Mailspring/issues/432

##### What operating system are you using?
Microsoft Windows 10 Home
Version 10.0.18362 Build 18362

##### What version of Mailspring are you using?
Version 1.6.3-134a0e55

##### Issue description

When clicking on links in email, nothing happens. Default browser is Chrome version 75.0.3770.142 (Official Build) (64-bit).

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Issue happens with all links.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—I tried to reproduce this but haven't had any luck (it seems to open properly for me for some reason.) Going to leave this here and we'll see if anyone else is running in to this so we can narrow it down a bit!
