### ISSUE TITLE
Is there a way to not "stack" emails?

### ISSUE THREAD

**Issue by Spidersouris** [Foundry376/Mailspring#1596]
##### Are there any related issues?

I didn't find any.
...

##### What operating system are you using?
Windows 10 Pro, x64
...

##### What version of Mailspring are you using?
1.6.3-134a0e55
...

--

I don't really know how to explain this, but when receiving an email from the same recipient and with the same title, it creates an email thread. Here's an image so it is clearer for all of you: https://i.imgur.com/qKgdtI7.png

Is there a way to make it so that, like eM client does, emails are shown separately, in their own "box" and don't create any thread?

Thanks.

**Comment by bengotow** [comment]
Hey! Unfortunately there's no way to turn off threading in Mailspring. It's a bit of a bummer, but the concept of threads is tied really deeply into the app's underlying data model and it'd take a lot of work to change. I think back in 2014 we imagined that email would be moving entirely to the conversation model, and in reality it's only gone about 80% of the way there.

**Comment by SylwesterZarebski** [comment]
@bengotow : Is it possible to change algorithm, to not use recipient+subject, but references (RFC) and thread-index (MS)? Even MS in Outlook has backed out from recipient+subject threading.
