### ISSUE TITLE
Japanese of the label is garbled.

### ISSUE THREAD

**Issue by kometchtech** [Foundry376/Mailspring#16]
##### Are there any related issues?

...
https://github.com/Foundry376/Mailspring/issues/15
##### What operating system are you using?
...
Windows 10 Pro 1703
##### What version of Mailspring are you using?
...
1.0.0
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
no
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
Gmail
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
![label](https://user-images.githubusercontent.com/5137077/31171308-26222066-a93a-11e7-8ee9-917d38318948.JPG)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by louim** [comment]
This was fixed in https://github.com/Foundry376/Mailspring/commit/37cd1a8c607493bfdd474bd9e59c15584814d5ae, which should be in the next release, see #9.

**Comment by bengotow** [comment]
Yep—this will be fixed in a release today. Stay tuned! Closing as dup of #9.
