### ISSUE TITLE
Menu Bar Icon on Mac does not get inverted when mode (light/dark) changes  

### ISSUE THREAD

**Issue by eugener** [Foundry376/Mailspring#1603]
##### Are there any related issues?

Not for MacOS I think

##### What operating system are you using?

MacOS 10 .15

##### What version of Mailspring are you using?

1.6.3

--

**Bug?**

Yes, The menu bar icon is not properly inverted when theme switches

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

Here are some screenshots. The client was installed when the dark appearance was on and the icon looked correct (white) 

![image](https://user-images.githubusercontent.com/341840/62538628-45715e80-b821-11e9-9699-411dccec8784.png)

After switching to light mode, the icon is still white and thus invisible

![image](https://user-images.githubusercontent.com/341840/62538674-61750000-b821-11e9-9c7e-850fb83ba45d.png)
![image](https://user-images.githubusercontent.com/341840/62538701-70f44900-b821-11e9-9b53-e7f4a598f4f9.png)

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

No

**Comment by bengotow** [comment]
Hey! I think this was actually an issue in the Mojave betas - it doesn't seem to happen for me anymore in 10.14.6 (as of right now, at least). Can you see if this is still happening for you? Let me know and I can re-open!

**Comment by eugener** [comment]
Tested on both Mojave and Catalina. It does not seem to happen anymore.
