### ISSUE TITLE
No Logo Showing I replied to an email.

### ISSUE THREAD

**Issue by ECMatt90** [Foundry376/Mailspring#1607]
New to Mailspring and like it overall.

When I reply to an email there is no logo in Mailspring showing that I replied.  Is there a way to turn this one?

**Comment by bengotow** [comment]
Hey @ECMatt90 — is this what you're looking for? I think Mailspring only shows these reply indicators if there aren't any new / unread messages on the thread and the thread is not starred (the star appears in the same place). Maybe that was the issue?

![image](https://user-images.githubusercontent.com/1037212/66435055-93553f00-e9e9-11e9-828e-a80c9bbfa60b.png)

Going to close this but let me know if you were thinking something else!
