### ISSUE TITLE
MailSpring won't load rbind no such file or directory on Manjaro Snap install

### ISSUE THREAD

**Issue by JpMaxMan** [Foundry376/Mailspring#1610]
##### What operating system are you using?

Manjaro latest

##### What version of Mailspring are you using?

snapd latest

--

**Bug?**

Suddenly MailSpring won't load - when I try from the command line I get:

cannot perform operation: mount --rbind /dev /tmp/snap.rootfs_QzATfm//dev: No such file or directory

**Comment by bengotow** [comment]
Hey! This sounds like a snapd issue unfortunately - you might have more luck over at https://forum.snapcraft.io/, they're usually pretty fast! I'd also recommend rebooting since sometimes snapd updates itself in the background and it seems to get "confused".
