### ISSUE TITLE
[Feature Request] - add instagram to signature creator

### ISSUE THREAD

**Issue by ikiru** [Foundry376/Mailspring#1611]
##### Are there any related issues?

People have requested linkedin and github as well to the signature creator.

...

##### What operating system are you using?

macOS Mojave 10.14.6

##### What version of Mailspring are you using?

1.6.3

--
Feature Request?

add instagram to the signature creator.

**Comment by piotrzarycki** [comment]
ok,  i will add

**Comment by bengotow** [comment]
Looks great @piotrzarycki — thanks! Going to mark this as pending release!

**Comment by bengotow** [comment]
Hey folks! This shipped today in 1.7.2 - you can download the update from our website at getmailspring.com/download or choose "Check for Updates" in the app's menu. Enjoy the update!
