### ISSUE TITLE
Mailspring Download Really Slow

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#162]
My internet's perfectly fine. I can download files from Google at 4.5MB/s. Yet for some reason, downloading the file from Mailspring is at 500KB/s. Is there any reason why it is so slow?

**Comment by bengotow** [comment]
Nope! It’s hosted on EC2 in the US-East region. Maybe if you’re overseas it’s slow?

**Comment by Modelmat** [comment]
Yep. I am in Australia, but it's still weird. Normal github has the same issue.

**Comment by Bouska** [comment]
I had the same problem two days ago when downloading the RPM of MailSpring 1.0.4 with Firefox; I was downloading at 150kB/s. I launch the same download with `wget`and could download at 3MB/s. Weird... I'm in France BTW.

**Comment by bengotow** [comment]
Interesting - on Linux we'll be moving to Ubuntu's Snapcraft servers soon (for installation via `snapd`) and I've noticed their setup is crazy fast, even here in SF. I think that'll be better for everyone on Linux.

Definitely interested in making the Mac/Windows install process faster as well. We can pay for an edge cache like Cloudflare but it'd be super expensive to send such a large file through it so many times. The best bet is probably using a "handful of mirrors" approach and picking the closest one, but it complicates things a bit.

**Comment by Modelmat** [comment]
@bengotow Maybe you could something like Mega or Google Drive and use that? Then all the mirror handling would be left to them.

**Comment by fakeid30** [comment]
@bengotow I've had this on my personal project too and I fixed it by moving to Digitalocean Spaces . I know they only have data center in NYC but it is crazy fast for me. 

Give it a thought.

**Comment by bengotow** [comment]
Hey folks! We recently moved the app downloads to Github's servers (which seem to be faster, and are also saving me $300/mo in Amazon S3 bills). Going to close this now 👍  Enjoy!

**Comment by imtiaz-rahi** [comment]
Well the DEB download is still crazy slow.
And I am not going to using snap. Uninstalled snap from my ubuntu laptop, so that's not an option.
