### ISSUE TITLE
Eventually sync errors appear--can only be fixed by hard killing the processes

### ISSUE THREAD

**Issue by nvesely** [Foundry376/Mailspring#1620]
After enough time running (since the background processes are not killed when Mailspring is closed), one or more of my 5 accounts always runs into irrecoverable sync issues. To fix these I use htop to hard kill all Mailspring processes (closing and re-opening is insufficient as the failing sync processes are not restarted that way), and I'm able to then re-open Mailspring and sync correctly.

Sometimes these errors are accompanied by prolonged high CPU usage. I'll notice my fan going, then check htop and see a Mailspring processes is using ~100% CPU, then the open Mailspring to find sync errors.

##### What operating system are you using?

Debian 10

##### What version of Mailspring are you using?

1.6.3-134a0e55

**Bug?**

##### Is this an email sync or connection issue?

Yes, it is a sync issue. I don't feel comfortable sharing logs publicly. Is there somewhere I could send them to?

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Gmail and Exchange seem regularly affected. Accounts not backed by those providers appear to be reliably syncing. I use OAuth to authenticate where applicable.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No.

**Comment by kadmonj** [comment]
Similar issue on Ubuntu 19.04
Same Mailspring version: 1.6.3-134a0e55
gmail account.
After a while I see a persistent message "syncing mail', with occasionally sync error appar. 

From the logs I get
```
19920 [2019-08-29 00:05:43.592] [main] [info] Identity created at 1566958133 - using ID Schema 1
19920 [2019-08-29 00:05:43.594] [main] [info] ------------- Starting Sync (kad***@gmail.com) ---------------
19920 [2019-08-29 00:05:43.597] [background] [info] Fetching XOAuth2 access token from Gmail for e3489d72
19920 [2019-08-29 00:05:43.598] [metadata] [info] Metadata delta stream starting...
19920 [2019-08-29 00:05:43.757] [background] [info] Marking all folders as `busy`
19920 [2019-08-29 00:05:43.758] [background] [info] Syncing folder list...
19920 [2019-08-29 00:05:45.625] [background] [info] Syncing folder list...
19920 [2019-08-29 00:05:46.036] [background] [info] syncFolderUIDRange for [Gmail]/All Mail, UIDs: 140832 - 143386, Heavy: false
19920 [2019-08-29 00:05:47.177] [background] [info] - remote=400, local=400
19920 [2019-08-29 00:05:47.275] [background] [info] Cleaning local cache and updating stats
19920 [2019-08-29 00:05:47.352] [background] [info] -- 0 message bodies deleted from local cache.
19920 [2019-08-29 00:05:47.532] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/All Mail: modseq 8049841 to 8049863, uidnext 143386 to 143386
19920 [2019-08-29 00:05:47.626] [background] [info] syncFolderUIDRange for [Gmail]/Trash, UIDs: 1 - 45737, Heavy: false
19920 [2019-08-29 00:05:48.272] [foreground] [info] syncFolderChangesViaCondstore - Changes since HMODSEQ 8049841: 0 changed, 0 vanished
19920 [2019-08-29 00:05:48.272] [background] [info] - remote=8, local=8
19920 [2019-08-29 00:05:48.272] [background] [info] Cleaning local cache and updating stats
19920 [2019-08-29 00:05:48.337] [background] [info] -- 0 message bodies deleted from local cache.
19920 [2019-08-29 00:05:48.365] [background] [info] Sync loop deleting unlinked messages with phase 2.
19920 [2019-08-29 00:05:48.374] [background] [info] Sync loop complete.
19920 [2019-08-29 00:05:48.381] [foreground] [info] Idling on folder [Gmail]/All Mail
19920 [2019-08-29 00:05:58.598] [metadataExpiration] [info] Scanning for expired metadata
19920 [2019-08-29 00:05:58.599] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
19920 [2019-08-29 00:06:03.599] [metadata] [info] Metadata delta stream timed out.
19920 [2019-08-29 00:06:03.613] [metadata] [critical] 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.316] invalid UTF-8 byte at index 0: 0xC0
 ***
```

**Comment by bengotow** [comment]
Hey folks - just a quick heads up that the `invalid UTF-8 byte at index 0` bug will be fixed in the next release this week. This turned out to be a tricky one and the app doesn't retry the connection because the error is actually thrown within the error handling logic for the sync worker. Stay tuned!
