### ISSUE TITLE
Could not store your password

### ISSUE THREAD

**Issue by zengxiaoliang** [Foundry376/Mailspring#1623]
##### What operating system are you using?

macOs  10.13.6

##### What version of Mailspring are you using?

1.6.3-134a0e55

**Bug?**

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Run app filled with message 

Running database migrations
App load time: 166ms
GVA info: Successfully connected to the Intel plugin, offline Gen95

{"error":null}
2019-08-27 11:26:10.568 Mailspring[35649:22872012] *** WARNING: Textured window <AtomNSWindow: 0x7f9dfcd091c0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
{ [Error: The user name or passphrase you entered is not correct.]
  message: 'The user name or passphrase you entered is not correct.' } { pluginIds: [] }

![image](https://user-images.githubusercontent.com/16423049/63739150-da1a2a00-c8be-11e9-8d7f-a5dc626c02be.png)

**Comment by bengotow** [comment]
Hey! Can you try opening Keychain Access on your Mac and making sure you can "unlock" the login keychain? It sounds like Mailspring is unable to access your system keychain, or you declined it's permission dialog when it prompted.

**Comment by zengxiaoliang** [comment]
work well after reinstall
