### ISSUE TITLE
Attachments (mail ghosting)

### ISSUE THREAD

**Issue by dale76uk** [Foundry376/Mailspring#1629]
using 1.6.3 on ubuntu 18.04

I'm having issues when adding attachments.  I'm unable to replicate this everytime but it seems to be prevalent with PDF attachments.  The mail page just "Ghosts" and you are forced to close the mail and try to continue from the Drafts folder.

I only encounter this issue using the drag and drop method.

See screenshot
![Screenshot from 2019-09-06 12-56-22](https://user-images.githubusercontent.com/9768923/64426240-f4fe5280-d0a5-11e9-847b-29beed423282.png)

**Comment by nfaivre** [comment]
Exact same problem, ubuntu 19.04, mailspring 1.6.3-134a0e55

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this - this is definitely interesting. Next times this happens, can you choose Developer > Toggle Developer Tools within the composer window and see if errors appear in the console there? It seems an exception of some sort must be thrown that causes the page to "stick".

**Comment by dale76uk** [comment]
I've managed to screen record this issue, nothing is displayed in the console window when this bug occurs.

https://youtu.be/hbwvgj-OIBs

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved — I've tried to replicate with Mailspring 1.8.0 and Ubuntu 20.04, and even large PDFs attach correctly — so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
