### ISSUE TITLE
Notifications working on only one account

### ISSUE THREAD

**Issue by josecarlosns** [Foundry376/Mailspring#1632]
##### Are there any related issues?

#1042 #1467 #160 #411

##### What operating system are you using?

Linux Mint 19.2 Cinnamon

##### What version of Mailspring are you using?

Mailspring v1.6.3-134a0e55
Installed from the .deb package available on the official site

--

**Bug?**

I have multiple accounts linked to mailpring but I'm only receiving notifications for the first one. (possibly related to #160 and #1467 ). I thought that maybe thats how it its and notifications for all accounts is a premium feature that I'm too free-user to get, but I didn't read anything about it in the home page.

Also the system tray icon doesn't do anything when I have new unread e-mails, even for the first account, only if the app is minimized it changes (possibly related to #1042 and #411 )

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

**Comment by bengotow** [comment]
Hey! I think this is related to the other two issues, will get this release out this week and we can verify!

**Comment by josecarlosns** [comment]
I've just installed version 1.7.0

The following issues:

- System tray icon not updating on new emails received. (#411 )
- Notifications for new emails not working properly. (#160) 

And this issue (notifications only for one account) **ARE ALL FIXED!**

Good job Mailspring team! 

I :heart:  you all!
