### ISSUE TITLE
Cannot fully uninstall Mailspring - what gives?

### ISSUE THREAD

**Issue by mausergirl** [Foundry376/Mailspring#1635]
My boss asked me to test different email programs to help find one that will best fit her needs. She is older and has been overwhelmed with some of the full-featured programs like Outlook and wanted something simpler. 

We tried Mailspring, but she didn't like it - the lack of address book and calendar function didn't work for her. So I've uninstalled it following the directions here (https://foundry376.zendesk.com/hc/en-us/articles/115001882612-Uninstalling-Mailspring) but it keeps f*n reinstalling "Mailspring" folders in any other email program we are trying.

I've searched for Mailspring in Windows Explorer and literally deleted everything. And the folders keep. popping. up. in eM or Thunderbird or any other program I try. How in the heck do I get rid of these Mailsping folders? It's like a virus. >:(

**Comment by user00101010** [comment]
Did you disconnect Mailspring and remove the IMAP folders from the online account?

**Comment by bengotow** [comment]
Hey @mausergirl —thanks for reporting this. It sounds like when you uninstalled Mailspring, it may have still been running in the background. (To deliver new mail notifications, etc.) You can quit it from a small icon in the system tray or restart your computer after uninstalling. After that, it shouldn't re-create it's Mailspring folder!

Sorry for the hassle,
