### ISSUE TITLE
Getting error while trying to send email

### ISSUE THREAD

**Issue by uplabhijit** [Foundry376/Mailspring#1639]
##### Are there any related issues?
Not able to find any issue related to the issue that I am facing.

##### What operating system are you using?
Macair - macOS Mojave (10.14.6)

##### What version of Mailspring are you using?
Version 1.6.3 (1.6.3)

**Bug?**

##### Is this an email sync or connection issue?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
The mailbox is from gsuite (google)

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No idea

![image](https://user-images.githubusercontent.com/41364678/65501316-6def0e00-dede-11e9-89fb-5ed985264660.png)

**Comment by bengotow** [comment]
Hey! Thanks for filing this—if this happens again, could you see if there's a particular set of steps that made this happen? Maybe switching which account you're sending from / using a template? Not sure how this could happen offhand.

**Comment by uplabhijit** [comment]
I am getting this email everyday and it's same error, not able to find any content in the email body. I do not know how can we change the template here. As you can check the email that I had forwarded earlier, it's a large email content in the body.

Check if this can be addressed else we will wait it whenever it gets resolve.
