### ISSUE TITLE
Folder names containing dots result in syncing problems with RoundCube

### ISSUE THREAD

**Issue by cascornelissen** [Foundry376/Mailspring#164]
##### Are there any related issues?
#158 might be related, as well as #91, although I'm not experiencing any high CPU/memory usage.

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.0.4-e604c991

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No third-party plugins installed

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No, I'm having this issue with an IMAP-account

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

--

When connecting to an IMAP-account that's being provided by [TransIP](https://www.transip.com/) Mailspring connects successfully and starts syncing but it looks like it gets stuck on the `[Mailspring].Snoozed` folder. It will stay this way forever. The entire mailbox is just under 3MB in size according to the webmail interface from TransIP ([RoundCube](https://roundcube.net/)).

![image](https://user-images.githubusercontent.com/1304939/31584108-0d56b97c-b1a8-11e7-89e5-bbdaab3fe882.png)

I can open/read e-mails but whenever I click on a conversation in the list the following alert comes up. Clicking Okay hides the alert and shows the e-mail but I can't do anything with the e-mail (like deleting/moving/archiving), it just shows the same alert and the keeps the e-mail in the inbox.

![image](https://user-images.githubusercontent.com/1304939/31584121-5f4813a2-b1a8-11e7-957e-a604c241570e.png)

The `[Mailspring].Snoozed` folder never shows up in the RoundCube instance either so I'm thinking the problem is in the name of the snoozed folder. Creating a folder `Test.Test` in RoundCube throws the following error:

> Folder name contains a forbidden character. (.)

**Comment by cascornelissen** [comment]
I previously used Nylas Mail which worked correctly with this account and the Snoozed folder name there was `N1-Snoozed`

**Comment by cascornelissen** [comment]
Alright, I haven't found the problem or where the dot comes from but I've since switched from RoundCube to G Suite from Google and thus can't really test this problem any more.

I'll leave it open in case anyone else runs into this problem.

**Comment by bengotow** [comment]
Looks like this folder name is also an issue with mail.163.com and mail.cstnet.cn, and secureserver.net. Will see if we can get this fixed in the next major release.

**Comment by bengotow** [comment]
Hey folks—the fix for this has been shipped in 1.1.2 today. The app will autoupdate in the next few hours, or you can download the new version directly from https://getmailspring.com/download. Enjoy!

It turns out that several other mail providers also don't support folder names like `[Mailspring]`, so we've changed the app to create a `Mailspring` folder instead.
