### ISSUE TITLE
How to add new keyword shortcuts

### ISSUE THREAD

**Issue by pablorq** [Foundry376/Mailspring#1640]
##### Are there any related issues?

No related issues.

##### What operating system are you using?

Windows7, Windows10

##### What version of Mailspring are you using?

version 1.6.3-134a0e55

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Yes.

How can I add a new shortcut to add a sign when composing an email?

There is a list of all possible commands, like "composer:select-attachment", to add new shortcuts?

Regards.

**Comment by bengotow** [comment]
Hey! If you visit Preferences > Shortcuts, you can click an existing shortcut to enter / type a new combination you'd like to use. There are a few commands that you can bind shortcuts to that aren't listed there and must be added to your keymaps file manually, but unfortunately we don't ahve an up-to-date list.  Any of the "command" values you find in the menu files are valid: https://github.com/Foundry376/Mailspring/blob/master/app/menus/darwin.json

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/1037212/66434492-4e7cd880-e9e8-11e9-85ac-934168406335.png">

**Comment by pablorq** [comment]
I think the correct url is https://github.com/Foundry376/Mailspring/blob/master/app/menus/darwin.js

But again in this file says nothing about a command to add a signature in composer, which later can be added as a shortcut.

Where is the 'add signature' button in composer, and how can be called to add a shortcut?
