### ISSUE TITLE
Composer: Add option to set language

### ISSUE THREAD

**Issue by pablorq** [Foundry376/Mailspring#1641]
##### Are there any related issues?

#129 

##### What operating system are you using?

Windows7, Windows10

##### What version of Mailspring are you using?

1.6.3-134a0e55

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Yes.

It would be nice to have a drop-down list to select 'automatic', 'en-en', 'en-us', 'en-uk', 'es-es', etc., to be able to force the spell checking.

The drop-down list can be configured on 'preferences' with a list of selected languages from a large list with (all ?) the languages. Android style.

Regards.

**Comment by bengotow** [comment]
Hi - you can set the language in preferences under General > Composing here:



<img width="501" alt="image" src="https://user-images.githubusercontent.com/1037212/66434407-1a091c80-e9e8-11e9-8a73-83747315f01d.png">

**Comment by pablorq** [comment]
Yes, this a general language setting.

But I mean to select and force the language in the composer, instead of the automatic language detection.

I'm thinking to have in composer a drop down list set in automatic but also with some 'favorite' languages, like en-en, en-us, en-uk, es-es, etc.. The configuration of this favorite languages can be added to the preferences, along with the general language setting.

Do I explain it ok or just I add confusion to this feature request?
