### ISSUE TITLE
Not able to read email sent from cPanel

### ISSUE THREAD

**Issue by uplabhijit** [Foundry376/Mailspring#1646]
##### Are there any related issues?

Not able to find any issue related to the issue that I am facing.
...

##### What operating system are you using?
Macair - macOS Mojave (10.14.6)
...

##### What version of Mailspring are you using?
Version 1.6.3 (1.6.3)
...

--

**Bug?**

##### Is this an email sync or connection issue?

No, as email is available in the list of emails, but not opening the mail in email reader.
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
cPanel via Amazon SES
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Can provide copy of the email to any specific developer email.
...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
No

...

**Comment by bengotow** [comment]
Hey! If you could use another mail client to redirect the message to me at ben@foundry376.com I'd be happy to take a look there. If your webmail doesn't have a redirect option, see if you can "Show Original" and send me the raw MIME! (Sometimes when forwarding the messages get modified so much they work.)
