### ISSUE TITLE
[Feature Request] Option to always show full headers

### ISSUE THREAD

**Issue by pablorq** [Foundry376/Mailspring#1647]
##### Are there any related issues?

Not found.

##### What operating system are you using?

Windows 7 / Windows 10

##### What version of Mailspring are you using?

1.6.3-134a0e55

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Yes.

Please add an option in 'Preferences' to show the full headers (from, to, cc, cco, date, time, folder) on each email.

Right now you can only see 'from', a grouped 'to' and 'cc', and date. This is not enough in most of the cases, in my case. To see the full headers you have to click the headers to expand them.

A 3rd option can be something like the actual view with 2 grouped fields: 1 for 'to' and other for 'cc'.

**Comment by bengotow** [comment]
Hey! This is coming in the next release which will be out this week - stay tuned!

![image](https://user-images.githubusercontent.com/1037212/66433748-a1ee2700-e9e6-11e9-9c41-bca56a559ce9.png)

**Comment by pablorq** [comment]
Oh! What a nice!

👍

**Comment by bengotow** [comment]
Hey folks! This shipped today in 1.7.2 - you can download the update from our website at getmailspring.com/download or choose "Check for Updates" in the app's menu. Enjoy the update!
