### ISSUE TITLE
Attached image/s are always inline instead of attached

### ISSUE THREAD

**Issue by pablorq** [Foundry376/Mailspring#1653]
##### Are there any related issues?

#1283 Possible related

##### What operating system are you using?

Windows 7/10

##### What version of Mailspring are you using?

v1.6.3-134a0e55

--

**Bug?**

##### Is this an email sync or connection issue?

No log related

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Any provider. Is for composer.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Steps to reproduce:
- Create a new email
- Drag and drop an image to the new email, or click in attach and browse for the image.
- In any case the image is set inline, instead as an attached file.

Expected behavior:
- Drop an image on the email: inline image.
- Click on the attach button: image attached as a file.
- Drop in the attach button: image attached as a file.

**Comment by bengotow** [comment]
Hey! This is actually more or less how Mailspring works currently, but both attachments (inline and file) are rendered in the same way if they're images which makes it pretty confusing.

If you drag and drop an image in, it's inline and you can write text before / after it and drag it around the message.

If you click "Attach file" and choose the file, it's always at the bottom of your document and you can't type beneath it, etc. It still looks like the other image though.

I'll see if we can differentiate these a bit in the next release!

**Comment by bengotow** [comment]
Actually, thinking about this a bit more, I think I'm going to revert the display of image "attachments" to always look like files, like this:

<img width="778" alt="image" src="https://user-images.githubusercontent.com/1037212/66446977-30c46900-ea12-11e9-8968-d36c6ddaaa2d.png">

**Comment by pablorq** [comment]
Actually, as you can see on your image, you have both the attached image and the inline image, which is a bit confuse.

As proposed before, you can split the composer behavior as follows:
- Drop an image on the email: inline image.
- Click on the attach button: image attached as a file.
- Drop in the attach button: image attached as a file.

Is just an idea.

:)

**Comment by pablorq** [comment]
It works nice in v1.7.1!

Just an improvement idea:
- Drop in email body: image inline
- Drop in the bottom bar (where the attach icon is): image attached

:)

**Comment by bengotow** [comment]
Hey folks! This shipped today in 1.7.1 - you can download the update from our website at getmailspring.com/download or choose "Check for Updates" in the app's menu. Enjoy the update!

I like the idea of making dropping in the bottom bar attach the item as a file attachment, I'll see if we can add that soon!
