### ISSUE TITLE
Have 2 accounts set up.  Some emails from one inbox also are displayed in other inbox.

### ISSUE THREAD

**Issue by cryoknight** [Foundry376/Mailspring#1654]
Hi!  Mailspring is great!  However, I am noticing one issue that has been happening ever since installing MailSpring.

I set up one gmail account and one hotmail account.   When looking at my gmail inbox, some of the emails from my hotmail account are being displayed in it.  When I click on the "To: You" line, it shows the hotmail email address.  I am looking at the gmail inbox, not the unified inbox.

When I look at the Unified inbox, many of the emails appear duplicated.

Thanks!

##### Are there any related issues?

**I did not see other bugs like this one.**

...

##### What operating system are you using?

**Windows 10**

##### What version of Mailspring are you using?

**1.6.3-134a0e55**

**Bug?** Looks like it

##### Is this an email sync or connection issue?

**Looks like a sync issue**

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Happening with some (not all) hotmail emails being displayed in gmail inbox, but only happens in MailSpring.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![MailSpringHotmailGmailBug](https://user-images.githubusercontent.com/929773/66338481-0ed5c400-e8f6-11e9-8fe8-2d41044a2d23.jpg)

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by bengotow** [comment]
Wow this is pretty wild—I don't think I've seen this one before.

Is there any chance you migrated your email at one point, and the same messages exist in both accounts?

Could you try navigating to a hotmail email and clicking the white-space to the left of the "Reply" button in the message panel? It will show a context menu with some debug options, and I'd love if you could choose "Copy Debug Info" and paste it here. And repeat for one of the Gmail messages.

<img width="482" alt="image" src="https://user-images.githubusercontent.com/1037212/66446373-e641ed00-ea0f-11e9-90f0-5002afbb65d1.png">

Mailspring generates unique IDs for each account you link, and it's possible that these two email accounts happen to generate the same 10-character string, but that seems crazy!

**Comment by cryoknight** [comment]
Now I feel silly. I looked through my gmail settings (... at gmail.com) and it turns out I had set up my gmail account to check my hotmail emails. Okay, this is not a bug. I just never noticed it until using Mailspring.
