### ISSUE TITLE
Switching accounts

### ISSUE THREAD

**Issue by fly1ngDream** [Foundry376/Mailspring#1657]
Am I able to change **Ctrl + 1, 2, 3, ...** to **Alt + 1, 2, 3, ...** or any other key for switching accounts? If no, it would be good to have such an option. I find Alt much more convenient

**Comment by bengotow** [comment]
Hey! We don't support this unfortunately and it was designed to match other apps like Slack (at least on the Mac, both Mailspring and Slack use Cmd-[1,2,3].) Sorry for the hassle!
