### ISSUE TITLE
Need a way to copy version numbers

### ISSUE THREAD

**Issue by keithyipkw** [Foundry376/Mailspring#1658]
It is such a pain and error-prone to report the version when you need to memorize it and type it yourself.

...

##### What operating system are you using?
Win 10
...

##### What version of Mailspring are you using?
1.6.3-134a0e55
...

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Most of the programs

...

**Comment by bengotow** [comment]
Hey! Sorry for the hassle—we only ship one commit hash for each version, so it's actually OK to just report the 1.6.3 part! I'll update the issue template so it's a bit more clear.
