### ISSUE TITLE
Badge counter is behind

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#167]
##### Are there any related issues?

...

##### What operating system are you using?
MacOS 10.12.6

##### What version of Mailspring are you using?
1.0.4

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Don't think so

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Archive or delete emails from the inbox.
Badge counter seems to eventually get out of sync
E.g. right now if I select every email in my inbox manually, Mailspring says "20 threads selected", but badge counter says 22
Badge counter seems to eventually catch up after anywhere between 5 and 60 minutes

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—I think this is the same issue that was reported in #485. If you moved unread email to another /folder/ (usually trash), the badge counter would take much longer to update than if you archived it or moved it to a label.
