### ISSUE TITLE
[Feature Request] ZX2C4's pass instead gnome-keyring

### ISSUE THREAD

**Issue by helionmelion** [Foundry376/Mailspring#1670]
Instead using gnome-keyring for storing passwords, option for use "pass" (password-store).

##### Does this feature exist in another mail client or tool you use?
For thunderbird as an add-on, **but was discontinued**. Maybe its not so popular at all. For many web browsers this integration exists.
Thank you very much.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we're actually dependent on a project called keytar for password storage which works with anything compatible with libsecret (eg: gnome-keyring). Maybe you could file an issue there and see if they could make that library compatible with `pass`! https://github.com/atom/node-keytar
