### ISSUE TITLE
Sync error on adding new Yahoo Mail account

### ISSUE THREAD

**Issue by josiasmat** [Foundry376/Mailspring#1672]
Mailspring version 1.7.1, Windows 10 x64. When I add a new Yahoo Mail account, it triggers a sync error. That means it is impossible to make an Yahoo Mail account to work. Tested on two PCs. The log file says:

> 19828 [2019-10-17 15:28:30.581] [main] [info] Identity created at 1536074444 - using ID Schema 1
> 19828 [2019-10-17 15:28:30.582] [main] [info] ------------- Starting Sync (******@yahoo.com.br) ---------------
> 19828 [2019-10-17 15:28:30.585] [background] [info] Marking all folders as `busy`
> 19828 [2019-10-17 15:28:30.585] [background] [info] Syncing folder list...
> 19828 [2019-10-17 15:28:30.585] [metadata] [info] Metadata delta stream starting...
> 19828 [2019-10-17 15:28:32.874] [background] [critical]  *** Stack trace:
>  ***   raise
>  ***   abort
>  ***   terminate
>  ***   _is_exception_typeof
>  ***   _is_exception_typeof
>  ***   RtlInterlockedCompareExchange64
>  ***   RtlInterlockedCompareExchange64
>  ***   KiUserExceptionDispatcher
>  ***   _CxxThrowException
>  ***   _o_iswdigit
>  ***

**Comment by bengotow** [comment]
Hmm it looks like this was reported recently in #1628, going to merge these (though I have no idea what that means, will keep digging in to this one...)

**Comment by josiasmat** [comment]
I think this is not the same issue as #1628, since I have absolutely no problem with any e-mail accounts other than Yahoo Mail, and the issue with Yahoo always occurs (not at random times), and only with new accounts -- I have another Yahoo Mail account which I added on an older version of Mailspring, and it simply works.

Please reopen.
