### ISSUE TITLE
Confidentiality and Privacy Security

### ISSUE THREAD

**Issue by sebhochuli** [Foundry376/Mailspring#1675]
**Personnal use**

Mailspring version 1.7.1

**Feature Request**

Documents in **C:\Users\username\AppData\Roaming\Mailspring\files** are not secured. Files should be crypted or deleted for a best security.

**Comment by bengotow** [comment]
Hey! For now our official recommendation is that you encrypt your whole drive at rest using something like FileVault on macOS or VeraCrypt on Windows. Thanks!
