### ISSUE TITLE
[feature request] Remove focus on specific email when turning on reading pane

### ISSUE THREAD

**Issue by tvercaut** [Foundry376/Mailspring#1679]
When using Mailspring with the reading pane hidden, putting the focus on an email does not mark it as read which is the expected behaviour. Then when turning on the reading pane, the message that had the focus is now inadvertently marked as read. To avoid marking it as read, it would be safer to change this behaviour and loosing the focus on a particular email when turning on the reading pane.

##### Are there any related issues?

#231 is remotely related

##### What operating system are you using?

Mac OS X Catalina

##### What version of Mailspring are you using?

1.7.1

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Not that I know

**Comment by bengotow** [comment]
Hey! This is a good point and I think we can fix this pretty easily - will take a look!

**Comment by bengotow** [comment]
Hey folks! This shipped today in 1.7.2 - you can download the update from our website at getmailspring.com/download or choose "Check for Updates" in the app's menu. Enjoy the update!
