### ISSUE TITLE
Two Panel View Position Not Maintaining

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#168]
##### Are there any related issues?
No
...

##### What operating system are you using?
Windows 10
...

##### What version of Mailspring are you using?
1.0.4
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No
...

If I position the view so that I have large email tiles (like outlook), and restart mailspring, it goes back to the default of the thin tiles (like gmail).

--

**Comment by bengotow** [comment]
Hey! This would be a great bug for someone interested in contributing - the `AppEnv` class handles loading and saving a file called "main-window-state.json" that should be storing these values. It'd be interesting to determine whether the file isn't being written or isn't being read when the app launches.

**Comment by bengotow** [comment]
Hey! This should be fixed in the latest releases which use a different method of saving the panel positions. Thanks for reporting this!
