### ISSUE TITLE
[Feature Request] Allow for multiple identities with different SMTP servers.

### ISSUE THREAD

**Issue by alvaro-munoz** [Foundry376/Mailspring#1680]
It would be great to allow to set up different identities (just like alias) but allowing to use different SMTP servers for each identity.

##### Are there any related issues?

Not that I know of

##### What operating system are you using?

Windows 10 and Linux

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

Latest

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Thunderbird

**Comment by bengotow** [comment]
Hey! We don't plan to support advanced IMAP / SMTP configurations to Mailspring—Thunderbird is definitely best for scenarios like this where you need to deliver mail through multiple SMTP gateways in the same account.
