### ISSUE TITLE
Right sidebar is empty when opening it without any email selected

### ISSUE THREAD

**Issue by mhatvan** [Foundry376/Mailspring#1681]
##### Are there any related issues?
Nope

##### What operating system are you using?
Ubuntu 19.04

##### What version of Mailspring are you using?
1.7.1

**Bug?**

##### Is the issue reproducible with a particular attachment, message, signature, etc?
1. select any of the menu items e.g. "Inbox" or "Unread"
2. don't have any email selected
3. click on person icon to the right that says "show sidebar"
4. expect it to open blank  

![mailspring bug](https://user-images.githubusercontent.com/16797721/67150950-d1424500-f2be-11e9-8d85-248c511a8eb8.png)

**Potential fix**
Hide person icon when there is no email focused/selected

**Comment by bengotow** [comment]
Hey! This is expected behavior for now (it appears empty rather than "popping" in and out as you select / deselect conversations), but  I think that the sidebar will be refactored soon to have tabs and show a calendar day view so this may not be an issue for you for long! Thanks!
