### ISSUE TITLE
Add/Remove account closes Preferences window

### ISSUE THREAD

**Issue by mslourens** [Foundry376/Mailspring#1684]
##### What operating system are you using?
Linux Mint 19.2

##### What version of Mailspring are you using?
1.7.2

**Bug?**
Steps to reproduce:
1. Open the preferences window
2. Remove an account
--> the Preferences window closes

Expected behavior: The preferences window remains open and editable

The same happens with adding an account.

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in a recent update. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down!
