### ISSUE TITLE
Never translate dialog freezes

### ISSUE THREAD

**Issue by xcashy** [Foundry376/Mailspring#1685]
When i click in the Translation Widget on Options -> Never translate German an Dialog asks me if Im sure to do this. The Dialog doesnt recognize my input so I can't click on the yes or no button.
I'm using the 0.7.1 version in Linux.

**Comment by njascanu** [comment]
I confirm. You cannot click on the dialog's Yes or No buttons. However, it works using keyboard Left, Right and Enter.

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this - I don't think I've heard of this before but I'll see if I can fix it today.

**Comment by jamy3531** [comment]
the same problem with mailspring on my deepin linux os

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
