### ISSUE TITLE
Fails to open GUI on PopOS 19.10 (Ubuntu)

### ISSUE THREAD

**Issue by DylanC** [Foundry376/Mailspring#1697]
##### What operating system are you using?
PopOS 19.10 (Ubuntu 19.10)
...

##### What version of Mailspring are you using?
1.7.2
--

##### What is the issue?
I have used Mailspring on 18.04 previously. So I do have an account to login with. After going through the initial setup screen I click sign in and get the following error:
![Screenshot from 2019-11-02 15-41-04](https://user-images.githubusercontent.com/4488048/68073364-4ca7fa00-fd87-11e9-9f1a-f503bc268831.png)

--

**Comment by mhatvan** [comment]
I am using mailspring on Ubuntu 19.10 as well and didn't encounter the error you are experiencing.
Did you try to install potential missing `libscret` and related libs? https://www.howtoinstall.co/en/ubuntu/xenial/libsecret-tools

**Comment by DylanC** [comment]
@mhatvan - I can install this manually. However, I feel if MailSpring depends on this lib it should be added to the dependencies. Otherwise MailSpring will not work on distros that are built on the Ubuntu base image. (Ubuntu based distros)

**Comment by DylanC** [comment]
@mhatvan - I have removed MailSpring for now. I'll wait until they fix the dependencies before I try it again.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
