### ISSUE TITLE
Certificate Error (SMTP) with STARTTLS

### ISSUE THREAD

**Issue by StoppingBuck** [Foundry376/Mailspring#1698]
I'm basically experiencing the same problem (and solution) as #66 from two years ago. I'm using the ProtonMail Bridge (https://protonmail.com/bridge/) on Arch Linux, but the default configuration is refused with a Certificate Error for the SMTP part, I have to Allow unsecure SSL in order to successfully add the account.

##### What operating system are you using?
Arch Linux

##### What version of Mailspring are you using?
1.7.2-4522b259

--

**Bug?**

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Have only experienced it with ProtonMail, using the official ProtonMail Bridge, which should be compatible with all IMAP/SMTP clients.

**Comment by SinTan1729** [comment]
I'm having this problem with Gmail via oauth.

**Comment by odelucca** [comment]
Same issue here

**Comment by redactedscribe** [comment]
Same.

Apparently this is because Bridge certificate is self-signed. The only way to proceed with the account setup in Mailspring is to "Allow insecure SSL", but even still, the emails never sync.

Conclusion: Bridge doesn't work with Mailspring.

**Comment by bengotow** [comment]
Hey folks—yep Bridge does not work with Mailspring. We tried hard (#429) but they seem to have wrote their own IMAP protocol implementation and it's nonstandard in some ways that would require us to patch libMailCore to fix (one of those beautiful old C++ libraries with tons of if statements from a decade of tweaking and no tests).

It's definitely unusual to have this problem with Gmail and other providers. It may be that you need to install the ca-certificates package (https://www.archlinux.org/packages/core/any/ca-certificates/) to have the root certs in the place Mailspring is looking for them. On Linux, we use this code to locate the certificates that should be used:

```
string FindLinuxCertsBundle() {
#ifdef __linux__
    std::string certificatePaths[] = {
        // Debian, Ubuntu, Arch: maintained by update-ca-certificates
        "/etc/ssl/certs/ca-certificates.crt",
        // Red Hat 5+, Fedora, Centos
        "/etc/pki/tls/certs/ca-bundle.crt",
        // Red Hat 4
        "/usr/share/ssl/certs/ca-bundle.crt",
        // FreeBSD (security/ca-root-nss package)
        "/usr/local/share/certs/ca-root-nss.crt",
        // FreeBSD (deprecated security/ca-root package, removed 2008)
        "/usr/local/share/certs/ca-root.crt",
        // FreeBSD (optional symlink)
        // OpenBSD
        "/etc/ssl/cert.pem",
        // OpenSUSE
        "/etc/ssl/ca-bundle.pem",
    };
    for (const auto path : certificatePaths) {
        struct stat buffer;
        if (stat (path.c_str(), &buffer) == 0) {
            return path;
        }
    }
#endif
    return "";
}

```

Hope that helps! Sorry for the delay addressing this one, will re-open if there's follow-up!

**Comment by mitchelnelson** [comment]
I want to add for anyone who is looking for something to try in 2024, something different worked for me. I was having trouble with Gmail auth, and I turned on access for less secure apps in my Google Account. I no longer had issues with SMTP or IMAP errors on pop!_OS after this.
![image](https://github.com/Foundry376/Mailspring/assets/66894405/cf5d1216-5442-4b07-8f5e-4f555f20aad5)
