### ISSUE TITLE
I can't add 2 accounts on Mailspring!

### ISSUE THREAD

**Issue by JumperLuko** [Foundry376/Mailspring#1699]
##### Are there any related issues?
Maybe, I not found a solution

##### What operating system are you using?
Using Ubuntu 19.10

##### What version of Mailspring are you using?
Version 1.7.2-4522b259 (deb amd64 and snap)

**Bug?**

##### Is this an email sync or connection issue?
in period of try to sync, i got this in file mailsync-38296bca.log.

```
23806 [2019-11-05 14:16:36.242] [background] [info] Syncing folder list...
23806 [2019-11-05 14:16:37.323] [background] [info] syncFolderUIDRange for [Gmail]/Todos os e-mails, UIDs: 23173 - 23174, Heavy: true
23806 [2019-11-05 14:16:38.913] [background] [info] - remote=1, local=0
23806 [2019-11-05 14:16:38.919] [background] [info] syncFolderUIDRange for [Gmail]/Todos os e-mails, UIDs: 22565 - 23174, Heavy: false
23806 [2019-11-05 14:16:39.942] [background] [info] - remote=401, local=401
23806 [2019-11-05 14:16:40.870] [background] [info] syncFolderUIDRange for [Gmail]/Lixeira, UIDs: 1 - 5609, Heavy: false
23806 [2019-11-05 14:16:41.210] [foreground] [info] Idle exited with code 0
23806 [2019-11-05 14:16:42.735] [background] [info] - remote=114, local=114
23806 [2019-11-05 14:16:43.031] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/Todos os e-mails: modseq 1732951 to 1733055, uidnext 23174 to 23175
23806 [2019-11-05 14:16:43.640] [background] [info] syncFolderUIDRange for [Gmail]/Spam, UIDs: 1 - 961, Heavy: false
23806 [2019-11-05 14:16:44.084] [foreground] [info] syncFolderChangesViaCondstore - Changes since HMODSEQ 1732951: 2 changed, 0 vanished
23806 [2019-11-05 14:16:44.582] [foreground] [info] Idling on folder [Gmail]/Todos os e-mails
23806 [2019-11-05 14:16:44.677] [background] [info] - remote=18, local=18
23806 [2019-11-05 14:16:44.686] [background] [info] Sync loop deleting unlinked messages with phase 2.
23806 [2019-11-05 14:16:44.693] [background] [info] Sync loop complete.
23806 [2019-11-05 14:16:44.693] [background] [info] Syncing folder list...
23806 [2019-11-05 14:16:46.642] [background] [info] Sync loop deleting unlinked messages with phase 1.
23806 [2019-11-05 14:16:46.645] [background] [info] Sync loop complete.
```

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I tried in Gmail account, tried in multiple accounts, tried in multiple versions in the last months.
Tried in Ubuntu 18.04, Ubuntu 19.04, Ubuntu 19.10, Mint 19 and Debian 9.
In Debian 9 I was able to add only 2 account.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I just click to add a Gmail account > select the account on Chrome Browse > Mailspring say connecting > little window close > nothing happens.
![Screenshot from 2019-11-05 14-26-53](https://user-images.githubusercontent.com/22037309/68230742-69873c00-ffd8-11e9-8053-7d37eafa5a36.png)

Only the first account is logged, any second not working (but it works on windows).
![Screenshot from 2019-11-05 14-30-53](https://user-images.githubusercontent.com/22037309/68231762-6ab96880-ffda-11e9-809b-8702578de442.png)

**Comment by JumperLuko** [comment]
I tried in another user account, and works, what just happens?

**Comment by bengotow** [comment]
Hey @JumperLuko — thanks for filing this! Could you clarify, did this work when you linked a different second account? It sounds like there may have been something specific about the second account you tried to link but it's hard to provide more steps without knowing what email provider you're trying to connect. Thanks,
