### ISSUE TITLE
No instructions on how to edit keymap.json

### ISSUE THREAD

**Issue by nickolasclarke** [Foundry376/Mailspring#170]
##### Are there any related issues?

None

##### What operating system are you using?
Win 10

##### What version of Mailspring are you using?
1.0.4

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
As far as I can tell, there are no instructions on how to use the keymap.json. Can you override existing mappings or only add new ones? If so, can you remap for certain accounts (i.e. remap `e` to move to an "Archive" folder on non-gmail providers but maintain its existing functionality for providers that support archiving) If some basic instructions can be provided, I'll gladly flesh them out and submit a PR. However, its also not clear where such info should be kept in the project at the moment.

**Comment by bengotow** [comment]
Hey! There are no instructions for editing `keymap.json`, but you can click the mappings in Preferences > Keymaps to change them. There are a few keybindings that aren't displayed there, but only a handful.

Hope that helps - you can find more documentation of this here: https://foundry376.zendesk.com/hc/en-us/articles/115001882572-Using-and-customizing-keyboard-shortcuts

**Comment by lode** [comment]
What helped me as well was a list of shortcut presets. This helped with both naming the shortcuts and with how to describe modifier keys and multiple shortcuts.

See https://github.com/Foundry376/Mailspring/tree/master/app/keymaps/templates
