### ISSUE TITLE
Unable to use port 2525 for smtp

### ISSUE THREAD

**Issue by jbmckee** [Foundry376/Mailspring#1702]
I am unable to enter custom port 2525 when setting up an smtp outgoing server. When I type 25 it just select 25 in the dropdown.

**Comment by bengotow** [comment]
Wow that really sucks—I'll get this fixed. In the meantime, you may be able to do this by pasting the full number into the field instead of typing it!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
