### ISSUE TITLE
email improperly parsed in title

### ISSUE THREAD

**Issue by nickolasclarke** [Foundry376/Mailspring#171]
##### Are there any related issues?

none that I can find.

##### What operating system are you using?
Win 10

##### What version of Mailspring are you using?
1.0.4

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Zoho, possibly all generic IMAP providers

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![snip_20171016142258](https://user-images.githubusercontent.com/2177320/31597911-886b48dc-b27d-11e7-85cd-0d4a809ca904.png)

Send to an email not in your address book, and sometimes parses with an unescaped \ backslash. I thought it may be related to when there is more than 1 recipient, but it doesnt look to be consistent. It could also be related to the non-traditional TLD perhaps? 

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! Thanks for reporting this. I haven't been able to reproduce this yet - i think it might be specific to Zoho. I think the best bet might be updating the parser to strip the leading and trailing quotes, so I'll see if we can address that in an update.

**Comment by nickolasclarke** [comment]
great. On a possibly related note, its not clear where the address book  / contacts are synced from. On windows it appears it may actually pull from the local "people" app + build it's own internally based off of your synced mail perhaps? I can open up a new ticket / feature request to be able to manage your contact sync if needs be.

**Comment by bengotow** [comment]
Hey folks! It's been a few years and there haven't been any more reports of this issue so I'm going to close this as probably-fixed. Feel free to bump or create a new issue referencing this one if you encounter this again!
