### ISSUE TITLE
New Install Blocked by Windows 10 Smartscreen

### ISSUE THREAD

**Issue by darrylmorley** [Foundry376/Mailspring#1710]
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10
...

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)
1.7.2
--

**Bug?**
Windows Defender Smartscreen blocks the install of Mailspring....
You can overide this but sure to raise concern with users?

##### Is this an email sync or connection issue?
No

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I would expect so.
...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by darrylmorley** [comment]
No response, closing

**Comment by bengotow** [comment]
Hey folks—yep this is usually resolved within a day after a release. It seems the new installer is marked as suspicious until it's been scanned on a large enough number of machines. Thanks for filing this!
