### ISSUE TITLE
Double-click required to open draft

### ISSUE THREAD

**Issue by djfredalert** [Foundry376/Mailspring#1718]
MacOS 10.15.1
Mailspring 1.7.2

Opening a draft requires two clicks. Expected behavior: single click (same as in inbox, etc)

To reproduce: click drafts under all accounts, single click a draft. Nothing happens (it should open). Same result when you click on drafts under a specific account.

**Comment by bengotow** [comment]
Hey! Right now opening a draft opens a new window so it requires a double-click (which is more or less standard for actions on desktop that open new windows). If we change the UI in the future so that drafts open in an in-window editor, we'll definitely change this behavior then.
