### ISSUE TITLE
drafts syncing is broken

### ISSUE THREAD

**Issue by tubeldelta** [Foundry376/Mailspring#1726]
##### Are there any related issues?

Related issue:
https://github.com/Foundry376/Mailspring/issues/1417

However, this wasn't responded to or assigned.

...

##### What operating system are you using?

MacOS and Windows 10
...

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

1.7.2
--

**Bug?**

##### Is this an email sync or connection issue?

Drafts are not synced into the mapped IMAP drafts folder, which can be easily reproduced by checking on another machine or client, where they're not present.

Since the drafts folder can be mapped to the IMAP directory, I assume syncing is supposed to work.

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Only tested with IMAP.

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Occurs with any message.

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by bengotow** [comment]
Hey thanks for filing this! This has actually never been implemented - we did draft sync back when Mailspring was Nylas N1 and ran against their cloud infrastructure, but it took a lot of work to get the synchronization right and surprisingly few users noticed when we launched it. When I launched Mailspring I figured I'd see if people actually asked for it.

Will see if we can ship this in Q1!

**Comment by bengotow** [comment]
Closing in favor of an upvote on #1417

**Comment by tubeldelta** [comment]
Thanks! I've voted on #1417
