### ISSUE TITLE
Mailspring is adding Russian SPAM in Calender 

### ISSUE THREAD

**Issue by MuTaTeD** [Foundry376/Mailspring#1727]
Recurring Russian SPAM meetings are being added to my Google Calender repeatedly and when I check the google access it shows that access was via the Authorised Application (662287800555-0a5h4ii0e9hsbpq0mqtul7fja0jhf9uf.apps.googleusercontent.com) which is the app id of MailSpring every 12 hours or so.

After revoking access to MailSpring for the said account, the meetings requests seems to have stopped

**Comment by MuTaTeD** [comment]
Seems like Mailspring is looking in the SPAM folder of the mailbox and if it finds a meeting invitation, it is automatically adding it to the Google Calender

**Comment by bengotow** [comment]
Hey! Mailspring doesn't automatically add any calendar events (though it probably will some day when the calendar feature is more complete). This happens to me too with just plain old Gmail (though I get "Free iPhone" calendar events and not russian ones). You might need to uncheck the "Auto-add from Email" feature in Gmail's settings here: https://support.google.com/calendar/answer/6084018?co=GENIE.Platform%3DDesktop&hl=en
