### ISSUE TITLE
Adding a folder is a pain in the neck 

### ISSUE THREAD

**Issue by StewAlexanderACC** [Foundry376/Mailspring#1728]
Attempting to create folders on an instance of Novell Groupwise server on a SLES system using the SMTP / IMAP functions of MailSpring (as in clicking the + button next to folders in the MailSpring Folder, adding a name, yadda-yadda)

It takes all sorts of random behavior to create the folder, like creating the folder 3 times, quitting completely out of MailSpring ... all sorts of steps to eventually get the folder made.

Why?

Can this be fixed?

The client is on Windows 10

![image](https://user-images.githubusercontent.com/48565067/69970357-1a0b3180-14ec-11ea-9e93-e697c5b45b32.png)

**Comment by bengotow** [comment]
Hey! This is most likely a sync latency issue specific to Novell Groupwise. My guess is that you only have to do it once and wait about 3 minutes. Mailspring sends the command to create the folder immediately and then looks for it, so I don't think that we can fix how long it takes with this service. Thanks!

**Comment by StewAlexanderACC** [comment]
@bengotow alright, thanks for the info .... I'll sit back and wait
