### ISSUE TITLE
add an option to disable 'is-online'

### ISSUE THREAD

**Issue by working-name** [Foundry376/Mailspring#1731]
##### Are there any related issues?

#1357, [is-online - #50](https://github.com/sindresorhus/is-online/issues/50)

##### What operating system are you using?

macOS 10.14.6

##### What version of Mailspring are you using?

1.7.2

-----

**Feature Request**

Add an option to disable the is-online library. 

_TL;DR_

Mailspring is offline 100% of the time when it cannot get a proper response from captive.apple.com. My pihole blocks that crap, it's useless on my home network, I am my own network manager, my pi resets power to the modem when it detects an issue. ~~Yes, I can spoof a local captive portal and return `<HTML><HEAD><TITLE>Success</TITLE></HEAD><BODY>Success</BODY></HTML>`, but that doesn't save face for Mailspring; on the contrary.~~ - I tried that and it won't work for some reason - didn't investigate.

You're crippling your own app based on a response that is requested every so many seconds without any basis - your app did not have issues connecting and then started checking on it. This is not a smart solution to a problem, **it is the problem**.

**Comment by bengotow** [comment]
I totally agree is-online shouldn't work this way, will investigate if we can change this.

Closing this now because I find the tone irritating.

**Comment by working-name** [comment]
Thanks and sorry, I was already irritated thus my crappy tone. I apologize.
