### ISSUE TITLE
Disable Translation in apps

### ISSUE THREAD

**Issue by HuiiBuh** [Foundry376/Mailspring#1733]
#### Are there any related issues?  
No

##### What operating system are you using?  
Linux Mint 19.2 Cinnamon

##### What version of Mailspring are you using?
1.7.2 installed with snap

**Bug?**

Mailspring offers to translate an email if it is not your language. If you try to disable this by clicking by clicking on the `options` and then  `never translate ___` 
![image](https://user-images.githubusercontent.com/46561026/70607140-33079700-1bfe-11ea-8330-5d0ec8d1f326.png)

As soon as this dialogue appears nothing on the desktop including the dialogue can be clicked. You can accept the dialogue with the keyboard, but the mouse cannot click anything including the Linux mint task bar. 
![image](https://user-images.githubusercontent.com/46561026/70608154-f472dc00-1bff-11ea-964a-fc3ef90b4373.png)

**Comment by bengotow** [comment]
Hey! Marking this as a dup of #1685
