### ISSUE TITLE
Infinite Sign In & Failure to Reauthenticate

### ISSUE THREAD

**Issue by elijahjcobb** [Foundry376/Mailspring#1737]
##### What operating system are you using?
Ubuntu 19.10

##### What version of Mailspring are you using?
1.7.2

**Bug?**
Stuck in an inifite loop of signing in after all accounts were not connected and needed to be reauthenticated. The ReAuthenticate button would not do anything on click and I tried resetting the cache and account setting but nothing worked. Even uninstalled and installed Mailspring again.

##### Is this an email sync or connection issue?

Unable to login at the main screen and so I am unable to view the menu.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Google

##### Is the issue reproducible with a particular attachment, message, signature, etc?

All accounts were invalidated and when I went into relaunch with debug mode then the reauthenticate button worked but opened up the oath website and the log displayed that some properties of my mailsync account might be missing. It said to uninstall and reinstall mailspring, so I did.

**Comment by bengotow** [comment]
Hey @elijahjcobb — it sounds like Mailspring isn't able to securely store the password to your email account. You might need to install a keyring package like `libsecret-1-dev`. Mailspring should warn about this when it starts but I'm not sure exactly what the set up is on Ubuntu 19.

**Comment by mwspicer** [comment]
I'm having a similar issue on Arch Linux. I have libsecret version 0.20.2 installed, but when I open mailspring, the popup that used to appear asking to unlock the keyring never appears, so I'm not able to sync mail. Have also tried uninstalling and reinstalling mailspring and libsecret. Any ideas?

**Comment by elijahjcobb** [comment]
I have resolved this issue. I had changed my password on my computer and for some reason it didn't propagate to my keying. I changed my password to the same thing it was and it worked the second time. It was not a Mailspring issue but an issue of the GUI in Ubuntu user settings. Sorry for the confusion, have a nice week!

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
