### ISSUE TITLE
confirmation popup freezes screen.

### ISSUE THREAD

**Issue by dodekoekjes** [Foundry376/Mailspring#1741]
When I click on never translate Dutch to english button. I get an Pop up asking me if i am sure.
The 2 buttons of this popup are not selectable and when I click on one of them my screen freezes.
I changed tty's to unfreeze the screen and the buttons where selectable and I could proceed as normal.

##### What operating system are you using?
Ubuntu 18.04 bionic beaver with Flat remix shell.

##### What version of Mailspring are you using?
latest version from the ubuntu store. so should be version 1.7.2

**Bug?**
YES

**Comment by bengotow** [comment]
Hey! I believe this is a duplicate of #1685 and should be fixed in 1.7.3. Let me know if you're still running in to it in the latest version!
