### ISSUE TITLE
Vertical scrollbar truncates HTML content

### ISSUE THREAD

**Issue by sbuschjaeger** [Foundry376/Mailspring#1743]
Hi,

I have a problem where HTML message content is truncated due to a vertical scroll bar (see attachment). This happens with detached messages as well as in the one/two column layout.
I think that the message box does not properly take into account the size of the vertical scroll bar for HTML content:

![Screenshot1](https://user-images.githubusercontent.com/32978972/70932846-f80cc580-203a-11ea-8be1-1b6cecb8ac76.png)

This specific screenshot can be reproduced with the following mail (I omitted the header):

> Content-Type: multipart/alternative;
> 	boundary="Apple-Mail=_8B6F0173-584A-4AF8-98F5-46CC3C86DCCA"
> Mime-Version: 1.0 (Mac OS X Mail 12.4 \(3445.104.11\))
> Subject: asdfads
> Message-Id: 
> Date: Wed, 9 Oct 2019 14:58:15 +0200
> To: 
> X-Mailer: Apple Mail (2.3445.104.11)
> 
> 
> --Apple-Mail=_8B6F0173-584A-4AF8-98F5-46CC3C86DCCA
> Content-Transfer-Encoding: quoted-printable
> Content-Type: text/plain;
> 	charset=us-ascii
> 
> --good-names =
> i,j,k,l,d,y,x,f,X,m,n,N,X,Y,T,df,s,X_train,Y_train,X_test,Y_test,X_trial,Y=
> _trial,eq,ch --indent-string "\t" --indent-after-paren 1 --disable=3DC0330=
>  --disable=3DE0401 --min-public-methods=3D0 --generated-members=3Dtorch.*=
> 
> --Apple-Mail=_8B6F0173-584A-4AF8-98F5-46CC3C86DCCA
> Content-Transfer-Encoding: 7bit
> Content-Type: text/html;
> 	charset=us-ascii
> 
> <html><head><meta http-equiv="Content-Type" content="text/html; charset=us-ascii"></head><body style="word-wrap: break-word; -webkit-nbsp-mode: space; line-break: after-white-space;" class=""><div style="color: rgb(212, 212, 212); background-color: rgb(30, 30, 30); font-family: &quot;Source Code Pro&quot;, Menlo, Monaco, &quot;Courier New&quot;, monospace; font-size: 16px; line-height: 24px; white-space: pre;" class=""><span style="color: #ce9178;" class="">--good-names&nbsp;i,j,k,l,d,y,x,f,X,m,n,N,X,Y,T,df,s,X_train,Y_train,X_test,Y_test,X_trial,Y_trial,eq,ch&nbsp;--indent-string&nbsp;"\t"&nbsp;--indent-after-paren&nbsp;1&nbsp;--disable=C0330&nbsp;--disable=E0401&nbsp;--min-public-methods=0&nbsp;--generated-members=torch.*</span></div></body></html>
> --Apple-Mail=_8B6F0173-584A-4AF8-98F5-46CC3C86DCCA--
> 

As you can see this particular mail was send via AppelMail, but I am not sure if this is the issue.
I am running Mailspring 1.7.2 on ArchLinux with Kernel 5.4.2-arch1-1. This issue does not seem to be related to any specific mail provider (happened with an IMAP account). 

##### Are there any related issues?

https://github.com/Foundry376/Mailspring/issues/1496 might be related here.

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this, this has been fixed by 86ed6db (#1762) and will be shipped in 1.7.6.

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
