### ISSUE TITLE
Indicate number of unread message on Label / Mark all as read

### ISSUE THREAD

**Issue by SteinTheRuler** [Foundry376/Mailspring#1745]
I miss seeing how many unread emails each Label has and the ability to mark all as unread

**Comment by bengotow** [comment]
Hey! There's no batch mark-as-unread ability for an entire label but you can turn on this feature to see the unread counts:

![image](https://user-images.githubusercontent.com/1037212/79421223-fec32f00-7f7f-11ea-8b2a-942630d47c5c.png)
