### ISSUE TITLE
Certificate Errors (SMTP) on Linux Mint

### ISSUE THREAD

**Issue by thob** [Foundry376/Mailspring#175]
##### What operating system are you using?
Linux Mint 17.3
##### What version of Mailspring are you using?
1.0.4
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Yes, [Runbox](https://help.runbox.com/smtp/)

##### Is the issue reproducible with a particular attachment, message, signature, etc?
```
----------SMTP----------
220 mailfront10.runbox.com ESMTP Exim 4.82 Ubuntu Mon, 16 Oct 2017 17:58:10 +0200
T (\H!EHLO thux
250-mailfront10.runbox.com Hello example.com [80.*.*.*]
250-SIZE 136314880
250-8BITMIME
250-PIPELINING
250-AUTH PLAIN LOGIN
250-STARTTLS
250 HELP
!STARTTLS
�220 TLS go ahead
EHLO thux
250-mailfront10.runbox.com Hello example.com [80.*.*.*]
250-SIZE 136314880
250-8BITMIME
250-PIPELINING
250-AUTH PLAIN LOGIN
250 HELP

SMTP Last Response Code: 250

SMTP Last Response: mailfront10.runbox.com Hello example.com [80.*.*.*]
SIZE 136314880
8BITMIME
PIPELINING
AUTH PLAIN LOGIN
HELP


mailsmtp Last Error Code: 17

mailsmtp Last Error Location: 10
```

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
yes :-)

Maybe related tp #130

**Comment by bengotow** [comment]
Hey there—this looks like a certificate error. The logs aren't much use because the client hangs up due to the certificate error before even trying to log in. Can you look at https://github.com/Foundry376/Mailspring/issues/144 and see if the file paths that are referenced there are valid for you? I'm not sure where certificates are stored on Linux Mint.

**Comment by thob** [comment]
please see https://github.com/Foundry376/Mailspring/issues/130#issuecomment-337126430
