### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by rhysperry111** [Foundry376/Mailspring#1758]
##### Are there any related issues?

There are a few others mentioning RAM usage but they seem to be fixed.

##### What operating system are you using?

Linux

##### What version of Mailspring are you using?

1.7.2-4522b259

**Bug?**
=====

##### Is this an email sync or connection issue?

Neither

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I don't think so but I use gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Just open up the app and use

##### Explaination
Mailspring seems to be using a lot of RAM (about 420MiB - see screenshot) when no windows are actually open (it is running background sync though). This seems like a very high amount of ram for a background sync process.
![screenshot@2020 01 05-09:29:16](https://user-images.githubusercontent.com/28820694/71777983-9b4c5d00-2f9f-11ea-9bca-375fe7f988b4.png)

**Comment by bengotow** [comment]
Hey! This actually looks about right unfortunately—we may be able to improve this in the future but it'll most likely never be lower than ~300MB because we're dependent on Chromium and it achieves security / sandboxing through process isolation. 

Closing this for now but with a tinge of sadness in my click.

**Comment by joaopauloalbq** [comment]
Hi Mailspring team :)

I also noticed a high RAM usage, I'm using version 1.10.8 consuming 977MB which is a lot for an application that is supposed to be open all the time.

![Screenshot_20230621_201307](https://github.com/Foundry376/Mailspring/assets/9905202/61c33cb3-d807-41fc-a3d3-5964003a0892)

I found "a library for building cross-platform native desktop applications with Node.js and CSS powered by Qt6 which makes it CPU and memory efficient as compared to other chromium based solutions like Electron."

I never used it though 

Take a look => [NodeGui](https://github.com/nodegui/nodegui)
