### ISSUE TITLE
Ability to add on premises installed Exchange account via EWS protocol

### ISSUE THREAD

**Issue by acosonic** [Foundry376/Mailspring#1759]
##### Are there any related issues?
No

...

##### What operating system are you using?
Ubuntu Linux
...

##### What version of Mailspring are you using?

1.7.2
--

**Bug?**

No
##### Is this an email sync or connection issue?

Both
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Locally installed Exchange
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

Yes

##### Does this feature exist in another mail client or tool you use?

Yes, I have shared below a link towards mailcore2 feature request to add
EWS connectivity via Thunderbird plugin's libews C++ library.

...
This is a feature request.

Ability to connect to Exchange (this also goes for Office 365 cloud accounts), via EWS.

Please watch for 
[https://github.com/MailCore/mailcore2/issues/1856](https://github.com/MailCore/mailcore2/issues/1856
)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we're definitely interested in Exchange support in the future but it's fairly different from IMAP + SMTP, so most mail sync software essentially has to be built twice, once to support everyone and then again to support Exchange. I will probably try to do it after the Mailspring calendar launches this year!

Merging this in to #34 so we can track it there!

**Comment by playforvoices1** [comment]
How about to add the EWS functionality by Evolution? Is that possible?
