### ISSUE TITLE
[Feature Request] Increase font size

### ISSUE THREAD

**Issue by PaulDebus** [Foundry376/Mailspring#176]
##### Are there any related issues?
Not that I found

##### What operating system are you using?
Arch Linux, Sway on Wayland, HDPI screen

##### What version of Mailspring are you using?
1.0.4 from the AUR

Hey,

I would like to zoom the entire interface like I can do with the normal Chrome browser using `ctrl +`. I think this should be possible with electron since Chrome can do it, sadly I do not know anything about Electron, so I don't feel I can fix is myself.

Thanks!

**Comment by bengotow** [comment]
Hey! You can do this in a theme, or by opening ~/.config/Mailspring/config.json and adding an entry like `interfaceZoom: 1.5` inside `*.core`. It's not documented because it can lead to strange behaviors, but that's the equivalent to zooming in in Chromium.

**Comment by PaulDebus** [comment]
Ah, ok. I changed it and it works for now. Thank you! This solves my question. 
I really like mailspring, thanks for the great work.

**Comment by WesHildebrandt** [comment]
I set *.core.interfaceZoom to 1.5 and it did not seem to have any impact on the application.  I'm using version 1.0.7 on Ubuntu 17.10 on a HiDPI monitor.  Is that undocumented option still available, or is there a replacement?  For reference, here are the initial lines from my config.json file:
`{
  "*": {
    "env": "production",
    "core": {
      "interfaceZoom": 1.5,
      "themes": [
        "ui-light"
      ],
      "disabledPackages": [
        "message-view-on-github",
`

**Comment by xavier83ar** [comment]
I've tried on ubuntu 16.04, mailspring 1.0.8, and it doesn't work.

**Comment by PaulDebus** [comment]
So this is what I have and it works for me.... though I had to decrease the zoom to <1 after a recent update as it seems Mailspring now detects HiDPI monitors and I like small fonts

```
{
  "*": {
    "env": "production",
    "core": {
      "disabledPackages": [
        "message-view-on-github",
         ........
      ],
      "workspace": {
        "interfaceZoom": 0.8,
```

**Comment by WesHildebrandt** [comment]
Thanks, @PaulDebus!  Moving the parameter down to *.core.workspace worked for me as well.
