### ISSUE TITLE
Crashes when choosing 'Options translate' popup menu

### ISSUE THREAD

**Issue by Trebor87** [Foundry376/Mailspring#1764]
Reading a French mail (I'm running all in English but receive French mails )

I try to choose Options, 'Never translate French'

Mailspring crashes or rather blocks my whole system

I have to use Pkill Mailspring to kill your app, and then the computer is Ok again

Running : Linux version 5.4.6-2-MANJARO

Mailspring version 1.7.2 4522b259
...

--

![Xrash Mailspring](https://user-images.githubusercontent.com/55857416/72146586-139a9000-339d-11ea-9ed6-3e1ac9f46d62.png)

...

**Comment by tgrgin** [comment]
Reported this to support a month+ ago, nothing. Crash reproducible with any language combo I tried.
Ubuntu 18.04.3 running on MacBookPro.

**Comment by Trebor87** [comment]
Hah, didn't see your post though did a quick look around before I posted

Do Mailspring  read/do anything about bug reports ? it's a nice program, but if bugs aren't corrected then that's a shame

**Comment by HoWol76** [comment]
Same issue here, I think.
Specifically, I get the option to translate a German text, and I don't want translations for German. So I click on "Options", then "Never translate German". Then I get a pop-up "Are you sure? Mailspring will no longer offer to translate German. [Yes] [Cancel]" (something along those lines), and it seems as if that pop-up completely disables all event loops. I can't press any of the buttons, but I can also not click on anything else. The mouse moves, but nothing else happens.

**UPDATE:**

With Alt-Tab I was able to tab between windows, was able to tab into the popup and confirm the "Never translate German" option. Still a bug, but this might be a work-around.

Mailspring 1.7.2-4522b259

System: Linux Mint 18 Sarah

**Comment by tvdeyen** [comment]
Same bug for me.

> With Alt-Tab I was able to tab between windows, was able to tab into the popup and confirm the "Never translate German" option. Still a bug, but this might be a work-around.

This worked as a workaround.

**Comment by k-rokicki** [comment]
Same issue, Ubuntu 16.04

**Comment by ricardo-lou** [comment]
Same problem, needed to go to the terminal with alt-tab to kill the process.
Distro: MX-19_x64 patito feo October 21  2019
base: Debian GNU/Linux 10 (buster)

**Comment by salva-ferrer** [comment]
Hello!

I was having the same issue and it went away just hitting the return key.

Issue:

1. opening an email written in a different language than my locale, triggers mailspring to translate it.
2. select the translate box and click 'do not translate emails in (language)'
3. a confirmation popup will show. the popup is not clickable. It captures mouse events and you cannot click anywhere else in the screen. 
4. You can still move around the screen with the keyboard

Reproducible always, I'm using ubuntu 19.10 deb install mailspring 1.7.2 dual monitor setup

Keyboard is still functional and you can click alt-space to open the window menu, try to move the window or raise it to top, no chance, or switch to a terminal with alt-tab to type a kill process as has been mentioned. My guess is that there is a dialog window hidden somewhere.

BUT! enter still works, after some time trying to click an invisible button with my mouse. I just hit enter and the window accepted my input and closed returning control of the mouse.

**Comment by alessandrogiorgi99** [comment]
Same issue here with Fedora 30 and having installed latest version of mailspring as of now via RPM.

I can confirm that it locks mouse events, but you can still manage to select Yes/Cancel by using keys (move with tabs/arrows and hit enter)

**Comment by bengotow** [comment]
Hey folks—this should be addressed by 571074391659e9754334fc504547ae009b824900, will see if I can reproduce this and we'll get the new release out this week.
