### ISSUE TITLE
Dual monitor issue

### ISSUE THREAD

**Issue by mustafakibar** [Foundry376/Mailspring#1769]
Are there any related issues?
No

What operating system are you using?
Ubuntu 19.10 (GNOME 3.34.2)

What version of Mailspring are you using?
1.7.2-4522b259

Explanation
I'm using a dual monitor. Mailspring main window runs on my **primary** screen but when I click 'New Message...' or 'Add Account...' under file menu, unfortunately, it appears on my second screen(every time even if I drag it my primary screen).

**Comment by jannikbuhr** [comment]
The same happens for me on Pop!_OS 19.10, GNOME Shell 3.34.1 with mailspring 1.7.2

**Comment by Josee9988** [comment]
Same issue here, a bit annoying! Using Linux 5.4.0-51-generic in an Ubuntu 20.04 pc, with mailspring version 1.7.8

**Comment by CodeMouse92** [comment]
@Josee9988 If you're still having this issue, please open a new bug report on our Discourse: https://community.getmailspring.com/ Thanks!
