### ISSUE TITLE
How do I turn on Send And Archive by default?

### ISSUE THREAD

**Issue by itstheandre** [Foundry376/Mailspring#1771]
Hello there.
I really dont understand how to turn on Send And Archive By default.
I've seen an issue here, and as soon as I follow the instructions (editing the config.json) it breaks the app.
Help please

**Comment by bengotow** [comment]
Hey @itstheandre! I'll get this added as an option in the next release - in the meantime, you can edit your Mailspring config.json folder (located in the folder shown when you choose Developer > Show Mailsync Logs from the app's menu) like this:

```
{
  "*": {
    "env": "production",
    "core": {
      "themes": [
        "ui-light"
      ],
      "sending": {
        "defaultSendType": "send-and-archive"
      },
```

(If there's not a section called "sending" inside the "core" section, you may need to add it. The `"defaultSendType": "send-and-archive"` line is the key one!)

**Comment by itstheandre** [comment]
Perfect. Working now :)

**Comment by dkotik** [comment]
Was the UI option added? I couldn't find it today - had to config-rig again.

**Comment by CodeMouse92** [comment]
I think this accidentally fell by the wayside. I've added it to the roadmap again.

https://community.getmailspring.com/t/option-for-send-and-archive-by-default/418

---

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)
