### ISSUE TITLE
Mailspring still cannot use the Google account

### ISSUE THREAD

**Issue by mohistmen** [Foundry376/Mailspring#1775]
Well, it is 2020, but Mailspring still can't use the Google account. I don't know what happened in Mailsping programe, but the Mailspring, I can say, is the most gorgeous Email client I've ever used. I found great amount of email clients for a long time, but I can still not forget the experience what Mailspring brought to me. Unfortunately, starting for a time, Mailsping suddenly cannot login to the Google account. At the beginning I even think it's maybe just a little problem, but this issue still not be solved till today. I really hope this issue can be handled.

**Comment by sebastian-brandt** [comment]
I have zero issues using my google account with Mailspring, it actually seems optimized for exactly that.

**Comment by bengotow** [comment]
Hey! It looks like there have been 872,000 Gmail accounts used in Mailspring in the last 24 hours so this is definitely an isolated issue.  :-) It might be worth checking the following:

- If you changed your Gmail password recently or enabled 2FA, etc., try going to Preferences > Accounts and signing in to Gmail again. This will refresh the app's auth tokens so it can start syncing again if they've been revoked for some reason.

- Go into Gmail's settings and make sure that "Enable IMAP Access" is enabled and also make sure that the "All Mail" folder in your Gmail account is exposed via IMAP. Gmail allows you to enable/disable individual folders / labels so they are hidden from your client, and Mailspring doesn't play nicely with the All Mail folder being hidden.

I hope that helps! Mailspring definitely should play nicely with your Gmail account. You may also want to check your Mailsync logs (available from Developer > Show Mailsync Logs in the menu) and see if you're getting a more specific error. It's possible that there's something about a particular message that is throwing off sync, but that's pretty rare these days.

**Comment by nello** [comment]
Same here, with 2 different Google email accounts.

**Comment by AyueArch** [comment]
Hi, I failed to use my Google account with Mailspring, and it report like this: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ETIMEDOUT 172.217.163.42:443
Is there any solution I can apply to this?
![屏幕截图 2023-11-24 090513](https://github.com/Foundry376/Mailspring/assets/61608599/b933bce0-a041-4ce4-9240-6fb0feefd225)
![屏幕截图 2023-11-24 090538](https://github.com/Foundry376/Mailspring/assets/61608599/2ba7ca44-1bf9-4a45-a90e-376bfb16fbda)

**Comment by william20210206** [comment]
> Hi, I failed to use my Google account with Mailspring, and it report like this: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ETIMEDOUT 172.217.163.42:443 Is there any solution I can apply to this? ![屏幕截图 2023-11-24 090513](https://private-user-images.githubusercontent.com/61608599/285329842-b933bce0-a041-4ce4-9240-6fb0feefd225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTgyMjEsIm5iZiI6MTcwNDc5NzkyMSwicGF0aCI6Ii82MTYwODU5OS8yODUzMjk4NDItYjkzM2JjZTAtYTA0MS00Y2U0LTkyNDAtNmZiMGZlZWZkMjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEwNTg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZTdiMzNmZGNmMTgwOWU3ZTIxMjlhODJiYjJjNjQ5NWJlMWU1MGMwOGQ3NzczMTBlYTI0M2M5YjBlOTAxZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.46d9aZBkrFHqF7-uYgEM0wJPJdEdoCuuixDr25Ba1iU) ![屏幕截图 2023-11-24 090538](https://private-user-images.githubusercontent.com/61608599/285329844-2ba7ca44-1bf9-4a45-a90e-376bfb16fbda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTgyMjEsIm5iZiI6MTcwNDc5NzkyMSwicGF0aCI6Ii82MTYwODU5OS8yODUzMjk4NDQtMmJhN2NhNDQtMWJmOS00YTQ1LWE5MGUtMzc2YmZiMTZmYmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEwNTg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZWIxZjA5Yzc3MjE4ZmY0MjMyN2VkZTc4NjEyODQ3MTViY2JkMGE2ODcxYzliZGJkNzcwMDNiMzNkNTYwMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gEFKtAkUlLELGsuu-av4_7cXQdGxMwgnSqvQIAWhhzw)

I faced the same issuse, I still can't find a solution....

**Comment by Monkiesh** [comment]
> Hi, I failed to use my Google account with Mailspring, and it report like this: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ETIMEDOUT 172.217.163.42:443 Is there any solution I can apply to this? ![屏幕截图 2023-11-24 090513](https://private-user-images.githubusercontent.com/61608599/285329842-b933bce0-a041-4ce4-9240-6fb0feefd225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODczNTIsIm5iZiI6MTczMDc4NzA1MiwicGF0aCI6Ii82MTYwODU5OS8yODUzMjk4NDItYjkzM2JjZTAtYTA0MS00Y2U0LTkyNDAtNmZiMGZlZWZkMjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA2MTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZTIzZGU4N2Y1NGE0ZWIzYTE5NThiY2MzNTg2ODM5ZDc3MzY1ZWIwNjY3ZGQwMDJjY2M5N2FmNzdhMGI4MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OAa-elZZa1ttaiGwb8-AHRHbXkldBGyz8-6GPxr3V90) ![屏幕截图 2023-11-24 090538](https://private-user-images.githubusercontent.com/61608599/285329844-2ba7ca44-1bf9-4a45-a90e-376bfb16fbda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODczNTIsIm5iZiI6MTczMDc4NzA1MiwicGF0aCI6Ii82MTYwODU5OS8yODUzMjk4NDQtMmJhN2NhNDQtMWJmOS00YTQ1LWE5MGUtMzc2YmZiMTZmYmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA2MTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNDAxMTc0NmQ1OWYwZjhlMWE2ZWM2MGQwOWZjODNlNjRjMzk5YzE1NDE0N2EyOWRmYWM0ZWU1ZjY1ZWFlZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pN5K7Mi58WxwHRgRQHeWt4cX8iSp6o2hyheOj2EcAS0)

found a solution at: [https://community.getmailspring.com/t/cant-add-gmail-account-this-app-is-blocked/8524](https://community.getmailspring.com/t/cant-add-gmail-account-this-app-is-blocked/8524)

**Comment by vanyolai** [comment]
I have the same problem, but different error message:
This account is invalid, or Mailspring couldn't find your Inbox or All Mail folder.
Might be because of the hungrian language?

![Image](https://github.com/user-attachments/assets/524d24cd-e485-42b0-9e97-08bbd11fefdc)
