### ISSUE TITLE
Key command assigned to "delete-empty-draft" doesn't work.

### ISSUE THREAD

**Issue by gracintosh** [Foundry376/Mailspring#1776]
In a Json file "composer.json" the command "composer:delete-empty-draft" is assigned to the "escape" key. This key mapping doesn't work. The command can be executed if the key mapping is changed.

Keymapping for should be diagnosed and fixed, or command should be reassigned to another logical command.

Steps to recreate:

- Launch Composer window
- Press "escape" key and observe how nothing happens.
- Something is _intended_ to happen, as you can see from the use of "escape" in the "composer.json" file: app > internal packages > composer > keymaps > composer.json.
-Switching this "escape" keymapping to another acceptable keymap does indeed perform a function. It appears "escape" then is not acceptable as a keymapping, either due to incorrect syntax, or another issue.

##### Are there any related issues?

Doesn't look like it, no.

##### What operating system are you using?

macOS 10.15.2, pop!_OS 19.10

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

Version 1.7.2

--

**Bug?**

##### Is this an email sync or connection issue?

Nope.

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Doesn't appear to be, no.
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No.

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
