### ISSUE TITLE
Images from unknown senders are not always blocked when setting is set to block images

### ISSUE THREAD

**Issue by cryoknight** [Foundry376/Mailspring#1779]
I think I posted this before but couldn't find it again.

...
Windows 10

...

##### What version of Mailspring are you using?
1.7.2.something

--

**Bug?**

Sometimes I have opened a spam message, and although I have Mailspring set to block images, images occasionally load regardless, so now the spammer knows my email address is valid.
Please make it ALWAYS block images unless I mark the sender as safe.

##### Is this an email sync or connection issue?
No

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Don't know.

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Not going to attach a spam message.

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—if you get this to happen again, could you please forward the affected message to ben@foundry376.com so I can take a look? This is likely achieved by some super whacky or broken HTML that allows the image src attribute to get through our sanitizer, but offhand I have no idea what input would do it!

**Comment by cryoknight** [comment]
Sure, I just got a spam that I accidentally clicked on, that automatically displayed its images.  I'll forward it to you now.

**Comment by bengotow** [comment]
Hey folks! This has finally been fixed in bc25ebfe9e8407298a689578bb14300ae94bb9fe and 250f88004069fd02e3a1b7399093364562740506. It turns out there was a really tricky scenario where our code behaved differently if called repeatedly on the same message because the Javascript function `Regexp.test` "advances" through the string if given the same string over and over.

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
