### ISSUE TITLE
Can't sync  my email on Ubuntu 18

### ISSUE THREAD

**Issue by AliAbdelaal** [Foundry376/Mailspring#1781]
Encountered an error while syncing my mail

here is the stack trace from the log file 

3572 [2020-01-21 12:03:15.704] [main] [info] Identity created at 1520772725 - using ID Schema 1
3572 [2020-01-21 12:03:15.706] [main] [info] ------------- Starting Sync (aabdelaal@adam.ai) ---------------
3572 [2020-01-21 12:03:15.710] [metadata] [info] Metadata delta stream starting...
3572 [2020-01-21 12:03:16.709] [background] [info] Marking all folders as `busy`
3572 [2020-01-21 12:03:16.716] [background] [info] Syncing folder list...
3572 [2020-01-21 12:03:17.541] [background] [info] Syncing folder list...
3572 [2020-01-21 12:03:17.801] [background] [info] syncFolderChangesViaCondstore - INBOX: modseq 125 to 125, uidnext 63 to 63
3572 [2020-01-21 12:03:17.888] [background] [info] syncFolderChangesViaCondstore - INBOX.Sent: modseq 7 to 7, uidnext 7 to 7
3572 [2020-01-21 12:03:17.977] [background] [info] syncFolderChangesViaCondstore - INBOX.Drafts: modseq 1 to 1, uidnext 1 to 1
3572 [2020-01-21 12:03:18.064] [background] [info] syncFolderChangesViaCondstore - INBOX.Archive: modseq 1 to 1, uidnext 1 to 1
3572 [2020-01-21 12:03:18.151] [background] [info] syncFolderChangesViaCondstore - INBOX.Trash: modseq 1 to 1, uidnext 1 to 1
3572 [2020-01-21 12:03:18.237] [background] [info] syncFolderChangesViaCondstore - INBOX.spam: modseq 1 to 1, uidnext 1 to 1
3572 [2020-01-21 12:03:18.302] [foreground] [info] syncFolderChangesViaCondstore - INBOX: modseq 125 to 125, uidnext 63 to 63
3572 [2020-01-21 12:03:18.303] [foreground] [info] Idling on folder INBOX
3572 [2020-01-21 12:03:18.323] [background] [info] syncFolderChangesViaCondstore - INBOX.Mailspring: modseq 1 to 1, uidnext 1 to 1
3572 [2020-01-21 12:03:18.408] [background] [info] syncFolderChangesViaCondstore - INBOX.Mailspring.Snoozed: modseq 1 to 1, uidnext 1 to 1
3572 [2020-01-21 12:03:18.495] [background] [info] syncFolderChangesViaCondstore - INBOX.Notes: modseq 1 to 1, uidnext 1 to 1
3572 [2020-01-21 12:03:18.496] [background] [info] Sync loop deleting unlinked messages with phase 2.
3572 [2020-01-21 12:03:18.497] [background] [info] Sync loop complete.
3572 [2020-01-21 12:03:30.709] [metadataExpiration] [info] Scanning for expired metadata
3572 [2020-01-21 12:03:30.710] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
3572 [2020-01-21 12:03:34.343] [calContacts] [critical] 
 ***
 *** An exception occurred during program execution: 
 *** (unknown exception details)
 ***

3572 [2020-01-21 12:03:34.350] [calContacts] [critical]  *** Stack trace:
 ***   clone
 ***

3605 [2020-01-21 12:03:34.472] [main] [info] Identity created at 1520772725 - using ID Schema 1
3605 [2020-01-21 12:03:34.474] [main] [info] ------------- Starting Sync (aabdelaal@adam.ai) ---------------
3605 [2020-01-21 12:03:34.477] [] [info] Metadata delta stream starting...
3605 [2020-01-21 12:03:34.481] [] [critical]  *** Stack trace:
 ***   _Rb_tree_insert_and_rebalance(bool, _Rb_tree_node_base*, _Rb_tree_node_base*, _Rb_tree_node_base&)
 ***   _Rb_tree::_M_insert_node(_Rb_tree_node_base*, _Rb_tree_node_base*, _Rb_tree_node*)
 ***   _Rb_tree_iterator _Rb_tree::_M_emplace_hint_unique(_Rb_tree_const_iterator, piecewise_construct_t const&, tuple&&, tuple&&)
 ***   map::operator[](unsigned long&&)
 ***   SetThreadName(char const*)
 ***   clone
 ***

**Comment by iBernd81** [comment]
Yesterday I downloaded and installed Mailspring in current version 1.7.2 on Debian Stretch for my very first time. I was very excited at first but in the end same problem as mentioned here: every few minutes an error is shown that messages could not be synced. I just use a simple IMAP/SMTP configuration.

**Comment by sci3ma** [comment]
Confirmed.
Ubuntu 18.04.3 LTS (5.3.0-26-generic)
Mailspring 1.7.2

With gmail I have no issues but there's a problem with custom imap.
I've added my custom imap, was able to sync all emails but every after 1-2min I get error in left-bottom corner which says "Encountered an error while syncing ***@***.***
When I click Try Again I can receive and send emails for about 1 minute then error pop ups again.

My custom imap works with Thunderbird.

**Comment by rajeshxsankaran** [comment]
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
Mailspring: 1.7.2 

I downloaded and started using Mailspring for the first time yesterday. However, I was unable to 
get Gmail to work either as suite or plain IMAP/SMTP. I knew it was not an issue with IMAP/SMTP 
as I was using the same process on other mail clients (Opera and Thunderbird).

The issue finally happened to be the All Mail visibility - 

https://foundry376.zendesk.com/hc/en-us/articles/115001881912

I fixed it and worked fine for me.

**Comment by sci3ma** [comment]
@rajeshxsankaran thanks for you help but your solution solves issue with Gmail only which is fine in our case. We have issues with custom IMAP.

**Comment by joshnewans** [comment]
I believe this is related to:
#1749, #1660, #1664, #1753, #1693, #1682

**Comment by rajeshxsankaran** [comment]
@sci3ma Thanks for the note. Looks like I did not make it clear. I was unable to still sync Google Mail using IMAP/SMTP, but only the gsuite route worked.

**Comment by bengotow** [comment]
Hey folks! I think there are a bunch of separate issues discussed here (most likely, the issues with specific email providers aren't related to the fact that it's running on Ubuntu), but this stands out as very strange:

```
 *** _Rb_tree_insert_and_rebalance(bool, _Rb_tree_node_base*, _Rb_tree_node_base*, _Rb_tree_node_base&)
*** _Rb_tree::_M_insert_node(_Rb_tree_node_base*, _Rb_tree_node_base*, _Rb_tree_node*)
*** _Rb_tree_iterator _Rb_tree::_M_emplace_hint_unique(_Rb_tree_const_iterator, piecewise_construct_t const&, tuple&&, tuple&&)
*** map::operator[](unsigned long&&)
*** SetThreadName(char const*)
*** clone
```

I will see if I can figure out what's going on here - that call to SetThreadName is just meant to make debugging / logging more informative and I've never seen an exception in there.

**Comment by bengotow** [comment]
The commit above should resolve that particular exception.  Cheers!
