### ISSUE TITLE
Deleted a folder and it deleted two with similar name

### ISSUE THREAD

**Issue by XGhozt** [Foundry376/Mailspring#1785]
I'm on v1.7.2. I have a folder with sub folders, example:

```
Folder
 - SubFolder
```

I accidentality created a folder called:

`folder/subfolder`

When I deleted this folder, it also deleted "SubFolder" inside "Folder". It also ignored letter capitalization.

---

Edit: Also, there was no prompt before deleting the folder to confirm and it should have moved it into the trash instead of just deleting it.

**Comment by bengotow** [comment]
Hey @XGhozt thanks for filing this! What email service (Gmail, Yandex, AOL, etc) does this email account use? Usually the slashes are used as the delimiters in folder names, so a folder called "folder/subfolder" is the underlying name for "subfolder" when it's nested inside "folder".

It sounds like your mail provider may be deleting folders in a case insensitive way but there's a chance Mailspring is also causing this in some way. If you could let me know what type of account it is I can reopen this ticket and try to reproduce!

Also going to add a confirmation prompt now... there's actually no way to move a folder to the trash (the trash is just for messages, not for folders, which is a bit of an old limitation of IMAP), so we definitely need one here.

**Comment by XGhozt** [comment]
Thanks @bengotow . The account I was using was a SmaterMail server via IMAP. Since this service may be hard to come by you can email me directly for a temporary account to test if you want.

I am a little surprised at your mention of IMAP limiting your ability to delete folders. I've never seen a mail client not be able to do this (have sub folders in trash folder). If there's no IMAP command for deleting folders specifically, then we should just be "moving" them into whatever folder is designated as trash. And then if the user "empties" their trash we can delete at that point.

I noticed the same for the Sent folder. It's a bit odd that we can't have sub folders there either.
