### ISSUE TITLE
Ask for user confirmation before installing on windows

### ISSUE THREAD

**Issue by beppe9000** [Foundry376/Mailspring#1787]
The installer feels like a malware dropper... most likely the cause of #1710

**Comment by bengotow** [comment]
Currently this project uses the same installer as VSCode / Atom / Slack etc. on Windows. I think that this might be worth raising on https://github.com/Squirrel/Squirrel.Windows. Thanks!

**Comment by beppe9000** [comment]
Despite that, what about just adding a zip package with the binary to the releases? I would also like to bump issue #922 since it is related and I believe would be a great alternative to a 'classic' install.
