### ISSUE TITLE
The user bio is wrong fetched from email ID 

### ISSUE THREAD

**Issue by NehaSukhlecha** [Foundry376/Mailspring#1791]
if we open any email details the data coming is wrong and for some profile old, 

Ex : like redirecting to wrong linked in profile @team 

![image](https://user-images.githubusercontent.com/22446023/73841666-0f00b480-4841-11ea-93b3-d742d624fc59.png)

**Comment by bengotow** [comment]
Hey @NehaSukhlecha! Thanks for filing this—we cache profile data after we discover it for about a year, but I'll see if we can keep this up to date better!
