### ISSUE TITLE
Extra space in email hyperlinks

### ISSUE THREAD

**Issue by saltymedic** [Foundry376/Mailspring#1796]
I receive an email from our system where someone submits their email address. I use that information in a work flow where I copy the the email address in the body of the email by right clicking on the address and selecting "Copy email address". When I go to paste this, it adds an extra space in front of the email address. When I view the email in Gmail and right click on the email address to copy the address, it does not have that extra space in front of the email address when I got to paste it.

Looking at the email that I recieve, I can see that there is an extra space that gets added. There is an underlined space that shows itself for the hyperlink.

I would like for there not to be an extra space added in front of the email address

I am using Linux version 1.7.2-4522b259

**Comment by bengotow** [comment]
Hey @saltymedic — thanks for reporting this! I'll take a look and see what's going on, it seems like it should be straightforward for us to fix. 🙏

**Comment by bengotow** [comment]
Hey @saltymedic, I sent myself an email with a handful of email addresses (some in hyperlinks and some just plain text) but I haven't been able to get this to happen. Could you share an example of the emails you receive if they're not too sensitive or if you can hack it up a bit? If you could forward one to me at ben@foundry376.com I can look at your specific case!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
