### ISSUE TITLE
[Feature Request] Custom "Global" Folders

### ISSUE THREAD

**Issue by SonOfDiablo** [Foundry376/Mailspring#1797]
This Feature Request is for the option to make *Custom Global Folders* (for a lack of a better name).

Essentially this would allow the user to create new folders under the "All Accounts" group in Mailspring. These folders would have some rule attached to them and mails (from all accounts or alternatively only selected accounts) that fall into these rules will be shown in these folders.

Example:
I want to see all mails from Amazon, so I make a folder with the rule "From Contains Amazon Move *Global Amazon Folder*" (based on the Mail Rules feature of Mailspring). 

And related, some default "Smart" folders would be great too.
Like Personal, Notifications, Newsletters (based on some rule set)

##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

1.7.2

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Spark (mail client for Android and iOS) has a [Smart Inbox feature](https://sparkmailapp.com/features/smart_inbox)

I don't know of other clients doing the same thing.

**Comment by bengotow** [comment]
Hey! Thanks for filing this, I think this would be a great feature, going to merge into #514 and we can track development there.
