### ISSUE TITLE
Add Hacktoberfest tag to issue all Help Wanted issues

### ISSUE THREAD

**Issue by nickolasclarke** [Foundry376/Mailspring#180]
Title says it all, lets get some cred for [Hacktoberfest ](https://hacktoberfest.digitalocean.com/) and possibly get some extra commits that otherwise wouldnt happen.

**Comment by bengotow** [comment]
You got it! https://github.com/Foundry376/Mailspring/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest
