### ISSUE TITLE
Bug: user-open error when open links inside e-mails on Fedora Linux

### ISSUE THREAD

**Issue by LucasMazei** [Foundry376/Mailspring#1806]
**Description**
Every time I click to open a link inside an e-mail I get the error (in my terminal):

> user-open error: cannot find snap for connection: cannot find a snap for pid 3735

**To Reproduce**
1. Start mailspring
2. Click on any link
3. See error

**Setup: (please complete the following information):**
 - OS: Fedora Linux
 - OS Version 31
 - Mailspring Version: ex: 1.7.2

**Comment by bengotow** [comment]
Hey! This seems like an issue with the installation of Snapcraft on your machine - you might want to try posting about this on https://forum.snapcraft.io/ and see if folks there can help out!
