### ISSUE TITLE
Bug: Mailspring should remove spaces from your hostname when connecting to IMAP/SMTP

### ISSUE THREAD

**Issue by BlueManCZ** [Foundry376/Mailspring#1808]
**Bug description:**
I'm unable to connect to Gmail account, when my computer hostname contains whitespace character. Same behavior when using [IMAP/SMTP](https://support.google.com/mail/answer/7126229) or Google OAuth.

**Log:**

> ----------SMTP----------
> 220 smtp.gmail.com ESMTP r5sm17263171wrt.43 - gsmtp
> EHLO Z170-D3H Gentoo
> 501-5.5.4 HELO/EHLO **argument "Z170-D3H Gentoo" invalid**, closing connection.
> 501 5.5.4  https://support.google.com/mail/?p=helo r5sm17263171wrt.43 - gsmtp
> HELO Z170-D3H Gentoo
> QUIT

**Workaround:**
Remove whitespaces from hostname.

**References:**
https://github.com/Foundry376/Mailspring/issues/368#issuecomment-590246126

**Setup:**
 - OS: **Gentoo Linux**
 - OS Version: Gentoo Base System **release 2.6**
 - Kernel: **4.19.44-gentoo**
 - Mailspring Version: **1.7.2**

![Snímek z 2020-02-24 10-53-47](https://user-images.githubusercontent.com/17854950/75146332-296cd600-56fb-11ea-9a9f-312cd82d48b2.png)

**Comment by bengotow** [comment]
Hey! It looks like we need to make Mailspring sanitize your hostname to fix this. I'm actually really surprised we haven't seen this, but I think most OS's don't let you insert spaces.

**Comment by BlueManCZ** [comment]
I was actually quite surprised, why does Mailspring need hostname to connect somewhere? Is there any specific purpose?

**Comment by bengotow** [comment]
Hey! Sorry for the delay. Yeah-it's a bit weird. SMTP sessions begin with a "HELO" message, and the convention is for the client to identify itself eg: "HELO bens-macbook-pro.local". I'm actually not quite sure why that's necessary (and the spec was written back in the 1980s so it's possible it never turned out to be useful at all), but we should be able to workaround this. I'll see what Thunderbird and other clients are doing!

**Comment by bengotow** [comment]
Next version of Mailspring will replace the spaces with `-`. If it's unable to resolve a hostname for your machine, it'll fall back to using your IP address (which is Thunderbird's default behavior actually!)

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
