### ISSUE TITLE
Mailspring auto-labeling new emails on existing threads

### ISSUE THREAD

**Issue by valdotdev** [Foundry376/Mailspring#181]
##### What operating system are you using?
macOS 10.13

##### What version of Mailspring are you using?
1.0.5

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail. Haven't noticed with other providers yet.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I don't think so.

--
I'm not sure if I'm missing something or this is an intended behavior or whatever, but I'll try to explain as best as I can and detailed as possible. I guess in chronological events.

1. My brother sent an email in which I was BCC'd.
2. I then labeled that email "Personal" and archived it via Gmail. (I usually use auto-filters in Gmail for certain addresses and when It labels an email I set "Skip the Inbox", aka Archive). In this case, I just manually labelled it because the address he used was a different one from what I have in my filters.
3. After a few weeks, my bro replied to that same email he sent, which he also changed the subject. At this point, I was already using Mailspring.

Expected Result in Mailspring:
-In Inbox, the new email should not have any labels since I did not set anything in my Gmail filters to slap a label on this particular address.

Actual result in Mailspring:
-The new email I received was labeled "Personal", even though I haven't done so yet. In Gmail it's not labeled so it's fine and the only label was the default "Inbox".

So I'm thinking, Mailspring is basing it's "labeling" when I first labelled the original email as "Personal". Since the email reply was in the same email thread, it used it as a reference and just slapped a label on there.

In Mailspring, thinking that since it was already labeled as such, I just archived it. The problem now, after checking in Gmail, there's no label at all and I need to look for it in "All Mail" just to manually label the thing.

Bottomline:
I guess it's ok that Mailspring labels emails on it's own especially if the original email already has a label on it, but it doesn't reflect on Gmail. The workaround I guess it to just add the address to my filters so that it's labeled AND archived. But there are emails that I prefer to label manually.

**Comment by bengotow** [comment]
Hey thanks for reporting this. Mailspring is showing the labels on that message because the message is a new email in an existing thread, and you previously labeled the thread. AFAIK, labels are a thread concept, not a per-message concept. It's definitely interesting Inbox isn't showing the labels on there - I'll see if they've changed anything. Mailspring's display should be consistent with Gmail.
