### ISSUE TITLE
Bug:  No finalized IMAP configuration

### ISSUE THREAD

**Issue by b3lz3bu** [Foundry376/Mailspring#1826]
At the end of IMAP/SMTP configuration Mailspring not finalize not save the conf settings

**To Reproduce**
1. Go to 'Option/accont/ad account'
2. Click on 'plus key to add account'
3. Scroll down to 'ins all option, server and passkey for your account'
4. You receive the message of configuration successful, but the account is not saved to the list

This also in the first account configuration at ehe end of this the program stop on white rectangle 

**Setup: (please complete the following information):**
 - OS: Windows 10 1909
 - Mailspring Version: 1.7.4

**Comment by ndem0** [comment]
Same for me.

OS: CentOS Linux release 7.7.1908
Mailspring version: 1.7.4

**Comment by karincalvinho** [comment]
Same for me, both using the IMAP configuration and the "add Exchange account" tool.
OS: Windows
Mailspring version: 1.7.4

All other accounts still work as normal.

**Comment by ssuter1** [comment]
Same on OSX 10.15.3 Catalina
Mailspring version: 1.7.4

Ended up downgrading to 1.7.1, adding all accounts just fine, and then performing the upgrade.  All is well after that.

**Comment by karincalvinho** [comment]
@ssuter1 Thanks for the workaround! Downgrading solved the problem for me.

**Comment by b3lz3bu** [comment]
yes, with downgrade the problem is solved, now i try to update to 1.7.4 version

**Comment by paulich69** [comment]
same Problem here... pop os 19.10

**Comment by MalteKiefer** [comment]
see #1817

**Comment by zeph** [comment]
downgraded to 1.7.2 and it works

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this and submitting a fix - I'm sorry it's taken me so long to ship a build with the changes. I honestly can't believe it's April already. I'm doing QA tonight and I'll ship the 1.7.5 release with the patch ASAP tomorrow!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
