### ISSUE TITLE
Mailspring becomes slow in 1.0.5

### ISSUE THREAD

**Issue by JunnanZ** [Foundry376/Mailspring#183]
##### Are there any related issues?

...

##### What operating system are you using?
Arch

##### What version of Mailspring are you using?
1.0.5

--

**Bug?**
Everything becomes much slower. There is a significant lag after every move, clicking an email, scrolling, clicking a tab in settings, etc. The lag is not very big, like 500ms, but the overall performance is not smooth as the previous versions.

##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by JunnanZ** [comment]
Sorry, rebooting solves the issue.

**Comment by fakeid30** [comment]
@JunnanZ close the issue then
