### ISSUE TITLE
Can't add Yandex account

### ISSUE THREAD

**Issue by thedrint** [Foundry376/Mailspring#1831]
##### What is the behavior you're seeing?
Try to add yandex mail account - after successful adding no account in list and in main window.

##### What email provider (Gmail, Exchange, etc.) are you trying to use?
Yandex.ru

##### What operating system are you using?
Windows 10 1903

##### What version of Mailspring are you using?
Latest

(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Reproducible with password and app-passwords.

**Comment by sasasagagaga** [comment]
I have the same issue with mail.ru account

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this - I think it's related to a bug in the current release that causes issues with IMAP account auth. I'm really sorry it's taken so long for the fix in #1876 to get shipped. I will push out a 1.7.5 release tomorrow.

I think we can close it as a dup of #1848 but I'll keep it open until 1.7.5 ships for here for visibility. Thanks everyone for the comments and help triaging!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
