### ISSUE TITLE
Feature Request: Flatpack Support

### ISSUE THREAD

**Issue by GianlucaRea** [Foundry376/Mailspring#1832]
A Flatpack support for this fantastic application

As an user of fedora linux the problem is that snap aren't really good on this system. 
I have to download manually the rpm package every new update.
This feature will be really useful for users like me. 

Thanks,
and compliments for the good work already done!

**Comment by ethragur** [comment]
See issue #345

**Comment by GianlucaRea** [comment]
I will close it !!! :smile:
