### ISSUE TITLE
Bug: adding yahoo account will prompt a empty window

### ISSUE THREAD

**Issue by douidou75** [Foundry376/Mailspring#1834]
Everytime I try to add a Yahoo account, it asks my email, my password (so I used yahoo password generator in the security section of course, not my yahoo acount password).
Then it says "Your yahoo account is successfully connected". And then I have a white empty window, and nothing happens. 
![2020-03-01_22h56_34](https://user-images.githubusercontent.com/61667709/75634666-fdc48100-5c0f-11ea-8cdf-9787db63e7a1.png)

**Comment by danHavercroft** [comment]
I've had the same issue with adding Hotmail accounts. I've just installed the latest version via the snap store for Manjaro.

**Comment by MalteKiefer** [comment]
see #1817

**Comment by Darkducat** [comment]
Idem Bug fix by passing with an older version 7.1.2

**Comment by greggslist** [comment]
I've also reported with more details/video of the same issue - see #1847

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this and submitting a fix - I'm sorry it's taken me so long to ship a build with the changes. I honestly can't believe it's April already. I'm doing QA tonight and I'll ship the 1.7.5 release with the patch ASAP tomorrow!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
