### ISSUE TITLE
Bug: Cannot connect Squirrelmail account

### ISSUE THREAD

**Issue by GuitGuil** [Foundry376/Mailspring#1835]
Installed Mailspring under freshly installed Ubuntu 19.10, I cannot connect an account from Squirrelmail. Connectc to this account used to work under previous ubuntu install. 
After Imap and Smtp information recognized (with authorisation of unsecured connections), a message saying 'we're adding your account to mailspring' shows up, but the account is never actually added.

I have 2 other gmail account added that seem to work fine. 

**Setup: (please complete the following information):**
- OS : Ubuntu 19.10
- Mailspring Version 1.7.4-d54ff730

Thanks for helping me with this issue,

**Comment by lmince** [comment]
Similar, most likely the same issue. Last week my email accounts except from gmail stopped working. Tried reinstalling mailspring, but that didn't help -- still can add my gmail account, but any other account is not seen (the whole process adding other accounts seems to succeed, but the accounts do not appear in the email client). Note the initial issue appeared without any changes in the system.

OS: Linux Minut 19.1 Cinnamon
Mailspring version 1.7.4-d54ff730

**Comment by superh1k** [comment]
Same here. Tried to add webmail accounts. It says that is successful but accounts are not added.  

OS: Windows 10 1809
Mailspring version 1.7.4-d54ff730

**Comment by bengotow** [comment]
Hey folks—thanks for filing this, this is a pretty serious bug. It was reported in a handful of other issues and we shipped a fix for it yesterday in version 1.7.5.

You can download the update from GitHub releases or from https://getmailspring.com/download, and the app should also auto-update if you have been using it. Sorry for the delay getting a fix out for this one, I appreciate everyone's help debugging and triaging the problem!
