### ISSUE TITLE
Searching in labelled gmail folders never returns

### ISSUE THREAD

**Issue by gnunn1** [Foundry376/Mailspring#184]
##### Are there any related issues?
No

##### What operating system are you using?

Arch Linux

##### What version of Mailspring are you using?

1.05
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

GMail (corporate account)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

The issue happens only when searching labelled folders. I subscribe to several e-mail lists at work and just leave all the e-mails there as the searching in gmail is much better then the list software we use. The issue doesn't seem to be related to size, even searching labelled folders with relatively few emails never returns.

All that happens is I see the dot pattern moving but no results.

**Comment by bengotow** [comment]
Hey! Can you give an example of a search query? I'm not sure what you mean by labelled folders?

**Comment by agesome** [comment]
Hi. I get this also with an Office365 and an IMAP account. I can see relevant threads in the quick search results but after I press enter to actually search - infinite progress indicator. I can also see threads from folders other than selected, even though it's indicated "Search <folder name>". Here is a gif for you.
Can I provide some debug info here?

![search](https://user-images.githubusercontent.com/63224/31712058-a9fafb10-b402-11e7-99a2-83e070a9e32e.gif)

**Comment by gnunn1** [comment]
I subscribe to several mailing lists and I use gmail's filter capabilities to automatically label the e-mails I receive. These labels are treated as folders by gmail and the labelling feature in mailspring does the exact same thing. When I select one of these folders and try to search in it using the top search bar, as per @agesome picture above, the search never returns. The animation of the four circles in a row just continues on forever.

**Comment by we3geeks** [comment]
I see this behavior, as well, if I use any of the Gmail-style search strings (e.g., "is:unread" or "label:Soccer"). I get the animated dots forever and it never seems to return any search results.

I'm on macOS, running v1.0.6, and have Mailspring configured to use a single Gmail account.

**Comment by nul0m** [comment]
+1, ubuntu 16.04, mailspring 1.0.6

**Comment by Kredns** [comment]
I have this exact same issue on Fedora using mailspring 1.0.7.

**Comment by bengotow** [comment]
This should be fixed in a416c4b0fab24274d1b2a45f82487f0a4670c4a3 - basically, if you wanted to search using terms and also using a label / specifier (eg: "bengotow is:unread"), you had to add an AND ("bengotow AND is:unread"). The AND Is redundant and silly but was required by the search parser.

The issue with the loading spinner just sticking forever is also fixed!

**Comment by bengotow** [comment]
Hey folks! Thanks for the updates—we fixed another bug in `1.0.10` that caused Mailspring's search to fail in the context of folders (#394) - this should be good to go now. Let me know if you still encounter problems after downloading the update.
