### ISSUE TITLE
Bug: switching signature puts signature and text inside quoted message after 1.7.4 update

### ISSUE THREAD

**Issue by didrip** [Foundry376/Mailspring#1842]
**Describe the bug**
After update to 1.7.4 when replying to an email and switching the alias used to send the email (From drop-down menu),
The signature and any previously typed text (above signature) is hidden, and is is not possible to type new text.
The signature and text are actually present but embedded inside the quoted email.

**To Reproduce**
1. Click "Reply" icon
2. Type some text above signature
3. Click on "From" email
4. Select Email Alias

**Expected behavior**
Previously typed text should stay in place, on top, above signature.
Signature should be replace.

**Setup: (please complete the following information):**
 - OS Windows x64 1909 (as a matter of fact same bug with 1809 version)
 - Mailspring Version: 1.7.4-d54ff730

**Additional context** 
Bug appeared after  update to 1.7.4.
Possibly related to issue #1825

**Comment by didrip** [comment]
In the meantime I switched back to 1.7.2 and confirm it does not have this bug.

**Comment by didrip** [comment]
Still happening on 1.5 a976d71

**Comment by bengotow** [comment]
Hey @didrip! Thanks for filing this—I was able to reproduce the problem and it should be fixed in the next release.  This one is super frustrating when it happens.

**Comment by didrip** [comment]
@bengotow Thank you very much for your work on Mailspring it is astonishing.

ps : wish I could help but I got lost when I dived in the code (despite the comments), there is a lot going there !

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
