### ISSUE TITLE
Arch User Repository Update 1.7.4

### ISSUE THREAD

**Issue by jwalteros** [Foundry376/Mailspring#1843]
Can anyone update the AUR version of mailspring to the latest version 1.7.4?

**Comment by PCPNIELSEN** [comment]
Think this request is better suited for the AUR.
And second, the 1.7.4 have a bug were you cannot add IMAP accounts. So 1.7.2 is the best option right now IMO.

**Comment by CodeMouse92** [comment]
https://community.getmailspring.com/t/for-those-installing-on-an-arch-based-distribution/125
