### ISSUE TITLE
Bug: Mailspring not Adding Outlook Account

### ISSUE THREAD

**Issue by rainer2208** [Foundry376/Mailspring#1844]
**Describe the bug**

When I try to add an Outlook account, following the steps and entering the information on the Add-Account-Window, I get a confirmation message "Account Successfully Added", but the account doesn't appear in the list of mail accounts. 

This happens both with Hotmail and and Office 365 accounts. 

Restarting the computer does not help. Neither does repeating the pŕocedure. 

**To Reproduce**
1. Go to 'File > Add Account ... '
2. Click on 'Outlook - Hotmail' or 'Office 365'
3. Fill in account information. 
4. Click on 'Connect Account'.
4. Confirmation message (Account Successfully Added) appears, but account is not not listed.

**Expected behavior**
The account should be added after getting the confirmation 

**Setup: (please complete the following information):**
 - OS: Ubuntu Budgie
 - OS Version: 19.10
 - Mailspring Version: 1.7.4 - installed via software application

**Comment by DerGeist** [comment]
Same thing happens, if I try to log in to outlook.com or imap / smtp.

- OS: Manjaro
 - OS Version: 19
 - Mailspring Version: 1.7.4 - installed via snap

**Comment by greggslist** [comment]
I can't get an @outlook.com account to add either.

I've been able to add a Gmail account without any issues, but I get a white screen when adding an email account that's not Gmail (email account hosted through a cPanel server). I've taken video I provided in my bug issue #1847

**Comment by napsterv** [comment]
Same issue for me.

**Comment by ViMotte** [comment]
Same issue here. It seems recent, the problem did not occur with a previous version. 
Behaviour reproduced with both deb and snap installation process.
The only working provider is Gmail, others don't show up, even if it's the first account to be set up in the app (leads to white screen).

**Comment by nofate301** [comment]
Same happens when adding Exchange account.  Stuck at a white screen after completing the wizard.  If I add a Gmail account that's fine, but if I try to add exchange, it says it was successful, but nothing shows up.  if I clear out the other accounts and just add the exchange account I end up at the white screen after the wizard.

This is on windows lastest stable version at the time of this comment.

**Comment by wiah** [comment]
I am experiencing the same thing on Ubuntu Bionic Beaver 18.04 (LTS).
Initially, I had changed my outlook email password and wanted to update it correspondingly in Mailspring, but I was unable to do that. I tried removing my outlook account and adding it again, but this resulted in the beaviour explained above.
I also added a Gmail account to test the difference, and this did not result in any issues.

**Comment by louis-pham** [comment]
Having this same issue on Windows 10.

**Comment by apemother** [comment]
I can't add an outlook account either with Ubuntu 18.04 LTS, it just states it is successful in adding my account but it does not appear as added anywhere.

**Comment by Mstkj** [comment]
Exactly the same issue, but only with Outlook/Office365 accounts.

OS: Ubuntu
OS Version: 19.10
Mailspring Version: 1.7.4-d54ff730

**Comment by ZhirenXu** [comment]
I tried to add office365 and add outlook account using manual setup, get exact behavior.
OS: Ubuntu 19.10 x86_64
MailSpring version: 1.7.4-d54ff730

**Comment by pythonInRelay** [comment]
Temp solution. Install an older version located [here](https://github.com/Foundry376/Mailspring/releases/tag/1.7.2).

**Comment by nofate301** [comment]
should we try and update after adding our account this way?  It worked for me and I was able to use my company's OWA.

**Comment by bergmul** [comment]
Same problem for university IMAP account on Pop!_OS 19.10 (Ubuntu 19.10 derivative)

**Comment by napsterv** [comment]
I downgraded to 1.7.2, Outlook works fine now.

**Comment by SherifEssamGomaa** [comment]
> I downgraded to 1.7.2, Outlook works fine now.

How can I downgrade

**Comment by mikehalim** [comment]
Same issue!! very disappointed I use it currently for just my gmail and I absolutely love it. I hope it gets fixed shortly.

**Comment by ZayRTun** [comment]
I am having the same issue so I downgraded to 1.7.2 as others above and now it works fine.

**Comment by rainer2208** [comment]
> > I downgraded to 1.7.2, Outlook works fine now.
> 
> How can I downgrade

Here is a link ..... 

https://github.com/Foundry376/Mailspring/releases/tag/1.7.2

**Comment by mikehalim** [comment]
> I am having the same issue on Ubuntu 18.04, so I downgraded to 1.7.2 as others above and now it works fine.

Perfect!! Worked for me. Thank you

**Comment by rainer2208** [comment]
> > I downgraded to 1.7.2, Outlook works fine now.
> 
> How can I downgrade

Here is a link ..... 

https://github.com/Foundry376/Mailspring/releases/tag/1.7.2

**Comment by bergmul** [comment]
@rainer2208, you should reopen the issue. We are all experiencing a bug in the current version of the program. Even though downgrading solves the problem for us, the bug still persists in the current version of Mailspring and should kept open until that bug is fixed.

**Comment by mikehalim** [comment]
> @rainer2208, you should reopen the issue. We are all experiencing a bug in the current version of the program. Even though downgrading solves the problem for us, the bug still persists in the current version of Mailspring and should kept open until that bug is fixed.

I agree with this... I’d like to use the latest release as well. I hope this can be fixed soon.

**Comment by rainer2208** [comment]
That was

**Comment by CarlosRebolledoA** [comment]
Mismo error y sorprendido por falta de respuesta de @bengotow 
SO: Windows 10 - 64
Versión de MailSpring: 1.7.4-d54ff730

**Comment by frigaut** [comment]
+1 here.
Perhaps @gengotow is busy with a corona emergency.

**Comment by JingyuHe** [comment]
same, Mailspring 1.7.4, Mac OS 10.15.3 (19D76)

**Comment by CarlosRebolledoA** [comment]
> +1 aquí.
> Quizás @bengotow está ocupado con una emergencia de la corona.

Ojalá que no tenga problemas de salud ni menos con Convid19

**Comment by SamuilDichev** [comment]
Can confirm, Mailspring 1.7.4, Windows 10 Education v1909

**Comment by ZayRTun** [comment]
Still having the same issue even after reinstalling it. Just can't seem to install Hotmail. I just hope that this gets fixed soon.

**Comment by napsterv** [comment]
It appears that things are gonna stay this way until this Corona thing is over. 

Use 1.7.2 bois.

**Comment by jnorment** [comment]
Same issue here.

Using 1.7.4-d54ff730 on Elementary OS 5.1.2 [Ubuntu 18.04.3 LTS]

Both accounts do not have two-factor authentication enabled and receive the "successful" message but nothing happens.

**Comment by HuiiBuh** [comment]
Same here with Mailspring 1.7.4 and Linux Mint 19.3

**Comment by estebakos** [comment]
Exactly the same. Mailspring 1.7.4 and Linux Mint 19.3

**Comment by estebakos** [comment]
It works for me using this specific version and an outlook account.

![Captura de pantalla de 2020-04-03 15-13-55](https://user-images.githubusercontent.com/6438548/78401386-416b2b80-75be-11ea-9013-6092b77b2e3e.png)

**Comment by JingyuHe** [comment]
Solution: Install 1.7.0 and login your outlook. Then upgrade it to the latest version

**Comment by scookdev** [comment]
Same issue for me with both Outlook and Apple accounts. Downgraded to 1.7.2 and works fine.

**Comment by Orion83** [comment]
If anyone got links for the 1.7.5 edge version (deb, rpm, exe, ...)
Would help or just put it in repos...

**Comment by ZayRTun** [comment]
Just `sudo snap install mailspring --edge`

**Comment by CarlosRebolledo** [comment]
Hi Ben !!! ???? What happens???!!! All good?? I hope you are well, but it is worrying not to see your response or activity around here. Excuse me, but I'm a paying customer and I don't think I deserve this silence.

**Comment by r12f** [comment]
I am using the windows version and getting the same issue here.

**Comment by rayonnunes** [comment]
downloading from the edge channel (version 1.7.5) via snap store fixed this bug for me on Fedora 31

**Comment by CarlosRebolledo** [comment]
> La descarga desde el canal perimetral (versión 1.7.5) a través de la tienda de instantáneas me arregló este error en Fedora 31

Where? Please link

**Comment by rayonnunes** [comment]
> > La descarga desde el canal perimetral (versión 1.7.5) a través de la tienda de instantáneas me arregló este error en Fedora 31
> 
> Where? Please link

@CarlosRebolledo 
here: https://snapcraft.io/mailspring

or just install via terminal: `sudo snap install mailspring --edge`

**Comment by CarlosRebolledo** [comment]
Ok, ,muchas gracias

*Carlos Rebolledo Aguirre*

*Abogado*

Inversiones en Línea Limitada

F: +56712212721 | M: +56983419924 | E: carebolledo@inverline.cl A: 1 Norte 880, oficinas 7 y 8, Talca

La información contenida en este correo electrónico es de propiedad del abogado Carlos Rebolledo Aguirre, corresponde a una comunicación privada, acotada y está destinada al uso exclusivo de la persona o las personas a quien va dirigida y puede contener información privilegiada, confidencial o de divulgación restringida según la ley chilena. Si usted no es destinatario de éste correo, le informo que cualquier divulgación, distribución o copia de esta comunicación constituye un delito conforme a la ley chilena. Y, si esta comunicación la ha recibido por error, le solicito tener a bien destruirla y avisarme de manera inmediata. Muchas gracias.

**Comment by CarlosRebolledo** [comment]
@bengotow Glad to see you're doing repairs. Just remember to solve the problem of adding Outlook accounts. It still persists under the newly released version 1.75

**Comment by bengotow** [comment]
Hey folks—thanks for filing this, this is a pretty serious bug. It was reported in a handful of other issues and we shipped a fix for it yesterday in version 1.7.5. 

You can download the update from GitHub releases or from https://getmailspring.com/download, and the app should also auto-update if you have been using it. Sorry for the delay getting a fix out for this one, I appreciate everyone's help debugging and triaging the problem!

Small note about Outlook: Mailspring supports Office 365 accounts (https://outlook.office365.com) because that service supports IMAP. However, you may need to create an "app password" just for Mailspring in order to add your account. It's unclear if this is always necessary, or something that individual organizations configure: https://support.office.com/en-us/article/create-an-app-password-for-office-365-3e7c860f-bda4-4441-a618-b53953ee1183. 

Mailspring unfortunately does NOT support Exchange, which is the type of email system you get with "Office 365 Business". I'm working to add support in the future but it's an entirely separate email protocol that doesn't have anything in commong with IMAP/SMTP. Thanks!

**Comment by BrunoSpy** [comment]
@bengotow Is there a issue to follow the implementation of Exchange support ? My organization recently switched from a plain IMAP server to Office365 with only Exchange and 2FA capability and I can't use Mailspring anymore (too many emails for DAVMail).

**Comment by humanolaranja** [comment]
> @bengotow Is there a issue to follow the implementation of Exchange support ? My organization recently switched from a plain IMAP server to Office365 with only Exchange and 2FA capability and I can't use Mailspring anymore (too many emails for DAVMail).

Same problem here (organization account with 2FA)

**Comment by CodeMouse92** [comment]
@humanolaranja and/or @BrunoSpy: We are in the process of migrating our community and bug reporting to https://community.mailspring.com

To ensure this problem receives proper attention, especially as the current manifestation of this bug may have different causes, please open a new bug report there following the template. I encourage you to include a link to this issue under the Additional Context field there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
