### ISSUE TITLE
Bug: Couldn't add imap account

### ISSUE THREAD

**Issue by WHMHammer** [Foundry376/Mailspring#1848]
**Describe the bug**
After "successfully" adding an imap account, the account doesn't show the account anywhere.

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Accounts'
3. Click on the '+' sign on the bottom of the account list window
4. Click on 'IMAP/SMTP'
5. Type in the correct Name, Email, and Password
6. Click on 'Continue'
7. Fill in each entry correctly
8. Click on 'Connect Account'
9. A window pops up, saying something similar to "successfully connected to imap account". The window closes itself in around 1sec
10. My account doesn't show in the account list

**Comment by WHMHammer** [comment]
Sorry, I forgot to mention that I'm running version 1.7.4 on 64-bit Windows 10 Pro 1909

**Comment by boraikizoglu** [comment]
I have exactly the same problem.

OS: Mac OS 10.15.3
Version: 1.7.4

**Comment by linked2ding** [comment]
I got the same issue; and the same account set up in another computer in Mailspring could not update anymore.

**Comment by Fitz13009** [comment]
The same problem also showed up in my Ubuntu 18.04 Computer. I could not find my university email to mailspring after a successful adding.

**Comment by ChefReg** [comment]
Same problem, 2015 iMac running Elementary Hera 5.1

**Comment by genesteelmen** [comment]
Same Problem Windows 10

**Comment by JohnnyBrr** [comment]
Same problem Windows 10

**Comment by jefflenz** [comment]
Same issue
OS: Ubuntu 18.04.4 LTS
Version: 1.7.4

**Comment by esoto-geret** [comment]
Same issue
OS: Windows 10 Home
Version: 1.7.4

**Comment by vucacruz** [comment]
Same issue;
OS: Ubuntu 19.10
Version 1.7.4

**Comment by pashtet422** [comment]
Same problem. Fedora 31

**Comment by WHMHammer** [comment]
FYI I rolled back to 1.7.2, and successfully added my account.

**Comment by pythonInRelay** [comment]
Temp solution. Install an older version located [here](https://github.com/Foundry376/Mailspring/releases/tag/1.7.2).

**Comment by sketet** [comment]
Hello, I changed the password of my email account and when I try to update the setting in mailspring I receive a blank window. Is it the same issue?
A solution?

**Comment by facubarril** [comment]
Same problem. While adding the account it connects fine and gives no error, but then it doesn't show anywhere.

**Comment by xtrp** [comment]
Same problem as well.

**Comment by sketet** [comment]
Hello, if I remove the current version, then I install an older version, I lose all the settings? The older version recognize the setting folders in .home with the setting of the newer version?
I've several accounts, with all the settings... signatures... I don't want to do it again!

**Comment by pashtet422** [comment]
> Hello, if I remove the current version, then I install an older version, I lose all the settings? The older version recognize the setting folders in .home with the setting of the newer version?
> I've several accounts, with all the settings... signatures... I don't want to do it again!

Snap package and github package has different setting environment
I don't want to be responsible for that but.
I installed an older version from github without removing a newer one (newer one was from github too). then i created a new imap account, and installed latest version again. and everything works flawlessly.
P.S. make a copy of a home/.config/Mailspring folder, it helps you undo your changes, if something goes wrong

**Comment by Marco22874** [comment]
Same issue on windows 10 64bit + mailspring 1.7.4

**Comment by sketet** [comment]
> > Hello, if I remove the current version, then I install an older version, I lose all the settings? The older version recognize the setting folders in .home with the setting of the newer version?
> > I've several accounts, with all the settings... signatures... I don't want to do it again!
> 
> Snap package and github package has different settings environment
> I don't want to be responsible for that but.
> I installed an older version from github (rpm package) without removing a newer one (newer one was from github too). then i created a new imap account, and installed latest version again. and everything works flawlessly.
> P.S. make a copy of a home/.config/Mailspring folder, it helps you undo your changes, if something goes wrong

I installed with .deb, if I try to install an older version, keeping the current version, I receive this error.
![Schermata del 2020-04-15 12-27-41](https://user-images.githubusercontent.com/34894217/79332465-27fea380-7f1d-11ea-93e4-e23d2994d683.png)

So I've to remove and then reinstall. But like I told, I don't want to enter all the data again.
I will see...

**Comment by DrMorbid** [comment]
Hello,
had the same problem on Linux Mint 19.3 with Mailspring 1.7.4.
Tried to do:
`sudo snap refresh mailspring --channel=latest/edge`
Which installed version 1.7.5 and I can now add IMAP account without problems.

**Comment by alvaro-leite** [comment]
The version 1.7.5 solves the IMAP problem for me.

Thanks!

**Comment by bengotow** [comment]
Hey folks—thanks for filing this, this is a pretty serious bug. It was reported in a handful of other issues and we shipped a fix for it yesterday in version 1.7.5. 

You can download the update from GitHub releases or from https://getmailspring.com/download, and the app should also auto-update if you have been using it. Sorry for the delay getting a fix out for this one, I appreciate everyone's help debugging and triaging the problem!
