### ISSUE TITLE
Add Ability to Enable Archive Button for Any Email Type Which Allows Folder Moving

### ISSUE THREAD

**Issue by seesemichaelj** [Foundry376/Mailspring#185]
I'm not sure why, but Mailspring has removed the ability to archive emails with the press of a button for Office 365 accounts (I haven't checked whether or not this was enabled for IMAP accounts). Why? I see there no reason why there can't be a button to move emails to the Archive folder quickly since Inbox Zero is a very popular thought process.

I'm fine if there is a setting to turn this functionality on; however I enjoyed how it was functioning in Nylas.

**Comment by bengotow** [comment]
Hmm I'll see if this is possible. Archiving in Gmail is not the same as archiving on other providers that happen to have an Archive folder, so it could create some very strange behaviors if you're in unified inbox and select some O365 threads and some Gmail threads and say "Archive".

**Comment by seesemichaelj** [comment]
Archiving worked before, what changed in Mailspring?

**Comment by bengotow** [comment]
Hey! Yeah—the old version of Nylas Mail had a concept of "categories" which were sort of folders and labels munged together. It made the logic kind of complicated in the app, and when I implemented the new sync engine I switched back to Folders and Labels as separate concepts.

I think the old version of the app coerced the "archive" behavior to a folder action on the sync side, but I can't quite remember.

I've been looking at this and I think we can definitely autodetect an "Archive" folder / role for non-Gmail accounts and set it to a folder, and the logic in the client might still handle it correctly. Will try it and see :-)

**Comment by seesemichaelj** [comment]
Sounds great! Thanks!

**Comment by bengotow** [comment]
Hey folks! This has been resolved and just didn't get closed somehow. You can now use the Preferences > Folders screen to choose an archive folder for any account and use it.

<img width="833" alt="image" src="https://user-images.githubusercontent.com/1037212/33348742-72bafa76-d48f-11e7-9620-caf8a97c906d.png">
