### ISSUE TITLE
Bug: Scroll bar eating links from GitHub emails

### ISSUE THREAD

**Issue by ForNeVeR** [Foundry376/Mailspring#1851]
**Describe the bug**
I often receive mails from GitHub that contain long log messages. When I look onto them in Mailspring, the bottom line of the message (which contains useful links!) may be obscured by the scroll bar:
![image](https://user-images.githubusercontent.com/92793/76213744-e6078100-623d-11ea-8b67-9aff96579326.png)

Actual message looks like this:
![image](https://user-images.githubusercontent.com/92793/76213773-f7e92400-623d-11ea-836c-c1695969d083.png)

**To Reproduce**

Receive a message from GitHub that contains a long line inside of a code block.

**Expected behavior**
I think that the scrollbar should be outside of the last message line, or at least there should be a vertical scrollbar?

**Setup: (please complete the following information):**
 - OS: Windows 10
 - OS Version: 1903
 - Mailspring Version: 1.7.4

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this, this has been fixed by 86ed6db08851b8a45bec9dd4f30f0b26f80f5406 (#1762) and will be shipped in 1.7.6.

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
