### ISSUE TITLE
Bug: Multiple signatures are inserted into message body when toggling between send-as accounts that have different signatures configured

### ISSUE THREAD

**Issue by axfelix** [Foundry376/Mailspring#1852]
This appears to be new as of the latest version -- if you have Mailspring configured with multiple send-as accounts using multiple signatures, and you start a new composition, toggling between From: accounts will leave all of your signatures stacked in the message body. Didn't happen in 1.7.3.

**Comment by axfelix** [comment]
Looks like this might be a duplicate of #1825.

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
