### ISSUE TITLE
Unable to update connection settings Bug: 

### ISSUE THREAD

**Issue by chivalryx** [Foundry376/Mailspring#1858]
**Describe the bug**
When attempting to create a new iMap account, or update connection settings of an existing account, the window pop up shows blank.  The only work around I've found, is to install 1.7.2 or older, create all the accounts and settings, then update to 1.7.4.

**To Reproduce**
Settings
Preferences
Accounts
Update Connection Settings (produces a blank window)

**Expected behavior**
The window pop up should show the connection settings and allow editting.

**Setup: (please complete the following information):**
 - OS: iOS 10.14.6
 - Mailspring Version: 1.7.4

**Comment by sarovin** [comment]
Duplicate #1841

**Comment by pythonInRelay** [comment]
Temp solution. Install an older version located [here](https://github.com/Foundry376/Mailspring/releases/tag/1.7.2).

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved in a later release, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
