### ISSUE TITLE
Bug: stay blank white when adding office-365 account

### ISSUE THREAD

**Issue by zlf341** [Foundry376/Mailspring#1861]
**Describe the bug**
after trying to add office-365 account, GUI stay in white blank

**To Reproduce**
grand new installed ubuntu 18.04.4, 
installed mailspring from software store
login into mailspring id
add office-365 account, input email and password
then it is stay on white blank screen for more than 30 min not response
here are from ps

usr+  2274  1605  0 22:23 tty2     00:00:10 /snap/mailspring/440/usr/share/mailspring/mailspring
usr+  2497  2274  0 22:23 tty2     00:00:00 /snap/mailspring/440/usr/share/mailspring/mailspring --type=zygote --no-sandbox
usr+  2541  2274  0 22:23 tty2     00:00:00 /snap/mailspring/440/usr/share/mailspring/mailspring --type=gpu-process --enable-features=SharedArrayBuffer --no-sandbox --gpu-preferences=KAAAAAAAAACAAABAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --use-gl=swiftshader-webgl --service-request-channel-token=5301159965975372

**Expected behavior**
should be continue display.

**Screenshots**

**Setup: (please complete the following information):**
 - OS: [Ubuntu 18.04.4]

**Comment by dbatsche** [comment]
Same happens for me on Mac, Windows and Linux (elementaryOS, based on Ubuntu 18.04) with several IMAP accounts.
It happens also with a mail address which worked before, since I removed the account to start from scratch.

Replied here since I think it is not a problem bound to an account type but a general problem.

**Comment by jmirap** [comment]
Same for me with an hotmail account. No problem with gmail accounts. OS: Windows 8.1

**Comment by pythonInRelay** [comment]
Exact same problem. It's completely unusable.

**Comment by 404NotFoundv2** [comment]
I have the same problem. No issues with Gmail, but Hotmail gives me a blank screen when setting it up as the first account. When I add a Hotmail account after I've set up my Gmail it says that it has been added successfully, but nothing happened.

**Comment by geniiii** [comment]
Same here, can't add IMAP/SMTP account.

**Comment by matheusreich** [comment]
It is also happening with me, Ubuntu 19.10 Snap version. I'm only able to add an G-Mail account, and no IMAP or Hotmail account.

**Comment by bwbuhse** [comment]
I'm having the same problem on Arch with Linux Kernel 5.5.9-arch1-2 with KDE Plasma 5.18.3

**Comment by theAndrewCline** [comment]
Having this issue as well. Pop!_os 19.10

**Comment by strange-developer** [comment]
Having this issue as well with Office365 account. OS 18.04

**Comment by westr029** [comment]
This is also happening with Ubuntu 20.04 for an office 365 account

**Comment by dklarkowski** [comment]
I could not connect with Office365 on Windows too, roll backed to 1.7.2 and it seems to work fine.

**Comment by bengotow** [comment]
Hey folks—thanks for filing this, this is a pretty serious bug. It was reported in a handful of other issues and we shipped a fix for it yesterday in version 1.7.5. 

You can download the update from GitHub releases or from https://getmailspring.com/download, and the app should also auto-update if you have been using it. Sorry for the delay getting a fix out for this one, I appreciate everyone's help debugging and triaging the problem!
