### ISSUE TITLE
Bug: Can't re-authenticate any account

### ISSUE THREAD

**Issue by nagaflokhu** [Foundry376/Mailspring#1864]
**Describe the bug**
The `Re-authenticate...` button in `Preferences > Accounts` does not work.

**To Reproduce**
1. Go to `Preferences > Accounts`.
2. Click on any of your accounts and then on `Re-authenticate...`.
3. Either nothing happens or a blank window that remains blank forever appears.

**Expected behavior**
I expected a window that would allow me to re-enter my authentication credentials for the selected account.

**Setup: (please complete the following information):**
 - OS: macOs
 - OS Version: 10.13.6 (High Sierra)
 - Mailspring Version: 1.7.4

**Comment by wreedheid** [comment]
Same issue here.

**Comment by ASeatonSpatial** [comment]
Same issue here.  I get a blank window, nothing ever appears.

Version 1.7.4
Ubuntu 18.04 LTS

**Comment by ASeatonSpatial** [comment]
I had to change passwords for two accounts this week.  I can't reauthenticate or remove the accounts.  I'll switch to another email client for now until this gets resolved.

**Comment by wreedheid** [comment]
If you download version 1.7.2 and configure your clients in that version, then let it update, it should work.

**Comment by patrickrmaia** [comment]
Same issue here.

OS: macOS
OS Version: 10.15.3 (Catalina)
Mailspring Version: 1.7.4

**Comment by skonsoft** [comment]
Hello,

Same problem here. 

I can not update my account password. White screen and nothing happing... I can not wait a lot of time, i need to send email for my company, so i uninstalled mailspring and i installed hiri and it works as charm on UBUNTU 19.10.

**Comment by bengotow** [comment]
Hey folks—thanks for filing this, this is a pretty serious bug. It was reported in a handful of other issues and we shipped a fix for it yesterday in version 1.7.5. 

You can download the update from GitHub releases or from https://getmailspring.com/download, and the app should also auto-update if you have been using it. Sorry for the delay getting a fix out for this one, I appreciate everyone's help debugging and triaging the problem!
