### ISSUE TITLE
Feature request: Search for  'not starred' emails

### ISSUE THREAD

**Issue by pablorq** [Foundry376/Mailspring#1867]
**Is your feature request related to a problem? Please describe.**
In the search box you can combine different filters in gmail search style, like "in:inbox is:starred". But I can't search for not starred emails or do a 'not' over a filter o word, to search for the rest of emails.

**Describe the solution you'd like**
In Gmail you can do a 'not' search for words and status. For instance, you can do a search like "in:inbox -is:starred". This will search for emails in the inbox without stars.

**Describe alternatives you've considered**
To look for every email and manually click the ones without stars. Not a good alternative at all!

**Additional context**
It could work with gmail and other type of accounts (office365, in my case).

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—I went ahead and implemented the "NOT" operator in search today (f6a008b279680231393bcbd0df79596c9d0b4c3d) so this will work in the next release. One important caveat is that you have to say "A NOT B" (so your example of in:inbox NOT is:starred) will work fine, but you can't say "NOT is:starred" by itself). 

The next release is scheduled to go out tomorrow - stay tuned!

**Comment by pablorq** [comment]
Oh! It's nice to hear that!

I think that "A NOT B" is ok. Maybe you can add some error message just in case someone (maybe myself! jajaja) try a "NOT something".

Some error message like: 'Missing parameter. Usage: A NOT B"

Cheers!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
