### ISSUE TITLE
Bug: Adding Imap Mail Account

### ISSUE THREAD

**Issue by antonkro** [Foundry376/Mailspring#1868]
**Describe the bug**
Since the last update its not possible anymore to setup a IMAP Mail Account (GMail works)
Since there are some similar bugs allready opened the purpose of this is to provide additional information to support the dev team

**To Reproduce**
1. Freshly install Mailspring via Snap/rpm package
2. Click on IMAP Button
3. Fill in valid data
4. Create

**Current bevavior**
White App Screen, error on output

**Expected behavior**
Setup will be finished and mail will be added

**Screenshots**

Snap App:
![image](https://user-images.githubusercontent.com/22957640/77022038-caf8e780-6988-11ea-83c5-9cb622b75e64.png)

Console Output:
![image](https://user-images.githubusercontent.com/22957640/77022065-df3ce480-6988-11ea-8b44-d83e1f33422b.png)

**Setup: (please complete the following information):**
 - OS: Fedora
 - OS Version 31
 - Mailspring Version Snap: Latest snapcraft snap (1.7.4-d54ff730)
 - Mailspring Version rpm: Latest rpm from homepage (mailspring-1.7.4-0.1.x86_64.rpm)

**Additional context** 
Same behavior on different software origins (rpm File /snap), I also tested it on different machine (Deskop PC / Notebook)

If you need any further information let me know and I will provide you with all the information you need. 

Thank you in advance!
Cheers Toni

**Comment by iwaffles** [comment]
I'm also seeing this error on Pop!_Os installed as the .deb package.

**Comment by nsiret** [comment]
Same Problem with the latest download.  Installed as an .rpm package.

**Comment by louis-lau** [comment]
Seeing the same behaviour on windows.

**Comment by lommysly** [comment]
![Imap_2](https://user-images.githubusercontent.com/62479049/77232603-631de900-6ba2-11ea-907e-9775405f5574.PNG)

**Comment by lommysly** [comment]
hello, I have tried several times to configure corporate mails but it fails.
When I enter all the data he replies that he added the account but does not actually enter it.
is there a solution to the problem?

**Comment by louis-lau** [comment]
For now, install the previous version.

**Comment by antonkro** [comment]
Thanks! Allready did that. I'm running Mailspring smoothly at Version 1.7.2-4522b259... clicking couraged the update message away!

**Comment by rakshith-ravi** [comment]
> For now, install the previous version.

Hey @louis-lau. Would you happen to know how that works with snap from the CLI? Not sure how to proceed with installing a specific version. Anything I find online only points to channels.

**Comment by louis-lau** [comment]
@rakshith-ravi On desktop I use windows, and I don't really use snap for anything else so I'm not sure. Should be the same as for any other snap package though. I imagine Google be able to help you with that. 😁

**Comment by antonkro** [comment]
@rakshith-ravi 
as far as i know you can you use "snap revert mailspring" for that

**Comment by nagaflokhu** [comment]
I just checked the diff between the 1.7.3 and 1.7.4 tags. IIUC those are the two latest released Mailspring versions.

I see essentially three types changes:
1. Documentation changes (changelog, updating version number).
2. MacOS-specific changes which seem to influence the build process. We can safely ignore these since this issue is clearly cross-platform.
3. Dependency updates. Specifically, changes to `package-lock.json`.

Clearly, because we can ignore documentation and Mac-specific changes, the cause of this problem is not Mailspring itself, but a problem in one of Mailspring's dependencies.

**Comment by edmond-irani** [comment]
I had the same issue with 1.7.4. The solution was installing version 1.7.2 first, then upgrade to 1.7.4.

**Comment by nagaflokhu** [comment]
after upgrading you are able to add IMAP accounts? because I am pretty sure I had 1.7.2 before and that stopped working when I upgraded to 1.7.4.

**Comment by louis-lau** [comment]
I wouldn't say solution. More of a workaround.

**Comment by edmond-irani** [comment]
> after upgrading you are able to add IMAP accounts? because I am pretty sure I had 1.7.2 before and that stopped working when I upgraded to 1.7.4.

Yeah. I re-started Mailspring after a while and went for the latest 1.7.4, and faced the same white screen problem when adding an IMAP/SMTP account. As I said, I uninstalled 1.7.4, installed 1.7.2 and could add my account in 1.7.2. Then I upgraded by installing the 1.7.4 package without removing 1.7.2. I haven't tried adding a new account again in 1.7.4 though. But with the current "workaround" I could have my account running under 1.7.4.

**Comment by rakshith-ravi** [comment]
> @rakshith-ravi
> as far as i know you can you use "snap revert mailspring" for that

That only reverts back to the previous installed version. I don't have any previous version installed. This is from a fresh install. So that doesn't exactly work out for me

**Comment by nagaflokhu** [comment]
@rakshith-ravi You can use this link to download 1.7.2: https://github.com/Foundry376/Mailspring/releases/download/1.7.2/Mailspring.zip

**Comment by rakshith-ravi** [comment]
> @rakshith-ravi You can use this link to download 1.7.2: https://github.com/Foundry376/Mailspring/releases/download/1.7.2/Mailspring.zip

This is for the mac. I'm using snap unfortunately. The deb version requires python, which isn't available on 20.04. So I'm forced to use the snap

**Comment by AzagraMac** [comment]
**OS:** Debian 10.3 Buster 64bit
**Mailspring:** 1.7.4
**Installation method:** from [https://getmailspring.com/download](https://getmailspring.com/download) with the 64-bit .deb file
**Case:** Error, it is not possible to add an IMAP / iCloud account, despite the fact that in graphic mode it does not report an error, looking at the log, it returns this error.

```sh
{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
```

**Comment by JakeCowton** [comment]
Same error for adding an outlook account on Ubuntu 18.04.

**Comment by rakshith-ravi** [comment]
Can we please have a new version released with this fix so that we can update it on our systems?

**Comment by nagaflokhu** [comment]
I would be curious to know how the one added line fixes this issue. And it seems like a good idea to add at least one regression test to make sure this doesn't happen again in the future.

**Comment by rakshith-ravi** [comment]
@bengotow can we please release a new version 1.7.5 of mailspring so that we can start using this fix? I'd rather rely on official channels of release than build from source. Can we have a new version published to snap please?

**Comment by marcwieland95** [comment]
Thanks. Great work. Can confirm it solved an issue I had since a long long time.
