### ISSUE TITLE
Create Chat/Communication Channel

### ISSUE THREAD

**Issue by seesemichaelj** [Foundry376/Mailspring#187]
Whether this is Slack (I prefer this since the Gitter desktop client is crap and I use Slack for business purposes - no offense to Gitter fans) or Gitter or etc. I believe we should create a communication channel that we can communicate questions/etc that don't belong on Github

**Comment by bengotow** [comment]
Have been meaning to do this - here goes!

https://join-mailspring-slack.herokuapp.com/

Gonna update the readme and the issue template to reference the new channel. 👍
