### ISSUE TITLE
Bug: MailSpring cannot be installed on Centos8+ or RHEL 8+

### ISSUE THREAD

**Issue by nsiret** [Foundry376/Mailspring#1870]
**Describe the bug**
MailSpring cannot be installed on Centos8+ or RHEL 8+ due to broken dependency.

**To Reproduce**
1. Download mailspring (*.rpm) 
2. Try to install on Centos8+ or RHEL 8+

**Expected behavior**
The installation runs smoothly 

**Screenshots**
Not required. Log:
```
Error: 
 Problem: conflicting requests
  - nothing provides libappindicator needed by mailspring-1.7.4-0.1.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Setup: (please complete the following information):**
 - OS: Centos and RHEL
 - OS Version 8+
 - Mailspring Version: 1.7.4

**Possible bug fix** 
In file ./app/build/resources/linux/redhat/mailspring.spec.in

```
%ifarch i386 i486 i586 i686
Requires: lsb-core-noarch, libXss.so.1, libsecret-1.so.0, ca-certificates
%if 0%{?rhel} >= 8
Requires: libappindicator-gtk3
%else
Requires: libappindicator
%endif
%else
Requires: lsb-core-noarch, libXss.so.1()(64bit), libsecret-1.so.0()(64bit), ca-certificates
%if 0%{?rhel} >= 8
Requires: libappindicator-gtk3
%else
Requires: libappindicator
%endif
%endif
```

**Comment by bengotow** [comment]
Hey @nsiret thanks for filing this—can you confirm that the app's notifications still work with `libappindicator-gtk3`? As long as things still work this seems like a safe change to make.

**Comment by nsiret** [comment]
Hey @bengotow, you're welcome! The app notifications still work (email received, email open, etc.) with `libappindicator-gtk3`. I am using Mailspring on CentOS 8.1 with `libappindicator-gtk3` right now and everything's fine.

**Comment by bengotow** [comment]
Great! I will ship your suggested change in the next release, seems safe to me and consistent with the docs over here https://fedoraproject.org/wiki/Packaging:DistTag Cheers!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!

**Comment by Tekkness** [comment]
Hello @bengotow , I downloaded the RPM file from https://getmailspring.com/download and it is still asking for "libadppindicator". 

DNF wont install anything, even with "--skip-broken"

**Comment by nsiret** [comment]
Hello @Tekkness, 

Just checked the new release, and yes it is still asking for `libappindicator` on CentOS 8/RHEL 8. Not an expert in packaging RPM but `rpm --eval 0%{?rhel}` return `08` so `%if 0%{?rhel} >= 8` should have fixed the problem... unless CentOS and RHEL are a bit more binding and one needs to specify `%if 0%{?rhel} == 8` instead of `%if 0%{?rhel} >= 8`. It is less generic but the operator `==` is more often used in CentOS/RHEL documentation. 

Note that I have **not** tested the solution so it might be another problem. 

@bengotow, if you want to install Mailspring with CentOS/RHEL 8, you can do it by modifying the dependency and repackaging:
1. Install [rpmrebuil](https://sourceforge.net/projects/rpmrebuild/files/rpmrebuild/) (13 or 14 but not 15 because it uses libs not yet supported on RHEL/CentOS 8) 
2. ```$ rpmrebuild -enp mailspring-1.7.6-0.1.x86_64.rpm ```
3. Go to line ```Requires:      libappindicator``` and modify ```Requires:      libappindicator-gtk3```
4. Save and exit, the process will continue
5 ```Do you want to continue ? (y/N) y```
6. The RPM has been repackaged
7. Go to ```$ cd $HOME/rpmbuild/RPMS/x86_64/```
7. ```$ yum localinstall mailspring-1.7.6-0.1.x86_64.rpm```

Not ideal but it is a working solution.

**Comment by Tekkness** [comment]
@nsiret Thank you very much! Rebuilding the RPM and local installing it worked for me 

Thanks :)

**Comment by nsiret** [comment]
You're welcome!
