### ISSUE TITLE
LinkedIn profile url in the sidebar is malformed

### ISSUE THREAD

**Issue by stanclarke-jr** [Foundry376/Mailspring#1875]
**Describe the bug**
The LinkedIn profile url in the sidebar appears to be malformed. There's an extra 'in' before the user's handle. The result is a broken link.

**To Reproduce**
1. Go to the sidebar
2. Hover over the LinkedIn icon. You will see: https://www.linkedin.com/in/in/{linkedin.handle}
3. Click it. You are redirected to https://www.linkedin.com/in/unavailable/

**Expected behavior**
Click on the LinkedIn icon, and you are taken to the user's profile page.

**Setup:**
 - OS: Kali Linux 5.4.0-kali4-amd64
 - Mailspring Version: ex: 1.7.4-d54ff730

**Comment by bengotow** [comment]
Ahh good catch! It looks like the data we're retrieving from the contact discovery system sometimes contains the /in/ prefix and sometimes doesn't. Will get this fixed!

**Comment by stanclarke-jr** [comment]
Nice. That was quick. Installing the new release as I type.

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀 The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
