### ISSUE TITLE
ported theme is displayed in picker but cannot be selected.

### ISSUE THREAD

**Issue by nickolasclarke** [Foundry376/Mailspring#188]
##### Are there any related issues?

...

##### What operating system are you using?
Win 10

##### What version of Mailspring are you using?
1.0.5

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I've [ported](https://github.com/nickolasclarke/mailspring-dracula) the Dracula theme for N1 to Mailspring, and after a few tries, it did install. It now appears in the picker, but when I try to select it  the following error appears in the JS logs: 

``` 
{"host":"NCLARKE","timestamp":"2017-10-17T08:09:04.508Z"}
{"host":"NCLARKE","timestamp":"2017-10-17T08:09:04.508Z","payload":{"url":"C:\\Users\\nclarke\\AppData\\Local\\Mailspring\\app-1.0.5\\resources\\app.asar\\node_modules\\react-dom\\lib\\ReactErrorUtils.js","line":51,"column":7,"pluginIds":[]}}
{"host":"NCLARKE","timestamp":"2017-10-17T08:09:12.938Z"}
{"host":"NCLARKE","timestamp":"2017-10-17T08:09:12.938Z","payload":{"url":"C:\\Users\\nclarke\\AppData\\Local\\Mailspring\\app-1.0.5\\resources\\app.asar\\node_modules\\react-dom\\lib\\ReactErrorUtils.js","line":51,"column":7,"pluginIds":[]}}
```

**Comment by bengotow** [comment]
Hey that looks cool! Can you try editing this file, and changing `styles/ui-variables.less` to `ui-variables.less` since the files are in the same folder now? That should do the trick. Definitely weird it didn't give a LESS compiler error in the console though.

https://github.com/nickolasclarke/mailspring-dracula/blob/master/styles/index.less#L1

**Comment by nickolasclarke** [comment]
ah yes, of course. That did it. I need to do some more work to make the theme actually readable in parts, however. Thanks for the help!
