### ISSUE TITLE
Bug: Ubuntu 20.04 Has no Python2 support

### ISSUE THREAD

**Issue by siddhantmahalle** [Foundry376/Mailspring#1880]
**Describe the bug**
Ubuntu 20.04 has removed python2 and mailspring is not installing due to it.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup: (please complete the following information):**
 - OS: [e.g. macOS, Fedora Linux]
 - OS Version [e.g. 14]
 - Mailspring Version: ex: 1.6.2 (found in the app's menu)

**Additional context** 
Add any other context about the problem here. If this issue is related to a particular account or email service, be sure to mention it so this report is actionable!

**Comment by Alexander-Huang** [comment]
I haven't installed python2 but I'm running mailspring correctly.Python2 doesn't seem like a dependency of mailspring.

**Comment by usfbrian** [comment]
+1 this doesn't work without a workaround on a 9370 XPS 13 with fresh install of 20.04 daily/prerelease.

*CONTRIBUTING.md* lists Python v2.7 as a dependency, and on 20.04, the 'python' apt package is obsolete, replaced by 'python3' (installed) or 'python2' (not installed).

Fortunately, Atom has the same problem. The current workaround for them is to install a few python2 packages and then modify the dependencies in the .deb package:
```
$  dpkg -x mailspring-1.7.4-amd64.deb mailspring-src  
$  dpkg -e mailspring-1.7.4-amd64.deb mailspring-src/DEBIAN  
$  gedit mailspring-src/DEBIAN/control
(in the Depends line, change 'python' to 'python | python2')
$  dpkg -b mailspring-src/ mailspring-1.7.4-amd64-patched.deb
```
Then, install all dependencies, which might include `python2-minimal`, `libsecret-1-dev`, `gconf2`, and a handful of others; use `sudo apt -f install` to fix any broken packages. Finally:
```
$  sudo dpkg -i mailspring-1.7.4-amd64-patched.deb  
```

**Comment by usfbrian** [comment]
Also, @siddhantmahalle, if you're using the template, actually insert bug details instead of copy/pasting and changing just the bug description!

-----

**To Reproduce**
1. Download .deb
2. `dpkg -i mailspring-1.7.4-amd64.deb`
3. Error:
```
Selecting previously unselected package mailspring.
(Reading database ... ##### files and directories currently installed.)
Preparing to unpack mailspring-1.7.4-amd64.deb ...
Unpacking mailspring (1.7.4) ...
dpkg: dependency problems prevent configuration of mailspring:
 mailspring depends on libsecret-1-dev; however:
  Package libsecret-1-dev is not installed.
 mailspring depends on gconf2; however:
  Package gconf2 is not installed.
 mailspring depends on gconf-service; however:
  Package gconf-service is not installed.
 mailspring depends on python; however:
  Package python is not installed.
```

**Expected behavior**
Program installs from .deb without error

**Setup:**
OS: Ubuntu 20.04  
Mailspring Version: 1.7.4

**Additional context**
Atom is already installed on my computer, which meant the [steps for installing Python 2 (linked)](https://github.com/atom/atom/issues/20356) (`python2-minimal` followed by `libpython2-stdlib` and `python2`) on 20.04 were omitted.

**Comment by rakshith-ravi** [comment]
Also, @siddhantmahalle if you're using Ubuntu 20.04, you can install mailspring from the snap without worrying about the deb file. It will work even though python isn't installed.
