### ISSUE TITLE
Bug: 1.7.4 cant install SMPT accounts

### ISSUE THREAD

**Issue by martijnmichel** [Foundry376/Mailspring#1881]
**Describe the bug**
Cannot add SMPT account on 1.7.4, after succesfully completing the steps to add it and get a success message nothing happens. Gmail accounts work fine.

**To Reproduce**

**Expected behavior**
SMPT gets added

**Screenshots**

**Setup: (please complete the following information):**
 - OS: Fedora Linux
 - OS Version 31
 - Mailspring Version: ex: 1.7.4 (found in the app's menu)

**Additional context** 
SOLVED BY INSTALLING 1.7.2

**Comment by tarantelklient** [comment]
The bug was fixed in #1876, but there is no release up to now with this update.

**Comment by majkinetor** [comment]
Can we have a release ? 
Mailspring is unusable for me now.

**Comment by martijnmichel** [comment]
@majkinetor just install 1.7.2

**Comment by majkinetor** [comment]
1.7.2 has different bugs thatt were solved by 1.7.3

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this - I'm really sorry it's taken so long for the fix in #1876 to get shipped. I honestly can't believe it's April already - I will push out a 1.7.5 release tomorrow.

I think we can close it as a dup of #1848 but I'll keep it open until 1.7.5 ships for here for visibility. Thanks everyone for the comments and help triaging!

**Comment by martijnmichel** [comment]
Now my client is constantly hanging on Syncing your mailboxes :(
What happened to mailspring?? It used to be so good

**Comment by majkinetor** [comment]
I concur, the client is buggy, almost every friend using it had some problem so far. Too bad, because all like it in general.

On my side, after the latest update the message is constantly on, and dissapears when i click 'try now'.  Not sure why it can't do it on its own.

![image](https://user-images.githubusercontent.com/85767/79783516-119f8000-8341-11ea-8534-42f7422dc32c.png)


The behavior reported by @martijnmichel  was there on previous version constantly.

**Comment by bengotow** [comment]
Hey folks! I think the original issue got addressed here in 1.7.5 and 1.7.6, thanks for all the help triaging this.

@majkinetor — could you try downloading the latest release (1.7.6) and then when your account has issues, go to Preferences > Accounts and select it there? In the red error box there should be a new button that says `Error Details...` - that includes a more specific error message from the sync logs and other metadata about the account. If you could file a new issue with that context we can try to track this down!

**Comment by majkinetor** [comment]
There was no "red box"
