### ISSUE TITLE
The MailSpring can still not log in by using Google account

### ISSUE THREAD

**Issue by mohistmen** [Foundry376/Mailspring#1884]
Although I do not use mailspring for several weeks, I still pay attition to it. Well, today I want trying to use mailspring for checking that whether the Google account is available or not, but something similar happened. I even find that you say the "Google account issue" has been solved in Github. Maybe this issue doesn't happen out of China, but I log in in this country by using VPN. So can you check about the proxy? I don't know this problem is about proxy or not. Hope you can handle it. Thank you!
(Bless you keep COVID-19 away)

**Comment by mohistmen** [comment]
Additionally, it says that about "unknown error (mailsync: 3765269347)".

**Comment by bengotow** [comment]
Hey there! Thanks for reporting this issue. It sounds like you're running in to the same problem that folks have reported in #397 so I'm going to merge this into that issue and see if I can find out what is going on there.
