### ISSUE TITLE
Bug:Mailspring doesnt do nothing when trying to log in accounts 

### ISSUE THREAD

**Issue by mikesislac** [Foundry376/Mailspring#1889]
When I try to log in my accounts after installation, mailspring remains in a white window and does nothing.
![Anotación 2020-04-05 203450](https://user-images.githubusercontent.com/63180170/78515818-ed5a7580-777c-11ea-8a1c-2d41808c8579.png)

**Comment by skrive** [comment]
This bug was fixed in #1876, but there is no release yet with this update.

**Comment by playforvoices1** [comment]
The same problem here witth elementary os 5.1.3 Hera.

**Comment by redac** [comment]
Here's what i did to fix it before the new update drops:

Install an earlier version (not the latest) e.g: 1.7.2
Add your accounts, then update. After updating you will have the same problem so make sure you add all the accounts you need in the meanwhile.

**Comment by playforvoices1** [comment]
> Here's what i did to fix it before the new update drops:
> 
> Install an earlier version (not the latest) e.g: 1.7.2
> Add your accounts, then update. After updating you will have the same problem so make sure you add all the accounts you need in the meanwhile.

Thank you. This has also worked for me now.

**Comment by mikesislac** [comment]
> Here's what i did to fix it before the new update drops:
> 
> Install an earlier version (not the latest) e.g: 1.7.2
> Add your accounts, then update. After updating you will have the same problem so make sure you add all the accounts you need in the meanwhile.

It worked! Thank you so much.

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this - I'm really sorry it's taken so long for the fix in #1876 to get shipped. I honestly can't believe it's April already - I will push out a 1.7.5 release tomorrow.

I think we can close it as a dup of #1848 but I'll keep it open until 1.7.5 ships for here for visibility. Thanks everyone for the comments and help triaging!

**Comment by mikesislac** [comment]
Thank to you so much for paying attention.

**Comment by playforvoices1** [comment]
It`s good to know that have a look on the problem(s). Thank you.

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀 The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
