### ISSUE TITLE
Bug: Unable to get badge counters to work in KDE Neon/Kubuntu.

### ISSUE THREAD

**Issue by Jonchun** [Foundry376/Mailspring#1890]
**Describe the bug**
Badge counter notifications do not work in KDE. I've posted for some help troubleshooting [here](https://bugs.kde.org/show_bug.cgi?id=419659), but I find it unlikely I'll get anything  major. 

**To Reproduce**
1. Install Mailspring
2. Login so that you should have unread messages
3. Check to see if you have a counter badge

**Expected behavior**
I expect to see a badge. Don't get a badge.

**Screenshots**
This is the type of badge I'm referring to:
![image](https://user-images.githubusercontent.com/5800539/78646764-8b3a6700-7887-11ea-97ae-b2aed67e212a.png)

**Setup: (please complete the following information):**
 - OS: KDE Neon 18.04, Kubuntu 18.04, Kubuntu 20.04
 - Mailspring Version: 1.7.4, installed from snap and installed from deb

**Additional context** 
I was able to get the badges working after following [these instructions](https://github.com/Foundry376/Mailspring/issues/420) on Ubuntu 18.04 and Ubuntu 20.04. However, the same problem does not seem to apply to KDE.

Additionally, Telegram DOES work in KDE, so clearly there is at least one way of getting badge counters to work in KDE. According to the dev in the previously linked bug report, latte-dock (the dock I'm using) supports the unity launcher API.

Here is a table of my distro testing and whether I could get the badge notifications to work (after applying any relevant fixes to get it to load in the first place)
```
+----------------+----------+---------------+---------+--------------+------------+-----------------+
|     Distro     | Telegram | Telegram Snap | Discord | Discord Snap | Mailspring | Mailspring Snap |
+----------------+----------+---------------+---------+--------------+------------+-----------------+
| KDE Neon 18.04 | Yes      | Yes           | No      | No           | No         | No              |
| Kubuntu 18.04  | Yes      | Yes           | No      | No           | No         | No              |
| Kubuntu 20.04  | Yes      | Yes           | No      | No           | No         | No              |
| Ubuntu 18.04   | Yes      | Yes           | Yes     | No           | Yes        | No              |
| Ubuntu 20.04   | Yes      | Yes           | Yes     | No           | Yes        | No              |
+----------------+----------+---------------+---------+--------------+------------+-----------------+
```

**Comment by Jonchun** [comment]
Fixed. Need to install `libunity-dev`.

This only works with the .deb install, not the snap store version.

**Comment by Drarig29** [comment]
For Arch users, you need this AUR package: [`libunity`](https://aur.archlinux.org/packages/libunity/)

**Comment by shawnk0723** [comment]
> For Arch users, you need this AUR package: [`libunity`](https://aur.archlinux.org/packages/libunity/)

Did you successfully get it to work in Arch KDE? I tried this as you recommended but the badge didn't show up at all. Any idea?

**Comment by Drarig29** [comment]
You might need to restart your computer, I haven't figured out when it was starting to work, if it was just after installing the package or after restarting.

So just try it :wink:

**Comment by shawnk0723** [comment]
> You might need to restart your computer, I haven't figured out when it was starting to work, if it was just after installing the package or after restarting.
> 
> So just try it wink

I tried it already but it didn't work. :( are you using default kde panel or latte dock? I'm using latte. do you think that has anything to do with this issue?

**Comment by Drarig29** [comment]
I use the default one, and I don't know if it's because of latte, though it appears to.

**Comment by shawnk0723** [comment]
> I use the default one, and I don't know if it's because of latte, although it appears to.

I just confirmed this has nothing to do with the latte. So I installed libunity from aur and enabled "Show badge on the app icon: show unread count" in mailspring and of course I rebooted my system afterward but nothing happens. Am I missing something? I really need this to work so I can check my emails promptly. :(

**Comment by Cantello** [comment]
I was able to get the badge on Manjaro after installing vala & libunity from AUR.

![image](https://user-images.githubusercontent.com/594700/170838362-923334fd-de53-42c2-960d-83dd366e6cc6.png)

**Comment by shawnk0723** [comment]
> I was able to get the badge on Manjaro after installing vala & libunity from AUR.
> 
> ![image](https://user-images.githubusercontent.com/594700/170838362-923334fd-de53-42c2-960d-83dd366e6cc6.png)

I envy you. It doesn't work on mine. I tried everything you mentioned but no luck. I tried different versions of vala + libunity and mailsprings from snap, flatpak, aur on both latte dock and default kde panel then rebooted the system of course but nothing works. I wonder what's the difference between mine and your system settings. :(

**Comment by shawnk0723** [comment]
Just a quick question. In your "Unread" section, does it show a badge that indicates how many unread emails there? I'm just wondering if it supposed to show the number of unread emails bc mine doesn't

> You might need to restart your computer, I haven't figured out when it was starting to work, if it was just after installing the package or after restarting.
> 
> So just try it wink

Just a quick question. In your "Unread" section, does it show a badge that indicates how many unread emails there? I'm just wondering if it supposed to show the number of unread emails bc mine doesn't

**Comment by Cantello** [comment]
You mean here in the upper left part? Says '3' there, same as on the taskbar icon.

![2022-06-06 21_15_40-Manjaro Plasma  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/594700/172231442-43130761-d315-4cb1-98a7-6c3aee30fa99.png)

**Comment by shawnk0723** [comment]
No, I meant the "Unread" under the "Inbox" section but it looks like yours doesn't show any number there either. I was just wondering if not showing any number in that section has anything to do with my issue but apparently it's not. I have no idea what my system's problem is then. I'm on garuda and tried everything pretty much without any luck. :( thank you for the screenshot by the way.

**Comment by shawnk0723** [comment]
> No, I meant the "Unread" under the "Inbox" section but it looks like yours doesn't show any number there either. I was just wondering if not showing any number in that section has anything to do with my issue but apparently it's not. I have no idea what my system's problem is then. I'm on garuda and tried everything pretty much without any luck. :( thank you for the screenshot by the way.

No, I meant the "Unread" under the "Inbox" section but it looks like yours doesn't show any number there either. I was just wondering if not showing any number in that section has anything to do with my issue but apparently it's not. I have no idea what my system's problem is then. I'm on garuda and tried everything pretty much without any luck. :( thank you for the screenshot by the way.

**Comment by shawnk0723** [comment]
> For the record, the screenshot was done on Manjaro with Plasma, all updated and the latest version of vala installed via AUR first, then libunity. Maybe Garuda handles some things differently, even though both are Arch derivatives.

My system is Garuda with Plasma, all updated and the latest vala and libunity as well. I guess there is difference between Manjaro and Garuda. I just wish I can at least find out why this doesn't work on Garuda (whether it's compatibility issue or something else... that way I can at least have closure on this). All I know is I'm not the only one who has this issue. oh well... Thank you for sharing your system specs and trying to help me troubleshooting this issue.

**Comment by Phylu** [comment]
> No, I meant the "Unread" under the "Inbox" section but it looks like yours doesn't show any number there either.

@shawnk0723 As far as I know, this unread is just a "normal" folder that contains the unread e-mail. The counter badge in the menu only works for the inbox and not for other folders. However, I am not sure if this is a regression bug or something that has just not been implemented as a feature. (Tested on Ubuntu 22.04)

**Comment by Phylu** [comment]
@shawnk0723 Unfortunately, I don't have a Garuda system to trace down the issue with the task bar at the moment. We are leveraging the electron bindings here. If you want to have a look at the code to do some more debugging, this should be the place where this is implemented: https://github.com/Foundry376/Mailspring/blob/master/app/src/browser/application.ts#L537

**Comment by shawnk0723** [comment]
> electron bindings

Thank you for the link. I'll have a look but I'm afraid that I won't be good enough to debug it myself. Should we reopen this issue so hopefully it'll get more attention from people who are more knowledgeable with this bug than I am?

**Comment by shawnk0723** [comment]
> @shawnk0723 Unfortunately, I don't have a Garuda system to trace down the issue with the task bar at the moment. We are leveraging the electron bindings here. If you want to have a look at the code to do some more debugging, this should be the place where this is implemented: https://github.com/Foundry376/Mailspring/blob/master/app/src/browser/application.ts#L537

Thank you for the link. I'll have a look but I'm afraid that I won't be good enough to debug it myself. Should we reopen this issue so hopefully it'll get more attention from people who are more knowledgeable with this bug than I am?

**Comment by shawnk0723** [comment]
> Fixed. Need to install `libunity-dev`.
> 
> This only works with the .deb install, not the snap store version.

Hi Jonchun, I'm still having this issue. Have you tested this on any arch based distros by any chance? I'm on Garuda. I tried all the suggested methods but none of them worked for me. If nothing works then I think we should reopen this issue. Please let me know if you have any suggestions/tips. I would appreciate it very much.
