### ISSUE TITLE
Bug: Unable to automatically generate names etc. in mail body - contacts problem. (PRO user if it is necessary)

### ISSUE THREAD

**Issue by metegenez** [Foundry376/Mailspring#1891]
**Describe the bug**
A clear and concise description of what the bug is. Does it happen with all email accounts, or only a particular account and/or email message?

**To Reproduce**
1. Go to 'New mail'
2. Type "{{name}}" in somewhere in your mail
3. Send it for test

**Expected behavior**
Putting name of my contact into mail automatically.
**Screenshots**
https://i.ibb.co/gz4kwHP/image.png

**Setup: (please complete the following information):**
 - OS: Ubuntu
 - OS Version - 18.04
 - Mailspring Version: 1.7.2

**Additional context** 
As an additional problem, even if I add a contact in my address book, it does not come up when I type it into "To:" part. I have complete problem with contact support and generating automatic names etc. in my mail body.

**Comment by bengotow** [comment]
Hey @metegenez thanks for filing this! Mailspring allows you to create templates from Preferences > Templates that contain variable regions you can quickly navigate between and fill in, but it doesn't support automatic variable substitution based on the addressees. This is a cool idea though!

We're planning on adding broader support for mail merge (which is what this is typically called when the names + emails are coming from another source like a spreadsheet). Stay tuned! I'm going to merge this in to #174 so we can track it along with that feature.
