### ISSUE TITLE
Bug: Mailspring 1.7.4 can not add more than 1 account

### ISSUE THREAD

**Issue by DJ-Qst** [Foundry376/Mailspring#1892]
This bug affects all of my email addresses. I am able to add the initial Gmail account, but am unable to add a second account. Able to walk through the steps to set up account, but it says "Account Added Successfully" and then nothing happens

**To Reproduce**

1. Install Mailspring 1.7.4 (Current Release)
2. Go through setup
3. Once in main window, attempt to add a second account
4. Go through the steps to add an account
5. Nothing happens

**Expected behavior**
Adding a second or subsequent email account to use mailspring as a normal mail client

**Setup: (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - Mailspring Version: 1.7.4

**Additional context** 
To fix the problem currently, I had to roll back to 1.7.2, and that was the fix for both window's machines I have

**Comment by maneandrea** [comment]
Seems to be duplicate (or at least related) to this [other issue](https://github.com/Foundry376/Mailspring/issues/1248).

The current workaround for Ubuntu is to download and install an older version, like 1.7.2 from [here](https://github.com/Foundry376/Mailspring/releases), add the desired accounts, and finally update back to 1.7.4.

Perhaps that works for Windows too.

**Comment by DJ-Qst** [comment]
I'm not sure how I missed that issue when I was looking. I'm still fairly new to Github, so should I close this issue since there's the other issue that's still open?
