### ISSUE TITLE
Bug: can't add Yandex email account on the list

### ISSUE THREAD

**Issue by urbanishimwe** [Foundry376/Mailspring#1899]
**Describe the bug**
I tried to add my Yandex email account, I signed in successfully but I didn't see Yandex account on the list of my emails. I repeated the process a lot of times.

**To Reproduce**
1. on the window's menu Click on `file` and then `Add account`
2. select `Yandex`
3. fill out the details [username, password]
4. the Yandex account won't be added on the list

**Expected behavior**
I was expecting to see my Yandex account on the list of added emails

**Screenshots**
![yandex-1](https://user-images.githubusercontent.com/33803574/79056011-48470d80-7c52-11ea-9e9c-138d858a2af6.png)
![yandex-2](https://user-images.githubusercontent.com/33803574/79056012-4f6e1b80-7c52-11ea-80e4-a2558359ae9b.png)

**Setup: (please complete the following information):**
 - OS: ZorinOS
 - OS Version 15
 - Mailspring Version: 1.7.4

**Additional context** 
N/A

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this - I think it's related to a bug in the current release that causes issues with IMAP account auth. I'm really sorry it's taken so long for the fix in #1876 to get shipped. I will push out a 1.7.5 release tomorrow.

I think we can close it as a dup of #1848 but I'll keep it open until 1.7.5 ships for here for visibility. Thanks everyone for the comments and help triaging!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
