### ISSUE TITLE
Bug: Windows 10 - Can't add SMTP Email

### ISSUE THREAD

**Issue by RyanGaudion** [Foundry376/Mailspring#1900]
**To Reproduce**
Click add new account.
Choose IMAP/SMTP
I then enter the details as required
When I click submit/done it says "Adding account" but it doesn't appear in my list of accounts

**Expected behavior**
Account should appear in my list of account

**Setup: (please complete the following information):**
 - OS: Windows 10
 - App Version: 1.7.4

**Comment by hansva** [comment]
Duplicate #1876

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this - I'm really sorry it's taken so long for the fix in #1876 to get shipped. I will push out a 1.7.5 release tomorrow.

I think we can close it as a dup of #1848 but I'll keep it open until 1.7.5 ships for here for visibility. Thanks everyone for the comments and help triaging!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
