### ISSUE TITLE
Cannot sync 2nd email in mailspring app

### ISSUE THREAD

**Issue by Rechelle77** [Foundry376/Mailspring#1905]
I am experiencing issues with adding my second account. I can't add it and it says it's added but upon checking, it's not.

**Comment by tpaixao** [comment]
This was a bug in 1.7.4 and was fixed in 1.7.5, I believe.

**Comment by siucdude** [comment]
I have Ubuntu 20.10 and running 1.8 and i can confirm that this still is a bug... I can't add any second account.. Also people recommend to install 1.7.2 first, problem is in Ubuntu 20.10 the python package changed and we can't install old version..

**Comment by CodeMouse92** [comment]
Duplicate of #1248
