### ISSUE TITLE
Bug: White screen upon login

### ISSUE THREAD

**Issue by Nswayze** [Foundry376/Mailspring#1910]
**Describe the bug**
Currently running Manjaro linux. After adding phone number, app password and verifying via a url on Yandex. The account seems to login but the returned result is a white screen.

**To Reproduce**
1. Create or login to Mailspring account
2. Enter pop3 details manually

**Expected behavior**
A gui with all related content should display as opposed to a white screen

**Screenshots**

**Setup: (please complete the following information):**
 - OS: [Manjaro Linux]
 - OS Version [e.g. 14]
 - Mailspring Version: ex: 19.0.2 (found in the app's menu)

**Additional context** 
This error only seems to occur when manually entering the account pop3 details. When selecting Yandex from the list it is working. Great app!

**Comment by bengotow** [comment]
Hey @Nswayze! Thanks for reporting this—there was a really serious issue in 1.7.4 that caused this white screen but it was fixed in the 1.7.5 release yesterday. Can you make sure you've got the new version and try again?

**Comment by laplacecrame** [comment]
I've been tracking this issue for days. I updated to 1.7.5 as soon as you publish the release. Still it pops a blank screen.

Setup:
Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.68.0
Qt Version: 5.14.2
Kernel Version: 5.4.31-1-MANJARO
OS Type: 64-bit

**Comment by rsalevsky** [comment]
I can confirm. The white screen issue is also in 1.7.5.

**Comment by Nswayze** [comment]
Just want to restate, that it only seems to be happening when you manually enter the details. Selecting the button from the main screen doesn't seem to have any bugs on my end.

**Comment by skrive** [comment]
For anyone experiencing this, try deleting the Mailspring folder in .config (I'm not sure where it's located on Windows/Mac) and setting up Mailspring from scratch.

**Comment by laplacecrame** [comment]
> For anyone experiencing this, try deleting the Mailspring folder in .config (I'm not sure where it's located on Windows/Mac) and setting up Mailspring from scratch.

Thanks. It works!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
