### ISSUE TITLE
Hide in tray (on Windows)

### ISSUE THREAD

**Issue by MrMyth** [Foundry376/Mailspring#1913]
Good evening. Today I tried your program. He gave it up for several reasons. But I decided to leave a review. The first reason is that there is no way to hide the program in the tray. Remove the icon on the task bars.

**Comment by tpaixao** [comment]
If you simply close it, the icon on the tray remains there (Windows and Linux).

**Comment by MrMyth** [comment]
I don't understand you a little bit, I still have the badge on the taskbar.

**Comment by bengotow** [comment]
Hey there! You can hide Mailspring's system tray icon by going here in the preferences:
![image](https://user-images.githubusercontent.com/1037212/80001804-6ac3fc80-8484-11ea-8469-a6366adad5b3.png)

As @tpaixao mentioned, you can close Mailspring's main window and it will continue running / sending you notifications from the system tray. If you right click the system-tray, you can exit the program completely.

**Comment by MrMyth** [comment]
If a new letter comes I don't see any icons in the bottom right corner.
