### ISSUE TITLE
see incoming emails separately for each mailbox.

### ISSUE THREAD

**Issue by MrMyth** [Foundry376/Mailspring#1914]
Good evening. I wish I could hide a single mailbox. And see incoming emails separately for each mailbox. On Windows.

**Comment by skrive** [comment]
I'm not sure exactly what you mean, but you can already view each mailbox separately by clicking the window tab and selecting which account you want to view. This hides all other accounts.

**Comment by bengotow** [comment]
Hey! Yep, in the top left of the Mailspring window, you can click this dropdown to switch to a non-unified inbox view. You can also switch using the application's menu or using the keyboard shortcuts Ctrl-1, Ctrl-2, etc. Enjoy!

<img width="580" alt="image" src="https://user-images.githubusercontent.com/1037212/80004960-95b04f80-8488-11ea-821e-5af2041c7bca.png">
