### ISSUE TITLE
Bug: Can't send mail since latest release

### ISSUE THREAD

**Issue by marcwieland95** [Foundry376/Mailspring#1917]
**Describe the bug**
I'm unable to send mails since the latest update (1.7.5). No response when clicking the send button. The mail goes into the draft at some point. I reverted back to 1.7.4 and it's working again.

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version 10.15.4
 - Mailspring Version: 1.7.5

**Comment by bengotow** [comment]
Wow thanks for reporting this—I haven't seen this happen but I will track this down ASAP.

**Comment by bengotow** [comment]
Hey @marcwieland95 —thanks for reporting this. Could you try going to Developer > Show Mailsync Logs in Mailspring's menu? That'll reveal a folder that contains the mailsync-***.log files. If you could look at the bottom of those and see if there are any stack traces / errors, that will help narrow this down a lot.

**Comment by marcwieland95** [comment]
I can't reproduce it anymore. That's strange.
I'm back up at version 1.7.5 and I'm able to send them now.

**Comment by bengotow** [comment]
That's good! I've also added a button to the next release in 78a0748f7728433501ea5280819fa79a8127cb62 so that if this happens again, you can collect all the relevant error info quickly. Cheers!
