### ISSUE TITLE
Sync errors on IMAP account on 1.7.5

### ISSUE THREAD

**Issue by tpaixao** [Foundry376/Mailspring#1918]
Keep getting IMAP sync errors on my IMAP account.
In the acount tab, it says: "Mailspring encountered errors syncing this account. Crash reports have been sent to the Mailspring team and we'll work to fix these errors in the next release".

This happens both on Windows and Linux (snap) since 1.7.4...

**Comment by skrive** [comment]
The same is happening with me on Linux.

**Comment by tpaixao** [comment]
I tried a fresh installation in a brand new laptop and the same behavior happens. It doesn't matter if the IMAP account is the first or the second account to be added.

**Comment by sudoman281** [comment]
Works for me. I'm running Mailspring 1.7.5-1 on Manajaro Linux 5.5.16-1.

**Comment by skrive** [comment]
Just a quick update on this. I deleted the Mailspring folder in .config and set everything up again. I haven't experienced the issue since and everything seems to be working great.

I'm using Zorin (Ubuntu derivative) and used the .deb package to install Mailspring.

**Comment by BigDon55** [comment]
I too am having this issue on mxLinux 19.1 since the update to 1.7.5. I will try removing the config folder and see if this resolves the problem, else it is on to a more stable email client.

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this. Could you try going to Developer > Show Mailsync Logs in Mailspring's menu? That'll reveal a folder that contains the mailsync-***.log files. If you could look at the bottom of those and see if there are any stack traces / errors, that will help narrow this down a lot.

**Comment by BigDon55** [comment]
I have resolved the issue.

The problem is the LOCK files are not being deleted. The program crashed after first installation and left the LOCK files behind. After I deleted those, the program has not hiccuped again.
Don Matthews
In HIS Grace and With Gratitude

**Comment by tpaixao** [comment]
Where are the LOCK files?

**Comment by BigDon55** [comment]
I am on a Linux machine. The files on my system are:

~/.config/Mailspring
There are 3 or 4 LOCK files in this folder. Close Mailspring, and delete those. Restart Mailspring and it should work fine.
Don Matthews
In HIS Grace and With Gratitude

**Comment by BigDon55** [comment]
.

Don Matthews
In HIS Grace and With Gratitude

**Comment by Zach2212** [comment]
> Hey folks—thanks for reporting this. Could you try going to Developer > Show Mailsync Logs in Mailspring's menu? That'll reveal a folder that contains the mailsync-***.log files. If you could look at the bottom of those and see if there are any stack traces / errors, that will help narrow this down a lot.

```
[calContacts] [critical] 
 ***
 *** An exception occurred during program execution: 
 *** (unknown exception details)
 ***

24991 [2020-04-23 13:05:32.594] [calContacts] [critical]  *** Stack trace:
 ***   clone
 ***
```

This happens when it tries to sync my office365 account

**Comment by spylacopa** [comment]
The same happens here (openSUSE Tumbleweed, new installation via snap edge,
version 1.7.6)

here is the my log:

`Mailspring Version: 1.7.6-c394dc80
Platform: linux
Account State: sync_error
Account Provider: imap
IMAP Server: mail.efm.de
SMTP Server: mail.efm.de
--------------------------------------------
6141 [2020-04-26 00:30:54.680] [background] [info] -- 0 matches.
6141 [2020-04-26 00:30:54.680] [background] [warning] [SLOW] Transaction=unlinkMessagesMatchingQuery > 60ms (75444 microseconds, 6 waiting to aquire)
6141 [2020-04-26 00:30:54.680] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) no longer present in remote range.
6141 [2020-04-26 00:30:54.757] [background] [info] -- 0 matches.
6141 [2020-04-26 00:30:54.757] [background] [warning] [SLOW] Transaction=unlinkMessagesMatchingQuery > 60ms (77372 microseconds, 6 waiting to aquire)
6141 [2020-04-26 00:30:54.757] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) no longer present in remote range.
6141 [2020-04-26 00:30:54.831] [background] [info] -- 0 matches.
6141 [2020-04-26 00:30:54.831] [background] [warning] [SLOW] Transaction=unlinkMessagesMatchingQuery > 60ms (74279 microseconds, 7 waiting to aquire)
6141 [2020-04-26 00:30:54.831] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) no longer present in remote range.
6141 [2020-04-26 00:30:54.881] [foreground] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** database is locked
 ***

6141 [2020-04-26 00:30:54.887] [foreground] [critical]  *** Stack trace:
 ***   clone
 ***
`

**Comment by fferraro87** [comment]
on ubuntu 20.04 i've same problem database is locked...

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/crash-on-sync-no-stack-trace/419

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
