### ISSUE TITLE
A forwarded mail is not displayed in the thread

### ISSUE THREAD

**Issue by maximlefebvre** [Foundry376/Mailspring#192]
##### Are there any related issues?

...

##### What operating system are you using?
macOS Sierra, Version 10.12.6

##### What version of Mailspring are you using?
Version 1.0.5

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

When I forward a message with MailSpring, this message is not adding in the thread, altough it is, when I use Gmail directly or Mail.

I looked in the mail source, and I see that MailSpring doesn't add the reference (References: in header) to the previous mail.

Here an exemple of e-mail header when I forward a mail with MailSpring :

`Date: Tue, 17 Oct 2017 21:05:03 +0200
From: Maxime Lefebvre <my@mail.com>
To: "my2@mail.com" <my2@mail.com>
Message-ID: <local-0ac50f51-8a95@MacBookdeMaxime>
Subject: Fwd: Forward example
X-Mailer: Mailspring`

And for the same e-mail forwarded with Apple Mail :

`From: Maxime Lefebvre <my@mail.com>
Content-Type: multipart/alternative; boundary="Apple-Mail=_F4A08C52-9E3F-46EB-AE72-AE4DD8E5525F"
Mime-Version: 1.0 (Mac OS X Mail 10.3 \(3273\))
Subject: Fwd: Forward example
Message-Id: <2A667018-FCA6-40E5-A6F3-DC992D710558@dimelo.com>
References: <OF2988EF87.42D22460-ONC12581BC.005ED13B-C12581BC.005F0367@retraite.lan>
To: Maxim Lefebvre <my2@mail.com>
Date: Tue, 17 Oct 2017 21:17:54 +0200
X-Mailer: Apple Mail (2.3273)`

Thank you in advance for your help!

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! Thanks for reporting this and digging in to the message headers. I was able to reproduce this just now and I'll get it fixed in the next release.
