### ISSUE TITLE
Bug: Blank white page instead of Update Connection Settings

### ISSUE THREAD

**Issue by ZeeshanSultan** [Foundry376/Mailspring#1923]
**Describe the bug**
My mails randomly don't send saying they're unable to connect to the imap server / port. And repeat the same behavior for certain emails meanwhile working at the same time for newer mails.
I have confirmed it's not a port issue. 

I still wanted to update the IMAP connection setting but the setting screen shows a blank white page no buttons.

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Accounts'
3. Click on 'Update Connection Settings...'

**Expected behavior**
I want to check why it keeps saying Mail server / port unreachable after every couple of mails even though it's reachable but it keeps on showing a blank white screen

**Screenshots**
![image](https://user-images.githubusercontent.com/8667667/79773941-87a8e480-834b-11ea-9e45-1815c05cfa46.png)

**Setup: (please complete the following information):**
 - OS: Windows
 - OS Version 10
 - Mailspring Version: ex: 1.7.5

**Comment by playforvoices1** [comment]
The same problem here with the recent version on Windows 10 and Ubuntu 18.04

**Comment by fracsi** [comment]
Might be related to: #1814

**Comment by bengotow** [comment]
Hey folks! This will be resolved in the 1.7.6 release very soon - sorry for the hassle, this one took a little while to track down 👍

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
