### ISSUE TITLE
Incorrect classification of conversations in sent folder

### ISSUE THREAD

**Issue by JunnanZ** [Foundry376/Mailspring#193]
##### Are there any related issues?

No

##### What operating system are you using?
Arch

##### What version of Mailspring are you using?
1.0.5

--

**Bug?**
I replied a totally new email but when I went to the sent folder, it was grouped into an old thread where the emails have nothing in common (subject, receivers) with the mail I just replied. 

This incorrect thread is not in the web interface of my email account.

##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only observed one incorrect group in the sent folder of an Office 365 account.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey folks! It's been a few years and there haven't been any more reports of this issue so I'm going to close this as probably-fixed. Feel free to bump or create a new issue referencing this one if you encounter this again!
