### ISSUE TITLE
Bug: Google & Gsuite loosing authentication 

### ISSUE THREAD

**Issue by pyeguy** [Foundry376/Mailspring#1933]
**Describe the bug**
Loosing sync with google accounts (personal and gsuite) after last update. Essientially makes the application unusable. 

**To Reproduce**
None required, happens spontaneously. 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5299472/80147261-1abe6600-8568-11ea-8a5e-04ebed854344.png)

**Setup: (please complete the following information):**
 - OS: Windows 10 Hom
 - OS Version 10.0.19041
 - Mailspring Version: ex: 1.7.6-e94bb759

**Additional context** 

Mailspring Version: 1.7.6-e94bb759
Platform: win32
Account State: sync_error
Account Provider: gmail
IMAP Server: imap.gmail.com
SMTP Server: smtp.gmail.com

excerpt from error log

```
22984 [2020-04-23 13:19:41.606] [background] [info] Sync loop deleting unlinked messages with phase 2.
22984 [2020-04-23 13:19:41.614] [background] [info] Sync loop complete.
22984 [2020-04-23 13:19:46.357] [calContacts] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   _is_exception_typeof
 ***   _is_exception_typeof
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***
```

**Comment by athelas64** [comment]
Same issue...

**Comment by bengotow** [comment]
Hmm that's no good - thanks for reporting and including the error log. It looks like the process is crashing during calendar and contacts sync but we're not able to get a full stack trace somehow. I'll see if I can fix the stack reporting on Windows and get to the bottom of this!

**Comment by athelas64** [comment]
Let me know if you will need anything regarding reports, happy to help.

**Comment by pyeguy** [comment]
likewise! i'm back to using GMail in the browser at the moment 😭

**Comment by marcocastignoli** [comment]
new about this?

**Comment by pyeguy** [comment]
@bengotow  any update here? Sorry to pester but I can't use mailspring right now due to this fatal bug. 

If a fix is going to be a long way off can you point me to a previous release I can roll back to if you think the issue is client side?

**Comment by pyeguy** [comment]
any updates here @bengotow ? sorry to keep bumping I  would really love to be able to use MS again!

**Comment by dawidpalka** [comment]
@pyeguy For me, the last update (1.7.7-71504f2c) solved this problem. Update MS and try again.

**Comment by pyeguy** [comment]
@dawidpalka that did it! thanks for pointing that out, I hadn't opened it in a while.
