### ISSUE TITLE
Translation not complete, even if it is complete in the repository

### ISSUE THREAD

**Issue by silviopen** [Foundry376/Mailspring#1939]
I just installed mailspring 1.7.6 on ubuntu 19.10 through Ubuntu software and I noticed that the user interface is not completely translated into Italian.
I immediately looked for localization info but I found that the complete translation for my language already exists on github, But I don't know how to update the location file.

Any suggestions for solving this problem?

Keep in mind that I don't have much experience with Linux but I'm willing to learn
Thanks

![Schermata](https://user-images.githubusercontent.com/44685300/80286811-e09ec100-872d-11ea-9517-5a94168688b2.png)

**Comment by bengotow** [comment]
Hey @silviopen! Mailspring pulls these particular strings from your mail provider so they should match your account. Your IMAP provider is indicating that your trash folder is called `Cestino` maybe?

**Comment by silviopen** [comment]
I apologize, I actually confused the folders on the server with the location of the user interface.
In the meantime, I found out where to set the language.

Thanks anyway
