### ISSUE TITLE
Need clarification

### ISSUE THREAD

**Issue by specter78** [Foundry376/Mailspring#1944]
What would happen if I block `id.getmailspring.com` and `updates.getmailspring.com`? Mailspring is making too many requests to these domains.

PS: I’m not a pro user.

**Comment by bengotow** [comment]
Once you've signed in to the app the first time, it's safe to disable access to these domains. It'll prevent the following features from working, but as long as you don't use them you'll be fine:

- read receipts / link tracking
- composer translate button
- incoming message translation

"Snooze" and "send reminders" should still work but if you uninstall mailspring it'll forget what it was planning to unsnooze / take action on. It syncs the metadata for those features to the cloud so it can restore them across installs.
