### ISSUE TITLE
Bug: Mailspring sync crashes with error "[calContacts] [critical]   ***  *** A C++ exception occurred during program execution:   *** too many SQL variables  ***

### ISSUE THREAD

**Issue by ChrisFab16** [Foundry376/Mailspring#1951]
When syncing mail, I get a warning box in the lower left corner with "Encountered an error while syncing <email>"
This happens only for my primary gmail account. I have a second gmail account that seems to be fine.
When the sync issue is there, no interactions with any folders on the account is possible.
Reconnecting the account gives a short window where syncing works again before the error reappears.

**To Reproduce**
1. open mailspring
2. sync mail

**Expected behavior**
New mail to be fetched.

**Setup: (please complete the following information):**
 - OS: [e.g. macOS, Fedora Linux]
 - OS Version [e.g. 14]
 - Mailspring Version: ex: 1.6.2 (found in the app's menu)

**Additional context** 
Mailspring Version: 1.7.6-e94bb759
Platform: darwin
Account State: sync_error
Account Provider: gmail
IMAP Server: imap.gmail.com
SMTP Server: smtp.gmail.com
--------------------------------------------
 *** in mailsync     GoogleContactsWorker::run()::$_1::operator()(nlohmann::basic_json) const
 *** in mailsync     void __1::__invoke_void_return_wrapper::__call(GoogleContactsWorker::run()::$_1&, nlohmann::basic_json&&)
 *** in mailsync     GoogleContactsWorker::paginateGoogleCollection(__1::string, __1::string, __1::string, __1::function)
 *** in mailsync     GoogleContactsWorker::run()
 *** in mailsync     runCalContactsSyncWorker()
 *** in mailsync     main::$_7::operator()() const
 *** in mailsync     void* __1::__thread_proxy(void*)
 *** 0x7fff73e8d109  _pthread_start
 *** 0x7fff73e88b8b  thread_start
 ***

55412 [2020-04-29 08:18:47.435] [main] [info] Identity created at [redacted] - using ID Schema 1
55412 [2020-04-29 08:18:47.437] [main] [info] ------------- Starting Sync (email@domain.com) ---------------
55412 [2020-04-29 08:18:47.444] [metadata] [info] Metadata delta stream starting...
55412 [2020-04-29 08:18:50.447] [background] [info] Fetching XOAuth2 access token from Gmail for [redacted]
55412 [2020-04-29 08:18:50.621] [background] [info] Marking all folders as `busy`
55412 [2020-04-29 08:18:50.622] [background] [info] Syncing folder list...
55412 [2020-04-29 08:18:51.810] [background] [info] Syncing folder list...
55412 [2020-04-29 08:18:52.599] [background] [info] Sync loop deleting unlinked messages with phase 2.
55412 [2020-04-29 08:18:52.616] [background] [info] Sync loop complete.
55412 [2020-04-29 08:18:53.647] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/All Mail: modseq 9990370 to 9990370, uidnext 164700 to 164700
55412 [2020-04-29 08:18:53.849] [foreground] [info] Idling on folder [Gmail]/All Mail
55412 [2020-04-29 08:19:02.444] [metadataExpiration] [info] Scanning for expired metadata
55412 [2020-04-29 08:19:02.444] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
55412 [2020-04-29 08:19:11.127] [calContacts] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** too many SQL variables
 ***

55412 [2020-04-29 08:19:11.472] [calContacts] [critical]  *** Stack trace (line numbers are approximate):
 *** in mailsync     SQLite::Statement::Ptr::Ptr(sqlite3*, __1::string&)
 *** in mailsync     SQLite::Statement::Statement(SQLite::Database&, __1::string const&)
 *** in mailsync     ContactGroup::syncMembers(MailStore*, __1::vector)
 *** in mailsync     GoogleContactsWorker::run()::$_1::operator()(nlohmann::basic_json) const
 *** in mailsync     void __1::__invoke_void_return_wrapper::__call(GoogleContactsWorker::run()::$_1&, nlohmann::basic_json&&)
 *** in mailsync     GoogleContactsWorker::paginateGoogleCollection(__1::string, __1::string, __1::string, __1::function)
 *** in mailsync     GoogleContactsWorker::run()
 *** in mailsync     runCalContactsSyncWorker()
 *** in mailsync     main::$_7::operator()() const
 *** in mailsync     void* __1::__thread_proxy(void*)
 *** 0x7fff73e8d109  _pthread_start
 *** 0x7fff73e88b8b  thread_start
 ***

**Comment by bengotow** [comment]
Hey this is awesome, thank you so much for posting @ChrisFab16! This has been happening super sporadically but the previous crash reports have been on Windows where (for super complicated C++ reasons) we don't get as accurate stack traces. I think I can get this fixed in the next release, will look into it ASAP.

**Comment by jshum** [comment]
Having the same issue. Also same the scenario where only the primary gmail account fails, but second gmail account, third fastmail account does not fail.

Thank you for looking into this!

**Comment by acyment** [comment]
Same issue here. Manjaro Gnome 20. Mailspring 1.7.6-e94bb759. Account provider is Gmail too. Not much detail in the log:

### 17972 [2020-05-05 11:17:13.848] [background] [info] Fetching XOAuth2 access token from Gmail for e5f44254
17972 [2020-05-05 11:17:13.849] [metadata] [info] Metadata delta stream starting...
17972 [2020-05-05 11:17:14.069] [background] [info] Marking all folders as `busy`
17972 [2020-05-05 11:17:14.070] [background] [info] Syncing folder list...
17972 [2020-05-05 11:17:16.712] [background] [info] Syncing folder list...
17972 [2020-05-05 11:17:17.239] [background] [info] syncFolderUIDRange for [Gmail]/All Mail, UIDs: 348220 - 348670, Heavy: false
17972 [2020-05-05 11:17:19.024] [background] [info] - remote=400, local=400
17972 [2020-05-05 11:17:19.864] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/All Mail: modseq 13304096 to 13304096, uidnext 348670 to 348670
17972 [2020-05-05 11:17:20.496] [background] [info] Sync loop deleting unlinked messages with phase 2.
17972 [2020-05-05 11:17:20.681] [background] [warning] [SLOW] Transaction=deleteMessagesStillUnlinked > 60ms (185355 microseconds, 12 waiting to aquire)
17972 [2020-05-05 11:17:20.681] [background] [info] Sync loop complete.
17972 [2020-05-05 11:17:20.699] [foreground] [info] Idling on folder [Gmail]/All Mail
17972 [2020-05-05 11:17:28.842] [metadataExpiration] [info] Scanning for expired metadata
17972 [2020-05-05 11:17:28.842] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
17972 [2020-05-05 11:17:38.944] [calContacts] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** too many SQL variables
 ***

17972 [2020-05-05 11:17:38.968] [calContacts] [critical]  *** Stack trace:
 ***   clone
 ***

Thanks!

**Comment by bengotow** [comment]
Hey folks! Thanks for the help triaging this one—I was able to track it down (and actually spent like an entire day improving the quality of our Windows stack traces, so hopefully this will be easier for more folks to report in the future...) Will ship the fix soon since it looks like this is impacting quite a few people!

**Comment by arthurlogilab** [comment]
Hey, I'm getting something similar on ubuntu but with less details 

```
6790 [2020-05-20 10:44:14.883] [calContacts] [critical] 
 ***
 *** An exception occurred during program execution: 
 *** (unknown exception details)
 ***

6790 [2020-05-20 10:44:14.908] [calContacts] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***
```
Indeed I probably have *a lot* of contacts that mailspring is finding in my emails. Editing the contact lists before it crashes seems to be working and is blocked after the crash happens. 

Is it the same bug ? Should I open a new issue ?

**Comment by JpMaxMan** [comment]
Any updates on when this might go live or a work around?  Having the same issue on Manjaro and it pretty much prevents MailSpring from working completely as the sync dies and I have to reconnect to get it to try again.

40132 [2020-05-20 06:32:12.251] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/All Mail: modseq 28584793 to 28584793, uidnext 698966 to 698966
40132 [2020-05-20 06:32:12.789] [background] [info] Sync loop deleting unlinked messages with phase 2.
40132 [2020-05-20 06:32:12.892] [background] [warning] [SLOW] Transaction=deleteMessagesStillUnlinked > 60ms (103210 microseconds, 4 waiting to aquire)
40132 [2020-05-20 06:32:12.892] [background] [info] Sync loop complete.
40132 [2020-05-20 06:32:13.221] [foreground] [info] Idling on folder [Gmail]/All Mail
40132 [2020-05-20 06:32:22.725] [metadataExpiration] [info] Scanning for expired metadata
40132 [2020-05-20 06:32:22.725] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
40132 [2020-05-20 06:32:30.636] [calContacts] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** too many SQL variables
 ***

40132 [2020-05-20 06:32:30.676] [calContacts] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

**Comment by acyment** [comment]
I’m basically using a downgraded version these days. It became unusable for me with this bug. 

Alan

**Comment by acyment** [comment]
I've been using 1.7.8 and so far the bug has not reappeared. Thanks!!!

**Comment by ChrisFab16** [comment]
Confirmed fixed. Issue closed. Thanks!

**Comment by TarunDhirta** [comment]
![image](https://user-images.githubusercontent.com/41358631/157719705-780aeeea-2cdf-4691-9a60-a4946572f542.png)
error with the latest version .
