### ISSUE TITLE
Email Scheduling 

### ISSUE THREAD

**Issue by ckkibet** [Foundry376/Mailspring#1954]
##### What is the behavior you're seeing?
When I schedule emails to be sent at a particular time and or date and exit the app, the email wont be sent even if the schedule requirement has been met until such a time I reopen the application. 

##### What email provider (Gmail, Exchange, etc.) are you trying to use?
Gmail 

##### What operating system are you using?
Fedora 32 (Workstation Edition)

##### What version of Mailspring are you using?
1.7.6-e94bb759

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No. The issue happens regardless of attachment, message and or signature.

**Comment by CodeMouse92** [comment]
This is addressed here: https://community.getmailspring.com/t/does-mailspring-need-to-be-running-to-send-scheduled-emails/277
