### ISSUE TITLE
Can't get oauth token for gmail accounts

### ISSUE THREAD

**Issue by krasi-georgiev** [Foundry376/Mailspring#1957]
#### What is the behavior you're seeing?
Lost connection to all Gmail accounts

##### What email provider (Gmail, Exchange, etc.) are you trying to use?
gmail

##### What operating system are you using?
ubuntu

##### What version of Mailspring are you using?
1.7.6

tried authenticating, but the auth window also gets stuck
also can't add a new Gmail account

```
3203 [2020-05-01 12:20:31.082] [metadata] [info] Encountered error: {"debuginfo":"https://id.getmailspring.com/deltas/c8bfb684/head","key":"Timeout was reached","retryable":true,"what":"std::exception"}. Will retry in 300 sec.
3203 [2020-05-01 12:21:51.118] [background] [info] Fetching XOAuth2 access token from Gmail for c8bfb684
3203 [2020-05-01 12:22:11.170] [background] [info] Sleeping after exception: {"debuginfo":"https://www.googleapis.com/oauth2/v4/token","key":"Timeout was reached","retryable":true,"what":"std::exception"}
3203 [2020-05-01 12:24:11.170] [background] [info] Fetching XOAuth2 access token from Gmail for c8bfb684
3203 [2020-05-01 12:24:31.224] [background] [info] Sleeping after exception: {"debuginfo":"https://www.googleapis.com/oauth2/v4/token","key":"Timeout was reached","retryable":true,"what":"std::exception"}
3203 [2020-05-01 12:25:51.111] [metadata] [info] Encountered error: {"debuginfo":"https://id.getmailspring.com/deltas/c8bfb684/head","key":"Timeout was reached","retryable":true,"what":"std::exception"}. Will retry in 300 sec.
3203 [2020-05-01 12:26:31.224] [background] [info] Fetching XOAuth2 access token from Gmail for c8bfb684
3203 [2020-05-01 12:26:51.278] [background] [info] Sleeping after exception: {"debuginfo":"https://www.googleapis.com/oauth2/v4/token","key":"Timeout was reached","retryable":true,"what":"std::exception"}
```

**Comment by krasi-georgiev** [comment]
I just tried complete settings reset from the menu and this didn't help either.

**Comment by krasi-georgiev** [comment]
just tried a complete reinstall and also deleting .config/Mailpspring folder and same result.

**Comment by krasi-georgiev** [comment]
just tried 1.7.5 the same result.

**Comment by krasi-georgiev** [comment]
It all started working as normal again without any changes on my end. Does mailspring depend on some external service hosted on the mailspting servers that wasn't working?

**Comment by krasi-georgiev** [comment]
no response closing

**Comment by CodeMouse92** [comment]
Hi @krasi-georgiev,

Sorry for the radio silence. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

There was an AWS service interruption for Mailspring in *December*, but I doubt this would have been related. From what you describe, it actually sounds like Google was having the problem.

If you do have any further problems, please report it on our brand new [Discourse community](https://community.getmailspring.com). We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you on Discourse soon...and hopefully for reasons other than your email giving you fits. :wink:
