### ISSUE TITLE
Folder names on the back button in single pane mode are incorrectly capitalized

### ISSUE THREAD

**Issue by agesome** [Foundry376/Mailspring#196]
Hello.

With folder names that contain words in ALL CAPS, they are displayed differently on the back button from viewing an email in single pane mode; also folders with all lowercase are capitalized.

Examples: "RTC" -> "Rtc", "IT Maintenance" -> "it Maintenance"

![back button](https://user-images.githubusercontent.com/63224/31708144-d904ae4e-b3f6-11e7-9aee-891b383c6bf3.png)

Actually found the place where this is done: https://github.com/Foundry376/Mailspring/blob/9833d33b98fd183f0c6384c8ead660c24e70410e/app/src/sheet-toolbar.jsx#L87

Git blame says it was initially implemented so. I wonder why :)

##### Are there any related issues?
Could not find any.

##### What operating system are you using?
Windows 7

##### What version of Mailspring are you using?
1.0.5

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No - tested with IMAP and Office365

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Examples provided.

**Comment by bengotow** [comment]
Hey! Thanks for tracking this down! Definitely seems strange and I think it should maintain the user's initial case. I think we did this to specifically handle INBOX > Inbox, which is probably better implemented as a special case.
