### ISSUE TITLE
Bug: Can't restore default signature, can't re-create it either

### ISSUE THREAD

**Issue by squintgit** [Foundry376/Mailspring#1961]
**Describe the bug**
After deleting the default signature, I couldn't find a way to put it back. I wanted to edit the signature so it doesn't say "the best email app for work".. I wanted it to say "the best email app". I didn't see a way to edit the signature. When I create a new one, I don't see a way to add that text back either.

**To Reproduce**
1. Delete the default Mailspring signature
2. Try to restore it or recreate it

**Expected behavior**
I would have thought I could edit the default signature.

**Screenshots**
n/a

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version 10.14.6
 - Mailspring Version: 1.7.6

**Additional context** 
The default signature should be editable.  Not sure if a "Restore defaults" button is needed. Probably not. Just make signatures editable.

**Comment by bengotow** [comment]
Hey! It sounds like you may not be able to see the full signatures UI (maybe a window size issue?) You can edit the data that is used to create the signature in the "information" section beneath the editor:

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/1037212/80926754-c896f500-8d5e-11ea-95ac-2bc047d5bcb0.png">

The default signature just fills the "Title" field (though I think that if you edit it, it might remove the Mailspring "link" and that's something we should probably fix).

If you want full control over the signature, you can also click "Raw HTML" - the last template option on the right. When you choose that you can edit plain HTML beneath the preview.

Hope that helps!

![Uploading image.png…]()

**Comment by squintgit** [comment]
doh thanks
