### ISSUE TITLE
Billing error

### ISSUE THREAD

**Issue by anderskitson** [Foundry376/Mailspring#1966]
I don't know where else to post this, I have contacted mailspring support mutliple times, message you guys on twitter and no response. I got charged a yearly subscription for no reason. I was month to month and was about to cancel and I got charged for a year. I never signed up for a year and no one is helping here. If someone could contact me that would be great.

Thanks

**Comment by valentt** [comment]
Same here! I'm trying to get invoice but they aren't replying on any channels. Support tickets. emails and twitter to no use... Did you get any response in the mean time?

**Comment by CodeMouse92** [comment]
Hi @anderskitson,

Our deepest apologies for this. 2020 hit @bengotow pretty hard, and that brought all work on Mailspring to a halt. It has resumed now.

We're in the process of migrating to our new [Discourse community](https://community.getmailspring.com/) to better facilitate handling various issues. (You would not *believe* the sheer mass of email that is received, much of it irrelevant!) If this issue has not been resolved, please post to [Service Issues](https://community.getmailspring.com/c/service-issues/11), and I'll personally make sure it gets resolved.

Once again, sorry for the inconvenience. 2020 was not kind to any of us.

-Jason C. McDonald
Volunteer Community Manager
Mailspring
