### ISSUE TITLE
Personnal domain

### ISSUE THREAD

**Issue by jief666** [Foundry376/Mailspring#1968]
Hi,
I own a domain. So, I can send and receive emails at [whatever]@mydomain.com.
Is it possible to configure your software so I can change what's before '@' to whatever I like, before sending an email.
Currently, I would have to configure each email I use as a separate account.
Thanks.

**Comment by kyeb** [comment]
Is the "Aliases" functionality in the Accounts preferences what you're looking for?

**Comment by jief666** [comment]
I didn't install yet, so I'm not sure. But I'd say probably not. Because I don't want to declare an alias for each email address I use.
I'm giving you food for thought : imagine, in the configuration somewhere, you can enter *@domain.com to indicate you can receive all emails on that domain.
Then, you receive an email to foo1@domain.com. When you click "answer", foo1@domain.com is automatically used without the need of declaring an alias or anything.
If I create a new message, you can initialise the 'from' field with the address '*@domain.com', forcing the user to replace the '*' by whatever he wants.

**Comment by kyeb** [comment]
That seems like a very niche use case to me, although I do see how it could be useful. However, I think this kind of configuration would entirely break mailing lists. Most mailing lists (for example, list@domain.com) show the address of the list in the "to" field. If it worked the way you're suggesting, then it seems like replying to any email from a mailing list would attempt to send it "as" the mailing list, which doesn't make sense.

**Comment by jief666** [comment]
With the current configuration, if you reply, you use the configured address whatever there is in 'to', is that right ?
The real recipient address should be in the source of the email. Otherwise, how would it arrived.

I'm surprised it's niche use, for 10$ a year, it seems to me it should more common. How could I give my bank the same address email than a dodgy website I sometime register to.

That's ok. Was just asking.
