### ISSUE TITLE
Bug: adding attachements doesn't work in latest 1.7.6 version

### ISSUE THREAD

**Issue by valentt** [Foundry376/Mailspring#1977]
**Describe the bug**
I tried on several accounts (gmail, imap and smtp) to add attachements while sending email, both via in mail attachement icon and drag and drop method. Both methods don't work but also don't give any error.

Only once email is send I can create new reply and then add an attachement, but not from initial email.

So if you have message thread you can add attachement, but not in your first email which is very strange.

This is 100% reproducable on my linux machine with Mailspring 1.7.6

**Comment by maneandrea** [comment]
I haven't experienced this issue with Mailspring 1.7.6 and I am on Ubuntu 18.04 LTS. 
Are you using the snap package or the .deb package? If you switch between the two do you still experience the same problem?

**Comment by valentt** [comment]
I tried doing update of same version, without removing the package first. This did nothing.
On second try I removed package and then installed it again, this time attachments started to work as expected.
