### ISSUE TITLE
Snoozed folder appears as [Mailspring].Snoozed

### ISSUE THREAD

**Issue by agurz** [Foundry376/Mailspring#198]
![mailspring](https://user-images.githubusercontent.com/13837769/31722748-49ac88d2-b3f3-11e7-8c7a-de1c8cef6d35.PNG)

##### Are there any related issues?

...

##### What operating system are you using?
Windows 10 15063.674

##### What version of Mailspring are you using?
1.0.5

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

**Comment by Galaxias** [comment]
@agurz : is this still affecting you? I can't reproduce it using Mailspring 1.0.6.

**Comment by sprakash81** [comment]
I am seeing additional label [Mailspring]/Snoozed in my gmail account.  I'm using MailSpring 1.0.12

**Comment by bengotow** [comment]
Hey folks—this should be fixed in the next release. Mailspring does create a `Mailspring/Snoozed` folder to keep track of Snoozed emails, but it shouldn't appear anymore with the prefix in the sidebar.

**Comment by bengotow** [comment]
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.

**Comment by frijj2k** [comment]
I've installed latest version (1.5.3) today and having the same issue...  Any ideas why?

I wondered if it was because I already had a snoozed folder (from Spark) but checked with Roundcube and it doesn't exist so can't be that.

Cheers!

**Comment by WanderingRaven** [comment]
Same issue here.  The folder does not exist on my server (verified via Roundcube as above).  Version 1.5.3-420ce003.  I have another email program which I use to also access my email and it has a snooze option.  I am trying to get these two programs to sync.  The other snoozed messages are put into "Snoozed".  For some reason even when I delete via Roundcube as above, Mailspring keeps re-creating these Mailspring.Snoozed folders.

**Comment by Naks** [comment]
I also have this issue. Running Version 1.5.5 (1.5.5) on MacOS 10.14.3 (18D109).
