### ISSUE TITLE
Bug: Yahoo IMAP error for correctly configured MailSpring

### ISSUE THREAD

**Issue by GeorgeB5555** [Foundry376/Mailspring#1987]
**Describe the bug**
Version 1.7.6 returns a IMAP error even though the correct settings are in place for Mailspring after it was correctly configured since 6 May

**To Reproduce**
1. Install Mailspring 1.7.6.'
2. Set up Yahoo App password
3. Attempt to complete the Mailspring set up

**Expected behavior**
IMAP error doesn't occur

**Screenshots**

**Setup: (please complete the following information):**
 - OS: [e.g. macOS, Fedora Linux]
 - OS Version [e.g. 14]
 - Mailspring Version: ex: 1.6.2 (found in the app's menu)

**Additional context** 
Add any other context about the problem here. If this issue is related to a particular account or email service, be sure to mention it so this report is actionable!

**Comment by sudohainguyen** [comment]
I also have the same problem, hope this would be fixed soon

**Comment by Gab1960** [comment]
I have the same issue.
OS: MX Linux
OS version: 19.1
kernel: 4.19.0-6-amd64 x86_64
MailSpring version: 1.7.6
![yahoobug](https://user-images.githubusercontent.com/65460498/82125552-fb051100-97a6-11ea-9f01-db1ff4c5a0f4.png)

**Comment by bamco2020** [comment]
I have the exact same Mailspring and Yahoo connecting issue as well.  I have been using Mailspring with Yahoo for years and it worked fine until I installed Mailspring update 1.7.6.  Now I cannot connect Mailspring to Yahoo.  I did all the steps to connect to yahoo and still no go.  I contacted support, they responded with a general email telling me to do all the steps to connect Mailspring to Yahoo that does not work. I responded to them again but have not heard back.  I do not think they want to acknowledge they have a bug in their software for those using Mailspring with Yahoo.  I am using Windows 10.

**Comment by 233mhz** [comment]
Same error https://github.com/Foundry376/Mailspring/issues/1974

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
