### ISSUE TITLE
Erro: mailsync: 134

### ISSUE THREAD

**Issue by miletece** [Foundry376/Mailspring#1990]
Hello,

I can't sync my gmail.

![image](https://user-images.githubusercontent.com/26185606/82136275-4688e080-97e2-11ea-8aac-311495054ce3.png)

My program version is 1.7.6-e94bb759.

Information that may be relevant:

My system is Linux Mint 19.3.
The operating system is encrypted.

**Comment by bengotow** [comment]
Hey @miletece thanks for reporting this, can you try upgrading to the 1.7.7 release? I I believe this was fixed when we shipped the updated version of OpenSSL on Linux.

**Comment by jimifm** [comment]
version:1.7.8-13635bcf


Running database migrations
App load time: 167ms

{"error":null}
Manual update check (updates.getmailspring.com/check/linux/x64/1.7.8-13635bcf/57f78fa0-a13e-4169-b0a6-cf4b22b19878/stable) returned 204
{ [TypeError: Failed to fetch] message: 'Failed to fetch' } { pluginIds: [] }
Raven: undefined - undefined
Raven: undefined - undefined
{ Error: 发生了一个未知错误 (mailsync: 134)
    at ChildProcess._proc.on.code (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/mailsync-process.ts:227:25)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe._handle.close (net.js:606:12)
  message: '发生了一个未知错误 (mailsync: 134)',
  rawLog:
   '\nWaiting for Account JSON:\n\nWaiting for Identity JSON:\ninfo: Identity created at 1592516255 - using ID Schema 1\ninfo: Fetching XOAuth2 access token from Gmail for 87b61d35\ncritical: \n***\n*** Mailspring Sync \n*** An exception occurred during program execution: \n*** {"debuginfo":"https://www.googleapis.com/oauth2/v4/token","key":"SSL connect error","retryable":true,"what":"std::exception"}\n***\n\ncritical: \n***\n*** Mailspring Sync \n*** An exception occurred during program execution: \n*** {"debuginfo":"https://www.googleapis.com/oauth2/v4/token","key":"SSL connect error","retryable":true,"what":"std::exception"}\n***\n\ncritical: *** Stack trace (line numbers are approximate):\n*** ??:?  ValidateRequestResp(CURLcode, void*, string)\n*** ??:?  PerformRequest(void*)\n*** ??:?  PerformJSONRequest(void*)\n*** ??:?  MakeGmailOAuthRequest(string, string)\n*** ??:?  XOAuth2TokenManager::partsForAccount(shared_ptr)\n*** ??:?  MailUtils::configureSessionForAccount(mailcore::IMAPSession&, shared_ptr)\n*** ??:?  runTestAuth(shared_ptr)\n*** ??:?  main()\n***\n\ncritical: *** Stack trace (line numbers are approximate):\n*** ??:?  ValidateRequestResp(CURLcode, void*, string)\n*** ??:?  PerformRequest(void*)\n*** ??:?  PerformJSONRequest(void*)\n*** ??:?  MakeGmailOAuthRequest(string, string)\n*** ??:?  XOAuth2TokenManager::partsForAccount(shared_ptr)\n*** ??:?  MailUtils::configureSessionForAccount(mailcore::IMAPSession&, shared_ptr)\n*** ??:?  runTestAuth(shared_ptr)\n*** ??:?  main()\n***\n\n/usr/share/mailspring/resources/app.asar.unpacked/mailsync: line 5: 27614 Aborted                 SASL_PATH="$SCRIPTPATH" LD_LIBRARY_PATH="$SCRIPTPATH;$LD_LIBRARY_PATH" "$SCRIPTPATH/mailsync.bin" "$@"\n' } { pluginIds: [] }
Raven: 429 - undefined

**Comment by CodeMouse92** [comment]
@jimifm Are you still having this problem on Mailspring 1.8.0?

We also have this issue, although I suspect it's unrelated: https://community.getmailspring.com/t/cannot-connect-to-gmail-from-behind-vpn/421

**If you're still having this bug, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
