### ISSUE TITLE
Bug: Mailspring completely unresponsive - not able to reinstall on Ubuntu 20.04

### ISSUE THREAD

**Issue by weixelbaumer** [Foundry376/Mailspring#1992]
**Describe the bug**
Mailspring is not responding anymore on a Ubuntu 20.04 installation .. there seemed to have been oAuth issues accd. to logs before but now it is not reacting at all.

Tried re-installation a dozen times ... tried manual deletion several times but Mailspring won't come up... only showing that weird violet screen preview.

**To Reproduce**
1. Start Mailspring on Ubuntu 20.04 (???) well normally it worked
2. No application window appears
3. except in the small preview window you see this 

**Expected behavior**
Application should start.

**Screenshots**

![mailspring-clusterfuck](https://user-images.githubusercontent.com/2777906/82302916-8c000600-99ba-11ea-992d-42af8b7472c8.png)

**Setup: (please complete the following information):**
 - OS: Ubuntu 20.04
 - Mailspring Version: latest stable 1.7.6

**Comment by weixelbaumer** [comment]
Fixed with latest update

**Comment by weixelbaumer** [comment]
Reopened as new connection of Google Mail is not working.
![image](https://user-images.githubusercontent.com/2777906/82609989-e6b57f80-9bbd-11ea-8bde-f03ee2304d95.png)

**Comment by MechieCoder** [comment]
dkfsf
