### ISSUE TITLE
Bug: Cannot sign up. 

### ISSUE THREAD

**Issue by TimSYQQX** [Foundry376/Mailspring#1994]
The following error popped as clicked on sign up. Using Ubuntu 18.04, and installed from Snap. 

![Screenshot from 2020-05-20 17-15-46](https://user-images.githubusercontent.com/22300644/82498235-a66ed800-9abd-11ea-9a3b-ba52be001397.png)

**Comment by bengotow** [comment]
Hey @TimSYQQX  thanks for reporting this! It looks like this was happening briefly because our MySQL aurora cluster was performing a fail-over but it should be fixed now and I added some alerting to watch out for the underlying problem. Thanks,
