### ISSUE TITLE
Bug: Unable to subscribe to Mailspring Pro

### ISSUE THREAD

**Issue by squintgit** [Foundry376/Mailspring#2000]
**Describe the bug**
I wanted to subscribe to Pro, not so much because I need the features or unlimited amounts of the features that are limited in the free version, but because I just want to support the development of this app. I got this error when trying to do so at 5/21/20 at 12:01 PM CST:  "SequelizeDatabaseError: ER_OPTION_PREVENTS_STATEMENT: The MySQL server is running with the --read-only option so it cannot execute this statement"

**To Reproduce**
1. On macOS app, went to Preferences > Subscription
2. Clicked Get Mailspring Pro
3. Entered Payment Information then clicked Upgrade to Mailspring Pro button.
4. Payment Information was cleared (probably expected), and error showed (not expected)

**Expected behavior**
No error.

**Screenshots**
<img width="400" alt="Screen Shot 2020-05-21 at 12 02 05 PM" src="https://user-images.githubusercontent.com/11663794/82585319-6c541380-9b5b-11ea-8e38-f6714e65d178.png">

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version 10.15.4 (19E266)
 - Mailspring Version: 1.7.7 (1.7.7)

**Additional context** 
Let me know when I can upgrade!

**Comment by bengotow** [comment]
Hey @squintgit thanks for posting this, I appreciate you supporting Mailspring! I have been digging into this for an hour now and it's pretty wild—it looks like this error has been appearing sporadically a few hundred times an hour today. I use Amazon Aurora MySQL for the ID service, and it doesn't look like there was a failover event or anything so I'm a bit mystified. Going to reboot the database servers and keep an eye on this, but it's disconcerting for sure.

**Comment by squintgit** [comment]
Thanks @bengotow. There's a twist to this. :)

Looks like I actually did buy a subscription after doing the above steps earlier (one time - didn't try again later). I didn't receive any kind of email or anything, not sure if that is expected. But yeah, I had no idea the purchase went through.

**Comment by bengotow** [comment]
Just a heads up that I triggered a database failover and it seems to have fixed this. I've set up alerting on this particular error and I'll keep an eye out since it's still a little unclear how this happened, but you should be able to go through the flow now. 🙏 Thank you so much for bringing this to my attention!

**Comment by bengotow** [comment]
Oh interesting! I will pull up your records and make sure you didn't get billed twice, that's unusual but I guess it depends how far it got through the flow before trying to write to the database. Sorry  again for the hassle.
