### ISSUE TITLE
Bug: Authentication Error for School Office365 Email Account

### ISSUE THREAD

**Issue by isaisabored** [Foundry376/Mailspring#2002]
At present, I am unable to add my school email account to Mailspring. My school uses Office365 to run email accounts, and after the latest update I became unable to send emails. I attempted removing and adding the account again to see if it would work, but instead now Mailspring refuses to authenticate my account at all. I've tried Office365, Outlook, and IMAP, but none of them work. 

I'm using a Windows 10 Build 18363.836, and running Mailspring version 1.7.7-71504f2c.

**Comment by iceman3000** [comment]
Fixed by rolling back to Mailspring 1.7.6

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this - going to merge this into #1996. The fix has landed in master and I'll be shipping it soon!
