### ISSUE TITLE
Sync issue with gmail "too many SQL variables"

### ISSUE THREAD

**Issue by nikoneufeld** [Foundry376/Mailspring#2006]
##### What is the behavior you're seeing?
"Encountered an error while syncing niko.neufeld@gmail.com"

##### What email provider (Gmail, Exchange, etc.) are you trying to use?
gmail
##### What operating system are you using?
Linux superfeind 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

##### What version of Mailspring are you using?

(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)
1.7.6-e94bb759
##### Is the issue reproducible with a particular attachment, message, signature, etc?
n/a - the problem occurs systematically every 2 minutes or so. 
[mailsync-02c81192.log.gz](https://github.com/Foundry376/Mailspring/files/4666777/mailsync-02c81192.log.gz)

**Comment by nikoneufeld** [comment]
I should add that I have a very large inbox on gmail  / about 180k mails. In the synclog I always see the "too many SQL variables , C\++ exception error"

**Comment by bengotow** [comment]
Hey @nikoneufeld  thanks for reporting this! This was actually fixed in the 1.7.7 release, could you try upgrading to that one and see if it resolves the issue for you?

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
