### ISSUE TITLE
Link & Opening is tracked when it's disabled / Free user

### ISSUE THREAD

**Issue by tchiotludo** [Foundry376/Mailspring#201]
If just send my first email with mailspring.

I'm free account / I click on the new message modal to disable link tracking and opening tracking 
`https://link.getmailspring.com/link/local-{{uid}}@{{machine}}/0?redirect={{my-link}}`
The pixel tracker is also present on email.

The worst : 
![image](https://user-images.githubusercontent.com/2064609/31736679-b647dcf6-b445-11e7-954b-0ffee82a95de.png)

If I'm a free user and don't want link tracking, so you must follow the user requirement.

**Comment by bengotow** [comment]
Hey! You're welcome to disable these features: https://foundry376.zendesk.com/hc/en-us/articles/115002228092

**Comment by tchiotludo** [comment]
It just the trouble !! I disabled it, but the mail was tracked, it's the main reason of this issue.
I reply to this email and the reply was also tracked when I disabled it on new email window
