### ISSUE TITLE
No sync with Windows 10 on version 1.7.7

### ISSUE THREAD

**Issue by playforvoices1** [Foundry376/Mailspring#2012]
Just installed the recent version of Mailspring (1.7.7) on my Windows 10 machine. After the update the app isn't able to sync mails. I get a warning that Mailspring is offline. 

I reinstalled the version 1.7.6 and it works well. Please check this bug. :)

**Comment by bengotow** [comment]
Hey @playforvoices1 - thanks for posting this. What email provider / service do you use? Mailspring 1.7.7 upgrades the app to use a newer version of OpenSSL, so it's possible that caused a problem for you, but I'd be kind of surprised.

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this - going to merge this into #1996. The fix has landed in master and I'll be shipping it soon!

**Comment by playforvoices1** [comment]
Hi @bengotow 

With the recent version of MS (1.7.8) the problem continues to exist on my Windows 10 machine. I've to downgrade to version 1.7.6 then MS works well.

**Comment by playforvoices1** [comment]
Howdy @bengotow 
 
Can you fix these bug next time? I'm tired of reinstall the 1.7.6 version on Windows to receive and send my mails.
