### ISSUE TITLE
Bug: Incorrect time when receiving Zoom meetings

### ISSUE THREAD

**Issue by D4V3M0NK** [Foundry376/Mailspring#2024]
It appears that when I receive a Zoom meeting request from someone in a different timezone, the time for that meeting is incorrect when I read the invite in Mailspring, but when I review my calendar (Google), the meeting is scheduled correctly.  To be honest, I've not noticed this happen with other meeting providers, but I will keep an eye out for them.  

In the attached image, the scheduled time for the meeting is 9am PDT but as you can see, it appears as 11am PDT in Mailspring. When I review my Google calendar, it appears as 9am PDT. The email originated from someone located in the Central time zone, two hours ahead of my (Pacific) time zone.

![Screenshot from 2020-05-26 11-47-57](https://user-images.githubusercontent.com/7572742/82940057-20cdab00-9f49-11ea-905e-a5a3a1c0306c.png)

**Setup: (please complete the following information):**
 - OS: Ubuntu 18 Desktop
 - Mailspring Version: ex: 1.7.8 (13635bcf)

**Comment by BenoitDuffez** [comment]
Same on my setup, Elementary OS (latest) with the latest snap available today for Mailspring.

This is what I received. The sender is in Miami (EDT), the mail server is in France (CEST) and I am in Los Angeles (PDT).

```
Return-Path: <...redacted....>
Delivered-To: ...redacted....
Received: from ...redacted....
	Wed, 27 May 2020 20:10:28 +0200 (CEST)
From: ...redacted....
To: ...redacted....
Subject: Jove <> Kerlink
Date: Wed, 27 May 2020 14:10:26 -0400
Message-ID: <...redacted....>
MIME-Version: 1.0
Content-Type: text/calendar; method=REQUEST;
	charset="utf-8"
Content-Transfer-Encoding: 8bit
X-Mailer: Microsoft Outlook 16.0
Thread-Index: ...redacted....
Content-Language: fr
X-Alinto-Spam: NO (/)

BEGIN:VCALENDAR
PRODID:-//Microsoft Corporation//Outlook 16.0 MIMEDIR//EN
VERSION:2.0
METHOD:REQUEST
X-MS-OLK-FORCEINSPECTOROPEN:TRUE
BEGIN:VTIMEZONE
TZID:Eastern Standard Time
BEGIN:STANDARD
DTSTART:16011104T020000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010311T020000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;CN=...redacted....
ATTENDEE;CN=...redacted....
CLASS:PUBLIC
CREATED:20200527T181016Z
DESCRIPTION: \n\n \n\n_________...redacted....
DTEND;TZID="Eastern Standard Time":20200528T170000
DTSTAMP:20200527T181016Z
DTSTART;TZID="Eastern Standard Time":20200528T160000
LAST-MODIFIED:20200527T181016Z
LOCATION:...redacted....
ORGANIZER;CN=...redacted....
PRIORITY:5
SEQUENCE:3
SUMMARY;LANGUAGE=fr:...redacted....
TRANSP:OPAQUE
UID:...redacted....
X-ALT-DESC;FMTTYPE=text/html:...redacted....
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MS-OLK-APPTLASTSEQUENCE:2
X-MS-OLK-APPTSEQTIME:20200522T123004Z
X-MS-OLK-AUTOSTARTCHECK:FALSE
X-MS-OLK-CONFTYPE:0
END:VEVENT
END:VCALENDAR
```

The real time is 4-5pm EDT:
```
DTSTART;TZID="Eastern Standard Time":20200528T160000
DTEND;TZID="Eastern Standard Time":20200528T170000
```
It is displayed at 16:00 PDT (that's the time EDT) but the actual time will be 13:00 PDT.

![image](https://user-images.githubusercontent.com/802209/83072243-44fdba80-a023-11ea-9ae8-cef285b81b8e.png)

Either show 16:00 EDT or 13:00 PDT

**Comment by iveselin** [comment]
Probably caused by https://github.com/Foundry376/Mailspring/issues/2039
