### ISSUE TITLE
consider about update ROADMAP.md?

### ISSUE THREAD

**Issue by XenoAmess** [Foundry376/Mailspring#2025]
It is already year 2020 now.
So I think it is a time to renew/update your ROADMAP.md

**Comment by CodeMouse92** [comment]
2020 prevented much development work on Mailspring, but rest assured, development has resumed! **In fact, we're working on the new roadmap right now.** All future updates will be here: https://community.getmailspring.com/

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
