### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by gocarlos** [Foundry376/Mailspring#203]
##### Are there any related issues?

...

##### What operating system are you using?
... Ubuntu 

##### What version of Mailspring are you using?
... 1.0.5

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
... No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
... IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?

... Try to add IMAP account, if it fails, change the SMTP from STARTLS to SSL --> Add Account -> Segmentation Fault

--
![screenshot from 2017-10-18 22-37-50](https://user-images.githubusercontent.com/1331762/31741638-3fbe484e-b455-11e7-9db2-5d11d3f80b30.png)

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by henres** [comment]
Same here on Ubuntu 17.04 and mailspring 1.0.5

**Comment by ElectricCookie** [comment]
This happened to me when I was entering the wrong port

**Comment by LiHRaM** [comment]
I had this one too, Ubuntu 17.10 and Mailspring 1.0.6.

**Comment by adelplace** [comment]
Same issue on Mint Sarah and Mailspring 1.0.6.

**Comment by trustin** [comment]
Happened to me when domain name resolution failed.

**Comment by massenz** [comment]
Ubuntu 17.10 - not sure about Mailspring version, but updated very recently (last couple of weeks) to the latest.

I just get segfault when starting Mailspring:
```
$ mailspring 
Segmentation fault
```

**Comment by massenz** [comment]
Removed and re-installed 1.0.8, fixed the issue.
Again not sure what version I had before.

Also, as a side note, if you guys made it easier to copy/paste the version number it'd be easier to report it here.

**Comment by bengotow** [comment]
Hey folks - we haven't seen any occurrences of this for a few months so I'm going to close this issue.

**Comment by pkvk** [comment]
Hi!

I have the same issue on arch linux (mailspring-1.3.0-1):

>  mailspring 
> [1]    5569 segmentation fault (core dumped)  mailspring
