### ISSUE TITLE
Unable to build Mail spring code in windows

### ISSUE THREAD

**Issue by kanji-keraliya** [Foundry376/Mailspring#2034]
**Describe the bug**
Unable to complete npm install command

**here is logs**

> node scripts/postinstall.js

-- Clearing app/node_modules --

-- Running npm install in ./app with electron config --

> windows-quiet-hours@1.2.7 install D:\Mailspring-master\app\node_modules\windows-quiet-hours
> node-gyp rebuild

D:\Mailspring-master\app\node_modules\windows-quiet-hours>if not defined npm_config_node_gyp (node "D:\Mailspring-master\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 403 status code downloading arm64 node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\install.js:335:22)  
gyp ERR! stack     at Request.emit (events.js:215:7)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1066:10)
gyp ERR! stack     at ClientRequest.emit (events.js:210:5)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:456:22)
gyp ERR! stack     at TLSSocket.emit (events.js:210:5)
gyp ERR! stack     at addChunk (_stream_readable.js:308:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:289:11)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Mailspring-master\app\node_modules\windows-quiet-hours
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

> runas@3.2.5 install D:\Mailspring-master\app\node_modules\runas
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=4.2.2 runtime=electron arch=x64 platform=win32)

D:\Mailspring-master\app\node_modules\runas>if not defined npm_config_node_gyp (node "D:\Mailspring-master\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 status code downloading arm64 node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\install.js:335:22)
gyp ERR! stack     at Request.emit (events.js:215:7)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1066:10)
gyp ERR! stack     at ClientRequest.emit (events.js:210:5)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:456:22)
gyp ERR! stack     at TLSSocket.emit (events.js:210:5)
gyp ERR! stack     at addChunk (_stream_readable.js:308:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:289:11)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Mailspring-master\app\node_modules\runas
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-quiet-hours@1.2.7 (node_modules\windows-quiet-hours):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-quiet-hours@1.2.7 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! runas@3.2.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-05-30T11_08_05_701Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mailspring-root@0.0.1 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mailspring-root@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-05-30T11_08_05_975Z-debug.log

**Comment by andyliuhaowen** [comment]
If you cannot build, this is likely a build issue, rather than a bug. Please kindly change its label.

**Comment by kanji-keraliya** [comment]
Downgrade node js to version **11.15.0** working for me
