### ISSUE TITLE
Bug: Timezone handling for event invites is incorrect

### ISSUE THREAD

**Issue by liam-wiltshire** [Foundry376/Mailspring#2039]
**Describe the bug**
When you receive an event invite, the time displayed is in the _senders_ local time, but the timezone displayed is the _received_ timezone.

For example, if I, as the sender am in Bulgaria (EEST (UTC+3)), and I send an invite for an event at 4pm EEST to a recipient in the UK (BST (UTC+1)), the recipient should see the invite time as 2pm BST. However instead it displays 4pm BST (the senders time, but with BST as the timezone).

Have logged into GMail and confirmed that, in GMail, the correct time is displayed (2pm BST):

![Incorrect time shown in Mailspring](https://user-images.githubusercontent.com/10179637/83633001-1ee29800-a598-11ea-84c4-0d71dc7fce13.png)

![Correct time shown on GMail](https://user-images.githubusercontent.com/10179637/83633043-36218580-a598-11ea-97c8-b3cfdf54eb61.png)

**To Reproduce**
1. Send an invite (likely _not_ by using Mailspring) from one timezone (e.g. EST)
2. Receive the invite via Mailspring with your setup to use a different timezone from the original invite (e.g. PST)
3. See the time as being the invite time from the sender, but suffixed with your local timezone.

**Expected behavior**
Either a) The time should be shown using the senders time _and_ timezone (not ideal), or the time should be showng and converted to your timezone (preferable).

**Screenshots**
See above

**Setup: (please complete the following information):**
 - OS: Fedora
 - OS Fedora release 28 (Twenty Eight)
 - Mailspring Version: 1.7.6

**Additional context** 
Have only tested _receiving_ invites into a GSuite/GMail account -  haven't tested sending them, or seeing if the same issue exists when receiving invites through other mail providers, although I cannot see why it wouldn't.

**Comment by tecoholic** [comment]
More confirmation

![image](https://user-images.githubusercontent.com/383862/87323181-0f1d8280-c54c-11ea-9209-209e5feca18e.png)

**Comment by 3v1n0** [comment]
Damn it, this made me wake me up early in the morning for an event happening way later!

![immagine](https://user-images.githubusercontent.com/345675/100061501-71f22500-2e2e-11eb-8b92-d103dc6453c2.png)

**Comment by felipecustodio** [comment]
Confirmation that this issue is still happening,
on timezone (GMT-3).

## Setup:
OS: Windows 10
Mailspring Version: 1.78

## Screenshots

On Mailspring:

![image](https://user-images.githubusercontent.com/4261743/104309458-f406dd80-54b0-11eb-95d1-70b985ab7975.png)

When downloading the invite or accepting the meeting in Microsoft Teams:
![image](https://user-images.githubusercontent.com/4261743/104309512-0c76f800-54b1-11eb-9fe0-17a2b3052508.png)

**Comment by 3v1n0** [comment]
This is actually fixed by https://github.com/Foundry376/Mailspring/pull/2093 but it has not been released yet (it works using a more recent build).

**Comment by Phylu** [comment]
@CodeMouse92 This issue can be closed as of the most recent release.

**Comment by CodeMouse92** [comment]
Resolved in Mailspring 1.8.0 via #2093. 🎉
