### ISSUE TITLE
[Feature request] Apply mail rules on mailbox sync

### ISSUE THREAD

**Issue by Andrewsudarikov** [Foundry376/Mailspring#204]
##### Are there any related issues?

...

##### What operating system are you using?
Elementary OS 0.4.1

##### What version of Mailspring are you using?
1.0.5

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
... Every day I get 50+ emails that are not spam and need to be organised into 10+ folders/labels. Even though the sorting rules work, I need to go to Preferences pane every time to activate them. This is highly inconvenient.
Could you design the mail sequence to apply rules _automatically_ after mailbox is synced? This would be very useful. Thanks!

**Comment by agurz** [comment]
Related to #59 and #146

**Comment by bengotow** [comment]
Hey thanks - this should be fixed soon. Mail rules are supposed to run automatically but aren't. @agurz thanks for tying this back to #59!
