### ISSUE TITLE
Bug: Sidebar UI - No apparent way to close Contact Previews

### ISSUE THREAD

**Issue by ekeppel** [Foundry376/Mailspring#2051]
**Describe the bug**
After selecting an email and clicking 'try now' to view a contact preview in the sidebar, there is no apparent way to close it.  I've restarted the app, and it continues to show, taking up screen real estate.  This happens in all accounts.

**To Reproduce**
1. Select an e-mail from your inbox
2. Open the sidebar
3. Click on 'try now' to view Contact Preview
4. The user has no apparent way to close or collapse the displayed contact information

**Expected behavior**

I think most users would expect a small UI element (perhaps a small up/down chevron) that, when clicked, expands and collapses the contact information.

**Setup: (please complete the following information):**
 - OS: Windows 10
 - Build 1909
 - Mailspring Version: 1.7.8-13635bcf  (FREE Version)

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
