### ISSUE TITLE
Mailspring unresponsive even after three weeks and multiple emails

### ISSUE THREAD

**Issue by valentt** [Foundry376/Mailspring#2056]
I'm a paying subscription member, and the lack of support from Mailspring is shocking. I send multiple support requests regarding issue with the licence via email and support ticket system but got no reply!

Is anyone taking seriously paying customers or you just don't care?!?

**Comment by CarlosRebolledo** [comment]
Muy lamentable lo que ocurre. Después de la última actualización, que no representa un gran avance desde el punto de vista de dar certeza acerca de la continuidad de este cliente de correo, no queda más que esperar, sin perjuicio del legítimo derecho a pensar que no hay interés real en dar continuidad a este correo.

**Comment by jalal** [comment]
It's good to hear about this. I was planning to become a paying subscription member but after multiple attempts to try and contact Mailspring (I had some questions) and no response, I will give up. A pity, it is a nice client overall...

**Comment by compuguy** [comment]
Agreed. Its disappointing that development of this app has mostly stalled...😢

**Comment by CarlosRebolledo** [comment]
It is disappointing to see that the months go by and there are no answers or less indications about the present and future of Mailspring, except, of course, that there is no answer whatsoever about it.

**Comment by CarlosRebolledo** [comment]
Sigo esperando, aunque con menos esperanzas, una respuesta o señal de vida de Mailspring.

Ben parece estar más preocupado y ocupado en otras cosas

**Comment by CodeMouse92** [comment]
The events of 2020 brought Mailspring development to a temporary halt. Develompent *has* resumed.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)
