### ISSUE TITLE
Feature Request: Customer Support for PRO users

### ISSUE THREAD

**Issue by zonked13** [Foundry376/Mailspring#2069]
It's very frustrating for those of us supporting Mailspring paying $8 and no customer support service.

**Solution: If you're not going to have any type of customer service for the people who are paying for your app monthly, then simply make the features FREE and that way there's no need to have a customer service team (especially a webpage dedicated to support questions) in place and instead just answer any questions in regards to issues here on GitHub. 

**Describe alternatives you've considered**
Make all PRO features free indefinitely, or until you have a proper customer support team in place that actually answers questions.

**Additional context** N/A

**Comment by CodeMouse92** [comment]
Mailspring Pro subscriptions cover the costs of the servers and APIs necessary to provide those features; without subscriptions, those features would simply not be possible, full stop.

Mailspring is an independent software project, and its primary developer works on it in addition to a full time job. It is for this reason that Mailspring has *never* promised Premium Support as part of Pro.
