### ISSUE TITLE
Issue with University's Office365 account syncing.

### ISSUE THREAD

**Issue by SG14-96** [Foundry376/Mailspring#207]
##### Are there any related issues?

...

##### What operating system are you using?
MacOS

##### What version of Mailspring are you using?
1.0.5

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! Gonna need more info unfortunately - how is it not syncing? Does it start and then fail, not sync at all? Do you see your folders in the sidebar?

**Comment by SG14-96** [comment]
Everything shows up, it just gives me an error on the left side pane.
