### ISSUE TITLE
Feature Request: UX ideas from Hey.com

### ISSUE THREAD

**Issue by eshnil** [Foundry376/Mailspring#2071]
There are some good UI/UX ideas in Hey.com: [Features](https://hey.com/features/) , [How it works](https://hey.com/how-it-works/)

- New senders must be whitelisted via The Screener
- Reply Later and Set Aside queues.
- Feed view
- and more

Are there plans to bring any of these to Mailspring?

**Comment by CodeMouse92** [comment]
If you would like to see these features in Mailspring, please propose each relevant feature in a separate Feature Request on our [Discourse](https://community.getmailspring.com). That will enable each to be tracked, discussed, and considered in its own right.

For the record, we already offer Reply Later (Send Later in Mailspring Pro) and Set Aside (Snooze in Mailspring Pro) features.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
