### ISSUE TITLE
Bug: Search bar decentralized in Windows 10

### ISSUE THREAD

**Issue by allanmviana** [Foundry376/Mailspring#2074]
**Describe the bug**
The search bar is decentralized in Windows 10 2004
![Search bar in Windows](https://user-images.githubusercontent.com/29358641/85913705-6e218e80-b80d-11ea-9218-16b9b4ebb3d9.png)
**Setup:**
 - OS: Windows 10
 - OS Version 2004
 - Mailspring Version: ex: 1.7.8-13635bcf

**Additional context** 
Changing themes do not affect the search bar positioning.

**Comment by tilda** [comment]
CNR on Win 10 20H2, Mailspring 1.7.8-13635bcf

**Comment by CodeMouse92** [comment]
Unfortunately, I can't quite work out what you mean by "decentralized". The screenshot seems to show the search bar in the right position, at least to my eyes.

If you still believe this is a bug, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
