### ISSUE TITLE
Bug: Spam action is not working

### ISSUE THREAD

**Issue by ponyesteves** [Foundry376/Mailspring#2077]
When I right click a mail from inbox list and select from the menu `Marcar como correo no deseado` (mark as spam), nothing happens.  The account is Gmail account
 
**Expected behavior**
   I expect that this moves the mail to spam folder and report the spam.

**Setup: (please complete the following information):**
 - OS: Linux - Ubuntu 19.10 and also I reproduce on 20.04
 - Mailspring Version: ex: 1.7.8

**Additional context** 
I have 3 gsuite accounts and I from gmail, spam is not working on neither.

**Comment by CodeMouse92** [comment]
@ponyesteves Sorry for the delay in response. Do you have a Spam or Junk folder configured under Settings > Folders for the accounts in question? If not, set those and try the Mark As Spam feature again.

**If this does not solve the problem, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
