### ISSUE TITLE
Read Receipt Numbers

### ISSUE THREAD

**Issue by commseditor** [Foundry376/Mailspring#2079]
How to I get the specific read receipt report from mailspring? I have sent out an email last week and it's only shown 999+.
Is there any way to pull out the numbers?

**Comment by CodeMouse92** [comment]
A full explanation of how Read Receipts and their associated insights work can be found here: https://community.getmailspring.com/t/read-receipts-link-tracking-and-activity-reports/162

If that doesn't answer your question, please sign up for our Discourse and ask a new question under Help: https://community.getmailspring.com/c/help/7
