### ISSUE TITLE
Exporting account settings (signatures & aliases)

### ISSUE THREAD

**Issue by AbiertaMente** [Foundry376/Mailspring#208]
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

I'm ussing an gmail account which manages every mail addresses and aliases of home and work, so I have several aliases and signatures for each account and mails i have, when I go to configure the same thing in laptop i have to do it again

I expected to get a mailspring ID and then configure my email and all its configuration in your database or anything like that, so if i log in again in a new mailspring client it could apply every settings i had, it could be great and useful, and it could be a full excuse to be happy creating a mailspring account

**Comment by patrickheeney** [comment]
It sounds like https://github.com/Foundry376/Mailspring/issues/44 is what you want?

**Comment by AbiertaMente** [comment]
Oh, looks so, didn't see it, sorry & thanks

**Comment by bengotow** [comment]
Thanks - merging this in to #44! This is definitely something we're hoping to do in the near future, at least for settings. (Transferring passwords through the cloud is something we'd need super clear messaging around.)
