### ISSUE TITLE
Bug: Read receipts not working in mailspring

### ISSUE THREAD

**Issue by MichelleOliver** [Foundry376/Mailspring#2083]
**Describe the bug**
A clear and concise description of what the bug is. Does it happen with all email accounts, or only a particular account and/or email message?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup: (please complete the following information):**
 - OS: [e.g. macOS, Fedora Linux]
 - OS Version [e.g. 14]
 - Mailspring Version: ex: 1.6.2 (found in the app's menu)

**Additional context** 
Add any other context about the problem here. If this issue is related to a particular account or email service, be sure to mention it so this report is actionable!

**Comment by MichelleOliver** [comment]
Please help! 
I upgraded my account and I still have no read receipts and now my emails are not even sending!

**Comment by aemmadi** [comment]
@MichelleOliver Can you try to edit your issue with appropriate information? Right now it is just the template for bug reports. 

Have you tried reinstalling mailspring on your device? How are your mailboxes configured?

**Comment by MichelleOliver** [comment]
With the exception of reinstalling Mailspring, I don’t know how to do answer these questions. I need someone to help me understand why it isn’t working, At this point, I am just looking for a new solution but the emails I sent and tracked I really need to know if there were received and read.

Is it impossible to have a call with someone?

 
Michelle Oliver
970-460-6288

**Comment by aemmadi** [comment]
From my understanding you sent emails earlier and you upgraded to the Pro version and you are wondering why you can't get read receipts on those emails?

If that's the case, the emails you send after you upgrade to Pro will start getting tracked. You can't view prior emails you send without and kind of tracking. 

I am on the free plan and I get about 5 emails per week that I can add read receipts and tracking to. Make sure you have the feature enabled. It should be on the bottom side of the email compose window. 

Just an FYI, I am not the owner/maintainer for this app so I may be wrong with the info above, I am just an avid user of this app. Good Luck!

**Comment by MichelleOliver** [comment]
Thank you so much for responding!

No, I upgraded first and then sent after enabling tracking by clicking on the eye in the compose window.

Michelle Oliver
970-460-6288

**Comment by MichelleOliver** [comment]
It is now working!

No idea why.


Michelle Oliver
970-460-6288

**Comment by aemmadi** [comment]
Awesome, glad to hear! If everything is all good then make sure to close this issue on github

**Comment by MichelleOliver** [comment]
This is driving me crazy! Now it isn’t working again. What is going on?


Michelle Oliver
970-460-6288

**Comment by CodeMouse92** [comment]
@MichelleOliver Sorry for the delay in response. 2020 really prevented much development work on Mailspring. I joined the project as a volunteer recently to help get on top of the GitHub Issues backlog.

What you're describing isn't a bug at all, but is actually completely normal. See this article on our new Discourse community, explaining what's going on:

https://community.getmailspring.com/t/read-receipts-not-working/473

We hope to see you there!
