### ISSUE TITLE
Bug: VS Code Debug Fails

### ISSUE THREAD

**Issue by jaullo** [Foundry376/Mailspring#2092]
**Describe the bug**
Trying to debug mailspring using vs code fails with message: attribute program does not exist (/home/xxx/xxx/mailspring/--dev

**To Reproduce**
1. Open latest vs code
2. Open mailspring folder
3. Debug -- Start debugging

**Expected behavior**
Debug starts and mailspring windows is shown

**Setup: (please complete the following information):**
 - OS: Debian

**Additional context** 
npm start directly in folder works ok

**Comment by CodeMouse92** [comment]
Simply put, I don't think the project has been configured for debugging with VSCode. If you configure it as such (in the `.vscode/` directory), you're welcome to share your configuration here: https://community.getmailspring.com/c/development/5
