### ISSUE TITLE
Some emails show up as (no subject) on Windows

### ISSUE THREAD

**Issue by billytcl** [Foundry376/Mailspring#21]
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
v1.0.0-20839f9b

--

**Bug?**

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Some email threads show up as (No Subject), even though gmail clearly shows them having a subject line. Body of email is OK. I can't figure out the common theme. See bottom of post for screenshots.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Shows correctly in Gmail

Mailspring:
![image](https://user-images.githubusercontent.com/10386511/31193382-cbb8001e-a8f8-11e7-8875-fa02e0c94fde.png)
![image](https://user-images.githubusercontent.com/10386511/31193408-dde80e1e-a8f8-11e7-9588-a0140ac1af40.png)

Gmail:
![image](https://user-images.githubusercontent.com/10386511/31193547-49acbfa0-a8f9-11e7-9f93-fd993d432901.png)
![image](https://user-images.githubusercontent.com/10386511/31193512-2dc822e8-a8f9-11e7-8555-f5650b085f22.png)

**Comment by fenrisbear** [comment]
Applies to me as well.

**Comment by bengotow** [comment]
Hey folks—could you open the developer console in Mailspring (Menu > Developer > Toggle Developer Tools), select one of the threads in the thread list with `(No Subject)` and then type this on the JavaScript console and paste the result here?

```
require('electron').clipboard.writeText(JSON.stringify({thread: $m.FocusedContentStore.focused('thread'), messagesSubjects: $m.MessageStore.items().map(m => m.subject)}, null, 2))
```

This will copy the thread object to the clipboard, as well as the subjects of each message on the thread. I'm curious to see whether all of the messages have no subject, or if it's just the thread that was created to hold the messages.

**Comment by fenrisbear** [comment]
```{
  "thread": {
    "id": "t:Traw4tyCUePc25FK6eGwJqJ4zxtohHiLbcZza7y7v",
    "aid": "fd698de4",
    "metadata": [],
    "subject": "",
    "unread": false,
    "starred": false,
    "v": 6,
    "categories": [
      {
        "id": "g4zAKFYqYLX793sXUEZoLxXXuWCXdFPgAAwQN3xxi",
        "aid": "fd698de4",
        "role": "all",
        "path": "[Gmail]/All Mail",
        "__cls": "Folder"
      },
      {
        "id": "ofanp2CQyg6mSCdCNNxjYUBpw6bc2EBYoKBSo2q8o",
        "aid": "fd698de4",
        "role": "inbox",
        "path": "INBOX",
        "__cls": "Label"
      }
    ],
    "folders": [
      {
        "id": "g4zAKFYqYLX793sXUEZoLxXXuWCXdFPgAAwQN3xxi",
        "aid": "fd698de4",
        "role": "all",
        "path": "[Gmail]/All Mail",
        "__cls": "Folder"
      }
    ],
    "labels": [
      {
        "id": "ofanp2CQyg6mSCdCNNxjYUBpw6bc2EBYoKBSo2q8o",
        "aid": "fd698de4",
        "role": "inbox",
        "path": "INBOX",
        "__cls": "Label"
      }
    ],
    "participants": [
      {
        "aid": "fd698de4",
        "email": "*************",
        "thirdPartyData": {},
        "__cls": "Contact"
      },
      {
        "aid": "fd698de4",
        "name": "Spotify",
        "email": "hello@spotify.com",
        "thirdPartyData": {},
        "__cls": "Contact"
      }
    ],
    "attachmentCount": 0,
    "lmrt": 1504888500,
    "lmst": null,
    "inAllMail": true,
    "__cls": "Thread"
  },
  "messagesSubjects": [
    ""
  ]
}
```

**Comment by billytcl** [comment]
{
  "thread": {
    "id": "t:EznLoEwNcVVVbHFD5CCyZ8DFiXzCYcrtVCmSatETC",
    "aid": "95cb0f9c",
    "metadata": [],
    "subject": "",
    "unread": false,
    "starred": false,
    "v": 7,
    "categories": [
      {
        "id": "WmzHGHmNqVZ2FR51PmHdfm7kMm9au27GLLAMzMPur",
        "aid": "95cb0f9c",
        "role": "all",
        "path": "[Gmail]/All Mail",
        "__cls": "Folder"
      },
      {
        "id": "DnZgxGbaeq5eHdyLhWgzMDG5Nd8ut75AFUUGZXTUg",
        "aid": "95cb0f9c",
        "role": "inbox",
        "path": "INBOX",
        "__cls": "Label"
      }
    ],
    "folders": [
      {
        "id": "WmzHGHmNqVZ2FR51PmHdfm7kMm9au27GLLAMzMPur",
        "aid": "95cb0f9c",
        "role": "all",
        "path": "[Gmail]/All Mail",
        "__cls": "Folder"
      }
    ],
    "labels": [
      {
        "id": "DnZgxGbaeq5eHdyLhWgzMDG5Nd8ut75AFUUGZXTUg",
        "aid": "95cb0f9c",
        "role": "inbox",
        "path": "INBOX",
        "__cls": "Label"
      }
    ],
    "participants": [
      {
        "aid": "95cb0f9c",
        "email": "******@gmail.com",
        "thirdPartyData": {},
        "__cls": "Contact"
      },
      {
        "aid": "95cb0f9c",
        "name": "Lief Storer",
        "email": "support@teespring.com",
        "thirdPartyData": {},
        "__cls": "Contact"
      }
    ],
    "attachmentCount": 0,
    "lmrt": 1507144383,
    "lmst": null,
    "inAllMail": true,
    "__cls": "Thread"
  },
  "messagesSubjects": [
    ""
  ]
}

**Comment by bengotow** [comment]
Hey folks—thanks for the debug info! It looks like both the messages and the threads are missing subjects which helps narrow this down a bit.

Is there any chance you use Apple Mail, or a mail client that supports "redirecting" or "bouncing" messages? If so, it'd be great if you could send a copy of one of these emails (maybe one that isn't sensitive) to `ben@foundry376.com`. Unfortunately, it needs to be a redirect / bounce — typically forwarding a message changes its contents. In Apple Mail you can do it like this:

![image](https://user-images.githubusercontent.com/1037212/31200728-f3d17572-a910-11e7-9179-236a99e7a721.png)

I'll add some additional logging to the next version of Mailspring so we can track this down better.

**Comment by bengotow** [comment]
Hey folks! It looks like I've been able to reproduce this thanks to #15. It seems this only happens on Windows and not on Mac OS X, but I have several emails where it's happening in my own inbox. Stay tuned. (Merging in #15)

**Comment by billytcl** [comment]
Just wanted to say thanks for being so responsive to the bugs! I don't think I've ever seen a faster followup.

**Comment by bengotow** [comment]
Hey—thanks @billytcl! Version 1.0.2 has been released and should fix this issue. Since your mailbox has already been synced, you'll need to go to Preferences > General and click the "Reset Email Cache" button at the bottom to force Mailspring to refetch the messages it couldn't parse before.

**Comment by kometchtech** [comment]
I deleted cache and confirmed that I confirmed that there was no problem with the Japanese display of the subject.
