### ISSUE TITLE
Bug: Occasional loss of ability to track an email  

### ISSUE THREAD

**Issue by quattroman** [Foundry376/Mailspring#2103]
I pay for the ability to track any email I originate or reply to.  On occasion, despite the feature being selected, the "no opens" tag dissapears once the mail or reply is physically sent.  Hence the abaility to track "opens" is lost.  I have attached a log of the event and have amaned the email address used to XXXXXXX@gmail.com (my email address) and XXXXXX@hotmail.com (the replied to email address).

Thanks

Peter
[mailspring.txt](https://github.com/Foundry376/Mailspring/files/4984439/mailspring.txt)

**Comment by CodeMouse92** [comment]
Open tracking works by embedding a 1x1 pixel transparent image at the bottom of the email, which is the industry-standard technique for this. When the image is loaded — meaning the email was opened — the Mailspring servers hosting the image can tell the resource (image) is being accessed, and report that fact back to your Mailspring client.

However, if the recipient has configured their client to *not* load images by default, the tracking image is never loaded. If it's not loaded, the Mailspring servers never find out that the email was opened. Some users prefer this; they don't like open tracking for privacy (or other) reasons.

You can learn more about how this works here: https://community.getmailspring.com/t/privacy-with-read-receipt-and-link-tracking/163/2

In any case, this is just how open tracking works, and thus isn't a bug. We appreciate you reporting it, though!

By the way, check out our new [Discourse community](https://community.getmailspring.com), which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you on Discourse soon!
