### ISSUE TITLE
Bug: IMAP yandex.ru - LOGIN invalid credentials or IMAP is disabled

### ISSUE THREAD

**Issue by bazhenovrussia** [Foundry376/Mailspring#2111]
----------IMAP----------
connect <mailcore::IMAPSession:0x7ffddcf1e4e0>
* OK Yandex IMAP4rev1 at sas2-1e59ad28a72c.qloud-c.yandex.net:993 ready to talk with ::ffff:89.222.174.138:38922, 2020-Aug-01 08:34:38, cYXlpv732Cg1
ssl connect imap.yandex.com 993 2
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
1 CAPABILITY
* CAPABILITY IMAP4rev1 CHILDREN UNSELECT LITERAL+ NAMESPACE XLIST BINARY UIDPLUS ENABLE ID AUTH=PLAIN AUTH=XOAUTH2 IDLE MOVE
1 OK CAPABILITY Completed.
connect ok
login
2 LOGIN "******@yandex.ru" *********
2 NO [AUTHENTICATIONFAILED] LOGIN invalid credentials or IMAP is disabled sc=cYXlpv732Cg1_010534_2-1e59ad28a72c

**To Reproduce**
Use yandex (yandex.ru) imap auth

**Setup: (please complete the following information):**
 - OS: Fedora 32
 - Mailspring Version: 1.7.8-13635bcf

**Comment by bengotow** [comment]
Hey there! Can you visit https://mail.yandex.com/#setup/client and make sure you've checked "enable IMAP" on that screen? You may also need to create an app password for Mailspring depending on the options you choose on that page.

I think Yandex changed their rules recently and I've added this link to our setup instructions too! Cheers 🙌

**Comment by Minashraf** [comment]
Still the same problem with me and yes I enabled the IMAP
![image](https://user-images.githubusercontent.com/46136768/96017013-beb70900-0e49-11eb-8ee4-4428ffdbdce6.png)

**Comment by simon-the-shark** [comment]
@Minashraf the problem is, that we can't use our normal yandex password. Go to https://passport.yandex.com/profile/ and create new app password for mail and then use it as your password in mainspring. Worked for me.

**Comment by CodeMouse92** [comment]
I've migrated this conversation to the Help section of our new Mailspring community! We would love to see you there, @Minashraf and @simon-the-shark.

https://community.getmailspring.com/t/imap-yandex-ru-login-invalid-credentials-or-imap-is-disabled/59

Bonus, if you sign up, we can reassign the question and answer to you two respectively. (Just ask a moderator to do that in a private message or comment on that thread.)
