### ISSUE TITLE
Bug: mail rules appear to be case sensitive

### ISSUE THREAD

**Issue by DanHartas** [Foundry376/Mailspring#2115]
**Describe the bug**
I have been using a mail rule automatically marking as read anything appearing in my inbox sent to "marketing@xxxxx.com" rather than directly to my address. It was only working part of the time, and on closer inspection I noticed that mail addressed to "marketing@xxxxx.com" was being caught by the rule, but mail addressed to "MARKETING@XXXXX.COM" was not.

**To Reproduce**
Steps to reproduce the behaviour:
1. Introduce a to equals rule with a lowercase email address marking all such emails as read.
2. Send test messages which give the email address in both lower and upper case.
3. Check which messages the rule has been successfully applied to.

**Expected behaviour**
I would expect a rule like this to be case-insensitive. Perhaps this was intentional, to allow users greater freedom to discriminate, but I can't imagine a use case for that, and presumably technically (however unlikely this is to matter) I would have to introduce rules for every variant of "MarKEtInG@XxXxx.cOm" to get the expected behaviour right now!

**Setup: (please complete the following information):**
 - OS: Kubuntu Linux
 - OS Version: 20.04.1 LTS (Focal Fossa)
 - Mailspring Version: 1.7.8-13635bcf

**Comment by bengotow** [comment]
Hey thanks for reporting this! I totally agree these rules, especially for the address fields, should be case insensitive. I'm putting together another release now, will see if I can fix this real quick 🙌

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
