### ISSUE TITLE
[Suggestion] Add ability to manage Contacts

### ISSUE THREAD

**Issue by applesea2** [Foundry376/Mailspring#212]
##### Are there any related issues?

...

##### What operating system are you using?
...
Windows 10
##### What version of Mailspring are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...
I'd like the ability to add and remove contacts and edit information like the name, phone number like the web versions of most email services. Consider creating an "addressbook" easily accessible through a click

**Comment by victortrac** [comment]
I'd love the ability to "blacklist" contacts/email addresses that were automatically added to the database. I guess Mailspring indexed a ton of email addresses based on my mailbox, so I've inadvertantly sent emails to folks' old email addresses after carelessly selecting their name from the dropdown.

**Comment by bengotow** [comment]
Related to #86

**Comment by bengotow** [comment]
Hey folks! I'm happy to announce that Mailspring 1.7.0 shipped earlier today, which includes a full address book accessible from **Window > Contacts** in the menu. Enjoy!
