### ISSUE TITLE
Bug: office365 permissions issue when adding account

### ISSUE THREAD

**Issue by wwood** [Foundry376/Mailspring#2129]
**Describe the bug**
Attempting to setup an office365 account, but cannot because I'm running into a permissions issue.

I have 2 other installs of mailspring where there was (and is) no issue, so it seems to be something particular to adding the account (or perhaps some change in my institution's setup since I setup previously)

```
<my email address>
Need admin approval
Mailspring
www.getmailspring.com

Mailspring needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it.
Have an admin account? Sign in with that account
Return to the application without granting consent 
```

**To Reproduce**
1. Installed mailspring (I'm on edge snap on Ubuntu 20.04 i.e. 1.7.8-052f6dd5)
2. Click office365 new account
3. Logged into my institution (QUT), this was accepted as far as I can tell. I clicked remember details when prompted.
4. Run into permissions issue, so cannot add the account to mailspring

Thanks in advance, ben

**Comment by flindeberg** [comment]
The server you are using is not configured to allow Mailspring. Talk to your admin.

**Comment by wwood** [comment]
Thanks. Sorry for not following up on this, but I managed to solve this not by talking to the admin, but by using non-edge mailspring. Can't rule out the possibility that the admin fixed something at the same time though.

**Comment by doctorjei** [comment]
While this isn't technically a "bug", it is something that could be solved. If you look at the way that the Linux "onedrive" client works (https://github.com/abraunegg/onedrive), you can set up a way to manually authenticate. I'll admit it's not ideal, but it would be nice to have some avenue for this.
