### ISSUE TITLE
Feature Request: Open-Source MailSync

### ISSUE THREAD

**Issue by thejustinwalsh** [Foundry376/Mailspring#2135]
I read the disclaimer, and am willing to help clean-up the mail-sync code so that it is easily build-able on all platforms it supports. Also I know plenty of C++ developers that are also web devs, and think that cleaning it up and publishing it would be beneficial to the community as a whole, as well as your support of the bugs specific to MailSync.

I love Mailspring, and would love to help. I've been professionally developing in C++ for over 12 years, and have a special knack for cross platform library building and best practices.

Thoughts?

**Comment by 3v1n0** [comment]
@bengotow Hey, given this was a commitment as per the README, would be best to do it now (as per #2231 outcome)?

The README why's for keeping this closed aren't really a valid explaination IMHO, given that

1) we don't have to care about code polishment 100%
2) CI failures aren't a problem, can be ignored as per now
3) Other developers can improve it

So please, just release it as it is, it's better to keep it in a place where others can improve it, instead that leaving it in in the dark where nobody can change the situation.

**Comment by CodeMouse92** [comment]
This is being discussed. There are multiple factors in play, beyond what has been previously outlined and discussed, but it's under active consideration. I'm a C++ developer (and a FOSS advocate) as well, and will be helping with the task *if* Mailspring ultimately open-sources the core.

Right now, there are some considerably bigger fish to fry. ;)

**Comment by CodeMouse92** [comment]
We're closing and locking this issue as part of our migration to Discourse. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

Please join the new community for the latest news, including decisions on the FOSS status of Mailspring: https://community.getmailspring.com/
