### ISSUE TITLE
Client must be relaunched for the first time to add Gmail Account

### ISSUE THREAD

**Issue by HugoReeves** [Foundry376/Mailspring#215]
I have come from Nylas mail, this product is great, thanks for keeping a well-maintained version alive. Its awesome to see a fast mail client that looks great across platforms.

Today I installed Mailspring on both my home PC and laptop, both are running **windows 10 creators update**. After installing the client, on the first launch, I created a Mailspring ID and then tried to connect my standard Gmail account. The connection process kept failing at the very end and the client directed me to this (help page)[https://foundry376.zendesk.com/hc/en-us/articles/115002012491]. The page is for Linux users, but the devices I am using are windows. After **restarting** the client I was able to connect my Gmail account as expected, without issue.

I have come across this issue on 2 windows PCs today, running the **latest windows build** from getmailspring.com/download. This issue may be caused by having Nylas mail still installed on both PCs but I'm not sure.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - I'm trying to reproduce this now and hopefully we can get it fixed in the next update.

**Comment by bengotow** [comment]
Hey! We just shipped 1.0.6 which should fix this — have a great weekend 🚀

**Comment by HugoReeves** [comment]
Thanks @bengotow I installed the latest build on ubuntu and the issue did not occur. This [issue](https://github.com/Foundry376/Mailspring/issues/216) seems to be very simmilar to the issue I was having on Windows 10. They may be related.
