### ISSUE TITLE
Bug: Can't install on Ubuntu 20.10

### ISSUE THREAD

**Issue by Pajn** [Foundry376/Mailspring#2154]
**Describe the bug**
The deb package depends on `gvfs-bin`, this package has long been deprecated and is no longer available in Ubuntu 20.10.
I can not see that any `gvfs-*` command line tools is used by mailspring so it might be as easy as just dropping `gvfs-bin` from https://github.com/Foundry376/Mailspring/blob/master/app/build/resources/linux/debian/control.in

Electron itself used `gvfs-bin` in version 2 which is why it might have been included in the first place, but since version 3 it has migrated to the newer and supported gio tools https://github.com/atom/atom/issues/17452#issuecomment-490037674

**Comment by JAZ-013** [comment]
I am also experiencing this.  I just upgraded to 20.10 now that it is officially release and no long have Mailspring installed.  Any chance this could be bumped up in priority?

**Comment by Code-Bases** [comment]
Hi.
Here's te solution for now:

In my case firstly I needed to resolve some other dependencies:
`sudo apt install libsecret-1-dev gconf2 python2 python-is-python2` 

And after that, just install it ignoring the gvfs-bin:
`sudo dpkg --ignore-depends=gvfs-bin -i mailspring-1.7.8-amd64.deb`

So far everything working perfect. In Ubuntu 20.10 package `gvfs-bin` was replaced by `gvfs, libglib2.0-bin` which are already installed, so technically we should be fine.

**Comment by jrodd96** [comment]
Can confirm the above solution works for me on Pop! OS 20.10. This also works for a handful of other applications that have the same dependency issue w/ `gvfs-bin` for now.

**Comment by jrodd96** [comment]
I would also like to add to the above solution if you are running the `aptitude` package manager, you are likely to encounter an error whenever you run `sudo apt-get upgrade` if you already had Mailspring installed before the upgrade:

`The following packages have unmet dependencies:
 mailspring : Depends: gvfs-bin but it is not installable`

The solution that I found was to manually edit `/var/lib/dpkg/status` (BE CAREFUL) and remove `gvfs-bin` from the list of dependencies for Mailspring.
Then run `sudo apt-get -f install` with no options to ensure the change has worked.

**Comment by ElSenor64** [comment]
I can confirm that this temporary workaround does work on POP!_os 20.10, and that jrodd96's fix for the dependency error also works great.

Thanks guys! I love this client and it's good to be up and using it again!

**Comment by bjoernhohe** [comment]
Same here switched to POP!OS 20.10 yesterday and the workaorund helped for now

**Comment by codehia** [comment]
Instead of removing `gvfs-bin` replacing the same with `libglib2.0-bin | gvfs-bin` also works.

**Comment by Vinod-1122** [comment]
> Hi. Here's te solution for now:
> 
> In my case firstly I needed to resolve some other dependencies: `sudo apt install libsecret-1-dev gconf2 python2 python-is-python2`
> 
> And after that, just install it ignoring the gvfs-bin: `sudo dpkg --ignore-depends=gvfs-bin -i mailspring-1.7.8-amd64.deb`
> 
> So far everything working perfect. In Ubuntu 20.10, package `gvfs-bin` was replaced by `gvfs, libglib2.0-bin` which are already installed, so technically we should be fine.
> 
> Let me know if it work for You.

It worked in installing slack desktop same error I had but after analysing u r tip above I had resolved with u r commands
