### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by fschaupp** [Foundry376/Mailspring#2155]
**Describe the bug**
The link to https://join-mailspring-slack.herokuapp.com/ seems broken. It's in the README.md on the top beneath the CICD Badges.

**To Reproduce**
1. Go to the main Page of Mailspring and scroll down to the Readme-Area of GitHub
2. The Link is shown as broken and when you click on it, the heroku page shows an application error

**Expected behavior**
A redirect to the slack space

**Comment by CodeMouse92** [comment]
We discontinued our Slack, and have updated the README accordingly.

Our new community is here: https://community.getmailspring.com/
