### ISSUE TITLE
Bug: Office 365 Incorrect password error for two different accounts

### ISSUE THREAD

**Issue by jabba2324** [Foundry376/Mailspring#2156]
**Describe the bug**
Office 365 Incorrect password error for two different accounts, one has MFA+ app password and another does not. I've tried all possible combinations of app and normal passwords.

**To Reproduce**
1. Select Add Office 365 Account
2. Enter correct email & password
3. Given incorrect password response, asked to view IMAP logs.

**Expected behavior**
Can connect to office 365 mailbox

**Screenshots**

**Setup: (please complete the following information):**
 - OS: [Ubuntu 20.20]
 - OS Version [e.g. 14]
 - Mailspring Version: Unknown, when going to click Help >> View License, nothing happens

**Comment by flindeberg** [comment]
Try waiting a bit, sometimes Office 365 app passwords take up to four hours to work (don't ask me why).

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved by the preceding response, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
