### ISSUE TITLE
Your Mailspring ID is missing required fields

### ISSUE THREAD

**Issue by applesea2** [Foundry376/Mailspring#216]
##### Are there any related issues?

...

##### What operating system are you using?
...
Ubuntu 17.10
##### What version of Mailspring are you using?
...
1.0.5-2
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
Your Mailspring ID is missing required fields popup immediately after installing on Ubuntu distributions. Installing the package libsecret-1-dev fixes the issue. Possibly add it as a dependency 
#204 #### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Did you see any errors when you installed the debian package? As far as I know, libsecret-1 is already a dependency: https://github.com/Foundry376/Mailspring/blob/master/app/build/resources/linux/debian/control.in#L3. Maybe we need to specify `libsecret-1-dev` instead of `libsecret-1-0` in that file?

**Comment by bengotow** [comment]
We'll see if switching this out for libsecret-1-dev fixes it. 👍

**Comment by Shickmo** [comment]
I literally just ran this on the just released version of Pop_OS!, which is based on Ubuntu 17.10, and adding libsecret-1-dev package resolved the issue. So the work around until Ben gets this pushed out is to just install that package in your distribution of choice, close mailspring and relaunch and you should be good to go.

Thanks.
