### ISSUE TITLE
Feature Request: Mailspring Human Responses

### ISSUE THREAD

**Issue by CarlosRebolledo** [Foundry376/Mailspring#2160]
**Is your feature request related to a problem? Please describe.**

Paid mailspring by definition includes technical support and for several months we only have Bot and not clear and concrete answers

**Describe the solution you'd like**

Mailspring must not only give clear and concrete answers, but they also have to be human.  That is, the human team and not through Bot

**Describe alternatives you've considered**

We need Mailspring and its maintainer to say what happens.  I don't want candy or aspirin, but a real answer

**Comment by CodeMouse92** [comment]
> Paid mailspring by definition includes technical support and for several months we only have Bot and not clear and concrete answers

Paid Mailspring has never promised techncial support. This project is run primarily by one person, who maintains Mailspring in addition to his full-time job. I just joined as a volunteer to help tame the GitHub Issues.

We've created a new Discourse community to better facilitate community-based support, as well as better handing of issues and quicker response for service issues: https://community.getmailspring.com/
