### ISSUE TITLE
Bug: "Reply all" always includes self in CC

### ISSUE THREAD

**Issue by mp1994** [Foundry376/Mailspring#2168]
**Describe the bug**
Whenever I use the "Reply all" button, I am added to the CC box and I really do not want this to happen. 

**To Reproduce**
1. Go to the inbox, open any message
2. Click on Reply all
3. Scroll down to the CC field
4. See "self" in the CC field

**Expected behavior**
I guess this should not happen, as I have not set any rule for automatic CC/BCC and I have not found any option to disable this feature, so I guess it is a bug.

**Screenshots**
![Selection_003](https://user-images.githubusercontent.com/23299360/95843971-a90dea80-0d48-11eb-846e-01b6f2019238.png)
![Selection_004](https://user-images.githubusercontent.com/23299360/95844333-1752ad00-0d49-11eb-81df-5c972e672f75.png)

In the screenshots you can see the issue. It happens both if the e-mail is sent to me only or with other people too (as in the screenshot).

**Setup: (please complete the following information):**
 - OS: Ubuntu 
 - OS Version 18.04 LTS
 - Mailspring Version: 1.7.8-13635bcf

**Comment by asparc** [comment]
Could this be related to email-aliases? E.g. you have your email adress (1) and an alias for that same email address (2); you were addressed through (2) and you reply-all via (1), or vice versa? This way Mailspring might not see that (1) and (2) are the same. This used to happen with the email client I was using on Android. 

If this is the case, a solution might be to add the alias in the email settings?

**Comment by mp1994** [comment]
Yes! That was it!! I didn't think of aliases, now that I have added it, the "bug" is gone!
Thanks so much dude
