### ISSUE TITLE
Feature Request: User Community

### ISSUE THREAD

**Issue by amandabee** [Foundry376/Mailspring#2169]
**Is your feature request related to a problem? Please describe.**

Is there an active user community anywhere? It seems like most spaces where that might emerge are not open to dialog, which makes sense -- I can see that a lot of people are using it as a space to voice frustration with support available to paid users, but a true external community could just assert that we can't handle complaints about support. 

**Describe the solution you'd like**
I'd like to see the documentation direct users who want to support each other to a place where we can do that. 

**Describe alternatives you've considered**
I've done a lot of searching and looked at Stack Exchange and Reddit for existing communities and I didn't see any. 

**Additional context**
When I was getting set up I almost quit because no amount of searching would turn up any documentation of how mail filters work. It turns out they're called "rules" -- if I could have turned to a user community someone could definitely have pointed me in the right direction.

I'm also very interested in exploring some theme variations and would love to see whether other active users have developed themes already that will work for me.

**Comment by Phylu** [comment]
Hi @amandabee,

a User Community has just been created a few days ago. You can find it here: https://community.getmailspring.com/

Best regards
Phylu

@CodeMouse92 Please close the issue.

**Comment by CodeMouse92** [comment]
@amandabee We have indeed started this community, as @Phylu pointed out (thanks!)

We'd love for you to join, and to share your experiences with mail filters in the new Help section.
