### ISSUE TITLE
Accidentally emptied spam and lost data

### ISSUE THREAD

**Issue by mredigonda** [Foundry376/Mailspring#2177]
There is an "empty spam" without any undo option, in the same position in the screen as the "clear selection" button. Messages aren't even sent to thrash so this resulted in loss of data.

**Comment by jvidal-sysadmin** [comment]
Same behaviour that when you use Gmail via web. It's very common do that.

So, I think this issue is not a bug is just a suggestion.

Sorry my friend, bad luck.
