### ISSUE TITLE
Hyperlink popup closes automatically

### ISSUE THREAD

**Issue by cccruzr** [Foundry376/Mailspring#218]
**Version:** Win10 - Mailspring 1.0.5-84643cb3
**Bug?** Hyperlink popup window closes automatically and does not allow to write nor verify the typed/pasted URL. 

![](https://media.giphy.com/media/l1J9R4fcpwKEqrwpG/giphy.gif)

Edit: I realized it happens just the first time you open the popup, because it works fine when you want to edit the URL

**Comment by palefire19** [comment]
+1 on MacOS

**Comment by cccruzr** [comment]
Any update on this?
Seems not fixed in the last update [1.0.7-664204d8]

**Comment by bengotow** [comment]
Hey folks! This has been fixed in 1.1.0 and onward, which uses a new composer based on `SlateJS`. Enjoy! Also, you can now use Cmd/Ctrl+K to show the link picker, which is handy. 👍
