### ISSUE TITLE
Feature Request: Source inbox color label for different accounts

### ISSUE THREAD

**Issue by ZachariahRosenberg** [Foundry376/Mailspring#2184]
**Is your feature request related to a problem? Please describe.**
With multiple inboxes, it is difficult to quickly see which emails belong to which accounts in combined folders (e.g. combined inbox, combined, unread). 

**Describe the solution you'd like**
Quick color coded labels that indicate which inbox the email is for. Here is how Spark email does this (two accounts with labels gold and green):

<img width="101" alt="Screen Shot 2020-10-26 at 5 52 08 PM copy" src="https://user-images.githubusercontent.com/6923376/97233601-9cac7780-17b5-11eb-85ac-378ca5b05155.png">

**Comment by Phylu** [comment]
I started working on the issue. See:
* https://github.com/Foundry376/Mailspring/issues/526#issuecomment-751387311
* https://github.com/Phylu/Mailspring/tree/feature/526-colorize-accounts
