### ISSUE TITLE
Some inline images are displayed as attachments

### ISSUE THREAD

**Issue by rafrsr** [Foundry376/Mailspring#219]
##### Are there any related issues?
No

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.0.5

**Bug?**
Yes

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

> When compose a email with images like the following:
![image](https://user-images.githubusercontent.com/7094012/31830178-6beb9a6e-b58d-11e7-86c6-1a400975ad33.png)

> The email is received in Mailspring with in-line images removed and displayed as attachments.
![image](https://user-images.githubusercontent.com/7094012/31830269-b5079356-b58d-11e7-95b7-eddc4825ab59.png)

This happens with all the emails and it is annoying because images are displayed out of context.

**Comment by bengotow** [comment]
Hey! A few clients send inline images as mime parts interleaved between HTML parts, rather than using the newer "cid:" style references in the rich text body. Mailspring currently only supports the later case. Inline images in emails sent from Gmail, Mail.app, etc. should work - I think this /should/ be a bit of an edge case.

What client was this message sent from?

**Comment by rafrsr** [comment]
> What client was this message sent from?

The same MailSpring, copy from gimp & paste inside the body, or using a screenshot tool like shutter and send me the email to myself.

Other messages from some of my contacts has the same problem and her company logo over the signature is displayed as attachment, however the same email is displayed correctly in the web-mail, Thunderbird, Evolution or any other email client.

> The gray rectangle is displayed instead of the company logo, and the logo is displayed as attachment.
![image](https://user-images.githubusercontent.com/7094012/31839738-69380046-b5b0-11e7-8c3a-13296c3a6276.png)

In this case: `X-Mailer: Microsoft Outlook 16.0`

**Comment by bengotow** [comment]
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.
