### ISSUE TITLE
Bug: Dependencies cannot be installed correctly

### ISSUE THREAD

**Issue by Bruce-Ming** [Foundry376/Mailspring#2197]
**Describe the bug**
platforms： windows，
node 11.0.0

when i run npm install， Console Printing 
`-- Running npm install in ./app with electron config --`
 but I've been waiting a long time.
 Console Printing 
```
npm ERR! code 128
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE clone --mirror -q https://github.com/bengotow/slate.git C:\Users\mac\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-e535fc07\.git --config core.longpaths=true
npm ERR! warning: templates not found in C:\Users\mac\AppData\Local\Temp\pacote-git-template-tmp\git-clone-cbe403bd
npm ERR! error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054
npm ERR! fatal: the remote end hung up unexpectedly
npm ERR! fatal: early EOF
npm ERR! fatal: index-pack failed
npm ERR! code 128
```

**To Reproduce**
1. According to the document 
`npm install --global --production windows-build-tools`
2. clone this code
3. npm install

i am chinese， Is this a problem with my network?  Has anyone else had this problem?

**Comment by CodeMouse92** [comment]
Not gonna lie, that's a weird error. I do suspect network, although it's hard to say for sure.

**Is this still an active problem for you?** If so, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
