### ISSUE TITLE
Bug: Can't install using .deb as gfvs-bin cannot be found

### ISSUE THREAD

**Issue by scottedwards** [Foundry376/Mailspring#2198]
Tried to install on Pop!_OS 20.10 but can't as the package gfvs-bin is not install-able.

https://i.imgur.com/oH7xKnS.png

**Comment by mokshchaudhary** [comment]
Install using the following command:
`sudo dpkg --ignore-depends=gvfs-bin -i mailspring-1.7.8-amd64.deb`

**Comment by scottedwards** [comment]
Nice, that worked. Considering it doesn't need to have this dependency installed, would it be best to update the project so that it doesn't require it?
