### ISSUE TITLE
Error: SyncWorker crashed with SIGSEGV (code null):

### ISSUE THREAD

**Issue by louim** [Foundry376/Mailspring#22]
Hey!

I'm getting this error in loop (every couple of minutes)

##### Are there any related issues?

No

##### What operating system are you using?
Mac OS X Sierra

##### What version of Mailspring are you using?
1.0.0

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
I'm trying to sync an Hotmail account (Office365).
I'm getting "Encountered an error while syncing myemail@hotmail.com" in the sidebar.

Looking at the console, there's the following error:
```
Error: SyncWorker crashed with SIGSEGV (code null):
Error: null

A segmentation fault occurred during program execution.
This typically happens when you try to dereference a pointer
that is NULL or invalid.

19506 [2017-10-04 14:48:31.627] [background] [critical]in mailsync     Message::Message(mailcore::IMAPMessage*, Folder&, long) 

{
  "stack": "in mailsync     Message::Message(mailcore::IMAPMessage*, Folder&, long)\nin mailsync     MailProcessor::insertMessage(mailcore::IMAPMessage*, Folder&, long)\nin mailsync     MailProcessor::insertFallbackToUpdateMessage(mailcore::IMAPMessage*, Folder&, long)\nin mailsync     SyncWorker::syncFolderUIDRange(Folder&, mailcore::Range, bool, __1::vector*)\nin mailsync     SyncWorker::syncNow()\nin mailsync     runBackgroundSyncWorker()\nin mailsync     void* __1::__thread_proxy(void*)\n0x7fff9736693b  _pthread_body\n0x7fff97366887  _pthread_body\n0x7fff9736608d  thread_start\n\n\n",
  "log": "19497 [2017-10-04 14:47:51.668] [foreground] [info] Idling on folder INBOX\n19497 [2017-10-04 14:48:03.899] [metadataExpiration] [info] Scanning for expired metadata\n19497 [2017-10-04 14:48:03.899] [metadataExpiration] [info] -- Will wake for next expiration in 7201sec\n19506 [2017-10-04 14:48:08.908] [main] [info] ------------- Starting Sync ---------------\n19506 [2017-10-04 14:48:08.915] [background] [info] Marking all folders as `busy`\n19506 [2017-10-04 14:48:08.915] [metadata] [info] Metadata delta stream starting...\n19506 [2017-10-04 14:48:08.925] [background] [info] Syncing folder list...\n19506 [2017-10-04 14:48:10.288] [background] [info] Syncing folder list...\n19506 [2017-10-04 14:48:10.373] [background] [info] syncFolderUIDRange - (INBOX, UIDs: 11685 - 16685, Heavy: true)\n19506 [2017-10-04 14:48:11.405] [foreground] [info] syncFolderUIDRange - (INBOX, UIDs: 17175 - 17456, Heavy: false)\n19506 [2017-10-04 14:48:12.170] [foreground] [info] Idling on folder INBOX\n19506 [2017-10-04 14:48:23.916] [metadataExpiration] [info] Scanning for expired metadata\n19506 [2017-10-04 14:48:23.916] [metadataExpiration] [info] -- Will wake for next expiration in 7201sec\n",
  "provider": "office365"
}
```

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Office365 (Hotmail)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I'm not exactly sure what's happening here. Maybe of interest, this is a really old email account with thousands of emails over the last 15 years.

Let me know if there's more I can do to help debug.

--

**Comment by bengotow** [comment]
Hi @louim — thanks for reporting this. Sentry has actually been pretty flooded with this error and it seems to happen when mailsync hits a particular message it can't parse. Can you try updating to the  1.0.1 version I shipped a couple minutes ago and see if that fixes the issue? I narrowed down at least one case, which crashed the app when the message had no "From:" address. (Which isn't /supposed/ to be possible, but oh well...)

Here's a direct link to the Windows installer: https://mailspring-builds.s3.amazonaws.com/client/ba1d6734/win-ia32/MailspringSetup.exe

**Comment by louim** [comment]
Hey! I should have waited a couple minutes more before posting this issue 😄 , version 1.0.1 fixed the problem for me, it happily chugged through my account without any hiccups. Thanks again for the quick work! 🎉
