### ISSUE TITLE
Notification alert not showing for new messages [Windows 10]

### ISSUE THREAD

**Issue by domenico-ruggiano** [Foundry376/Mailspring#221]
I'm currently not showing the notification alerts when receiving new messages, on **windows 10**

##### Are there any related issues?

Related issue #160

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.0.5

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?

NO

**Comment by bengotow** [comment]
Merging into #160
