### ISSUE TITLE
Feature Request: Reduce memory usage

### ISSUE THREAD

**Issue by howdev** [Foundry376/Mailspring#2210]
May be you could reduce the memory usage on Linux system. Currently Mailspring 1.7.8 uses 280MB RAM while Thunderbird uses 210MB

**Comment by CodeMouse92** [comment]
This is probably not something we can do a lot about. Mailspring is built on Electron, which is in turn based on Chromium. Its architecture works very well for what Mailspring does, but it unfortunately has considerable memory overhead, owing in large part to Electron's use of multiprocessing and IPC.

In general, we want to keep memory usage as low as possible, but this is not likely to be achievable as is. The fact we're *that close* to Thunderbird is actually rather encouraging to *me*, especially when you compare to the memory usage Chromium tends towards itself.

By the way, we are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
