### ISSUE TITLE
Fastmail: Clarify that password should be IMAP

### ISSUE THREAD

**Issue by WhyNotHugo** [Foundry376/Mailspring#2216]
**Describe the bug**

Fastmail supports both IMAP and JMAP.

Mail spring does not specify which protocol it uses, so when creating an app password one has to guess. Being that JMAP is led by fastmail, and the recommended  approach, one would assume that's what mailspring supports.

After generating and providing the password to mailspring, it throws an error message indicating "Check your username and password (IMAP).

It would be best to clarify what protocol mailspring will use **before** a users provides a password, since one has to chose the protocol before generating the password.

**To Reproduce**
1. Open mailspring
2. Log into mailspring
3. Select fastmail -- you're prompted for credentials
4. Head over to fastmail to generate an app password.
5. A protocol must be selected at this point. Mailspring does not indicate any, so let's assume JMAP.
6. Finish generating the app password.
7. Put the password in mailspring.
8. At this point, mailspring show an error and clarifies that I should have selected IMAP in step 5.

**Expected behavior**
Supported protocol should be shown _before_ a password is provided, since it's required to generate a password.

**Actual behaviour**
Supported protocol should be shown _after_ a password is provided, so the initial password must be deleted and another one must be generated.

**Setup: (please complete the following information):**
 - OS: ArchLinux
 - Mailspring Version: 1.7.8-13635bcf

**Additional context** 

This is more of a UX issue than anything else -- it's not a blocker, but just annoying.

**Comment by Phylu** [comment]
The current text is: `FastMail requires that you create a unique app password for email apps like Mailspring. Follow these instructions to create one and then paste it below.` The instructions on the FastMail website do not indicate, that there are different types of app passwords that can be generated. 

@WhyNotHugo  Would the following text work be fitting?
`FastMail requires that you create a unique app password of type IMAP for email apps like Mailspring. Follow these instructions to create one and then paste it below.`

**Comment by WhyNotHugo** [comment]
Yeah, I think that would be clear enough. :+1:

**Comment by CodeMouse92** [comment]
I won't be migrating this issue, as it is active and will be closed by @Phylu's PR.
