### ISSUE TITLE
Bug: Linux Ubuntu 20.10 dependencies deprecated for gvfs-bin

### ISSUE THREAD

**Issue by bibanez** [Foundry376/Mailspring#2226]
**Describe the bug**
Can't install package due to the package manager trying to install gvfs-bin, a deprecated software that in 20.10 was substituted for gvfs.

**To Reproduce**
1. Install package on Ubuntu 20.10 or Pop Os 20.10 using either Eddie or apt-get.

**Expected behavior**
Failure to install giving the following message: "The following packages have unmet dependencies:
  mailspring: Depends: gvfs-bin but it is not installable"

**Setup: (please complete the following information):**
 - OS: Pop Os
 - OS Version 20.10
 - Mailspring Version: 1.7.8

**Additional context** 
It can be solved by updating the file on app/build/resources/linux/debian/control.in

**Comment by cerebrux** [comment]
This should be fixed with this https://github.com/Foundry376/Mailspring/commit/53b5b95990240ea069525bac7440247c1a249b2b

**Comment by imtiaz-rahi** [comment]
> This should be fixed with this [53b5b95](https://github.com/Foundry376/Mailspring/commit/53b5b95990240ea069525bac7440247c1a249b2b)

But there is no new release with this fix yet.

@bibanez in the meantime, please use the workaround described [here](https://github.com/Foundry376/Mailspring/issues/2154#issuecomment-716920439).

**Comment by CodeMouse92** [comment]
The fix was released in Mailspring 1.8.0. :tada:
