### ISSUE TITLE
Bug: Double/single click on tray icon doesn't open app

### ISSUE THREAD

**Issue by SinTan1729** [Foundry376/Mailspring#2229]
### Steps to reproduce

1.  Double/single click on tray icon

### Expected behavior

App should open as most other apps do.

### Actual behavior

A popup is shown, needing another click at "Open Inbox"

### ENVIRONMENT

> Version: 1.7.8-13635bcf

> OS: Linux (Manjaro KDE)

> Arch: x64

**Comment by valentt** [comment]
Check my bug: https://github.com/Foundry376/Mailspring/issues/2231

This is a dead project and dead product unfortunately, and we need to find an alternative. Any suggestions?

**Comment by SinTan1729** [comment]
> Check my bug: https://github.com/Foundry376/Mailspring/issues/2231
> 
> This is a dead project and dead product unfortunately, and we need to find an alternative. Any suggestions?

TBH, I never used its paid features. I'm a student, and just need a decent client to manage my GMail and University mail. I chose Mailspring mostly because it behaves well with GMail labels and also looks good.

But since an abandoned project might soon become a security issue, I'll probably start looking for an alternative as well.

**Comment by CodeMouse92** [comment]
@SimTan1729 Unfortunately, @valentt spoke out of turn. The project and product are NOT dead. The maintainer responded to his issue. There was a server issue.

Mailspring is alive and well!

**Comment by SinTan1729** [comment]
> @SimTan1729 Unfortunately, @valentt spoke out of turn. The project and product are NOT dead. The maintainer responded to his issue. There was a server issue.
> 
> Mailspring is alive and well!

That's a very good news. Hope this issue gets resolved soon.

**Comment by CodeMouse92** [comment]
@SinTan1729 I'm in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term.

https://community.getmailspring.com/t/double-single-click-on-tray-icon-doesnt-open-app/37

Please consider joining that community!
