### ISSUE TITLE
Bug: The attachment received by mailspring becomes "winmail.bat"

### ISSUE THREAD

**Issue by shrh1020** [Foundry376/Mailspring#2237]
The attachment received by mailspring becomes "winmail.bat", but it's normal to use other clients to receive the same e-mail.

**Comment by kaleidoscopique** [comment]
Same here! 2 PDFs have been changed by "winmail.bat". 

This is the first time it happens to me after 1+ year of Mailspring. In my case, the sender of this email has made a mistake when typing one of the receiver's address : https://jmp.sh/sRLePx7 As you can see on my screenshot, there are some non-latin characters translated in Ascii+Punycode, which is a mistake.

I wonder if there is a relation between both facts. @shrh1020 : does your email has been sent to an address containing non-latin characters (using the `xn--` syntax)? Like Chinese or Cyrillic characters?

**Comment by shrh1020** [comment]
> Same here! 2 PDFs have been changed by "winmail.bat".
> 
> This is the first time it happens to me after 1+ year of Mailspring. In my case, the sender of this email has made a mistake when typing one of the receiver's address : https://jmp.sh/sRLePx7 As you can see on my screenshot, there are some non-latin characters translated in Ascii+Punycode, which is a mistake.
> 
> I wonder if there is a relation between both facts. @shrh1020 : does your email has been sent to an address containing non-latin characters (using the `xn--` syntax)? Like Chinese or Cyrillic characters?

Thank you for your reply.

The email address only contains English letters, numbers and "@", which are all in ASCII.So that's not the reason.

I also looked for the reasons. Some people mentioned the following two points.
(a) It is a RTF format file sent by Microsoft Office Outlook.
(b) It is recommended that the sender send the message in HTML format.

But why is there no problem in opening the same email with other email clients.  -_-!

**Comment by CodeMouse92** [comment]
This looks like an odd one!

@shrh1020 We're in the process of migrating to Discourse for future issues. As we need additional information anyway, would you please open a Bug Report here: https://community.getmailspring.com/c/bugs/10

Be sure you include all of the requested information, in addition to what you've provided above.

Once that Discourse topic is created, the conversation can continue there. I've closed and locked this topic for now, but rest assured, we'll still take this bug into consideration once we have the needed information. :)
