### ISSUE TITLE
Tray icon is too big

### ISSUE THREAD

**Issue by dennisotugo** [Foundry376/Mailspring#225]
How do i change the tray icon for linux? Is there an icon name i can use to override it?

**Comment by bengotow** [comment]
Can you attach a screenshot + the Linux distro you're using? There is no way to override the icon currently because it's inside the app's ASAR archive.

**Comment by bengotow** [comment]
(Somewhat related to #209)

**Comment by rplanchuelo** [comment]
I agree, tray icon is too big
![imagen](https://user-images.githubusercontent.com/32977921/31850191-80bf4b40-b64e-11e7-808f-58976d0caa7c.png)
I use Antergos with KDE Plasma

**Comment by rplanchuelo** [comment]
Could I suggest that the normal icon could be the Mailspring's logo when there isn't any unread mail and the same but with other color or a simple letter, if there are some unread mail?

**Comment by rplanchuelo** [comment]
Another suggestion could be that the Mailspring's logo shows a letter opened or closed respectively

**Comment by dennisotugo** [comment]
Would something in this manner work? [https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/data/database/mailspring.json](https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/data/database/mailspring.json) & I use manjaro

**Comment by applesea2** [comment]
Yeah I noticed that too. Still works, but much larger than the Windows tray icon

**Comment by dennisotugo** [comment]
[https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/data/database/mailspring.json](https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/data/database/mailspring.json) fixed my problem. I will be closing this now.

**Comment by rplanchuelo** [comment]
I have been able to change the icons without you have to install new applications. If you want, you can download a new file app.asar and copy it in /usr/share/mailspring/resources (in Arch Linux). I have only changed png files. Maybe it won't work when Mailspring is upgrade.

https://www.dropbox.com/s/kjeue6sie3ao4cb/app.asar.zip?dl=0

**Comment by bengotow** [comment]
(You probably shouldn't replace the app.asar file—there could be other unauthorized changes to the app in there and it will be reset the next time you update Mailspring. All of the app's javascript code and resources are in that bundle.)

Thanks for the pictures folks—I think we must just need to ship a smaller image. It's strange that it looks fine on other linux distros.

**Comment by dennisotugo** [comment]
@bengotow Not a smaller image, probably a different size for linux panels i.e 16px, 22px, 24px and so on or placing the icon in the icons so as to allow for easier change?

**Comment by BlueManCZ** [comment]
I have similar situation on KDE Plasma, but icon should be smaller and black.

![screenshot_20171114_143435](https://user-images.githubusercontent.com/17854950/32782614-4a568f1a-c949-11e7-8ed8-27c5e8dcbdf5.png)

**Comment by rplanchuelo** [comment]
![menuitem-inbox-full-newitems 2x](https://user-images.githubusercontent.com/32977921/32787942-329e0ac4-c958-11e7-8b3e-8c5dcefb7465.png)
![menuitem-inbox-full 2x](https://user-images.githubusercontent.com/32977921/32787943-32d890e0-c958-11e7-9062-022d9a31f67c.png)
![menuitem-inbox-zero 2x](https://user-images.githubusercontent.com/32977921/32787945-332440c6-c958-11e7-9f05-f7182b99339d.png)

**Comment by rplanchuelo** [comment]
I make a scrip to change de icons. You'd have installed asar to run it. If you change png files, without change the names, the scrip'd work ok.
So you can change the color or the size in gimp. 
[Mailspring-icons.zip](https://github.com/Foundry376/Mailspring/files/1471388/Mailspring-icons.zip)

**Comment by rplanchuelo** [comment]
I make a scrip to change de icons. You have to install asar to run it. If you change png files, without change the names (colors, sizes, ...), the scrip'd work ok. It works in Arch Linux, maybe you'll need to change directories in the scrip in other distribution. 
[Mailspring-icons.zip](https://github.com/Foundry376/Mailspring/files/1471413/Mailspring-icons.zip)

**Comment by rplanchuelo** [comment]
Black version
[Black version.zip](https://github.com/Foundry376/Mailspring/files/1471486/Black.version.zip)

**Comment by Quadss** [comment]
Same issue on XFCE, running Adwaita theme, with elementary XFCE icon pack. Would really appreciate having a dark icon.
![screenshot_2018-05-25_13-53-10](https://user-images.githubusercontent.com/38180101/40543175-79f5b48c-6023-11e8-877f-03d399921b15.png)
