### ISSUE TITLE
Mailspring window doesn't respond after minimising/restoring it

### ISSUE THREAD

**Issue by moray33** [Foundry376/Mailspring#2269]
I've had this problem since I started using Mailspring a long time ago and it's a bit annoying. There are some issues when you minimise/restore the Mailspring window in several ways.
I always keep the program opened so I get notifications when I get new mail. So, for example, one clear situation when the window pops up but it doesn't respond is when you do the following:
-Open the window.
-Minimise it
-Close it (wether clicking the Mailpring icon in the system tray, or right click and close the icon in the task bar)
-Click the Mailspring icon in the task bar (then, it shows up minimised in the task bar)
-Click the Mailspring icon in the task bar. Then, the window pops up but it doesn't respond, you can't move or open anything. To do so, you have to click on the system tray icon again.

**Comment by CodeMouse92** [comment]
As mentioned in the Issue creation screen, we no longer accept bug reports through GitHub. Please see https://community.getmailspring.com/
