### ISSUE TITLE
RFE: Find contacts by full name

### ISSUE THREAD

**Issue by gnunn1** [Foundry376/Mailspring#227]
When adding addresses in the To, CC or BCC fields mailspring searches for matches based on e-mail address rather then name. In my company we generally use the naming convention of first initial and last name but not always. In these cases I'm always having to go to an old e-mail and copy/paste the address as I can't find it with just the assist provided in the To field.

In gmail I can search for addresses by either email or full name and it happily matches either. I never have to manually search for an old e-mail to copy and paste the address.

##### Are there any related issues?

...

##### What operating system are you using?
...
Arch Linux

##### What version of Mailspring are you using?
...
1.05
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...
Yesm GMail does this.

**Comment by bengotow** [comment]
This should work in Mailspring if the emails have names on them when you receive them. If they're just raw email addresses, it won't guess the names though.

![image](https://user-images.githubusercontent.com/1037212/31904534-69f7294e-b7e0-11e7-99d8-2a105368915f.png)

**Comment by gnunn1** [comment]
I think it works for you because your full name is the e-mail address. In my company, which uses gmail, they use first initial plus last name. So given the name Bob Smith <bsmith@mycompany.com> search for Bob returns nothing. Searching for bsmith works fine however.

In your example of Ben Gotow (bengotow@gmail.com) typing ben returns your email address since it is contained in it.

Does that make sense?

**Comment by bengotow** [comment]
Hey! Ahh that totally makes sense. My example was pretty awful actually.

I've been able to reproduce this problem on my machine with a contact in the form you suggested `Rob Mann rmann@xxxx.com` - I can find him by last name (`Mann`) but not by first name, which is odd.  Will get this fixed!

**Comment by bengotow** [comment]
This should be fixed in the next release, but it requires that Mailspring rebuild the local cache of your mailbox. After downloading the update, you'll need to click this button in Preferences > General. Thanks!

![image](https://user-images.githubusercontent.com/1037212/31972380-458f6062-b8d5-11e7-9623-084aabc1390f.png)
