### ISSUE TITLE
Add Yahoo! Brasil Support

### ISSUE THREAD

**Issue by CodeMouse92** [Foundry376/Mailspring#2273]
## Objective
It appears that `yahoo.com.br` is not supported. It defaults to using the domains for Yahoo! (presumably), rather than the domains for Yahoo! Brasil.

## Testing Notes

I've asked the original poster to test the fix.

## Tips

I think we can use the difference between `yahoo.com` and `yahoo.co.jp` accounts as a model to fix this.

## References

https://community.getmailspring.com/t/problem-to-add-a-yahoo-com-br-account/356

**Comment by CodeMouse92** [comment]
My original theory was off. It indeed uses the normal yahoo.com mail servers, not a different domain. Something is fishy.

**Comment by dale76uk** [comment]
do you have the log?

**Comment by Phylu** [comment]
Closed as being stale since 2021. Can be revisited if somebody wants to follow it up from here: https://community.getmailspring.com/t/problem-to-add-a-yahoo-com-br-account/356/15
