### ISSUE TITLE
IMAP analize error

### ISSUE THREAD

**Issue by chojnacky** [Foundry376/Mailspring#2274]
I can't connect to any e-mail account hosted on www.poczta.home.pl
Both my accounts throw this error when it comes to "Archive".

> ----------IMAP----------
> connect <mailcore::IMAPSession:0x7ffeefbff688>
> * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
> ssl connect 
> connect ok
> login
> 1 LOGIN "xyz@xyz" *********
> 1 OK [CAPABILITY IMAP4rev1 SASL-IR LITERAL+ CHILDREN I18NLEVEL=1 ID IDLE SORT SORT=DISPLAY UIDPLUS UNSELECT QUOTA MOVE WITHIN LIST-EXTENDED LIST-STATUS SPECIAL-USE XLIST STARTTLS] Completed
> 2 LIST "" ""
> * LIST (\Noselect) "." ""
> 2 OK Completed
> login ok
> 3 XLIST "" "*"
> * XLIST (\HasNoChildren \) "." "Archive"
> * XLIST (\HasChildren \) "." "Archiwum"
> * XLIST (\HasNoChildren \) "." "Archiwum.2019"
> * XLIST (\HasNoChildren \) "." "Archiwum.2020"
> * XLIST (\HasNoChildren \Draft) "." "DRAFTS"
> * XLIST (\HasNoChildren \Inbox) "." "INBOX"
> * XLIST (\HasNoChildren \Sent) "." "SENT"
> * XLIST (\HasNoChildren \Spam) "." "SPAM"
> * XLIST (\HasNoChildren \Trash) "." "TRASH"
> * XLIST (\HasNoChildren \) "." "confirmed-ham"
> * XLIST (\HasNoChildren \) "." "confirmed-spam"
> 3 OK Completed
> XLIST (\HasNoChildren \) "." "Archive"
>

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
