### ISSUE TITLE
Rules not applying as expected

### ISSUE THREAD

**Issue by luizaq** [Foundry376/Mailspring#2281]
I have a very simple rule setup to add a tag to emails from a determined address.However the tag was only applyed to some emails after reprocessing,

![image](https://user-images.githubusercontent.com/37643140/107598682-4432a600-6bfd-11eb-96d1-4c7988b6083c.png)
![image](https://user-images.githubusercontent.com/37643140/107598708-5b719380-6bfd-11eb-91b1-fae55a3461f7.png)

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
