### ISSUE TITLE
Calendar blank on gmail, Abort error (SIGABRT): system functions that detect corrupt state.

### ISSUE THREAD

**Issue by MadCabbit** [Foundry376/Mailspring#2282]
I set up Mailspring Linux earlier and the calendar was working, but when I tried rebooting into Windows 10 Pro on the same machine, it's blank.  I'm getting the following error in the logs, clearing out the AppData directory and trying setup again didn't change anything:

18728 [2021-02-11 01:02:16.401] [calendar] [critical] 
***
*** Mailspring Sync 
*** An abort error (SIGABRT) occurred during program execution: 
*** system functions that detect corrupt state.
***

18728 [2021-02-11 01:02:16.448] [calendar] [critical] *** Stack trace (line numbers are approximate):
*** 185  ValidateRequestResp()
*** 137  PerformRequest()
*** 678  DAVWorker::performXMLRequest()
*** 585  DAVWorker::runForCalendar()
*** 518  ::operator()
*** 214  _Func_impl::_Do_call()
*** 71   DavXML::evaluateXPath()
*** 519  DAVWorker::runCalendars()
*** 98   DAVWorker::run()
*** 491  ::operator()
*** 210  _Pad::_Call_func()
***

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
