### ISSUE TITLE
Feature Request -- Add In IRC And Jabber Protocol Support

### ISSUE THREAD

**Issue by brttmsn** [Foundry376/Mailspring#2285]
I would like to say, first of all, that Mailspring is a wonderful slick and beautiful mail client and I am moving away from thunderbird. The only thing I would like to see added into Mailspring would be support for irc and jabber as these are two protocols that I use regularly. Thank you for consideration.

**Comment by CodeMouse92** [comment]
Mailspring just launched an official Discourse community which will house the catalog for themes and plugins, among other things. It would be great to have this theme listed there: https://community.getmailspring.com/c/themes/9

<<MAINTAINER>> if you join, we can also add you to the Theme Designers group.

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
