### ISSUE TITLE
Attach files via sendto dialogue

### ISSUE THREAD

**Issue by Phylu** [Foundry376/Mailspring#2289]
## Objective
On Linux systems do a right click to a file in the desktop environment and chose "Send To" in order to attach a file to a Mailspring e-mail. This currently only opens an empty e-mail without the attachment. [1]

## Testing Notes
Behaviour is probably different for different desktop environments. Development is done on gnome and will match the nautilus-sendto behaviour [2].
Therefore this should be checked on other desktop environments (e.g. KDE) as well.

## References

[1] https://community.getmailspring.com/t/right-click-send-via-mail-opens-new-email-dialog-but-doesnt-attach-file-kde-neon-dolphin-file-explorer/644/3
[2] https://gitlab.gnome.org/Archive/nautilus-sendto/-/blob/master/src/nautilus-sendto.c

**Comment by Phylu** [comment]
@CodeMouse92 Can you please assign the issue to me.

**Comment by CodeMouse92** [comment]
There you are, good sir. :)

**Comment by bengotow** [comment]
Thanks for looking into this @Phylu!
