### ISSUE TITLE
Wrong date and time on new mails

### ISSUE THREAD

**Issue by K0ple** [Foundry376/Mailspring#2304]

**Comment by K0ple** [comment]
While receiving new mails the date and time for some mails is wrong. For example, if the date is 12th March some mails are appearing with the date as 13th March and wrong time. I checked in gmail to confirm and there they display correct info. Also my system date and time are correct.

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
