### ISSUE TITLE
Mailspring Email has stopped working

### ISSUE THREAD

**Issue by peterK2108** [Foundry376/Mailspring#2305]

**Comment by peterK2108** [comment]
All my mail logos have disappeared and several of my tutors cannot send or receive

**Comment by peterK2108** [comment]
![Screen Shot 2021-03-17 at 14 10 45](https://user-images.githubusercontent.com/80835624/111481249-aade3e80-872a-11eb-8df4-5fe7eedda19d.png)

**Comment by r-adamski** [comment]
![image](https://user-images.githubusercontent.com/14250922/111485342-d404cc00-8736-11eb-894f-177214ac4342.png)
Same here, while trying to upload signature image.

**Comment by peterK2108** [comment]
Its a real pain, everything was working fine until today, and now several of my team cannot even receive or send


Peter Kellitt
Proprietor

E: ***@***.***
P:  07867114795
A: 61 Bridge Street, Kington, HR5 3DJ
W: http://www.thehomeschoolacademy.co.uk

**Comment by peepingThomist** [comment]
Yes, what these people are saying is true. Please fix it.

**Comment by marklabrecque** [comment]
I think I am seeing the same sort of issue on a fresh install this morning, but when I try to setup the app and login with my Mailspring ID, I get a blank screen, with no errors. This may be related to the Cloudflare outages this morning perhaps and may resolve itself once addressed from the external vendor.

**Comment by peepingThomist** [comment]
Thanks! Ihope that's right.

Lance Simmons

**Comment by marklabrecque** [comment]
It's working for me now. Maybe the @peterK2108 should try this again and if it's working, close the ticket.

**Comment by CodeMouse92** [comment]
This should have been reported on Discourse. As the templates here on GitHub clearly state in multiple places, we don't accept bug reports etc here on GitHub anymore.

As it happens, this was reported and resolved here: https://community.getmailspring.com/t/stuck-in-welcome-flow/1115
