### ISSUE TITLE
White screen upon first start

### ISSUE THREAD

**Issue by ZeroV0LT** [Foundry376/Mailspring#2306]
At first start, I can see the "Welcome to Mailspring" page, than a few slides up to the "snooze emails ..." and than a white window with just a back arrow in the top left corner.
Cannot get past this point.

Any suggestion?

Version is: 1.8.0 2021-01-19 on latest Popos!

STDOUT:

```
domenico@pop-os:/tmp$ mailspring
Gtk-Message: Failed to load module "appmenu-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 100ms

{"error":null}
```

**Comment by ZeroV0LT** [comment]
It seems running in dev mode let me go over this point ...

**Comment by CodeMouse92** [comment]
@ZeroV0LT as our template here on GitHub clearly stated in multiple places (which you had to bypass and/or erase three times to post this), you should not be reporting issues here on GitHub. Instead, you should report them on our Discourse.

As it happens, this was already reported and resolved here: https://community.getmailspring.com/t/stuck-in-welcome-flow/1115
