### ISSUE TITLE
Mailspring Search not listing Emails when compared to GMail.com webmail

### ISSUE THREAD

**Issue by zparihar** [Foundry376/Mailspring#2309]
Hi Guys,

Love your mail product, but I've experienced the lack of ability to do a search for both text in the body or the subject line in Mailspring when doing a search.

I'm on the PRO plan, and I initially installed the SNAP version about a year ago.  A few months back, I was noticing that some of the searches were not very comprehensive compared to my previous experiences.  So I decided to remove the SNAP package and install the DEB package.  After logging into my account, all the search results were exactly on par with GMAIL.COM webmail.  Now after running the DEB package for a few months, I'm seeing the same behaviour again where my search results are no longer on par with GMAIL.COM.  Its kind of hard to identify a pattern of behaviour though.  Is there some sort of setting in place regarding search results?  I can't really find it...

Please point me in the right direction for this issue.

Cheers,

Zubin

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
