### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by pbleic** [Foundry376/Mailspring#2314]
I am in Ubuntu 18.04, using Mailspring 1.8.0-893.  Search will find some emails but not others.  For a particular person, it will find that email (and it's thread) using multiple search terms, but won't find another email thread to and from the same person.  I have the emails also in Thunderbird and Gmail and BOTH will find all the emails. Mailspring seems to arbitrarily find only some and not all of the emails.

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
