### ISSUE TITLE
Minimize to tray on close

### ISSUE THREAD

**Issue by ondrej-petr** [Foundry376/Mailspring#2318]
Hi,
please give back the option / feature to minimize to tray, when I close the Mailspring window. I miss this behaviour from update to version 1.9.0-87660767 (Windows 10).

**Comment by agreeff** [comment]
I would like the same thing.. Testing the current latest Mailspring release at the moment on Pop!_OS 20.10 with Gnome 3.38, but I can't get it to stay running.

The `mailspring --background` command does indeed launch the app in the background as expected, complete with tray icon, but then I cannot find a way to "hide" the window again, as "minimize" doesn't hide the window and "close" quits the app.

Geary has a (currently slightly broken) "Watch for mails when window is closed" setting that attempts to make the "close" button hide the window instead, but I don't see any similar option in Mailspring.

**Comment by Zenoo** [comment]
Same, I can't have in in the tray anymore ...

**Comment by Cafnio** [comment]
Same issue here

**Comment by Chinney** [comment]
Same here on Ubuntu 20.04.

**Comment by redking974** [comment]
I have the same issue since the last update. Windows 10

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/. Having said that:

This will be resolved with #2316. As a workaround please switch the tray icon off and on again in the preferences as described here: https://community.getmailspring.com/t/close-button-quits-mailspring-instead-of-minimizing-to-tray-even-though-there-is-icon-in-system-tray/1400

I will leave the issue open for now in order for this to be visible here on GitHub.

**Comment by iveselin** [comment]
@Phylu workaround works, thanks.

**Comment by ondrej-petr** [comment]
For me too, thanks.

**Comment by fsevenm** [comment]
On Ubuntu 18.04, I experienced this issue since updating to 1.9. The workaround worked. My steps: 1. Opened Mailspring; 2. Went to Edit → Preferences; 3. Unticked `Show icon in menu bar/system tray`; 4. Closed Mailspring; 5. Opened Mailspring again; 6. Ticked `Show icon in menu bar/system tray`.
