### ISSUE TITLE
Experiencing this on the new release 1.9.1

### ISSUE THREAD

**Issue by kevinmwalugha** [Foundry376/Mailspring#2320]
Seeing this issue as well with my Gmail account 

![screen shot 2018-09-18 at 9 54 50 am](https://user-images.githubusercontent.com/117500/45703363-f519e100-bb28-11e8-8e43-068a22fa3d6c.png)

_Originally posted by @onlydole in https://github.com/Foundry376/Mailspring/issues/918#issuecomment-422469010_

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
