### ISSUE TITLE
Blank Screen 

### ISSUE THREAD

**Issue by Swiftgti** [Foundry376/Mailspring#2321]
Hi I am in windows 10 latest updates and when I press the button to compose a new mail , new windows appears but the main window of mail spring gets in blank. 
The only way to see again the main windows is to minimize it and open again the window

it’s very annoying, also happens the same issue when you read an email that has an attachment and you have the option to show the icons of the attachments, I had to disable it and after a long time of why in some mails the screen was getting all blank. 

What do you need. For help you ?

**Comment by Swiftgti** [comment]
I confirm that this issues of blank screen appears when microsoft Edge browser is running, so if I close Edge browser mailspring works fine, but when I open Edge browser (my default browser ) again, all this blank screen issues starts again.

Some type of conflict exist, this is a really problematic issue for Windows users.

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
