### ISSUE TITLE
Selam sevgili admin Windows kullanıcısıyım. Mailspring 1.9.1. sürümünden sonra sorun yaşamaya başladım.

### ISSUE THREAD

**Issue by Craya07** [Foundry376/Mailspring#2328]

**Comment by Craya07** [comment]
İlk defa hata bildirdiğim için yanlışlıklar olmuş olabilir. kusura bakmayın. Yaşadığım sorun; genel maillerimi kontrol ederken sayfa bir anda beyaz oluyor. Uygulamayı kapatıp açtığımda bir şey değişmiyor. bende 1.8.0 versiyonunu indirip onu kullanıyorum. Sonraki gün bilgisayarımı açtığımda uygulama kendini güncellemiş oluyor. bu yaptığım işlemi bir daha ve bir daha bu şekilde devam ediyor.
sorunu anlayıp çözüme kavuşturursanız çok sevineceğim. şimdiden çok teşekkürler. güzel bir uygulama tebrikler

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
