### ISSUE TITLE
Update chocolatey Mailspring package

### ISSUE THREAD

**Issue by vairag22** [Foundry376/Mailspring#2329]
Update the Mailspring package on Chocolatey @bengotow. 
The [Chocolatey package](https://community.chocolatey.org/packages/mailspring) is version 1.3, but latest release is version 1.9.1

**Comment by vairag22** [comment]
However chocolatey does download and install the latest version. It's more or less an issue with the metadata stored in the package.

**Comment by vairag22** [comment]
But I am not sure if it **updates** to the latest version.
 When installing for the first time, the powershell script downloads and installs the latest version but it shows version 1.3. If metadata isn't updated in the package I wonder if Chocolatey will know that updates are available. 
This could be a potential security risk...

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
