### ISSUE TITLE
Composing reply to email

### ISSUE THREAD

**Issue by aamasri** [Foundry376/Mailspring#2330]
Mac OS 11.3, Mailspring 1.9.1

I like Mailspring, but like the other modern email clients (like Spark) it has some serious glitches that have gone unresolved for a long time.

If I click on reply to email and expand the "quoted text".  After a bit of editing, the editor starts interfering while I'm typing: whole sentences disappear suddenly, coinciding with the email scrolling to the bottom of the quoted content. Sometimes I can use undo to bring back the disappeared text, but as the problem recurs at an increasing frequency, I'm generally compelled to abandon Mailspring and use the native email client.

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
