### ISSUE TITLE
error when add new account

### ISSUE THREAD

**Issue by tanky91** [Foundry376/Mailspring#2333]
Waiting for Account JSON:

Waiting for Identity JSON:
info: Identity created at 1612131410 - using ID Schema 1

OPENSSL_Uplink(5886D878,08): no OPENSSL_Applink

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
