### ISSUE TITLE
In Arch Based Linux OS mailspring is saying lib secret cannot found but i have lib secret

### ISSUE THREAD

**Issue by Eshan-dev** [Foundry376/Mailspring#2335]
![Screenshot__1](https://user-images.githubusercontent.com/72184750/121505911-dd819580-ca00-11eb-933d-bdf0dce83896.png)

**Comment by CodeMouse92** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
