### ISSUE TITLE
Mailspring screen becomes white

### ISSUE THREAD

**Issue by ronavnery** [Foundry376/Mailspring#2337]
I'm running latest version of mailspring (1.9.1) on Windows 10 and very often mailspring becomes all white.
To fix the problem I need to restore down or minimize the window or restart the program - and it doesnt always work.

Is there a solution for this? This is really annoying , major bug.

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
