### ISSUE TITLE
How your app to be the default email client in macos

### ISSUE THREAD

**Issue by infeng** [Foundry376/Mailspring#2340]
I'm also developing a mac mail app, how Mailsprint to be the default email client, I don't know how to make my app appear in this list
<img width="564" alt="截屏2021-08-26 下午11 01 21" src="https://user-images.githubusercontent.com/16483610/130987117-e8dd6fcc-6605-4c3a-bb38-2aac0d37fc74.png">

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
