### ISSUE TITLE
Office365 - unable to Sync

### ISSUE THREAD

**Issue by jamie9090** [Foundry376/Mailspring#2342]
I'm on Mailsping Pro.

I'm using a domain e-mail address via Office365.

I am getting asked to re-authenticate constantly, even in the same session.

Is there anyway to fix this? 

Also, if there is any other way to get help for the paid service, I would appreciate that.

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.

Please check e.g. this thread here, which could be a similar issue: https://community.getmailspring.com/t/mailspring-needs-to-reconnect-my-gmail-account-every-time-i-log-in-my-computer/2327
