### ISSUE TITLE
No Autoresponder options?

### ISSUE THREAD

**Issue by krystianraj** [Foundry376/Mailspring#2343]
NO AUTORESPONDER? This is a joke... since half of a year I am using PRO version, now I am going to vacation and want to set autoresponders... NO SUCH option... really? PRO version of email client without autoresponder options? Any module for this? Guys, I am very dissapointed, and pissed off, that's why I have ignored your remarks about posting such messages to community forum. I've seen thread regarding autoresponder which is competely ignored. I am paying for this product and not willing to share my thoughts to community, who mostly uses free version and does not give a freak about it. Dissapointed a lot... XXI century PRO email client without autoresponder / vacation settings - please, say it's only a bad dream.

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
