### ISSUE TITLE
Print/Save as PDF not saving

### ISSUE THREAD

**Issue by ehula** [Foundry376/Mailspring#2347]
I am running Mailspring 1.9.2 on Linux (Manjaro). If I tap the 'Print' button, then 'Save as PDF', I am able to select a destination, but after I tap the 'Save' button, the file requester disappears but the PDF is not saved.

**Comment by Kalud-Z** [comment]
Im also having the same issue on Linux popOS

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
