### ISSUE TITLE
[Win10] Compose windows doesn't open on same screen as main window

### ISSUE THREAD

**Issue by rexbron** [Foundry376/Mailspring#2349]
On Windows 10, the compose window will open on the primary display, rather than the display that the main window of Mailspring is on.

The compose window should follow the main window when it is moved from one display to another.

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
