### ISSUE TITLE
Window elements are minuscule at full zoom

### ISSUE THREAD

**Issue by zach-is-my-name** [Foundry376/Mailspring#2353]
the app is barely legible at full zoom on my machine   
Would it be possible to just default to normal electron behavior and zoom with ctrl- + ctrl- - ?

PS I'm not registering to an external forum to report and track issues.  Let me know if this is a problem

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
