### ISSUE TITLE
Connection Error Unable to connect to the server / port you provided. (SMTP) Ubuntu 20.04 #2021

### ISSUE THREAD

**Issue by progmamun** [Foundry376/Mailspring#2354]
I can't log in to my Outlook account. If I try to connect to Gmail same issues I have seen. How could I solve these issues?
![Screenshot from 2021-11-08 11-51-51](https://user-images.githubusercontent.com/67066348/140691905-76c20382-907b-4221-a2ca-e4e8b695ccac.png)
here is the error log: 
----------IMAP----------
connect <mailcore::IMAPSession:0x7ffd54c5c8b0>
* OK The Microsoft Exchange IMAP4 service is ready. [UABOADMAUABSADAAMQBDAEEAMAAwADUAOQAuAEkATgBEAFAAUgBEADAAMQAuAFAAUgBPAEQALgBPAFUAVABMAE8ATwBLAC4AQwBPAE0A]
ssl connect imap-mail.outlook.com 993 2
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
connect ok
login
2 LOGIN "mamun@outlook.com" "*********"
2 OK LOGIN completed.
3 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
3 OK CAPABILITY completed.
4 NAMESPACE
* NAMESPACE (("" "/")) NIL NIL
4 OK NAMESPACE completed.
login ok
5 LIST "" "*"
* LIST (\HasNoChildren) "/" Archive
* LIST (\HasNoChildren \Trash) "/" Deleted
* LIST (\HasNoChildren \Drafts) "/" Drafts
* LIST (\Marked \HasNoChildren) "/" Inbox
* LIST (\HasNoChildren \Junk) "/" Junk
* LIST (\HasNoChildren) "/" Notes
* LIST (\HasNoChildren) "/" Outbox
* LIST (\HasNoChildren \Sent) "/" Sent
* LIST (\HasChildren) "/" "Sync Issues"
* LIST (\HasNoChildren) "/" "Sync Issues/Conflicts"
* LIST (\HasNoChildren) "/" "Sync Issues/Local Failures"
* LIST (\HasNoChildren) "/" "Sync Issues/Server Failures"
* LIST (\HasNoChildren) "/" Unwanted
5 OK LIST completed.

----------SMTP----------
connect smtp-mail.outlook.com 587

SASL_PATH: /snap/mailspring/506/usr/share/mailspring/resources/app.asar.unpacked

mailsmtp Last Error Code: 25
mailsmtp Last Error Explanation: MAILSMTP_ERROR_CONNECTION_REFUSED
mailsmtp Last Error Location: 1
mailsmtp Last Auth Type: 0

**Comment by idhyt** [comment]
The same problem with U, Use the following methods to solve it.

1. login hotmail in brower and into email setting (Microsoft Account Setting).
2. Securyty - App Password  - Create
3. Mailspring - Add Account - Outlook.com/Hotmail - Input U Email and App Password
4. Enjoy it!

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
