### ISSUE TITLE
Show "You" in senders of other associated email addresses

### ISSUE THREAD

**Issue by nelakay** [Foundry376/Mailspring#2358]
Hello,

I am having an issue that evolves as follows:

As a family, we have one email address that is common, everybody has access to it. However, only my husband uses it to send messages. Now, every time he sends an email from this email address to my regular email, the sender appears as "You", even though I haven't sent anything. This is confusing, and as I have 8 different email addresses to monitor, quite time consuming. 
Can I change this, so the display name for said email address appears in the header of the email?
Thank you.

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
