### ISSUE TITLE
Support GMail-like Tabs

### ISSUE THREAD

**Issue by jgindin** [Foundry376/Mailspring#236]
This didn't seem to make it over from the Nylas bug tracker, but there seemed to be a lot of interest:

https://github.com/nylas/nylas-mail/issues/698

**Comment by bengotow** [comment]
https://foundry376.zendesk.com/hc/en-us/articles/115001881952-Does-Mailspring-support-Categories-from-Gmail-or-Bundles-from-Google-Inbox-
