### ISSUE TITLE
Windows ARM64

### ISSUE THREAD

**Issue by edmondt** [Foundry376/Mailspring#2362]
Any chance we can get a build for ARM64 Windows? Need all the help I can get for Optimizing the Surface Pro X :)

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.

That being said, after the upgrade to Electron 14 (https://github.com/Foundry376/Mailspring/pull/2357), an arm build may be possible.
