### ISSUE TITLE
Can't send email without Draft folder

### ISSUE THREAD

**Issue by ggakwaya** [Foundry376/Mailspring#2363]
I can't send email from newly created imap account because the draft folder isn't created yet. Is it possible to have Mailspring create the missing folder in this situation? I'm not having this issue with thunderbird or outlook.

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
