### ISSUE TITLE
Toggling Contacts sidebar shows "Moved to Trash" notification

### ISSUE THREAD

**Issue by we3geeks** [Foundry376/Mailspring#237]
Toggling the Contacts sidebar either on or off causes the "Moved to Trash" notification to appear for a few seconds then disappear...

##### Are there any related issues?

I can't find any...

##### What operating system are you using?
macOS 10.13

##### What version of Mailspring are you using?
1.0.6

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Unknown; I have Mailspring working with just one account (Gmail).

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Does not seem to be specific to any particular message.

**Comment by bengotow** [comment]
Wow you're totally right... that's whacky.

**Comment by we3geeks** [comment]
@bengotow If it matters (or makes sense), I am no longer seeing this behavior after updating to v1.0.8?

**Comment by bengotow** [comment]
Hey! Thanks for following up—this should be fixed in 1.0.8!
