### ISSUE TITLE
We encountered a problem with your local email database. Error" on install

### ISSUE THREAD

**Issue by gldtn** [Foundry376/Mailspring#2374]
Version 1.10

I'm having this problem after trying to update to latest version

Can't rebuild better_sqlite3.node

I tried uninstalling and remove all mailspring folders on my user dir, restarted computer and tried installing again. I'm still getting the same error.

**Comment by Refzlund** [comment]
Same, when trying to update.

**Comment by DanyGee** [comment]
Same here.

**Comment by Phylu** [comment]
Duplicate of #2373.

**Comment by GMan69101** [comment]
I am having this problem on Windows 11 since an update to the OS yesterday.  I have elementary on my thinkpad and that has no errors on Mailspring. IS anyone attending to this?  I have premium and am paying for the service but there is no support.

**Comment by AhoyLemon** [comment]
+1 for this. Looks like mine is also related to Windows 11 update.
