### ISSUE TITLE
v1.10 completely broken on windows

### ISSUE THREAD

**Issue by TomMann** [Foundry376/Mailspring#2376]
goes into an endless loop of popups saying

We encountered a problem with your local email database. We will now attempt to rebuild it.

Error:
\\?\C:\Users\Username\AppData\Local\Mailspring\app-1.10.0\resources\app....\better_sqlite3.node is not a valid Win32 application.

reinstall doesnt help, only fix is to revert to previous version.

**Comment by Soahr** [comment]
Same here ! Not fixed

**Comment by chris-aeviator** [comment]
I think this issue should stay open.

**Comment by BenjaminHoegh** [comment]
this is indeed still a problem on both windows and Mac
