### ISSUE TITLE
SPELL CHECK DOESN'T WORK!

### ISSUE THREAD

**Issue by marijanprivate** [Foundry376/Mailspring#2381]
Why can't you address this issue? God-damn it, like a lot of users report that spell checking doesn't work and still nothing has been done yet. I know I shouldn't open an issue here, but I don't care, simply as you devs also do not care, especially where I'm paying $8 per month.

**Comment by i-zanis** [comment]
Thank you for opening an issue.

I am currently experiencing the same issue.

**Comment by marijanprivate** [comment]
Literally guys have opened bug reports on the forum, and they all are being ignored, so what's the point? Spell Checking should be essential, even the low quality text editors or any other typing systems have working spell checkers. Please address this issue ASAP.
