### ISSUE TITLE
Notifications, Email opens, clicks dont work

### ISSUE THREAD

**Issue by sirtakinos** [Foundry376/Mailspring#2389]
Hello,

After the update email opens, new email notifications, links clicks don't work. 

I am running Mailspring on WIN10 and MacOS both have same issue after 1.10 updates.

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.

Please also provide a better description on the issue.
