### ISSUE TITLE
[Enhancement] Drafts should always be treated as unread / number should appear in left sidebar

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#239]
##### Are there any related issues?

...

##### What operating system are you using?
MacOS 10.12.6

##### What version of Mailspring are you using?
1.0.6

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
I'd suggest Mailspring mimics Gmail's behavior here, so that you can remember when you've got drafts. Basically I think the number of drafts should always show up as a number on the left hand pane, just like unread emails in the inbox.

**Comment by bengotow** [comment]
Hey folks! It's been a few years and there haven't been any more reports of this issue so I'm going to close this as probably-fixed. Feel free to bump or create a new issue referencing this one if you encounter this again!
