### ISSUE TITLE
Mailbox Not Synching for Gmail

### ISSUE THREAD

**Issue by SNajm** [Foundry376/Mailspring#2394]
I installed Mailspring and installed the latest version on my Zorin OS 16
Initially the mail was downloading.

but then all of a sudden it stopped and it won't download anything. 

Where are the logs that I can paste for you here ?

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
