### ISSUE TITLE
Wikipedia article

### ISSUE THREAD

**Issue by paulvi** [Foundry376/Mailspring#2397]
It quite a while to find this really FOSS multiplatform client.

For future and other searching, an article on Wikipedia would help.
Currently only https://en.wikipedia.org/wiki/Nylas_Mail references it.

But I think it is good enough to be even email clients summary
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/1614482/165340001-22f2b60c-638a-4e2c-bfde-7ba45851650e.png">

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.

Having that said, feel free to create a Wikipedia article about it if you think that it would be helpful. Any support is highly appreciated.
