### ISSUE TITLE
rich text editor does not work with empty signature 

### ISSUE THREAD

**Issue by nixoid** [Foundry376/Mailspring#2398]
When the signature for an account is empty / not configured, most of the times click on the message body does not move focus to the editor, making it impossible to start writing a message.

It is only reproducible when composing new message - works fine for replies.
Also works fine in text mode or when signature is not empty.

It probably has something todo with the dimensions of the invisible editable area.

Mailspring version: Version 1.10.3 (1.10.3)
OS version: MacOS Monterey 12.3 (21E230)

**Comment by nixoid** [comment]
Assigning a default signature to an account fixes the issue, but i don't necessary want to have signatures for all accounts

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
