### ISSUE TITLE
Yandex Authentication Error: Yandex requires phone number verification before connecting to Mailspring

### ISSUE THREAD

**Issue by hotrush** [Foundry376/Mailspring#240]
##### Are there any related issues?
https://github.com/Foundry376/Mailspring/issues/71
...

##### What operating system are you using?
Linux Mint 17.3
... 

##### What version of Mailspring are you using?
...
1.0.6-9448c994
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Yandex PDD - post for domain
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Log here:

----------IMAP----------
* OK Yandex IMAP4rev1 at imap29j.mail.yandex.net:993 ready to talk with ::ffff:46.216.50.103:36322, 2017-Oct-24 00:46:25, PkTROU1bQiE1
q1 CAPABILITY
* CAPABILITY IMAP4rev1 CHILDREN UNSELECT LITERAL+ NAMESPACE XLIST BINARY UIDPLUS ENABLE ID AUTH=PLAIN AUTH=XOAUTH2 IDLE MOVE
f:46.216.5Q1 OK CAPABILITY Completed.
2 LOGIN "romaxxx@anxxxb.ru" *********
* CAPABILITY IMAP4rev1 CHILDREN UNSELECT LITERAL+ NAMESPACE XLIST BINARY UIDPLUS ENABLE ID IDLE MOVE
2 OK LOGIN Completed.
ff:46.216.53 NAMESPACE
* NAMESPACE (("" "|")) NIL NIL
03 OK NAMESPACE Completed.
4 ID NIL
* ID ("name" "Yandex Mail" "vendor" "Yandex" "support-url" "http://feedback.yandex.ru/?from=mail")
4 OK ID Completed.
5 XLIST "" "*"
* XLIST (\Unmarked \HasChildren ) "|" Archives
* XLIST (\Unmarked \HasNoChildren ) "|" "Archives|2017"
* XLIST (\Unmarked \HasNoChildren \Drafts \Drafts) "|" Drafts
* XLIST (\Unmarked \NoInferiors \Inbox) "|" INBOX
* XLIST (\Unmarked \HasNoChildren ) "|" N1-Snoozed
* XLIST (\Unmarked \HasNoChildren ) "|" Outbox
* XLIST (\Unmarked \HasNoChildren \Sent \Sent) "|" Sent
* XLIST (\Unmarked \HasNoChildren \Junk \Spam) "|" Spam
* XLIST (\Unmarked \HasNoChildren \Trash \Trash) "|" Trash
S ENABLE ID�5 OK XLIST Completed.

----------SMTP----------
220 smtp1j.mail.yandex.net ESMTP (Want to use Yandex.Mail for your domain? Visit http://pdd.yandex.ru)
��pw_�ԀEHLO Rush-Laptop
250-smtp1j.mail.yandex.net
250-8BITMIME
250-PIPELINING
250-SIZE 42991616
250-AUTH LOGIN PLAIN XOAUTH2
250-DSN
250 ENHANCEDSTATUSCODES

SMTP Last Response Code: 250

SMTP Last Response: smtp1j.mail.yandex.net
8BITMIME
PIPELINING
SIZE 42991616
AUTH LOGIN PLAIN XOAUTH2
DSN
ENHANCEDSTATUSCODES

mailsmtp Last Error Code: 17

mailsmtp Last Error Location: 10
...

Same error was in latest versions of Nylas and that because i returned back to Thunderbird :(

**Comment by bengotow** [comment]
Hey! Everything in the logs actually looks OK - I think you might be getting this error because your machine doesn't trust the SMTP server's SSL certificate. Could you try again but check the "Insecure SSL" checkbox in the IMAP/SMTP settings?

**Comment by hotrush** [comment]
Hi @bengotow, i have tried it with diffrenet ports and with insecure ssl checkbox checked. Also it works with thunderbird and geary.
![1508918065572](https://user-images.githubusercontent.com/1247004/31986965-e8d78928-b972-11e7-9562-b137017c2bde.jpg)
Maybe i can add their cert somehow?

**Comment by gocarlos** [comment]
The same is happening to my university mail address: mail.ethz.ch

with the official settings: https://www.isg.inf.ethz.ch/Main/HelpMailClientSetup
on Gnome Geary works... 

----------IMAP----------
* OK The Microsoft Exchange IMAP4 service is ready.
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN UIDPLUS CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
2 LOGIN gocarlos "*******"
2 OK LOGIN completed.
3 CAPABILITY
d.* CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN UIDPLUS CHILDREN IDLE NAMESPACE LITERAL+
3 OK CAPABILITY completed.
4 NAMESPACE
* NAMESPACE (("" "/")) NIL NIL
4 OK NAMESPACE completed.
TAK5 LIST "" "*"
* LIST (\HasNoChildren) "/" Archive
* LOTS OF LISTS HERE
* LIST (\HasNoChildren) "/" "asdfasdfsafd"
5 OK LIST completed.
�U9�

----------SMTP----------
220 mail.ethz.ch Microsoft ESMTP MAIL Service ready at Sun, 29 Oct 2017 19:10:16 +0100
QEHLO gocarlos-tp260
250-mail.ethz.ch Hello [213.55.184.244]
250-SIZE 31457280
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-AUTH GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250 CHUNKING
STARTTLS
los-tp260
220 2.0.0 SMTP server ready
EHLO gocarlos-tp260
�5�250-mail.ethz.ch Hello [213.55.184.244]
250-SIZE 31457280
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH GSSAPI NTLM LOGIN
250-8BITMIME
250-BINARYMIME
250 CHUNKING

SMTP Last Response Code: 250

SMTP Last Response: mail.ethz.ch Hello [213.55.184.244]
SIZE 31457280
PIPELINING
DSN
ENHANCEDSTATUSCODES
AUTH GSSAPI NTLM LOGIN
8BITMIME
BINARYMIME
CHUNKING

mailsmtp Last Error Code: 17

mailsmtp Last Error Location: 10

**Comment by gocarlos** [comment]
This happens also with another mail provider:: 
hoststar, https://www.hoststar.ch/en/support/mail/set-up/general-configuration 

----------IMAP----------
* OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE AUTH=PLAIN ACL ACL2=UNION] Courier-IMAP ready. Copyright 1998-2011 Double Precision, Inc.  See COPYING for distribution information.
1 LOGIN "carlos@martinho.ch" "*********"
1 OK LOGIN Ok.
���2 CAPABILITY
* CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE AUTH=PLAIN ACL ACL2=UNION
2 OK CAPABILITY completed
3 NAMESPACE
* NAMESPACE (("INBOX." ".")) NIL (("#shared." ".")("shared." "."))
3 OK NAMESPACE completed.
formation.4 LIST "INBOX." "*"
* LIST (\HasNoChildren) "." "INBOX.Junk"
* LIST (\HasNoChildren) "." "INBOX.spam"
* LIST (\HasNoChildren) "." "INBOX.Trash"
* LIST (\HasNoChildren) "." "INBOX.Sent"
* LIST (\HasNoChildren) "." "INBOX.Drafts"
4 OK LIST completed
�>�5 LIST "" "INBOX"
* LIST (\Unmarked \HasChildren) "." "INBOX"
5 OK LIST completed
�

----------SMTP----------
220 tux197.hoststar.ch ESMTP Sendmail 8.14.9/8.12.11; Fri, 17 Nov 2017 10:31:34 +0100
EHLO gocarlos-rrch07
250-tux197.hoststar.ch Hello 46-140-56-115.static.cablecom.ch [46.140.56.115] (may be forged), pleased to meet you
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-8BITMIME
250-SIZE 52430000
250-DSN
250-AUTH LOGIN PLAIN
250-DELIVERBY
250 HELP

SMTP Last Response Code: 250

SMTP Last Response: tux197.hoststar.ch Hello 46-140-56-115.static.cablecom.ch [46.140.56.115] (may be forged), pleased to meet you
ENHANCEDSTATUSCODES
PIPELINING
8BITMIME
SIZE 52430000
DSN
AUTH LOGIN PLAIN
DELIVERBY
HELP


mailsmtp Last Error Code: 17

mailsmtp Last Error Location: 10

**Comment by hotrush** [comment]
@bengotow i think you should confirm this bug. Can make an account on yadex mail for domains for you to reproduce

**Comment by svechinsky** [comment]
Having the same issue with my own remote hosted mail server. 
Anyone happen found a solution for this?

**Comment by hotrush** [comment]
@svechinsky yes, thunderbid)

**Comment by svechinsky** [comment]
@hotrush Just updating that after using the snap version (as opposed to the deb pacakge) it works fine

**Comment by hotrush** [comment]
@svechinsky lucky boy, still not works for me at 1.0.10

**Comment by bengotow** [comment]
Hey folks—just wanted to follow up here. I created a Yandex account and attempted to use it with Mailspring. I got an error and clicked "View Log" from the IMAP/SMTP settings dialog.

The log contains this warning:
```
535 5.7.8 Error: authentication failed: Your message looks like spam. You need to use web for sending or prove you are not a robot using the following link http://ya.cc/6lIh

SMTP Last Response Code: 535
```

Basically, Yandex will not allow you to send mail through their SMTP gateway unless you've added a phone number to your account or otherwise verified it. After I entered my phone number and was texted a confirmation code, I was able to re-try the account settings successfully and use Mailspring.

I'll see if I can fix this in the future - we really should detect this error and display it instead of the generic "Authentication Error".

**Comment by hotrush** [comment]
Hi @bengotow, thanks for your response, but i have another error in log) It returns error code 17 and my account has verified phone number.

**Comment by hotrush** [comment]
@bengotow, FYI, i am using deeping 15.5 now that based on debian 8 and can't see this bug, so it might relate to linux mint only

**Comment by WEB-MOLOT** [comment]
----------IMAP----------
* OK Yandex IMAP4rev1 at imap8p.mail.yandex.net:993 ready to talk with ::ffff:37.146.133.167:59055, 2018-May-05 19:05:07, 75WV3Hj1x3uQ1
1 CAPABILITY
* CAPABILITY IMAP4rev1 CHILDREN UNSELECT LITERAL+ NAMESPACE XLIST BINARY UIDPLUS ENABLE ID AUTH=PLAIN AUTH=XO3A3UTH2 IDLE MOVE
1 OK CAPABILITY Completed.
2 LOGIN LOGIN "*********"
2 NO [AUTHENTICATIONFAILED] LOGIN Invalid credentials or IMAP is disabled sc=75WVHj1xJuQ31_0516305_8p

**Comment by bengotow** [comment]
Merging this in to #620

**Comment by suzglorious** [comment]
hi @bengotow i'm having the same error.
I already linked my phone number and enabled app passwords. please help! :(

**Comment by tonyAndr** [comment]
@suzglorious I had the same problem with Geary (Gnome3/Manjaro). Imap login was succesful, but SMTP always answers with error that I have to add a phone number, which was added long ago...
Looks like a bug on Yandex's side with some mail clients because I see no issues with thunderbird on Windows. In the end I end up using gmail which imports from yandex everything, and then added gmail in Geary
