### ISSUE TITLE
indicator in tray icon

### ISSUE THREAD

**Issue by x-tropic** [Foundry376/Mailspring#2401]
Unread message indicator in tray icon on WIndows 10 is too small.
Could you make it bigger? Or better yet, make it the number of unread mail.
Thanks for answer.

**Comment by x-tropic** [comment]
1920x1080, "27.
![06 06 - 14-57_zu](https://user-images.githubusercontent.com/46036927/172156294-4e01cde5-2c2c-46d4-bf33-6a43a75b0167.jpg)

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
