### ISSUE TITLE
Mailspring Issues Flagged - Not reaching destination - certificate for community site expired on 06/04/2022 so cannot open ticket there

### ISSUE THREAD

**Issue by bravovictor42** [Foundry376/Mailspring#2404]
The links entered into emails that go to Mailspring and then redirect are getting flagged and then never opening in the mail client. They get stuck on exceptions in the web browser.

Furthermore, tracking is not working. In testing, I can respond to an email that is set to not interfere with downloading of linking, tracking pixels, etc., and even upon response to that email, Mailspring still tells me the message was not read. Obviously, the message was read if it has been replied to. 

I can no longer trust emails to get through utilizing Mailspring, please advise.

**Comment by LulzSecToolkit** [comment]
the same prob

**Comment by edgyelle** [comment]
Same. I tried emailing re: security. I just purchased the license. Unless I know the site and application are secure, despite reviews, I have to cancel my subscription. Unfortunately, I can't afford a security fiasco.

**Comment by Phylu** [comment]
I suspect this is due to: https://github.com/Foundry376/Mailspring/issues/2403
So it should be resolved by now.
