### ISSUE TITLE
Error Message when i connect my account "Authentication error - Check your username and password (IMAP)View Log" 

### ISSUE THREAD

**Issue by Jamsrooo** [Foundry376/Mailspring#2406]
## Objective

THIS IS THE MESSAGE THAT I RECEIVE 

connect <mailcore::IMAPSession:00CFF7D0>

* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS MOVE SNIPPET=FUZZY PREVIEW=FUZZY STATUS=SIZE SAVEDATE LITERAL+ QUOTA AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
ssl connect ....mail........ 993 2
connect ok
login
1 LOGIN "....mail........." "*********"
1 NO [AUTHENTICATIONFAILED] Authentication failed.

Thanks a lot for your help mailspring community

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
