### ISSUE TITLE
Bug adding an account

### ISSUE THREAD

**Issue by clover-es** [Foundry376/Mailspring#241]
Hello, I was just trying this software, when I had this issue trying to add an account:
![image](https://user-images.githubusercontent.com/15948561/31916872-06ddfa66-b855-11e7-8a0c-741541ecf2f2.png)

##### What operating system are you using?
Windows 10 x64

##### What version of Mailspring are you using?
1.0.6-9448c884

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I don't know yet

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I think it's very likely because I mistakenly put same server for outbound messages.

**Comment by pedzed** [comment]
```
Waiting for Account JSON:

Waiting for Identity JSON:

 ***
 *** A segmentation fault occurred during program execution.
 *** This typically happens when you try to dereference a pointer
 *** that is NULL or invalid.
 ***
19955 [2017-10-24 09:16:55.486] [main] [critical]  *** Stack trace (line numbers are approximate):
 *** in mailsync     logger(mailimap*, int, char const*, unsigned long, void*)
 *** in mailsync     mailstream_low_read
 *** in mailsync     mailstream_feed_read_buffer
 *** in mailsync     mailstream_read_line_append
 *** in mailsync     mailimap_connect
 *** in mailsync     mailcore::IMAPSession::connect(mailcore::ErrorCode*)
 *** in mailsync     runTestAuth(__1::shared_ptr)
 *** in mailsync     main
 *** 0x7fff96afb235  start
 ***
```

**Comment by westr029** [comment]
I have the same here on Ubuntu 16.04. 
Want to connect to an exchange server via imap.
![screenshot from 2017-10-24 10-58-50](https://user-images.githubusercontent.com/25100691/31933797-78ab5544-b8aa-11e7-941d-bd66b416ca48.png)

**Comment by pkerschbaum** [comment]
Same here on Windows 10 x64

**Comment by bengotow** [comment]
Hey! Thanks for reporting this–will see if I can reproduce this. Looks like it's specific to a handful of email providers.

**Comment by pkerschbaum** [comment]
Retest OK on my side:

I downloaded version 1.0.7-664204d8 and could successfully add the SMTP account.

**Comment by westr029** [comment]
Deformation is not happening again, this is redirected to a log-file. However, the same error is occuring and I can still not add an account after installing version 1.0.7-664204d8.

**Comment by bengotow** [comment]
Hey @westr029 —hmm, interesting... is it complaining specifically about your SMTP setup now? This crash was happening when a certain kind of SMTP error occurred, so you should probably check your SMTP settings. I notice in the screenshot your provider is using secure IMAP but the old, insecure port for SMTP. Maybe try switching that and see if the secure port works?

**Comment by westr029** [comment]
Hi @bengotow : I have indeed the feeling that it has to do with my SMTP setup. I basically tried all combinations possible and they all gave an error, see below for summary of log file:
- SSL/TLS:p25
  - IMAP: seems OK
  - SMTP: gives `mailsmtp Last Error Code: 27` and `mailsmtp Last Error Location: 5`
- SSL/TLS:p465
  - IMAP: seems OK
  - SMTP: gives `mailsmtp Last Error Code: 25` and `mailsmtp Last Error Location: 5`
- SSL/TLS:p587
  - IMAP: seems OK
  - SMTP: gives `mailsmtp Last Error Code: 25` and `mailsmtp Last Error Location: 5`
- STARTTLS:p465
  - IMAP: seems OK
  - SMTP: gives `mailsmtp Last Error Code: 25` and `mailsmtp Last Error Location: 1`
- STARTTLS:p587
  - IMAP: seems OK
  - SMTP: gives `mailsmtp Last Error Code: 25` and `mailsmtp Last Error Location: 1`
- STARTTLS:p25 (takes much longer before error shows up), which gives the following error in the UI *An unexpected mailsync error occurred (139)*. The log file you can find below:
```

Waiting for Account JSON:

Waiting for Identity JSON:

 ***
 *** A segmentation fault occurred during program execution.
 *** This typically happens when you try to dereference a pointer
 *** that is NULL or invalid.
 ***
11553 [2017-11-08 09:51:59.858] [main] [critical]  *** Stack trace (line numbers are approximate):
 *** ??:?                     AccumulatorLogger::log(void*, mailcore::ConnectionLogType, mailcore::Data*)
 *** mailstream_low.c:244     mailstream_low_read
 *** mailstream.c:306         mailstream_feed_read_buffer
 *** mailstream_helper.c:102  mailstream_read_line_append
 *** mailstream_helper.c:116  mailstream_read_line_remove_eol
 *** mailsmtp.c:1413          mailesmtp_auth_sasl
 *** ??:?                     mailcore::SMTPSession::login(mailcore::ErrorCode*)
 *** ??:?                     mailcore::SMTPSession::loginIfNeeded(mailcore::ErrorCode*)
 *** ??:?                     mailcore::SMTPSession::checkAccount(mailcore::Address*, mailcore::ErrorCode*)
 *** ??:?                     runTestAuth(shared_ptr)
 *** ??:?                     main
 ***

/usr/share/mailspring/resources/app.asar.unpacked/mailsync: line 4: 11553 Segmentation fault      (core dumped) SASL_PATH="$(dirname $(realpath $0))" LD_LIBRARY_PATH="$(dirname $(realpath $0));$LD_LIBRARY_PATH" "$(dirname $0)/mailsync.bin" "$@"
```
I tried to find out what the mailsmtp errors are, but could not figure it out.
It is quite some information, but I hope you can help me fixing this.

Thanks!!
