### ISSUE TITLE
HTPPS down - everything is down

### ISSUE THREAD

**Issue by doctorrrrrrrr** [Foundry376/Mailspring#2410]
The https is down on https://getmailspring.com/ - It seems it also disconnect all inboxes of the Macbook App and we're not able to connect at all anymore

**Comment by mel-geo** [comment]
same

**Comment by ragnargwyn** [comment]
Same

**Comment by EdTorbett** [comment]
I'm affected by this too. Signing out of your mailspring account in settings appears to get the inbox sync working again.

**Comment by Phylu** [comment]
I have informed @bengotow who is responsible of the server in question, directly. This should be resolved soon.

Thanks a lot for reporting it!

**Comment by doctorrrrrrrr** [comment]
> I'm affected by this too. Signing out of your mailspring account in settings appears to get the inbox sync working again.

It worked for me as well, thank you!

**Comment by initmd** [comment]
Same here, can't run the install script, is there a certificate issue?

**Comment by luckydays** [comment]
Yeah, the SSL certificate got expired some hours ago. Hopefully, it'll be prolonged soon.
<img width="530" alt="Monosnap 2022-06-28 14-43-41" src="https://user-images.githubusercontent.com/10942891/176181511-405fd32b-8399-4eb1-9c53-03fa03553421.png">

**Comment by LoboCreative** [comment]
Yep down for us as well! @bengotow is this something you can look at?

**Comment by choloclos** [comment]
+1

**Comment by jcraig999** [comment]
It's still a little buggy. Had to reset my password, and at first it would not take. Then, when it finally took, the page would not load on the app for me to sign in to my ID. Then, I closed the app and it did the same thing. For some reason, I had to reset my password a second time for it to take. And when I did it the second time there were graphical glitches on the website https://id.getmailspring.com. However, after I reset my password the second time everything loaded fine.

**Comment by Jellouse** [comment]
thanks! back to normal

**Comment by Phylu** [comment]
Thanks again for all the reports. Closing this here as it has been resolved.

**Comment by Dahaniel** [comment]
Did this happen again? id.getmailspring.com is not accessible and thus I cannot setup mailspring on my new PC at work

**Comment by madmax755** [comment]
same

**Comment by bengotow** [comment]
Hey folks thanks for reporting this - it looks like our provider had a small incident on May 23 (https://status.flyio.net/), and Mailspring's servers needed to be manually restarted after it was resolved. I emailed asking why they didn't auto-restart since their health checks were failing, will see what we can do to prevent this happening again.

**Comment by CRCinAU** [comment]
The discourse server also seems to be down.

**Comment by bengotow** [comment]
Hey @CRCinAU thanks for flagging this - I took the community site down over the weekend to apply all the system updates + discourse upgrades. The site had started getting some spam, and I believe it was because we needed to upgrade to the latest version.  It's all back in place now 👋
