### ISSUE TITLE
Deleted messages still show in inbox

### ISSUE THREAD

**Issue by allanmcpherson** [Foundry376/Mailspring#2413]
When I delete a message from my inbox, it's not removed from the inbox. When I click on the message, it says that it's been moved to the trash or spam. It does this regardless of whether I delete the message by selecting it or opening it and clicking the delete button or using the keyboard shortcut.

Linux Mint 20.3 Cinnamon
Version 1.10.3-a476c230

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
