### ISSUE TITLE
Capture Keyboard Input in folder/label dropdowns faster

### ISSUE THREAD

**Issue by jGleitz** [Foundry376/Mailspring#242]
##### Are there any related issues?
Couldn’t find any.

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.0.6

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no

##### Is the issue reproducible with a particular attachment, message, signature, etc?
no

**Feature Request?**

If I use the keyboard shortcut to move a message (<kbd>l</kbd> in the Gmail keymap), I type the name of the folder directly aftewards and hit Enter (after confirming with a quick glance that the correct folder is selected). This is the workflow I’m used to from other clients.

Mailspring, on the other hand, has a little delay until the folder selector is shown, which is no problem on its own. However, Mailspring only captures the keyboard input after the selector is shown. Thus, my first few keystrokes are often lost because I forget to wait for the selector.

I suggest to find a way to capture the keyboard input directly (like in an input box off-screen), so that no keystrokes are lost until the selector is shown.

In the cast below, i was hitting <kbd>l</kbd> and typed “Newsle” to put the mail in my Newsletter folder. However, Mailspring only captured “wesle” and hence did not find the folder.

![folder type](https://user-images.githubusercontent.com/4305652/31940662-4398f19e-b8bf-11e7-883f-e0011f843d77.gif)

##### Does this feature exist in another mail client or tool you use?
Thunderbird (with quick-folder-move add-on)

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
