### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by JamieSlome** [Foundry376/Mailspring#2427]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@ogianatiempo) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by bengotow** [comment]
Hey hey! Ahh I can definitely add a SECURITY.md to the repo, I think it's over at https://getmailspring.com/security and just needs to be mirrored here. Please feel free to email any security-related concerns to security@foundry376.com. I read everything that comes through that mailbox and we've fixed several issues that have been raised in the past. Thank you for the work you do in the OSS community!

**Comment by Phylu** [comment]
The file has been added as https://github.com/Foundry376/Mailspring/blob/master/SECURITY.md
