### ISSUE TITLE
Can't install .deb nor dependencies

### ISSUE THREAD

**Issue by BarbzYHOOL** [Foundry376/Mailspring#2430]
Guys, I knwo it's not proper but i have a github account and not an account on your forum where my post will be probably ignored.

I just downloaded the .deb and it doesn't work on PopOS 22.04

```
sudo apt install ./mailspring-1.10.5-amd64.deb                                                                                       0.9s|00:14:17
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 mailspring : Depends: libsecret-1-dev but it is not installed
              Depends: gconf2
              Depends: gconf-service
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```
------------------------------------------------------------------------------------------------

```
sudo apt install libsecret-1-dev gconf2 gconf-service                                                                              0.7s|01:35:16
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 gconf-service : Depends: gconf-service-backend (= 3.2.6-7ubuntu2) but it is not going to be installed
 gconf2 : Depends: libgconf-2-4 (>= 3.2.6-7ubuntu2) but it is not going to be installed
          Depends: gconf-service-backend (= 3.2.6-7ubuntu2) but it is not going to be installed
 libsecret-1-dev : Depends: libgcrypt20-dev (>= 1.2.2) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

impossible to install the dependencies

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.

Nonetheless:
* Have you tried? `apt --fix-broken install`
* As an alternative, you may want to try the snap version of mailspring.

**Comment by BarbzYHOOL** [comment]
@Phylu I've tried on a live ISO of POPOS (with nothing but barebones POP OS) and same exact issue
But then I did "apt --fix-broken install" and it worked, thought I should not have to do that :)

I also tried another approach, using pacstall and it worked flawlessly, i'm gonna do that I guess
