### ISSUE TITLE
Spell Check Still Not Working

### ISSUE THREAD

**Issue by JimmyLaslo** [Foundry376/Mailspring#2434]
1st off thanks to all the people that work on the best email client for windows.  For the last several versions, spell check does not work in the body of email.  Ironically, spell check does work in the subject heading.

I hope this can be addressed in a future update.
![20221111_183735](https://user-images.githubusercontent.com/86624872/201445626-abac231e-0d37-4747-ac2a-2d92b3409002.jpg)
![20221111_184123](https://user-images.githubusercontent.com/86624872/201445628-2d6163a5-adb4-4d6b-ab3b-9114cce65b82.jpg)

**Comment by Safibulae** [comment]
I have the same exact issue. Curiously, if I uncheck "rich text and advanced editor" in Preferences > General, spell check works (screenshots below), but this is not an ideal workaround. Would someone please help us Windows Mailspring users?

![Screenshot 2023-01-20 073529](https://user-images.githubusercontent.com/117452434/213675196-db58add5-b277-4307-9bbf-66ab48f04321.jpg)

![Screenshot 2023-01-20 073253](https://user-images.githubusercontent.com/117452434/213675152-bdf0590f-9b02-4d4e-b6c9-b7bef4941c19.jpg)

**Comment by petersaints** [comment]
This was the number one reason why I tried Mailspring and dumped in less than a day. I was actually liking it but the lack of proper spell checking is just a deal breaker. Please fix it.

**Comment by RobMalan1946** [comment]
very poor taht spellcheck does not work I paid for this useless mail client.

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.

The spellchecking issue is tracked here: https://community.getmailspring.com/t/spell-check-not-working/4762/19

**Comment by ojshakewell** [comment]
> This was the number one reason why I tried Mailspring and dumped in less than a day. I was actually liking it but the lack of proper spell checking is just a deal breaker. Please fix it.

Nearly three years later an this still hasn't been fixet yet. WTF?
