### ISSUE TITLE
SMTP authentication error reported by riseup.net

### ISSUE THREAD

**Issue by mrscottie** [Foundry376/Mailspring#2435]
The log shows SMTP authentication is successful; however, the recipient domain is not found, which is causing the addition of the email account to fail.

----------IMAP----------
connect <mailcore::IMAPSession:0x7ffe3dbacdd0>
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] howdy, ready.
ssl connect mail.riseup.net 993 2
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
connect ok
login
1 LOGIN scot "*********"
1 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY LITERAL+ NOTIFY SPECIAL-USE COMPRESS=DEFLATE QUOTA] Logged in
2 COMPRESS DEFLATE
2 OK Begin compression (0.001 + 0.000 secs).
3 ENABLE QRESYNC
* ENABLED QRESYNC
3 OK Enabled (0.001 + 0.000 secs).
4 NAMESPACE
* NAMESPACE (("" ".")) NIL NIL
4 OK Namespace completed (0.001 + 0.000 secs).
login ok
5 LIST "" "*"
* LIST (\Noselect \HasChildren) "." Mailspring
* LIST (\HasNoChildren \UnMarked) "." Mailspring.Snoozed
* LIST (\HasNoChildren \UnMarked) "." Archive
* LIST (\HasNoChildren \UnMarked) "." Spambox
* LIST (\HasNoChildren \UnMarked) "." Queue
* LIST (\HasNoChildren \UnMarked \Junk) "." Spam
* LIST (\HasNoChildren \UnMarked \Sent) "." Sent
* LIST (\HasNoChildren \UnMarked \Drafts) "." Drafts
* LIST (\HasNoChildren \Marked \Trash) "." Trash
* LIST (\HasNoChildren) "." INBOX
5 OK List completed (0.002 + 0.000 + 0.001 secs).

----------SMTP----------
220 fews2.riseup.net ESMTP (spam is not appreciated)
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
init
EHLO arch
250-fews2.riseup.net
250-PIPELINING
250-SIZE 25600000
250-ETRN
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250-SMTPUTF8
250 CHUNKING
AUTH PLAIN c2NvdABzY290AEFiMGwxc2hBbGxTdGF0ZSQh
235 2.7.0 Authentication successful
MAIL FROM:<scot@riseup.net>
250 2.1.0 Ok
RCPT TO:<email@invalid.com>
450 4.1.2 <email@invalid.com>: Recipient address rejected: Domain not found

SASL_PATH: /usr/share/mailspring/resources/app.asar.unpacked

SMTP Last Response Code: 450
SMTP Last Response: 4.1.2 <email@invalid.com>: Recipient address rejected: Domain not found

Mailspring 1.10.6-1
Arch Linux - kernel 6.1.0-rc4-1-mainline

**Comment by dale76uk** [comment]
same here; tried both Linux and windows with the same reported error. had to abandon and switch to bluemail.

log:- personal info redacted

----------IMAP----------
connect <mailcore::IMAPSession:0x7ffe2c3add90>
* OK [CAPABILITY IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL- MOVE NAMESPACE QUOTA SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN AUTH=LOGIN AUTH=PLAIN] IMAP server ready H mieue008 22.3 IMAP-1MtgiN-1pFhKb2xGJ-00vBWE
ssl connect imap.1and1.co.uk 993 2
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
connect ok
login
1 LOGIN "xxxxxxx@xxxxxxxx.co.uk" "*********"
1 OK LOGIN completed
2 CAPABILITY
* CAPABILITY IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL- MOVE NAMESPACE QUOTA SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN APPENDLIMIT=140000000
2 OK CAPABILITY completed
3 NAMESPACE
* NAMESPACE (("" "/")) NIL NIL
3 OK NAMESPACE completed
login ok
4 LIST "" "*"
* LIST (\HasNoChildren) "/" Denmans
* LIST (\Drafts \HasNoChildren) "/" Drafts
* LIST (\HasNoChildren) "/" INBOX
* LIST (\HasChildren) "/" Mailspring
* LIST (\HasNoChildren) "/" Mailspring/Snoozed
* LIST (\HasNoChildren) "/" Notes
* LIST (\Sent \HasNoChildren) "/" "Sent Items"
* LIST (\Junk \HasNoChildren) "/" Spam
* LIST (\HasNoChildren) "/" Temp
* LIST (\HasNoChildren) "/" "Temp sent"
* LIST (\Trash \HasNoChildren) "/" Trash
* LIST (\HasNoChildren) "/" Yesss
4 OK LIST completed


----------SMTP----------
220 kundenserver.de (mreue108) Nemesis ESMTP Service ready
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
init
EHLO xxxxxxxxx-ThinkPad-X1-Carbon-5th
250-kundenserver.de Hello xxxxxx-ThinkPad-X1-Carbon-5th [xx.xx.xx.xx.xx]
250-8BITMIME
250-AUTH LOGIN PLAIN
250 SIZE 140000000
AUTH PLAIN ZGFsZWdyYXR0b25AZ3JhdHRyb25peC5jby51awBkYWxlZ3JhdHRvbkBncmF0dHJvbml4LmNvLnVrAEBHZW9yZ2UyMTEw
235 Authentication succeeded
MAIL FROM:<xxxxxxxxx@xxxxxxxxxx.co.uk>
250 Requested mail action okay, completed
RCPT TO:<email@invalid.com>
451 Requested action aborted: local error in processing


SASL_PATH: /usr/share/mailspring/resources/app.asar.unpacked

SMTP Last Response Code: 451
SMTP Last Response: Requested action aborted: local error in processing

**Comment by llogojo** [comment]
Same error, I'm getting really frustrated here. Does anyone even monitor these posts? Has the project been abandoned? Is the error due to updates? I know I was using Mailspring successfully a few months back, but I had to reload my Linux OS. Newest version of Mailspring resulting in smtp authentication error. Help!!!

**Comment by guategeek** [comment]
Yah I was just trying to set up email on my new computer and getting the same exact problem, its trying to test the SMTP by sending to a fake address and that is failing leaving me unable to add the account. In my case the provider is mailbox.org

**Comment by glenn2223** [comment]
Issues have migrated to the mailspring discourse, there is a discussion over there at:

https://community.getmailspring.com/t/account-set-up-fails-with-smtp-error/1625

---

There is a PR in place that just needs to be approved and implemented. Hopefully, a fix should be up very soon

https://github.com/Foundry376/Mailspring-Sync/pull/6

**Comment by llogojo** [comment]
Thanks so much for the update Glenn, I appreciate it!

**Comment by mndscp** [comment]
I installed the new version `1.10.7-1` yesterday. Quick note: It did not fix any sync issues with my existing setup. I had to delete the config directory and set up my account from scratch, then it worked. Thanks for the update :)

**Comment by Phylu** [comment]
@mndscp Thanks for testing this and the confirmation that it worked after setting up the the account anew.
