### ISSUE TITLE
Empty Spam to Trash

### ISSUE THREAD

**Issue by mischkl** [Foundry376/Mailspring#2441]
Most e-mail clients move Spam to trash when it is deleted. To conform to what users are accustomed to and avoid accidental permanent deletion, it would be helpful if Spam could be moved to the Trash when the folder is emptied, instead of being permanently deleted. For reference, I myself have lost a few important messages permanently because I clicked on "Empty Spam" without thinking twice.

**Comment by federicorosso1993** [comment]
Talking about trash, the fact that you can only empty the trash but not delete single email is a strange limitation.

**Comment by mischkl** [comment]
Closed the issue since apparently all bug reports go through Discourse (now).
