### ISSUE TITLE
New internal 'welcome to mailspring' script prevents email provider login

### ISSUE THREAD

**Issue by Skukkuk** [Foundry376/Mailspring#2446]
With the newly added mailspring feature to send an internal 'welcome to mailspring' email with the actual account setup, my email provider refuses to accept login. 

The mail.ru provider does not allow to send scripts with the login, so the service refuses to accept the login. 
Having confirmed several times, that login data including passwort is correct with other email clients. 
The mailspring error log also confirms that with the login data there was the greeting message from mailspring added, what caused the issue. 

## Objective
There has to be an option to cut the 'welcome to mailspring' message from the login procedure. 

## Testing Notes
Email provider mail.ru refuses to accept scripts to be added to the login data.

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
