### ISSUE TITLE
libsecret not found in debian distro

### ISSUE THREAD

**Issue by holms** [Foundry376/Mailspring#2450]
![screen](https://user-images.githubusercontent.com/280958/216215155-e22a38ec-8bfa-4bea-89ba-e25d8ab06616.png)

Got this error screen in here. `libsecret` is installed, but you probably seeking the wrong one.  That's the only one which is available on Debian Bullseye (11.6):

```
holms@holms:~/Downloads$ whereis libsecret-1
libsecret-1: /usr/lib/x86_64-linux-gnu/libsecret-1.so /usr/lib/x86_64-linux-gnu/libsecret-1.a /usr/include/libsecret-1

holms@holms:~/Downloads$ sudo apt search libsecret
Sorting... Done
Full Text Search... Done
gir1.2-secret-1/stable,now 0.20.4-2 amd64 [installed,automatic]
  Secret store (GObject-Introspection)

libsecret-1-0/stable,now 0.20.4-2 amd64 [installed]
  Secret store

libsecret-1-dev/stable,now 0.20.4-2 amd64 [installed]
  Secret store (development files)

libsecret-common/stable,now 0.20.4-2 all [installed,automatic]
  Secret store (common files)

libsecret-tools/stable,now 0.20.4-2 amd64 [installed]
  tool for storing and retrieving GObject passwords
```

**Comment by swituo** [comment]
the same problem

try install `gnome-keyring` solves the problem

#681

**Comment by hww** [comment]
On the manjaron 

> Linux mjr 6.1.31-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023 x86_64 GNU/Linux

Version form the github displays the error

Make sure you have `libsecret` installed and keyring is present. For more information visit https://www.getmailspring.com/hc/en-us/articles/115001875571

**Comment by a2nt** [comment]
don't have this message, but that's weird to require -dev dependencies for binary
I think libsecret-1-dev shouldn't be required

**Comment by Phylu** [comment]
The latest version 1.12 has a reworked credential storage. If you had any issues before, please follow the steps outlined here: https://community.getmailspring.com/t/password-management-error/199/2

If you still have any issues, please report them over there.
