### ISSUE TITLE
This site has been reported as unsafe

### ISSUE THREAD

**Issue by alex8654** [Foundry376/Mailspring#2451]
It seems your downloads have been reported as phishing

![image](https://user-images.githubusercontent.com/47474085/217023622-25410173-c6c2-4612-8d1f-f04f068ec746.png)

**Comment by agencytrailblazer** [comment]
Saw this too and stopped me from downloading :(

**Comment by ashergz** [comment]
Same. Came here to find out what the deal was. The fact that no dev has bothered to respond makes me even more suspicious.

**Comment by alex8654** [comment]
from the discussions on their forum, it is a lost cause, just stick to thunderbird, this seems to be abandonware, there is a reason for the warning

**Comment by Phylu** [comment]
I will let @bengotow who owns the webserver know directly. Thanks!

**Comment by Phylu** [comment]
The website has been reported to Microsoft as a false positive. They will hopefully reevaluate and remove the warning.

Thanks for reporting!

**Comment by code2be** [comment]
I can confirm that it's working without any alerts on Microsoft Edge, while searched for "Mailspring" and clicking the link appeared in the "Bing" results.
So, I think this is resolved.

**Comment by thevaidik** [comment]
> The website has been reported to Microsoft as a false positive. They will hopefully reevaluate and remove the warning.
> 
> Thanks for reporting!

Hopefully it solves it
