### ISSUE TITLE
Option to use alternative server url

### ISSUE THREAD

**Issue by 1RandomDev** [Foundry376/Mailspring#2453]
Hey guys,
I'm currently working on an alternative implementation of the Mailspring (and Mailsync) backend API. In order to make Mailspring use the new server it obviously would be necessary to change all server urls in the app. It seems that there already are three predefined urls that can be switched using the `env` config entry, but there's no way of adding a custom server and some plugins also have their own list of urls. It would be really nice if there would be an official setting or environment variable to choose a custom api url.

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
