### ISSUE TITLE
reply email error

### ISSUE THREAD

**Issue by xiangjianhe-github** [Foundry376/Mailspring#2455]
## Objective

You need to reply to the email and use Simplified Chinese to reply. The input method should be Simplified Chinese input.

## Tips

I look forward to fixing this issue, so that there are no errors in Chinese input and the page does not crash.

## References

The Chinese input method crashes or malfunctions when replying to emails.

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
