### ISSUE TITLE
Some deleted emails remain in the Inbox without a body

### ISSUE THREAD

**Issue by rafrsr** [Foundry376/Mailspring#246]
##### Are there any related issues?
no

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.06

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no
##### Is the issue reproducible with a particular attachment, message, signature, etc?
Can`t find the way to reproduce this bug, but i have multiple already removed emails in the Inbox but without a body. 

Some mails when remove it the message appear in the trash and in the inbox, but the message inside inbox does not have a body, only the subject. 

This error does not happen always, only some emails has this problem, maybe can be a connection lost during the delete process ...

**Comment by bengotow** [comment]
Hey! We haven't seen any reports of this in several months so I'm gonna go ahead and close this. It was likely fixed by another patch and we just didn't tie it back to this. Thanks!
