### ISSUE TITLE
Intuitive Time Parsing for Email Scheduling

### ISSUE THREAD

**Issue by ChocoTonic** [Foundry376/Mailspring#2462]
## Objective

The objective of this task is to update the date parsing logic to handle both 3 and 4 digit time input strings for scheduling emails.
This will help interpret strings like "123" as "1:23" and "1234" as "12:34" as valid times.

## References

Feature Proposal: [Intuitive Time Parsing for Email Scheduling - Mailspring Community](https://community.getmailspring.com/t/intuitive-time-parsing-for-email-scheduling/6991)

**Comment by chriskesl** [comment]
>

**Comment by ChocoTonic** [comment]
hi @chriskesl was there a comment that you meant to leave there?
