### ISSUE TITLE
The system tray icon has disappeared

### ISSUE THREAD

**Issue by chuhha** [Foundry376/Mailspring#2479]
In version 1.13.1-59cb1b1d the system tray icon disappeared in Fedora 38 (GNOME)
Gnome 44
Uses the AppIndicator and KStatusNotifierItem Support extension
In version 1.12* the icon was

![Снимок экрана от 2023-11-24 00-24-44](https://github.com/Foundry376/Mailspring/assets/57899753/cdee6edb-7137-4b3a-b6a4-873e6e8ce075)

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.

This has already been reported there: https://community.getmailspring.com/t/the-icon-in-the-system-tray-has-disappeared/7442
