### ISSUE TITLE
Mailspring for Fedora, converting from Mac Mail on Mac OSX 10.14.6

### ISSUE THREAD

**Issue by johnstonesnow** [Foundry376/Mailspring#2483]
Hi, not a github regular, barely understand how to use it sorry. A few questions if I may:

1. Does the fact I can only find a github page for Mailspring (rather than a website with a dummy-friendly Download button :D) mean that this is only for dev types? Is CLI stuff needed to install/use Mailspring?

2. I am leaving Apple (hw and sw). I am looking for a powerful mail client to replace Mac Mail. I have 20 yrs of email sorted into many local folders, which I need to retain on my new client. Can Mailspring do what I need?

3. If yes to 2, could anyone advise the process to convert/move mail from Mac Mail over to Mailspring on Fedora?

thanks and sorry if I have asked this in the wrong place, I can't see anywhere else to post it.

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.

However, here is a quick answer for your questions:
1. Download Page: https://www.getmailspring.com/download
2. If you use the IMAP protocol (standard for modern mail clients), yes
3. Just log in to your mail accounts with Mailspring and your mails should appear again with their sorting.

**Comment by johnstonesnow** [comment]
Thanks. No idea what an 'issue template' is but thanks for link to community. 

PS You may have missed the word "local" in my post. I have lots of folders "on my mac", i.e. local folders, not on the imap/mail server. So yes I am using imap with my mail accounts, and I know those folders will be imported, but i dont use imap folders to organise mail, i use local folders. Can Mailspring handle this and allow local folders? if so, is there a way to convert my Mac Mail folders to MailSpring ?

thanks

**Comment by Phylu** [comment]
Sorry, local folders cannot be transferred easily from any other mail program to mailspring.
