### ISSUE TITLE
Fastmail sync encounters errors

### ISSUE THREAD

**Issue by taohansen** [Foundry376/Mailspring#254]
Windows 10, latest Mailspring. when i click the error message, it notifies me that its dispatched an error report to your team.

result: Fastmail account does not sync.

**Comment by TheNuclearCat** [comment]
got same problem on my imap account (self hosted).

**Comment by bengotow** [comment]
Hey folks! We've fixed so many sync bugs since Oct it's hard to say whether this is still an issue or not. Gonna close and we can re-open if the problem still occurs.

**Comment by taohansen** [comment]
still running into issues with Fastmail sync
