### ISSUE TITLE
The window title should display the title of the currently selected email

### ISSUE THREAD

**Issue by andreyuv** [Foundry376/Mailspring#256]
##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?
1.0.6.

**Feature Request**

##### Description
There are a number of automatic time tracking utilities which rely on reading window titles for task categorization.

Currently Mailspring just displays "Mailspring" in the title at all times. The window title should change to display the title of the currently selected thead (when in the main thread listing) or the currently open email/draft (when the email is open in a separate window).

##### Does this feature exist in another mail client or tool you use?
Yes, it exists in Microsoft Outlook (in all email windows, including the email list). There's also partial support in Mailbird and eM Client (these  only change the title when opening a single email in a new window).

**Comment by bengotow** [comment]
Hey! This is a great suggestion—thanks for filing this. I can definitely see how it'd be handy (I used RescueTime for a while and it recorded window titles as well.) I'll see if we can get this into an upcoming release.

**Comment by bengotow** [comment]
If anyone is interested in tackling this, I think this might be as simple as updating `window.title` to match the currently selected thread.  The code should probably go in `MessageStore`, which is responsible for the data in the messages column of the UI. It has a function called `_onApplyFocusChange` that is called whenever the focused thread changes, and we could probably put this in there.

(The `MessageStore` is one of the older parts of the app and it's unfortunately written in CoffeeScript still... hopefully sometime soon we'll get this modernized a bit.)
