### ISSUE TITLE
Sync Error: Too Many SQL variables

### ISSUE THREAD

**Issue by lukeco11** [Foundry376/Mailspring#257]
##### Are there any related issues?

Not that I can find, perhaps #120 

##### What operating system are you using?

Mac OS HIgh Sierra 

##### What version of Mailspring are you using?

1.0.6 (but issue has persisted since the first release)

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Potentially, this account is a Google Apps account for work with custom domain. However, Mailspring has no issue with another account with this same setup. 

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Every time I sync this account (across computers or clean installs), Mailspring says, "Encountered an error while syncing..." Trying again just encounters the error again. It seems to get stopped at the same percentage each time (6%). The log looks like below. The common errors message is, "A C++ exception occurred during program execution: Too many SQL variables."

11027 [2017-10-26 16:03:49.856] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** too many SQL variables
 ***

11027 [2017-10-26 16:03:49.876] [metadataExpiration] [info] Scanning for expired metadata
11027 [2017-10-26 16:03:49.876] [metadataExpiration] [info] -- Will wake for next expiration in 7201sec
11027 [2017-10-26 16:03:49.888] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** in mailsync     MailProcessor::insertFallbackToUpdateMessage(mailcore::IMAPMessage*, Folder&, long)
 *** in mailsync     SyncWorker::syncFolderUIDRange(Folder&, mailcore::Range, bool, __1::vector*)
 *** in mailsync     SyncWorker::syncNow()
 *** in mailsync     runBackgroundSyncWorker()
 *** in mailsync     void* __1::__thread_proxy(void*)
 *** 0x7fff6bf206c1  _pthread_body
 *** 0x7fff6bf2056d  _pthread_body
 *** 0x7fff6bf1fc5d  thread_start
 ***

--

**Comment by lukeco11** [comment]
Also worth noting - Nylas does not have this error on this account. @bengotow Thanks for your great work on Mailspring!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—I think I've finally figured out what's going on here. It looks like this could happen if a message contains a header field referencing more than ~100 other messages. Normally when clients send replies to a thread they only reference a handful of messages, but maybe there's a rouge client out there just making the "in reply to" list bigger and bigger forever. 

Will address this and we can see if it's fixed for you in the next release!
