### ISSUE TITLE
Sync error: Mailspring GenericException occurred during program execution

### ISSUE THREAD

**Issue by agurz** [Foundry376/Mailspring#26]
Getting errors while syncing IMAP account:

<img width="1294" alt="screen shot 2017-10-04 at 5 45 04 pm" src="https://user-images.githubusercontent.com/13837769/31198806-e927167a-a92b-11e7-849d-738117ea669f.png">
 
Here is the console output:

[1507149913641.log](https://github.com/Foundry376/Mailspring/files/1357301/1507149913641.log)

---

##### Are there any related issues?

#8, maybe?

##### What operating system are you using?
macOS Sierra 10.12.6

##### What version of Mailspring are you using?
1.0.1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP

**Comment by bengotow** [comment]
Hi @agurz thanks for reporting this. It looks like the logs don't include the specific folder it's trying to sync when that exception occurs, so I'm going to make a few changes to the sync process so we can debug this better in the next release. Stay tuned!

**Comment by agurz** [comment]
I have just updated the app and it seems to sync well now. 

I'm receiving this error on the console (It doesn't affect the sync of my emails AFAIK):

<img width="1320" alt="screen shot 2017-10-06 at 7 04 18 pm" src="https://user-images.githubusercontent.com/13837769/31300328-82b95b60-aac9-11e7-8852-1a4cfc84b1cb.png">

But it's already reported on #56. 

I believe you can close this issue now.

**Comment by bengotow** [comment]
Thanks - glad it's working properly now! That other error is odd, but definitely a different issue. Will track that down separately.
