### ISSUE TITLE
Blank Youtube Reply Emails

### ISSUE THREAD

**Issue by applesea2** [Foundry376/Mailspring#260]
##### Are there any related issues?

...
No
##### What operating system are you using?
...
Windows 10
##### What version of Mailspring are you using?
...
Dev build (1.06). Issue persistent in Stable builds as well.
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
With no plugins installed, picture of Youtube video in the email is completely blank. It will open, though
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
No
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
Yes
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...
Web Gmail
![screenshot 5](https://user-images.githubusercontent.com/20137421/32089713-96ae2560-bab9-11e7-8c24-1471361dde9f.png)

**Comment by bengotow** [comment]
Hey! I think this is probably the same issue as #262. Gotta go comment on one of my youtube videos and see if I can reproduce this...

**Comment by bengotow** [comment]
It looks like YouTube is sending emails with very strange HTML markup that includes spaces inside image `src` attributes and Mailspring is adding actual spaces to the URLs:

```
<img width=3D"46" height=3D"46" style=3D"display:block; border-radius: 50%;=
" border=3D"0"
            src=3D"
 =20
    https://lh6.googleusercontent.com/-9Z3oL97BzBQ/AAAAAAAAAAI/AAAAAAAAAAA/=
pNNLh2flMTg/s50-mo/photo.jpg
 =20
">
```

Will see if we can fix this.

**Comment by applesea2** [comment]
Same issue occurs several versions later. See if it can be rechecked.

**Comment by bengotow** [comment]
Yeah - looks like youtube subscriber emails are still coming in without images:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/1037212/34219550-c4edf902-e56e-11e7-9b99-77e4477fe9a7.png">

It looks like they're using the old `background ` HTML attribute (rather than background CSS style) and it was being stripped by the sanitizer. Will be fixed in the next release.
