### ISSUE TITLE
Some inline images is not displayed in mails

### ISSUE THREAD

**Issue by IevgenSobko** [Foundry376/Mailspring#262]
##### What operating system are you using?
Kernel: 4.9.56-1-lts x86_64 bits: 64 
Desktop: KDE Plasma 5.11.1 
Distro: Antergos Linux

##### What version of Mailspring are you using?
1.0.6-9448c884

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No third-party plugins

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I have only one Gmail provider configured

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![screenshot_20171027_091630](https://user-images.githubusercontent.com/14232100/32090621-099b2c5a-baf9-11e7-875d-e5e9e0aed41b.png)

--

**Comment by Bouska** [comment]
Could you give us the URL of the inlined image so we can investigate?

**Comment by IevgenSobko** [comment]
Here is part of html code that responsible for this image

<td width="600" class="m_571126308962239829bg" valign="top" height="600" align="center" background="https://ci4.googleusercontent.com/proxy/rIqQNOK9vjAJ5BZGGHi4ZoYpTEtgsEtyLkOa3AAAQgGJOC_xnhKGlB-TASiTY6F2UzxTuPSzOSS3fqVBlHorzTQD311eKEAoSn8sXMhX6xiFLh96g0DeGp5vF3nUSDsGNa6AykXWL8w6gtFfxggb8cn8U-GGkMw1DToYCu2mW8nYEWvAowbnK4_hsFTB=s0-d-e1-ft#https://appboy-images.com/appboy/communication/assets/image_assets/images/59f313065c5a6824b4c7389e/original.?1509102342" style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#000000;background-repeat:no-repeat">

<table align="center" border="0" cellpadding="0" cellspacing="0" class="m_571126308962239829fluid_width" width="600">

<tbody>

<tr>

<td align="left" style="padding:20px 0 0 20px;border:none" valign="top" width="100%"><a href="http://link.announce.busuu.com/wf/click?upn=Pw3CCRub0d0VBcMfFtEzF18TFJ2e2td4ySadeY8vCuI-3D_D2j-2F2sIY-2BrdzpMyCEP8w-2FxFZ7MQkY11Wc-2F0CLRGSyKj675VQCj0R8kAWdRUNCAJSPW7DCYVXorCZbZ4PqyPDil9ioM7X-2Bhvyb1sRKieqB-2BtTWd7Wy-2Fg62Zy84h5GWnMLViHyTJ8H7gye-2B5qnIX15ENHn5U4SQ2kbZtOuwvpNekqvayF2EZ0qzN3Bnq2sO9-2BUTN89iJgEWIBkCX-2Bjtt9mJRSj6QhgWCTuYS3FZ9ngjM5d5vFTZQs9OLROecZ3c5eCnpxcuhyhkOzSsoxTb3MD77et8YS7RtimfoF05RJd5dOKQ2jqP5B1-2FifRjl-2FKiqIsDV5jRcZMbta-2B5iUPcHtcYxhu85UOZ6S-2B8YJjopoy6sAZ9wnRp9L6SvtgIk4UyHZ6xa-2FpcgRpIZ5mIT92h7SWGQNj1HP8xQle-2F0lfOoDYrFARsIFJE-2FCV46PmJiJvVsyWBLb5W1vx1EXbU7SXlp8RYw-3D-3D" style="display:block;width:110px" title="Busuu" target="_blank" data-saferedirecturl="https://www.google.com/url?hl=uk&amp;q=http://link.announce.busuu.com/wf/click?upn%3DPw3CCRub0d0VBcMfFtEzF18TFJ2e2td4ySadeY8vCuI-3D_D2j-2F2sIY-2BrdzpMyCEP8w-2FxFZ7MQkY11Wc-2F0CLRGSyKj675VQCj0R8kAWdRUNCAJSPW7DCYVXorCZbZ4PqyPDil9ioM7X-2Bhvyb1sRKieqB-2BtTWd7Wy-2Fg62Zy84h5GWnMLViHyTJ8H7gye-2B5qnIX15ENHn5U4SQ2kbZtOuwvpNekqvayF2EZ0qzN3Bnq2sO9-2BUTN89iJgEWIBkCX-2Bjtt9mJRSj6QhgWCTuYS3FZ9ngjM5d5vFTZQs9OLROecZ3c5eCnpxcuhyhkOzSsoxTb3MD77et8YS7RtimfoF05RJd5dOKQ2jqP5B1-2FifRjl-2FKiqIsDV5jRcZMbta-2B5iUPcHtcYxhu85UOZ6S-2B8YJjopoy6sAZ9wnRp9L6SvtgIk4UyHZ6xa-2FpcgRpIZ5mIT92h7SWGQNj1HP8xQle-2F0lfOoDYrFARsIFJE-2FCV46PmJiJvVsyWBLb5W1vx1EXbU7SXlp8RYw-3D-3D&amp;source=gmail&amp;ust=1509322550325000&amp;usg=AFQjCNGHZk4Pdz-PxxzorgpMolybebnoHQ"><img alt="Busuu" src="https://ci3.googleusercontent.com/proxy/KlM6EEj68Fq06PCn3c1QfELGfeufaEQRN6qHv0gwku0PXtSmB03nN-7G5YCLMnF1C_JFyNig0CNz4DRXvmdHKMJLFR7LqbLF8tey2rVDRRLc41nlr4c5ZDVe8wclvQmFx5c21p4M-FXd5k3Z9aoVGLOTLGyg9idqnUhIavengufP4Ghk5AmT8vqEC-DE=s0-d-e1-ft#https://appboy-images.com/appboy/communication/assets/image_assets/images/598351ff56ec3170feddbc0e/original.?1501778431" style="display:block;width:100%;border:0" class="CToWUd"> </a></td>

</tr>

</tbody>

</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" class="m_571126308962239829fluid_width" width="600">

<tbody>

<tr>

<td align="left" style="padding:0;border:none" valign="top" width="100%"><a href="http://link.announce.busuu.com/wf/click?upn=Pw3CCRub0d0VBcMfFtEzF9RyJ1ix32z6E91S1CK9s9bWMTlsM0lh8w-2FpKvOreTQlEUmNqgsYHa0AGNRriS7ZsqGk-2B9lAppg93pn0acMGwQuXUlXXhYNXYT7gc3zZ8ERerViEjiCdMBMS5w4jMeN42ncZquKbqa2nGabtPiqqsLU-3D_D2j-2F2sIY-2BrdzpMyCEP8w-2FxFZ7MQkY11Wc-2F0CLRGSyKj675VQCj0R8kAWdRUNCAJShHKdhloMlTs5z-2BkBdfwZouIfSTJgBgJ8TgmWHecvxRK-2F0Cl5Amu-2FLbDB-2FkYlk6ViuzbtfjV39cxze-2BHImFaBGIY39ZUZfmWPVagAmMC-2FJfDq3EVx0AK-2BvuHffvvc0E-2BspN6N-2FzYCLNCj6C-2BX35UNyetKklV2yU9t27KBJnXqgfdIvt59xC7B0XWiO0L6QJe3C9972vR8ECMnK9qqjDKK3Ghuv-2BahgeMZdkQhFpdJ5YoN76tt8lO36S-2FGs2P7yTasOi6Vdl9pGHzlE-2FUi6Pztp44axXsgOVtPOTszeLgKyGgo84BnUfXupx37dWCV-2F-2FRS-2BTD-2BuGz1UTf0IRcRUneCCEhll3glIbo6D-2FVXvNrYm4nZT6WJZEeBuiy5LGCpzx8k9sXcBD9urSJ8lFK6-2BaAchQ-3D-3D" style="display:block;width:100%;height:545px" target="_blank" data-saferedirecturl="https://www.google.com/url?hl=uk&amp;q=http://link.announce.busuu.com/wf/click?upn%3DPw3CCRub0d0VBcMfFtEzF9RyJ1ix32z6E91S1CK9s9bWMTlsM0lh8w-2FpKvOreTQlEUmNqgsYHa0AGNRriS7ZsqGk-2B9lAppg93pn0acMGwQuXUlXXhYNXYT7gc3zZ8ERerViEjiCdMBMS5w4jMeN42ncZquKbqa2nGabtPiqqsLU-3D_D2j-2F2sIY-2BrdzpMyCEP8w-2FxFZ7MQkY11Wc-2F0CLRGSyKj675VQCj0R8kAWdRUNCAJShHKdhloMlTs5z-2BkBdfwZouIfSTJgBgJ8TgmWHecvxRK-2F0Cl5Amu-2FLbDB-2FkYlk6ViuzbtfjV39cxze-2BHImFaBGIY39ZUZfmWPVagAmMC-2FJfDq3EVx0AK-2BvuHffvvc0E-2BspN6N-2FzYCLNCj6C-2BX35UNyetKklV2yU9t27KBJnXqgfdIvt59xC7B0XWiO0L6QJe3C9972vR8ECMnK9qqjDKK3Ghuv-2BahgeMZdkQhFpdJ5YoN76tt8lO36S-2FGs2P7yTasOi6Vdl9pGHzlE-2FUi6Pztp44axXsgOVtPOTszeLgKyGgo84BnUfXupx37dWCV-2F-2FRS-2BTD-2BuGz1UTf0IRcRUneCCEhll3glIbo6D-2FVXvNrYm4nZT6WJZEeBuiy5LGCpzx8k9sXcBD9urSJ8lFK6-2BaAchQ-3D-3D&amp;source=gmail&amp;ust=1509322550325000&amp;usg=AFQjCNGwP_hsrCNwwfZK92IWx4nqpcWqSA"></a></td>

</tr>

</tbody>

</table>

</td>

**Comment by bengotow** [comment]
Hmm - it doesn't look like that HTML block contains the image shown at the top of the email. Could you try going to Gmail and saying forward and sending it to me at ben@foundry376.com or pasting the raw message source here?

**Comment by IevgenSobko** [comment]
Hi there,
See full attached email source
[original_msg (1).txt](https://github.com/Foundry376/Mailspring/files/1433841/original_msg.1.txt)

**Comment by IevgenSobko** [comment]
Hi,
Any updates on this?
I see u have closed #260, but I still have bunch of emails with missing images in version 1.0.9
![mailspring_screenshot](https://user-images.githubusercontent.com/14232100/33551374-e215699c-d8f9-11e7-960a-9690d735576d.png)

**Comment by bengotow** [comment]
Hey folks! This should be fixed by #260 in some scenarios (which was closed a bit early but should now be fixed) and 5cbf7e31e544f69ed03646da0820190db9955199 which ensures Mailspring displays inline attachments without titles correctly. Should be fully fixed in v1.1 when it ships this week.

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and a lot of other small improvements. You can grab the latest version from https://getmailspring.com/download.
