### ISSUE TITLE
Automatic search suggestions broken with single quote character

### ISSUE THREAD

**Issue by Bouska** [Foundry376/Mailspring#263]
I'm using Mailspring 1.0.6 on Fedora 26. When the search bar suggest me threads, I have no problem selecting one of them and getting the result but if the subject of the mail contain at least one single quote then the search loops indefinitely (you can't see the throttling bar on the screenshot but it's there). If I remove the leading and trailing double quote and relaunch the search, then it works.
![mailspring_search_bug_1](https://user-images.githubusercontent.com/1036656/32107980-830fc2a8-bb30-11e7-9d47-187c724ce09f.png)
![mailspring_search_bug_2](https://user-images.githubusercontent.com/1036656/32107983-851c1eac-bb30-11e7-951d-97e427f70e47.png)
I initially thought it was a problem with French characters, but not at all.

**Comment by bengotow** [comment]
Hey! This should be fixed now—turns out when the search parser was improved to handle things like "bengotow is:unread", the escaping was disabled. Will be fixed in the next release!

**Comment by palefire19** [comment]
Ben, is there any documentation on what types of queries the search can handle (e.g. 'is:unread') or is there a planned update that would expose those parameters in the search bar more clearly (for example an implementation similar to https://sparkmailapp.com/search).

**Comment by bengotow** [comment]
Hey! Ooh I like those pages they've got, that's a really nice way of showing it off.

You can find the Mailspring docs on search here: https://foundry376.zendesk.com/hc/en-us/articles/115002212931-Using-Advanced-Search-Features. Definitely need to make some prettier feature pages...
