### ISSUE TITLE
On Outlook, there are 3 breaklines for one on MailSpring

### ISSUE THREAD

**Issue by maximlefebvre** [Foundry376/Mailspring#265]
##### What operating system are you using?
macOS Sierra, Version 10.12.6 

##### What version of Mailspring are you using?
Version 1.0.6

--

**Bug?**
##### Is the issue reproducible with a particular attachment, message, signature, etc?
Today, on a WebEx, I saw an e-mail on Outlook that I send earlier this week with MailSpring, and my e-mail was displayed with a lot of breakline. There was 3 breakline in Outlook for one in MailSpring.

I checked on Gmail and on Apple Mail to see how this mail was displayed, and it was OK.

In looking in the Raw data of this e-mail, I saw that MailSpring add some div in the content, that Outlook replace by a br. So a `<div><br></div>` in MailSpring become a `<br><br><br>` in Outlook.

Gmail doesn't do that, there is no div in the content, only around the content.

Here an example from MailSpring : 

```
Hello from MailSpring,
<div>
	<div><br></div>
	<div>Here a mail example.</div>
	<div><br></div>
	<div>List :</div>
	<div>
		<ul>
			<li>1</li>
			<li>2</li>
			<li>3</li>
			<li>4</li>
		</ul>
		<div>End of the list</div>
	</div>
</div>
<br>
```

The same content from Gmail : 

```
<div dir=3D"ltr">Hello from Gmail,<br>
	<br>
	Here a mail example.<br>
	<br>
	List :<br>
	<ul>
		<li>1<br></li>
		<li>2<br></li>
		<li>3<br></li>
		<li>4</li>
	</ul>
	End of the list<br>
<br clear=3D"all">
</div>
```

Thank you in advance for your help. For the work, it's very problematic, for my prospects and customers, I look like idiot :(

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and a lot of other small improvements. You can grab the latest version from https://getmailspring.com/download.
