### ISSUE TITLE
Archiving a message to to a different account folder

### ISSUE THREAD

**Issue by trustin** [Foundry376/Mailspring#266]
I wish I can archive a message in one account to the folder of another account. Mailspring currently only allows me to choose the folder of the same account. This feature is particularly useful to the users with limited quota.

##### What operating system are you using?
Arch Linux

##### What version of Mailspring are you using?
1.0.6

##### Does this feature exist in another mail client or tool you use?
Thunderbird and Claws Mail IIRC.

**Comment by bengotow** [comment]
Hey! Thanks for filing this - this is technically doable but I think we'd need to implement it very carefully from a usability standpoint. I imagine the likelihood of people accidentally moving messages out of an account is higher than the likelihood of them doing it intentionally. 

Gonna flag this as a wontfix for now, but leave this open and see if we can collect some 👍 votes.

**Comment by trustin** [comment]
This feature will involve a conscious configuration change, so I think it's hard to make that happen by mistake. If we're in doubt, we could add some extra confirmation steps or something simlar in the preferences UI, e.g:

- Only show the folders of the current account and let a user tick the check box 'show the folders from other accounts'.
- When a chooses a folder from other account, show a confirmation dialog which states potential risk.
- When a folder from other account is chosen, show some extra text or warning sign.
