### ISSUE TITLE
Bind Cmd-Shift-V to paste without formatting

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#268]
##### Are there any related issues?

...

##### What operating system are you using?
MacOS 10.12.6

##### What version of Mailspring are you using?
1.0.6

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Gmail does this and I think it is becoming standard in a large variety of applications. I do a lot of pasting from other sources into Mailspring and appreciate the "Paste and Match Style" option in the context menu, just think that Cmd-Shift-V should do the same thing.

**Comment by bengotow** [comment]
Hey thanks for reporting this... let me see if we have control over this. The Mac OS X standard is Cmd-Shift-Option-V (Messages, Notes.app, etc.) but I also get it wrong all the time and I don't think Cmd-Shift-V is tied to anything. It looks like Chrome actually accepts both too.

**Comment by bengotow** [comment]
Hey! This has shipped in `1.0.10`. Thanks for the suggestion!
