### ISSUE TITLE
Long, complex URL is not correctly linked in message view

### ISSUE THREAD

**Issue by kometchtech** [Foundry376/Mailspring#269]
##### Are there any related issues?

...None
##### What operating system are you using?
...Windows 10 Pro 1709 

##### What version of Mailspring are you using?
...1.0.6

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...As shown in the image, it seems that "?" Is not correctly encoded, or it is a URL, but the subsequent character string is not correctly recognized as a URL.

I will paste the email of Amazon.co.jp for reference.
![shipment](https://user-images.githubusercontent.com/5137077/32135413-effd2518-bc39-11e7-968a-244563c8ec8d.JPG)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by Bouska** [comment]
Seems the blame has to be put on a non perfect regex for URLs : https://github.com/Foundry376/Mailspring/blame/master/app/src/regexp-utils.coffee#L42

**Comment by bengotow** [comment]
Hey! Thanks for filing this—it definitely looks like a regexp issue.... is there any chance that the blurred-out part of your screenshot contains non-latin characters? (Maybe a product name containing Japanese characters?) I think this might be somewhat similar to the unicode issue fixed in #273.

**Comment by kometchtech** [comment]
@bengotow 
Japanese does not seem to be included in the URL in the browser etc.
(As you say, the subject, body, product name is Japanese)

**Comment by bengotow** [comment]
Now that I'm looking at this URL more closely, I think the regex is getting tripped up by the fact that it's `index.html/ref=bla?` and not `index.html?ref=bla&`... I think the equals sign must be followed by a ? in our current regex? If anyone wants to dig in it'd be super helpful, but unfortunately the URL regex is crazy complicated...
