### ISSUE TITLE
Does not sync mails on Windows 10

### ISSUE THREAD

**Issue by DanyGee** [Foundry376/Mailspring#27]
##### What operating system are you using?
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.15063 N/A Build 15063
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. 1902, 27.06.2016

##### What version of Mailspring are you using?
1.0.1-ba1d6734

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Yes, Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Simply configured my account.
Tried 2 ways:
1. Choosing "Gmail" option - followed the rest of the config in browser etc. - error syncing (but it synced some spam - see screenshot)
2. Choosing "IMAP" option - tried both passwords (normal and for apps) - error syncing (but it synced some spam - see screenshot)
![2017-10-04_22-46-39](https://user-images.githubusercontent.com/26818551/31199295-3a916666-a957-11e7-9a06-e87491ba5c65.jpg)

--

**Comment by bengotow** [comment]
Hi @DanyGee thanks for reporting this! It looks like Mailspring hasn't correctly identified the "All Mail" folder in your Gmail account. The sidebar should look like this (notice All Mail is beneath Sent Messages):

![image](https://user-images.githubusercontent.com/1037212/31199901-bb958dae-a90d-11e7-8a02-4a758e925a1c.png)

Is one of those items `Wyslane`, `Kosz`, etc. your all mail folder? I'm afraid I can't read the language they're localized into, and I think Mailspring may be getting confused by that as well.

**Comment by DanyGee** [comment]
Wysłane = Sent
Kosz = Trash
...so they are not my "all mail" folders.

To be honest I don't see any "all mail" folder on my account.

Here are my folders directly from Gmail:
![2017-10-04_23-20-33](https://user-images.githubusercontent.com/26818551/31200425-39af4a34-a95b-11e7-9381-beb2ba91d31c.jpg)

**Comment by bengotow** [comment]
Hey @DanyGee - thanks for the reply. The All Mail folder is usually hidden, so it's OK that it doesn't appear in Gmail's sidebar.

I think I may need to create a Polish Gmail account to reproduce this issue, but could you try one last thing? In Gmail, open the Settings and check that "All Mail" has "Show in IMAP" checked. Here's a picture of how to do it: https://foundry376.zendesk.com/hc/en-us/articles/115001881912.

Mailspring is supposed to check automatically and ask you to change this setting, but maybe that isn't working.

**Comment by DanyGee** [comment]
> Mailspring is supposed to check automatically and ask you to change this setting, but maybe that isn't working.

Most probably, cause it didn't ask me to ;)

Anyway, checked "Show in IMAP" for All Mail and we got a bit further, but still no messages getting parsed.
Looks like only headers get through...
![2017-10-05_00-39-59](https://user-images.githubusercontent.com/26818551/31203262-933b326a-a966-11e7-8860-37b1ba0bcf69.jpg)
Notice that it still grinds the spam and trash folder...My spam is already empty, but it still shows 45 count in Mailspring.

**Comment by ashleyseric** [comment]
I'm getting that "Encountered an error while syncing" as well with when using IMAP / SMTP (godaddy hosted email address).  I can see emails in my folders but not the inbox. Also can't seem to send emails from that address (no error message when I try, the send button is just unresponsive). Also worth noting, this same email syncs fine with Nylas mail without any errors or issues.

**Comment by kometchtech** [comment]
1.0.3 (windows 10 Pro 1703) But even when I notice it, I can not synchronize.
Even if you clicked "Sync New Mail Now", synchronization did not resume.

**Comment by bengotow** [comment]
Hey folks! We just shipped 1.0.4 which resolves a bunch of issues with custom IMAP/SMTP accounts and allows you to manually choose your Sent folder, Drafts folder, etc. (in Preferences > Folders) in the event that Mailspring can't auto-detect which one it should use. You can get the update from getmailspring.com/download, or from Menu > Check for Updates... if you're on macOS or Windows. Let me know if you still see the issue after updating!

**Comment by DanyGee** [comment]
Exactly the same problems.

**Comment by DanyGee** [comment]
I gave up the app and uninstalled it - way too much problems for an e-mail client.
![2017-10-13_19-53-29](https://user-images.githubusercontent.com/26818551/31582635-6339d5c8-b189-11e7-9087-bfe6053eb2fa.jpg)

**Comment by bengotow** [comment]
No worries—thanks for trying it and reporting bugs! I think there were three separate issues in this ticket we've fixed so far, probably just a couple more to go.

It's actually interesting that it displays the "Program has exited" dialog on Windows. The sync workers are designed to exit in some scenarios (like repeated network failures) and the app restarts them. or reports the problem. On Mac and Linux it's totally silent, but I guess we need to silence those dialogs on Windows.

**Comment by HotToTroc** [comment]
Similar problem to previous reports but in my case no emails are visible and "Syncing your Mailbox" is displaying in the lower left hand corner of my Windows 10 laptop.  Memory being consumed by the process and no progress for hours.
