### ISSUE TITLE
Different alignment in Chrome and Mailspring

### ISSUE THREAD

**Issue by IevgenSobko** [Foundry376/Mailspring#270]
See image below.
In Google Chrome weather forecast image is centered in Mailspring it is aligned to the left

##### What operating system are you using?
Kernel: 4.9.56-1-lts x86_64 bits: 64 
Desktop: KDE Plasma 5.11.1 
Distro: Antergos Linux

##### What version of Mailspring are you using?
1.0.6-9448c884

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No third-party plugins

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I have only one Gmail provider configured

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![screenshot_20171028_114503](https://user-images.githubusercontent.com/14232100/32139695-8e8bef2e-bc59-11e7-87dc-e5a3c51bb533.png)

**Comment by bengotow** [comment]
Huh—that's pretty interesting. if you can post the HTML of the message that'd be helpful. Mailspring applies some styles to messages in an attempt to format them better, but it shouldn't be causing alignment changes.

**Comment by IevgenSobko** [comment]
Hey,
I've attached original message
[original_msg.txt](https://github.com/Foundry376/Mailspring/files/1433752/original_msg.txt)

**Comment by bengotow** [comment]
Hey thanks for the message source! I strangely haven't been able to reproduce this when I put the HTML into Mailspring... I think the sync engine must be mangling the HTML somehow when it fetches the email (breaking it before it reaches the UI, where I'm pasting it in to test). I also see the text this way, which I notice is also broken for you.

Will try injecting this a bit lower down and keep you posted.

<img width="1259" alt="screen shot 2017-11-04 at 9 00 52 pm" src="https://user-images.githubusercontent.com/1037212/32408996-43ad29b0-c1a3-11e7-8820-4c20e7c4943a.png">

**Comment by bengotow** [comment]
I'm almost positive this will be fixed by 4e119e5eaddb2af4f81a784b670c7b6904bdc806—stay tuned!

**Comment by IevgenSobko** [comment]
Hopefully, it'll fix also facebook mail's buttons not clickable, as well as other messages missing images and alignments.
I've seen a lot of such issues last few days, but decided to wait for this fix. Maybe it will fix other issues too.
Thanks.

**Comment by IevgenSobko** [comment]
@bengotow it is still reproducible with 1.0.8 release.
Please reopen this issue.

**Comment by IevgenSobko** [comment]
Thx. Finally in 1.0.9 it is working as expected.
