### ISSUE TITLE
[Feature Request] Provide option to hide menu bar.

### ISSUE THREAD

**Issue by shadowwarrior29** [Foundry376/Mailspring#271]
What operating system are you using?

Linux Mint (Sonya)

What version of Mailspring are you using?

1.0.6

Feature Request?
Could you provide an option or a shortcut key which enables hiding of menubar. The UI of mailspring is beautiful but it would look much better if I could hide the menu bar.
This feature was already available in Nylas mail.

**Comment by rhoconlinux** [comment]
+1
This would be really nice!

Thanks in advance
rho

PS: I think some of this work were already developed in the latest versions of nylas (after the break involving payments and security issues)

**Comment by rafrsr** [comment]
+1 👍

A replacement may be place a main menu button in the toolbar:

![image](https://user-images.githubusercontent.com/7094012/32228429-9ad1bcb0-be24-11e7-9d2e-62bff6b119a9.png)

**Comment by jGleitz** [comment]
I would suggest not to clutter the toolbar with more unrelated icons (cf. #283). Instead, I think it would be logical to add an option to the “View” menu like there already is an option for toggling the reading pane. I feel like that would be more consistent and less intrusive.

Additionally, it would make sense to adopt a pattern that is used by many applications (e.g. Atom, Firefox), and show the Menu when pressing <kbd>Alt</kbd>.

**Comment by rafrsr** [comment]
sounds good, it's a clean solution 👍

**Comment by JimSangwine** [comment]
I would very much like this too. It took me a while to figure out that tapping the alt key in Nylas would show the menu bar, but once I did I loved that it was hidden by default. It really clashes with the beautiful UI now.

**Comment by bengotow** [comment]
Hey folks - in the next release I'm adding a preference for this, as well as a new option to use the "right corner hamburger menu" and completely custom window controls. I think this will improve things a lot, especially on distros like Elementary where the standard window frame is very tall.

New options:
<img width="958" alt="image" src="https://user-images.githubusercontent.com/1037212/34469806-1311b00e-eedb-11e7-9ca7-e922b4725a55.png">

"Right corner hamburger" option - note the system window frame is not used at all, so it'll look like this (or your selected theme) on all Linux distros:
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/1037212/34469818-2f88a3f0-eedb-11e7-999c-40a51a50dece.png">

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and a lot of other small improvements. You can grab the latest version from https://getmailspring.com/download.
