### ISSUE TITLE
[Dev Workflow] A fork will no longer install (Mailsync) after a commit has been made in fork

### ISSUE THREAD

**Issue by mattlyons0** [Foundry376/Mailspring#274]
##### What operating system are you using?
Linux

The method you are using to download a version of Mailsync in scripts/postinstall.js is getting the HEAD SHA1 and take the first 8 chars. This is fine for the official repo but this doesn't work well in forks because once a commit is made there isn't a Mailsync version for that SHA1.

Maybe the solution is to keep trying SHA1's from HEAD down to the last commit that returns 200 on the AWS server?

**Comment by bengotow** [comment]
Hmm... yeah I think the approach here needs to change - I think that for 99.9% of cases, using the sync engine from the last stable release of Mailspring would be better. Those are pretty much guaranteed to be there. Will change this!
