### ISSUE TITLE
Could you add a new function: auto bcc to myself?

### ISSUE THREAD

**Issue by jerry79** [Foundry376/Mailspring#275]
##### Are there any related issues?

...

##### What operating system are you using?
I used linux, and imap mailbox, when I send a mail, cannot save mail to the sendbox, so I bcc to myself every time, if you can support auto bcc, it is very pleasure. thanks very much

##### What version of Mailspring are you using?
...
now 1.0.6
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
no any plugins
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
no
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
no
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...
I used the Foxmail Client on Windows.

**Comment by bengotow** [comment]
Hey! This is definitely coming – we've had a bunch of requests and it should be fairly easy to add. It'll probably be bundled into a larger reworking of the Preferences > Accounts screen. 👍  Stay tuned!

**Comment by bengotow** [comment]
Hey! This is definitely coming – we've had a bunch of requests and it should be fairly easy to add. It'll probably be bundled into a larger reworking of the Preferences > Accounts screen. 👍  Stay tuned!

**Comment by teodorkasap** [comment]
hi,
it's good to hear that this feature will be coming soon. I have downloaded 1.0.9 snap package on ubuntu 16.04 and all the sync issues I was facing seem to have been resolved. Currently this is the only feature, which keeps me away from using Mailspring as primary offline email client. Thanks for the good work!

**Comment by bengotow** [comment]
Hey! This has landed on master and will ship in 1.0.12 very soon. Stay tuned! For now, the new option appears on the accounts page of preferences:

<img width="843" alt="image" src="https://user-images.githubusercontent.com/1037212/34416692-a78901f4-ebc2-11e7-8479-03fdee394972.png">
