### ISSUE TITLE
[Feature request] Make "update" alert dismiss-able

### ISSUE THREAD

**Issue by prajapati-parth** [Foundry376/Mailspring#276]
##### What operating system are you using?
... Ubuntu 16.04 LTS

##### What version of Mailspring are you using?
... 1.0.6

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
... None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
... No

**Feature Request?**
I think it would be great if the "update available" alert has a dismiss button or close icon.
![image](https://user-images.githubusercontent.com/17194534/32166504-131cb376-bd8c-11e7-9a76-1fb4e118d844.png)

Thanks for MailSpring! :+1:

**Comment by bengotow** [comment]
Hey! We'll be switching to a snap package on Linux soon and these alerts will go away. (The snap autoupdates itself without user interaction.) Stay tuned! It's almost ready but we're having a problem with mailto:// links.

**Comment by prajapati-parth** [comment]
All right!
