### ISSUE TITLE
Unable to paste any URL to highlighted text in email body.

### ISSUE THREAD

**Issue by Shickmo** [Foundry376/Mailspring#278]
##### What version of Mailspring are you using? 1.0.7-664204d8

**Bug?**
##### Is the issue reproducible with a particular attachment, message, signature, etc?
Hard to screenshot the issue but basically I highlight some text in the email and in the popup menu that appears I click on the edit link icon and try to paste the URL I wish to embed in the highlighted text. I would expect the text to change color reflecting it now being a link and be able to tell the URL I just pasted or typed is correct. What actually happens is the text I highlighted is erased and the URL is pasted where the text was I just highlighted. I followed this support [article](https://foundry376.zendesk.com/hc/en-us/articles/115001876671-Formatting-messages) so I believe that I am trying to do this correctly.

Thanks in advance for your help on this issue, or confirming I am a doofus and doing this wrong :) .

**Comment by zabil** [comment]
Maybe related.

---

### Steps to reproduce.

* Compose a new mail
* Type a text
* Use the ctrl+k option to make the text a link
* The text box for entering link loses focus.

![mailspringlink](https://user-images.githubusercontent.com/54427/32366899-2e6639e6-c0a6-11e7-9f1c-d869b4e139b6.gif)
---

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: elementary
Description:    elementary OS 0.4.1 Loki
Release:        0.4.1
Codename:       loki
```

##### What version of Mailspring are you using?
1.0.7-664204d8

**Comment by ronan18** [comment]
I have this issue too. I am using the latest version. (1.0.9)

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and a lot of other small improvements. You can grab the latest version from https://getmailspring.com/download.
