### ISSUE TITLE
Cannot find out how to open links contained in emails with Vivaldi

### ISSUE THREAD

**Issue by blackbart420** [Foundry376/Mailspring#281]
Hello,

this is an issue I had with nylas-mail too,

the links contained in emails open with Opera whereas I want them to open in Vivaldi.

Opera was my previous default browser but I switched to Vivaldi.

I am running on archlinux, with XFCE desktop environment and i3wm. 
I set Vivaldi as the default browser in XFCE favorites apps, so I do not understand why Mailspring opens Opera...

Thank you for the help

**Comment by bengotow** [comment]
Hey! You might have better luck asking on the Slack channel—Mailspring uses `xdg-open` to launch your browser on Linux (the same way other Electron apps do, so you could try searching for a similar issue with the Slack or Atom or VSCode projects). I'm not sure why that wouldn't work with your desktop environment.

**Comment by jmaybe** [comment]
You could try this: 
  Open the Whisker Menu and type _Preferred Applications_
    The open tab should show _Internet_ and _Web Browser_
  Change browser and close.
  Click a link in mail and it _should_ open in your newly selected browser.

**Comment by DrummerKH** [comment]
The same issue with former default browser Google Chrome and Firefox.
