### ISSUE TITLE
Forwarding with 'f' key breaks after aborted attempt

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#282]
##### Are there any related issues?

...

##### What operating system are you using?
Mac OS 10.12.6

##### What version of Mailspring are you using?
1.0.7

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Interesting bug. Here's how to reproduce:

1. Open a new email
2. Hit `f` to forward
3. Trash the draft
4. Hit `f` again to forward - now nothing happens

Seems to only happen with `f`. `r` and `a` continue to work.

**Comment by bengotow** [comment]
Confirmed! This is super strange... will see if we can get this fixed.
