### ISSUE TITLE
UX: Group Message Icons for Better Differentiation

### ISSUE THREAD

**Issue by jGleitz** [Foundry376/Mailspring#283]
Right now, there are nine¹ buttons at the top right of Mailspring:

![message actions](https://user-images.githubusercontent.com/4305652/32218555-813de51a-be2b-11e7-9b96-ccb2717cf698.png)

Now it may be a specific problem of mine that I have troubles scanning a line of similar-looking icons. But the notion that one should be aware of Gestalt laws, like proximity and similarity, when designing UX has also been stressed elaborately by others (e.g. [here](https://www.usertesting.com/blog/2016/02/24/gestalt-principles/)).

I want to suggest that those nine icons are arranged in a more meaningful way, by grouping them and/or changing their position and looks. For instance:

* “Archive”, “Trash”, “Spam” and “Move” will move the message. The former three are merely special cases of the last one. All will lead to the message being moved to another folder and being removed from view. Yet, “Move” is not placed next to the other three.

* “Mark as read” and “Star” will not move the message², but “mark” it in some way. So for me, they form another class of buttons

* From my point of view, “Snooze” and “Remind” form another, distinct class of buttons, but one may surely argue about that.

 * the contact button on the far right is only remotely concerned with the message being displayed. It actually changes the user interface by showing the contact pane (maybe the button could indicate that?)

Additionally, clicking “Archive”, “Trash”, “Spam”, “Mark read”, “Star” will directly change the message, while clicking “Move”, “Snooze” or “Remind” will first show some kind of dialogue before actually doing something. The buttons could represent that.

For me, it would be very helpful to better represent the different types of buttons in the user interface. I am not a UX designer, so there are surely people that have better ideas about *how* to do this. A start might be to group buttons. But having them look differently would be even better, IMHO.

Last, I want to point out that if the buttons are grouped and/ore changed in how they look, more attention could be drawn towards the features that make Mailspring special and are its selling point.

¹ I think it’s ten buttons for Gmail accounts because they also have a button to change the label.
² They will change whether the message shows up in the “Starred” and “Unread” sections, but I, as a user don’t think “put a copy in the starred folder” but rather “mark that message as starred”

**Comment by bengotow** [comment]
Hey! I think this would be great actually — the buttons are totally getting out of control, and there are other things (like the unsubscribe button) that will probably go in there too.

**Comment by bengotow** [comment]
This has been implemented in 699d67a9f4d6b72f2d05bfee72ddee054414906b - will ship in 1.2.0 soon!

<img width="582" alt="image" src="https://user-images.githubusercontent.com/1037212/38263285-92a0691e-3724-11e8-863c-2180a7c1ec4e.png">

**Comment by jGleitz** [comment]
Hey, this looks really cool! Great to see this!

**Comment by bengotow** [comment]
This has shipped! Thanks for the suggestions and feedback everyone.
