### ISSUE TITLE
Toggle Screenshot Mode not working

### ISSUE THREAD

**Issue by agurz** [Foundry376/Mailspring#287]
Console output:

<img width="1440" alt="screen shot 2017-11-01 at 11 25 36 am" src="https://user-images.githubusercontent.com/13837769/32279459-9277c180-bef7-11e7-8884-4139fc4bc11d.png">

##### Are there any related issues?

No, AFAIK

##### What operating system are you using?
macOS Sierra

##### What version of Mailspring are you using?
1.0.7

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

**Comment by bengotow** [comment]
Oh interesting—it looks like the `path` module needs to be required at the top of the `internal_packages/screenshot-mode/lib/main.coffee` file. Anybody want to take a stab at fixing this, and maybe converting that coffeescript to ES6? (with a `.es6` extension so it gets transpiled) Would be really helpful!

**Comment by bengotow** [comment]
Merged this and it'll be fixed in the next release! Thanks @agurz
