### ISSUE TITLE
Images are not visible in the body of the message after sending

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#288]
Hello

I wrote a new message. I answered a message.(with version 1.0.6)

Usually, with versions Nylas N1 or Nylas mails, I could not insert images directly into the message. I found that this feature was not included at the moment in Mailspring.

To work around this limitation with Nylas Mails, I copied the images to the clipboard and I could paste the images into the message. After sending, the images were still in the body of the message and the display of the images was correctly displayed at the addressee.
With Mailspring, I can paste the images into the message and during the writing of the message, the images are well displayed. But after sending, the images are no longer in the body of the message and appear in attached files.
Problem: Images are not visible in the body of the message

##### What operating system are you using?
Windows 10 x32bits

##### What version of Mailspring are you using?
1.0.6

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No, none installed

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I attach a screenshot

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
yes
![images problem](https://user-images.githubusercontent.com/31793920/32279307-ab67b9a4-bf18-11e7-841a-7ce669030ed4.png)

**Comment by donmoskeyra** [comment]
I need this issue solved!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we fixed two issues with inline images in 1.0.9, so this may be fixed. Could you check and see if you're still running in to this after the update?

**Comment by franco27** [comment]
Thank you, you have solved this problem. With version 1.0.9, I can still paste an image from the clipboard but after sending the message, the image is always in the body of the message (the image is no longer moved as an attached file) 
In the other messaging software, I did the test, for eM Client and Mailbird, now in the body of the message, the images are no longer reported as missing images.
The images are correctly visible in the body of the message.

Thanks again ! When will there be a button to insert images in the message, or since the context menu from the "new message" window?

**Comment by bengotow** [comment]
Great! Glad I could help - right now, if you paste, Mailspring will always put the image in the body of the email. If you use the attachment icon at the bottom of the composer to choose an image file from your computer, then it'll be attached at the bottom as an attachment. Hope that helps—

**Comment by franco27** [comment]
Yes, you have helped a lot . I thank you very much.

it's a pity that there is not in the context menu for example a menu to insert an image in the body of the message from an image file.
