### ISSUE TITLE
Synchronization problem after update  (1.0.6  > 1.0.7) Windows10

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#289]
Hello

After updating to the 1.0.7 version, the synchronization panel could not display or expand to see the progress. (the "synchronization In progress" message was displayed)
The reception and sending of the messages did not want to run and the synchronization was frozen.
(no problem to report after installing 1.0.6)

1 / the update by Mailspring did not work: error message. (1.0.6 to 1.0.7) (with Windows10 x32)
2 / I downloaded the version 107 installation file, I opened this file and installed version 107
3 / version 1.0.7 of Mailspring has opened and there is no error message.
4/the synchronization panel could not display or expand to see the progress. (the "synchronization In progress" message was displayed)
The reception and sending of the messages did not want to run and the synchronization was frozen.

The software behaves strangely.
(Yesterday for the Linux version (.deb ubuntu x64bits), I had no problem after the update.)

I was forced to completely uninstall Mailspring.
Because after uninstall/new installation of Mailspring 1.0.7, the problem is always present.

I deleted the user folders (the 2 folders in AppData) and after the problem was resolved but I was forced to add my mail accounts again and reset my settings.

##### What operating system are you using?
Windows 10 x32bits

##### What version of Mailspring are you using?
version 1.0.6 was installed. Automatic update not possible: Error message

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no , 4 accounts mails (gmail,+ gmx,+laposte, and  antdm(mail website)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—that's really strange. If you open `C:\Users\<your account>\AppData\Roaming\Mailspring\mailsync-*.log`, do you see any sort of error messages? If you could post the last 100 lines or so of those files it'd be really helpful to narrow this down.

**Comment by franco27** [comment]
Unfortunately I deleted this folder after the uninstall Mailspring. \AppData\Roaming\Mailspring
and this folder \AppData\local\Mailspring

I can't find the. log file anymore.
If this problem happens again with the next update, I will send you this file.

I am French. Will there be a French translation?
Have you planned for language support? I would like to make the French translation.

**Comment by franco27** [comment]
after removing these folders and uninstalling, I made a new installation with version 1.0.7.
I solved this problem but was forced to add my email accounts again ...

**Comment by franco27** [comment]
This issue has not been reproduced for the 1.0.8 update.
I was in version 1.0.7 on my other Windows 10 x64 computer.

**Comment by franco27** [comment]
This issue has not been reproduced for the 1.0.9 update.
I was in version 1.0.8 on my other Windows 10 x64 computer. and Windows 10 x32 computer.

**Comment by bengotow** [comment]
Hey—thanks @franco27, so you haven't seen this issue anymore? I'll go ahead and close the thread.

**Comment by franco27** [comment]
this problem is solved. for the update to version 1.0.10, the problem has not been reproduced
