### ISSUE TITLE
Email Account Configuration Error

### ISSUE THREAD

**Issue by ruggeroland** [Foundry376/Mailspring#295]
Hi, I just installed mailspring.
When I try to configure my email address I always get error "IMAP error certificate"
If I try to configure with the same parameters on another client I will not receive any error.
Use Ubuntu 16.04

**Comment by bengotow** [comment]
Hey! Thanks for reporting this — by default Mailspring does strict certificate checking on SSL connections, so if you mail server is using a self-signed certificate or an expired certificate for SSL, it will fail to connect. This is important for preventing MITM attacks.

Try putting a common server like `imap.gmail.com` in the IMAP server field. If you still get the certificate error, it means Mailspring can't find the certificate trust chain on your computer. On Linux, you may need to install the `ca-certificates` package, but it's almost always present. Mailspring looks for certificates in the following locations:

        // Debian, Ubuntu, Arch: maintained by update-ca-certificates
        /etc/ssl/certs/ca-certificates.crt

        // Red Hat 5+, Fedora, Centos
        /etc/pki/tls/certs/ca-bundle.crt

        // Red Hat 4
        /usr/share/ssl/certs/ca-bundle.crt

        // FreeBSD (security/ca-root-nss package)
        /usr/local/share/certs/ca-root-nss.crt

        // FreeBSD (deprecated security/ca-root package, removed 2008)
        /usr/local/share/certs/ca-root.crt

        // FreeBSD (optional symlink)
        // OpenBSD
        /etc/ssl/cert.pem

        // OpenSUSE
        /etc/ssl/ca-bundle.pem


If `imap.gmail.com` works correctly, your server is using an untrusted certificate and you'll need to disable the certificate checks by clicking the "Allow Insecure SSL" checkbox.

Hope that helps!

**Comment by ruggeroland** [comment]
Hi, I've entered imap.gmail.com with my account.
But I always have the same mistake.
/etc/ssl/certs/ca-certificates.crt is present in my ubuntu
Do you have any other help for me?
Thank you!

**Comment by bengotow** [comment]
Hey! Were you able to get this resolved? I'm gonna close this one since we haven't seen any more reports. If you still see this, let me know - you may want to try the `Snapcraft` release as well via `snap install mailspring`.
