### ISSUE TITLE
no-drafts-folder

### ISSUE THREAD

**Issue by nmrshll** [Foundry376/Mailspring#298]
On ubuntu 16.10, on a new installation of mailspring, I get this message when trying to send an email through my company's IMAP server:

An unknown error occurred: {"key":"no-drafts-folder","debuginfo":"This account does not have a folder with `role` = `drafts` or `all`."}

I tried to create a "drafts" folder but it doesn't seem to create it successfully (it just doesn't appear when I create it).

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - could you try creating a Drafts folder via your webmail, and then in Mailspring go to Preferences > Folders and mark that the new folder is your Drafts folder? Let me know if that works–we may need to make changes to the sync engine but I'm not sure offhand.

**Comment by bengotow** [comment]
Closing as resolved 👍
