### ISSUE TITLE
"Show original" does not show original 

### ISSUE THREAD

**Issue by louim** [Foundry376/Mailspring#300]
##### Are there any related issues?

No

##### What operating system are you using?

Mac OS X Sierra

##### What version of Mailspring are you using?

Version 1.0.7 (1.0.7)

---

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

The "show original" button used to open a new window with the raw email in Nylas mail. Currently, clicking it doesn't seem to do anything. It was really useful to debug and check the source of the mail. 
![image](https://user-images.githubusercontent.com/923718/32380443-728b97f8-c086-11e7-87d0-1541bb8c79c4.png)

--

**Feature Request?**

**Comment by bengotow** [comment]
This should be fixed in the next release—didn't think about anybody else know about this one ;-) Really need to get this into a real menu.
