### ISSUE TITLE
Please add these issue labels

### ISSUE THREAD

**Issue by HugoReeves** [Foundry376/Mailspring#302]
Could you please add the following two issue labels.

- "community check needed" or some similar named tag. Applied to issues that need community members to check if the bug exists across platforms. Community members can corroborate reports of bugs on certain platforms or on certain mail services
- "good first issue" for issues that are approachable for newbies wanting to make their first pr or just want to help out quickly

**Comment by bengotow** [comment]
Sure! `Help wanted` is our equivalent of `Good First Issue`, so i'll just rename that one. `Not Yet Actionable` is usually that I put on things that need to be corroborated or need more reproduction so I'll rename that to `Needs Reproduction` which might be more clear for folks that want to help out!
