### ISSUE TITLE
Bug on IMAP account

### ISSUE THREAD

**Issue by mitchazj** [Foundry376/Mailspring#303]
##### Are there any related issues?

Not that I can see :)

##### What operating system are you using?
Error occurring on both Ubuntu 16.04 and Windows 10

##### What version of Mailspring are you using?
1.0.7-664204d8

**Bug?** Yes
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Yes, it's related to a specific provider. My Gmail works fine, the issue occurs on my university email which is outsourced to Microsoft: the IMAP servers are outlook.office365.com and smtp.office365.com respectively.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I didn't notice any issues on the first public release of Mailspring, after an update (can't remember which) it started only syncing mail for 30 seconds or so before crashing and refusing to sync.

Screenshots from Ubuntu (the exact same symptoms occur on Windows 10, but I don't get the popup explaining what happened):
https://imgur.com/a/3car1
https://imgur.com/a/cUhgu
https://imgur.com/a/YDKjl

I've tried re-authenticating the account, unfortunately after doing this it briefly connects (for 15 seconds or so) before crashing again.

--

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - on your Linux machine, can you try opening the files at `~/.config/Mailspring/mailsync-**.log`> The bottom of those files should contain exceptions when this problem occurs. If you could paste the last 100 lines or so here, it'd be really helpful. (Those logs should contain complete stack traces so we can see exactly how it's crashing.) Thanks!

**Comment by mitchazj** [comment]
Sure thing:

**Comment by mitchazj** [comment]
11249 [2017-11-03 23:42:58.646] [main] [info] ------------- Starting Sync (<redacted>@connect.qut.edu.au) ---------------
11249 [2017-11-03 23:42:58.649] [] [info] Marking all folders as `busy`
11249 [2017-11-03 23:42:58.649] [metadata] [info] Metadata delta stream starting...
11249 [2017-11-03 23:42:58.651] [] [info] Syncing folder list...
11249 [2017-11-03 23:42:59.539] [] [info] Syncing folder list...
11249 [2017-11-03 23:42:59.809] [] [critical] 
 ***
 *** A string exception occurred during program execution: 
 *** blow up the world
 ***

11249 [2017-11-03 23:42:59.821] [] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

2801 [2017-11-04 13:41:52.060] [main] [info] ------------- Starting Sync (<redacted>@connect.qut.edu.au) ---------------
2801 [2017-11-04 13:41:52.063] [background] [info] Marking all folders as `busy`
2801 [2017-11-04 13:41:52.063] [metadata] [info] Metadata delta stream starting...
2801 [2017-11-04 13:41:52.175] [background] [info] Syncing folder list...
2801 [2017-11-04 13:41:53.129] [metadata] [info] Received metadata V11 for (message - SJFWWPHXzQDSVGKnseDakPJXaQq1fTcyd9R4oBwrj)
2801 [2017-11-04 13:41:53.129] [metadata] [info]  -- Saved on to local model.
2801 [2017-11-04 13:41:53.664] [background] [info] Syncing folder list...
2801 [2017-11-04 13:41:53.802] [background] [info] syncFolderUIDRange - (INBOX, UIDs: 20020 - 20031, Heavy: true)
2801 [2017-11-04 13:41:54.333] [foreground] [info] syncFolderUIDRange - (INBOX, UIDs: 19671 - 20031, Heavy: false)
2801 [2017-11-04 13:41:54.387] [background] [info] syncFolderUIDRange - (INBOX, UIDs: 17880 - 20031, Heavy: false)
2801 [2017-11-04 13:41:54.458] [background] [error] syncFolderUIDRange - Fetching full headers for 1
2801 [2017-11-04 13:41:54.509] [foreground] [info] Idling on folder INBOX
2801 [2017-11-04 13:41:54.598] [background] [info] 🔸 Updating message 757=18753 with subject: RE: Hack the North
2801 [2017-11-04 13:41:54.700] [background] [info] syncFolderUIDRange - (Sent Items, UIDs: 1 - 816, Heavy: false)
2801 [2017-11-04 13:41:54.832] [background] [error] syncFolderUIDRange - Fetching full headers for 10
2801 [2017-11-04 13:41:55.135] [background] [info] 🔸 Updating message 18753=757 with subject: RE: Hack the North
2801 [2017-11-04 13:41:55.158] [background] [info] 🔸 Updating message 545=554 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.160] [background] [info] 🔸 Updating message 554=553 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.162] [background] [info] 🔸 Updating message 553=552 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.164] [background] [info] 🔸 Updating message 552=551 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.166] [background] [info] 🔸 Updating message 551=550 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.167] [background] [info] 🔸 Updating message 550=549 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.169] [background] [info] 🔸 Updating message 549=548 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.171] [background] [info] 🔸 Updating message 548=547 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.173] [background] [info] 🔸 Updating message 547=546 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.217] [background] [critical] 
 ***
 *** A string exception occurred during program execution: 
 *** blow up the world
 ***

2801 [2017-11-04 13:41:55.251] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

2856 [2017-11-04 13:41:55.464] [main] [info] ------------- Starting Sync (<redacted>@connect.qut.edu.au) ---------------
2856 [2017-11-04 13:41:55.467] [background] [info] Marking all folders as `busy`
2856 [2017-11-04 13:41:55.467] [metadata] [info] Metadata delta stream starting...
2856 [2017-11-04 13:41:55.469] [background] [info] Syncing folder list...
2856 [2017-11-04 13:41:56.089] [background] [info] Syncing folder list...
2856 [2017-11-04 13:41:56.265] [background] [critical] 
 ***
 *** A string exception occurred during program execution: 
 *** blow up the world
 ***

2856 [2017-11-04 13:41:56.277] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

2881 [2017-11-04 13:41:56.398] [main] [info] ------------- Starting Sync (<redacted>@connect.qut.edu.au) ---------------
2881 [2017-11-04 13:41:56.401] [background] [info] Marking all folders as `busy`
2881 [2017-11-04 13:41:56.401] [metadata] [info] Metadata delta stream starting...
2881 [2017-11-04 13:41:56.404] [background] [info] Syncing folder list...
2881 [2017-11-04 13:41:57.073] [background] [info] Syncing folder list...
2881 [2017-11-04 13:41:57.252] [background] [critical] 
 ***
 *** A string exception occurred during program execution: 
 *** blow up the world
 ***

2881 [2017-11-04 13:41:57.265] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

2902 [2017-11-04 13:41:57.386] [main] [info] ------------- Starting Sync (<redacted>@connect.qut.edu.au) ---------------
2902 [2017-11-04 13:41:57.389] [background] [info] Marking all folders as `busy`
2902 [2017-11-04 13:41:57.389] [metadata] [info] Metadata delta stream starting...
2902 [2017-11-04 13:41:57.392] [background] [info] Syncing folder list...
2902 [2017-11-04 13:41:58.038] [background] [info] Syncing folder list...
2902 [2017-11-04 13:41:58.215] [background] [critical] 
 ***
 *** A string exception occurred during program execution: 
 *** blow up the world
 ***

2902 [2017-11-04 13:41:58.228] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

2924 [2017-11-04 13:41:58.348] [main] [info] ------------- Starting Sync (<redacted>@connect.qut.edu.au) ---------------
2924 [2017-11-04 13:41:58.350] [background] [info] Marking all folders as `busy`
2924 [2017-11-04 13:41:58.350] [metadata] [info] Metadata delta stream starting...
2924 [2017-11-04 13:41:58.352] [background] [info] Syncing folder list...
2924 [2017-11-04 13:41:58.956] [background] [info] Syncing folder list...
2924 [2017-11-04 13:41:59.167] [background] [critical] 
 ***
 *** A string exception occurred during program execution: 
 *** blow up the world
 ***

2924 [2017-11-04 13:41:59.179] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

**Comment by mitchazj** [comment]
```
11249 [2017-11-03 23:42:58.646] [main] [info] ------------- Starting Sync (<redacted>@connect.qut.edu.au) ---------------
11249 [2017-11-03 23:42:58.649] [] [info] Marking all folders as `busy`
11249 [2017-11-03 23:42:58.649] [metadata] [info] Metadata delta stream starting...
11249 [2017-11-03 23:42:58.651] [] [info] Syncing folder list...
11249 [2017-11-03 23:42:59.539] [] [info] Syncing folder list...
11249 [2017-11-03 23:42:59.809] [] [critical] 
 ***
 *** A string exception occurred during program execution: 
 *** blow up the world
 ***

11249 [2017-11-03 23:42:59.821] [] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

2801 [2017-11-04 13:41:52.060] [main] [info] ------------- Starting Sync (<redacted>@connect.qut.edu.au) ---------------
2801 [2017-11-04 13:41:52.063] [background] [info] Marking all folders as `busy`
2801 [2017-11-04 13:41:52.063] [metadata] [info] Metadata delta stream starting...
2801 [2017-11-04 13:41:52.175] [background] [info] Syncing folder list...
2801 [2017-11-04 13:41:53.129] [metadata] [info] Received metadata V11 for (message - SJFWWPHXzQDSVGKnseDakPJXaQq1fTcyd9R4oBwrj)
2801 [2017-11-04 13:41:53.129] [metadata] [info]  -- Saved on to local model.
2801 [2017-11-04 13:41:53.664] [background] [info] Syncing folder list...
2801 [2017-11-04 13:41:53.802] [background] [info] syncFolderUIDRange - (INBOX, UIDs: 20020 - 20031, Heavy: true)
2801 [2017-11-04 13:41:54.333] [foreground] [info] syncFolderUIDRange - (INBOX, UIDs: 19671 - 20031, Heavy: false)
2801 [2017-11-04 13:41:54.387] [background] [info] syncFolderUIDRange - (INBOX, UIDs: 17880 - 20031, Heavy: false)
2801 [2017-11-04 13:41:54.458] [background] [error] syncFolderUIDRange - Fetching full headers for 1
2801 [2017-11-04 13:41:54.509] [foreground] [info] Idling on folder INBOX
2801 [2017-11-04 13:41:54.598] [background] [info] 🔸 Updating message 757=18753 with subject: RE: Hack the North
2801 [2017-11-04 13:41:54.700] [background] [info] syncFolderUIDRange - (Sent Items, UIDs: 1 - 816, Heavy: false)
2801 [2017-11-04 13:41:54.832] [background] [error] syncFolderUIDRange - Fetching full headers for 10
2801 [2017-11-04 13:41:55.135] [background] [info] 🔸 Updating message 18753=757 with subject: RE: Hack the North
2801 [2017-11-04 13:41:55.158] [background] [info] 🔸 Updating message 545=554 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.160] [background] [info] 🔸 Updating message 554=553 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.162] [background] [info] 🔸 Updating message 553=552 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.164] [background] [info] 🔸 Updating message 552=551 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.166] [background] [info] 🔸 Updating message 551=550 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.167] [background] [info] 🔸 Updating message 550=549 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.169] [background] [info] 🔸 Updating message 549=548 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.171] [background] [info] 🔸 Updating message 548=547 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.173] [background] [info] 🔸 Updating message 547=546 with subject: IAB201 Week 9 L
2801 [2017-11-04 13:41:55.217] [background] [critical] 
 ***
 *** A string exception occurred during program execution: 
 *** blow up the world
 ***

2801 [2017-11-04 13:41:55.251] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

2856 [2017-11-04 13:41:55.464] [main] [info] ------------- Starting Sync (<redacted>@connect.qut.edu.au) ---------------
2856 [2017-11-04 13:41:55.467] [background] [info] Marking all folders as `busy`
2856 [2017-11-04 13:41:55.467] [metadata] [info] Metadata delta stream starting...
2856 [2017-11-04 13:41:55.469] [background] [info] Syncing folder list...
2856 [2017-11-04 13:41:56.089] [background] [info] Syncing folder list...
2856 [2017-11-04 13:41:56.265] [background] [critical] 
 ***
 *** A string exception occurred during program execution: 
 *** blow up the world
 ***

2856 [2017-11-04 13:41:56.277] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

2881 [2017-11-04 13:41:56.398] [main] [info] ------------- Starting Sync (<redacted>@connect.qut.edu.au) ---------------
2881 [2017-11-04 13:41:56.401] [background] [info] Marking all folders as `busy`
2881 [2017-11-04 13:41:56.401] [metadata] [info] Metadata delta stream starting...
2881 [2017-11-04 13:41:56.404] [background] [info] Syncing folder list...
2881 [2017-11-04 13:41:57.073] [background] [info] Syncing folder list...
2881 [2017-11-04 13:41:57.252] [background] [critical] 
 ***
 *** A string exception occurred during program execution: 
 *** blow up the world
 ***

2881 [2017-11-04 13:41:57.265] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

2902 [2017-11-04 13:41:57.386] [main] [info] ------------- Starting Sync (<redacted>@connect.qut.edu.au) ---------------
2902 [2017-11-04 13:41:57.389] [background] [info] Marking all folders as `busy`
2902 [2017-11-04 13:41:57.389] [metadata] [info] Metadata delta stream starting...
2902 [2017-11-04 13:41:57.392] [background] [info] Syncing folder list...
2902 [2017-11-04 13:41:58.038] [background] [info] Syncing folder list...
2902 [2017-11-04 13:41:58.215] [background] [critical] 
 ***
 *** A string exception occurred during program execution: 
 *** blow up the world
 ***

2902 [2017-11-04 13:41:58.228] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

2924 [2017-11-04 13:41:58.348] [main] [info] ------------- Starting Sync (<redacted>@connect.qut.edu.au) ---------------
2924 [2017-11-04 13:41:58.350] [background] [info] Marking all folders as `busy`
2924 [2017-11-04 13:41:58.350] [metadata] [info] Metadata delta stream starting...
2924 [2017-11-04 13:41:58.352] [background] [info] Syncing folder list...
2924 [2017-11-04 13:41:58.956] [background] [info] Syncing folder list...
2924 [2017-11-04 13:41:59.167] [background] [critical] 
 ***
 *** A string exception occurred during program execution: 
 *** blow up the world
 ***

2924 [2017-11-04 13:41:59.179] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

**Comment by bengotow** [comment]
Hey folks—we haven't seen any reports of this in several months so I'm gonna go ahead and close this. It was likely fixed by another patch and we just didn't tie it back. That specific error message `blow up the world` has been replaced with correct handling of UID Invalidity scenarios. Thanks!
