### ISSUE TITLE
Libappindicator1 dependency in Fedora

### ISSUE THREAD

**Issue by mthomos** [Foundry376/Mailspring#306]
Fedora does't have the libappindicator1 package but libappindicator package and the counter in the system tray doesn't appear. Can you symlink libappindicator1 with libappindicator in Fedora ? 
Thanks!

**Comment by bengotow** [comment]
Hey thanks! Looks like on Fedora we can just make `libappindicator` a dependency. Cheers!

**Comment by geckolinux** [comment]
Hi, unfortunately this change breaks the package for openSUSE (Tumbleweed in my case). Tumbleweed has:
- https://software.opensuse.org/package/libappindicator1
- https://software.opensuse.org/package/libappindicator3-1
But there is no `libappindicator` package.
