### ISSUE TITLE
Have to delete emails twice for them to actually delete from inbox.

### ISSUE THREAD

**Issue by Shickmo** [Foundry376/Mailspring#312]
##### Are there any related issues?
Not that I saw with a brief search.

##### What operating system are you using?
POP_OS! (Ubuntu 17.10 under lying distro)

##### What version of Mailspring are you using?
1.07-664204d8

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Connecting to Office 365 business account.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
This issue doesn't appear to be content or attachment related. Basically if you select a large amount of messages, shoot for more than 25, and try to mark them as read followed by deleting them. I can't seem to make this happen every time but it seems intermittently after I delete the messages a moment or two later they all return to my inbox, marked as read now, but I now have to delete them a second time. 

All of that to say its happening enough and I am noticing it enough to open this bug. Please note I have m set as the shortcut to mark the emails as read, which is how I am performing that task, and I have the del key mapped to delete email, which is how I am performing that task. I have the keyboard shortcut set to outlook at this time. 

Thanks in advance for your help.

**Comment by fcoury** [comment]
Also seeing this using macOS 10.12.6, no plugins, connecting to Gmail and for almost any received message.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—there's a fix for this odd "flickering" and inconsistent archiving / trashing behavior in the next release. It was actually a race condition that occurred when the app tried to mark as read and move the messages at the same time. Stay tuned!

**Comment by fcoury** [comment]
Here's an additional weirdness around archive:

![](https://cl.ly/0w3r460E3S1C/download/Screen%20Recording%202017-11-10%20at%2001.17%20PM.gif)

Is it related?
