### ISSUE TITLE
Can't search in sent folders

### ISSUE THREAD

**Issue by JunnanZ** [Foundry376/Mailspring#315]
##### Are there any related issues?
No.

##### What operating system are you using?
Arch

##### What version of Mailspring are you using?
1.0.7

--

**Bug?**
If I search in "Sent Mail", it keeps loading but no result is shown. Searching in inbox is fine and fast.
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No. 

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! This is a bit random, but can you try adding the word AND and see if it works? eg: `blabla AND in:sent`. Trying to reproduce this now and it seems to get upset if the AND Is omitted, which I think is a bug.

**Comment by bengotow** [comment]
This should be fixed by a416c4b0fab24274d1b2a45f82487f0a4670c4a3

**Comment by JunnanZ** [comment]
Adding AND works. Waiting for the new release.

**Comment by Hronom** [comment]
`1.0.8` still have this issue

**Comment by JunnanZ** [comment]
@bengotow I just installed the latest version. It doesn't stuck at loading anymore, but it just returns no result no matter what I search.

**Comment by bengotow** [comment]
Hey folks! Thanks for the updates—we fixed another bug in `1.0.10` that caused Mailspring's search to fail in the context of folders (#184) - this should be good to go now. Let me know if you still encounter problems after downloading the update.

**Comment by JunnanZ** [comment]
@bengotow Thanks for the update. However, search `blah in:sent` in Inbox works, but search `blah` or `blah in:sent` in Sent Mail still return nothing.

**Comment by nicoceledon** [comment]
Hi, i have the version `1.0.11-ea4b20af` and I tried to do **Preferences > General > Reset Email Cache** (I don't have Rebuild Email Cache) but i still can't search in the Sent Folder. I have two accounts configured, and running on debian.

**Comment by jazruybal** [comment]
I have Version 1.0.12 (1.0.12) and nothing shows in my sent folder. There are lots of emails in my sent folder when I look at it in gmail. Have Mailspring installed on Mac and PC, same issue on both. I tried Preferences>General>Reset Email Cache and nothing changed. Still shows "No Messages" when I click on the Sent folder.

**Comment by krasi-georgiev** [comment]
```
SentEmail
   Account1
   Account2
```
when I click Sent email and search there it is all good , but when I click `Account1` or `Account2` and want to search there nothing shows. so root folder works , but sub-folders don't.

**Comment by krasi-georgiev** [comment]
this is on 1.1.0-7563...

**Comment by bengotow** [comment]
Hey folks—this has been fixed in 1.1.5 which shipped yesterday. You can download the update from https://getmailspring.com/download or choose "Check for Updates" within the app to install it. Enjoy!
