### ISSUE TITLE
[Feature Request] Add / improve select all behavior

### ISSUE THREAD

**Issue by abdonmosqueira** [Foundry376/Mailspring#316]
##### What operating system are you using?
Windows 10 / Linux Mint (Sonya)

##### What version of Mailspring are you using?
1.0.7

##### Feature Request?
Could you add "select all" button?
When we start selecting multi messages in folder there is just "clear selection" option on top right.

**Comment by slhck** [comment]
Isn't this a bug?

I would expect `Ctrl-A` or `Edit --> Select All` to select all messages when highlighting one message in a mailbox.

Instead, it selects the name and email address of the contact in the rightmost pane, if that is open, or the title of the message.

**Comment by bengotow** [comment]
Hey folks! There's a Select-All action in the app, but depending on your keyboard shortcuts it may not be bound to Cmd-A / Ctrl-A (which is odd.) Try `* a` if you're using the Gmail set.

We should definitely bind that to Ctrl-A all the time... actually not sure why it's not.

**Comment by fcoury** [comment]
@bengotow the `* a` workaround works great for the time being. Thanks.

**Comment by NikhilMTomy** [comment]
But it doesn't seem to select all the mails. For me it only selects upto 200 mails.

**Comment by stepedes** [comment]
Selecting the first mail, then scrolling down and shift clicking the last one works for me. But I would also appriciate a Ctrl A..

**Comment by grg2rsr** [comment]
for me, `ctrl+a` does not work, `*`,`a` selects 200 mails max just as @NikhilMTomy reported. Mailspring 1.1.2. Has this something to do with the mails not being available locally? When I scroll down, new messages appear as it seems like they have to be fetched first.

**Comment by akanarsky** [comment]
Same for me; Mailspring 1.1.5 on Linux Mint 18.3. Ctrl+A and "Edit->Select All" do nothing while `* a` selects 200 threads max.

**Comment by Galaxy0419** [comment]
The bug still exists with the latest version? Is there any fixes?

**Comment by TejasAvinashShetty** [comment]
Neither *a, nor Ctrl + A does anything
I have to use select all read or select all unread. Even then, I can choose only a maximum of  200 threads max.

**Comment by liarokapisv** [comment]
This bug still persists

**Comment by Kladizkov** [comment]
+1 Trying to delete around 1000+ mails from Archive folder. Select All doesn't work for me. Even holding shift button and selecting a big bunch by selecting the first and one at half down the list doesn't select them.

**Comment by NotZX2** [comment]
heres how you can fix this problem:

go to **edit > preferences > shortcuts**, after going to shortcuts scroll down and you'll see a "**selection**" tab then change ***a (for selecting all) to ctrl + a.**

![image](https://user-images.githubusercontent.com/44892352/105435579-31792100-5c90-11eb-8677-d5a8eda7f45b.png)


OS: windows 7 and ubuntu 20.04 LTS
Mailspring version: 1.8.0

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, I've migrated this issue to a question and answer on Discourse:

https://community.getmailspring.com/t/select-all-messages/171

@NotZX2 Please join there and comment on the thread, and I'll credit your answer to you!
