### ISSUE TITLE
Can't create account for local mail server, since its name does not contain dot

### ISSUE THREAD

**Issue by d-makarenko** [Foundry376/Mailspring#317]
Hi.

Our company uses "mail-serv" name for mail server. And Mailspring does not recognize this name as valid and refuses to create account.

**Comment by bengotow** [comment]
Hey! Man, totally didn't know this was a thing folks did with internal DNS :-) there's actually already a PR open to fix this (#286) so I'll get that merged.

**Comment by kryksyh** [comment]
Thank you!
