### ISSUE TITLE
[Feature Request] Allow IMAP folder mapping (Sent, Drafts, etc.) to be manually selected

### ISSUE THREAD

**Issue by Aleixenandros** [Foundry376/Mailspring#32]
I can not select the Sent and Deleted folder on my IMAP server
![imagen](https://user-images.githubusercontent.com/31532028/29976556-b4916e34-8f3a-11e7-862e-d4e28a824959.png)

This was already corrected in Nylas v2.0.32

**Comment by Aleixenandros** [comment]
![sin titulo](https://user-images.githubusercontent.com/31532028/31223506-d474cdfe-a9ca-11e7-9bcb-0dbc46b7c944.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—we've added this in version 1.0.4 which just shipped a few minutes ago. You can grab the update at getmailspring.com/download. Going to leave this open for a while so folks don't create duplicates, but you should be set!

**Comment by Aleixenandros** [comment]
Gracias!
