### ISSUE TITLE
Only build quicklook previews for images, etc. less than a certain size

### ISSUE THREAD

**Issue by lewisamarshall** [Foundry376/Mailspring#320]
##### What operating system are you using?
OSX

##### What version of Mailspring are you using?
1.0.7

--

qlmanager can consume large amounts of memory (I observed up to 20 GB virtual memory) when making thumbnails for attachments. I was able to remove this behavior by deselecting the "display thumbnails for attachments when available. (macOS only)" option. 

##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail and Microsoft Outlook 365 accounts

**Comment by bengotow** [comment]
Thanks for the heads up—i think the best fix here is to only render previews for images, etc. less than a certain size.

**Comment by bengotow** [comment]
Code is here for anyone that wants to take a look! https://github.com/Foundry376/Mailspring/blob/master/app/src/flux/stores/attachment-store.es6#L109 Would be really great to convert it to the new `async / await` pattern to avoid callback hell there...

**Comment by lewisamarshall** [comment]
Awesome. I don't have a lot of experience as a JS developer, but I would love to try fixing this. I'm really glad you brought back N1! ✨
