### ISSUE TITLE
On Roundcube, Mailspring can't create the [Mailspring] folder, which breaks snoozing

### ISSUE THREAD

**Issue by d-makarenko** [Foundry376/Mailspring#321]
##### Are there any related issues?
I didn't found any relates issues.

##### What operating system are you using?
Windows 7

##### What version of Mailspring are you using?
1.0.7

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I guess so. This issue only appear with my local mail server. 

##### Is the issue reproducible with a particular attachment, message, signature, etc?

It doesn't depend on message itself.

Logs

```
2788 [2017-11-08 13:56:07.690] [background] [error] Could not create required Mailspring folder: INBOX.[Mailspring].Snoozed. ErrorCreate
2788 [2017-11-08 13:56:07.703] [background] [info] syncFolderChangesViaCondstore - INBOX: highestmodseq, uidnext match, no changes.
2788 [2017-11-08 13:56:07.715] [background] [info] syncFolderChangesViaCondstore - INBOX.Sent: highestmodseq, uidnext match, no changes.
2788 [2017-11-08 13:56:07.729] [background] [info] syncFolderChangesViaCondstore - INBOX.Drafts: highestmodseq, uidnext match, no changes.
2788 [2017-11-08 13:56:07.741] [background] [info] syncFolderChangesViaCondstore - INBOX.Trash: highestmodseq, uidnext match, no changes.
2788 [2017-11-08 13:56:07.748] [background] [info] syncFolderChangesViaCondstore - INBOX.Junk: highestmodseq, uidnext match, no changes.
2788 [2017-11-08 13:56:07.756] [background] [info] syncFolderChangesViaCondstore - INBOX.&BB0ENQQ2BDUEOwQwBEIENQQ7BEwEPQQwBE8- &BD8EPgRHBEIEMA-: highestmodseq, uidnext match, no changes.
2788 [2017-11-08 13:56:07.768] [background] [info] syncFolderChangesViaCondstore - INBOX.&BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-: highestmodseq, uidnext match, no changes.
2788 [2017-11-08 13:56:07.778] [background] [info] syncFolderChangesViaCondstore - INBOX.&BCMENAQwBDsENQQ9BD0ESwQ1-: highestmodseq, uidnext match, no changes.
2788 [2017-11-08 13:56:07.787] [background] [info] syncFolderChangesViaCondstore - INBOX.Infected Items: highestmodseq, uidnext match, no changes.
2788 [2017-11-08 13:56:07.799] [background] [info] syncFolderChangesViaCondstore - INBOX.Junk E-mail: highestmodseq, uidnext match, no changes.
2788 [2017-11-08 13:56:07.811] [background] [info] syncFolderChangesViaCondstore - INBOX.Outbox: highestmodseq, uidnext match, no changes.
2788 [2017-11-08 13:56:07.814] [background] [info] Sync loop deleting unlinked messages with phase 2.
2788 [2017-11-08 13:56:07.817] [background] [info] Sync loop complete.

```

I think it might be because imap server is refusing to create "[Mailspring]" folder. I can't create it in roundcube webinterface either.

**Comment by bengotow** [comment]
Hey! Ahh that's really interesting - do you know if it's the `[` character that's upsetting roundcube? Does it work if you remove the square brackets?

**Comment by d-makarenko** [comment]
Yep, name "Mailspring" works fine.

**Comment by franco27** [comment]
I have an email address Roundcube Webmail 1.3.3.

The folder has been created. The [Mailspring] folder is grayed out. When I click on it, there is an error message.
See the screenshots.
![2017-11-10 15_18_38-adm tools webmail __ inbox](https://user-images.githubusercontent.com/31793920/32662591-5f8ff766-c62b-11e7-8564-9af775ea05b1.png)
![2017-11-10 15_13_56-adm tools webmail __ folders](https://user-images.githubusercontent.com/31793920/32662592-5fb61edc-c62b-11e7-80ab-187b51a69e4b.png)
![roundcube](https://user-images.githubusercontent.com/31793920/32662593-5fd77b22-c62b-11e7-9f57-231442b92a9d.png)

**Comment by bengotow** [comment]
Hey folks! In 1.1.2, which shipped last week, Mailspring will now create a `Mailspring` folder instead of `[Mailspring]`, which should take care of this. Enjoy!
