### ISSUE TITLE
Initial sync stopped - Unknown exception

### ISSUE THREAD

**Issue by cuddylier** [Foundry376/Mailspring#322]
##### Are there any related issues?
No

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.0.7

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
At least Outlook

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N/A

My mail stopped the initial sync at 97% for the inbox, I have a few million messages.

The logs show the following:

4816 [2017-11-08 21:09:58.872] [main] [info] ------------- Starting Sync (*****@hotmail.co.uk) ---------------
4816 [2017-11-08 21:09:58.879] [background] [info] Marking all folders as `busy`
4816 [2017-11-08 21:09:58.880] [metadata] [info] Metadata delta stream starting...
4816 [2017-11-08 21:09:58.899] [background] [info] Syncing folder list...
4816 [2017-11-08 21:10:00.358] [background] [info] Syncing folder list...
4816 [2017-11-08 21:10:00.446] [background] [info] syncFolderUIDRange - (INBOX, UIDs: 2483 - 7483, Heavy: true)
4816 [2017-11-08 21:10:02.068] [foreground] [info] syncFolderUIDRange - (INBOX, UIDs: 228331 - 228442, Heavy: false)
4816 [2017-11-08 21:10:10.814] [foreground] [info] Idling on folder INBOX
4816 [2017-11-08 21:10:13.888] [metadataExpiration] [info] Scanning for expired metadata
4816 [2017-11-08 21:10:13.888] [metadataExpiration] [info] -- Will wake for next expiration in 7201sec
4816 [2017-11-08 21:10:43.424] [background] [info] ðŸ”¸ Updating message 5782=5783 with subject: ***
4816 [2017-11-08 21:10:43.460] [background] [info] syncFolderUIDRange - (INBOX, UIDs: 2483 - 2482, Heavy: false)
4816 [2017-11-08 21:10:46.868] [background] [error] syncFolderUIDRange - Fetching full headers for 35
4816 [2017-11-08 21:11:16.927] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorConnection","retryable":true,"what":"Unknown exception"}

**Comment by bengotow** [comment]
Hey! This should be resolved in 1.0.9 which just shipped today. Thanks–

**Comment by cuddylier** [comment]
@bengotow Unfortunately it wasn't resolved by that update.

16424 [2017-12-02 15:37:13.641] [main] [info] ------------- Starting Sync (xxxxxx@hotmail.co.uk) ---------------
16424 [2017-12-02 15:37:13.647] [background] [info] Marking all folders as `busy`
16424 [2017-12-02 15:37:13.647] [metadata] [info] Metadata delta stream starting...
16424 [2017-12-02 15:37:13.657] [background] [info] Syncing folder list...
16424 [2017-12-02 15:37:14.945] [background] [info] Syncing folder list...
16424 [2017-12-02 15:37:15.019] [background] [info] syncFolderUIDRange - (INBOX, UIDs: 1 - 0, Heavy: false)
16424 [2017-12-02 15:37:16.395] [foreground] [info] syncFolderUIDRange - (INBOX, UIDs: 230275 - 230380, Heavy: false)
16424 [2017-12-02 15:37:23.537] [foreground] [error] syncFolderUIDRange - Fetching full headers for 2
16424 [2017-12-02 15:37:23.734] [foreground] [info] ðŸ”¸ Updating message 230379=230379 with subject: 
16424 [2017-12-02 15:37:23.779] [foreground] [info] ðŸ”¸ Updating message 230378=230378 with subject:
16424 [2017-12-02 15:37:24.482] [foreground] [info] Idling on folder INBOX
16424 [2017-12-02 15:37:26.861] [background] [error] syncFolderUIDRange - Fetching full headers for 37
16424 [2017-12-02 15:37:28.650] [metadataExpiration] [info] Scanning for expired metadata
16424 [2017-12-02 15:37:28.650] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
16424 [2017-12-02 15:37:56.898] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorConnection","retryable":true,"what":"Unknown exception"}
16424 [2017-12-02 15:38:01.354] [foreground] [info] Idle exited with code 0
16424 [2017-12-02 15:38:02.116] [foreground] [info] syncFolderUIDRange - (INBOX, UIDs: 230275 - 230380, Heavy: false)
16424 [2017-12-02 15:38:02.833] [foreground] [error] syncFolderUIDRange - Fetching full headers for 1
16424 [2017-12-02 15:38:03.884] [foreground] [info] Idling on folder INBOX
