### ISSUE TITLE
Linux distribution as a .tar.gzip (gzipped tarball)

### ISSUE THREAD

**Issue by mariosant** [Foundry376/Mailspring#325]
Hello!

I am trying to build Mailspring for my favorite Linux distro. The current Linux build system tries to create deb's and rpm's, but what I am really looking for is old plain gzipped tarballs.

Any advice how to do this?

**Comment by bengotow** [comment]
Hey! Later this week we're shipping a Linux snapcraft distribution that should resolve this, since .snap is a flatpak-style format and installs on most linux distributions. (Snap files are also just zip files, so if you still need the raw stuff it's easy to access.) Stay tuned!

**Comment by Cediddi** [comment]
This is great and all but I wish you leave deb. I'm using linux mint 17.3 (ubuntu.14.04) and I can't have snapd and I can't upgrade as my company requires a 14.04 based distro (for package compability issues). If you still want to remove rpm and deb packages, at least release tar.gz files so I can still use and upgrade manually. (I promise I'll set an alarm clock for upgrades)

**Comment by CodeMouse92** [comment]
As of 2021, we support both .deb and .snap.

---

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
