### ISSUE TITLE
[Feature Request] Ability to edit / rename contacts so they have full name + email

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#327]
##### Are there any related issues?

#86 #212 

##### What operating system are you using?
MacOS 10.12.6

##### What version of Mailspring are you using?
1.0.8

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

- In Mailspring, most email addresses are stored as "Jane Doe <jane.doe@domain.com>". But some are simply stored as jane.doe@domain.com, which is not as elegant or nice
- If possible, I would like the ability to edit those instances in the compose window, and then have Mailspring remember that I made the edit

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Obviously this would be solved by a full address book / contact manager, although honestly I don't think I really need that compared to this more simple fix.

**Comment by bengotow** [comment]
Related to #212

**Comment by bengotow** [comment]
Hey folks! I'm happy to announce that Mailspring 1.7.0 shipped earlier today, which includes a full address book (with CardDAV and Google support) accessible from **Window > Contacts** in the menu. Enjoy!
