### ISSUE TITLE
Contact Syncing (gmail)

### ISSUE THREAD

**Issue by mshallop** [Foundry376/Mailspring#329]
Ubuntu 16.05/Mailspring 1.0.8.x

I recently updated a contact by removing their email and replacing it with a new email address for my gmail account.

several days later, mailspring is still referencing the old email when I start typing the name.  However, if I type the first couple letters of the new email address, it pulls the reference, by the recipient's name, and correctly displays it in the To: field.

Start typing name:  wrong email address
Start typing right email address:  right name

Double checked on google to ensure that contact card was updated correctly (it was)

thanks!

**Comment by bengotow** [comment]
Hey! Currently the contact autocompletion in Mailspring is based on the headers of your emails, not your address book. Would definitely be nice to use Google Contacts / O365 contacts in the future!

**Comment by mshallop** [comment]
@bengotow thank you for the update -  it would be a nice feature, I agree!

Best email client, ever!

**Comment by Lyptik** [comment]
Up ! Hey guys I didn't find any place with this information, is there any sort of contact syncing, or plugins to use a google contacts address book ? Or is there only in pro ?
I personally can't use a mail client without a synced address book, pretty suprised a so advanced mail client as mailsping seems not to support it yet, is there some technical complexities to implement it ? Or is there no plugins to do it ?
