### ISSUE TITLE
ChangeFolderTask fails on remote

### ISSUE THREAD

**Issue by chris-hld** [Foundry376/Mailspring#330]
##### Are there any related issues?

No

##### What operating system are you using?
elementary OS 0.4.1 Loki

##### What version of Mailspring are you using?
1.0.8

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Exchange

##### Is the issue reproducible with a particular attachment, message, signature, etc?

When moving messages to trash or archive with my university mail account ([TU Berlin-exchange](http://www.tubit.tu-berlin.de/menue/dienste/kommunikation_internet/der_exchange_dienst/))
changes are not reflected/synced on the remote server.
This has been working in older versions, I believe < 1.0.3

5533 [2017-11-10 18:18:38.903] [main] [info] [local-eff9260b-b2b8] Running ChangeFolderTask performLocal:
5533 [2017-11-10 18:18:38.911] [main] [info] [local-eff9260b-b2b8] -- Succeeded. Changing status to `remote`
5533 [2017-11-10 18:18:39.228] [foreground] [info] Idle exited with code 0
5533 [2017-11-10 18:18:39.236] [foreground] [info] [local-eff9260b-b2b8] Running ChangeFolderTask performRemote:
5533 [2017-11-10 18:18:39.503] [foreground] [error] [local-eff9260b-b2b8] -- Failed ({"debuginfo":"moveMessages","key":"ErrorCopy","retryable":false,"what":"std::exception"}). Changing status to `complete`
5533 [2017-11-10 18:18:39.549] [foreground] [info] syncFolderUIDRange - (INBOX, UIDs: 1 - 6432, Heavy: false)
5533 [2017-11-10 18:18:39.623] [foreground] [error] syncFolderUIDRange - Fetching full headers for 23

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hmm this is interesting - this is probably what's happening in #335 too.

**Comment by bengotow** [comment]
Hey folks—I think we've figured this out in #364. Mailspring required the IMAP `MOVE` extension to actually place messages in the trash, archive, etc. and it seems a fair number of providers still don't support that extension. In 1.0.11, we'll fall back to the very old school approach of `COPY, STORE, DELETE` when the MOVE capability isn't available.  It's a bit slower but should ensure that deleting / archiving messages works absolutely everywhere.

Sorry for the hassle—I actually hadn't seen an IMAP server that didn't support the MOVE extension, and the underlying mailcore2 library we use for IMAP was assuming it would always be present. I'm going to continue testing the fix but 1.0.11 should ship in a couple days.

**Comment by bengotow** [comment]
Hey folks - this has shipped in 1.0.11. The app will download the update automatically, but you can get it directly here: https://www.getmailspring.com/download. Gonna go ahead and close this—if you continue to have trouble after the update, let me know and I'll re-open it!
