### ISSUE TITLE
[Feature Request] Paste files from Explorer/Finder/Nautilus et al. as attachments while in compose window.

### ISSUE THREAD

**Issue by gitbobbed** [Foundry376/Mailspring#331]
Would be nice to copy a file from your file manager of choice and have it automatically inserted as an attachment once I press Cmd/Ctrl + V in the compose window.

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes. Spark and Airmail both do it. 

Spark has the 'smarter' implementation, IMHO: it pastes the file as an attachment if I press Cmd + V in the compose windows but only pastes the name if I press Cmd + V in the subject field. 

Airmail pastes the file as an attachment and adds the filename to current current cursor position in the compose window. Only pastes the file name if I press Cmd + V in the subject field.
...

**Comment by bengotow** [comment]
Hey! This would definitely be cool. I tried to implement it, but it looks like by the time the event reaches JavaScript in the window, `event.clipboardData.items` is just `text/plain` when you've selected and copied a few items in the Finder. (It's just the filenames.) `require('electron').clipboard.availableFormats()` is also just `text/plain`, so I'm not sure how to obtain the file references offhand. Will see what we can do!

In the meantime, you can drag and drop the files, or drag onto the app icon to attach files to a new draft. Hope that helps!

**Comment by bengotow** [comment]
Turns out we actually could do this - at least for a single file copied onto the clipboard, it just isn't documented and doesn't come back in availableFormats() for some reason!

**Comment by gitbobbed** [comment]
Hey there!

I'm not a developer, but from some quick google-fu it seems that the W3 standard does support it and that Google does do some javascript trickery to get pictures pasted in webpages in Chrome, so glad to hear that something works, even if it's just for one file!

It's a great feature to have, honestly, especially for people who don't like to lift their hands out of the keyboard unless absolutely necessary.

Also, let me know about the translation thing I mentioned earlier. This is a great project, and I'd love to contribute with my expertise if it becomes useful.

Best,

Daniel

Daniel Pereira Maciel
+55 61 981-300-300 | +1 415-466-5661

Sworn Translator and Interpreter
English <> Portuguese (BR)
http://www.linkedin.com/in/dpmaciel (https://link.getmailspring.com/link/local-887c6542-0899@Daniels-iMac.local/1?redirect=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fdpmaciel&recipient=reply%2B0200051d989c4134bb2d5af03a5a0133c7c47da3a250068892cf000000011620615d92a169ce10460784%40reply.github.com)
