### ISSUE TITLE
Bad spam score when sending as alias

### ISSUE THREAD

**Issue by TomOnGit** [Foundry376/Mailspring#337]
I've configured a few "Send mail as" aliases in Gmail (which have Amazon SES SMTP configured to send mail through).

When I send from one of these aliases from Mailspring, the mail gets a 4.4 spam score (scale 0-10, 10 is best). When I send a similar mail from Gmail the mail gets a 8.5 spam score.

send from Mailspring: https://www.mail-tester.com/web-b7sqj
send from Gmail: https://www.mail-tester.com/web-s9dk1

**Comment by bengotow** [comment]
Hey! The spam score result links seem to have broken, but my guess is that link and open tracking were enabled on the email. Having tracking links / pixels in the email typically raises the spam score a bit, and having that in combination with an alias (esp one going out through a separate gateway) might be too much. Gonna close this one but let me know if you disable link and open tracking and still see this result!
