### ISSUE TITLE
[Question] Gmail accounts and threading

### ISSUE THREAD

**Issue by kapad** [Foundry376/Mailspring#339]
For Gmail accounts, does Mailspring implement it's own threading or does it piggy back off of Gmail's APIs to thread my emails?

**Comment by bengotow** [comment]
Hey! Sorry for the delay—for Gmail accounts, Mailspring uses Gmail's X-GM-THRID extension and copies Gmail threading exactly. For other accounts, it uses the "references" chain in the message headers to collect messages that belong in the same thread.
