### ISSUE TITLE
Unable to sync to upstream

### ISSUE THREAD

**Issue by Immortalin** [Foundry376/Mailspring#340]
##### What operating system are you using?
Ubuntu Budgie 17.10

##### What version of Mailspring are you using?
1.0.8-5a837
--

**Bug?**
iCloud mail changes (e.g. deletions, moves to different folder etc.) not syncing to upstream, changes remain local only 

##### Do you have any third-party plugins installed? If so, which ones?
N/A | near stock installation

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
(no other accounts added besides icloud mail)

##### Is the issue reproducible with a particular attachment, message, signature, etc?
[mailsync-c365742c.log](https://github.com/Foundry376/Mailspring/files/1471323/mailsync-c365742c.log)

**Comment by chris-hld** [comment]
> 13378 [2017-11-13 18:56:38.640] [main] [info] [local-88bb3e8e-4d9f] -- Succeeded. Changing status to `remote`
> 13378 [2017-11-13 18:56:38.997] [foreground] [info] Idle exited with code 0
> 13378 [2017-11-13 18:56:38.998] [foreground] [info] [local-88bb3e8e-4d9f] Running ChangeFolderTask performRemote:
> 13378 [2017-11-13 18:56:39.268] [foreground] [error] [local-88bb3e8e-4d9f] -- Failed ({"debuginfo":"moveMessages","key":"ErrorCopy","retryable":false,"what":"std::exception"}). Changing status to `complete`

Same pattern here https://github.com/Foundry376/Mailspring/issues/330

**Comment by bengotow** [comment]
Hey thanks for reporting this! @chris-hld are you also using iCloud? I'll fire up an icloud test account and see if I can reproduce this locally.

**Comment by chris-hld** [comment]
This https://github.com/Foundry376/Mailspring/issues/330 is an exchange account (via IMAP).

**Comment by chris-hld** [comment]
This https://github.com/Foundry376/Mailspring/issues/330 is an exchange account (via IMAP).

**Comment by bengotow** [comment]
Hey @chris-hld —I think we've figured this out in #364. Mailspring required the IMAP `MOVE` extension to actually place messages in the trash, archive, etc. and it seems a fair number of providers still don't support that extension. In 1.0.11, we'll fall back to the very old school approach of `COPY, STORE, DELETE` when the MOVE capability isn't available.  It's a bit slower but should ensure that deleting / archiving messages works absolutely everywhere.

Sorry for the hassle—I actually hadn't seen an IMAP server that didn't support the MOVE extension, and the underlying mailcore2 library we use for IMAP was assuming it would always be present. I'm going to continue testing the fix but 1.0.11 should ship in a couple days.

**Comment by bengotow** [comment]
Hey folks - this has shipped in 1.0.11. The app will download the update automatically, but you can get it directly here: https://www.getmailspring.com/download. Gonna go ahead and close this—if you continue to have trouble after the update, let me know and I'll re-open it!
