### ISSUE TITLE
Unknown mailsmtp error 27 (SSL Error) when adding IMAP/SMTP account

### ISSUE THREAD

**Issue by stefvonb** [Foundry376/Mailspring#341]
##### Are there any related issues?
Similar, but not the same

##### What operating system are you using?
Ubuntu 16.04 LTS

##### What version of Mailspring are you using?
1.0.8

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I'm running into trouble setting up a simple IMAP/SMTP account. I managed to do this on Nylas with no issues (and on countless other mail programs). Note that this is on the same computer Nylas was installed on, but I have since removed it.

The IMAP seems to connect easily, but SMTP crashes with a pretty bland error message. This is from the suggested log file:

`----------IMAP----------`
`* OK The Microsoft Exchange IMAP4 service is ready.`
`1 CAPABILITY`
`* CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN UIDPLUS CHILDREN IDLE NAMESPACE LITERAL+`
`1 OK CAPABILITY completed.`
`2 LOGIN svonbudd *********`
`2 OK LOGIN completed.`
`3 CAPABILITY`
`* CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN UIDPLUS CHILDREN IDLE NAMESPACE LITERAL+`
`3 OK CAPABILITY completed.`
`4 NAMESPACE`
`* NAMESPACE (("" "/")) NIL NIL`
`4 OK NAMESPACE completed.`
`5 LIST "" "*"`
`* LIST (\HasNoChildren) "/" Archive`
`* LIST (\HasNoChildren) "/" Calendar`
`* LIST (\HasNoChildren) "/" Contacts`
`* LIST (\HasNoChildren) "/" "Deleted Items"`
`* LIST (\HasNoChildren) "/" "Deleted Messages"`
`* LIST (\HasNoChildren) "/" Drafts`
`* LIST (\Marked \HasNoChildren) "/" INBOX`
`* LIST (\HasNoChildren) "/" Journal`
`* LIST (\HasNoChildren) "/" Junk`
`* LIST (\HasNoChildren) "/" "Junk E-Mail"`
`* LIST (\HasNoChildren) "/" N1-Snoozed`
`* LIST (\HasNoChildren) "/" Notes`
`* LIST (\HasNoChildren) "/" Outbox`
`* LIST (\HasNoChildren) "/" Sent`
`* LIST (\HasNoChildren) "/" "Sent Items"`
`* LIST (\HasNoChildren) "/" "Sent Messages"`
`* LIST (\HasNoChildren) "/" Tasks`
`* LIST (\HasNoChildren) "/" Trash`
`5 OK LIST completed.`

`----------SMTP----------`

`mailsmtp Last Error Code: 27`

`mailsmtp Last Error Location: 5`

I could probably provide more info if I know what the SMTP errors are.

**Comment by RicardoEPRodrigues** [comment]
I have the same issue!

It's still active on `1.0.9`.

**Comment by earandap** [comment]
I got it too on 1.0.10

**Comment by lourencoj** [comment]
Same problem here.

**Comment by bengotow** [comment]
Hey folks! Those errors are a bit cryptic, but map to a look up table here: https://github.com/dinhviethoa/libetpan/blob/master/src/low-level/smtp/mailsmtp_types.h#L75. It looks like 27 is the last one (SSL Error). 

We have really strict SSL and security checking on by default in Mailspring and it doesn't turn it off unless you choose "Allow Insecure SSL" during IMAP/SMTP auth. It could be that your SMTP server has an invalid / self-signed SSL certificate, or the certificate expired or it's signed with a root cert that your machine doesn't trust. We also had some early problems with Mailspring not being able to find your computer's certificate trust chain on some distributions of Linux, so it may be that as well - let me know if you're running Linux!

**Comment by xulongwu4** [comment]
I am running linux and having this problem with 1.0.9.

**Comment by stefvonb** [comment]
Hi @bengotow

Thanks for the link! I am running Linux, using Ubuntu 16.04 LTS

**Comment by RicardoEPRodrigues** [comment]
I also tested this on Windows and it is still happening for me, even with `Allow Insecure SSL`.

**Comment by earandap** [comment]
Hi @bengotow

I am running Linux, using Ubuntu 17.10. I checked  `Allow Insecure SSL` and the error changed.


```
EHLO ed-precision
250-******************************
250-SIZE 52428800
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-AUTH GSSAPI NTLM LOGIN
250-8BITMIME
250-BINARYMIME
250 CHUNKING
STARTTLS
ecision
220 2.0.0 SMTP server ready
4SEHLO ed-precision
250-*******************
250-SIZE 52428800
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH GSSAPI NTLM LOGIN
250-8BITMIME
250-BINARYMIME
250 CHUNKING


SMTP Last Response Code: 250

SMTP Last Response: *********
SIZE 52428800
PIPELINING
DSN
ENHANCEDSTATUSCODES
AUTH GSSAPI NTLM LOGIN
8BITMIME
BINARYMIME
CHUNKING


mailsmtp Last Error Code: 17

mailsmtp Last Error Location: 10
```

**Comment by pablodecm** [comment]
Same problem both for Mac (High Sierra) and Linux (Ubuntu 16.04 LTS) client with 1.0.10, tested with and without `Allow Insecure SSL`.

**Comment by tobgaer** [comment]
Same problem, but only on Linux (Debian). On Windows 10 everything works fine. SMTP-Server is _smtp.strato.de_

**Comment by en4ble** [comment]
I have the same problem on Arch Linux, using client with 1.0.12, tested with and without `Allow insecure SSL`

**Comment by joshjabs** [comment]
Same here on Windows 10. Mail server has a self-signed cert and Mailspring won't let me connect regardless of whether 'Allow Insecure SSL' is checked or not.

**Comment by bburt33** [comment]
Same problem here. macOS 10.13.2. Mailiwise 1.0.12. Tried all ports with and without `Allow insecure SSL`. Same settings are fine in other clients.

**Comment by stefvonb** [comment]
Just to bump this thread a little: I'm getting a bit further on 1.1.0. Now when I use STARTTLS, the connection is made, but it says I am using an incorrect username/password configuration (which I have checked countless times).

The errors are now mailsmtp 10 and 17.

**Comment by en4ble** [comment]
Can confirm, also on 1.1.0.7563b09b. I still have the same errors, incorrect username/password. :(

**Comment by Mildpaul** [comment]
Hi,

First off, awesome email client, love it! I used the old Nylas client until it became so slow it was unbearable. Been using Mailspring now for a while, on Ubuntu-Gnome, and I get the same error 27 when trying to add my work accounts. IMAP works fine, but not SMTP, regardless if I use SSL or not.

Did some testing via Telnet and realized that the SMTP only accepts logins if username and password are sent separately, and not in a single string as I see in the error log that Mailspring does.

Not sure if this is the reason for everybody getting the error, but at least it seems to be for my case. Hope this helps in resolving the issue!

**Comment by Toby91** [comment]
Same here in Mailspring 1.1.2, Ubuntu 17.10

**Comment by brunoaraujocosta** [comment]
HI

Same here.
Ubuntu 16.04 Mailsprong 1.1.2. 
Now that provider uses SSL on port 587.

Does not work 

mailsmtp Last Error Code: 25
or
mailsmtp Last Error Code: 27

**Comment by westr029** [comment]
Same here on mailspring 1.1.2 and 1.1.3 on Ubuntu 16.04.
Provider uses SSL on port 25.

Works just fine on Evolution.

It's a pity that this is still not resolved. Encountered this problem already since a long time (October/November last year - #241 )

**Comment by lSindra** [comment]
Same here, mailspring 1.1.2 and 1.1.4, Ubuntu 16.04.
Evolution works

**Comment by killouis** [comment]
Hello,
in Debian 9, Mailspring 1.1.2 I had the same problem.

Changing "Security" from "SSL / TLS" to "STARTTLS" and activating the "Allow SSL not secure" flag, **the problem has been solved**!

I hope it works for you too!

Greetings

**Comment by en4ble** [comment]
Hey, 
just tried it again. I cannot confirm @killouis statement, I still have the same error with STARTTLS. 
Trying to connect with SSL/TLS to IMAP and STARTTLS to SMTP.
cheers

**Comment by xulongwu4** [comment]
Didn't work for me either.

**Comment by johnnydubrovnik** [comment]
Same problem here, OSX 10.13.3 (17D47), Mailspring v 1.1.4 (1.1.4).

STARTTLS just made it time out.

**Comment by piyushnet** [comment]
Great email client. Having same issue! Please help.

**Comment by burmanh** [comment]
Same issues with v. 1.1.5 on Debian 9 with slightly different error codes but an completely empty log for the Imap alternative, sadly an install of Nylas Mail worked perfectly...

**Comment by npfoss** [comment]
I'm having the same problem (IMAP incoming works, SMTP outgoing doesn't) connecting to an exchange server from Ubuntu 16.04. This seems to be the same issue just older: https://github.com/Foundry376/Mailspring/issues/130

As for the solutions proposed above, neither STARTTLS nor any combination of "Allow insecure SSL" worked for me.

Error c/p below:
> SMTP Last Response Code: 250
> 
> SMTP Last Response: **********
> ENHANCEDSTATUSCODES
> PIPELINING
> 8BITMIME
> SIZE 41943040
> ETRN
> AUTH GSSAPI LOGIN
> DELIVERBY
> HELP
> 
> 
> mailsmtp Last Error Code: 17
> 
> mailsmtp Last Error Location: 10

**Comment by tikondrus** [comment]
I have the same problem (IMAP incoming works, SMTP outgoing doesn't) connecting to an exchange server from Fedora 27. As for the solutions proposed above, noone combination of options  work for me.
----------SMTP----------


mailsmtp Last Error Code: 27

mailsmtp Last Error Location: 5

**Comment by Mildpaul** [comment]
Been using Mailspring now for a while, on Ubuntu-Gnome, and I get the same error 27 when trying to add my work accounts. IMAP works fine, but not SMTP, regardless if I use SSL with or without "Allow insecure SSL".

Did some testing via Telnet and realized that the SMTP only accepts logins if username and password are sent separately, and not in a single string as I see in the error log that Mailspring does.

Not sure if this is the reason for everybody getting the error, but at least it seems to be for my case.

**Comment by stanleykylee** [comment]
@Mildpaul were you able to get it working after your discovery? Or does this basically mean it won't work until it's fixed?

**Comment by krisgermann** [comment]
Same here, any update from the MailSpring team?

Google works of course, as does my cPanel mail accounts; however, Zentyal does not.

IMAP: 143, STARTLS (Allow insecure SSL) - works
SMTP: 465, SSL / TLS (Allow insecure SSL) - ERROR:

```
----------SMTP----------
220 ucs.portalnetworks.ca ESMTP
EHLO Kriss-iMac.local
250-my.mailserver.address
250-PIPELINING
250-SIZE
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 SMTPUTF8
STARTTLS
220 2.0.0 Ready to start TLS
EHLO Kriss-iMac.local
250-ucs.portalnetworks.ca
250-PIPELINING
250-SIZE
250-ETRN
250-AUTH GSSAPI PLAIN
250-AUTH=GSSAPI PLAIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 SMTPUTF8

SMTP Last Response Code: 250

SMTP Last Response: my.mailserver.address
PIPELINING
SIZE
ETRN
AUTH GSSAPI PLAIN
AUTH=GSSAPI PLAIN
ENHANCEDSTATUSCODES
8BITMIME
DSN
SMTPUTF8

mailsmtp Last Error Code: 17
mailsmtp Last Error Location: 10
```

I have also tried port 25, 465, and 587 with a combination of SSL/TLS, None, and STARTLS - Using SSL / TLS, port 587 with Allow insecure SSL doesn't work, but, it provides a different error code and takes the longest to fail:

```
----------SMTP----------
mailsmtp Last Error Code: 27
mailsmtp Last Error Location: 5
```

**Comment by RicardoEPRodrigues** [comment]
@bengotow can you guys at least talk about this issue?

**Comment by philippeller** [comment]
same issue here - this is preventing me from switching to Mailspring, as I need all my emails in one place

**Comment by RicardoEPRodrigues** [comment]
No developer/owner comment since December 11th...

**Comment by hyviquel** [comment]
anyone knows if this is a bug inherited from mailcore that should be reported there? or is it specific to mailsync?

**Comment by hyviquel** [comment]
FYI, I was able to add my account using the SMTP server of my Gmail account. You can even send email from the other email by adding the SMTP of your other account in Gmail setting and using alias in mailspring. It still a workaround but will work for me until this bug get fixed.

**Comment by oz123** [comment]
I can confirm this behaviour too.

**Comment by tonypartridge** [comment]
Anyone?? I've almost moved over completely but also have this issue :-(. Going to have to cancel my subscription and go back to SparkMailApp if it can't be fixed.

**Comment by Mildpaul** [comment]
@tonypartridge I feel you, I actually cancelled my subscription a while back and went back to Thunderbird over this issue. But now that the company that I work for has migrated to Google Suite I've started using Mailspring again. Thunderbird is just too slow and, dare I say, ugly. But no subscription this time.

And as @RicardoEPRodrigues pointed out a while back, there hasn't been any developer comment in this thread since December. But there has been several new releases since then, so I think it is safe to say that this issue won't be fixed. It's just not a priority, to few that are affected I guess.

**Comment by RicardoEPRodrigues** [comment]
@Mildpaul I have started moving away from Mailspring. I had a subscription for Nylas N1 and got fooled, thank god I didn't subscribe to Mailspring.

I just hope they fix this for other users, but apparently it's not going to happen. :cry:

**Comment by oxmynx** [comment]
Same happened to me some months back. I was hoping that Mailspring will fix it over time and now I gave it another try. Same behavior. My iCloud and several other IMAP accounts work but one based on Exchange server doesn't. I need to be able to connect my company account otherwise, not worth subscribing. Please fix ASAP.

**Comment by Orjanp** [comment]
Was going to test Mailspring, but having the same problem with the Exchange server. To bad they don't fix this issue.

**Comment by bengotow** [comment]
Hey folks—thanks for all the detailed comments and follow-up here. I spent some time this weekend tracking this down and was able to reproduce it. I configured a "Mail-in-a-box" (http://mailinabox.email) server (which is Dovecot + Postfix) and didn't have any trouble signing in and sending mail from Mailspring. Then I downloaded and configured a virtual machine running Zentyal (http://www.zentyal.org/), another out of the box solution that uses Dovecot and Postfix.

It turns out Zentyal was the perfect test case - it supports a small set of SMTP AUTH methods out of the box, just `GSSAPI` and `PLAIN`. Mailspring uses libmailcore2's auto configuration of SMTP authentication (https://github.com/MailCore/mailcore2/blob/master/src/core/smtp/MCSMTPSession.cpp#L487) and the app always prefers GSSAPI to PLAIN when it's present. (The thinking is it's more secure, though with STARTTLS / SSL it doesn't really matter.) However, GSSAPI / Kerberos rely on system configuration, take a domain/realm, etc. Mailspring doesn't yet support GSSAPI (#103) and it seems like libmailcore2's implementation may be entirely broken. (There's even a comment in the GSSAPI case that says `needs to be tested` https://github.com/MailCore/mailcore2/blob/master/src/core/smtp/MCSMTPSession.cpp#L556).

Disabling the GSSAPI / Kerberos authentication methods and allowing this code to fall through to the PLAIN option fixes the problem and I'm able to connect / send mail through Zentyal. I think that this took a long time to find because most large mail providers support CRAM_MD5 and/or DIGEST_MD5 and often don't support GSSAPI (since it's primarily for schools, enterprises, etc. with SSO).

I've also extended the logging in this code so that it prints the auth method it chose to use, which I think should make finding this sort of problem trivial in the future. And hopefully at some point soon I can build / fix support for GSSAPI as well.

I'm wrapping up testing a new release (with Touch Bar support!) and will ship the patch fo this in the next few days. Stay tuned! Thanks again to everyone who provided context and details.

**Comment by tonypartridge** [comment]
Awesome!! Look forward to trying this out.
  

  
  

  
  
>

**Comment by hyviquel** [comment]
Solved my problem too... Thanks =)

**Comment by tonypartridge** [comment]
Can we mark this as closed now?

**Comment by stanleykylee** [comment]
It’s fixed for me too.

**Comment by stefvonb** [comment]
Closing, thanks for finally fixing it!

**Comment by mobilegenome** [comment]
It seems for my mail provider it still doesn't work. I have the latest 1.6.1 version of Mailspring running on Linux Mint 17.3.  These are the recommended SMTP settings, which work well in other mail clients: https://manual.uberspace.de/mail-access.html

The log file says: 
----------SMTP----------
220 <host> ESMTP
EHLO <workstation>
250-<host>
250-PIPELINING
250-8BITMIME
250-AUTH LOGIN PLAIN
250-STARTTLS
250 X-NOTHING
STARTTLS
220 Proceed.
EHLO <workstation>
250-<host>
250-PIPELINING
250-8BITMIME
250 AUTH LOGIN PLAIN

SMTP Last Response Code: 250

SMTP Last Response: <host>
PIPELINING
8BITMIME
AUTH LOGIN PLAIN


mailsmtp Last Error Code: MAILSMTP_ERROR_AUTH_LOGIN

mailsmtp Last Error Location: 10

mailsmtp Last Auth Type: 2

**Comment by D4rk4** [comment]
Reproducible with mailspring 1.9.1

**Comment by ugurkanates** [comment]
Still happening sadly

SASL_PATH: 

mailsmtp Last Error Code: 27
mailsmtp Last Error Explanation: MAILSMTP_ERROR_SSL
mailsmtp Last Error Location: 5
mailsmtp Last Auth Type: 0

**Comment by ammaraziz** [comment]
I'm also experiencing this issue. Linux Mint 20, Mail Spring v1.9.1 with Microsoft Exchange Server 2013 or 2010 (unsure which, sorry). IMAP successfully authenticates but SMPT fails with this ending error:

    250-SIZE 37748736
    250-PIPELINING
    250-DSN
    250-ENHANCEDSTATUSCODES
    250-STARTTLS
    250-X-ANONYMOUSTLS
    250-AUTH NTLM
    250-X-EXPS GSSAPI NTLM
    250-8BITMIME
    250-BINARYMIME
    250-CHUNKING
    250 XRDST
    start TLS
    STARTTLS
    220 2.0.0 SMTP server ready
    done
    init after starttls
    EHLO XXXX
    250-XXXX Hello [172.28.201.116]
    250-SIZE 37748736
    250-PIPELINING
    250-DSN
    250-ENHANCEDSTATUSCODES
    250-AUTH NTLM LOGIN
    250-X-EXPS GSSAPI NTLM
    250-8BITMIME
    250-BINARYMIME
    250-CHUNKING
    250 XRDST
    AUTH LOGIN
    334 XXXX
    YXppemE=
    334 XXXX
    XXXX==
    535 5.7.3 Authentication unsuccessful
    
    
    SASL_PATH: XXXX
    
    SMTP Last Response Code: 535
    SMTP Last Response: 5.7.3 Authentication unsuccessful
    
    
    mailsmtp Last Error Code: 17
    mailsmtp Last Error Explanation: MAILSMTP_ERROR_AUTH_LOGIN
    mailsmtp Last Error Location: 10
    mailsmtp Last Auth Type: 16

**Comment by ammaraziz** [comment]
Hi Tony,

My apologies, I thought my server had SMTP enabled but apparently it does not have SMTP. Please ignore my request above.

**Comment by MTN-Studio** [comment]
I'm also now experiencing this issue after updating a password on the email account I use. IMAP connects no problem but regardless of what port I try, it just doesn't connect.

`mailsmtp Last Error Code: 27
mailsmtp Last Error Explanation: MAILSMTP_ERROR_SSL
mailsmtp Last Error Location: 5
mailsmtp Last Auth Type: 0`

**Comment by debarshibanerjee** [comment]
I can confirm the same issue:

`mailsmtp Last Error Code: 25
mailsmtp Last Error Explanation: MAILSMTP_ERROR_CONNECTION_REFUSED
mailsmtp Last Error Location: 1
mailsmtp Last Auth Type: 0
`

**Comment by ChristianVaughn** [comment]
I am having the same issue. Connection error trying to connect to the server on the Ubuntu version from the snap store. mailsmtp Last Error Code: 25
mailsmtp Last Error Explanation: MAILSMTP_ERROR_CONNECTION_REFUSED
mailsmtp Last Error Location: 5
mailsmtp Last Auth Type: 0

**Comment by Halfart** [comment]
SASL_PATH: /snap/mailspring/519/usr/share/mailspring/resources/app.asar.unpacked

mailsmtp Last Error Code: 27
mailsmtp Last Error Explanation: MAILSMTP_ERROR_SSL
mailsmtp Last Error Location: 5
mailsmtp Last Auth Type: 0

**Comment by zeph** [comment]
same issue here when attempting to use the Free Software Foundation Europe - Fellowship SMTP server
 - https://wiki.fsfe.org/action/login/TechDocs/SMTP

I believe it is related to the enforcement of TLS on server side as mentioned in their wiki... switching on `Mailspring` to use `SSL / TLS` with `Allow insecure SSL` doesn't help... here is the log of the attempt... 
```
----------SMTP----------


SASL_PATH: 

mailsmtp Last Error Code: 27
mailsmtp Last Error Explanation: MAILSMTP_ERROR_SSL
mailsmtp Last Error Location: 5
mailsmtp Last Auth Type: 0
```

otherwise... here is the error with a plain `STARTTLS` without the `insecure`
```
----------SMTP----------
connect mail.fsfe.org 587
220 mail1.fsfe.org ESMTP Postfix (Debian/GNU)
init
EHLO fluffy.local
250-mail1.fsfe.org
250-PIPELINING
250-SIZE 20971520
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING
start TLS
STARTTLS
220 2.0.0 Ready to start TLS
QUIT


SASL_PATH: 

SMTP Last Response Code: 220
SMTP Last Response: 2.0.0 Ready to start TLS


mailsmtp Last Error Code: 27
mailsmtp Last Error Explanation: MAILSMTP_ERROR_SSL
mailsmtp Last Error Location: 3
mailsmtp Last Auth Type: 0
```

Evolution handles such setup without any problem with such configuration 

<img width="718" alt="evolution" src="https://github.com/Foundry376/Mailspring/assets/209808/382b6e5a-47b9-4dce-b8f0-ba563448bdbd">

but I have to run a dedicated VM just to SEND my emails (to not stumble on SPF controls)

... and as u can see below, the certificate is in order:

```
% openssl s_client -starttls smtp -crlf -connect mail.fsfe.org:587                                 
Connecting to 217.69.89.151
CONNECTED(00000006)
depth=2 C=US, O=Internet Security Research Group, CN=ISRG Root X1
verify return:1
depth=1 C=US, O=Let's Encrypt, CN=R3
verify return:1
depth=0 CN=mail1.fsfe.org
verify return:1
---
Certificate chain
 0 s:CN=mail1.fsfe.org
   i:C=US, O=Let's Encrypt, CN=R3
   a:PKEY: id-ecPublicKey, 384 (bit); sigalg: RSA-SHA256
   v:NotBefore: Apr  4 08:01:27 2024 GMT; NotAfter: Jul  3 08:01:26 2024 GMT
 1 s:C=US, O=Let's Encrypt, CN=R3
   i:C=US, O=Internet Security Research Group, CN=ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
[...]
```

this is a legit BUG but on Mailspring... why is it closed?

**Comment by zeph** [comment]
ah @bengotow I saw now ur comment above... sadly this is still happening in `Version 1.13.3 (1.13.3)` on the conditions above

**Comment by zeph** [comment]
p.s. anyhow, if I can contribute seems I need to focus my effort on https://github.com/MailCore/mailcore2 , right @bengotow ?
