### ISSUE TITLE
Signature New Line Issue

### ISSUE THREAD

**Issue by colinking** [Foundry376/Mailspring#343]
##### Are there any related issues?
No

##### What operating system are you using?
macOS 10.13

##### What version of Mailspring are you using?
1.0.8

--

**Bug**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Tested with gmail, but don't believe so.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Using the default signature ("Sent from Mailspring, the best free email app for work") place the cursor on the line above the signature and press "Return". A new line will appear, but the cursor will hop to the previous line.

Can be annoying when your signature is your name, and you intend to add a closing later on.

**Comment by bengotow** [comment]
Hey! This should be fixed in the new composer.
