### ISSUE TITLE
"The Bat!" Mail client does not render replies from Mailspring correctly

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#346]
Hello

I have a friend who uses the email software "[The Bat!](https://www.ritlabs.com/en/products/thebat/)".

1/ I send a first message from Mailspring.
in TheBat! , the display is correct on the recipient's computer. The friend answers me.
2/ I answer him. In Mailspring no display problem.
3/ The friend or the recipient with TheBat! receive my email with a bad display.
see the screenshot

##### What operating system are you using?
Windows 10 x64

##### What version of Mailspring are you using?
1.0.8

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no 

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no

##### Is the issue reproducible with a particular attachment, message, signature, etc?
there is a screenshot
yes, on the recipient's computer when I answered him (only when I answer)
the first message sent from Mailspring is displayed correctly

![int_1](https://user-images.githubusercontent.com/31793920/32898131-9b65bf26-cae7-11e7-9e29-a56790bc020d.png)

**Comment by bengotow** [comment]
Hey thanks for reporting this–if anyone is available to dig in to this a bit more, I'd really appreciate it. It looks like Mailspring is sending (maybe malformed?) HTML when including quoted text, and "The Bat" has a very sensitive parser that is falling back to displaying the HTML as plain-text.

**Comment by franco27** [comment]
Additional information: When the recipient or my friend, click on "Reply" message with the wrong preview of the message preview;
When the "Reply" window is opened, the same message is displayed correctly.
![int_answer](https://user-images.githubusercontent.com/31793920/33021469-427550fc-ce02-11e7-9895-d41bb1506360.png)

**Comment by franco27** [comment]
The new version 1.0.9 did not solve this problem
![int_1](https://user-images.githubusercontent.com/31793920/33554419-ed54a50e-d8fc-11e7-8f06-a6dd1f9ef74d.png)

**Comment by franco27** [comment]
this problem has deteriorated or worsened ... see the issue #516

**Comment by franco27** [comment]
I confirm this problem is solved with the 1.1.0.
TheBat! user now correctly sees my messages sent with Mailspring, whether with a first message or when I reply.
