### ISSUE TITLE
[Bug] Send later mails stay in the drafts folder past send time

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#348]
##### Are there any related issues?

...

##### What operating system are you using?
10.12.6

##### What version of Mailspring are you using?
1.0.8

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Possibly Gmail but I doubt it

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Steps to reproduce:
- Compose an email
- Send later for tomorrow morning
- Close your laptop and go to bed
- Start working in the morning w/ Mailspring open - at least some of the time, the email simply never goes out. It just stays in my drafts folder saying "sending in a few seconds". The only way to get it to send is to re-open the draft and send immediately

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
v
