### ISSUE TITLE
Why do you make creation of a mailspring ID mandatory?

### ISSUE THREAD

**Issue by rightaway** [Foundry376/Mailspring#349]
Creating a mailspring ID is mandatory? If I don't care about "read receipts and shared templates" (not valuable features in my opinion) as your ID creation page says, why can't I use the app without that? I'm not interested in using mailspring at all if an ID is forced on us when no features requiring an ID are needed.

**Comment by palefire19** [comment]
See #33

**Comment by bengotow** [comment]
Closing as dup—thanks!

**Comment by kwmiebach** [comment]
### Looking for the skip button?

If you come here from google, looking for the "skip" button on the "create a mailspring id" page:

There is no skip button. But there is always:
 
    # for the debian familiy of linux os
    sudo snap remove mailspring
    sudo apt install thunderbird # going back to freedom

**Comment by buczoprazy** [comment]
> ### Looking for the skip button?
> 
> If you come here from google, looking for the "skip" button on the "create a mailspring id" page:
> 
> There is no skip button. But there is always:
> 
> ```
> # for the debian familiy of linux os
> sudo snap remove mailspring
> sudo apt install thunderbird # going back to freedom
> ```

Thank you, you saved my time. :) Will find proper mail software now.
