### ISSUE TITLE
[Windows] Significant performance degradation, especially when waking from sleep

### ISSUE THREAD

**Issue by billytcl** [Foundry376/Mailspring#35]
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.01-ba1d6734

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail?

##### Is the issue reproducible with a particular attachment, message, signature, etc?

System stalls for 10+ minutes at times, especially when waking from sleep. Computer is virtually unusable during this time.

Task manager shows near 100% disk usage for this amount of time for Mailspring/mailsync. I have an SSD, so it's unusual for the disk to be active for this long. 

Resource monitor in Windows shows "System" and mailspring constantly reading from "edgehill" db file.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - that's pretty crazy CPU usage. Could you try opening `C:/Users/<you>/AppData/Roaming/Mailspring/mailsync-****.log` and post the last few dozen lines? Should help narrow this down.

**Comment by billytcl** [comment]
My computer just woke from sleep, and it started freezing almost immediately:

13132 [2017-10-05 17:29:33.025] [metadata] [info] Metadata delta stream closed.
13132 [2017-10-05 17:29:33.162] [foreground] [info] Idle exited with code 0
13132 [2017-10-05 17:29:33.211] [foreground] [info] Fetching XOAuth2 access token for 95cb0f9c
13132 [2017-10-05 17:29:33.240] [metadata] [info] Metadata delta stream starting...
13132 [2017-10-05 17:29:37.956] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/All Mail: highestmodseq changed, requesting changes...
13132 [2017-10-05 17:30:02.745] [foreground] [info] Idling on folder [Gmail]/All Mail
13132 [2017-10-05 17:30:22.608] [background] [info] Syncing folder list...
13132 [2017-10-05 17:30:23.482] [background] [info] syncFolderUIDRange - ([Gmail]/All Mail, UIDs: 1 - 0, Heavy: false)
13132 [2017-10-05 17:33:55.364] [foreground] [info] Idle exited with code 0
13132 [2017-10-05 17:33:55.712] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/All Mail: highestmodseq changed, requesting changes...
13132 [2017-10-05 17:33:56.460] [foreground] [info] ðŸ”¸ Updating message 422839=422839 with subject: Re: [Foundry376/Mailspring] Significant performance degradation, especially when waking from sleep (#35)
13132 [2017-10-05 17:33:56.902] [foreground] [info] ðŸ”¸ Updating message 422840=422840 with subject: $40 off Fire TV and Echo Dot. Ends Saturday.
13132 [2017-10-05 17:33:56.920] [foreground] [info] ðŸ”¸ Updating message 422841=422841 with subject: 50-70% off all clearance ends. at. midnight!
13132 [2017-10-05 17:33:56.925] [foreground] [info] ðŸ”¸ Updating message 422842=422842 with subject: "Amazing," "Outstanding," "Nothing is Better" | Meet Our BRAVIA OLED TV
13132 [2017-10-05 17:37:22.949] [main] [info] Marking all folders as `busy`
13132 [2017-10-05 17:37:55.553] [background] [error] syncFolderUIDRange - Fetching full headers for 1
13132 [2017-10-05 17:37:56.128] [background] [info] ðŸ”¸ Updating message 422839=422839 with subject: Re: [Foundry376/Mailspring] Significant performance degradation, especially when waking from sleep (#35)
13132 [2017-10-05 17:38:27.969] [foreground] [info] Idling on folder [Gmail]/All Mail
13132 [2017-10-05 17:39:58.746] [background] [info] syncFolderUIDRange - ([Gmail]/Trash, UIDs: 1 - 0, Heavy: false)
13132 [2017-10-05 17:40:12.428] [background] [info] syncFolderUIDRange - ([Gmail]/Spam, UIDs: 1 - 0, Heavy: false)
13132 [2017-10-05 17:40:26.237] [background] [info] Sync loop deleting unlinked messages with phase 2.
13132 [2017-10-05 17:40:43.662] [background] [info] Sync loop complete.
13132 [2017-10-05 17:42:43.954] [background] [info] Syncing folder list...
13132 [2017-10-05 17:42:44.562] [background] [info] syncFolderUIDRange - ([Gmail]/All Mail, UIDs: 1 - 0, Heavy: false)
13132 [2017-10-05 17:44:33.913] [metadata] [info] Metadata delta stream closed.
13132 [2017-10-05 17:44:36.560] [metadata] [info] Metadata delta stream starting...

At 17:47, I had to close Mailspring just to be able to open up a browser to paste this. Not quite sure what is happening since I only had a couple of email messages come in since then.

**Comment by billytcl** [comment]
Any updates on this bug? Would like to know if there's any way to track this down. I noticed that there's another bug in the github saying that all the memory is being used. I'm having my disk usage issue alongside high memory usage too.

**Comment by HotToTroc** [comment]
Same issue.

**Comment by bengotow** [comment]
Hey! We've finally tracked this down in #388 and it'll be fixed in the next release of the app.

**Comment by bengotow** [comment]
Hey! The fix for this has shipped in `1.0.10` - thanks for all the reports and details. You can download the update by saying "Check for Updates..." within the app, or directly from https://getmailspring.com/download. Thanks!
