### ISSUE TITLE
 SMTP error when OpenVPN [Proxy] is connected

### ISSUE THREAD

**Issue by Cediddi** [Foundry376/Mailspring#352]
This interesting issue happened when I was connected over OpenVPN to my personal server. I tried to send an email and got an error a minute or so later, stating that Mailspring couldn't connect to the SMTP server. Interestingly I had no such issue with Thunderbird or Geary and I can still receive emails while on OpenVPN connection. Meanwhile I checked the mailsync logs and found out two lines that are related to the issue. The issue gone away when I disconnected OpenVPN.

```
12059 [2017-11-19 12:52:03.807] [foreground] [info] -X An SMTP error occurred: ErrorConnection
12059 [2017-11-19 12:52:03.833] [foreground] [error] [local-0aabf511-9155] -- Failed ({"debuginfo":"ErrorConnection","key":"send-failed","retryable":false,"what":"std::exception"}). Changing status to `complete`
```

![selection_220](https://user-images.githubusercontent.com/2720608/32989651-62405300-cd2b-11e7-8ca3-eb8fc710654e.jpg)

![selection_221](https://user-images.githubusercontent.com/2720608/32989650-6207079e-cd2b-11e7-92ca-06fe7db374af.jpg)

##### Are there any related issues?

No

##### What operating system are you using?
Linux Mint 17.3 (Ubuntu 14.04.5)

##### What version of Mailspring are you using?
1.0.8.5a837d0e

**Bug?** Yes
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I encountered on Gmail. I don't use others.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes I tried again and It did indeed happened again.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—Mailspring doesn't support proxies yet (#235), and it's possible that OpenVPN hooks itself into your system by altering the global proxy settings on your machine. (I know it does on macOS)

**Comment by Cediddi** [comment]
Yes, same applies here on linux land. Interesting thing is imap works but
not smtp.

Thank you, I'll br watching the other issue.

On Nov 29, 2017 01:39, "Ben Gotow" <notifications@github.com> wrote:

Hey! Thanks for reporting this—Mailspring doesn't support proxies yet (#235
<https://github.com/Foundry376/Mailspring/issues/235>), and it's possible
that OpenVPN hooks itself into your system by altering the global proxy
settings on your machine. (I know it does on macOS)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Foundry376/Mailspring/issues/352#issuecomment-347688168>,
or mute the thread

**Comment by bengotow** [comment]
Merging in to #235
