### ISSUE TITLE
Add support for titles to name checker

### ISSUE THREAD

**Issue by colinking** [Foundry376/Mailspring#354]
##### Are there any related issues?
Don't believe so.

##### What operating system are you using?
macOS 10.13.1

##### What version of Mailspring are you using?
1.0.8

--

**Feature Request**
The name checker is quite handy, though it doesn't handle titles very well. It'd be great if a handful of titles were hardcoded so that it would instead verify that the last name is correct (Mr., Mrs., Ms., Dr., etc.).

For example:
![image](https://user-images.githubusercontent.com/2907397/33025532-44512610-cddc-11e7-8301-384fa17af2c3.png)

Emailing Dr. Foster here should verify that the last name ("Foster") is correct.

**Comment by bengotow** [comment]
Hey! It looks like this was fixed a while back and I forgot to close this issue. The app should recognize a much wider range of titles and abbreviations now. Enjoy!
