### ISSUE TITLE
[Bug] Email gets sent with empty text (unless draft is already updated)

### ISSUE THREAD

**Issue by jrpereira** [Foundry376/Mailspring#356]
Hi,

**Quick problem description:**
Typing a short email and then quickly sending it results in an empty message being sent. Waiting for the Draft to update before sending, however, works fine. In other words, what gets sent is what's in the draft, not what's on the edit window.

**Context**
Mailspring 1.0.8-5a837d0e, Linux Ubuntu 17.10.
Tested with personal GMail and also G Suite account. 

**Related issues:**
I found a similar issue on Nylas https://github.com/nylas/nylas-mail/issues/2272, which points to a Mailspring patch here https://github.com/Foundry376/Mailspring/commit/f15ba78cc53bbf7f66c4f279ea67a6157272dead. However, in 1.0.8 this behaviour still occurs, so it seems like this doesn't effectively fix the issue (or, somehow it's not included in 1.0.8).

**Steps to replicate**
I checked whether it's related to syncing to Draft, and that does appear to be the case.
- Open the Drafts folder (so you can better see the behavior) 
- CTRL+N Create a new message
- Type something and immediately press CTRL+ENTER to send

The message will often be sent empty (it shows up empty on the server Sent folder). However, if you wait a few seconds (until the Draft is updated), the message will be sent ok,

**Comment by bengotow** [comment]
Will check this out and see if I can reproduce—this definitely sounds like something we need to track down and fix.

**Comment by bengotow** [comment]
Hey! This should be fixed in 1.0.9, which re-orders the sending code a bit to ensure drafts are /always/ saved, even if you draft and send before it has a chance to write to the database.

**Comment by jrpereira** [comment]
I can confirm this is fixed in 1.0.9. 

Thank you!
