### ISSUE TITLE
[BUG] Flickering when viewing inbox?

### ISSUE THREAD

**Issue by deronsizemore** [Foundry376/Mailspring#359]
when I'm viewing my inbox, every minute or so I'll see a very slight flicker of some sort. It doesn't seem to affect anything; it just flickers.

**Comment by wezm** [comment]
I'm seeing a similar flicker, in the toolbar captured here (first one happens around 10 secs in):

![mailspring toolbar flicker](https://user-images.githubusercontent.com/21787/34593891-cc420274-f221-11e7-89ea-9f6fb870281a.gif)

**OS:** Arch Linux
**Desktop:** GNOME 3 on Wayland
**Mailsmith:** 1.0.12-cf081332

**Comment by bengotow** [comment]
Hey folks—so I think this was actually the app encountering an exception and re-rendering the UI. This should be fixed in 1.1.3 because we're using a new version of React that handles this better. Thanks!

**Comment by joewilliams** [comment]
I am experiencing this issue on `1.14-22d9` on Ubuntu 16.04. Let me know if there is more info you need from me. Thanks!

**Comment by konradreiche** [comment]
The installation via the snap store flickers for me, the one installed with the `.deb` package doesn't. Even though it's the same version? :thinking:

**Comment by dhunt84971** [comment]
Just installed the deb on Ubuntu 16.04 and showing version 1.5.5-b7939d38 in the help.  Also seeing an occasional flicker.  I am also using DavMail to connect to an old OWA Exchange Server, but other than that I am not doing anything out of the ordinary.
