### ISSUE TITLE
Mail spring goes into infinite loop of trying to resetablish connections to mail servers

### ISSUE THREAD

**Issue by thertz** [Foundry376/Mailspring#365]
I Just installed mailspring on my new debian 9. After setting up 3 accounts (2 gmail and one imap) successfully mailspring keeps reporting that it needs to reauthenticate, or has problems connecting to servers (all 3). On many occasions it enters an infinite loop trying to resolve issues with the accounts, and the only way to stop it is to kill the process externally (program becomes non-responsive).

Overall, looks and feels great, but this bug renders the app completely non-useful.
##### Are there any related issues?

...

##### What operating system are you using?
...debian 9

##### What version of Mailspring are you using?
...
1.08-5a837
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
none
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
gmail and imap.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! When you installed Mailspring, did it display a dialog complaining about "password management"? It sounds like the app may not be able to store the passwords for your accounts correctly.

We haven't been testing on Debian 9—could anyone else comment on whether they're having this problem on Debian 9 as well? It might be a distro-specific problem.

Ben
