### ISSUE TITLE
Missing Standard Themes

### ISSUE THREAD

**Issue by jaydub200** [Foundry376/Mailspring#369]
##### Are there any related issues?

Not that I can see

##### What operating system are you using?
macOS 10.13.1 (17B48)

##### What version of Mailspring are you using?
1.08

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Only use Gmail, but can't see why it would be email specific

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Your web site documentation at
https://foundry376.zendesk.com/hc/en-us/articles/115001875831-Changing-the-Theme
 states that there are 8 standard themes available, however there are only six available within the app.  Ido and Material are not available.

![screen shot 2017-11-27 at 14 37 55](https://user-images.githubusercontent.com/33849107/33271963-a91c0d22-d380-11e7-9a38-ab32a38ba12b.png)

**Comment by Richyread** [comment]
Adding to the above -> it's actually more than two (2):

![image](https://user-images.githubusercontent.com/7470850/33279118-621ec512-d395-11e7-9d73-48fac93c34ae.png)

Not in current release:
[Legacy]
[Level Up]
[Ido]
[Material]

Different from current release:
[Dark] - Currently white/green/black but on website shows grey/blue/black

Documentation needs updating for deprecated themes perhaps?

**Comment by bengotow** [comment]
Hey thanks for the feedback—I've updated  the docs to show the most recent screenshot. I'm actually not sure where those others came from.

**Comment by opes** [comment]
Note that the [homepage](https://getmailspring.com/) also shows screenshots of the interface advertising themes that aren't included.
