### ISSUE TITLE
Removing Hallmarks from Nylas Mail

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#37]
In a lot of the images and pictures, the titles are shown as Nylas N1.  Possibly change this to the Mailspring.

Also, I would for their to be a new logo rather than the rather yucky looking cyan & white Nylas logo. (which also looks like Apple Mail on iOS). I was thinking maybe use orange with a secondary colour (even if it has a similar style), just to differentiate between the clients.

**Comment by bengotow** [comment]
Hey @Modelmat! Could you point me to some of the Nylas N1 references? We've been trying to get them cleaned up. I think there are a few in Preferences on Linux still...

Definitely working on a new icon - stay tuned!

**Comment by Modelmat** [comment]
http://getmailspring.com/static/img/hero_graphic_win32@2x.png has an email `@nylas.com` (same https://github.com/Foundry376/Mailspring/raw/master/screenshots/hero_graphic_mac%402x.png)
http://getmailspring.com/static/img/great-themes.jpg the second one has `Nylas N1` in it.

I believe there are more, but I can't find them anymore.

**Comment by Modelmat** [comment]
Found some more by searching for images;
[here](https://github.com/Foundry376/Mailspring/blob/master/app/internal_packages/ui-taiga/preview.jpg), [here](https://github.com/Foundry376/Mailspring/blob/master/app/internal_packages/ui-less-is-more/images/default.jpg)

**Comment by bengotow** [comment]
Hey thanks! As long as it's just screenshots I think that's OK—we'll be updating those on a rolling basis as we change the UI more. Thanks!
