### ISSUE TITLE
Window get resized when we click an item from 'View Activity' list

### ISSUE THREAD

**Issue by stenalpjolly** [Foundry376/Mailspring#372]
##### What operating system are you using?
Windows 10 Build 17035

##### What version of Mailspring are you using?
1.0.8-5a837d0e

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

**Comment by stenalpjolly** [comment]
Same thing happens when we click on the Windows notification

**Comment by bengotow** [comment]
Hey folks! It's been a few years and there haven't been any more reports of this issue so I'm going to close this as probably-fixed. Feel free to bump or create a new issue referencing this one if you encounter this again!
