### ISSUE TITLE
Set more restrictive permission on .config/Mailspring

### ISSUE THREAD

**Issue by l2dy** [Foundry376/Mailspring#375]
On Ubuntu, by default the `$HOME/.config/Mailspring` directory has 755 permission, so other users can read my email attachments, edgehill.db and some other files in this directory.

##### Are there any related issues?
No.

##### What operating system are you using?
Ubuntu 16.04

##### What version of Mailspring are you using?
mailspring-1.0.8-amd64.deb

--

**Bug**
##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

--

See also nylas-mail-lives/nylas-mail#181.

**Comment by bengotow** [comment]
Hey! If anyone wants  to take a look at this one, it'd be a great starter issue. The config directory is set up here: https://github.com/Foundry376/Mailspring/blob/master/app/src/browser/config-persistence-manager.es6#L25. (We copy in a template version of the directory). After the copySync we probably need to set the folder permissions. I'm actually surprised that all of `$HOME/.config` isn't scoped to the user like `~/Library` is on macOS.

**Comment by agurz** [comment]
Hey guys! 600 would be ok or it's too restrictive? I think we don't need execution permission, right?

<img width="284" alt="screen shot 2017-11-30 at 11 31 44 am" src="https://user-images.githubusercontent.com/13837769/33435896-2904086c-d5c2-11e7-8aae-8343f947bda6.png">

**Comment by l2dy** [comment]
@agurz usually 700, the execution bit works differently on directories:
>For directories, allow ... to search in the directory.

**Comment by oserban** [comment]
I'd say 700 for folders and 600 for files
