### ISSUE TITLE
Three copies of an email sent when sending undo is enabled

### ISSUE THREAD

**Issue by MattKevan** [Foundry376/Mailspring#377]
##### What operating system are you using?
10.13.2 Beta (17C60c)

##### What version of Mailspring are you using?
1.0.8 (1.0.8)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Don't think so. 

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Don't think so

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes, this happens every time. When message send undo is set to 5 seconds (I haven't tried any other time option), three copies of an email are sent. This does not happen when undo is disabled.

<img width="245" alt="screen shot 2017-11-29 at 10 21 10" src="https://user-images.githubusercontent.com/1121942/33370532-b4f95242-d4ef-11e7-9682-e30c29021f9c.png">

The send count is set to 3 in the sidebar, and the send notification sound is played 3 times. And 3 messages are sent...

<img width="423" alt="screen shot 2017-11-29 at 10 21 29" src="https://user-images.githubusercontent.com/1121942/33370518-a5fde366-d4ef-11e7-8f3e-864d1e52ca47.png">

--

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—this happened when Mailspring had other windows open beside the main window, and is fixed in the release that just shipped today (1.0.9). Sorry for the hassle–this is a nasty bug indeed.
