### ISSUE TITLE
Triggering the spellcheck seems to prevent inserting a hyperlink

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#378]
##### Are there any related issues?

Probably #278

##### What operating system are you using?
MacOS 10.13.1

##### What version of Mailspring are you using?
1.0.8

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
This happens in the compose window, so no

##### Is the issue reproducible with a particular attachment, message, signature, etc?

- Open a new compose window
- Type something that will trigger the spellcheck - what reliably is doing it for me is "Take a look at this candidate Jane Doxe."
- Wait till you get squiggly red line under "Doxe"
- Highlight the "Jane Doxe" text
- Try to insert a hyperlink either using `Cmd+K` or by clicking - nothing happens
- Interestingly, when I just highlight "Doxe" it seems to work...

See screenshot.

<img width="802" alt="screen shot 2017-11-29 at 6 30 52 pm" src="https://user-images.githubusercontent.com/4412269/33383129-8f8c5812-d533-11e7-86a4-59cfd6981623.png">

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and a lot of other small improvements. You can grab the latest version from https://getmailspring.com/download.
