### ISSUE TITLE
"Error - Couldn't find a Sent folder in your account"

### ISSUE THREAD

**Issue by austriker27** [Foundry376/Mailspring#379]
##### Are there any related issues?
no

##### What operating system are you using?
MacOS 10.13.1

##### What version of Mailspring are you using?
1.0.8

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP email through Dreamhost.com

##### Is the issue reproducible with a particular attachment, message, signature, etc?

<img width="500" alt="screen shot 2017-11-29 at 9 04 50 am" src="https://user-images.githubusercontent.com/14855925/33388722-8e5fd87c-d4e5-11e7-97e9-9dc9f0529438.png">
<img width="426" alt="screen shot 2017-11-29 at 9 04 44 am" src="https://user-images.githubusercontent.com/14855925/33388723-8e732b16-d4e5-11e7-8875-4ae91302e4e4.png">

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Nope, the same email works fine in Apple Mail.

**Comment by bengotow** [comment]
Hey! Can you go to Preferences > Folders and tell Mailspring which folder to use as the Sent folder? It's a bit odd it wasn't able to autodetect it, but that should do the trick.

I'll improve that error message!

**Comment by austriker27** [comment]
Thanks, I thought I tried that a week ago but didnt see a sent message folder option. Now I go to the sent folder setting and it shows the right box. Closing issue because it has been resolved.

**Comment by jackdesert** [comment]
I am getting this error with mailspring 1.5.7 when I added a second account.

When I go to Prefs -> Folders, there is no "drafts" or "sent" that can be chosen from the second account. There is only "Inbox", "Mailspring", and "Mailspring.snoozed".
