### ISSUE TITLE
Heroku link is not working

### ISSUE THREAD

**Issue by stenalpjolly** [Foundry376/Mailspring#380]
Public slack joining link https://join-mailspring-slack.herokuapp.com/ is not working.

![image](https://user-images.githubusercontent.com/8219855/33422823-e92fea6a-d5dc-11e7-9c4a-7f025faa9f67.png)

**Comment by bengotow** [comment]
Hey! Looks like it's working again now—will see if I can dig in and figure out what went wrong.
