### ISSUE TITLE
[Question] Does Mailspring use Gmail's search API for Gmail accounts? 

### ISSUE THREAD

**Issue by kapad** [Foundry376/Mailspring#383]
If this isn't the present implementations, is there any plan to implement this in the future?

**Comment by bengotow** [comment]
Hey! We don't use Gmail search APIs but Mailspring implements most of Gmail's search criteria itself, so things like `from:ben@foundry376.com in:inbox is:starred` work on all accounts. You can see the list of supported operators here:
https://foundry376.zendesk.com/hc/en-us/articles/115002212931-Using-Advanced-Search-Features

Also worth mentioning that there's a fix in 1.0.9 that makes this much better. Previously you had to say "termA AND termB" - the AND wasn't automatically implied.
