### ISSUE TITLE
How to turn off developer mode

### ISSUE THREAD

**Issue by wulfalpha** [Foundry376/Mailspring#384]
##### Are there any related issues?

...

##### What operating system are you using?
...Windows 10

##### What version of Mailspring are you using?
...Version 1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
... no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...no

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
I turned on developer mode like normal but I cant get it to turn off. I might be doin something wrong but I cant find the setting
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...
I don't know that's the problem

**Comment by wulfalpha** [comment]
![mailspring errors](https://user-images.githubusercontent.com/16473924/33510097-4e9039f8-d6c5-11e7-9759-34fa6942a4b1.png)

**Comment by bengotow** [comment]
Hey! It looks like you've got a custom theme installed and it's breaking the app (though it's pretty surprising it's totally removing the UI... I'll see if I can reproduce this!)

The best thing to do would be to remove or rename `C:\Users\..\AppData\Roaming\Mailspring\packages\dreamspark` and then run the app again.

**Comment by wulfalpha** [comment]
I think that worked. Thanks! I was trying to make my own theme but it doesn't seem to have worked

**Comment by wulfalpha** [comment]
By the way, can you direct me to the right way to add new themes so this doesn't happen again? also can I just grab Nylas themes from the internet?

**Comment by bengotow** [comment]
Hey! Sorry for the hassle—I updated the starter theme here so it should work now: https://github.com/Foundry376/Mailspring-Theme-Starter. Right now there's not a central place to find themes but we're working on it!

**Comment by ShiverStorm** [comment]
I Just tried to make my own theme this morning (11/9/2019) and got the same exact issue. Is there a way to just copy the existing dark theme and edit it from there? I'm super grateful for the easy fix though! Glad to have mailspring back!
