### ISSUE TITLE
[BUG] Message status won't go away

### ISSUE THREAD

**Issue by Zangoran** [Foundry376/Mailspring#385]
##### What operating system are you using?

Microsoft Windows [Version 10.0.14393]

##### What version of Mailspring are you using?

![image](https://user-images.githubusercontent.com/7672085/33512669-3bf89986-d6fa-11e7-8e47-f18b81ebed02.png)

--

**Bug?**

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![image](https://user-images.githubusercontent.com/7672085/33512628-ad92daee-d6f9-11e7-9874-d62c9a0369ba.png)

As the title suggests, the 'Looking for more messages...' status does not disappear even after messeges are all caught up.

**Comment by we3geeks** [comment]
Also seeing this issue with version 1.0.9 on macOS with a Gmail account.

**Comment by we3geeks** [comment]
Seems to be resolved for me on macOS with the update to v1.0.10 this evening?

**Comment by bengotow** [comment]
Hey folks - yep this is fixed in 1.0.10!

**Comment by Zangoran** [comment]
@bengotow Thanks!
