### ISSUE TITLE
Feature request: Progress bar for update downloads

### ISSUE THREAD

**Issue by wulfalpha** [Foundry376/Mailspring#387]
##### Are there any related issues?

...

##### What operating system are you using?
...Windows 10 1709

##### What version of Mailspring are you using?
...
1.08
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
Unable to tell if it is making progress downloading the update
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...
Outlook will tell you in the background when it is updating.

**Comment by bengotow** [comment]
Hey! This would be really awesome - I know there's a "Squirrel Updater 2.0" in the works so maybe it could be included there. Right now, we don't have much control over the update process in Mailspring because it's done upstream in Electron.
