### ISSUE TITLE
[Nasty bug] Undo send sends original draft, not revised draft

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#390]
##### What operating system are you using?
MacOS 10.13.1

##### What version of Mailspring are you using?
1.0.9

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Doubt it - seems to be happening in the compose window and not sync related

##### Is the issue reproducible with a particular attachment, message, signature, etc?

@bengotow this is a pretty nasty bug with Undo Send. Here's how to reproduce:
- Enable Undo Send at 15 seconds (I haven't tested at other durations)
- Open up an email that you have received
- Respond the sort of thing you might respond if you were frustrated with someone and really wanted to take what you wrote back the moment you hit send, e.g. "You are incompetent"
- Hit undo send
- Replace the word "incompetent" with "the best"
- Hit send
- Wait 15 seconds, and then what actually gets sent is _the original (i.e. "incomptent")_, not the revised
- Clue: This only seems to happening when *responding* to a thread, not when you start a new email

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by kungpaogao** [comment]
Just reproduced this on Xubuntu 17.10 with Mailspring 1.0.9 by sending an email to my alternate email address. Same bug occurs with 5 second delay.

**Comment by bengotow** [comment]
Hey folks - thanks, will take a look at this tomorrow. Definitely sounds like a nasty bug...

**Comment by victortrac** [comment]
Just reproduced yesterday on 1.0.10.d250d253-1. Hit "Send", "Undo", edited, and then as soon as I clicked on "Send" again, it showed the original version.

**Comment by gottlike** [comment]
Also noticed this with a recent email I sent. Couldn't edit it, no matter how often I "undid" the sending. Sent it anyway, because it was just a small mistake, but if I really wanted to change it, I would have had to discard the draft and start a new email.
