### ISSUE TITLE
"Mailspring is Offline" modal isn't always accurate, appears intermittently 

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#396]
Hello

1 / I write a new message
2 / I attach to this message a 5 MB file
3 / I send this message ...
4/During sending, I have this error message:
![mailspring](https://user-images.githubusercontent.com/31793920/33565165-a801a25c-d91c-11e7-97dd-354af22cb7fe.png)

5 / I notice a loss of my internet connection
Mailspring made me lose my internet connection. I can repeat the problem and every time my Internet connection is lost. I am forced to close Mailspring because the error message refuses to disappear.

6/ to solve my problem of internet connection, I am obliged to disable / reactivate my Ethernet network card (the Windows utility can not solve this problem and it informs me that I have to unplug my internet modem)
7 / luckily after reopening Mailspring, the error message is no longer displayed
I can continue to use Mailspring (Unlike Nylas)

Recently, for Nylas Mail lives, I reported the same problem 
this bug in Nylas went a lot further because .... (read ->
https://github.com/nylas-mail-lives/nylas-mail/issues/183)

##### What operating system are you using?
Windows 10 x64

##### What version of Mailspring are you using?
1.0.9 (12/1/2017)
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no, none
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no
##### Is the issue reproducible with a particular attachment, message, signature, etc?
yes

**Comment by bengotow** [comment]
Thanks - this "offline status" bar is pretty finicky and does it's own internet connectivity check separate from mailsync, so it may not be accurate if your internet connection is intermittent or poor. Will see if I can improve this.

**Comment by bengotow** [comment]
Hey folks! This has actually been fixed recently - we now use the actual connectivity to your mail providers to dictate whether the alert is shown.

**Comment by joanorsky** [comment]
Somehow i am having the same issue and i have no idea why!
