### ISSUE TITLE
Mailspring window fails to load

### ISSUE THREAD

**Issue by alrightjones** [Foundry376/Mailspring#398]
##### Are there any related issues?
Search doesn't return anything close to what I'm experiencing. 

##### What operating system are you using?
MacOS High Sierra Version 10.13.1 (17B1003)

##### What version of Mailspring are you using?
Version 1.0.9 (1.0.9)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No, although I did attempt to load the [Nylas Dracula Theme](https://draculatheme.com/nylas-n1/).

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![2017-12-04_15-45-28 mp4](https://user-images.githubusercontent.com/14301181/33582697-4866527c-d90b-11e7-9363-94509b75d304.gif)

**Comment by alrightjones** [comment]
**Update:**
I've uninstalled / reinstalled Mailspring and have opt'd to stick with default themes. I've been unable to recreate the issue since. For reference, here is the Dracula package.json file contents:

`{
  "name": "Mailspring-Dracula",
  "title": "Dracula",
  "displayName": "Dracula",
  "theme": "ui",
  "version": "0.1.0",
  "description": "A dark theme for Nylas N1",
  "license": "MIT",
  "engines": {
    "mailspring": "*"
  },
  "private": true
}
`

**Comment by bengotow** [comment]
Hey! Will check out the theme - it may need to be fixed.
