### ISSUE TITLE
Support RTL (Right-to-Left) text

### ISSUE THREAD

**Issue by humanoid** [Foundry376/Mailspring#399]
Currently, it is not possible to send emails in Hebrew or Arabic/Persian without the text ending up on the wrong side. I propose that an option be added to the dropdown menu, or to the text formatting popup that allows for the changing of text direction.

**Comment by thertz** [comment]
I second the request

**Comment by ItayXD** [comment]
Is it planned?

**Comment by humanoid** [comment]
@bengotow see [issue #124](https://github.com/nylas/nylas-mail/issues/124) in Nylas Mail for reference. Do you need further clarification?

**Comment by bengotow** [comment]
Hey folks—yes, this is planned and will probably ship in January. Stay tuned!

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and a lot of other small improvements. You can grab the latest version from https://getmailspring.com/download.

**Comment by mostafabahri** [comment]
@bengotow I tried the latest version (1.1.0) but still the issue remains.   

It only renders right-to-left properly when composing a new message:
![when-typing](https://user-images.githubusercontent.com/14005313/35259083-df501022-0018-11e8-9aed-ce2e4bb2e585.png)

but here's the same message in Sent folder:
![in-sent-folder](https://user-images.githubusercontent.com/14005313/35259091-f64cb9e2-0018-11e8-9429-3fbcecf15922.png)

and here's the received message in Gmail:
![google-inbox](https://user-images.githubusercontent.com/14005313/35259100-030dc608-0019-11e8-882a-d5f8616e0390.png)

OS: Ubuntu 16.04.

**Comment by AssafNegev** [comment]
same here, message reverts back to left-to-right after send.
OS: Windows 10 64bit

**Comment by alirezaDavid** [comment]
Do you have the plan to correct this one?

**Comment by jimmyheller** [comment]
I installed recently and also I have the same problem , please guys, do something for it. thanks!
