### ISSUE TITLE
Issue with Descriptions & Roadmap

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#40]
![image](https://user-images.githubusercontent.com/25718989/31258718-fcd90644-aa8c-11e7-9cc4-56c3f309b3e6.png)
![image](https://user-images.githubusercontent.com/25718989/31258755-4471275c-aa8d-11e7-875c-a9d7cff922ad.png)

I think some markdown has been missed, in the description and roadmap.

**Comment by bengotow** [comment]
Thanks will fix 👍
