### ISSUE TITLE
Object tag / SVG no longer displays in email message body

### ISSUE THREAD

**Issue by DarkSpyro003** [Foundry376/Mailspring#400]
The object tag can no longer be used to display an interactive SVG. It does nothing/vanishes.

##### Are there any related issues?
#48 

##### What operating system are you using?
Ubuntu 17.04

##### What version of Mailspring are you using?
1.0.9-c5e85dc4

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

This signature used to display correctly in Mailspring but no longer displays an image now.
![selection_311](https://user-images.githubusercontent.com/831435/33601416-701d36ae-d9ac-11e7-80c8-57b13ee2c4e0.png)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes, Thunderbird

I believe we should keep supporting SVGs in e-mails. People usually argue against it because "SVGs never get used in e-mail anyway" but this is because support in clients is still poor.
I tried to use inline SVG as a substitute (This also displays correctly in Thunderbird) but SVG gets converted into some weird HTML formatting by mailspring.

**Comment by bengotow** [comment]
Hey! This is intentional - this works in very few clients aside from Thunderbird and we pulled <object> tag support because you could use it to track users who requested that images not be loaded. We're launching a new signature editor soon that makes it easy to put pictures (including svgs) in your signature by converting them to png/jpg and uploading them so they can be a standard <img> tag.

**Comment by DarkSpyro003** [comment]
Displaying an image in my signature is no problem. It's just sad to see _interactive_ SVG support go "because nobody supports it anyway", which might be the reason the next client developer will do it as well.
