### ISSUE TITLE
MailSploit, check if Mailspring is affected or not, and provide fix if necessary

### ISSUE THREAD

**Issue by jeroen7s** [Foundry376/Mailspring#401]
https://thehackernews.com/2017/12/email-spoofing-client.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+TheHackersNews+%28The+Hackers+News+-+Security+Blog%29

**Comment by PrzemekSkw** [comment]
@jeroen7s affect linux ?

**Comment by jeroen7s** [comment]
@PrzemekSkw no clue, doesn't seem to be OS related.
seems to affect a lot of mail clients, according to this sheet with tested clients:
https://docs.google.com/spreadsheets/d/1jkb_ZybbAoUA43K902lL-sB7c1HMQ78-fhQ8nowJCQk/htmlview?sle=true
neither mailspring nor nylas mail were mentioned though. which is why i thought i should mention it here to check.

**Comment by bengotow** [comment]
Hey sorry I saw this on Twitter first and replied there: https://twitter.com/MailspringApp/status/938438900082606080.

You can see the results here: https://www.dropbox.com/s/pneetdwdosoeex1/mailsploit.mov?dl=0. `metasploit.com` appears in the from address in all cases so I think we're good.
