### ISSUE TITLE
reception of late messages or I do not receive the messages immediately

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#403]
Hello

1/ I open Mailspring. At startup, there is synchronization and I receive all my messages correctly. (everything is fine so far!)
2 / after I do not always receive messages immediately from my email account Roundcube Webmail
I hear my ringtone on my smartphone that indicates the receipt of a new message (I do not click on the message on my smartphone) but in Mailspring, after a few minutes, I still do not see this new message.

This problem is not every time but regularly I find myself in this situation.

3/ To try to solve this problem:
I change folder and I come back on Inbox , or
when I click in the menu on "sync new mail now"
the problem is not solved

4 / to solve it and especially to receive this new message, I am obliged to close Mailspring and open it again

##### What operating system are you using?
Windows 10 x64

##### What version of Mailspring are you using?
1.0.9 (12/1/2017)

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no, none

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Roundcube Webmail 1.3.3 (I do not know for the others providers ; I've noticed with Roundcube Webmail 1.3.3)

##### Is the issue reproducible with a particular attachment, message, signature, etc?
yes, already with version 1.0.8, with 1.0.9, this problem is repeated

##### Does this feature exist in another mail client or tool you use?
yes, no problem with other software

**Comment by bengotow** [comment]
Hey—this should be fixed in 1.0.11. I was able to track down this issue in #364 and it seems that Mailspring wouldn't recognize incoming mail immediately if your email server supported both the QRESYNC and CONDSTORE IMAP extensions. Stay tuned—

**Comment by franco27** [comment]
This problem has been reproduced again with 1.0.10
I will wait for the next version
thanks

**Comment by franco27** [comment]
I have the same problem with another email account imap @laposte.net

**Comment by bengotow** [comment]
Hey folks - this has shipped in 1.0.11. The app will download the update automatically, but you can get it directly here: https://www.getmailspring.com/download. Gonna go ahead and close this—if you continue to have trouble after the update, let me know and I'll re-open it!

**Comment by alorence** [comment]
I can confirm 1.0.11 fixed the issue for my IMAP accounts. Thanks !

**Comment by franco27** [comment]
For me too, I confirm it's solved! thank you
