### ISSUE TITLE
[Feature Request] Support Reply / Reply All / Forwarding in new window with Gmail Shortcuts

### ISSUE THREAD

**Issue by katonash** [Foundry376/Mailspring#404]
Allow composing in a new window when replying / forwarding emails. 
I usually do this by using the Shift+A for reply all, Shift+R for reply, and Shift+F for forwarding in Gmail web as well as Mailbird. 

This lets me scroll through the email chain I'm replying to while still having visibility on my draft.

**Comment by bengotow** [comment]
Hey! There's no shortcut for this but you can pop out a draft by clicking this icon: 
<img width="100" alt="image" src="https://user-images.githubusercontent.com/1037212/79421132-c9b6dc80-7f7f-11ea-8d46-8e4a0c6c82ca.png">

Based on the limited upvotes this has gotten I'm going to say we probably won't add shortcuts. Cheers!
