### ISSUE TITLE
Status bar icon on macOS doesn't show the menu items except on the Mailspring app and the desktop

### ISSUE THREAD

**Issue by kartikvashistha** [Foundry376/Mailspring#406]
##### Are there any related issues?

No

##### What operating system are you using?
macOS 10.13.1

##### What version of Mailspring are you using?

1.0.9
--

**Bug?**

Yes

##### Do you have any third-party plugins installed? If so, which ones?
None
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

This is a minor bug. Basically, the Mailspring icon on the status bar doesn't show the quick access menu when in full screen in other apps. It works fine inside the Mailspring app and the desktop. I have herewith attached screenshots showcasing this. 
Specs of my Mac: 2015 13 inch MBP i7 CPU, 16 GB RAM, & 512GB storage

Doesn't work in other full screen apps
<img width="1680" alt="doesn t work in other full screen apps" src="https://user-images.githubusercontent.com/24190807/33677356-5cd912ca-dab0-11e7-9067-acf85e1a77f6.png">

Works correctly in the Mailspring app and the desktop
<img width="1680" alt="works fine in desktop and mailspring" src="https://user-images.githubusercontent.com/24190807/33677357-5cf39f3c-dab0-11e7-9778-9c78efd6ea93.png">

--

**Comment by bengotow** [comment]
I can confirm this is an issue in the latest version (1.1.3). Could you do me a favor and file this over on the Electron/Electron repository? This will definitely impact all Electron apps and not just Mailspring.

**Comment by kartikvashistha** [comment]
Hi Ben, apologies for the late reply, but I have filed this issue in the Electron repo. It can be tracked [here](https://github.com/electron/electron/issues/12114)

**Comment by kartikvashistha** [comment]
Hi @bengotow, I no longer seem to have this problem in version 1.1.5 in macOS 10.13.4.

**Comment by kartikvashistha** [comment]
Closing this issue as it has been resolved for some time, completely forgot to close it.
