### ISSUE TITLE
Mailspring crashes on syncing university sponsored gmail account

### ISSUE THREAD

**Issue by thertz** [Foundry376/Mailspring#407]
Hi,
I have three accounts configured in mailspring - 
1. personal gmail account (no issues)
2. work imap account (no issues)
3. University gmail account - this sometimes says - 'problems syncing' and can then go into an infinite loop of error messages on the bottom of the inbox panel. The only way to stop it is to kill the app externally and restart.

This bug does not always occur - i.e. I have not yet figured out when/how it is triggered, but its certainly a recurring bug.

**Comment by Modelmat** [comment]
If the University Email account using Google Apps, and the IMAP is not supported, this will probably happen
To check if it is disabled (by your admin), go to Settings, and if the tab Forward & Pop Imap is not there, it is not supported.

**Comment by thertz** [comment]
hi,
this seems to have resolved in the new release which overall seems more stable. Still having issues with a few other things that I am not sure how to get around:

1. Mail search - is there no way to control indexing, some searches work, others do not.
2. RTL support for hebrew - have a workaround with the template response, but its clunky.

all in all this is a great mail app. coming from mac to linux after many years, this was a critical ingredient for my well being.

Thanks!
—Tomer


-------------------------------------------------------------------------
Tomer Hertz,  Ph.D.

Senior Lecturer (Assistant Professor)
The Edgar de Picciotto Career Development Chair in Systems Immunology
Dept. of Microbiology, Immunology and Genetics 
Faculty of Health Sciences, and
The National Institute for Biotechnology in the Negev
Ben-Gurion University of the Negev,
Beer-Sheva, 84105, Israel

Affiliate Investigator
Vaccine and Infectious Disease Division
Fred Hutchinson Cancer Research Center
1100 Fairview Ave. N
Seattle, WA, 98109
 
Homepage: http://www.hertz-lab.org <http://www.hertz-lab.org/>  
Email: thertz at fhcrc dot org
Tel: (206)-667-2310  
------------------------------------------------------------------------

**Comment by bengotow** [comment]
Hey! Thanks for the update Tomer.

Yep - I think you're right about the mail search. We index all the message headers (subject, etc.) but only the bodies from the last three months. So some searches for the contents of old emails won't work. This will be a setting soon - we just needed a reasonable default until then, since the cache can take up a few GB of space if you have a lot of email.

I'll see if we can improve RTL support - I'm not sure what's involved. Could you elaborate on your template response fix in https://github.com/Foundry376/Mailspring/issues/399? Would love to know if it's something we could standardize somehow.

Gonna close this one!

**Comment by thertz** [comment]
Hi Ben,

Digging on github replies I found an Israeli guy (how surprising…) that suggested to draft a quick response template that looks like this :
Create a file: RTL.html and paste into it:
<div style="direction:rtl;text-align:right;"><div>RTL</div></div>

Basically the main missing feature is the ability to define paragraph writing direction since the languages themselves are supported by the OS. 

I’ve never delved into the technical details of how this is provided, but as someone who constantly switches between RTL and LTR languages, I can tell you that the situation has been practically resolved on Windows and Mac (which was not the case even 10 years ago)

The mail search is critical in my mind. Its my most used feature, as I never file any emails and only erase junk messages.

Best,
—Tomer
