### ISSUE TITLE
[BUG] New signature editor blank boxes

### ISSUE THREAD

**Issue by Zangoran** [Foundry376/Mailspring#408]
##### What operating system are you using?
Microsoft Windows [Version 10.0.14393]

##### What version of Mailspring are you using?
1.0.10-d250d253

--

**Bug?**
![image](https://user-images.githubusercontent.com/7672085/33696394-ad578daa-dac7-11e7-8a54-74f9c742277c.png)

It appears that there are 5 blank boxes that only do one thing when you click on it. It just displays this box: 
![image](https://user-images.githubusercontent.com/7672085/33696483-09a21f58-dac8-11e7-853d-832d1a93d6ba.png)

Changing themes doesn't help.

**Comment by bengotow** [comment]
Hey! Hmm those are previews of what the signature would look like with
other templates applied. Unfortunately when we migrate signatures from the
old versions of the app, they’re just raw HTML so the other templates don’t
show any previews. If you click one ( and abandon your raw HTML) you’ll see
the new UI for styling your signature.

Will see if I can improve the empty state there.

Ben

**Comment by Zangoran** [comment]
@bengotow Awesome, I will take a look at the working UI by doing what you said. Thanks for the continued development!

**Comment by bengotow** [comment]
This has been fixed with some placeholders in 8fe8a65f8028adf843985c421517f76650646242, though by the time we ship it this week most people will probably have seen the new UI!

**Comment by Zangoran** [comment]
@bengotow Thanks!
