### ISSUE TITLE
[Issue] Size of Panes not Saving

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#41]
When I change the size of the left pane so it looks like outlook (compared to that of gmail), than I restart, it goes back to gmail size.

**Comment by zerolfc** [comment]
I have this problem too. the panel size when resize, its not saving the current size if you re-open the app. 
Hide / show email address also the same.

**Comment by bengotow** [comment]
Hey folks, this should be fixed in #41. This code was refactored quite a bit and saves to localStorage instead of to disk, which should resolve the issue when the app is quit and the file does not save.
