### ISSUE TITLE
Show the blocks with Chinese chars in Ubuntu 16.04

### ISSUE THREAD

**Issue by tlytg456** [Foundry376/Mailspring#414]
##### Are there any related issues?
Hello,
I cannot see the Email with Chinese chars, the chars always show the blocks, I think it is the language or font issue? My system language is English and the title of Mailspring window can show the Chinese.

##### What operating system are you using?
Ubuntu 16.04

##### What version of Mailspring are you using?
viersion 1.0.10-d250d253

--
Thanks a lot

**Comment by mgjo5899** [comment]
Ubuntu 17.10 - Xorg
Mailspring Version 1.0.10
Same with Korean words that are on some of my e-mail contents.  All of the Korean words show up in boxes (I think I saw this happening about 10 years ago in Internet Explorer in Windows env. lol).  Funny thing is that their titles show up on the top menu bar when I open them individually (I guess that's Ubuntu's language support) but in the content, I can't see any Korean words.

**Comment by duanyajuzi** [comment]
I also encountered the same problem, in Ubuntu 16.04, the title bar shows the correct Chinese, but the content is garbled, just like the box

**Comment by bengotow** [comment]
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of Electron and/or snapcraft. Feel free to bump this or re-open a new issue if you run in to this again.

**Comment by WebShapedBiz** [comment]
Hi,
I've just received an email written in Croatian language and this is how it looks only in Mailspring:
![Slika zaslona 2020-10-26 14 42 58](https://user-images.githubusercontent.com/6765137/97180288-264e4c00-179a-11eb-8946-3940c4dea798.jpeg)

Once again, only in Mailspring. In Gmail in browser or Wavebox that I'm using alternatively, the text is very much normal and readable.

OS: elementaryOS 5.1.7 (Ubuntu 18.04 based)
Mailspring version: 1.7.8-13635bcf

Cheeers.
