### ISSUE TITLE
URL containing : are incorrectly linked

### ISSUE THREAD

**Issue by Bouska** [Foundry376/Mailspring#417]
I'm using Mailspring 1.0.10 on Fedora 26. Like in issue #269, I have some URL that are incorrectly linked because they contain the ":" character like that one `https://fr.wikipedia.org/wiki/Special:ConfirmEmail/xxxxxxx`. Those URL are quite common on mail sent by MediaWiki. I think it's just a character to add on a regex, I'll correct it myself once I fixed my git repo.

**Comment by bengotow** [comment]
I can confirm that this is still a bug in 1.1.3:

<img width="548" alt="image" src="https://user-images.githubusercontent.com/1037212/35882260-678b5850-0b38-11e8-819e-10a772172875.png">

**Comment by bengotow** [comment]
Hey folks—this has been fixed in 1.1.5 which shipped yesterday. You can download the update from https://getmailspring.com/download or choose "Check for Updates" within the app to install it. Enjoy!
