### ISSUE TITLE
Empty attachment was sent if its title contains non-latin characters

### ISSUE THREAD

**Issue by JunnanZ** [Foundry376/Mailspring#419]
##### Are there any related issues?

#189 

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.0.10

--

**Bug?**
If I send an attachment (in Windows 10) whose title contains non-latin characters to someone, he will receive an email with an empty attachment, like this:
![screenshot 1](https://user-images.githubusercontent.com/11328339/33804275-a112f06c-ddf5-11e7-9dc2-3dfee7d94b6b.png)
![screenshot 2](https://user-images.githubusercontent.com/11328339/33804277-a648d858-ddf5-11e7-9c07-275f72bdc42d.png)

I tried Chinese and Russian so I guess all non-latin characters have this issue.

I also tried this on my Linux machine and there is no problem.

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - I fixed an issue with attachments not being saved on Windows if they contained non-latin characters, but I didn't see that it also impacted sending. Will get this fixed.

**Comment by JunnanZ** [comment]
Thank you!

**Comment by bengotow** [comment]
Hey! I've been able to fix this (turned out to be a dup of #370). Looks like it happens when the title of the file contains characters that are not safe on old versions of Windows (they work fine on Windows 7 forward, but Mailspring is still mangling the file data.) Will ship the fix in the next release—

**Comment by bengotow** [comment]
Hey folks - this has shipped in 1.0.11. The app will download the update automatically, but you can get it directly here: https://www.getmailspring.com/download. Gonna go ahead and close this—if you continue to have trouble after the update, let me know and I'll re-open it!
