### ISSUE TITLE
Is there any way to use old dark theme?

### ISSUE THREAD

**Issue by giedriusStan** [Foundry376/Mailspring#424]
I really liked the old dark theme, colors were kinda matching my OS theme. Is there a way to install it?

**Comment by bengotow** [comment]
Hmm technically you can – if you download this old version of the Mailspring source, you could take `app/internal_packages/ui-dark` and rename it to something else (`ui-old-dark` maybe, both in the folder and in the package.json file inside), and then say Mailspring > Install Theme... from the menu. Should still work fine!
