### ISSUE TITLE
Doc links to Nylas

### ISSUE THREAD

**Issue by step21** [Foundry376/Mailspring#427]
When looking at docs/readme, I noticed that some links redirect to N1/Nylas. Is that on purpose?

**Comment by bengotow** [comment]
Nope - can you point me to the places that are directing you to nylas?

**Comment by bengotow** [comment]
Ok - looks like our gh-pages branch is super old and is redirecting to Nylas, will get that fixed!

**Comment by bengotow** [comment]
OK - docs links should be fixed! (At least https://foundry376.github.io/mailspring). It's going to take some major work to get the docs updated - they were last really edited in 2015/2016 by the Nylas team.
