### ISSUE TITLE
Archiving and deleting email only work on local not on remote

### ISSUE THREAD

**Issue by thbtmntgn** [Foundry376/Mailspring#428]
I add a IMAP account to Mailspring and archiving and deleting emails seems to only work on local (Mailspring) and not on corresponding remote webmail.

##### Are there any related issues?
I saw some related issues but not sure they are exactly the same.

##### What operating system are you using?
MacOS 10.13.2

##### What version of Mailspring are you using?
1.0.10
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Yes.
Delete or archive some emails.
Reset email cache.
Deleted or archived emails are back.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hmm what email provider are you using? Merging this in to #350 and we can break it out if it turns out to be separate.
