### ISSUE TITLE
names of long files, cut

### ISSUE THREAD

**Issue by argotan** [Foundry376/Mailspring#430]
When we receive in an email, attachments and these have a long name, mailspring cuts the name when it shows in the body of the email. The workflow itself becomes slower because you have to check one by one, each file to check what it is. Moreover, when all the files your name starts the same and only differ at the end (this is the part that is not seen).

I thought that if I passed the mouse pointer, over the name of the file, it would return a mini-window with the full name of the file, it does not do anything.

I also thought that if I maximized the mail in a popout thread, to be able to use the full width of the screen would see the names of the files in full. This does not work either, since the body of the mail, has a maximum width on the screen, which does not approve the width of the monitor.

I'm using the latest version

**Comment by bengotow** [comment]
Thanks for reporting this - will see if I can reproduce. What platform are
you using? I think we might be doing this on Windows because some windows
filesystems still limit the length of file paths. Will check and see.

Ben

**Comment by argotan** [comment]
my S.O. it's [kde neon](https://neon.kde.org/) (linux-ubuntu16.04)

**Comment by bengotow** [comment]
Hmm I haven't been able to reproduce this on Ubuntu 16 using the latest version. I sent myself an email with some attachments with long names, and the attachments appear correctly for me when receiving the email:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/1037212/34017310-1b08cd88-e0da-11e7-9488-f012e01715b9.png">

**Comment by bengotow** [comment]
Oh I see - you're talking about the names being displayed truncated in the UI! I'll get a hover state in there so you can view the full titles.

**Comment by bengotow** [comment]
Hey folks - this has shipped in 1.0.11. The app will download the update automatically, but you can get it directly here: https://www.getmailspring.com/download. Enjoy!
