### ISSUE TITLE
[Bug] Links not opening in Chrome

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#432]
##### Are there any related issues?

...

##### What operating system are you using?
MacOS 10.13.2

##### What version of Mailspring are you using?
1.0.10

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Doubt it

##### Is the issue reproducible with a particular attachment, message, signature, etc?

All messages since 1.0.10 - any messages that have links in them, when I click on the link, Chrome (my default browser) opens up a new browser window but doesn't actually open the URL. Things seem to work perfectly fine on Safari, so this is somehow only a Chrome issue.

Also even before 1.0.10 a Mailspring / Chrome behavior that was a little quirky - links opened but they did so in the background - I think it probably makes more sense for Mailspring to switch over to the default browser the moment a link is clicked. (This is what is happening with Safari as default).

**Comment by bengotow** [comment]
Hey! Any chance you switched to the snap release when you upgraded to
1.0.10? This was an issue with older versions of snapd- you may need to run
‘snap update core’ on your system. (I think that was the command...)

**Comment by palefire19** [comment]
Nope, just doing the regular update method on MacOS

**Comment by jamiedbennett** [comment]
No snaps on Mac.

> What operating system are you using?
> 
> MacOS 10.13.2

**Comment by palefire19** [comment]
Nevermind. Turned out this was a Chrome problem, not a Mailspring problem. Sorry for the false alarm!

**Comment by monstercreative** [comment]
hi @palefire19 what was the issue please? I have the same problem…

**Comment by palefire19** [comment]
@monstercreative Restarting Chrome solved things for me

**Comment by moniqueyj** [comment]
I have same problem ,,
