### ISSUE TITLE
Enhancement Request: For an official arc dark theme supported by the Mailspring team.

### ISSUE THREAD

**Issue by Shickmo** [Foundry376/Mailspring#433]
**Enhancement Request**
Is there any chance in the near term to have a supported arc dark theme? 

I attempted to use this theme, https://github.com/mjohnson8165/mailspring-arc-dark and this one https://github.com/dennisotugo/Mailspring-Adapta-Theme and both failed pretty bad in their own ways. For example the arc dark theme would launch the app but immediately show the error console  and I was debugging it for quite some time with no real success and the second theme well I couldn't even launch the app and got a blank icon in the system tray. 

I have had these issue across multiple linux distributions and trying both natively packaged versions of mailspring on Solus 3 and also the snap version on Ubuntu 17.10 with the same results. 

I am still trying to write some of my own themes but figured I would request arc dark since its such a popular theme that a large amount of users would likely enjoy using. 

PS. Your dark green theme seems to be the only dark theme I have seen for the most part work with outlooks inline styling garbage which throws off a lot of themes it seems. 

**Feature Request?**
##### Does this feature exist in another mail client or tool you use? To a degree in Thunderbird as you can use the system colors, or theme, to properly color the application.
...

**Comment by bengotow** [comment]
Hey! We'll be launching a theme browser / installer soon that should make it a bit easier for you to get third party themes. In the meantime, I'll see if I can submit PRs to those themes to fix them. It seems like they should both work.

**Comment by bengotow** [comment]
Ok - https://github.com/mjohnson8165/mailspring-arc-dark/pull/1 and https://github.com/dennisotugo/Mailspring-Adapta-Theme/pull/1 should fix these themes. I'll see if we can pull one in to the app in the future, but we'll probably just be creating the theme / plugin browser instead.

**Comment by dennisotugo** [comment]
Just seeing this, mailspring has had a lot of updates that it changes made the themes irrelevant. I am working on this now.

**Comment by dennisotugo** [comment]
@Shickmo I just rebased the theme. It is no longer a full dark theme but it does have some darkness. It should work okay afaik
