### ISSUE TITLE
After install, can't search it [Wayland]

### ISSUE THREAD

**Issue by mgjo5899** [Foundry376/Mailspring#434]
##### Are there any related issues?
I tried both 'cannot open' and 'not showing up' but could not find any issue reports

##### What operating system are you using?
Ubuntu 17.10 - Wayland specific error

##### What version of Mailspring are you using?
1.0.10 (on Ubuntu software & update)

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Not related to any of those

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No

So I can't search it on the search bar that shows up after pressing Activities on the left top corner that shows Ubuntu version of Spotlight.
The only way I could launch it properly is by pressing the button "Launch" in the software & updates app.
When it shows up, it doesn't show its pretty image in my dock; it just shows a question mark.  Still, it works great in its functionality wise.

**Comment by bengotow** [comment]
Hey! Did you install the Debian package or the snapcraft release (snap
install mailspring)?

**Comment by mgjo5899** [comment]
I installed it through the Ubuntu Software application.  So I guess Debian??

**Comment by bengotow** [comment]
Hmm - this might be specific to the Ubuntu Software store - anyone else have an idea of why this could happen?

**Comment by mgjo5899** [comment]
@bengotow Are you saying that installation through snapcraft release and Debian package on Ubuntu 17.10 Wayland should not have such issue?  If that's the case, I will try with snapcraft or Debian package

**Comment by Shackelford-Arden** [comment]
Just recently installed this using the .deb on PopOS! via Eddy (dpkg -i) and didn't have any issues.

@mgjo5899 Upon rebooting your system:
1) Can you now search for Mailspring and find it
2) If yes, does it now show the correct icon?

I've noticed sometimes it takes a moment for newly installed applications to show up on Ubuntu.

**Comment by compiaffe** [comment]
I installed it on a 17.10 Ubuntu using the Snap and had the exact same issue while on Wayland.
When running in X I can both find, open and add Mailspring to the favorites in the dock.

**Comment by mgjo5899** [comment]
@Shackelford-Arden Nope.  Nothing worked out.  When I tried to open Mailspring from app store center thingy, it still opened up in Gray question mark icon.
However, as @compiaffe mentioned, this is Wayland specific error.  Currently, I'm using Xorg and Mailspring works perfectly fine, I can search it and I could see its beautiful icon on my dock.

**Comment by aral** [comment]
In addition to a +1 for the Snap installation not launching, like @Shackelford-Arden, I was able to get it running under Wayland on Pop!_OS 18.10 using the Debian package by manually installing the gir1.2-gnomekeyring-1.0 dependency.

**Comment by agoose77** [comment]
Just out of interest, what's your login shell? You need to manually source the files in `/etc/profile.d` for ZSH.

**Comment by bengotow** [comment]
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of Electron and/or snapcraft. Feel free to bump this or re-open a new issue if you run in to this again.
