### ISSUE TITLE
[Feature Request] Add an application level password.

### ISSUE THREAD

**Issue by HaoZeke** [Foundry376/Mailspring#440]
##### Are there any related issues?
Nope

##### What operating system are you using?
ArchLinux

##### What version of Mailspring are you using?
mailspring-1.0.10.d250d253-1

**Bug?**
 No

**Feature Request?**
Yes
##### Does this feature exist in another mail client or tool you use?
Yup, thunderbird has a master-password extension.

**Comment by bengotow** [comment]
Hey! going to close this one as a wontfix.

This is one of those things that is easy to do from a UI perspective but very difficult to actually make "real." I'm hesitant to add something that looks like a lock screen that is easily circumvented or doesn't reflect that the files on disk are actually unencrypted and browsing to the right folder would let you view them all.
