### ISSUE TITLE
Gmail sync breaks if "Show in IMAP" is disabled for the Important label (or others)

### ISSUE THREAD

**Issue by patrickheeney** [Foundry376/Mailspring#443]
##### Are there any related issues?
Maybe same as #437 since result is similar

##### What operating system are you using?
Mac OSX 10.13.2 (17C88)

##### What version of Mailspring are you using?
1.0.10

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

1. 'Run with Debug' restarts mailspring and I have to re-setup my mailspring ID and all my email accounts?

2. After running mailspring for awhile I get a constant message that its syncing, sending messages, and applying labels forever. Checking the logs, these were some of the latest problems. 

<img width="197" alt="screen shot 2017-12-15 at 10 15 58 am" src="https://user-images.githubusercontent.com/1407228/34052767-00d29b86-e181-11e7-837c-7c991e29ef64.png">

```
(9) mailsync-bridge.es6:315 Sync worker sent non-JSON formatted message: IMPORTANT --- Label not found: important

Sync worker sent non-JSON formatted message: IMPORTANT --- Label not found: important{"modelClass":"Message"}


{"host":"Patricks-iMac.local","timestamp":"2017-12-15T16:34:00.853Z","payload":"Error: Your locationRefNode must implement getBoundingClientRect. Be aware that Text nodes do not implement this, but Element nodes do. Find the nearest Element relative.\n    at FloatingToolbar._calculatePositionState (/src/components/contenteditable/floating-toolbar.cjsx:146:17)\n    at FloatingToolbar._calculatePositionState (/src/components/contenteditable/floating-toolbar.cjsx:1:1)\n    at FloatingToolbar._getStateFromProps (/src/components/contenteditable/floating-toolbar.cjsx:106:24)\n    at FloatingToolbar.componentWillReceiveInnerProps (/src/components/contenteditable/floating-toolbar.cjsx:75:16)\n    at FloatingToolbar.componentWillReceiveInnerProps (/src/components/contenteditable/floating-toolbar.cjsx:1:1)\n    at Contenteditable.setInnerState (/src/components/contenteditable/contenteditable.cjsx:171:35)\n    at Contenteditable.setInnerState (/src/components/contenteditable/contenteditable.cjsx:1:1)\n    at Contenteditable._saveSelection (/src/components/contenteditable/contenteditable.cjsx:550:6)\n    at Contenteditable._saveSelection (/src/components/contenteditable/contenteditable.cjsx:1:1)\n    at Contenteditable._onDOMMutated (/src/components/contenteditable/contenteditable.cjsx:340:8)\n    at MutationObserver.<anonymous> (/src/components/contenteditable/contenteditable.cjsx:1:1)"}
{"host":"Patricks-iMac.local","timestamp":"2017-12-15T16:34:00.863Z","payload":{"url":"/Applications/Mailspring.app/Contents/Resources/app.asar/src/components/contenteditable/floating-toolbar.js","line":171,"column":9,"pluginIds":[]}}
```

**Comment by bengotow** [comment]
Hey! In Gmail settings, make sure you have “Show in IMAP” checked for the
Important label. We can probably safely delete these warnings from the
logs, the app should still sync mail fine, but Gmail is providing us with a
label on a bunch of threads that doesn’t correspond to any label it
provided in the folder listing.

**Comment by patrickheeney** [comment]
@bengotow Something is causing the mailbox to get stuck syncing, applying labels, and sending mail. I turned the "Show in IMAP" setting on for all my accounts. However, I don't think its syncing fine since its stuck, but maybe these log messages are red herring.

**Comment by patrickheeney** [comment]
@bengotow Realized that I had "Show Gmail-style important markers (Gmail Only) turned on in preferences, but "show in imap" was turned off in gmail. Not sure if this combination is causing the logs to fill up and freeze the sync process.

**Comment by patrickheeney** [comment]
After turning on "Show in IMAP" for a few days, the sync errors have gone away. If I turn that option off, the app eventually fills with enough errors to cause the sync process to break (or at least visually break the UI).

**Comment by bengotow** [comment]
Hey! Thanks for the follow-up, I'll see if we can make sync handle the disabled labels a bit more elegantly in the next version.

**Comment by bengotow** [comment]
Hey folks - Mailspring now correctly verifies that you have "Show in IMAP" enabled for "All Mail" when you link an account. Going to go ahead and close this - thanks!
