### ISSUE TITLE
Link tracking breaks URLs containing &

### ISSUE THREAD

**Issue by IdiotBox** [Foundry376/Mailspring#445]
##### Are there any related issues?

Not that I can find.

##### What operating system are you using?
Windows 10 Pro N 1709

##### What version of Mailspring are you using?
1.0.10-d250d253

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No idea

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
I hope not.

Forwarding Emails which include links to sensitive things with Link and Click tracking disabled alters the link to change & to &amp;%3B.

This completely destroys the URL as it was never intended to be linked in that way.

Also, adding &recipient to the end of the URL is rather rude.. They shouldn't know if I'm forwarding the link onto someone else and neither should it be yours!

Sensitive Information changed to 0.
Original Link: https://portal.bitency.nl/backoffice/Klanten/betalen/?payment=F00000000000&key=d0000000000000000000000000000000&lang=EN

Link Received: https://portal.bitency.nl/backoffice/Klanten/betalen/?payment=F00000000000&amp%3Bkey=d0000000000000000000000000000000&amp%3Blang=EN&recipient=emailaddress%40gmail.com

No idea why any email client would do this except to try and redirect links through to them??

I'm probably uninstalling now as if I can't trust the links I send as they appear in my outbox fine!

**Comment by bengotow** [comment]
Hey! We add the recipient to the end of the URL so that Mailspring can tell you which recipients clicked links (for cases where many people are CC'd on an email, for example.) Each recipient receives a copy of the email with their email address tagged on the links. I think we could change that to use hashes in the future and avoid exposing the recipients email address, but it hasn't been a priority since recipients only receive links containing their own address.

I'll look at the links being broken - that should be a quick fix I think!

**Comment by bengotow** [comment]
Hey! I haven't been able to reproduce using the URL you provided - is there anything special about the section replaced with zeros?

The original link is turned into the following when the email is sent: 
```https://link.getmailspring.com/link/local-8338a95d-1539@Bens-MacBook-Pro.local/0?redirect=https%3A%2F%2Fportal.bitency.nl%2Fbackoffice%2FKlanten%2Fbetalen%2F%3Fpayment%3DF00000000000%26key%3Dd0000000000000000000000000000000%26lang%3DEN&recipient=bengotow%40gmail.com```

But when the mailspring server redirects to the underlying link, it does it correctly:

```
curl -v "https://link.getmailspring.com/link/local-8338a95d-1539@Bens-MacBook-Pro.local/0?redirect=https%3A%2F%2Fportal.bitency.nl%2Fbackoffice%2FKlanten%2Fbetalen%2F%3Fpayment%3DF00000000000%26key%3Dd0000000000000000000000000000000%26lang%3DEN&recipient=bengotow%40gmail.com"

< HTTP/1.1 302 Found
< cache-control: no-cache
< Date: Mon, 18 Dec 2017 23:34:27 GMT
< location: https://portal.bitency.nl/backoffice/Klanten/betalen/?payment=F00000000000&key=d0000000000000000000000000000000&lang=EN
```
