### ISSUE TITLE
Google Reminders / Snooze

### ISSUE THREAD

**Issue by Shackelford-Arden** [Foundry376/Mailspring#447]
# Feature Request
##### Does this feature exist in another mail client or tool you use?
No, this does not exist in another email client (that I know of).

I often use Google Inbox when I'm at work. I've come to find that being able to set emails as reminders for later are awesome. I've noticed that Mailspring offers similar functionality. However, I'd love it if Mailspring could sync that option with any Google email.

For example, if I set an email in Google Inbox to snooze or be reminded of later today, I'd like to be able to see this email in Mailspring under the **Reminders** folder for that respective account.

**Comment by bengotow** [comment]
Hey! Unfortunately Google Inbox doesn't expose any sort of API for it's snooze and reminders features. Hopefully we'll be able to do this in the future, but until there's a common standard every app pretty much needs to implement these separately.

**Comment by Shackelford-Arden** [comment]
I figured this would be the case but I figured I'd ask :)

Thanks @bengotow for the response!

**Comment by walkafwalka** [comment]
Is there a path to request API access for this feature from Google or is it usually just hope and pray?
