### ISSUE TITLE
sync errors with mail.163.com and mail.cstnet.cn serivice [Mailspring] folder name illegial

### ISSUE THREAD

**Issue by btstream** [Foundry376/Mailspring#453]
##### Are there any related issues?

...

##### What operating system are you using?
MacOSX 10.13.2

##### What version of Mailspring are you using?
1.0.11

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
It looks like this problem is related to `Coremail` related mail providers(Such as `mail.163.com` and `mail.cstnet.cn`), all my account on `mail.163.com` and `mail.cstnet.cn` have this issue (With IMAP protocal).

P.S. `Coremail` system is a very popular mail system in China, a lot of organizations use it to build their mail service.

1. Problem with `mail.163.com`
WIth `mail.163.com`, mailsync just crash!

2. Problem with `mail.cstnet.cn`
With `mail.cstnet.cn`, I can only see `looking for messages`.

MailSync logs are attached below.
[mail.cstnet.cn.log](https://github.com/Foundry376/Mailspring/files/1570123/mail.cstnet.cn.log)
[mail.163.com.log](https://github.com/Foundry376/Mailspring/files/1570124/mail.163.com.log)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Thanks for the logs - it looks like Coremail doesn't support a folder with the name `[Mailspring]` (probably because of the square brackets), which is breaking sync. I'll see if we can fix this in an update.

**Comment by bengotow** [comment]
Merging into #164
