### ISSUE TITLE
in the "new message" window, inserting a link is problematic

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#458]
Hello

Windows 10 x64 and Mailspring 1.0.11

I can reproduce this problem.

1/ I answer a message 
2/ I click on
![2017-12-19 21_42_26](https://user-images.githubusercontent.com/31793920/34177932-a964c6d4-e505-11e7-9037-8b823865819c.png)

3/ I write my answer
4/ in the body of the message, I select text
5/ this popup window opens:
![2017-12-19 21_33_30](https://user-images.githubusercontent.com/31793920/34178045-1aea30c8-e506-11e7-85c1-889b6d399f52.png)

6/I click on the button to insert a link (button framed in red), this popup window replaces the previous one
![2017-12-19 21_37_10-greenshot editeur d image](https://user-images.githubusercontent.com/31793920/34178110-556e088c-e506-11e7-8762-27f32b015265.png)

7/ but this window disappears immediately and I can not insert a link

I tried with  ctrl+k option to make the text a link, the window is not kept displayed

**Comment by bengotow** [comment]
Hey! Thanks for filing this - I totally agree this is... sorta wonky. I'm collecting all these `composer` issues and I'm gonna try to replace the editor itself with a new one that addresses a lot of the common concerns. (WIP screenshot below). Stay tuned!

<img width="841" alt="image" src="https://user-images.githubusercontent.com/1037212/34193198-abc4bdee-e50f-11e7-8a6e-aebf84e7b801.png">

**Comment by franco27** [comment]
yes, I will wait for this improvement with impatience

maybe add a button or an entry in the contextual menu (by the right click), to insert an image since a file in the body of the message
(keeping the function insert an image from the clipboard)

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and lots more. You can grab the latest version from https://getmailspring.com/download.

**Comment by franco27** [comment]
I confirm this problem is solved with the 1.1.0
