### ISSUE TITLE
How to configure Mail spring Project in vs2013 pro

### ISSUE THREAD

**Issue by satishgupta4s** [Foundry376/Mailspring#461]
we have downloaded code from the  https://github.com/Foundry376/Mailspring url. how we can configure this code in vs2013. what is the third party toll required to run this code. please provide step by step procedure. we also follow the given url to run code but we did not get success. please do needful as soon as possible. Thank's.

**Comment by bengotow** [comment]
Hi—Mailspring's UI is an Electron application and does not require Visual Studio. You can find instructions for setting up a development environment here: https://github.com/Foundry376/Mailspring/blob/master/CONTRIBUTING.md. If you'd like to create another mail client using Mailspring's C++ sync engine, contact mark@foundry376.com for licensing info!
