### ISSUE TITLE
[Manjaro Deepin] Drop to attach in the composer does not work

### ISSUE THREAD

**Issue by PrzemekSkw** [Foundry376/Mailspring#465]
I'm on Manjaro Deepin and have last version of Mailspring installed (1.0.11). I cannot drag and drop files to attach to messege.

**Comment by bengotow** [comment]
Hey—thanks for reporting this! Version 1.1.0 shipped today which includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and a bunch of other things. Can you see if this still happens with the new composer?

**Comment by PrzemekSkw** [comment]
It works now. Thank You very much.

**Comment by bengotow** [comment]
Awesome thank you for the reply!
