### ISSUE TITLE
Doesn't sync new mail, send email after resuming from sleep

### ISSUE THREAD

**Issue by JunnanZ** [Foundry376/Mailspring#468]
##### Are there any related issues?

No

##### What operating system are you using?
Arch Linux

##### What version of Mailspring are you using?
1.0.11

--

**Bug?**
After my laptop resumes from sleep (or suspend to be more accurate), Mailspring does not sync right away even if wifi is connected. Sometimes it starts to sync after a few minutes, but sometimes it just doesn't sync at all unless I restart Mailspring.

##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I think it affects both my Gmail and Office 365 accounts.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! I was able to reproduce this this morning and I will get this fixed in the next release.

**Comment by JunnanZ** [comment]
That's great! Thanks.

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and lots more. You can grab the latest version from https://getmailspring.com/download.
