### ISSUE TITLE
SMTP without authentication

### ISSUE THREAD

**Issue by paulpolidoro** [Foundry376/Mailspring#469]
How do I configure the account with SMTP without authentication? When I leave the user and password fields blank the program forces me to populate them and then I get authentication failure.

Springmail 1.0.11
Ubuntu 17.10

**Comment by bengotow** [comment]
Thanks - looks like a username is still required. Will get this fixed in the next release.

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and lots more. You can grab the latest version from https://getmailspring.com/download.
