### ISSUE TITLE
Syncing errors

### ISSUE THREAD

**Issue by AntouanK** [Foundry376/Mailspring#47]
##### Are there any related issues?
Cannot see any.

##### What operating system are you using?
```
$ uname -ar 
Linux 4.13.3-1-ARCH #1 SMP PREEMPT Thu Sep 21 20:33:16 CEST 2017 x86_64 GNU/Linux
$ cat /etc/arch-release 
Antergos Linux release 17.9 (ISO-Rolling)
```

##### What version of Mailspring are you using?
```
$ mailspring --version
1.0.1-ba1d6734
```

--

**Bug**
##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Maybe gmail?

##### Is the issue reproducible with a particular attachment, message, signature, etc?
When I open the app, it tries to sync my gmail account, and it fails.
In the console, I can see lots of output, and this line comes up again and again when I try to resync
```
/usr/lib/mailspring/resources/app.asar.unpacked/mailsync: line 4: 31460 Aborted                 (core dumped) LD_LIBRARY_PATH=". ${LD_LIBRARY_PATH}" "$(dirname $0)/mailsync.bin" "$@"
```

**Comment by bengotow** [comment]
This should be fixed in the next release -there were a bunch of issues with ArchLinux, libsasl2 and certificates. Stay tuned!
