### ISSUE TITLE
[Feature Request] Improve Mail Rules design

### ISSUE THREAD

**Issue by Andrewsudarikov** [Foundry376/Mailspring#470]
##### Are there any related issues?

...

##### What operating system are you using?
Elementary OS 0.4.1 Freya

##### What version of Mailspring are you using?
1.0.11

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No, it concerns the app's own preferences pane.

**Feature Request?**
So, here's my suggestion. As you can see on the screenshot: 
![screenshot from 2017-12-23 08 49 47](https://user-images.githubusercontent.com/18544958/34317409-e9ec1caa-e7be-11e7-9361-dd6145ff7efb.png)

When 2 or more conditions are added to any given rule, the sleek one-line design brakes down into the configuration like on the screenshot. If you have the time maybe you could shrink the address field or somehow address the design issue. It works perfectly, of course, but Mailspring being a well-designed sleek app could benefit from the fix to this minor design annoyance. Thanks!

**Comment by Andrewsudarikov** [comment]
The fix looks great in 1.0.12! 
![screenshot from 2018-01-02 07 46 38](https://user-images.githubusercontent.com/18544958/34474524-306e7964-ef91-11e7-975e-0454d7a920b1.png)

**Comment by Andrewsudarikov** [comment]
The fix looks great in 1.0.12! 
![screenshot from 2018-01-02 07 48 29](https://user-images.githubusercontent.com/18544958/34474541-5e7a568e-ef91-11e7-87fd-3486620bc70a.png)

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and lots more. You can grab the latest version from https://getmailspring.com/download.
