### ISSUE TITLE
Problem with IMAP/SMTP settings 

### ISSUE THREAD

**Issue by yilmazbah** [Foundry376/Mailspring#471]
Dear all,

I have already add Gmail and Outlook account. However, more importantly I need to add my university account which in Mail App of Mac itself, I can do it using exchange option. However, if I use CanaryMail or Airmail I can my account with IMAP/SMTP settings but in here it gives the error below. 

Any suggestion?

Thanks a lot.

##### Are there any related issues?
Closed issue!

##### What operating system are you using?
MacOS
##### What version of Mailspring are you using?
1.0.11

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
University Exchange account
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
----------IMAP----------
* OK The Microsoft Exchange IMAP4 service is ready.
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN SASL-IR UIDPLUS UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
2 LOGIN"*********"
Q�%2 OK LOGIN completed.
3 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN SASL-IR UIDPLUS ID UNSELECT CLIENTNETWORKPRESENCELOCATION CHILDREN IDLE NAMESPACE LITERAL+
3 OK CAPABILITY completed.
P8���4 NAMESPACE
* NAMESPACE (("" "/")) NIL NIL
4 OK NAMESPACE completed.
5 ID NIL
* ID ("name" "Microsoft.Exchange.Imap4.Imap4Server" "version" "15.1")
5 OK ID completed
6 LIST "" "*"
��ut* LIST (\HasNoChildren) "/" Archive
* LIST (\HasChildren) "/" Biobank
* LIST (\HasNoChildren) "/" Biobank/Results
* LIST (\HasNoChildren) "/" Bioinformatics
* LIST (\HasNoChildren) "/" Calendar

6 OK LIST completed.
��H�9���Ȥ�:d�:�3��{�[�(�_#S��C�"�p��Z��>�ש4a����uF�k@��*	Mp�����SD�&}8�/�s"m��v8|�G��^~���N+N�@X�~L��G�k۔�8��G�&��&eu���L�|��B�}���	8�~�zL�i'Yǿ�t�\�=6ԯ&5�P��

----------SMTP----------
220 aai-mail-03 ESMTP Mail
�EHLO b-MacBook-Pro.local
v250-mail.campus.unibe.ch Hello [31.10.147.77]
250-SIZE 20971520
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-AUTH GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250 CHUNKING
STARTTLS
220 2.0.0 SMTP server ready
EHLO b-MacBook-Pro.local
250-mail.campus.unibe.ch Hello [31.10.147.77]
250-SIZE 20971520
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH GSSAPI NTLM LOGIN
250-8BITMIME
250-BINARYMIME
250 CHUNKING

SMTP Last Response Code: 250

SMTP Last Response: mail.campus.unibe.ch Hello [31.10.147.77]
SIZE 20971520
PIPELINING
DSN
ENHANCEDSTATUSCODES
AUTH GSSAPI NTLM LOGIN
8BITMIME
BINARYMIME
CHUNKING

mailsmtp Last Error Code: 17

mailsmtp Last Error Location: 10

**Comment by yilmazbah** [comment]
Interestingly, if I use Nylas, it works beautifully. I doesn't give any error on adding account with IMAP/SMTP settings. Any idea?

**Comment by tkerst** [comment]
Same problem here running Arch with Mailspring 1.1.0-7563b09d (aur package). 
The authentication via openssl and with my smartphone works without any issues.

**Comment by dw72** [comment]
Same problem on my IMAP account

**Comment by yilmazbah** [comment]
Even update came recently but no news of whether this issue will be solved or not...

**Comment by Roger-T800** [comment]
Same for me too, same log. Mailspring version 1.1.4-22d9f20d. Please help!

**Comment by hassanalinali** [comment]
I have the same problem, luckily I've seen the comments and Nylas Mail also works for me, I get the same error code and location

**Comment by chupindo** [comment]
Same problem on Linux 18.04 LTS with Mailspring 1.2.1.

**Comment by bengotow** [comment]
Hey folks—this should be resolved when the fix for #341 ships this week. The app wasn't correctly choosing the LOGIN method over GSSAPI and NTLM.

**Comment by bengotow** [comment]
Hey folks! This has shipped in 1.4.1. You can get the update automatically if you're using the Mac and Windows versions, or the Linux snapcraft release, and you can also download it from https://getmailspring.com/download.  I'm going to go ahead and close this and we'll re-open it if necessary. Thanks—enjoy the app!

**Comment by yilmazbah** [comment]
Working beautifully.

Thank you so much.

Cheers,
Bahti
