### ISSUE TITLE
Warning about "Dear Professor XXX"

### ISSUE THREAD

**Issue by PowerSnail** [Foundry376/Mailspring#476]
#### The issue

I receive warnings about using "Dear Professor" when I address the email as "Dear Professor XXX,". I am not sure if this is intended. A quick search on Google seems to suggest that this is an appropriate way of addressing professors (If not a Doctor).

Thanks.

---------------

##### Are there any related issues?

I don't think so. A search on "professor" returned nothing relevant to my report.

##### What operating system are you using?

Windows.

##### What version of Mailspring are you using?

1.0.11

**Comment by bengotow** [comment]
Hey! We've had a bunch of trouble with this warning catching too many false positives. (Related #381). I'll merge this into that - we should probably just disable this check.
