### ISSUE TITLE
Doesn't start if no internet connection is available (Windows)

### ISSUE THREAD

**Issue by DanielBakovic** [Foundry376/Mailspring#478]
Hi,
the current Mailspring version doesn't start on Windows 7 if there is no internet connection. I use it only with my Gmail account.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - can you double check that you've updated to 1.0.11, the latest version? I think this was fixed a couple months ago but I'll double check and see if I can reproduce the problem.

**Comment by DanielBakovic** [comment]
Hi,
I re-installed Mailspring and not it's loading in offline mode, too. I have no idea what changed but it works now.

**Comment by bengotow** [comment]
Great! Thanks for checking—I'll re-open this if anything changes.
