### ISSUE TITLE
Receipt of message "Without object","incorrect date "and hidden email address

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#482]
with Windows 10 x64 , Mailspring  1.0.11

Hello

Since the installation of version 1.0.11, irregularly and this problem is random for the received messages (I do not always have this same problem for the same sender)

until today, this problem is not frequent and I have observed this problem with only newletters
today I had this same problem with one of my contacts

When this problem occurs: Mailspring warns me when I receive a new message, but I can not find this message at the top of the list.
In the "Inbox" folder, it is difficult to find it.

I see this message in the "Unread" folder. This message has anomalies: this message has no object, with a date very far in the past, and the address is hidden.
(in Thunderbird, the display is correct there is the date, the object and address)

today's example with my contact
1 / this contact sends me a message. the message is received normally (date, subject, mail display correct)
![mailspring_ _conges_2017-12-28_19-25-20](https://user-images.githubusercontent.com/31793920/34420378-7c6d7530-ec09-11e7-818f-c34ed87951ce.png)

2 / later, I receive another message from this same contact (and problem!)
![mailspring_ _no_subject_2017-12-28_17-32-04](https://user-images.githubusercontent.com/31793920/34420409-b7fee82c-ec09-11e7-9361-af52a97e37b3.png)

![2017-12-28_19-07-00](https://user-images.githubusercontent.com/31793920/34420425-cacd935e-ec09-11e7-985e-b72c0bfd3e77.png)

3 / when I click on the message on this icon
![mailspring_2017-12-28_20-03-10](https://user-images.githubusercontent.com/31793920/34420552-83ca14ae-ec0a-11e7-81f5-18aea96701ac.png)

the body of the message is not hidden and is displayed correctly

**Comment by bengotow** [comment]
Hey! This should be fixed in 1.0.12, which just shipped this evening - I think this was a side effect of a regression in 1.0.11. Can you try downloading the update from getmailspring.com/download and let me know if you still run into the issue?

**Comment by franco27** [comment]
I confirm this problem is solved with the 1.0.12

**Comment by franco27** [comment]
since the update, I have not had this problem again
