### ISSUE TITLE
Where is the SQLite DB stored?

### ISSUE THREAD

**Issue by jasondavis** [Foundry376/Mailspring#484]
Where is the SQLite DB stored on windows?

**Comment by bengotow** [comment]
The SQLite database is the `.db` file in the `C:\Users\<You>\AppData\Roaming\Mailspring` folder.  For info about app storage on other platforms, see: https://foundry376.zendesk.com/hc/en-us/articles/115001968632-Where-does-Mailspring-store-mail-data-how-do-I-delete-cached-settings-.

Thanks!
