### ISSUE TITLE
[Enhancement] Realtime unread count

### ISSUE THREAD

**Issue by tchiotludo** [Foundry376/Mailspring#485]
When I deleted a message, the unread count doesn't change in realtime.
The sync engine will sync the delete of a message and after the unread count is refresh.
It's quite frustrating when dealing with a lot of mails, you have the impression that you have unread mail and keep you checking for mail that don't exist any more.

**Comment by bengotow** [comment]
Interesting - it looks like it's instantaneous for Archiving but moving to Trash takes time to update. I'll see what's going on here.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this @tchiotludo —this was fixed by fe2170c above but I forgot to close the ticket somehow. Enjoy!
