### ISSUE TITLE
[Enhancement] Mark as unread only on the last mail of the thread

### ISSUE THREAD

**Issue by tchiotludo** [Foundry376/Mailspring#486]
When you mark a mail as unread, I've the impression that the whole thread is mark as unread even your own message : 

![peek 2017-12-29 07-58](https://user-images.githubusercontent.com/2064609/34431284-1a889b3c-ec6e-11e7-863b-c6e3e4e1ecc0.gif)

It must mark as unread only the last email of the thread

**Comment by bengotow** [comment]
Hey! I just checked and it looks like this behavior is the same as Gmail and Apple Mail on the Mac. All of the messages in the thread / conversation are given the flag. We may add the ability to change a single message in the future.

**Comment by koenpunt** [comment]
While this might be the case when selecting the thread, there's no option to mark a single message as unread, also not from the message itself. Or at least not that I know of..

**Comment by mikeytwice** [comment]
+1 here. I keep emails unread when I need to respond to them, which is a pretty common practice. Gmail allows you to "mark unread from here." Apple Mail still does not.
