### ISSUE TITLE
Mouse go backward functionality not working

### ISSUE THREAD

**Issue by chadidi** [Foundry376/Mailspring#490]
Mouse go backward functionality not working on mailspring

![FanTech](https://static.jumia.co.ke/cms/external/pet/FA286EL0QUWVGNAFAMZ/5f165af1f1b1fb579a58df79d5726f49.jpg)

Operating System: Windows 10 X64 bit
MailSpring Version: 1.0.12

**Comment by bengotow** [comment]
This is a dup of #210
