### ISSUE TITLE
I just installed Mailspring for the first time and it won't open

### ISSUE THREAD

**Issue by joshtwo** [Foundry376/Mailspring#494]
##### Are there any related issues?

...

##### What operating system are you using?
Arch Linux

##### What version of Mailspring are you using?
rev 105 via Spring

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No, this is a fresh install.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

All I did was install the application and attempt to run it for the first time. Installed and activated Snap, created the Ubuntu One account, logged in, ran `snap install mailspring`, ran `mailspring`, and I got something like this:

```
~ > mailspring
Streaming log data to /run/user/1000/snap.mailspring/Mailspring-2288.log
App load time: 204ms
```
There's never any GUI that comes after it though. It just sits there with this text on stdout. Was there something else I was supposed to do while setting up Mailspring?

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
I sure hope not!

**Comment by dweremeichik** [comment]
Hey, I think I might have run into the same thing earlier today on a different distro. I rebooted my machine and that seemed to fix the issue. Prior to doing that Mailspring didn't show up in the application menu either.

**Comment by joshtwo** [comment]
I thought of that but it didn’t work. I’m starting to wonder if this really is a Snap/Electron issue because I installed another app and had a similar issue.

Joshua Blume

On Dec 30, 2017, at 1:12 AM, Dylan Weremeichik <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey, I think I might have run into the same thing earlier today on a different distro. I rebooted my machine and that seemed to fix the issue. Prior to doing that Mailspring didn't show up in the application menu either.

**Comment by bengotow** [comment]
Hey! Hmm - this is pretty strange. Can you try updating snap itself via `snap refresh core` and see if that helps? I wonder if this happens when we try to use newer snap interfaces in an older version of snapcraft?

**Comment by joshtwo** [comment]
```
~ > snap refresh core
snap "core" has no updates available
```
That's all I get.

**Comment by joshtwo** [comment]
For the record, this is definitely a Snapcraft issue. I installed Mailspring using an AUR package (a package made by Arch's users instead of official maintainers) based on the .deb package and it works.

**Comment by AnianZ** [comment]
For what it's worth: I had the exact same issue on Arch and the snap. But I'm very happy with the AUR version now.

**Comment by franktopel** [comment]
I have the same problem on a fresh arch install, using the version from the AUR, both with Mailspring and nylas-mail-lives-bin package. The application never shows any GUI.

**Comment by joshtwo** [comment]
These days I use the installation from the AUR and it works. I just gave up on Snap, honestly.

**Comment by franktopel** [comment]
I installed the version from the AUR and starting it now kind of works, but leads to gnome session repeatedly crashing. gnome starts, then I see the Mailspring start screen in fullscreen view for like 2 seconds, then I'm logged off automatically. The only thing that helped was opening a Terminal (CTRL-ALT-F2), logging in and uninstalling Mailspring.

**Comment by Markm52** [comment]
i installed this yesterday on my alienware 14 laptop running zorin 12.3 it worked fine but when i downloaded and installed today on my desktop it did not work

**Comment by themazim** [comment]
Same for me, clean install on a freshly installed ubuntu, can't get it to open, yet the status icon (open inbox, new message, preferences) appears in the taskbar, clicking something won't do a thing.

**Comment by RB3rg** [comment]
same here Ubuntu 18.04 after update mailspring to 1.4.0
`/snap/mailspring/240/bin/desktop-launch: line 185: /home/user/snap/mailspring/common/.config/user-dirs.dirs: No such file or directory
cp: cannot create regular file '/home/user/snap/mailspring/common/.config/': Not a directory
/snap/mailspring/240/bin/desktop-launch: line 188: /home/user/snap/mailspring/common/.config/user-dirs.dirs.md5sum: No such file or directory
/snap/mailspring/240/bin/desktop-launch: line 188: /home/user/snap/mailspring/common/.config/user-dirs.locale.md5sum: No such file or directory
`
It was working with version 1.3.0

**Comment by botjaeger** [comment]
I say this issue still happening.
Ubuntu 18.04.1
MailSpring 1.4.0

**Comment by Hell0w** [comment]
Same issue on Ubuntu 18.04: 
- normal package starts and everything, but the snap won't start
- No logs when starting from command line
- No process when searching for "mailspring"

**Comment by CicoZhang** [comment]
Great to know that I am not alone.

**Comment by trickreich** [comment]
Same issue on Ubuntu 18.10:

- normal package starts and everything, but the snap won't start
- No logs when starting from command line

**Comment by jaimearc** [comment]
1- uninstall mailspring

2- $ sudo apt update
$ sudo apt install gdebi-core wget

3- $ wget -O ~/mailspring.deb "https://updates.getmailspring.com/download?platform=linuxDeb"

After execution of the above command you should find the Mailspring's installation package within your home directory:

$ ls ~/mailspring.deb 
/home/linuxconfig/mailspring.deb

Install Mailspring
Lastly, use the gdebi command to install Mailspring on Ubuntu 18.04. When prompted answer y:

$ sudo gdebi ~/mailspring.deb

"i see this in some tutorial and work for me"

**Comment by Wtorek** [comment]
@jaimearc thanks :+1: thats work

**Comment by bengotow** [comment]
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of Electron and/or snapcraft. Feel free to bump this or re-open a new issue if you run in to this again.
