### ISSUE TITLE
Being able to modify an account connection settings

### ISSUE THREAD

**Issue by ploum** [Foundry376/Mailspring#496]
When trying to modify an account connection settings, one must go through all the wizard. No setting is saved.

This is specially painful if you are unsure about one particular setting and want to try them.

**Comment by bengotow** [comment]
Hey! Interesting - it looks like this has been broken recently for standard IMAP/SMTP accounts (eg: not Gmail or Yahoo presets). I'll see if I can fix this in the next update.

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and lots more. You can grab the latest version from https://getmailspring.com/download.
