### ISSUE TITLE
[Feature Request] Make auto-hiding of header in composing email a setting

### ISSUE THREAD

**Issue by jasonmarkperez** [Foundry376/Mailspring#499]
##### What operating system are you using?
OSX 

##### What version of Mailspring are you using?
1.0.12-cf081332

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes.

I really don't like that clicking out of the recipient/header section of composing an email collapses and hides recipients and the email account in use. It makes it much more likely users will miss a recipient or accidentally send from the wrong account. It would be great if this could be disabled.

**Comment by bengotow** [comment]
Hey! You know I don't actually like this either... it's mostly a holdover from Nylas Mail. I'll see if I can get this behavior changed in the next release.

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which fixes this issue and includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown shortcuts and lots more. You can grab the latest version from https://getmailspring.com/download.
