### ISSUE TITLE
Missing 'Delete' button and 'Trash' folder

### ISSUE THREAD

**Issue by FrankKubuntu** [Foundry376/Mailspring#500]
Hello,

1.0.12 under Linux (Kubuntu 16.04).
No plug-in.
Issue specific to a specific account at a specific IMAP provider.
Issue always reproducible no matter how I create my accounts.
It seems Nylas email client is having this issue as well https://github.com/nylas/nylas-mail/issues/3594

I use 2 accounts (emails) at the same provider and no matter in which order I create them it's always the same that has the delete issue.

I create Account #1, the delete button is there and there is a TRASH folder in Mailspring for this account.
I create Account #2, the delete button is not there and there is no TRASH folder in Mailspring for this account.

I was in the process of transferring everything from Thunderbird and I halted. I'm staying with TB until this issue is fixed. I could not find any workaround, including dragging (moving) a msg to the Trash folder, as the folder is missing!

EDIT: I seem to be getting issues syncing for THAT specific account. Here his the log:

**********
24976 [2018-01-01 19:30:38.744] [main] [info] ------------- Starting Sync (Account2@provider.ca) ---------------
24976 [2018-01-01 19:30:38.745] [background] [info] Marking all folders as `busy`
24976 [2018-01-01 19:30:38.746] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** no such table: Folder
 ***

24976 [2018-01-01 19:30:38.747] [metadata] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** no such table: _State
 ***

24976 [2018-01-01 19:30:38.748] [main] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** no such table: Task
 ***

24976 [2018-01-01 19:30:38.804] [main] [critical]  *** Stack trace (line numbers are approximate):
 *** ??:?  SQLite::Statement::Ptr::Ptr(sqlite3*, string&)
 *** ??:?  SQLite::Statement::Statement(SQLite::Database&, string const&)
 *** ??:?  vector MailStore::findAll(Query&)
 *** ??:?  TaskProcessor::cleanupTasksAfterLaunch()
 *** ??:?  runListenOnMainThread(shared_ptr)
 *** ??:?  main
 ***
**********

Thank you very much for assigning yourself on this issue!

**Comment by bengotow** [comment]
Hey—it sounds like you need to tell Mailspring what folder to use for your Trash in Preferences > General:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/1037212/34507901-68f08a76-efef-11e7-99d5-02a1b887d81d.png">

**Comment by FrankKubuntu** [comment]
Hey Ben! That worked!

It was already assigned to "TRASH", but I re-selected it and it worked!

Now I can uninstall TB and become a full time member of Mailspring! I wish many good years of nice developments and improvements!

Tnx

**Comment by FrankKubuntu** [comment]
Closing.
