### ISSUE TITLE
Use TypeScript instead of Babel + CoffeeScript

### ISSUE THREAD

**Issue by DavidRouyer** [Foundry376/Mailspring#503]
Are you interested in migrating from Babel + CoffeeScript to TypeScript?
TypeScript is so much better!

**Comment by bengotow** [comment]
Yes! Would love to, but Mailspring is almost 80k lines of JS - PRs welcome ;-)

**Comment by DavidRouyer** [comment]
JS files are TS files :) This is why it is so popular, you don't have to do it all at once! Then you can start adding types

**Comment by bengotow** [comment]
Yeah I should definitely try adding types again—we tried about two years ago right when TypeScript came out and this was still Nylas Mail, but turning on the Typescript linter gave a zillion errors all over the project. Haha I'm sure that's been fixed now..

**Comment by bengotow** [comment]
Happy to report that as of 1.1.0, Mailspring has no coffeescript! One step closer ;-)
