### ISSUE TITLE
Mailspring Messages keeping Coming back after set as " Read"

### ISSUE THREAD

**Issue by dlj2019** [Foundry376/Mailspring#504]
Messages keep coming back ( from 1 to 2 day ago ) to the mail box after i set as "Read".  

What operating system are you using?
4.9.68-1-MANJARO

What version of Mailspring are you using?
mailspring 1.0.12.cf081332

Bug?**
Do you have any third-party plugins installed? If so, which ones?
No

Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

Thanks in advance!
DJ

**Comment by bengotow** [comment]
Hey folks—this should be fixed in v.1.13 - this would happen when the foreground sync worker became permanently blocked trying to use CONDSTORE to catch up on a very large number of message changes.

**Comment by bengotow** [comment]
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.
