### ISSUE TITLE
[Feature Request] Don't truncate email names in list of emails or header 

### ISSUE THREAD

**Issue by jasonmarkperez** [Foundry376/Mailspring#505]
In emails that have an ongoing thread, meaning it's been replied to, Mailspring seems to truncate the sender on the first space. 

I believe the logic is that it would represent the first name of a sender, but this leads to confusion if.. you communicate with people with the same first name or the sender is a company and not a person.

This happens in both the threadlist, and in the headers of emails you are viewing.
 
I sometimes email with the Cat Man of West Oakland, but he's truncated to Cat.

![screen shot 2018-01-04 at 1 42 17 pm](https://user-images.githubusercontent.com/57745/34585854-69804432-f156-11e7-9ebd-2f844df2c953.png)

![screen shot 2018-01-04 at 1 42 22 pm](https://user-images.githubusercontent.com/57745/34627187-7e6f43d4-f214-11e7-83cb-e89db221b8a1.png)

I work with a group called Dead Husband but they're truncated to Dead.

![screen shot 2018-01-04 at 1 41 57 pm](https://user-images.githubusercontent.com/57745/34585871-7b3bfbe4-f156-11e7-9101-8ca23d9c0508.png)

![screen shot 2018-01-04 at 1 42 02 pm](https://user-images.githubusercontent.com/57745/34627219-a6b9c4ae-f214-11e7-8e92-e6d3f80ae56f.png)

![screen shot 2018-01-04 at 1 56 47 pm](https://user-images.githubusercontent.com/57745/34586106-7bc2ed74-f157-11e7-85be-14f77525af33.png)

I'd much rather see their whole name, or at least truncated at the end of the whole string. Ideally, these sections in the list would be columns where the size could be adjustable.  

##### What operating system are you using?
OSX 10.12.6

##### What version of Mailspring are you using?
1.0.12
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yup.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
