### ISSUE TITLE
Empty message views

### ISSUE THREAD

**Issue by m-thielen** [Foundry376/Mailspring#506]
##### Are there any related issues?
Not found
##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.0.12

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

This happens quite often; the right pane shows my response correctly, but the mail I responded to is displayed as if it was empty. The following screenshot is made after I clicked the [...] button in my response, showing the text of the original mail as quoted text.

![mailspringbug](https://user-images.githubusercontent.com/1613101/34588105-98395098-f1ab-11e7-9ebc-6e440f1d364a.png)

**Comment by bengotow** [comment]
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of the app. Feel free to bump this or re-open a new issue if you run in to this again.
