### ISSUE TITLE
Error with password storage

### ISSUE THREAD

**Issue by Fumesover** [Foundry376/Mailspring#511]
##### What operating system are you using?
> Archlinux x86_64

##### What version of Mailspring are you using?
> 1.0.12-cf081332

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
> Nop

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
> Nop

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Hi, 
When I'm trying to login to mailspring with a typical user, I can't get it to store my password
The app is giving me the folowing error :
> Mailspring could not store your password securely. Make sure you have `libsecret` installed and a keyring is present.  For more information, visit http://support.getmailspring.com/hc/en-us/articles/115001875571

But if I run it with `sudo mailspring` it works direcly without any error

I don't know if the error is from me or not but you may update you'r support website

Amazing app, good luck guys !

**Comment by bengotow** [comment]
Thanks for reporting this! I'll incorporate this change when we update that page in the KB.

**Comment by spcmd** [comment]
I'm getting the same error on Arch Linux (mailspring 1.1.3.27dcee2-1)

```
core/libsecret 0.18.5+14+g9980655-1 [installed]
extra/gnome-keyring 1:3.27.2-1 (gnome) [installed]
extra/libgnome-keyring 3.12.0-2 [installed]
```

**Comment by BlueManCZ** [comment]
I solved this error by installing **[gnome-keyring](https://packages.debian.org/stretch/gnome-keyring)** package to system, which is also package defaultly installed with **evolution**, as @pba247 says. So thank you.

With apt: `sudo apt install gnome-keyring`

**Comment by michaelhofer** [comment]
As @BlueManCZ suggests, installing `gnome-keyring` does fix the issue.

It would be great if the rpm packages would include this as a dependency.

**Comment by brunofin** [comment]
I had the same problem on Kubuntu, and as @BlueManCZ suggests, installing gnome-keyring does fix the issue.

**Comment by denis-kisel** [comment]
Incredible, thanks BlueManCZ its work for lubuntu18.04(64)

**Comment by jasgagne** [comment]
@BlueManCZ Thanks a lot man! This helped me on Manjaro KDE!

**Comment by minyaen** [comment]
@BlueManCZ This worked for me!

**Comment by meowsus** [comment]
I'm surprised that installing `gnome-keyring` didn't work for me. After receiving the following error:

```
Mailspring could not store your password securely. Make sure you have `libsecret` installed and a keyring is present.  For more information, visit http://support.getmailspring.com/hc/en-us/articles/115001875571
```

I attempted to install `libsecret` and `gnome-keyring`

```
$ sudo apt install libsecret-1-0 libsecret-1-dev gnome-keyring
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gnome-keyring is already the newest version (3.31.91-1ubuntu1).
libsecret-1-0 is already the newest version (0.18.8-1).
libsecret-1-dev is already the newest version (0.18.8-1).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
```

But I still receive the error. I'm on Ubuntu 19.04:

```
$ lsb_release -a
LSB Version:	core-10.2019031300ubuntu1-noarch:printing-10.2019031300ubuntu1-noarch:security-10.2019031300ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

Checking the KB article linked in the error message prompts me to email support, which is what I'm doing presently.

**Comment by exapsy** [comment]
Very happy that Gnome-Keyring worked. But why? Does anyone have any idea? The message says that there just isn't a lib-secret, even though there is. So what's the issue here?

**Comment by itselijahciali** [comment]
If you're on Windows, I've found that running as administrator fixes this issue.

**Comment by romill93** [comment]
I tried running as administrator as suggested by @itselijahciali, but it did not work.
I use Mailspring on Win10 Pro 10.0.19042 Build 19042
Would really appreciate the help - if I should provide any additional info please shout out

**Comment by CodeMouse92** [comment]
We are in the process of migrating issues (and Zendesk articles too, actually) to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@romill93 The best way to get an answer to your question would be to post a new Topic on the Help section of our [Discourse](https://community.getmailspring.com).
