### ISSUE TITLE
Allow mail rules to operate on the message body

### ISSUE THREAD

**Issue by chosroes** [Foundry376/Mailspring#513]
##### Are there any related issues?

#146

##### What operating system are you using?
Linux Mint 18.03

##### What version of Mailspring are you using?
1.0.12

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
When I try to make a rule to move to trash emails that not contains a particular string, it doesn't work.
I tried with expression also, but same result.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - I think this would be a nice enhancement but currently Mailspring runs mail rules before it fetches the message bodies so we might have to rework a few things to make this possible.

**Comment by pranavgaikwad** [comment]
I believe that this issue is fixed.

![body](https://user-images.githubusercontent.com/9839757/49047951-15a88c00-f1a7-11e8-8ba7-af0b43ddb22f.png)

**Comment by bengotow** [comment]
Hey! Yep this has been fixed - it's a little buggy, but that issue will be addressed in #1064
