### ISSUE TITLE
The Bat! : displaying messages: HTML view / HTML code

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#516]
I had already reported this problem but with version 1.0.12, this problem has intensified.

My recipient uses TheBat! and when I send it messages from Mailspring, it has the HTML code of the message.
Today, the user of TheBat! has a lot of complication to read my messages.

He asked me to use another messaging software. because in the current state reading is very problematic.

he sent me screenshots, see this big problem:
![the bat4](https://user-images.githubusercontent.com/31793920/34775361-31f73446-f613-11e7-912c-9c17ac5a10da.jpg)
![the bat3](https://user-images.githubusercontent.com/31793920/34775362-321f0836-f613-11e7-8754-12da26764d54.jpg)
![the bat2](https://user-images.githubusercontent.com/31793920/34775363-324555f4-f613-11e7-9f2a-586c02ecc453.jpg)
![the bat](https://user-images.githubusercontent.com/31793920/34775364-326b0876-f613-11e7-9200-3bc471384cd3.jpg)

**Comment by bengotow** [comment]
Hey! I'll see if this can be fixed when we ship the new composer. Unfortunately "The Bat!" is very, very bad at displaying HTML emails.

Closing this as a dup of #346

**Comment by franco27** [comment]
OK, thanks

because before when I sent a message and when there was no written answer, the display was correct.
Now the display is bad (worse) and it is for all the messages sent. (even without answer)

I wish the whole team of Mailspring, a good and happy year 2018 and above all a good health who is the most important.

**Comment by franco27** [comment]
I confirm this problem is solved with the 1.1.0.
TheBat! user now correctly sees my messages sent with Mailspring, whether with a first message or when I reply.
