### ISSUE TITLE
Link and read tracking working in free version too

### ISSUE THREAD

**Issue by paulocoghi** [Foundry376/Mailspring#517]
##### Short description
Link and read tracking are apparently working in the free version. Is this expected? Such features certainly depend on the back end of the Pro version.

##### Are there any related issues?
Apparently, there are no related issues.

##### What operating system are you using?
Ubuntu 16.04

##### What version of Mailspring are you using?
1.0.12

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No third-party plugins installed.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Apparently link and read tracking are working in any account type.

**Comment by dweremeichik** [comment]
I believe these features exist as a "preview" in the free version. You may have X number of uses a week if I recall correctly. Perhaps it might be worth @bengotow outlining this somewhere.

**Comment by bengotow** [comment]
Hey! Yep — this is a little unclear still, but the way it's set up now you can try all the pro features a few times a week before the app asks you to upgrade. It seemed like a nice way to make a "free trial" of sorts without adding a strict time limit, but it's also more complicated to communicate... 

Thanks for filing this!

**Comment by ChenSun-Phys** [comment]
How many free trials of each pro feature are allowed each week?

**Comment by Phylu** [comment]
As indicated on the issue template, we do not accept bug reports or feature suggestions on GitHub Issues anymore. Please use https://community.getmailspring.com/.
