### ISSUE TITLE
allow to visit a link in the New email window

### ISSUE THREAD

**Issue by krasi-georgiev** [Foundry376/Mailspring#521]
##### What operating system are you using?
linux

##### What version of Mailspring are you using?
1.0.12
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
on mail for OSX when you compose a new message CTRL+ click allows you to visit the link. This is good to make sure the link is not broken.

**Comment by bengotow** [comment]
Hey! Thanks for filing this - I'll get this incorporated into the new composer. Stay tuned—

Ben
