### ISSUE TITLE
Keep folder assignment preferences when rebuilding cache

### ISSUE THREAD

**Issue by bgr** [Foundry376/Mailspring#523]
Folder names for Mailspring's "Sent Items", "Deleted Items" and "Archive" correspond to "Sent", "Trash" and "Archive/2018" on our server. When using "Rebuild Cache" option, the preferences for assigned folders get reset. It's also not possible to "be faster than the app" and assign folders before it syncs, since it resets the folder assignments again when sync is finished.

##### Expected behavior:
the folder assignment preferences should be retained when using "Rebuild Cache" option

---

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.0.12-cf081332

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
We're using Namecheap's "Private Email", but I'd bet this applies to any server where folder names for Sent/Trash/Archive don't match Mailspring's default

**Comment by bengotow** [comment]
Hey! This would definitely be nice but as far as development goes the goal is to make it so you don't need to rebuild the cache in the first place. If you could file another issue explaining what bug / issue is causing you to need to rebuild the cache that'd be great!

**Comment by bgr** [comment]
Agreed on that, it's just that "Rebuild Cache" can be a failsafe to sort things out until some unforeseen bug is fixed. For me it was the [1970 bug](https://github.com/Foundry376/Mailspring/issues/457#issuecomment-357006598) that prompted me to attempt this workaround, which led me to realization that preferences should be kept separate from mail cache, so that it can be purged without losing the preferences.
