### ISSUE TITLE
[Feature Request] Color Code for Account and Favorites Labels/Folders

### ISSUE THREAD

**Issue by lowercase00** [Foundry376/Mailspring#526]
Two features that exist in Spark:
1. Color code for diferent accounts
2. Possibility to add favorite folders/labels (for gmail)

##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of Mailspring are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by killtux** [comment]
+ for that!

customizing the left sidebar would be a big plus:
hiding some default folders: "Starred", "Unread", etc...
adding some custom imap folders/gmail labels that you want to check regularly (+ unread folder/label counter to see if there is a new message).

for example i get newsletters all day from my suppliers, but i have a gmail filter running that puts them to "news" and skips inbox to have a clear inbox and see really important mails.

in the morning or after work i check the news folder and unread mails if there is something interesting. a intelligent folder option would be nice. for example: set a special folder with the option "only unread mails" and got it added to the sidebar.

of course you can expand the accounts and see all labels. but they wont get checked about new emails till you click it and if you have 3 accounts with lots of labels there is a lot of scrolling needed. most labels you dont need on a daily base.

**Comment by readsquirrel** [comment]
Yes, +1 both requests. 

- I don't use Archive at all, so the ability to hide the folders would be great. Also, I don't need my SPAM folder to be that prominent.
- The ability to put favorite folders in the top section for Office 365 would also be great. There are some folders that are in a particular place in the folder tree logically but that I either check frequently or file documents into frequently. Having them as favorites at the top makes both easier.

**Comment by artsgirl** [comment]
+1

**Comment by no-boot-device** [comment]
Just set Mailspring up and this was the first thing I noticed wasn't a thing. C'mon.

**Comment by eclectic-coding** [comment]
I agree. This is a feature in SparkMail which is a wonderful helper. I would liek to see this added to MailSpring.

**Comment by gatiba** [comment]
+1

**Comment by math-uzh** [comment]
+1 favorite folders and colored accounts would be wonderful

**Comment by meesrutten** [comment]
+1

**Comment by intheravine** [comment]
+1

**Comment by skobylite** [comment]
+1

**Comment by ChitranshuV** [comment]
+1 Color code for different accounts.

**Comment by jesi-rgb** [comment]
+1 in color coding different accounts. That is a feature in Spark, a iOS and MacOS based client, and it works beautifully.

**Comment by moatus** [comment]
+1 plus the ability to customize the color of labels.

**Comment by Phylu** [comment]
I will have some time at the beginning of next year and would like to try working on this feature. This is something which is most important for me with my mail clients, and I would love to give it a shot. I think the following two issues are bascially asking for similar functionality as well:

* https://github.com/Foundry376/Mailspring/issues/1738
* https://github.com/Foundry376/Mailspring/issues/2184

I am thinking about the following:

1. In Settings > Accounts add a selector (e.g. color picker) for the account color.
2. In the main view adjust the background color of the e-mail preview tile accordingly

Are there any important things that I should keep in mind (in addition to https://github.com/Foundry376/Mailspring/blob/master/CONTRIBUTING.md)? Any pointers to the code that may be helpful are also totally welcome.

**Comment by Phylu** [comment]
I managed to get a first prototype working. I am happy to receive some feedback on it.

<img width="1552" alt="Screenshot 2020-12-26 at 20 08 43" src="https://user-images.githubusercontent.com/587332/103157777-f41b9380-47b6-11eb-8c22-4940558edd66.png">
<img width="1552" alt="Screenshot 2020-12-26 at 20 09 44" src="https://user-images.githubusercontent.com/587332/103157778-faaa0b00-47b6-11eb-8464-3e93495ff2e9.png">

**Comment by ZachariahRosenberg** [comment]
@Phylu Well done and thank you for working on this.

The label design you have here is on the full left border, which means that from a design hierarchy, it is ambiguous whether the label is *within* the message box versus part of the parent component. 

This becomes an important distinction when we include the message list "swipe functions":

<img width="156" alt="Screen Shot 2020-12-27 at 12 23 41 PM" src="https://user-images.githubusercontent.com/6923376/103176282-70a58500-483e-11eb-9623-dabf9a4bba00.png">
*screen capture of current swipe UI*

The swipe UI - the green archive - is not *inside* of the message box, but sort of underneath it. That star (in the same img above) is clearly inside the message box, so it is clear that it is tied to that message box (and when swiped to the archive, will go along with it). 

<img width="156" alt="Screen Shot 2020-12-27 at 12 29 19 PM" src="https://user-images.githubusercontent.com/6923376/103176379-35f01c80-483f-11eb-9c50-1238ae5996e0.png">
*mockup of account label with swipe UI. It's ambiguous whether the account label is part of the message box, the swipe action, or another message list feature*

With swipe actions, it becomes important to distinguish which UI elements are included *inside* the message box versus which aren't. The account label should be included with that specific message box (and when swiped, is swiped along with the rest). 

That is why it might be best to follow something similar to spark where it is a smaller color indication *inside* the message box:

<img width="114" alt="Screen Shot 2020-12-27 at 12 27 39 PM" src="https://user-images.githubusercontent.com/6923376/103176354-fb867f80-483e-11eb-8627-df2bb599f399.png">

**Comment by Phylu** [comment]
@ZachariahRosenberg Thanks for the design hint. I think having it similar to spark is looking better than adding a border left of the element (and easier to implement as well). have updated this accordingly:

<img width="380" alt="Screenshot 2020-12-27 at 20 28 06" src="https://user-images.githubusercontent.com/587332/103178323-22b27080-4882-11eb-9d8c-500a260f737d.png">
