### ISSUE TITLE
After a few weeks of use, "Unlinking messages" task starts to hang the app

### ISSUE THREAD

**Issue by axfelix** [Foundry376/Mailspring#527]
I've been able to reproduce this twice, running on newest Mailspring on Arch Linux with an ~11GB Gmail account.

After using the app for about three weeks, CPU usage becomes extremely heavy, and logs show repeated instances of:

`23217 [2018-01-09 10:43:42.413] [background] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) no longer present in remote range.`

There is no solution I've found (the app becomes almost unusably slow) other than removing the config directory and starting over, and I've been able to reproduce this twice now at intervals of a few weeks.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - I'll see if I can reproduce the CPU usage on a large mailbox. This unlinking process usually  happens when Gmail has deleted messages (maybe emptied the trash?), but I haven't seen it bring down performance like that. Stay tuned—

**Comment by axfelix** [comment]
Just FYI, I'm noticing *much* better performance in the newest version, and I haven't hit this issue yet, so here's hoping! Thanks for the great work.

**Comment by axfelix** [comment]
Closing this as I can no longer reproduce over a long enough timeframe.
