### ISSUE TITLE
<p>-Tags (Outlook) have margin/padding, but shouldn't

### ISSUE THREAD

**Issue by gottlike** [Foundry376/Mailspring#529]
##### Are there any related issues?
Nope

##### What operating system are you using?
MacOS

##### What version of Mailspring are you using?
1.0.12

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Margin/Padding is fine with `<div>`, but messed up with `<p>` tags. Unfortunately Outlook seems to use `<p>` instead of `<div>` for new paragraphs. In Gmail this renders just fine.

![screen shot 2018-01-13 at 11 45 00](https://user-images.githubusercontent.com/278766/34905370-6c8261ee-f857-11e7-9d87-99d2c2e65bf9.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - will see if we can get this fixed in the next release.

**Comment by bengotow** [comment]
Based on https://www.emailonacid.com/blog/article/email-development/paragraphs_in_html_email, I think it's safe to remove the default margin/padding from `<p>` tags all the time (it's what Yahoo mail does already.)

**Comment by bengotow** [comment]
Hey folks—the fix for this has been shipped in 1.1.2. The app will auto-update in the next few hours, or you can download the new version directly from https://getmailspring.com/download. Enjoy!

**Comment by alecmev** [comment]
> Based on https://www.emailonacid.com/blog/article/email-development/paragraphs_in_html_email, I think it's safe to remove the default margin/padding from \<p\> tags all the time (it's what Yahoo mail does already.)

Why is Yahoo's behavior being taken into consideration? It represents 5% of the market. In the meanwhile, the giants, Gmail + Apple + Outlook = ~86% of the market, have margin around paragraphs, the way it's supposed to be. [Market share source.](https://emailclientmarketshare.com/)

The link you posted is for people who write emails, their advice doesn't apply to email rendering.
