### ISSUE TITLE
Layout error

### ISSUE THREAD

**Issue by cccruzr** [Foundry376/Mailspring#53]
##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.0.1-ba1d6734

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not sure

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Seems like it happens with few emails.
The problem is that when resizing the Preview Pane in the Layout the mail content starts to blink as shown here:

![](https://i.imgur.com/jLJtj9n.gif)

--

**Feature Request?**
Please include a monospaced font to write code snippets.
##### Does this feature exist in another mail client or tool you use?
Yes. Mozilla Thunderbird.

**Comment by V3XATI0N** [comment]
Also happens here.. and has since the first N1 client. Annoying, although resizing the preview pane so that there are no divs right on the edge of wrapping [usually] fixes it.

**Comment by bengotow** [comment]
Hey folks—I actually noticed this myself yesterday while testing on Windows. This should be easy to fix—we've just missed it for a long time because it seems to be Windows-specific. Stay tuned.

**Comment by bengotow** [comment]
Hey! This has been fixed in 1.0.10.
