### ISSUE TITLE
Drafts disappeared

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#531]
##### What operating system are you using?
MacOS 10.13.2

##### What version of Mailspring are you using?
1.0.12

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I use Gmail with Mailspring

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I had about 4-5 drafts saved in Mailspring, now they are all gone.

Is there any way to recover these from a local folder or something like that? I have to be honest that basic reliability issues like this are making me question whether I can continue using Mailspring.

**Comment by bengotow** [comment]
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of the app. Feel free to bump this or re-open a new issue if you run in to this again.
