### ISSUE TITLE
Mailspring fails to build correctly with nodejs version 8.9.4

### ISSUE THREAD

**Issue by alecbcs** [Foundry376/Mailspring#532]
Hi Mailspring Team, 
I've been packaging mailspring from scratch for Solus (a Linux distro) and with the latest version of nodejs (8.9.4), npm fails to correctly download some of the assets required by Mailspring (1.0.12).

`npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-QFUCsAfzGcP0cXXER0UnMA8qta0= integrity checksum failed when using sha1: wanted sha1-QFUCsAfzGcP0cXXER0UnMA8qta0= but got sha512-zr6QQnzLt3Ja0t0XI8gws2kn7zV2p0l/D3kreNvS6hFZhVU5g+uY/30l42jbgt0XGcNBEmBDGJR71J692V92tA==. (260 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.`

This results in Mailspring failing to open upon installation with this error.

`Raven: 429 - Creation of this event was denied due to rate limiting`

Here is the link to the Bug report on Solus.
https://dev.solus-project.com/T5546

Is there any known work around for this? Thanks!

**Comment by bengotow** [comment]
Hey! What would we need to do to support Solus without a separate packaging process? Does the .snap release not work on Solus? (I try to heavily discourage people from downloading / putting their email passwords into unofficial builds of the app. I know you're distributing it as-is, but without trusted releases for the platform it'd be /very/ easy for someone to phish all your email passwords and then think it was Mailspring that screwed them over, which sucks.)

**Comment by alecbcs** [comment]
I briefly tried the snap when it was first released but, unfortunately because snap can not currently detect and use system fonts/themes I stopped using it because, while using mailspring my mouse cursor became a speck on my high dpi display. 
I might be wrong about this but I think that the error we are experiencing is a nodejs issue not being able to download the correct assets for mailspring. Just in case I'm wrong, are you not experiencing any errors when building the program on nodejs? (8.9.4) As long as nodejs is able get all the assets, I don't believe that we would need any separate packaging process. Thanks for your time.

**Comment by Logic-gate** [comment]
Hey,

This is still an issue; nylas started coughing blood yesterday and I needed a quick replacement. I swept through various solutions; snap worked, but it freezes a lot..and looks out of place in solus. I refrained from building from source and opted for the lazy yet workable solution of utilizing the .deb package. It works fine now, however it will yield issues on the long run. I do hope that this 'version' issue can be resolved as mailspring is the client of choice among early nylas supporters. 

As for my ugly--highly discouraged approach;

package.yml 

```
name       : mailspring
version    : 1.1.2
release    : 5
source     :
    - https://github.com/Foundry376/Mailspring/releases/download/1.1.2/mailspring-1.1.2-amd64.deb : 5d34ae89cf41bf48440aa9c05937ab8828bab78babbc71501bf3d987e4c86d0a
license    :
    - GPL-3.0
    - Distributable # mailsync
component  : network.mail
summary    : A beautiful, fast and maintained fork of Nylas Mail by one of the original authors.
description: |
    Leaving Nylas Mail? Mailspring is a new version by one of the original authors. It's faster, leaner, and shipping today! Mailspring replaces the JavaScript mailsync code in Nylas Mail with a new C++ sync engine based on Mailcore2. It uses roughly half the RAM and CPU of Nylas Mail and idles with almost zero "CPU Wakes", which translates to great battery life. A major overhaul of the package manager and dependency tree mean it launches faster too. You might not even notice it's an Electron app!
networking : yes
extract    : no
setup      : |
    ar x $sources/mailspring-${version}-amd64.deb
    tar xf data.tar.*
install    : |
    mkdir -p %installroot%
    cp -r usr %installroot%/
    cp %installroot%/usr/share/icons/hicolor/64x64/apps/mailspring.png /usr/share/pixmaps/mailspring.png

```

**Comment by bengotow** [comment]
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of Electron and/or snapcraft. Feel free to bump this or re-open a new issue if you run in to this again.
