### ISSUE TITLE
"libappindicator" dependency breaks RPM installation on openSUSE

### ISSUE THREAD

**Issue by geckolinux** [Foundry376/Mailspring#533]
Hi, unfortunately #306  prevents installation of Mailspring on openSUSE (Tumbleweed in my case). Tumbleweed has:
- https://software.opensuse.org/package/libappindicator1
- https://software.opensuse.org/package/libappindicator3-1

But there is no `libappindicator` package.

**Comment by ronisbr** [comment]
It is still happening in v1.2.1.

**Comment by qitar888** [comment]
still happening in 1.6.1

**Comment by TobiPeterG** [comment]
Hey, it works without; just ignore the depency, no problem here, Tumbleweed as well.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
