### ISSUE TITLE
Date in Different Language Than App

### ISSUE THREAD

**Issue by MrObvious** [Foundry376/Mailspring#541]
So...not sure if this is a feature enhancement or bug, but I'm running KUbuntu 17.10. I have my language set to Chinese. The program is in English, but the date is odd. For example check this reply header:

On 1月 17 2018, at 4:19 下午, ...

Possibly related to #226?

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—this is intended behavior (mostly because we're using locale-aware date and time formatting), and will probably make a lot more sense once we localize the rest of the app. Stay tuned!

**Comment by MrObvious** [comment]
Thanks Ben.

**Comment by MrObvious** [comment]
Ben, one question. Where does Mailspring pull it's localization information from and is there a way to manually override it for now?
