### ISSUE TITLE
How to set the Imap, Pop3 or Smtp via HTTP or SOCKS proxy?

### ISSUE THREAD

**Issue by pengcheng789** [Foundry376/Mailspring#543]
##### Are there any related issues?

No.

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.0.12

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

This is not a bug.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No.

Emm...  I just want to know how to set the HTTP proxy or SOCKS proxy in the mailspring.😅

**Comment by bengotow** [comment]
Mailspring does not support HTTP or SOCKS proxies. #235
