### ISSUE TITLE
[BUG] "less is more" theme "Subject" field style breaks when focused

### ISSUE THREAD

**Issue by danawoodman** [Foundry376/Mailspring#547]
##### Are there any related issues?

Not that I could find...

##### What operating system are you using?

Mac High Sierra

##### What version of Mailspring are you using?

Latest (pro)

##### Do you have any third-party plugins installed? If so, which ones?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

When drafting a new message using the "less is more" theme, a minor style quick shows up when focused on the "Subject field". It's width gets broken and goes 100% width instead of staying inline with the rest of the form, which just looks strange. Minor but I thought I'd point it out:

![](https://cl.ly/oxtE/Screen%20Shot%202018-01-19%20at%2010.35.43%20AM.png)

**Comment by danawoodman** [comment]
@bengotow thanks for the quick work on this! 👍

**Comment by bengotow** [comment]
Hey folks—the fix for this has been shipped in 1.1.2. The app will auto-update in the next few hours, or you can download the new version directly from https://getmailspring.com/download. Enjoy!

**Comment by danawoodman** [comment]
🤘🕺

Thanks!
