### ISSUE TITLE
Mailspring Theme

### ISSUE THREAD

**Issue by Aisyk** [Foundry376/Mailspring#548]
Hi,

I have some graphics problems with Mailspring.
Better for you to view it, i'm using Gnome-Shell and Arc Theme, it happens with Adawaita too.
[graphic UI](https://framapic.org/z8w3HdidO4ui/NS8a8haSesS6.png)
[graphic UI](https://framapic.org/BtdOCuBRdlBJ/I99DV4F1imxK.png)

Thanks for your work !

System : Ubuntu Gnome 16.04.3 LTS

**Comment by brw** [comment]
Duplicate of #495 (assuming you're using the Snap build).

**Comment by bengotow** [comment]
Hey! Thanks for marking this @brw, closing as a dup!
