### ISSUE TITLE
Mailspring not launching in Fedora 26

### ISSUE THREAD

**Issue by mthomos** [Foundry376/Mailspring#55]
I am using Fedora 26 and when i try to execute Mailspring  this message appears:
"We encountered a problem with your local email database. Error: /usr/share/mailspring/resources/app.asar.unpacked/mailsync.bin: error while loading shared libraries: libsasl2.so.2: cannot open shared object file: No such file or directory "
My installation includes cyrus-sasl-2 package.

**Comment by fearful-symmetry** [comment]
Ran Same problem, same OS:
```
ldd mailsync.bin                                                                                                                                                                  
	linux-vdso.so.1 (0x00007ffcccfdc000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007fb82b998000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb82b779000)
	libsasl2.so.2 => not found
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fb82b575000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fb82b25f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb82ae8e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb82bcab000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fb82ac1b000)
```
Found the package that provides that lib, then just had to symlink it:
```bash
ln -s /usr/lib64/libsasl2.so /usr/lib64/libsasl2.so.2
```

**Comment by mthomos** [comment]
I have the libsasl2.so.3 file, but when i symlink it, i have failure when i try to create a account

**Comment by bengotow** [comment]
Hey folks! Merging this in to #63 which should resolve this issue when it's closed.
