### ISSUE TITLE
Sync Error due to snoozed folder naming conventions while adding secureserver.net account

### ISSUE THREAD

**Issue by prasannshah** [Foundry376/Mailspring#551]
##### What operating system are you using?
MacOS

##### What version of Mailspring are you using?
1.0.11

this is the log

> 7629 [2018-01-22 14:08:23.698] [metadata] [info] Metadata delta stream starting...
> 7629 [2018-01-22 14:08:25.529] [background] [error] Could not create required Mailspring folder: [Mailspring]/Snoozed. ErrorCreate
> 7629 [2018-01-22 14:08:25.531] [background] [info] Syncing folder list...
> 7629 [2018-01-22 14:08:25.882] [background] [critical]
>  ***
>  *** Mailspring GenericException occurred during program execution:
>  *** {"debuginfo":"syncFoldersAndLabels - fetchAllFolders","key":"ErrorNonExistantFolder","retryable":false,"what":"std::exception"}
>  ***
> 
> 7629 [2018-01-22 14:08:25.882] [background] [critical]  *** Stack trace (line numbers are approximate):
>  *** in mailsync     SyncWorker::syncFoldersAndLabels()
>  *** in mailsync     SyncWorker::syncNow()
>  *** in mailsync     runBackgroundSyncWorker()
>  *** in mailsync     void* __1::__thread_proxy(void*)
>  *** 0x7fff773076c1  _pthread_body
>  *** 0x7fff7730756d  _pthread_body
>  *** 0x7fff77306c5d  thread_start
>  ***

possibly similar to [453](https://github.com/Foundry376/Mailspring/issues/453)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Trying to sync [secureserver.net](secureserver.net) account. This used to work in Nylas-n1.

Possible solution:
Most providers support '-'. N1 used to have `N1-snoozed`. Could have a similar name?

**Comment by bengotow** [comment]
hey! Thanks for reporting this - gonna merge this and #453 into #164 which is a similar issue, and get it fixed there.

**Comment by bengotow** [comment]
Hey @prasannshah—the fix for this has been shipped in 1.1.2. The app will auto-update in the next few hours, or you can download the new version directly from https://getmailspring.com/download. Enjoy!
