### ISSUE TITLE
unable to find the font mailspring used previously and I am unable to type after hitting backspace on the editor.

### ISSUE THREAD

**Issue by tuhinchakraborty** [Foundry376/Mailspring#554]
##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of Mailspring are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! Can you expand on the font issue? The fonts in Mailspring shouldn't have changed recently.

**Comment by tuhinchakraborty** [comment]
@bengotow one issue is if I open the compose window and hit the backspace couple of times, I can't type again. Second issue is if I have the in built dark theme on, the default font color is black and if I change it to white and if my recipient is using a light color theme on his/her mail client, the email cannot be seen. I don't believe it was an issue earlier.

**Comment by bengotow** [comment]
Hey thanks for the follow-up. The color issue and the backspace problem have both been resolved in separate tickets. Gonna close this!
