### ISSUE TITLE
Cmd-K no longer inserts a link in new composer

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#555]
##### Are there any related issues?

...

##### What operating system are you using?
MacOS 10.13.2

##### What version of Mailspring are you using?
1.1.0

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

New composer seems great, but Cmd-K went away as a way to insert a link for selected text. Please bring it back!

**Comment by bengotow** [comment]
Hey! Will fix this - looks like there are a handful of the composer shortcuts that need to be put back in place

**Comment by bengotow** [comment]
The fix for this has been shipped in 1.1.2. The app will auto-update in the next few hours, or you can download the new version directly from https://getmailspring.com/download. Enjoy!
