### ISSUE TITLE
Windows: When replying with shortcuts, focus is not in the text field

### ISSUE THREAD

**Issue by enoversum** [Foundry376/Mailspring#560]
With the current version (checked to make sure I have the latest update) on Windows, when replying to an e-mail through the two shortcuts ('A' or 'R') **after having clicked into the text of the received e-mail** (does not happen if you open it and then hit a shortcut), the focus in the composer is then not in the input field. 
This leads to a lot of colourful actions on my part, as I start typing and accidentally then perform various additional shortcuts like archiving and deleting. Also, sometimes it takes a considerable amount of time until the compose window opens, but not on all e-mails.

Steps to reproduce: 

1. Open an e-mail from the list with the three-column layout (e-mail text opens to the right).
2. Click somewhere into the body of the e-mail.
3. Hit 'A' or 'R' to reply.
4. Composer for e-mail opens, yellow background, no focus in text field.

**Comment by palefire19** [comment]
+1 on Mac

**Comment by victortrac** [comment]
+1 on windows. This is a regression with the new editor.

**Comment by bengotow** [comment]
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of the app. Feel free to bump this or re-open a new issue if you run in to this again.
