### ISSUE TITLE
Another small new composer bug: tab doesn't give focus to text window in certain circumstances

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#561]
##### What operating system are you using?
MacOS 10.13.2

##### What version of Mailspring are you using?
1.1.0

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Doubt it

##### Is the issue reproducible with a particular attachment, message, signature, etc?

1. Open an email
2. Forward it
3. Enter a recipient
4. Tab to subject
5. Tab again to text composer - doesn't give focus

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - I think the issue here was actually 8ae17eae12dffec9f6ceaa9339aba6c31c43e35a - can you see if this still happens for you in 1.1.2? Otherwise I'll mark it fixed when I ship the next update.

**Comment by palefire19** [comment]
1.1.2 looks like a great fix, but I don't think it's fixed this one. It's a very minor bug, if you follow my steps 1-5 above it's still consistently reproducible for me on 1.1.2

Thanks!

**Comment by bengotow** [comment]
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.
