### ISSUE TITLE
Better HiDPI support

### ISSUE THREAD

**Issue by gabaum10** [Foundry376/Mailspring#563]
Mailspring in HiDPI mode is pretty sketchy.  When using the snap, big swaths of the UI would just not render.  
![mailspring](https://user-images.githubusercontent.com/1561245/35336450-6f81034a-00e6-11e8-9510-182041683788.png)

After switching over to the .deb package, it all renders, but it's _tiny_.  Like microscopic.  I tried using the window -> zoom option to make things bigger, but no luck.  It doesn't seem to do anything.  I also tried to modify the config.json file as per the linked issue below, but that didn't seem to help either.

##### Are there any related issues?
https://github.com/Foundry376/Mailspring/issues/176 - that's not maintainable long term for the average user.  Plus, I couldn't get it to work.

##### What operating system are you using?
Pop! _os (from System76)

##### What version of Mailspring are you using?
1.1.0 - debian package.  The snap had all sorts of issues with HiDPI.

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No.  4k HiDPI screen is all that's necessary.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey—this should be fixed in the next release when Mailspring upgrades to Electron 1.8.x. Stay tuned.

**Comment by bengotow** [comment]
Gonna go ahead and close this now that 1.1.2 has shipped with Electron 1.8.x. If this still happens, let me know and I'll re-open the ticket!

**Comment by simonv3** [comment]
My issue here isn't that the text is tiny but that the mouse is suuuper small. I'm guessing that's still an electron issue though?

**Comment by Fahrenheit17** [comment]
The panel indicator icon is still super-tiny on Cinnamon with HiDPI...

**Comment by Chinney** [comment]
I have a 4k display on ubuntu. Icons won't scale appropriately and preference menu is bugged:

![mailspring_highdpi_2](https://user-images.githubusercontent.com/5702231/37099993-1945aef6-2222-11e8-89b2-b6b9dbfb14e1.png)
![mailspring_highdpi_1](https://user-images.githubusercontent.com/5702231/37099996-1b543cd0-2222-11e8-9ae4-c7274f2989c8.png)

**Comment by Erbengi** [comment]
This issue still persist even in Mailspring 1.3.0 installed from .deb package on Ubuntu 18.04:

![mailspring_bug](https://user-images.githubusercontent.com/31409742/42985999-20da17e2-8bf4-11e8-9a54-192b6230fac2.png)
![mailspring_bug2](https://user-images.githubusercontent.com/31409742/42986049-5df0ec8c-8bf4-11e8-94dc-9f16574592b8.png)

**Comment by petestanley** [comment]
Same issue on 1.6.3 but also noticed it's occurring with other electron apps so likely my system as apposed to MailSpring itself.
