### ISSUE TITLE
German special characters

### ISSUE THREAD

**Issue by sinnlosername** [Foundry376/Mailspring#564]
#### What operating system are you using?
Windows 10

#### What version of Mailspring are you using?
1.1.0

#### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

---
Mailspring is splitting german words at some german special characters like "äöüß". For example, if you write the german word "Höhle", Mailspring will split this word into 2 parts. "H" and "hle". The special character "ö" is ignored. This causes bugs with the spelling correction, as Mailspring is checking "H" and "hle" as two different words, instead of one word.

**Comment by bengotow** [comment]
Hey! Good catch - I'll get this fixed, there should be a small release going out in the next day or two.

**Comment by bengotow** [comment]
Hey @sinnlosername—the fix for this has been shipped in 1.1.2. The app will auto-update in the next few hours, or you can download the new version directly from https://getmailspring.com/download. Enjoy!
