### ISSUE TITLE
Version 1.1.0 is hogging Mac memory

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#566]
##### What operating system are you using?
MacOS 10.12.3

##### What version of Mailspring are you using?
1.1.0

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Doubt it

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Ever since version 1.1.0, Mailspring seems to be using a lot more system resources, especially memory. I'm noticing lags and unresponsiveness on Mailspring. On my Mac activity monitor, I'm seeing "Mailspring default" using 2.16GB of memory. Happy to provide any more info or logs that would be helpful.

**Comment by axfelix** [comment]
I can confirm -- I'm seeing close to 2GB used between memory and swap after having the app running for about a day on Linux.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this is interesting. Mailspring moved from Electron 1.7.8 to Electron 1.7.10, I'll check and see if anything changed there. (It's going to 1.8.x soon so that may fix the issue.)

Can you open Activity Monitor, and switch the view to `All Processes (Hierarchically)`, and post a picture like this? 

<img width="723" alt="image" src="https://user-images.githubusercontent.com/1037212/35400147-e7ae0182-01aa-11e8-9021-eabe28cd8220.png">

Would be interesting to know which child process is taking the most RAM.

**Comment by axfelix** [comment]
On htop (which is defeating my attempts to screenshot it clearly) it's "Mailspring default" by far. Not able to drill down to see any children of that...

**Comment by palefire19** [comment]
Here's mine. If helpful at all, yeah, seems like "Mailspring default" is the issue. In the attached screenshot it's gotten up to 700MB, lower than when I created this ticket but hopefully still illustrative.

<img width="544" alt="screen shot 2018-01-25 at 9 48 05 pm" src="https://user-images.githubusercontent.com/4412269/35406306-92fb0602-0219-11e8-8e09-a3bc2f8944e4.png">

**Comment by palefire19** [comment]
@bengotow Here's a screenshot from right now of "Mailspring default" taking up close to 2GB. I've had it open all day.

<img width="797" alt="screen shot 2018-01-30 at 6 30 04 pm" src="https://user-images.githubusercontent.com/4412269/35574734-a5a31396-05eb-11e8-98d0-bc308bf37366.png">

**Comment by orditeck** [comment]
Was using 1.5GB here, I closed it. I'll wait for a fix. I only have one brand new IMAP account...

**Comment by xtfer** [comment]
Im seeing 2.7GB in 1.5.2. I'm taking a snapshot as advised in #1211 and will forward.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
