### ISSUE TITLE
Windows client not opening

### ISSUE THREAD

**Issue by wulfalpha** [Foundry376/Mailspring#568]
##### Are there any related issues?

...

##### What operating system are you using?
...windows 10

##### What version of Mailspring are you using?
...
1.1.0
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
no
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
no
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
Mailspring kind of runs but wont open icon is missing from the system tray and it looks like nothing is running
--
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...
no

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - are you running any sort of antivirus software that might interfere with Mailspring? It's hard to say what's going on - you could try re-installing from getmailspring.com, or running it from a `cmd` prompt so you can see additional output that might be helpful.

**Comment by wulfalpha** [comment]
I'm using Windows defender I tried reinstalling it and it didn't help. Let me see if I can run it from command prompt

**Comment by wulfalpha** [comment]
I ran it from the CMD and it says nothing a blank button appears in the system tray that when I right click on it it says new mail properties and quit Mailspring but none of the buttons do anything. I check the task manager and the Mailspring process runs then closes itself every time i click it. I think i have to reinstall it to work but for some reason reinstalling isn't working.
![mailspring1](https://user-images.githubusercontent.com/16473924/35419694-a38cb998-01f6-11e8-8f5c-d00293386061.png)
![mailspring2](https://user-images.githubusercontent.com/16473924/35419697-a5b632c6-01f6-11e8-8624-9f0b8951bdea.png)

**Comment by wulfalpha** [comment]
Uninstalled and wiped app data nylus folder and reinstalled. It fixed the issue.
