### ISSUE TITLE
Sent email goes to trash folder!

### ISSUE THREAD

**Issue by b00f** [Foundry376/Mailspring#571]
I am using MailSpring 1.1.0 in Ubintu 16.04 LTS.
I just installed MailSpring. Today I sent an email to my colleague and but I couldn't find it on sent folder, So I sent it again. Sudden;y when I checked the trash folder I found my email there. check the screenshot here:
 
![screenshot from 2018-01-25 19-26-00](https://user-images.githubusercontent.com/8073510/35386410-edc5e5d8-0206-11e8-9e0b-bc101d3fd438.png)

**Comment by milesimarco** [comment]
Same problem here (fresh install on Windows 10 x64). Happened with all emails i sent today.

**Comment by b00f** [comment]
Any update?

**Comment by b00f** [comment]
@bengotow Do you have any idea what is going on here? Is there any fix for this issue?

**Comment by b00f** [comment]
Duplicated Bug #593
