### ISSUE TITLE
Within the snap, Mailspring cannot open folders / files on disk (View Mailsync Logs)

### ISSUE THREAD

**Issue by kkinder** [Foundry376/Mailspring#572]
When I attempt to view MailSpring's log file to see why it's having trouble syncing my Bridge account (see #429, but that's not directly related), nothing happens. I'm unable to locate MailSpring's logfile.

If I run MailSpring from a terminal, here's the output when I try to view log files:

```
Error org.freedesktop.DBus.Error.UnknownInterface: Object does not implement the interface
Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.SafeLauncher was not provided by any .service files
```

I googled around and I believe it may be caused by Snap packages' sandboxing, which prevents apps from accessing other apps' data (sort of like iOS or Android sandboxing, but on the desktop). Per an [ask Ubuntu thread](https://askubuntu.com/questions/831666/xdg-open-from-within-a-snap), I tried in installing `snapd-xdg-open` and edited my config file per the answer. Similar result:

```
Error org.freedesktop.DBus.Error.AccessDenied: Supplied URL scheme "" is not allowed
Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.SafeLauncher was not provided by any .service files
```

Still no dice. Can you tell me where MailSpring keeps its log files so I can look at them by hand?

This issue may also be related to #449

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.1.0-7563b09d

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
2 Gmail accounts, 1 ProtonMail Bridge account

**Comment by kkinder** [comment]
I also did try installing the dpkg file. While the menu option to view logs worked, I unfortunately lost my configuration. Not a huge deal, but kind of a bummer.

So it's definitely only a problem with the snap package.

**Comment by bengotow** [comment]
Hey! Was able to reproduce this - Mailspring /should/ be able to open a folder, but it seems like it's calling `xdg-open` with a file path (eg: empty URL scheme) and that isn't working. If you want to look manually, these files are in `/home/<you>/snap/mailspring/common`

**Comment by FedeVerges** [comment]
i have the same problem, i have 18.04 and it persist. i try install with snap but i can't run it.
i put "mailspring" in the terminal to run it, but doesn't work.

**Comment by bengotow** [comment]
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of Electron and/or snapcraft. Feel free to bump this or re-open a new issue if you run in to this again.
