### ISSUE TITLE
Message won't send because email address in to field are not recognized

### ISSUE THREAD

**Issue by brnold** [Foundry376/Mailspring#573]
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10 

##### What version of Mailspring are you using?
1.1.0-7563b09d

--

**Bug?**

When I try to reply or send a message, I get a message saying that "Send addressed to a name that does appear to be a recipient ("first line of my message after the first space"). <- It's actually the first line of my message after the first space. Sometimes I will delete then reenter the email address in the to field and the message will send, other times this won't work and I have to delete the draft and compose a new message. See screenshot, notice how "wes" is in my message body and it appears in the warning message. Also, when I deleted "wes" from my first line, my message sent.

##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Office365

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
![capture](https://user-images.githubusercontent.com/9080237/35397541-c14740d6-01bd-11e8-9337-96867e4aeb19.PNG)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - Mailspring is warning you because it thinks "Wes" might be the wrong name because the recipient is "Wesley". If you want, you can click "Send Anyway" to continue past the warning. I'll see if we can improve this in the future - we've been debating getting rid of this warning!

**Comment by brnold** [comment]
My Bad! Cool warning, keep it. Maybe just change the wording so it's clearer.
