### ISSUE TITLE
Undo while editing an email also undos previous mail actions (like deletes/archives)

### ISSUE THREAD

**Issue by victortrac** [Foundry376/Mailspring#577]
##### What operating system are you using?
Gnome-shell
Linux carbon 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux

##### What version of Mailspring are you using?
1.1.0.7563b09-1

##### Reproduction steps
1. Delete some emails
2. Click "respond" on an email, start typing. Undo a couple of times to see undo actions on both the editor window and the previous deletes.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - I'll get this fixed, looks like it was broken by the new composer UI.

**Comment by bengotow** [comment]
Hey @victortrac—the fix for this has been shipped in 1.1.2. The app will auto-update in the next few hours, or you can download the new version directly from https://getmailspring.com/download. Enjoy!
