### ISSUE TITLE
Downloading Update never ends

### ISSUE THREAD

**Issue by agurz** [Foundry376/Mailspring#58]
Hi @bengotow, my Mailspring setup is trying to update to 1.0.2 but it doesn't end. I have waited for 20 minutes by now. Maybe some cached data is preventing the new version to be downloaded?

<img width="306" alt="screen shot 2017-10-06 at 6 52 22 pm" src="https://user-images.githubusercontent.com/13837769/31299984-9b1c218a-aac7-11e7-8eda-f4659fd63232.png">

No clue on dev tools.

---

##### Are there any related issues?

No

##### What operating system are you using?
macOS Sierra 10.12.6

##### What version of Mailspring are you using?
1.0.1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

**Comment by agurz** [comment]
Forget about this. It just ended

**Comment by bengotow** [comment]
Hey! Glad it worked - super strange it took that long though, it must have failed the first time for some reason.
