### ISSUE TITLE
Can't download particular attached image

### ISSUE THREAD

**Issue by gmagic** [Foundry376/Mailspring#583]
##### Are there any related issues?

Didn't find.

##### What operating system are you using?
Fedora 27, Ubuntu 17.10, Windows

##### What version of Mailspring are you using?
1.1.0-7563b09d

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
I didn't install any third-party plugin.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Attached images

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
I can download only needed attachments one by one (not all) if they are not images, but i can't download particular image attachment, i just got "Download all" function in mail body.

**Comment by bengotow** [comment]
Good catch - in the next release I've updated this so it shows the "Download All" button (pictured below) at the bottom of the email, even if the attachments are all images that appear inline. 
<img width="242" alt="image" src="https://user-images.githubusercontent.com/1037212/35539878-31535f52-0508-11e8-9ef3-6764759cb14a.png">

**Comment by bengotow** [comment]
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.
