### ISSUE TITLE
sending empty message

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#591]
Windows 10 x64 -  Mailspring version 1.1.0 and 1.1.1

Unfortunately I don't know how to reproduce this bug, this problem occurs randomly and I have had the same problem several times and even today with the version 111.

1/ I write a new message: (now I put a text with a link)
2/ I send this message
3/ I note that it was sent correctly
4/ when I go to the folder "Send", this message is empty and my email address has been changed
(another email address of my accounts)

**Comment by bengotow** [comment]
Hey @franco27 thanks for reporting this - I'm trying to reproduce this now and I'll keep you posted.

**Comment by bengotow** [comment]
Hey @franco27, just to clarify, are you seeing that the message is sent correctly with the text and link, but the Sent folder does not show the content? Or is the message received by the recipient empty?

**Comment by franco27** [comment]
before , to create the new message: 
![2018-01-29 20_33_54](https://user-images.githubusercontent.com/31793920/35530414-4450a660-0534-11e8-8ba8-23b1f13bdcde.png)

I don't know if an empty message is sent; in the "Sent"folder, it is an empty message (the body of the message is empty, only the signature) 
the recipient's address is the same, the sender has changed (another email address of another email account appears instead) (the date of sending is correct)

In 110, I had set a default email address for editing (this is the sender address that was in the empty message), I removed it thinking it would solve but ... this problem was repeated later on ....
Currently, I have no default email address for new messages
(I noticed that I now have in the empty message, the sender address of the first email account in my settings)

**Comment by franco27** [comment]
I think I do not have this problem anymore with the version 112.
I will wait a few more days to see if this problem recurs with version 112.
Since its installation, I have not had this problem again.

**Comment by franco27** [comment]
I had this problem again with version 112.

I thought I found out how to reproduce this bug and this problem was repeated twice consecutively. (with the "Send" folder enabled, and clicking this folder on an email address to create a new message,)

At the third time, the new message was sent correctly.

**Comment by franco27** [comment]
![mailspring_ _no_subject_2018-02-04_21-09-40](https://user-images.githubusercontent.com/31793920/35781871-f14c7dc0-09ef-11e8-883e-cb15fe903c98.png)
![mailspring_ _no_subject_2018-02-04_21-08-44](https://user-images.githubusercontent.com/31793920/35781872-f17c5aea-09ef-11e8-871a-5387286f1230.png)

**Comment by r0x73** [comment]
Happened here as well on a gmail account.
When I tried to re-write and re-send it, a part of the mail was missing.
It seems that it sent the last auto-saved draft..

**Comment by emadow** [comment]
Also happening to me

**Comment by franco27** [comment]
since the installation of version 1.2.1, this situation has not happened again.  (with Windows 10)

**Comment by franco27** [comment]
And well not this is still not solved!
this problem has occurred again. 

I strongly believe that this problem is related to creating a new message with this menu  #2
![35530414-4450a660-0534-11e8-8ba8-23b1f13bdcde](https://user-images.githubusercontent.com/31793920/40256377-86ced01e-5aea-11e8-9d85-0335a466f60e.png)

It's been a long time since I've used this menu or this method to create a new message and before today this problem hadn't happened again.

**Comment by franco27** [comment]
The problem occurred again by clicking on an email address from the web browser.

1/ on a website, I clicked on an email address.
2/ the "new message" window has opened 
3/ I selected my email (there are several configured email accounts) and I wrote my message.
4/I clicked on "Send" and the message was sent ...

BUG :  in the "Send" folder, I see that it is an empty message that has been sent and my email address has been modified during sending ...  the subject of the message has been replaced by "No Subject" 
**I am forced to rewrite the message.**

![mailspring no subject 2018-05-21 11 39 57](https://user-images.githubusercontent.com/31793920/40301805-7fe92f24-5ced-11e8-81af-6d2b51450b16.png)

these sending problems persist and with the other problem, the "SMTP" error messages #795 which also persist, I am very annoyed by these repetitive problems.

I'm thinking of permanently abandoning your Mailspring software!

**Comment by hellonico** [comment]
I've had the same many times.
It really is random, and it's impossible to notice until the receiver tells you your mail was empty ;) hopefully with a sense of humor. 
I am on version: 1.4.1 and I've had this 3 times today, some other mails were sent correctly.

**Comment by phylophyl** [comment]
Some empty emails are sent when i check some old message, emails are sent to the recipient of these old messages.

**Comment by dzek69** [comment]
Just happend to me.
I have few accounts connected.

I wasn't receiving an expected response (I wanted to send it from "Account A") so I checked Sent folder just to see that I've sent empty message from wrong account ("Account B"). However - the signature was there, but it was signature from "Account C".

This is VERY VERY BAD. Especially that `Account C` is read-only for me, so to prevent sending from it by accident - I've set big red letters "DONT SEND, CHANGE ACCOUNT" as my signature for it.

So I've made myself look like an idiot in eyes of my client.

This is unacceptable behavior for something as important as mail client, really.

PS. #948 is not resolved as this is still happening.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
