### ISSUE TITLE
hostname in the link tracking URL

### ISSUE THREAD

**Issue by asim-vax** [Foundry376/Mailspring#597]
##### Are there any related issues?
Unable to find a related issue

##### What operating system are you using?
Ubuntu 16.04

##### What version of Mailspring are you using?
1.1.2
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

Why is the hostname used in link tracking? Would it be possible to use something else?

https://link.getmailspring.com/link/local-43e90e55-56d1@alex-xps-15-9550/19?redirect=http

Also as a non Pro user, is there a way to turn off link tracking, so my URLs appear just as normal links?

Thanks,

**Comment by sverhagen** [comment]
You may find this useful: [How do I turn off or disable link tracking / read receipts?](https://foundry376.zendesk.com/hc/en-us/articles/115002228092-How-do-I-turn-off-or-disable-link-tracking-read-receipts-).

**Comment by asim-vax** [comment]
thanks :)
