### ISSUE TITLE
build Mail spring code in windows 

### ISSUE THREAD

**Issue by satishgupta4s** [Foundry376/Mailspring#599]
we have downloaded Mail spring code from the  https://github.com/Foundry376/Mailspring url. when we try to build it produces error with some missing library. please provide step by step procedure to build it in windows .
Thank's in Advance.

**Comment by sverhagen** [comment]
Could you please show the error you're getting, that seems useful.

**Comment by satishgupta4s** [comment]
please find the file in attached form.

![error](https://user-images.githubusercontent.com/34708585/35608013-33f7649e-067d-11e8-97dc-2ae3b0edec3e.png)

**Comment by satishgupta4s** [comment]
this error occurred when i try to build.

**Comment by sverhagen** [comment]
My five cents, it'd probably be useful to do a `npm install` just from the command-line (don't think that's what we're seeing here). Are you owner of the folder this is in? Are you keeping this in deep paths with spaces in the folder names? (That may not be helpful.)

**Comment by satishgupta4s** [comment]
after solving the previous problem i m facing another problem. please see and suggest.
![error2](https://user-images.githubusercontent.com/34708585/35612652-85cb1006-068f-11e8-891e-42271a376c7d.png)

**Comment by bengotow** [comment]
Hey! Just in case you haven't seen it, the build procedure is documented here: https://github.com/Foundry376/Mailspring/blob/master/CONTRIBUTING.md#build-and-run-from-source. Make sure you run `npm install` and that no errors appear as it runs `npm run postinstall`, the last step.

**Comment by satishgupta4s** [comment]
Thank you. But i am following same concepts and again i am facing same error. Please resolve my problem asap.
![error](https://user-images.githubusercontent.com/34708585/35963049-7c7bd9ae-0cd9-11e8-9e00-4b4c76f3f3ad.png)

**Comment by sverhagen** [comment]
Even though you'd be running the user interface from source, there's still a closed-source binary. Mailspring is telling you it's missing on your system. When you run the command-line `npm install` it should resolve all NPM dependencies, and then, at the end, download the binary. As a general suggestion, it would probably be useful not to show screenshots of Windows applications here, instead rather copy/paste your (relevant) command-line output.

**Comment by satishgupta4s** [comment]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Jitendra Jain\AppData\Roamin
g\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jitendra Jain
\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gy
p.js" "rebuild"
gyp ERR! cwd C:\Users\Jitendra Jain\mailspring\app\node_modules\runas
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN mailspring@1.1.3 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-mac-notifier@0.0.13 (node_m
odules\node-mac-notifier):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for node-mac-
notifier@0.0.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","ar
ch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! runas@3.2.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jitendra Jain\AppData\Roaming\npm-cache\_logs\2018-02-12T0
5_50_00_751Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mailspring-root@0.0.1 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mailspring-root@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by sverhagen** [comment]
There's probably more useful information in that `C:\Users\Jitendra Jain\AppData\Roaming\npm-cache_logs\2018-02-12T05_50_00_751Z-debug.log` file, that's mentioned in there. I don't have good experiences, myself, with running these kinds of build tools on Windows, though. Even though it's Javascript, it sometimes wants to build native stuff, while assembling dependencies, and when that happens all the Windows stars must be perfectly aligned for it to work. But your mileage may vary. (And I'm also not an expert on Node and stuff; I'm just leeching this project, trying to be helpful.)
