### ISSUE TITLE
Critical : Reply to a long discussion freezes UI (force close) (Win10 x64)

### ISSUE THREAD

**Issue by benkuper** [Foundry376/Mailspring#601]
Last version 1.1.2-8ae17eae on Win10 x64
Tested on dark theme and light theme

-  Open mailSpring
- Select a long discussion (20-30 mails) with possibly attached documents
- Click reply
- App Freezes and windows asks to close it

It seems that this could be related to the lag problem, but i noticed a proportional lag depending on the size of the discussion and its content. Single emails reply are almost direct, while 10-15 mail discussions take a bit of time. They take even more if they have a lot of text or heavy attached documents.
There is a threshold when the app won't lag anymore but just freeze indefinitely.

**Comment by DmitryLoki** [comment]
Confirm that bug on Linux as well (Ubuntu 16.10)

**Comment by bengotow** [comment]
Hey! This will be fixed in the next release by 835ad95efc0cc69d9b8fb98f401853e8944bfbaf

**Comment by bengotow** [comment]
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.

**Comment by stuts88** [comment]
Still facing this issue
