### ISSUE TITLE
Wrong MimeType for linux

### ISSUE THREAD

**Issue by a2nt** [Foundry376/Mailspring#602]
Please, remove "text/plain" from /usr/share/applications/mailspring.desktop

It's not a text editor and it causes issues with some software like gnome-commander when it tries to open sass files with MailSpring.

Had to add a line to ~/.local/share/applications/mimeapps.list as temporary bugfix

**Comment by bengotow** [comment]
You got it - these seems like it was just left in there because it was the default in some example.

**Comment by bengotow** [comment]
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.
