### ISSUE TITLE
Unexpected mailsync errro / Gmail Windows account does not work anymore

### ISSUE THREAD

**Issue by Lyptik** [Foundry376/Mailspring#609]
Win10
Dark theme
4 mail synced (2 gmail, one imap, one outlook)

I have this error :

An unexpected mailsync error occurred (3221225477)

One gmail account works fine.
One other one just stopped working with mailspring telling me that it crashes and that crash report have been sent. Proporse me to reconnect through the browser, which works in the browser but does not change anything.

Deleting and adding account does not work, I cannot add my gmail account again.

Mailspring popup window says : An unexpected mailsync error occurred (3221225477)

Best

**Comment by bengotow** [comment]
Merging into #292
