### ISSUE TITLE
Deleting Message Takes a Few Goes

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#61]
##### Are there any related issues?
No.
...

##### What operating system are you using?
Windows 10
...

##### What version of Mailspring are you using?
1.0.1-ba1d (Latest)
...

**Bug?**
Deleting Email deletes then comes back to inbox in a few seconds. Have to delete a couple of takes for it to realise
##### Do you have any third-party plugins installed? If so, which ones?
No
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail (but don't have any others)
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Everything
...

**Comment by inceptorus** [comment]
I am experiencing this same issue. I am running KDE Neon (Ubuntu). The email provider is IMAP. Deleted messages reappear in the inbox.

**Comment by krishnaghatti** [comment]
Seeing this on mac os - 10.12.6 - Sierra.
Deleted mail re-appears then goes off after a while.

**Comment by mshallop** [comment]
Still seeing this on v.1.0.3 under Ubuntu 16.04 -- email isn't deleting on remote gmail host.

Clicking and deleting an email twice does remove it from the inbox pane but does not remove it from the gmail inbox as I have to go into gmail's inbox web-app to delete.   I know there's lag in sync'ing email, but this is for emails that I've deleted days previously.

I hope you get these issues worked-out!   Linux users need a great email client and it looks like this is the **best** current contender for uninstalling Thunderbird....

**Comment by bengotow** [comment]
Hey folks—this should be fixed in 1.0.11 (I think the changes for #364 will also fix this.) Stay tuned
