### ISSUE TITLE
Send without an attachment? - Prompt off Signature

### ISSUE THREAD

**Issue by datasage** [Foundry376/Mailspring#610]
My signature for work has the word attachments in it. So every time i try to send an email with that account. I am prompted to "Send without an attachment?".

I look for an option to disable the behavior, but didn't find one.

Ideally though I would prefer not to disable the behavior entirely, just have it ignore signature content.

##### Are there any related issues?
I did not find any. Unless my search fu needs work.

##### What operating system are you using?
macOS 10.13.3

##### What version of Mailspring are you using?
1.1.2

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
I don't use any other email tools at the moment. But i would think this can at least be disabled.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this is definitely a bug. I'll get this fixed.

**Comment by bengotow** [comment]
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.

**Comment by vmantovani** [comment]
Same issue here...Still happens....tried to download the version you said with no success.

Any update on this?
