### ISSUE TITLE
Pressing CTRL+z in composer window undo's both subject and body text

### ISSUE THREAD

**Issue by shemgp** [Foundry376/Mailspring#613]
# Bug
Pressing ctrl+z when typing in the composer's body undo's both the subject and the body text.

##### What operating system are you using?
Ubuntu 17.04

##### What version of Mailspring are you using?
1.1.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

**Comment by bengotow** [comment]
Good catch! Thanks for reporting this—it looks like `slate`, the new editor library we're using, isn't calling `stopPropagation` when it handles undo/redo. 👍

**Comment by bengotow** [comment]
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.
