### ISSUE TITLE
Ghost unread emails

### ISSUE THREAD

**Issue by louim** [Foundry376/Mailspring#616]
##### Are there any related issues?

Not that I know of.

##### What operating system are you using?

Mac OS 10.12.6 (16G1114)

##### What version of Mailspring are you using?

Version 1.1.1 (1.1.1)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Not really sure, has only happened with gmail, but that may be because it's my most used email

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I'm not sure how to reproduce exactly. Started to happen within the last 2 versions I think. The inbox show unread emails, even if there are none. I made a short video to better explain:

https://streamable.com/ubwuf

The only way to get rid of the unread mention is to trigger the whole thread as unread and then mark it as read again.

**Comment by bengotow** [comment]
Hey! Thanks for filing this and adding the video - I think this is the same as #247 so I'm merging it in there.
