### ISSUE TITLE
Feature Request: Add LinkedIn support to signature creator

### ISSUE THREAD

**Issue by ComputerTinker** [Foundry376/Mailspring#618]
The signature creator screen currently has support for a Website URL, Facebook URL, and Twitter URL.  I think adding support for a LinkedIn URL would also be beneficial.  Thanks!

**Comment by bengotow** [comment]
Hey! Unfortunately this isn't really possible because LinkedIn doesn't provide a public API for their profile photos. (https://stackoverflow.com/questions/6955647/getting-linkedin-profile-picture) Will keep an eye on this and implement it if we can in the future.

**Comment by cucumbur** [comment]
So are you hesitant to add in a auto oauth window for this? I get either side - nothing else in signature asks for authentication, but on the other hand users have already authenticated a bunch of emails so it wouldn't be too jarring.
https://developer.linkedin.com/docs/fields/basic-profile
https://github.com/auth0/passport-linkedin-oauth2/issues/41
https://developer.linkedin.com/docs/oauth2
(linking just for the sake of browsers)
I would be willing to contribute a feature like this if it was on the roadmap / wanted. I have only a few PRs to OSS projects but I work with JS professionally.

**Comment by ComputerTinker** [comment]
I'm unclear why Oauth is required. Isn't this just a form that auto-creates some HTML for the user, plus maybe a SVG LinkedIn graphic?

**Comment by pwr-srg** [comment]
Sorry guys to bother u, but I was wondering instead of adding a full integration with linkedin, with image retrieval etc, why can't we start adding just the linkedin field in the signature like the twitter and fb one?
So when it get filled up, a litttle linkedin logo appear at the bottom of the signature.

That would be just great!
Thx

**Comment by alevis** [comment]
@ComputerTinker @pwr-srg you could just replace the Facebook icon in the Raw HTML with a 26x26 gif icon of your choice.

**Comment by ComputerTinker** [comment]
@alevis, thanks for the suggestion. Unfortunately I had to give up using Mailspring as my mail client because I was having problems with attachments working correctly. Maybe in a few months I'll try again and see if all the kinks are worked out.

**Comment by bengotow** [comment]
Hey folks—I think there may have been some misunderstanding on my part on this issue. We can't show LinkedIn profile pictures in signatures, but we CAN show your Linkedin username and a link to your profile. I've added that in 1cdb6094de057a10d14233a69dfd4900b8dbbf9a.

**Comment by bengotow** [comment]
Hey! This has been fixed in 1.6.0 which shipped today. The app should auto-update, but you can also get the new version manually from https://getmailspring.com/download. Thanks - enjoy the app!
