### ISSUE TITLE
when i build Mailspring project it  produces error

### ISSUE THREAD

**Issue by satishgupta4s** [Foundry376/Mailspring#619]
we followed steps given below

1. download the code 
2. install node.js
3. npm-electron install
4. run with visual code 
5. Run Task-> npm- start

it produces error which is attached form.  please help
![error1](https://user-images.githubusercontent.com/34708585/35734961-041ae408-0849-11e8-9707-99a69aa3df71.png)

**Comment by bengotow** [comment]
Hmm, can you run `npm install` and the `npm run postinstall` script? (I'm not sure what npm-electron is, but you shouldn't need it.) `postinstall` should download and install the mailsync executable or log an error to your terminal.

**Comment by satishgupta4s** [comment]
I'm using window 7 . Can i download  postinstall and install the mailsync executable ( mailsync.tar.gz ) in window 7.

**Comment by bengotow** [comment]
Yes

**Comment by satishgupta4s** [comment]
Error in application.es6 file when run task and npm-start in visual code .  
How to solve this type of error.
![img](https://user-images.githubusercontent.com/34708585/35841303-44e869c6-0b21-11e8-8a2d-48d1d7b250e2.png)

**Comment by satishgupta4s** [comment]
-->Cannot connect to runtime via 'legacy' protocol; try to use 'inspector' protocol.
 
 --> Mailspring-master\Mailspring-master/node_modules/.bin/electron.CMD' --nolazy --debug-
       brk=36992 main.js 
 
-->  Cannot find module 'electron-spellchecker'
  -->Error: Cannot find module 'better-sqlite3'

Please solve these errors.

**Comment by satishgupta4s** [comment]
In Linux , i am facing same problem .
![centosdata-2018-03-13-15-41-58](https://user-images.githubusercontent.com/34708585/37335948-e9929fe4-26d5-11e8-94da-918801564747.png)

**Comment by bengotow** [comment]
Hey folks—going to close this due to inactivity. I think the problem here is that the OP is installing Mailspring without running the npm postinstall script. It /should/ be run automatically if you just cd into the base directory of the git repo and do `npm install`. Just watch the output to make sure it downloads the mailsync binary. If it doesn't running `npm run postinstall` manually should do it.
