### ISSUE TITLE
Tray icon in snap version is too big

### ISSUE THREAD

**Issue by Void97** [Foundry376/Mailspring#621]
Hi,
I'm running Manjaro KDE 17.1.3 and I noticed that the tray icon of Mailspring snap version is too big:
![screenshot_20180202_150137](https://user-images.githubusercontent.com/15859553/35737095-a2de1606-082a-11e8-996f-5e8f1a3db3e4.png)
whereas tray icon of Mailspring AUR package looks normal:
![screenshot_20180202_150806](https://user-images.githubusercontent.com/15859553/35737179-f581865e-082a-11e8-8c5b-a11864ce3d56.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - I wonder if Mailspring is unable to determine the density of your screen when running in the snap, or if the folks that packaged the AUR scaled down the image in their version. On Linux the system tray varies in height so we use a big image and assume the various system trays will scale it down, but it seems KDE doesn't. If anyone wants to do a bit more research on this I'd really appreciate it!

**Comment by bengotow** [comment]
Hey! So this should be fixed in 1.1.3 by 79a0f57916171fbc08857b6fd768633e14cf5008. Enjoy!

**Comment by Void97** [comment]
Yep, now it's fixed. Thank you!

**Comment by shroudedcode** [comment]
This only improved the icon for Linux trays that (for whatever reason) don't scale their icons. On elementary OS (which uses [`wingpanel`](https://github.com/elementary/wingpanel)) the new icon is too small and looks really weird.

*Before:* ![](https://user-images.githubusercontent.com/29176678/36001574-fb0dc85c-0d26-11e8-8b82-177aa5e6c3a1.png)
*After:* ![](https://user-images.githubusercontent.com/29176678/36001545-da6d199a-0d26-11e8-95d7-d490876c7f73.png)

**Comment by bengotow** [comment]
Hey thanks for the feedback @shroudedcode — I think we can make the image 48x48 pixels and let the tray manager downsize it. I wonder if `Manjaro KDE` will downsize the image if it's large (48px), but somehow 28px (the old size that was causing the problem) wasn't considered big enough to hit a threshold where it starts downsizing, giving us that weird clipped appearance?
