### ISSUE TITLE
[Bug] Deleted e-mails still appearing on other devices (intermittently)

### ISSUE THREAD

**Issue by sverhagen** [Foundry376/Mailspring#624]
While deleting e-mails, not nearly all of them get deleted across devices.
Steps to reproduce:
1. Select an e-mail in the Inbox
2. Press the `[Delete]`
3. Observe that the e-mail does not appear in the Inbox anymore
4. Observe the e-mail on other devices (i.e. OWA, Android's "Email" application)

Expected result:
- The e-mail does not appear on these devices anymore

Actual result:
- The e-mail does still appear on these devices (a significant portion of the time)

This happens for a significant portion of the e-mails that I delete in this way, though not all of them. It is unclear what the discriminator is.

##### Are there any related issues?
Couldn't find.

##### What operating system are you using?
Ubuntu 17.10. (Seen this on two separate such computers.)

##### What version of Mailspring are you using?
1.1.2-8ae17eae.

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Maybe. So far observed on Microsoft Exchange via IMAP. Not been able to observe on GMail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
This does not appear to be related to attachments. Other than that the pattern is unclear.

**Comment by sverhagen** [comment]
This problem seems broader than reported (by me -- although I may have seen the broader version being discussed on Slack). It's just not moving any mail between folders. Let's say I drag an e-mail to my custom folder "Finance", I can go to that folder and see the e-mail there _in Mailspring_, but other clients still have the e-mail where it used to be (i.e. in the Inbox).

**Comment by bengotow** [comment]
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of the app. Feel free to bump this or re-open a new issue if you run in to this again.
