### ISSUE TITLE
TypeError in Preview Pane 

### ISSUE THREAD

**Issue by sam-wright** [Foundry376/Mailspring#626]
##### Are there any related issues?

Possibly related or similar to #615
##### What operating system are you using?
Ubuntu 17.10
##### What version of Mailspring are you using?
Version1.1.2-8ae17eae (installed via snap)
--

**Bug?**
    TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.extname (path.js:1452:5)
    at Object.shouldDisplayAsImage (/src/flux/models/utils.es6:170:22)
    at files.filter.f (/internal_packages/attachments/lib/message-attachments.jsx:79:52)
    at Array.filter (native)
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
##### Is the issue reproducible with a particular attachment, message, signature, etc?

![screenshot from 2018-02-02 13-48-25](https://user-images.githubusercontent.com/1241069/35754400-8d1f35ca-0820-11e8-97f4-4e2c753ebb14.png)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No

**Comment by MiBengtsson** [comment]
Same problem on Fedora 24 and Windows 10. In my case, the problematic emails are Google calendar invitations sent before Jan 18, 2018. I tried 4-5 such emails from different people, as well as 2-3 newer, where the more recent invitations worked fine.

**Comment by bengotow** [comment]
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.

**Comment by InnocentPuff** [comment]
I have version 1.1.4 on Windows 10 and I still see this bug.

**Comment by InnocentPuff** [comment]
![error](https://user-images.githubusercontent.com/33402306/36490358-007a1a86-1720-11e8-9aff-331ca1490cb1.PNG)
