### ISSUE TITLE
Close, minimize, fullscreen icons not showing on Arch

### ISSUE THREAD

**Issue by jnylen** [Foundry376/Mailspring#627]
Basically the icons on arch for mailspring isn't showing on hover and they somehow isn't round at hover either.

![image](https://user-images.githubusercontent.com/3946116/35755946-99459648-0869-11e8-9d1c-395f0174cf48.png)

**Comment by bengotow** [comment]
That's... super weird. I'll see if I can reproduce this, seems like a low-hanging bug.

**Comment by bengotow** [comment]
Edit: I think this is a problem with a non-standard theme you're using? The icons actually don't appear this color anymore on Linux except in the built-in "Darkside" and "Less is More" themes, and in that case they're hardcoded to be a small rectangular shape. It might be that this theme needs to be updated?

**Comment by jnylen** [comment]
@bengotow,
This is with multiple icon themes.
Haven't found any theme that has the icons in there.
Tried: Deepin, Numix, Papirus, Sea.

**Comment by jnylen** [comment]
@bengotow still on going with 1.1.4.

**Comment by bengotow** [comment]
Merging in to #1104
