### ISSUE TITLE
Bug: Mailspring folder creating again

### ISSUE THREAD

**Issue by owner** [Foundry376/Mailspring#632]
If delete a Mailspring folder in app, after reload/another settings -> folder again created.

**Comment by bengotow** [comment]
Hey—yep Mailspring requires this folder. If you delete it and run Mailspring again, it will create it again. Basically just needs somewhere to keep Snoozed emails.

**Comment by SoftalkCS** [comment]
I have removed Mailspring yet the folders still keep returning after delete on any computer connecting to the Imap account

**Comment by nortexoid** [comment]
Same issue as SofttalkCS. If I remove mailspring and the folder using another mail client, it magically reappears. How is that possible?

**Comment by tscholiadis** [comment]
Because @bengotow mentioned, it is a REQUIRED folder in order for the "Snooze" functionality to work. Without it Mailspring would not work fully, so the software recreates it.

**Comment by makitsune** [comment]
What, I don't understand? Why can't I turn off "snoozed emails"? I don't even snooze emails whatever that means... Why not let me assign it to another folder? It's really annoying and I really love this mail client.

**Comment by ckeck** [comment]
Would love the option to disable the "snoozed email" functionality as well and get rid of the "Mailspring" folder entirely.

**Comment by CyberBlaed** [comment]
I second this motion, 

either enable the ability to disable snooze email function, or when the mailspring folder is deleted, it stays deleted.

**Comment by 1bardesign** [comment]
+1, especially "silently" adding a new folder that I cant remove feels quite hostile for such an otherwise "nice" client.
