### ISSUE TITLE
Introduce a cheaper Pro plan for business and add a silent installer for multiuser deployments

### ISSUE THREAD

**Issue by ogwh** [Foundry376/Mailspring#635]
There isn't an easy way to just send this to you via the website so I'm filing it here.

I love the app and want to use it for business purposes in the future (either myself or clients) as a replacement for Outlook. To be competitive though it needs to be cheaper if customers are buying multiple licenses. The competition (Gmail, Office 365, Zoho etc) are cheaper and they also offer hosting and a full office suite. Office 365 is a house of cards and not worth the hardware it's hosted on but that's another story.

It also needs a calendar and contacts manager really. The Gmail permissions list those but I can't find it in the UI.

Anyway best of luck the project/company, huge fan.

**Comment by bengotow** [comment]
Hey! Thanks for the feedback - Mailspring doesn't compete with hosted services like Gmail, etc., it actually competes with things like Boomerang for Gmail and Gmelius that do read receipts, link tracking, templates, etc. The user base we're after are mostly sales / business people who already pay $10+ / mo on these sort of email add-ons and can do it cheaper from Mailspring. Thanks for using the app!
