### ISSUE TITLE
Minor reading bug - collapse email in thread

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#636]
##### Are there any related issues?

Don't think so

##### What operating system are you using?
10.13.3

##### What version of Mailspring are you using?
1.1.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Minor bug - hopefully easy to fix.

1. Open a multi-thread email for reading
2. Expand one email
3. Click the small gray arrow next to sender to open up details
4. Now try to collapse email - can't do it until collapse gray arrow first - maybe that's intentional but it seems like an extra / unnecessary step?

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
