### ISSUE TITLE
Sometimes it's impossible to type an email

### ISSUE THREAD

**Issue by Ads20000** [Foundry376/Mailspring#638]
##### Are there any related issues?

Not as far as I can see

##### What operating system are you using?
Ubuntu 17.10 (Linux 4.13.0-32-generic)

##### What version of Mailspring are you using?
Mailspring snap 1.1.2 (140) on `core` 16-2.31~rc2 (3978, in `candidate`)
The bug applies also to 1.1.2 (140) on `core` 16-2.30 (3887, in `stable`)
The bug applies also to 1.1.2 (159, in `edge`) on `core` 16-2.30 (3887)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Don't think so

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Don't think so. But have a screenshot anyway!
![screenshot from 2018-02-04 10-55-00](https://user-images.githubusercontent.com/3178485/35776973-e65ff114-099d-11e8-95dd-d2019bd31fac.png)
See the dashes in the message box, for some reason they stop me from typing a message.
It sometimes takes a few attempts to reproduce, but what I do to reproduce it is to click the new message button, then type a contact and click their name when it comes up, then click the subject field and type a subject in, then click the content box. Sometimes I get the dashes come up which stop me typing a message, sometimes not.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
This isn't a feature request

**Comment by bengotow** [comment]
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of the app. Feel free to bump this or re-open a new issue if you run in to this again.

**Comment by sean-melko** [comment]
Bumping this. It can be fixed by switching the "from" email back and forth until it decided to cooperate.
