### ISSUE TITLE
Minor composer bug - ability to edit a hyperlink after it's been inserted

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#639]
##### What operating system are you using?
MacOS 10.13.3

##### What version of Mailspring are you using?
1.1.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No - composer

##### Is the issue reproducible with a particular attachment, message, signature, etc?

After a hyperlink has been inserted, editing either the underlying link or the visible text becomes very difficult.

I'd suggest three things:
- Ability to place a cursor in that text to edit it
- Clicking on the link shouldn't actually open the link in your browser
- The link editor should open up when the cursor is in linked text (similar to Gmail's implementation)

**Comment by bengotow** [comment]
Hey folks—this has been fixed in 1.1.5 which shipped yesterday. You can download the update from https://getmailspring.com/download or choose "Check for Updates" within the app to install it. Enjoy!
