### ISSUE TITLE
Attempting to reset Email cache results in an error

### ISSUE THREAD

**Issue by kometchtech** [Foundry376/Mailspring#64]
##### Are there any related issues?

...
https://github.com/Foundry376/Mailspring/issues/21#issuecomment-334872924
In connection with this, an error occurred when trying to delete cache.
##### What operating system are you using?
...
Windows10 Pro 1703
##### What version of Mailspring are you using?
...
1.0.2-4eab3f85
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
no
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
Gmail
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
![reset](https://user-images.githubusercontent.com/5137077/31304492-18efa09c-ab5d-11e7-95c4-321a215830a0.JPG)
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! It's been a few years and there haven't been any more reports of this issue so I'm going to close this as probably-fixed. Feel free to bump or create a new issue referencing this one if you encounter this again!
