### ISSUE TITLE
Error message when opening meeting request from search

### ISSUE THREAD

**Issue by gottlike** [Foundry376/Mailspring#640]
##### Are there any related issues?
Didn't find any.

##### What operating system are you using?
OS X

##### What version of Mailspring are you using?
1.1.2

--

**Bug**
##### Do you have any third-party plugins installed? If so, which ones?
Nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Nope

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I see the following error message when trying to open a meeting invitation from the search results page:

![screen shot 2018-02-05 at 12 26 30](https://user-images.githubusercontent.com/278766/35802905-323e29a0-0a72-11e8-9c67-a0018ba05456.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this has actually been fixed in the latest release that just shipped today (v1.1.3). You can download the update by choosing Mailspring > Check for Updates from the menu. Enjoy!

**Comment by bengotow** [comment]
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.
