### ISSUE TITLE
Copied text appears as white font for receivers

### ISSUE THREAD

**Issue by pat-s** [Foundry376/Mailspring#641]
I am using the [Adapta Dark theme](https://github.com/dennisotugo/Mailspring-Adapta-Theme) from  @dennisotugo.

Whenever I write an email and copy text from an old mail, the text appears in a white color for all receivers. In Mailspring everything looks fine for the sender.

If the receivers use a email client with a white theme, the email text is not visible then (white on white).

However, when I type new text in the composer instead of pasting text, it will be correctly converted and appears as black text on white background for the receivers.

(Idk if that is an theme or source problem that's why I also pinged @dennisotugo)

**Comment by dennisotugo** [comment]
Definitely not a theme problem. I do not think theming can actually affect what the receiver sees nor can it affect email conversions in the email? @bengotow

**Comment by pat-s** [comment]
Can you reproduce the issue @dennisotugo?

What makes me think that it maybe related to a theme problem is 

1. other users would have reported it already? Guess everyone copy/pastes email stuff regulary.
2. Adapta theme has a white font color due to the white background which seems to stay during sending and then appears as white for the receivers?

**Comment by dennisotugo** [comment]
@pat-s what you described has nothing to do with the theme. The theme does not affect the receiver nor does it affect how your sent emails are styled.  Also, I don't think by copying email that it will copy the styling of the UX. It will just copy the styling of the HTML email that the person sent afaik. The theme was based on Nylas with a little compatibility for Mailspring but I just rebased it now for Mailspring 100%.

**Comment by pat-s** [comment]
Receivers do not use mailspring (it was verified via Webmail and Thunderbird).

I am curious what the reason might be and why no one else reported this yet. 
This lets me assume that it is at least OS specific.
Could it inherit from system themes?
Happy to provide useful information. I'm on Kubuntu 16.04.

**Comment by bengotow** [comment]
Hey folks—so this is a bit of an interesting one. We intentionally preserve font colors when you paste in the composer so you can paste colored text, but this can definitely lead to sending emails with white / light colored text.

I think the correct solution is probably to make it so that when you copy the HTML from the previous email the font color is not included in the HTML. Will see if we can fix this.

In the meantime, the best solution I can offer is either 1) pasting as plain text instead of as HTML using the Ctrl-Shift-V hotkey / menu item, or 2) pasting and then clearing the text color by changing it to "black / default" in the color picker.

**Comment by pat-s** [comment]
@bengotow Did you address this issue in the meantime?

**Comment by monkeydri** [comment]
I have the same problem, using the dark theme.

workaround I use is to right click and "paste and match style" instead of doing a normal paste.

Mailspring v.1.4.0-549b7968 but I had this behaviour from the beginning.
Ubuntu 18.04 (on xorg) so it might be OS specific.

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!
