### ISSUE TITLE
Improve Visibility Versatility of Text Color Picker in Format Bar

### ISSUE THREAD

**Issue by seesemichaelj** [Foundry376/Mailspring#645]
##### Are there any related issues?
Couldn't see any

##### What operating system are you using?
elementary OS 0.4.1 Loki; this is probably the same for all OS's

##### What version of Mailspring are you using?
1.1.2

--

This is probably more of a feature request than a bug. The color swatch picker doesn't have a border around it; depending on the color selected (and/or theme behind it?), it can be hard to see. Here is white selected (Darkside theme):

![image](https://user-images.githubusercontent.com/549323/35837032-85c621e2-0ab1-11e8-829c-81142ebaf1b7.png)

It would be nice if there was a border something to indicate it's selectable/changable (if those aren't words, they are now) when it's difficult to see it's there.

I'm cool if the answer is "won't fix" as this is definitely an opinion thing.

For comparison, Gmail uses an A underlined by the color swatch (which I think is a pretty popular way to visualize this):
![image](https://user-images.githubusercontent.com/549323/35837091-ec918f10-0ab1-11e8-9375-d5ff356ec4e6.png)

**Comment by bengotow** [comment]
Oh I definitely like the Gmail approach - at the very least, we should put a border around that. Will see if I can fix this.
