### ISSUE TITLE
How do I uninstall a plugin?

### ISSUE THREAD

**Issue by smacking** [Foundry376/Mailspring#649]
##### What operating system are you using?
MacOS High Sierra 10.13.2 (17C205)

##### What version of Mailspring are you using?
Version 1.1.2 (1.1.2)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
I installed Mailspring avatars https://github.com/emadow/mailspring-avatars and the avatars don't show up.

Just stay like this: 
<img width="519" alt="screen shot 2018-02-06 at 12 58 46" src="https://user-images.githubusercontent.com/4571864/35860851-7f504ca2-0b3d-11e8-8db8-0c4a1df9d58a.png">

So how can I disable the plugin?

**Comment by bengotow** [comment]
Hey—you'll find the plugin at `~/Library/Application Support/Mailspring/packages` - just remove it from there and you're good to go. We'll be adding a package manager soon, gonna merge this in to #package

**Comment by smacking** [comment]
Done! Thanks!

**Comment by eyaskd** [comment]
how can i remove it from windows 11 ?

**Comment by weslyalfred** [comment]
> ¿Cómo puedo eliminarlo de Windows 11?

C:\Users\-----\AppData\Roaming\Mailspring\packages

**Comment by weslyalfred** [comment]
> ¿Cómo puedo eliminarlo de Windows 11?

The path is C:\Users\"youruser"\AppData\Roaming\Mailspring\packages

**Comment by aronkvh** [comment]
on Linux it's `~/.config/Mailspring/packages/`

**Comment by franc-in-action** [comment]
Hey guys on Windows 10 go to %appdata%/mailspring/packages

From here you can easily delete any theme or plugin you’ve installed
