### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#65]
##### Are there any related issues?
No
...

##### What operating system are you using?
Windows 10
...

##### What version of Mailspring are you using?
1.0.1-ba1d
...

--

**Bug?**
No "Check for Update" button (and it didn't find anything previously)
So downloaded installer, and installed. Got this error log:
http://textuploader.com/d4tzg

And it seemed to uninstall.
Reinstalled, and it kept previous settings and updated....

**Comment by bengotow** [comment]
Hey @Modelmat — it looks like when you ran the MailspringSetup.exe installer, a copy of Mailspring was actually still running. I'll see if we can make it check for that in the future.
