### ISSUE TITLE
[FEATURE REQUEST] click to tray icon shall toggle app window

### ISSUE THREAD

**Issue by a2nt** [Foundry376/Mailspring#650]
Click to tray icon shows app window, but if window is shown click to tray icon shall hide it

**Comment by bengotow** [comment]
This is a neat idea - the code for this would need to go along with the existing code here: https://github.com/Foundry376/Mailspring/blame/master/app/src/browser/system-tray-manager.es6#L81

**Comment by bengotow** [comment]
This is shipping in the next release—thanks @carlosjdelgado! 🎉

**Comment by bengotow** [comment]
This feature has shipped in 1.2.2 — the app should auto-update if you're using the Snap, or you can download the latest deb / rpm package from getmailspring.com. Enjoy the update!
