### ISSUE TITLE
Delete emails not working for filtered emails

### ISSUE THREAD

**Issue by sathiz1993** [Foundry376/Mailspring#651]
##### What operating system are you using?
Linux MInt 18.3

##### What version of Mailspring are you using?
1.1.2-8ae17eae

**Bug?**
I filter the emails based on particular sender and I try to delete the all filtered emails by selecting (nearly 70). After deletion , It displays "moved 70 emails to thrash" and the filtered emails still appears in the window.

**Comment by gmagic** [comment]
Confirm this. Placed such issue several days ago.

**Comment by bengotow** [comment]
This is a dup of #594
