### ISSUE TITLE
[Feature Request] Stop displaying open / link notifications when a message is no longer important

### ISSUE THREAD

**Issue by nmolinski** [Foundry376/Mailspring#652]
##### Are there any related issues?

NO

##### What operating system are you using?
LINUX
##### What version of Mailspring are you using?
1.1.2
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No need for attachment

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No

I need to have a way to stop tracking emails. Continually my email recipients keep opening already read emails and I get a notification about it every 5 mins.

I no longer need to continue the conversation with these people but need the emails for my records. Even archiving the emails does not solve the problem.

**Comment by bengotow** [comment]
Hey! I've added a new setting under Preferences > General > Notifications that allows you to turn off repeated notifications - so you only get one link click or open notification for each recipient. (If they open the email again, you don't get another notification.) Hope that helps! The release will ship in the next few days.

**Comment by nmolinski** [comment]
You are the boss!


On Mar 26 2018, at 5:47 pm, Ben Gotow <notifications@github.com> wrote:

Hey! I've added a new setting under Preferences > General > Notifications that allows you to turn off repeated notifications - so you only get one link click or open notification for each recipient. (If they open the email again, you don't get another notification.) Hope that helps! The release will ship in the next few days.
