### ISSUE TITLE
[BUG] Compose New Message button is slow

### ISSUE THREAD

**Issue by a2nt** [Foundry376/Mailspring#654]
Button to compose new message is slow because when u click on it the first thing it does is syncing mailbox. If u have slow internet connection u will need to wait for a while until new message window will be opened 
![screenshot from 2018-02-07 10-02-29](https://user-images.githubusercontent.com/672794/35896320-33c9489a-0bee-11e8-8c98-b2559ae7a043.png)

**Comment by JunnanZ** [comment]
Can confirm this in Mailspring 1.1.3, Arch Linux.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
