### ISSUE TITLE
'paste without formatting' no longer available

### ISSUE THREAD

**Issue by knireis** [Foundry376/Mailspring#655]
From version 1.1.2 the 'paste without formatting' is no longer available. 
Could that be restored?

I'm using the .deb version on Linux Mint. No third party plugins.

**Comment by bengotow** [comment]
Huh - that's odd... is it just not visible in the menu, or does it not work at all (via the Ctrl+Shift+V shrotcut?) It still appears on Mac for me.

**Comment by palefire19** [comment]
For me the keyboard shortcut still works but it's absent from the context menu.

**Comment by bengotow** [comment]
Ahh interesting - it was available on right-click before? I'll get that added back in.

**Comment by bengotow** [comment]
Hey! Was able to reproduce this one tonight and it'll be fixed in the 1.2.1 patch release tomorrow. Stay tuned!

**Comment by bengotow** [comment]
This should be addressed in 6340629d6dbdda9d5bce3e3ca43fbc9defb68850

**Comment by bengotow** [comment]
Hey folks! Sorry I never closed this ticket — this shipped in 1.2.1. Thanks to everyone for reporting this and submitting feedback.
