### ISSUE TITLE
[feature] Toggle notifications based on account

### ISSUE THREAD

**Issue by davidsharp** [Foundry376/Mailspring#656]
I use Mailspring at work for my work email account, and recently added my personal email too.

I would like to be able to turn off the notifications for my personal email and only receive notifications for my work email account. Therefore, the ability to turn off notifications for my personal email would be ideal.

**Comment by bengotow** [comment]
Merging this in to #360 since I think it encompasses this. Will rename that one to be a bit of a better match.
