### ISSUE TITLE
Certificate error on SMTP server only

### ISSUE THREAD

**Issue by etique57** [Foundry376/Mailspring#66]
When setting up my account, I have a certificate error on the SMTP server side.

I'm using the same server (and hence the same certificates) for both IMAP & SMTP, and I have no issue on Thunderbird.

I need to check the "Allow unsecure SSL" check box (on SMTP only) to go past the error.

##### Are there any related issues?
maybe #62

##### What operating system are you using?
Ubuntu Artful

##### What version of Mailspring are you using?
1.0.2
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP/SMTP

##### Is the issue reproducible with a particular attachment, message, signature, etc?
N/A

**Comment by bengotow** [comment]
Hey folks—I /think/ this is related to https://github.com/Foundry376/Mailspring/issues/63. We may want to ship that first and see if this issue is resolved.
