### ISSUE TITLE
Weird requests to apple.com

### ISSUE THREAD

**Issue by koxu1996** [Foundry376/Mailspring#660]
##### Are there any related issues?

No

##### What operating system are you using?

Arch Linux x64

##### What version of Mailspring are you using?

1.0.12-cf081332

--

While sniffing my computer traffic, I noticed weird requests to _http://captive.apple.com_ every 30 seconds:

```
GET /hotspot-detect.html HTTP/1.1
user-agent: CaptiveNetworkSupport/1.0 wispr
Accept-Encoding: gzip, deflate
Host: captive.apple.com
Connection: close
```
I found that Mailspring is making it, but I don't have apple device. Could you tell me what is the reason of this?

**Comment by bengotow** [comment]
Hey! Yep—these requests are Mailspring using `is-online` to verify that the app has a valid network connection: https://github.com/sindresorhus/is-online

**Comment by Cediddi** [comment]
I think sending constant heartbeats to apple servers is something I wouldn't want my computer to do, and worst part is it's http. The library you referenced supports two other endpoints too (namely opendns and icanhazip). I opened a ticket to is-online module to add option to disable calls to apple also enable https for apple.

sindresorhus/is-online#50

I'd be very happy if this goes well.
