### ISSUE TITLE
Remove 'Development' and 'Utility' categories from .desktop file

### ISSUE THREAD

**Issue by shroudedcode** [Foundry376/Mailspring#669]
> ```desktop
> Categories=GNOME;GTK;Network;Email;Utility;Development;
> ```

The `Development` category is meant to be used for software development tools and is labeled `Programming` on my Linux distribution. Mailspring doesn't fit into the category.

`Utility` is also wrong according to [the FreeDesktop specification](https://specifications.freedesktop.org/menu-spec/latest/apa.html) as it should be used for small system accessories (screenshotting tool, color picker, etc.).

**Comment by sverhagen** [comment]
How about "Office"?

**Comment by bengotow** [comment]
Thanks for the PR @sverhagen!
