### ISSUE TITLE
Updating removed my signatures

### ISSUE THREAD

**Issue by neamtua** [Foundry376/Mailspring#67]
Updating to the newest version removed both my signatures. Going back to settings is just the default one.

##### Are there any related issues?

...

##### What operating system are you using?
OSX High Sierra

##### What version of Mailspring are you using?
Version 1.0.2 (1.0.2)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
none

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no

##### Is the issue reproducible with a particular attachment, message, signature, etc?

no idea, i need to update again

**Comment by bengotow** [comment]
Hey! Ahh I’m sorry about this - there was some cleanup that was supposed to
make it into 1.0 and we shipped it in 1.0.2. If you open the Mailspring
confit.json file, you can move signatures from “nylas.signatures” to
“signatures” and everything should come back. The file is at
~/Library/Application Support/Mailspring on the Mac.

Also, there’s a whole new signature editor in the works - stay tuned!

Ben

**Comment by neamtua** [comment]
No worries. I just really like the app and I want it to be perfect. Thank you :)
