### ISSUE TITLE
Icon appearance bad on HDPI

### ISSUE THREAD

**Issue by BentHaase** [Foundry376/Mailspring#670]
##### What operating system are you using?
Fedora 27 Workstation, GNOME Shell 3.26.2, [Dash to Panel extension](https://extensions.gnome.org/extension/1160/dash-to-panel/)

##### What version of Mailspring are you using?

1.1.3

After the latest update the Mailspring icon looks really bad compared to before on HDPI (4K) or 1080p screens. Please allow manually setting the icon size in the settings or allow reverting to the previous icon.

![selection_127](https://user-images.githubusercontent.com/5788982/36004376-bd934f54-0d32-11e8-9de2-f5e0fe020b33.png)

**Comment by bengotow** [comment]
Hey! This icon was shrunk to prevent it from appearing too large on systems that don't automatically scale down the icon to match the display resolution. I think the next step is probably to make the app determine which icon to use manually based on the screen resolution. Would be a great starter issue!

**Comment by dennisotugo** [comment]
![screenshot_5](https://user-images.githubusercontent.com/17808627/36058639-49e9a2fc-0e26-11e8-8409-84658934467d.png)

I do not have a HDPi screen but still

**Comment by bengotow** [comment]
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of Electron and/or snapcraft. Feel free to bump this or re-open a new issue if you run in to this again.
