### ISSUE TITLE
Sending mail hitches the UI a little more than is acceptable

### ISSUE THREAD

**Issue by axfelix** [Foundry376/Mailspring#671]
Hi,

Wanted to say great work on the newest release of Mailspring -- it's getting closer and closer to being stable enough that I'd recommend it to people who aren't on Linux, where it's already the best option :)

The only major performance problem I still have is sending mail. On an i5-4300Y, which is an OK CPU, I still get a couple seconds UI hitching while sending, which is actually quite annoying and disruptive to my workflow. I really think this should be decoupled from the UI thread somehow; modern mail clients should be able to handle this just fine.

**Comment by bengotow** [comment]
Hey! This is actually pretty interesting - does it get "stuck" when you click "Reply" to start composing a new email, or when you actually send it? Since we switched to SlateJS for the editor in 1.1.0, there have definitely been performance issues when starting new drafts (#672, #654) and there should be a fix coming soon. I haven't run into problems when it actually sends though?

**Comment by axfelix** [comment]
It's when it sends. Reliably a couple seconds of UI hangs.

**Comment by dennisotugo** [comment]
@axfelix What is your distro, desktop any specific that could help with reproducing this

**Comment by axfelix** [comment]
Arch / Gnome

**Comment by palefire19** [comment]
This might not be helpful @axfelix @bengotow  but for me the hitches are much more on opening up a reply or a new compose window, rather than when I actually hit send.

**Comment by axfelix** [comment]
I've noticed this seems to only happen when my connection is poor (bad wifi in the office), if that helps.

**Comment by axfelix** [comment]
This is effectively fixed in current versions when my connection is stable. Mailspring still doesn't tolerate bad connections well (I've seen it leak tons of memory when the connection is poor) but I'll just chalk that up to Electron I guess...

**Comment by CodeMouse92** [comment]
It appears from the comments that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).** You're welcome to reference this issue again there.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
