### ISSUE TITLE
Cannot see selected label in dropdown with Taiga theme

### ISSUE THREAD

**Issue by briansholis** [Foundry376/Mailspring#674]
Hi,

Loving the app. I'm not technically savvy, so I don't know how to begin to fix this, but I wanted to point out that the colour scheme of Taiga contains an error: you cannot see a selected label in the dropdown because the highlight colour is the same as (or very similar to) the text colour. I'm on MacOS 10.13.3 using Mailspring 1.1.3. See attached screenshot. 
![screen shot 2018-02-09 at 9 15 50 am](https://user-images.githubusercontent.com/21323860/36031941-61a04c36-0d7a-11e8-9b18-5bfa317e3bee.jpg)

Thanks!

Brian

**Comment by bengotow** [comment]
Hey! Ahh thanks for pointing this out—I dunno how I hadn't noticed this. Will get this fixed in the next release.

**Comment by bengotow** [comment]
Hey! The fix for this shipped in version 1.1.4 this morning - cheers!
