### ISSUE TITLE
Archived conversation reappears after reply to conversation.

### ISSUE THREAD

**Issue by jyboudreau** [Foundry376/Mailspring#675]
Steps to reproduce:
1. Reply to a message in your inbox.
2. Archive the conversation while the message is outbound (I also have 5 second delay on sending on)
3. After a re-sync, conversation re-appears in inbox with my reply as unread.

Note: I have Outlook on my iPhone which is tied to the same account.

##### Are there any related issues?
Yes. #364 

##### What operating system are you using?
MacOS 10.13.3 (17D47)

##### What version of Mailspring are you using?
Version 1.1.3 (1.1.3) 27dcee2f

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Office365

Couldn't reproduce with Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Doesn't seem to be related to a particular message.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - I'll see if I can reproduce it with my test account. I imagine that this doesn't happen if you do this from the Outlook web interface? (eg: if you reply to an archived email, it stays archived?)

**Comment by jyboudreau** [comment]
I tried to reproduce in the Outlook web interface and I was able to reproduce. So I can close this for now.

Any suggestions on attempting to "fix" this problem?
