### ISSUE TITLE
[BUG] Hitting backspace multiple times in a new message breaks replies

### ISSUE THREAD

**Issue by danawoodman** [Foundry376/Mailspring#676]
##### Are there any related issues?

Not that I can tell

##### What operating system are you using?

OSX

##### What version of Mailspring are you using?

Latest

##### Do you have any third-party plugins installed? If so, which ones?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

1. Reply to a message
2. Hit backspace till you delete your signature
3. Now you are unable to write a reply (unless you expand the reply body)

If you do this, the cursor disappears (presumably hidden in the collapsed part of the message?) which is not intended behavior.

See:

![](https://cl.ly/pQ08/Screen%20Recording%202018-02-09%20at%2003.32%20PM.gif)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this was fixed in v1.1.5, enjoy!
