### ISSUE TITLE
[BUG] Have to double click to put cursor within misspelled word

### ISSUE THREAD

**Issue by danawoodman** [Foundry376/Mailspring#677]
##### Are there any related issues?

Possibly #578 

##### What operating system are you using?

OSX

##### What version of Mailspring are you using?

Latest

##### Do you have any third-party plugins installed? If so, which ones?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

1. Write some text which includes a misspelling
2. Attempt to click within the misspelled word to fix it
3. The cursor does not go where you click (as expected)
4. Click again to finally select within the text

See:

![screen recording 2018-02-09 at 03 49 pm](https://user-images.githubusercontent.com/157695/36055410-03dc71f6-0db1-11e8-9fb3-bb1ac6ec5d69.gif)

**Comment by bengotow** [comment]
Hey - thanks for filing this (and providing the GIF!) Looks like this should be a quick fix - stay tuned.

**Comment by danawoodman** [comment]
@bengotow thanks!

**Comment by bengotow** [comment]
Hey folks—this has been fixed in 1.1.5 which shipped yesterday. You can download the update from https://getmailspring.com/download or choose "Check for Updates" within the app to install it. Enjoy!

**Comment by danawoodman** [comment]
🍻🎉
