### ISSUE TITLE
Editing raw html signatures shows a very small text box

### ISSUE THREAD

**Issue by neamtua** [Foundry376/Mailspring#68]
##### What operating system are you using?
OSX High Sierra

##### What version of Mailspring are you using?
1.0.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no
##### Is the issue reproducible with a particular attachment, message, signature, etc?

<img width="833" alt="screen shot 2017-10-07 at 09 55 39" src="https://user-images.githubusercontent.com/1029457/31305575-b9c95b74-ab45-11e7-8354-3f6a0ae1b1f9.png">

**Comment by Modelmat** [comment]
It's on windows 10 too.

**Comment by Shickmo** [comment]
I can likewise confirm the tiny box in Ubuntu Mate 17.04. My work around was simply copying text to an editor and pasting back in when complete for now. Everything I entered showed as expected including links to internet based images.

**Comment by egoistonly** [comment]
Same on Deepin 15.4.1

**Comment by alorence** [comment]
I can confirm this issue is fixed in latest release 1.0.3

**Comment by Shickmo** [comment]
Confirmed this is fixed on Ubuntu Mate 17.04.
