### ISSUE TITLE
Unable to disable link open notification

### ISSUE THREAD

**Issue by PandaHugMonster** [Foundry376/Mailspring#680]
Really nice email-client, but it drives me crazy. I deleted the application now because I'm not being able to disable constant notifications on opening links.

**Comment by sverhagen** [comment]
Can you provide more information, what does your environment look like? What are these popups?

**Comment by PandaHugMonster** [comment]
The function of notifying about somebody opened links in my messages. I didn't find a way to switch it off.
Many times my colleagues opened the same link - I'm receiving those notifications. I don't need this function, why I can't switch it off?
Linux Arch x64

**Comment by sverhagen** [comment]
You can at least [turn it off for new e-mails](https://foundry376.zendesk.com/hc/en-us/articles/115002228092), if that's useful?

**Comment by PandaHugMonster** [comment]
Got it, Thank you.
