### ISSUE TITLE
The name org.freedesktop.secrets was not provided by any .service files

### ISSUE THREAD

**Issue by tobias-kuendig** [Foundry376/Mailspring#681]
When I run mailspring on latest KDE Neon I get the following message:

![-2- _006](https://user-images.githubusercontent.com/8600029/36097439-4a09c7fe-0ffb-11e8-97b1-f256f94d4099.png)

All `libsecret-*` packages are installed as recommended in the KB article.

It looks like Mailspring cannot communicate with KWallet. Any idea on how to get this working?

```
$ mailspring --dev
Running database migrations
App load time: 238ms

{"error":null}
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Manual update check (updates.getmailspring.com/check/linux/x64/1.1.3-27dcee2f/anonymous/stable) returned 204
{ Error: The name org.freedesktop.secrets was not provided by any .service files
  message: 'The name org.freedesktop.secrets was not provided by any .service files' } { pluginIds: [] }
TypeError: Cannot read property 'emit' of undefined
    at EventEmitter._electron.ipcMain.on.args (/usr/share/mailspring/resources/app.asar/src/browser/application.js:556:10)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at WebContents.<anonymous> (/usr/share/mailspring/resources/electron.asar/browser/api/web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7) {}
```

##### What operating system are you using?

```
Distributor ID: neon
Description:    KDE neon User Edition 5.12
Release:        16.04
Codename:       xenial
```

##### What version of Mailspring are you using?

1.1.3-27dcee2f

**Comment by bengotow** [comment]
Hey! Are you using the Snapcraft release of Mailspring? It might be a good idea to see if that works - might also be useful to look at https://github.com/atom/node-keytar (the package we use to access the system wallet) and see if there are any clues there?

**Comment by tobias-kuendig** [comment]
Hi, thanks for your response. I have tested it with both the `deb` and the `snap` version. Unfortunately without any luck.

This bug looks promising: https://github.com/atom/node-keytar/issues/74

**Comment by tobias-kuendig** [comment]
I can confirm that `sudo apt install gnome-keyring` solves the problem on KDE. Looks like the problem is with `node-keytar`. Thanks for pointing me to the right direction!

**Comment by outfrost** [comment]
Could you make it an option to _not_ store passwords on disk at all?

For me, none of the solutions or workarounds that I've found for the problem of Mailspring relying on libsecret are desirable. I would simply prefer it not to store my password offline, only holding it in RAM while logged in for the purpose of continuous sync. FWIW, it is an option in Thunderbird.

Hardwiring a desktop-agnostic app to absolutely always require a piece of GNOME software seems somewhat odd to me. IMHO it would be much better if offline password storage was optional.

**Comment by passioncsu** [comment]
> I can confirm that `sudo apt install gnome-keyring` solves the problem on KDE. Looks like the problem is with `node-keytar`. Thanks for pointing me to the right direction!

its also work for archlinux  thx!
