### ISSUE TITLE
Happened (once) while typing/answering a mail

### ISSUE THREAD

**Issue by Lyptik** [Foundry376/Mailspring#685]
windows 10
mailspring v1.1.3-27
Several mail accounts synced
theme dark

Probably not reproductible, even in my setup.
Screenshot attached for feedback.

![image](https://user-images.githubusercontent.com/5172593/36220956-c25fc25e-11bc-11e8-8d8d-c18a95ee314b.png)

**Comment by Lyptik** [comment]
By the way, to fix this I did ctrl+shift+r which triggered a reload of the software and then it was fixed xD

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - that definitely shouldn't be happening. Thankfully that trace narrows it down pretty specifically so I should be able to fix that without necessarily reproducing it. Cheers—

**Comment by JunnanZ** [comment]
I had the same issue, but mine is "...cannot read property 'id'...". I don't know how to reproduce it either, but it's gone after I deleted a draft.

**Comment by bengotow** [comment]
Hey folks—this has been fixed in 1.1.5 which shipped yesterday. You can download the update from https://getmailspring.com/download or choose "Check for Updates" within the app to install it. Enjoy!

**Comment by danclarkau** [comment]
Hi Guys, I have this issue when I open an old thread in email then as soon as I click the '4 Older Messages' button in the preview pane I get the error.
