### ISSUE TITLE
Feature Request: Google Inbox Bundles

### ISSUE THREAD

**Issue by s3w47m88** [Foundry376/Mailspring#687]
Are there any existing features or plans for a feature like Google Inbox Bundles?

**Comment by cavorka216** [comment]
I second this!!! Would be the best thing ever!

**Comment by tobiasrenkin** [comment]
I third this!

**Comment by CodeMouse92** [comment]
This is answered here: https://community.getmailspring.com/t/gmail-categories-or-bundles/302
