### ISSUE TITLE
Reminder Mail not showing correctly with dark theme

### ISSUE THREAD

**Issue by dwuttke90** [Foundry376/Mailspring#689]
##### Are there any related issues?

no

##### What operating system are you using?
arch linux

##### What version of Mailspring are you using?
1.1.4.22d9f20-1 AUR package

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
not sure. i am only using outlook.com

##### Is the issue reproducible with a particular attachment, message, signature, etc?

if i set a reminder to a mail and the reminder hows up in my inbox i cannot read the text in the mail list. seems like white background and slightly darker white as text

![image](https://user-images.githubusercontent.com/26198858/36259513-b343ab80-125e-11e8-8e2c-607c3fcbe4dd.png)

EDIT:
problem is gone after clicking on it. even setting it manually to unread is working as expected. so it is just for new reminders as it seems.

**Comment by bengotow** [comment]
This has been fixed now in 1.7.4 - stay tuned!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
