### ISSUE TITLE
[Q] config file location for precompiled package

### ISSUE THREAD

**Issue by aurabindo** [Foundry376/Mailspring#69]
I'd like to tweak the zoom setting `core.workspace.interfaceZoom` to say 1.5 or so. But where will I make this change in case of the officially provided debian (using Debian 9) package ?

**Comment by bengotow** [comment]
Hey! On Linux it's in `~/.config/Mailspring/config.json`. You can find the paths for other platforms here: https://foundry376.zendesk.com/hc/en-us/articles/115001968632-How-do-I-manually-delete-cached-mail-data-and-settings-

**Comment by aurabindo** [comment]
@bengotow  Thank you!
