### ISSUE TITLE
consider adding a way to disable swipe gestures

### ISSUE THREAD

**Issue by samkusnetz** [Foundry376/Mailspring#690]
when using a trackpad, it's very easy to accidentally archive a message when you're trying to scroll because swipe gestures use a two-finger sideways movement, and scrolling uses a two-finger vertical movement, and seemingly any diagonal movement is interpreted as sideways.

dimly related to https://github.com/Foundry376/Mailspring/issues/683

**Comment by RomanKlopsch** [comment]
there should be an option to disable swipe gestures in the settings.
try *settings -> general -> reading -> swipe gestures and backspace / delete move messages to trash*

i hope this is what you meant although i don't know whether this option also disables archiving messages due swipe gestures. I am also using a trackpad and my mailspring seems to not react to swipe gestures so i think what you have experienced did not happen on purpose...

**Comment by LunarTwilight** [comment]
Kinda related, but when I scroll in my inbox with two fingers, the message list scrolls, but when I view a message, scrolling makes me fly through my messages, rather than scrolling up and down the message?

**Comment by cloudsolver** [comment]
@RomanKlopsch You can disable swipe for delete, but you can not disable swipe for archive. 

Please add a checkbox in the preferences for BOTH delete move message to trash (exists) and disable move messages to Archive.

This is a a MAJOR usability feature for mac users!!

**Comment by bengotow** [comment]
Hey folks - this should be resolved in the next release. For some reason, the swipe gesture implementation properly required "mostly horizontal" touch interaction to trigger, but didn't filter macOS trackpad interaction in the same way. Stay tuned.

**Comment by manuel-tiedtke** [comment]
> Hey folks - this should be resolved in the next release. For some reason, the swipe gesture implementation properly required "mostly horizontal" touch interaction to trigger, but didn't filter macOS trackpad interaction in the same way. Stay tuned.

So this means, that in this future release the horizontal swipe gestures will require a much steeper horizontal swipe angle? I expect horizontal swipe gestures to only trigger when the swipe is nearly horizontal ±15˚ or something in the vicinity would be in order, I'd say. And it should be vertical XOR horizontal swipe.

**Comment by bengotow** [comment]
@manuel-tiedtke — Yep, that's right! Let me know if you're still seeing behavior that is too sensitive. Going to go ahead and close this.

**Comment by SvenEbens** [comment]
Using the MX master (2s) mouse, just slightly touching the horizontal scroll wheel, also triggers this swipe function and I regularly trigger it accidentally, deleting or archiving a mail. Turning the swipe option off in the settings fixed this, but it seems like that option has recently been removed. Can this please be added back, I have no use for the swipe functionality and would rather not have to worry about accidentally deleting/árchiving mails when touching the mouse.

**Comment by bengotow** [comment]
Hey folks, an option was added to Mailspring's preferences in 1.19.0 (March 2026). You can now disable thread list swipe gestures in **Preferences → General → Reading**. This should prevent accidental archive/delete when scrolling with a trackpad.

I'll also see if I can test with a magic mouse, I think I can borrow one from the office and try to repro this - ideally we'd just adjust the implementation so that that works well too.
