### ISSUE TITLE
is:unread fetches spam which doesn't seem natural

### ISSUE THREAD

**Issue by cavorka216** [Foundry376/Mailspring#691]
##### Are there any related issues?
I can't find related reports

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.1.4

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
So far I've only seen it with Gmail

**Comment by bengotow** [comment]
Hey! This has been fixed in f6a008b279680231393bcbd0df79596c9d0b4c3d and will ship in the next release. Enjoy!

**Comment by bengotow** [comment]
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!
