### ISSUE TITLE
Trojan HEUR/QVM20.1.4111.Malware.Gen detected in install file

### ISSUE THREAD

**Issue by gspolly** [Foundry376/Mailspring#697]
Hey there, I am trying to download the build for Windows (x64) from your website (https://getmailspring.com/download) but my antivirus software (360 Total Security, version 9.6.0.1245) triggers a quarantine for detecting the Trojan "HEUR/QVM20.1.4111.Malware.Gen" in the setup file. Does anyone else experience the same problem?

**Comment by gspolly** [comment]
I checked it again using virustotal (see https://www.virustotal.com/#/file/a4476663f1b095fbd7a65367facfbfdce288985c47472be61c46e736be6961e7/detection) and found a response at Qihoo-360 only. Seems to be a false positive.

**Comment by bengotow** [comment]
Awesome thanks for the update @gspolly!

**Comment by Rick-laboratory** [comment]
SecureAge APEX
Cylance
Ikarus
Qihoo-360

Are Bullshit, i can compile my own windows activator with 3 lines of code and they say virus xD
