### ISSUE TITLE
When creating/editing an email make the links clickable only with CTRL+click

### ISSUE THREAD

**Issue by krasi-georgiev** [Foundry376/Mailspring#702]
When editing or creating a message it is very easy to click a link unintentionally.
Can you please make it so that links in a text that is editable is clickable only when the CTRL is pressed. 
When CTRL is pressed  links that are clickable should change to indicate that they are clickable , I think just a slight colour change or underlining should be enough.

The is the default behaviour for all mail clients I have used - OSX mail , wmail etc.

**Comment by bengotow** [comment]
Yep I agree this should definitely change—let me see if I can fix this in the next release.

**Comment by krasi-georgiev** [comment]
thank you , thank you thank you. Just tried it works well. 

normally the cursor should also change to a mouse pointer when you hold the ctrl over a clickable link, but it is fine as like this as well.
