### ISSUE TITLE
auto correction changing the wrong word

### ISSUE THREAD

**Issue by krasi-georgiev** [Foundry376/Mailspring#703]
https://youtu.be/3Xkc8gVKnjg
As you can see the auto correction doesn't change the word where I did the right click.

##### What operating system are you using?
Fedora
##### What version of Mailspring are you using?
1.1.4-22d9f20d

##### Do you have any third-party plugins installed? If so, which ones?
none

**Comment by VinTz1** [comment]
Hello, I also noticed that problem. Auto-correction insert the corrected word at the place where the cursor is. A quick workarround is to select the word with double-left click before correcting it. Then it will be replaced. 

Personally, I found that auto-correction and language detection work very bad.

**Comment by krasi-georgiev** [comment]
so double click would be the expected behaviour ?

**Comment by VinTz1** [comment]
If you double left-click the word you want to replace and then it will be selected and then you right-click on it and the correct word will replace it.

**Comment by krasi-georgiev** [comment]
yes , I got that , all I am saying is that is that would remain the default behaviour than I should close this.
