### ISSUE TITLE
Emptying the Spam and trash folders sometimes "sticks" and messages remain

### ISSUE THREAD

**Issue by krasi-georgiev** [Foundry376/Mailspring#705]
Clicking the Spam or the Trash folder shows only a spinning animation and I don't see no other way to empty those folders.
Image attached.
If I restart the application it goes back to normal, but eventually it does that. so I assume it gets stuck at some checks somehewhere.
this would probably be difficult to replicate so let me know what other info do you need to help replicate it.

##### What operating system are you using?
Fedora
##### What version of Mailspring are you using?
1.1.4-22d9f20d
**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
NONE

![screenshot_20180218_145916](https://user-images.githubusercontent.com/8903888/36352097-775b56c6-14bc-11e8-9321-15ac66a2bc56.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—I was able to reproduce it for one of the test accounts but it worked for the others. Will see what's going on.

**Comment by Richyread** [comment]
I just wanted to add that I am seeing a seemingly related issue - I too have had to force close the app and reload to enable clear spam/clear trash runs on occasion.  However, for the last few days I'm now stuck with a single mail that refuses to clear from the trash;

It's no longer showing on the server (gmail) or 'findable' within the [All Mail] archives so certainly does appear to have been deleted, but Mailspring certainly seems to still be getting hung up with these clear spam/clear trash commands somewhere.

There's no sign of any obvious errors in the logs ~ just a long load time when launching the app as the 'sync' process seems to hang on checking the /Gmail/Bin, and this specific email is stubbornly refusing to leave 😄 

![image](https://user-images.githubusercontent.com/7470850/43370766-d48867c8-937c-11e8-83b8-4d76dd4db6c4.png)

**Comment by krasi-georgiev** [comment]
seems fine now

**Comment by sykp** [comment]
This issue hasn't changed with any updates... I face this issue every day, while emptying trash or spam folders... The rotating icon.

OSX 10.13.6, Mailspring Version 1.7.2 latest version.
