### ISSUE TITLE
Adding account bugged - missing required fields

### ISSUE THREAD

**Issue by ET-Bent** [Foundry376/Mailspring#707]
##### What operating system are you using?
Fedora 27, 64bit
GNOME Shell 3.26.2

##### What version of Mailspring are you using?
Mailspring 1.1.4-22d9f20d

Adding an account is impossible even after clearing cache or toggling "Allow insecure SSL":

![mailspring_195](https://user-images.githubusercontent.com/5788982/36373354-35a8809e-1568-11e8-8a68-37737f2e7b5f.png)

**Error:**

`Account is missing required fields:smtp_allow_insecure_ssl`

**Bonus bug:**

these text boxes are visible even though "custom" is not selected for "Port". Selecting custom and then selecting the given ports again hides the boxes.

![mailspring_196](https://user-images.githubusercontent.com/5788982/36373495-9c466d7a-1568-11e8-9dfd-3ad1e0921422.png)

EDIT:

Even though the first error is thrown the account somehow still is added.

**Comment by theollyr** [comment]
Same for me, although it doesn't add the account as mentioned in the edit. Mailspring 1.1.4-22d9f20d, Gnome 3.26.2, Arch.

**Comment by otobrzo** [comment]
Tha same for me, debian 9 (64bit) but account is not added.

**Comment by Viniter** [comment]
Same error, but after checking and unchecking both "Allow insecure SSL" checkboxes it works. I also get the double Port fields as pictured above, but after filling out same port number as the one selected in dropdown menu the second input field disappears. 

Ubuntu 17.10, GNOME Shell 3.26.1 (vanilla Gnome, not the Ubuntu flavour), Mailspring 1.1.4-22d9f20d

**Comment by roboto-cloud** [comment]
same error here

**Comment by bengotow** [comment]
Hey folks! This should be be fixed in version 1.1.5 (I think it was fixed as #739). Enjoy!
