### ISSUE TITLE
diacritic accents make email window crash

### ISSUE THREAD

**Issue by mnlngl** [Foundry376/Mailspring#718]
As stated above, whenever I type a diacritic accent on a mac laptop sunning high sierra, the email composition window stops working and I have to close it (or mailspring itself) in order to continue writing the message.

I write emails in three languages, two of these three have accents, like this é.

I am a paying customer and haven't received support after filing a bug. Pretty annoying.

##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of Mailspring are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Wow that's pretty crazy indeed. I'll see if I can reproduce this—could you elaborate on how the composer stops working? It just "locks" and won't accept any more text?

**Comment by bengotow** [comment]
Hmm, so I've been able to reproduce an odd issue where sometimes I type a diatric character (´) and then the cursor jumps to /before/ the character instead of after it, so when I type the next character (e), it doesn't have the diatric. Once I do that, I'm not able to press backspace or move the cursor until I type another diatric mark (`). Is that what you're seeing? Definitely odd behavior... I'll see if I can get to the bottom of it.

**Comment by mnlngl** [comment]
exactly that and the app does not allow me to edit the message unless i restart it. It happens every minute to me as I write in Spanish and Portuguese, which use lots of diacritics (I just apply them unconsciously and cannot afford to type with spelling errors!).
Also, restarting the app seems to erase some bits of the draft.
I want to process a refund for my use of the app until this issue is fixed. I will still continue to pay as I need the receipt alert and cannot stop using the app. However it is not on a usable state.

**Comment by gazambuja** [comment]
Same problem here. I need to close the composer window, go to Draft and double click into the email and start again.

**Comment by mnlngl** [comment]
It’s so frustrating, and Mailspring has no customer support, even though I am a paying customer!

This app feels like a scam ripoff of a once noble open source project called nylas mail.

**Comment by justindoran** [comment]
I have the same problem on MacOS and the US International - PC keyboard layout. It's definitely intermittent, and it definitely goes away if I switch to the regular US keyboard layout. It got better (i.e. less frequent) a few patches ago.

Is it something to do with how MacOS handles these key replacement layouts? I know it's different than how windows handles it. In MacOS, using the special diacritic keys first inputs the character (with some visual signal that it's tentative, like making it underlined), then it deletes that character on the next keystroke while inputting the correct character. Windows and Linux both just skip the first two steps, providing no visual feedback that the diacritic keystroke has been pressed before inputting the correctly accented character. Is that process of inputting, signaling, then deleting the character conflicting with some other character watching process in the composer window?

Thanks Ben!

PS - I'm also a paying "customer" but don't feel entitled to your attention/time. You're doing a great job irmão and mailspring is turning out fantastic!

**Comment by mnlngl** [comment]
Irmão,

No need for the passive aggressivity. It’s like saying you don’t feel entitled to occupy the flat you are paying rent for. I don’t feel entitled, at least I feel like I shouldn’t be charged £8 monthly for a half baked app. I know the process is going well but this is about ethics, not about feelings. In that case, it’s fine if the customer support is clear about its limitations, and the app is rightly branded as a beta version that is being charged. The thing that is annoying me the most is the fact that I opted out to continue the payment and got disconnected from a full month for the service I had paid. No answer as of now, and so I feel like I can rightly be frustrated.

Saudações,
M.

**Comment by bengotow** [comment]
Hey folks—finally got to the bottom of this over here: https://github.com/ianstormtaylor/slate/issues/1708, and it'll be fixed in the next release of Mailspring (early next week). This turned out to be pretty subtle and I'm hoping the folks working on Slate can make changes to prevent this sort of bug from ever happening again. Stay tuned—

**Comment by justindoran** [comment]
Just to follow up, this seems fixed for me now after the update. It might by psychosomatic, but the composer also just feels way snappier and more stable with this update. Great job and thank you!

**Comment by bengotow** [comment]
Hey folks! Sorry I never closed this ticket — this shipped a while back. Thanks to everyone for reporting this and submitting feedback.
