### ISSUE TITLE
Problems with Subject

### ISSUE THREAD

**Issue by Thalazor** [Foundry376/Mailspring#72]
The client isn't showing the correct subjects.

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
Version 1.0.2

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Nope

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![image](https://user-images.githubusercontent.com/20997488/31307725-3fef9c50-ab40-11e7-81e4-4f3af5a2a7b9.png)

**Comment by kometchtech** [comment]
Does "reset email cache" under Preference do not improve the situation?

**Comment by bengotow** [comment]
Hey! This should be fixed in 1.0.2, but you'll need to reset your email cache in Preferences > General as @kometchtech noted. There was a problem with the way we were handling subject lines with encoded characters on Windows!
