### ISSUE TITLE
Cannot add picture in signature.

### ISSUE THREAD

**Issue by abixadamj** [Foundry376/Mailspring#722]
##### What operating system are you using?
Linux Mint 64bit 18.2
...

##### What version of Mailspring are you using?
Latest - 1.1.4
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
When I try to add picture in Signature, I got an error:
_

> Sorry, we couldn't save your signature image to Mailspring's servers. Please try again.
> 
> (Error: POST https://id.getmailspring.com/api/save-public-asset returned 500 Internal Server Error)

**Comment by pedrominatel** [comment]
Also on Manjaro 17 64bits and Mailspring 1.1.4-22


**Message:**
Sorry, we couldn't save your signature image to Mailspring's servers. Please try again.

(Error: POST https://id.getmailspring.com/api/save-public-asset returned 503 Service Unavailable: Back-end server is at capacity)

**Comment by bengotow** [comment]
Hey! It looks like this was a temporary issue with the backend—should be resolved now (and I've added monitoring for this issue), thanks for reporting this.
