### ISSUE TITLE
Emails of deleted account can't be removed

### ISSUE THREAD

**Issue by rafrsr** [Foundry376/Mailspring#724]
##### Are there any related issues?
No

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
v1.1.4

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I have some draft emails in the draft folder of old deleted email account and I can't delete this email. When try to modify or delete these emails, I get the following error:

> **Mailspring is unable to sync undefined**
> In order to perform actions on this mailbox, you need to resolve the sync issue. Visit Preferences > Accounts for more information.

![peek 2018-02-25 14-24](https://user-images.githubusercontent.com/7094012/36645510-da046d64-1a37-11e8-85be-89089402f261.gif)

The account used to create these drafts has been deleted and and I not able to connect to this account again.

In the trash I also have some emails that I can not do anything with them and they are not deleted.

**Comment by bengotow** [comment]
Hey! This should be fixed soon—basically when you remove an account Mailspring needs to rebuild the search index and a few other things without the messages for that account. I'll see if I can get this added in the next release.

**Comment by bengotow** [comment]
Hey folks—this has been fixed in 1.1.5 which shipped yesterday. You can download the update from https://getmailspring.com/download or choose "Check for Updates" within the app to install it. Enjoy!

**Comment by aleasto** [comment]
Hi, I'm hitting this issue on the latest build: 1.9.1
