### ISSUE TITLE
Cannot sync Outlook.com

### ISSUE THREAD

**Issue by napsterv** [Foundry376/Mailspring#725]
##### What operating system are you using?
**Windows 10**

##### What version of Mailspring are you using?
**1.1.4**

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
**No**

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
**Microsoft Outlook**

##### Is the issue reproducible with a particular attachment, message, signature, etc?

This is the error log
_----------IMAP----------
* OK The Microsoft Exchange IMAP4 service is ready. [UABOADEAUABSADAAMQBDAEEAMAAxADAANwAuAEkATgBEAFAAUgBEADAAMQAuAFAAUgBPAEQALgBPAFUAVABMAE8ATwBLAC4AQwBPAE0A]
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
2 LOGIN "s*ft**ac*@outlook.com" "*********"
2 OK LOGIN completed.
3 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
3 OK CAPABILITY completed.
4 NAMESPACE
* NAMESPACE (("" "/")) NIL NIL
4 OK NAMESPACE completed.
5 LIST "" "*"
* LIST (\HasNoChildren) "/" Archive
* LIST (\HasNoChildren \Trash) "/" Deleted
* LIST (\Marked \HasNoChildren \Drafts) "/" Drafts
* LIST (\Marked \HasNoChildren) "/" Inbox
* LIST (\HasNoChildren \Junk) "/" Junk
* LIST (\HasNoChildren) "/" n**r*j.*@outlook.com
* LIST (\HasNoChildren) "/" Notes
* LIST (\Marked \HasNoChildren) "/" Outbox
* LIST (\HasNoChildren) "/" Scheduled
* LIST (\Marked \HasNoChildren \Sent) "/" Sent
* LIST (\HasChildren) "/" "Sync Issues"
* LIST (\HasNoChildren) "/" "Sync Issues/Conflicts"
* LIST (\HasNoChildren) "/" "Sync Issues/Local Failures"
* LIST (\HasNoChildren) "/" "Sync Issues/Server Failures"
5 OK LIST completed.

----------SMTP----------

mailsmtp Last Error Code: 25

mailsmtp Last Error Location: 1_

**I have masked my email for privacy**

![screenshot_64](https://user-images.githubusercontent.com/8555852/36646360-99828a54-1a9c-11e8-919f-d23a82cabc0e.png)

**Comment by cooler9711** [comment]
same issue. i am on arch with mailspring v. 1.1.4. 

![error screen](https://user-images.githubusercontent.com/16909054/36954330-6c870682-1fde-11e8-9a4a-a47fb19608dc.png)

[here is my error log](https://hastebin.com/aliwelimat.m)

**Comment by jlcs-es** [comment]
Same issue, arch 4.15.7-1, Mailspring 1.1.4.
Equivalent error log.

Other IMAP account connected succesfully.

**Comment by Toby-S-Steele** [comment]
Same here, Win 10, Mailspring 1.1.5.

Find my error log [here](https://hastebin.com/zabacetoye.m).

**Comment by thoward27** [comment]
I'm receiving the same error on my end. 

Version 1.1.5, Ubuntu 17.10 x64

**Comment by JoonasC** [comment]
Happening here too.
Manjaro Linux
Kernel 4.17

**Comment by RicardoEPRodrigues** [comment]
I'm also seeing this error.

The are also duplicate errors now: #788 #748

**Comment by rickstaa** [comment]
Same error:

----------IMAP----------
* OK The Microsoft Exchange IMAP4 service is ready. [QQBNADMAUABSADAANQBDAEEAMAAxADIAMgAuAGUAdQByAHAAcgBkADAANQAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
2 LOGIN "rick.staa@outlook.com" *********
2 OK LOGIN completed.
3 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
3 OK CAPABILITY completed.
4 NAMESPACE
* NAMESPACE (("" "/")) NIL NIL
4 OK NAMESPACE completed.
5 LIST "" "*"
* LIST (\Marked \HasChildren) "/" Archive
* LIST (\Marked \HasNoChildren) "/" Archive/Administration
* LIST (\Marked \HasNoChildren) "/" Archive/Education
* LIST (\HasNoChildren) "/" Archive/Health
* LIST (\HasNoChildren) "/" Archive/Other
* LIST (\HasNoChildren) "/" "Archive/Self development"
* LIST (\HasNoChildren) "/" Archive/Work
* LIST (\Marked \HasNoChildren \Drafts) "/" Drafts
* LIST (\HasChildren) "/" Mailspring
* LIST (\HasNoChildren) "/" Mailspring/Snoozed
* LIST (\HasNoChildren) "/" Notes
* LIST (\Marked \HasNoChildren \Junk) "/" Junk
* LIST (\Marked \HasNoChildren) "/" Inbox
* LIST (\HasNoChildren) "/" Outbox
* LIST (\HasChildren) "/" "Problemen met synchronisatie"
* LIST (\HasNoChildren) "/" "Problemen met synchronisatie/Conflicten"
* LIST (\HasNoChildren) "/" "Problemen met synchronisatie/Lokale fouten"
* LIST (\HasNoChildren) "/" "Problemen met synchronisatie/Serverfouten"
* LIST (\HasNoChildren) "/" Scheduled
* LIST (\HasNoChildren) "/" Snooze
* LIST (\HasNoChildren) "/" Unwanted
* LIST (\Marked \HasChildren \Trash) "/" Deleted
* LIST (\Marked \HasNoChildren \Sent) "/" Sent
5 OK LIST completed.


----------SMTP----------


mailsmtp Last Error Code: 25

mailsmtp Last Error Location: 1

**Comment by madve2** [comment]
I have used this guide to set up Outlook.com in Mailspring manually (i.e. as a generic IMAP account): https://www.lifewire.com/access-outlook-in-thunderbird-3572532 (yes, it's written for Thunderbird but you can set the same numbers in Mailspring :) )

I also suspect that the automatic setup tries to use the wrong port.

**Comment by freddiehaddad** [comment]
I'm not sure if the Office 365 option is meant for your outlook.com email.  Office 365 is a subscription service from Microsoft.  However, as the above post says, you can manually enter the IMAP/SMTP settings, but, I suggest logging into your outlook.com and grabbing the information direct from Microsoft.

1.  Log into your outlook.com account through your web browser
2. Click the Settings icon on the right side of the navbar
3. Click View full settings (near the bottom of the menu)
4. Click the Sync email option
5. Scroll down to the IMAP/SMTP settings

For reference, here are the values:

```
IMAP setting
Server name: outlook.office365.com
Port: 993
Encryption method: TLS

SMTP setting
Server name: smtp.office365.com
Port: 587
Encryption method: STARTTLS
```

**Comment by NoeelMoeskops** [comment]
same issue, 
kernel: 4.16.5, OS: Antergos, mailspring: 1.2.1-7e...
for *@hotmail.com it fails. However my *@hotmail.nl account succeeded.

**Comment by ansermino** [comment]
Started for me today. Ubuntu 16.04. Can receive but can't sent. Same log output as above. Its a school email running on office365

**Comment by bengotow** [comment]
Hey folks—thanks for reporting this. I've changed the default Outlook port in 314993f0b5d25474c37eba5089366eb0acbb0b86, and we've also revised the onboarding screen so that it presents Office365 and Outlook.com / Live.com as two separate options, which should resolve a lot of the confusion I think. Stay tuned! The new version should ship in a day or two.

**Comment by bengotow** [comment]
Hey folks! This has shipped in 1.4.1. You can get the update automatically if you're using the Mac and Windows versions, or the Linux snapcraft release, and you can also download it from https://getmailspring.com/download.  I'm going to go ahead and close this and we'll re-open it if necessary. Thanks—enjoy the app!

**Comment by OmarShawky1** [comment]
This issue appeared again in all of my devices (Linux & Windows). i tried to manually enter the IMAP & SMTP settings but to no avail. This is the error that shows when I manually enter the settings for Office365. (this issue appears for Office365 only).

```
----------SMTP----------
connect smtp.office365.com 587


SASL_PATH: 

mailsmtp Last Error Code: 25
mailsmtp Last Error Explanation: MAILSMTP_ERROR_CONNECTION_REFUSED
mailsmtp Last Error Location: 1
mailsmtp Last Auth Type: 0
```

**Comment by NancyNathan** [comment]
I'm having the same issue for about a month and it's driving me crazy. It used to work just fine for months. I tried everything!
