### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by xavier83ar** [Foundry376/Mailspring#731]
##### What operating system are you using?
Linux, Ubuntu 16.04

##### What version of Mailspring are you using?
1.1.4-22d9f20d

--

**Bug?**
Search is not working, or at least is not working as expected. When I search for some words it only shows a few results but not all of them, even when searching for the exact same subject, only shows a few results, and other are never shown.

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

#### Example
![seleccion_019](https://user-images.githubusercontent.com/1458700/36703908-a9a28ca4-1b3c-11e8-9b58-4808068d9451.png)
There is a few mails with subject "Cron Daemon", some of a few hours ago, other from yesterday (25 feb).

If I search "Cron Daemon" ...
![seleccion_020](https://user-images.githubusercontent.com/1458700/36703987-02171c10-1b3d-11e8-8f07-40fef8603323.png)

As you can see, there is no unread results and all search results are from 3 days ago and before. This is only an example, but the same is happening with all my searches, I've to go to gmail or my webmail because mailspring doesn't show all results and it's almost imposible to find what I'm looking for right now.

**Comment by palefire19** [comment]
I can reproduce - not the exact same as @xavier83ar but pretty similar - a simple search term (e.g. "John") misses emails in my inbox from a sender "John Doe".

**Comment by chapinpark** [comment]
I have the same problem. Working on a Mac, latest version of Mailspring.

**Comment by bengotow** [comment]
Hey folks—this has been fixed in 1.2.0 in efe6830bc3da8a6fcfd044b86467a1344f908078. In some scenarios the search query generator was creating SQL sub-selects and arbitrarily capping the number of results. (I guess as a performance optimization from when it was used differently!) Now that that is fixed, I see a full set of results as expected!

**Comment by pablorq** [comment]
Hi! This is actually happening still, with emails older than 6 months.

Do I have to open a new issue?

Regards.

**Comment by simroux** [comment]
Hi ! Just adding that this is happening to me too with new emails (i.e. only finding the older ones), Mailspring 1.7.6-e94bb759 running on Ubuntu 19.10. @pablorq : seems like it would be worth re-opening an issue.

**Comment by pablorq** [comment]
> Hi ! Just adding that this is happening to me too with new emails (i.e. only finding the older ones), Mailspring 1.7.6-e94bb759 running on Ubuntu 19.10. @pablorq : seems like it would be worth re-opening an issue.

Would you like to reopen, please?
