### ISSUE TITLE
Adding a @hotmail.it account ask for manual settings

### ISSUE THREAD

**Issue by Ansem93** [Foundry376/Mailspring#736]
Hi,
I'm having trouble with a @hotmail.it email. When I add it, Mailspring asks me to insert manually the configurazion.
I'm adding it with the office365 option, like I do for my @outlook.com email.

I don't think that this is normal, since the dominion @hotmail.it is a Microsoft dominion just like @outlook.com

##### What operating system are you using?
Windows 10 64bit

##### What version of Mailspring are you using?
1.1.4

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
only when adding a @hotmai.it email

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - looks like I missed this scenario when QAing the most recent release. Will be fixed in 1.1.5.

**Comment by bengotow** [comment]
Hey folks—this has been fixed in 1.1.5 which shipped yesterday. You can download the update from https://getmailspring.com/download or choose "Check for Updates" within the app to install it. Enjoy!
