### ISSUE TITLE
Signature images render improperly when image CSS is unsupported

### ISSUE THREAD

**Issue by bigbrett** [Foundry376/Mailspring#737]
I set an email signature with an image in the Mailspring app, and it looks fine in my email editor, as well as with Outlook online and Gmail. However **when the email is opened in the native MS Outlook app, the signature image appears gigantic** (not sure if its the original size of the image, but it is massive). 

## What it looks like in Mailspring, Outlook Online, and Gmail: 
![screenshot_2018-03-01_10-32-38](https://user-images.githubusercontent.com/7547222/36859550-f082fb8a-1d3b-11e8-989a-b870d3cd5c0e.png)

## What it looks like in Outlook:
![image](https://user-images.githubusercontent.com/7547222/36859655-4dd37c42-1d3c-11e8-9621-fc25cdda856c.png)

## Mailspring version: 
Auto updating snap, version 1.1.4.22d9f20d

## OS info:
![image](https://user-images.githubusercontent.com/7547222/36859942-3e4f2a7c-1d3d-11e8-966a-947108e1a0ac.png)

**Comment by bengotow** [comment]
Hey thanks for reporting this—it looks like Outlook isn't honoring the CSS properties on the image (I think we use max-width and max-height so you can choose images with different aspect ratios.) I'll see if I can get this fixed.

**Comment by bengotow** [comment]
Hey! This will be addressed in 1.2.1, which should be released in the next day or so. It'll require that you re-upload your image in the signature editor unfortunately. Stay tuned!
