### ISSUE TITLE
Can't sync Outlook

### ISSUE THREAD

**Issue by fakeid30** [Foundry376/Mailspring#74]
##### Are there any related issues?

https://github.com/Foundry376/Mailspring/issues/71
...

##### What operating system are you using?
Arch Linux
...

##### What version of Mailspring are you using?
https://aur.archlinux.org/packages/mailspring/
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
N/A
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Exchange
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![screenshot_20171007_194955](https://user-images.githubusercontent.com/26362832/31308470-e2a92666-ab66-11e7-8e74-1950fb89a0b0.png)

**Comment by bengotow** [comment]
This is caused by the AUR package replacing libsasl2. https://github.com/Foundry376/Mailspring/issues/13
