### ISSUE TITLE
An unexpected mailsync error occurred (3765269347) - win7

### ISSUE THREAD

**Issue by Luigi01** [Foundry376/Mailspring#740]
During installation while setting up my first email account (imap/smtp) the program halts after filling in all fields in the "set up your account" window and pressing the "continue" button. Listed in the window is the error as described above, the log file reads:

*****log-file*****
Waiting for Account JSON:

Waiting for Identity JSON:
info: Identity created at 1515524644 - using ID Schema 0

 ***
 *** A fatal error occurred during program execution.
 *** No details were provided about the error.
 ***
CREATE PROCESS FAIL: 
addr2line.exe -f -i -C -s -p -e "C:\Users\dehaan\AppData\Local\Mailspring\app-1.1.4\resources\app.asar.unpacked\mailsync" 75DDC54F 5B4645A5 0025FC83 0025BEC0 0029A01C 0027E99B 00288E8C 0028BACA 003A0B3C 7715343D 779A9832 779A9805
critical:  *** Stack trace:
 ***   RaiseException
 ***   CxxThrowException
 ***

critical:  *** Stack trace:
 ***   RaiseException
 ***   CxxThrowException
 ***
 *****end-log-file*****

Mailspring version: 1.1.4
OS: Windows 7 enterprise
Processor: i5 (3570)
RAM: 8Gb

**Comment by bengotow** [comment]
Hey folks - merging this in to #397
