### ISSUE TITLE
mailspring 1.1.4 at Linux kali 2017.2 ERROR for connect IMAP/SMTP

### ISSUE THREAD

**Issue by crisnello** [Foundry376/Mailspring#744]
![captura de tela de 2018-03-07 18-07-02](https://user-images.githubusercontent.com/839024/37118257-6cb2bab0-2232-11e8-98ad-4ddecbb076d4.png)
I was able to connect once to IMAP / SMTP from the company where I work, but I had to reinstall linux and now it does not connect any more

From Error 17 Location 10, but I already checked and everything is correct with the certificates

problem in SMTP authentication

//--------------------------------------------------------

----------IMAP----------
* OK The Microsoft Exchange IMAP4 service is ready.
1 STARTTLS
1 OK Begin TLS negotiation now.
2 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN IDLE NAMESPACE LITERAL+
2 OK CAPABILITY completed.
3 LOGIN "filipe.negrello" "*********"
3 OK LOGIN completed.
4 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=NTLM AUTH=GSSAPI AUTH=PLAIN IDLE NAMESPACE LITERAL+
4 OK CAPABILITY completed.
5 NAMESPACE
* NAMESPACE (("" "/")) NIL NIL
5 OK NAMESPACE completed.
6 LIST "" "*"
* LIST (\HasNoChildren) "/" Anota&AOcA9Q-es
* LIST (\Marked \HasNoChildren) "/" INBOX
* LIST (\HasNoChildren) "/" "Caixa de sa&AO0-da"
* LIST (\Marked \HasNoChildren) "/" Calend&AOE-rio
* LIST (\HasNoChildren) "/" Contatos
* LIST (\HasNoChildren) "/" Di&AOE-rio
* LIST (\HasNoChildren) "/" Enviados
* LIST (\HasNoChildren) "/" "Itens Enviados"
* LIST (\HasNoChildren) "/" "Itens Exclu&AO0-dos"
* LIST (\HasNoChildren) "/" "Lixo Eletr&APQ-nico"
* LIST (\HasChildren) "/" Mailspring
* LIST (\HasNoChildren) "/" Mailspring/Snoozed
* LIST (\HasNoChildren) "/" "Mensagens enviadas"
* LIST (\HasNoChildren) "/" "Mensagens exclu&AO0-das"
* LIST (\HasNoChildren) "/" Rascunhos
* LIST (\HasNoChildren) "/" Tarefas
* LIST (\HasNoChildren) "/" Trash
6 OK LIST completed.

----------SMTP----------
220 holanda.cits.br Microsoft ESMTP MAIL Service ready at Wed, 7 Mar 2018 18:06:54 -0300
EHLO cits-crisnello
250-holanda.cits.br Hello [10.0.1.170]
250-SIZE 20971520
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH GSSAPI NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250-XEXCH50
250 XRDST
STARTTLS
220 2.0.0 SMTP server ready
EHLO cits-crisnello
250-holanda.cits.br Hello [10.0.1.170]
250-SIZE 20971520
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH GSSAPI NTLM LOGIN
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250-XEXCH50
250 XRDST

SMTP Last Response Code: 250

SMTP Last Response: holanda.cits.br Hello [10.0.1.170]
SIZE 20971520
PIPELINING
DSN
ENHANCEDSTATUSCODES
AUTH GSSAPI NTLM LOGIN
X-EXPS GSSAPI NTLM
8BITMIME
BINARYMIME
CHUNKING
XEXCH50
XRDST

mailsmtp Last Error Code: 17

**Comment by strepkov** [comment]
Version 1.2.1, Ubuntu 18.04, have the similar problem :( 

----------SMTP----------
220 mail.rwth-aachen.de Microsoft ESMTP MAIL Service ready at Thu, 10 May 2018 12:50:30 +0200
EHLO streug-pc
250-mail.rwth-aachen.de Hello [134.61.100.1]
250-SIZE 41943040
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-AUTH GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250 CHUNKING
STARTTLS
220 2.0.0 SMTP server ready
EHLO streug-pc
250-mail.rwth-aachen.de Hello [134.61.100.1]
250-SIZE 41943040
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH GSSAPI NTLM LOGIN
250-8BITMIME
250-BINARYMIME
250 CHUNKING

SMTP Last Response Code: 250

SMTP Last Response: mail.rwth-aachen.de Hello [134.61.100.1]
SIZE 41943040
PIPELINING
DSN
ENHANCEDSTATUSCODES
AUTH GSSAPI NTLM LOGIN
8BITMIME
BINARYMIME
CHUNKING


mailsmtp Last Error Code: 17

mailsmtp Last Error Location: 10

**Comment by bengotow** [comment]
Hey folks—this should be fixed in the next release when we address #341. Stay tuned!

**Comment by bengotow** [comment]
Hey folks! This has shipped in 1.4.1. You can get the update automatically if you're using the Mac and Windows versions, or the Linux snapcraft release, and you can also download it from https://getmailspring.com/download.  I'm going to go ahead and close this and we'll re-open it if necessary. Thanks—enjoy the app!
