### ISSUE TITLE
No confirmation/warning on folder deletion

### ISSUE THREAD

**Issue by SharkAttack99** [Foundry376/Mailspring#746]
Using Mailspring 1.1.5 on MacOS 10.13.2. I right clicked on a folder and intended to click "Rename Folder". However, I mis-clicked and hit "Delete Folder". There was no confirmation or warning, just POOF - bye, bye emails. I tested again and this is consistent behavior. There should absolutely be an confirmation/warning dialog.

On a related note, without a server backup, if anyone has any idea of how to recover emails from an accidentally deleted folder I would LOVE to know.

**Comment by bengotow** [comment]
Ahh man that sucks! I'm sorry you lost your emails—we can definitely add a confirmation to this.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
