### ISSUE TITLE
Windows auto-updater will not autoupdate 1.1.4 to 1.1.5

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#752]
Windows 10 x64 - Mailspring 1.1.4 

With the update module, I couldn't perform the upgrade to install the latest version 1.1.5.
I had this same problem on my 2 computers.

I have been obliged to download the version 1.1.5 of Mailspring.

1/ I clicked on "Check for update"
2/ I saw this on the screen:
![mailspring_201_2018-03-09_13-26-20](https://user-images.githubusercontent.com/31793920/37208581-23d51f24-23a2-11e8-8a9b-dede04e6b4d4.png)

3/ some time later, (1 or 2 minutes)
this error message is not displayed immediately.
![update_error_2018-03-09_13-17-21](https://user-images.githubusercontent.com/31793920/37208677-831e35ce-23a2-11e8-94fc-0f4480e20b0a.png)

4/ when I was with version 1.1.4, I could repeat this problem and on my 2 computers.
My internet connection was well activated and I could go on the internet without any difficulty.

Yesterday I had this problem with the first computer and today with the second computer.
Yesterday and today, I was forced to update Mailspring to download the installation file 1.1.5.

**Comment by LightSnowDev** [comment]
Same for me. Here is the SquirrelSetup.log file:

[SquirrelSetup.log](https://github.com/Foundry376/Mailspring/files/1797950/SquirrelSetup.log)

**Comment by Ansem93** [comment]
Same error here, is it fixed in 1.1.5?

**Comment by bengotow** [comment]
Hey! Thanks for reporting this folks—this has been fixed with the release of 1.2.0

**Comment by franco27** [comment]
I confirm it's resolved!
