### ISSUE TITLE
Guys, you have a lot of, really a lot of bugs

### ISSUE THREAD

**Issue by AlisaBagrii** [Foundry376/Mailspring#758]
<!--
First of all, I am really very sad that Nylas is not maintained anymore. Mailspring has really a lot of bugs and happens to be less comfortable.

- the links didn't work properly. Ok, you corrected this bug a bit. But still, they look differently. So the link that is created inside the message, is underlined, and the link that is copied from outside, is blue bold. 
- if you compile the email from different sources, the text is just a forest of different fonts, that you have to spend time and correct. It really takes a lot of time, guys. 
 - when you switch accounts, you have to be very attentive, as Mailspring forgets to switch your signatures.!
 - the spellsheck is broken. It is like a trick - it shows that smth is wrong with the word, when go with the mouse to the word, it stops showing. I think you just have to guess, what is wrong. Or easier just rewrite the word.
 - And the last drop, it sends empty messages. You spend time, compile the message, and then the person gets just some empty email, even not from the account you sent. It happens once in 10 emails. It is a lot.
![image](https://user-images.githubusercontent.com/17273747/37342498-04dec180-26c5-11e8-8c60-f787d34c2f4b.png)
![mailspring bug](https://user-images.githubusercontent.com/17273747/37342568-407c7f02-26c5-11e8-9ae2-d0042339ff8a.png)
![mailspring bug 1](https://user-images.githubusercontent.com/17273747/37342610-6b5e51e6-26c5-11e8-9e03-29ca4053625a.png)

##### Are there any related issues?
I guess there are lot more. but they are still not solved.
##### What operating system are you using?
Windows

##### What version of Mailspring are you using?
the last

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no, it relates to the maintenance of Mailspring

##### Is the issue reproducible with a particular attachment, message, signature, etc?
sure

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
no, it relates to Mailspring

**Comment by tylerwhipple** [comment]
Please delete this, what does it help? It is an open source project. Fix some yourself or use something else.
