### ISSUE TITLE
Change defaults for FastMail accounts

### ISSUE THREAD

**Issue by duckwork** [Foundry376/Mailspring#759]
I installed Mailspring recently and went to add my Fastmail account.  It threw up an error, and when I checked the output I saw a diagnostic message from Fastmail about how they don't use messagingengine.com any more.  I changed to set up an IMAP/SMTP server and put in the credentials from [fastmail's site](https://www.fastmail.com/help/technical/servernamesandports.html?u=39e140bd#email) and it worked swimmingly.

Thought yall would want to know as this could trip up some new users.  I had to change the IMAP and SMTP servers and change SMTP's port and auth method to SSL/TLS from STARTTLS.

##### What version of Mailspring are you using?
1.1.5-5834c99f

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Fastmail

**Comment by kirkbeard** [comment]
I had this issue when I setup my Fastmail accounts a month ago. I've been meaning to submit a PR to fix it, but haven't got around to it yet.

**Comment by bengotow** [comment]
Thanks for pointing this out! fixed on master, will ship this soon.

**Comment by duckwork** [comment]
Thank you!
