### ISSUE TITLE
Parts of or whole thread is missing in forwarded mail

### ISSUE THREAD

**Issue by Dekadinious** [Foundry376/Mailspring#761]
When my colleague on macOS High Sierra forwards a thread to me, only the first or sometimes the first few messages appear in the thread. When clicking the [...] button, the e-mail expands by a few pixels but there is no content there.

I am not sure how to provide error logs, but please advice and I will upload it here.

##### Are there any related issues?
Somewhat related I think: https://github.com/Foundry376/Mailspring/issues/192
...

##### What operating system are you using?
macOS High Sierra 10.13.2 is forwarding to Windows 10

##### What version of Mailspring are you using?
1.1.5
-

**Bug?**
Yes.

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Not certain. Try to forward a large thread and see if every message in that thread appears in the forwarded message.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
