### ISSUE TITLE
	 as usual bug 17 in new version

### ISSUE THREAD

**Issue by crisnello** [Foundry376/Mailspring#765]
![captura de tela de 2018-03-14 09-31-20](https://user-images.githubusercontent.com/839024/37402636-17c96cea-276b-11e8-8e5f-ac20fd2b119d.png)

##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of Mailspring are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by crisnello** [comment]
When you solve this problem, I will only use this

**Comment by bengotow** [comment]
Merging into #620
