### ISSUE TITLE
Multiple "open tracking" notifications

### ISSUE THREAD

**Issue by intradesign** [Foundry376/Mailspring#766]
The "open tracking" notifications show up many times – it seems to be each time an email is opened ... again and again.

Especially in threads containing multiple messages with "open tracking" enabled there seems to be a notification for each single message when the thread is opened by the receiver ... on each open again and angain...

<img width="264" alt="mailspring 2018-03-15 07-42-30" src="https://user-images.githubusercontent.com/21263208/37448363-57744c46-2826-11e8-93c9-7a0217a707ce.png">

Yesterday I ended up with about 120 notifications for a thread containing 19 messages.

Wouldn`t it be better to be informed about an "open action" only for the very first time the message is openend?
I find these multiple notifications very annoying. No problem to count further opens but without notification please.

Or is it a configuration problem?

Thanks and best regards
Timo

**Comment by ElectricCookie** [comment]
I think a log would be great but only 1 notification

**Comment by bengotow** [comment]
Hey! I've added a new setting under Preferences > General > Notifications that allows you to turn off repeated notifications - so you only get one link click or open notification for each recipient. (If they open the email again, you don't get another notification.) Hope that helps! The release will ship in the next few days.

**Comment by bengotow** [comment]
Hey folks—this shipped in version 1.3.0. The app should have auto-updated by now, but if not you can download the latest release from https://www.getmailspring.com/download. Enjoy!
