### ISSUE TITLE
Sorry, we had trouble logging you in.

### ISSUE THREAD

**Issue by ZakharH** [Foundry376/Mailspring#77]
Tried logging in using gmail. Authenticated in my browser, then got this error

/usr/share/mailspring/resources/app.asar.unpacked/mailsync.bin: /usr/lib/libsasl2.so.2: no version information available (required by /usr/share/mailspring/resources/app.asar.unpacked/mailsync.bin)

Waiting for Account JSON:

Waiting for Identity JSON:

{"error":"Identity is missing required fields."}

**Comment by marek287** [comment]
Same problem with Arch Linux

**Comment by rezhajulio** [comment]
I also had the same problem

**Comment by wgaonar** [comment]
Yes, the same problem by here

**Comment by Dobbie03** [comment]
I have an error with Gmail on Arch with an error of "Certificate Error (IMAP)"

**Comment by bengotow** [comment]
Hey folks—are you installing via the AUR in that other Github issue (#13)? The folks there seem to be replacing libsasl2.so.2 and then renaming it to look correct, (which will produce that `no version information available issue`, since it's not actually the correct version). Merging into #13.

**Comment by Hannibalus** [comment]
Hi, same problem with KDE neon.

**Comment by Abdalla124** [comment]
Hello, same issue on Mint Linux 18.2.

**Comment by byoms23** [comment]
For those who are trying to use Mailspring with KDE, I just found that it is using libsecret, a library to manage secrets on Gnome, which it isn't supported by KWallet. I just installed `gnome-keyring` and it works.

For more info, check in comment of NeroBurner in https://github.com/lbryio/lbry-app/issues/386
