### ISSUE TITLE
any plans to support deleting individual mails from within a thread

### ISSUE THREAD

**Issue by rykr** [Foundry376/Mailspring#770]
Sometimes I'm on a long email thread and I like to delete emails from within the thread without deleting the original email or I might keep just selected emails from the thread.  Any thought on this type of feature?

**Comment by bengotow** [comment]
Hey! Thanks for pointing out the other issue @ohynek96 — I'm gonna merge these together. This definitely will be added at some point - the biggest blocker is that Mailspring's "conversation" UI doesn't have a selected message concept yet.
