### ISSUE TITLE
Problems syncing an Office365 account: Retrieval using the IMAP4 protocol failed

### ISSUE THREAD

**Issue by vsanchez** [Foundry376/Mailspring#78]
##### What operating system are you using?
Linux, but I have tried in the past with nylas-mail in windows and Mac and had a similar behavior (but I had not noticed the messages in the draft folder).

##### What version of Mailspring are you using?
Latest version as of 10/7/2017 (I cannot find the version ... sorry)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
An specific account in Office 365 (not in others)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

The problem happens with a particular account that Never finishes syncing and uses a lot of CPU time. I experienced exactly the same problem with nylas-mail (not N1). The sycing problem seems to get stuck. Thinking that maybe there were malformed messages (it always seemed to get stuck in around the same messages) y moved them and the problem has been minimized. However, messages seem to be missing.  Now I am finding this messages in the "draft" folder:
(a Draft message "To: me" from the "Microsoft Exchange Server @.MISSING-HOST-NAME.)

Subject: Retrieval using the IMAP4 protocol failed for the following message: 4

The server couldn't retrieve the following message: 

Subject: "Ricardo Teran S." 
From: "Not available" ("Not available") 
Sent date: 2/14/2017 1:05:22 PM 

The message hasn't been deleted. You might be able to view it using either Outlook or Outlook Web App. You can also contact the sender to find out what the message says.

Very strange but it does not seem to happen in Thunderbird or Hiri.

**Comment by bengotow** [comment]
Hey @vsanchez — Mailspring's sync engine was changed in 1.0.7 so that message fetch failures no longer block the account from syncing correctly, and a bunch of errors have been fixed. Let me know if you see this in the latest version.

**Comment by presianbg** [comment]
Hi,

I just found that wonderful mail client, but it's not working well with my O365 account.
Mailspring is consuming a lot of CPU and not syncing Calendar and Contact folders as @vsanchez described:

![image](https://user-images.githubusercontent.com/2163486/42346918-d8061cd4-80ac-11e8-83c7-9385282d16a3.png)

This is latest v.1.2.2 and up-to-date Arch Linux

**Comment by rbenal** [comment]
> Hi,
> 
> I just found that wonderful mail client, but it's not working well with my O365 account.
> Mailspring is consuming a lot of CPU and not syncing Calendar and Contact folders as @vsanchez described:
> 
> ![image](https://user-images.githubusercontent.com/2163486/42346918-d8061cd4-80ac-11e8-83c7-9385282d16a3.png)
> 
> This is latest v.1.2.2 and up-to-date Arch Linux

Same problem here V.1.5.5 Arch Linux
