### ISSUE TITLE
Infrastructure: Mailspring not starting - service unavailable HTTP 503

### ISSUE THREAD

**Issue by Conspir3D** [Foundry376/Mailspring#783]
Due to a problem with the server, mailspring is not able to start because it can'T login to mailspring service.

That is one of the reasons why a "cloud service" within a mailclient is a bad idea, even if i understand the benefits from such a service.

This "bug" (more a behaviour) is one of the main reasons why you can't use mailspring at productive envirpments like companies.

Do you plan to release a "cloud free" version of mailspring?

**Comment by bengotow** [comment]
Hey! Sorry for the hassle—there's been a pretty big uptick in daily active users recently and a misconfiguration of the server's database connection pooling caused downtime this week. Should be fixed now!

For what it's worth, once you install Mailspring and sign in, the app works without a connection to the Mailspring service - it just won't sync your snoozed emails / reminders / read receipts. We're not planning a cloud-free version - a good chunk of the roadmap is actually more features that build on IMAP and do cool stuff that requires the cloud.
