### ISSUE TITLE
Viewing a message in spam folder should not load remote images

### ISSUE THREAD

**Issue by emadow** [Foundry376/Mailspring#784]
Opening a message in my spam folder should not fetch remote images regardless of the _automatically load images in viewed messages_ preference.

----
##### What operating system are you using?
MacOS High Sierra

##### What version of Mailspring are you using?
1.1.5

--

**Bug?**
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes, most of them.

**Comment by bengotow** [comment]
Ahh I think this would be great—didn't realize this was a feature of other clients. Went ahead and adjusted the plugin logic in 0f265dfa963d15fb89f8a0730faa9c210ec4ca81 so it'll be fixed in the next release.

**Comment by emadow** [comment]
@bengotow amazing 🎉 

Initially I was going to dig in and create a PR myself but that turned out to be too ambitious -- no way I had a grasp of this codebase in 10 minutes.

Thank you!

**Comment by bengotow** [comment]
This has shipped in 1.2.2 and 1.2.3. Thanks for reporting this!
