### ISSUE TITLE
Copy / Paste

### ISSUE THREAD

**Issue by intradesign** [Foundry376/Mailspring#787]
Hitting CMD+C with nothing marked copies "nothing" into clipboard.

I just wanted to copy a text from a draft that I wanted to delete and paste it into another draft. Accidentially I hit CMD+C instead of CMD+V. The result was, that my previously copied text disappeared from clipboard.

I double-checked other apps: Hitting CMD+C with nothing to copy normally does not clear the clipboard.

**Comment by bengotow** [comment]
Hey! Thanks for catching this—I'm able to reproduce it and I'll get it fixed ASAP. The weirdest thing is that this seems to be default behavior in Electron but not in it's parent Chromium project.

**Comment by bengotow** [comment]
This has shipped in 1.2.2 and 1.2.3. Thanks for reporting this!
