### ISSUE TITLE
Blurry font on Ubuntu 16.04

### ISSUE THREAD

**Issue by peterLaurence** [Foundry376/Mailspring#79]
Hi, 

On Ubuntu 16.04, Mailspring 1.0.2, the font used is :
* different from the Ubuntu font used by the system
* too small and blurry

This is the only thing i have to say so far. Overall, Mailspring looks promising.

**Comment by bengotow** [comment]
Hey @peterLaurence — could you attach a screenshot? I'm not sure if you're seeing something incorrect or not, actually. Mailspring does use a different font than Ubuntu but it shouldn't look blurry.

**Comment by peterLaurence** [comment]
I'm not sure if you will see something but let's try. On the left you can see icons on my desktop (the font is perfect), on the right you can see Mailspring.

![screenshot](https://user-images.githubusercontent.com/15638794/31314774-748824fe-ac09-11e7-8dc7-dced14669ae5.png)

**Comment by peterLaurence** [comment]
@bengotow Do you see the issue in my screenshot?

**Comment by bengotow** [comment]
Hey @peterLaurence — this is super interesting, my test machine is Ubuntu as well but it's not as blurry. It looks like they've removed the CSS options from Chromium / Electron that used to allow us to control font ant-aliasing (see https://github.com/atom/atom/issues/6681). I also tried changing the `font-family` on the `nylas-workspace` element in the DOM tree to `system-ui`. Would be curious to see if that makes it less blurry for you—it didn't have any effect for me, but it also wasn't as blurry to begin with!

**Comment by peterLaurence** [comment]
Hey @bengotow  -- it works great for the list of email (the system font is applied and its perfect, though a little too small), but not for individual emails (see my screenshot)
![capture du 2017-10-15 10-37-17](https://user-images.githubusercontent.com/15638794/31583160-71990af6-b195-11e7-881a-cbc470f3018c.png)

**Comment by leonelprofe** [comment]
Hi there.

Same problem here. Blurry fonts.

The first version that I installed (I do not remember which) rendered well the fonts but some after this issue showed up.

I am using Ubuntu 17.04.

In any case, great job. I have been looking for a Thunderbird replacement and Mailspring is perfect.

Thanks a lot.

**Comment by peterLaurence** [comment]
Hi @bengotow,
In the new version 1.0.11, setting `system-ui` to `font-family` on the `nylas-workspace` solves the blurry issue. And ofc we get Ubuntu font which fits better with the other apps.
If we could have an option to set the font size it would be perfect (i find the font a little too small).

**Comment by bengotow** [comment]
Hey! Awesome @peterLaurence thanks for following up. There's a new option in Preferences > Appearance that allows you to change the size of the entire UI as well. Gonna mark this as resolved!

**Comment by peterLaurence** [comment]
@bengotow Yes i noticed and use it already. Thanks for the feature!
