### ISSUE TITLE
Mailspring 1.2.0 Froze, Now Fails to Launch

### ISSUE THREAD

**Issue by batshitbetty** [Foundry376/Mailspring#798]
**Are there any related issues?**

Not as far as I can find in reviewing open issues.

**What operating system are you using?**

Ubuntu 16.04 Xenial Xerus, in the Gnome desktop environment.

**What version of Mailspring are you using?**

Version 1.2.0.  Originally installed SNAP version.  Removed and reinstalled .deb package.

**_Bug?_**

**Do you have any third-party plugins installed? If so, which ones?**

No third-party plugins or themes installed.

**Is the issue related to a specific email provider (Gmail, Exchange, etc.)?**

The issue isn't account-specific.

**Is the issue reproducible with a particular attachment, message, signature, etc?**

I'm unsure if others would be able to reproduce it.  Steps taken as follows.

1. Computer woken up after four hours of sleep.
2. Mailspring found frozen.  Menu visible, all other areas of app blank white.
3. Mailspring closed normally; no need to force close or kill the app.
4. Mailspring attempts to launch, bringing up the app name in the menu bar and momentarily taking system resources.  However, app terminates prior to launching.
5. Rebooted system.  Issue persists.
6. Uninstalled SNAP version.
7. Downloaded .deb install file.  Install failed due to missing dependencies `libsecret-1-dev` and `git`.
8. Attempted `sudo apt-get install` for both dependencies; install failed.
9. Dependencies installed successfully via `sudo apt-get -f install`.
10.  Mailspring 1.2.0 .deb successfully installed via `sudo dpkg -i`.
11.  Back to step 4 - app still refuses to launch.

It worked fine this morning.  Any help you can offer will be greatly appreciated!

**Comment by bengotow** [comment]
Hey! Thanks for reporting this and documenting everything. I'm trying to reproduce this on a few Ubuntu VMs now and will keep you posted!

**Comment by bengotow** [comment]
Hey! I haven't been able to reproduce this yet - going to leave this issue open and see if we can collect a few more reports. Could you try launching Mailspring from the command line and see what output appears? You could also try launching it with `mailspring --disable-gpu`, which has resolved some odd linux issues in the past. It'd also be good to double check that you're not out of disk space, though that should produce a better error message...

**Comment by vivaldi-va** [comment]
getting the following on Ubuntu 16.04 when launching from the command line:

```
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
```

`--disable-gpu` produces the same result

**Comment by nielran** [comment]
I have same error messages than @vivaldi-va  on Ubuntu 17.10.

I have mailspring version 1.2.0, installed the 03.04.2018 via snap.

**Comment by fcastilloec** [comment]
I'm using Ubuntu 16.04 and I've never installed the app using snap. I upgrade to v1.2.0 and I don't have any problems starting Mailspring. This might be related to snap only.

**Comment by vivaldi-va** [comment]
Seems like an issue with updating to 1.2.0 via snap, seems to work for me after uninstalling and reinstalling again.

**Comment by Daxten** [comment]
same issue with snap

**Comment by nelas** [comment]
Same here with snap. When I run on the terminal I get:

```bash
$ mailspring 
ln: failed to create symbolic link '/home/user/snap/mailspring/202/.config/gtk-2.0/gtkfilechooser.ini': File exists
```

**Comment by batshitbetty** [comment]
@bengotow - thanks for spending so much time trying to duplicate this, and thanks to everyone else for the contributions!  Here's where things stand.  From terminal:

`mailspring --disable-gpu
Running database migrations
App load time: 274ms

{"error":null}
Manual update check (updates.getmailspring.com/check/linux/x64/1.2.1-7e7447b6/50872b2a-bd32-44eb-a994-9c2b8b43d90f/stable) returned 204`

On running the command the first time, it launched, made me sign in with my Mailspring ID, and showed me a clean slate with none of my accounts connected.  It allowed me to connect one account and I assume won't have a problem with the rest.  It prompted me to download the 1.2.1 update.

1.2.1 .deb file downloaded, opened, and installed through Software Manager.  It still won't launch normally, however running `mailspring --disable-gpu` launches it.  On subsequent launches, it appears linked accounts are retained.

It's functional.  Now I'll be grateful for getting my clicky icon back.  Thanks again!

**Comment by batshitbetty** [comment]
@bengotow - One last update for this issue, which seems now to be a non-issue.

I rebooted after running Mailspring using the `mailspring --disable-gpu` command.  On doing so, the newer, manual .deb install auto-launched itself, prompting me to set up accounts again.  I set up the most important accounts I need to monitor, thinking I'd wait for this issue to be resolved before setting the rest up.

Just now, I closed that instance of Mailspring and tried launching via the icon in my launch bar.  It opened perfectly, with settings exactly as I originally had them, and all accounts already set up.  It caught up to the current status of my IMAP accounts and is functioning as intended.

Whatever the bug was, it appears to have wandered off in search of tastier prey.  

Thank you for your help with this issue!

**Comment by mcolinp** [comment]
I don't think this is isolated to Ubuntu or Linux. I'm experiencing a similar situation on Windows 10. While mine did not freeze; once I installed it and setup 2 email accounts, (1 Gmail, the other IMAP), after closing the program; it fails to open. the only way I can get it to open again is if I unistall; delete all the preferences in AppData; then re-install. Then it is the same cyclical cycle of setup and then no launch . . .

**Comment by palbergstrom** [comment]
Same problem. Jambazishvili's solution worked for me. Thanks :+1:

**Comment by benjbt** [comment]
New install of Fedora 28, installed Mailspring from snap but fails to launch.

**Comment by Awwkaw** [comment]
Insalled mailspring to ubuntu using snapd

I get the following error when trying to launch from terminal:
```

/snap/mailspring/244/bin/desktop-launch: line 185: /home/tekc/snap/mailspring/common/.config/user-dirs.dirs: No such file or directory
cp: cannot create regular file '/home/tekc/snap/mailspring/common/.config/': Not a directory
/snap/mailspring/244/bin/desktop-launch: line 188: /home/tekc/snap/mailspring/common/.config/user-dirs.dirs.md5sum: No such file or directory
/snap/mailspring/244/bin/desktop-launch: line 188: /home/tekc/snap/mailspring/common/.config/user-dirs.locale.md5sum: No such file or directory
Gtk-Message: Failed to load module "appmenu-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
```

I also posted the error as a question on [askubuntu](https://askubuntu.com/questions/1082521/mailspring-snap-not-launching)

**Comment by bengotow** [comment]
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of Electron and/or snapcraft. Feel free to bump this or re-open a new issue if you run in to this again.
