### ISSUE TITLE
Several of your accounts are having issues syncing

### ISSUE THREAD

**Issue by agurz** [Foundry376/Mailspring#8]
##### Are there any related issues?

No, AFAIK

##### What operating system are you using?
macOS Sierra 10.12.6

##### What version of Mailspring are you using?
1.0.0-20839f9b

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
iCloud and custom IMAP

---

Several seconds after Mailsprint starts all my accounts stop being synced and this alert appears:

<img width="263" alt="screen shot 2017-10-03 at 3 38 25 pm" src="https://user-images.githubusercontent.com/13837769/31142580-13f17534-a851-11e7-8cbc-8716a5d2bd72.png">

Here is the console output:

<img width="1426" alt="screen shot 2017-10-03 at 3 02 45 pm" src="https://user-images.githubusercontent.com/13837769/31142497-d9376688-a850-11e7-90b9-5f955d60fb48.png">

And here in plain text: 
[SyncWorker crashed.txt](https://github.com/Foundry376/Mailspring/files/1353466/SyncWorker.crashed.txt)

Finally the entire console output: 
[1507056316741.log](https://github.com/Foundry376/Mailspring/files/1353479/1507056316741.log)

**Comment by bengotow** [comment]
Hey @agurz thanks for reporting this - it looks like you must have an email in your accounts that doesn't have a "header message id". I'm adding some improved error handling that should fix this in the next release. Stay tuned!

**Comment by LiHRaM** [comment]
Hey. I'm also having trouble syncing accounts that work fine in nylas-mail and nylas-mail-lives.
Is this problem a part of the C++ sync-engine?

**Comment by bengotow** [comment]
Version 1.0.1 started shipping a few minutes ago, so this should be fixed now. Let me know if you still see this after updating!

**Comment by agurz** [comment]
Hey! Thanks for bringing this awesome email client back to life! This seems to be fixed, but I'm now experiencing another issue with syncing (I'll open another issue after collecting some more data).

**Comment by karenachiketc** [comment]
I'm getting this issue. 
I'm on Ubuntu 17.10
Have installed mailspring as a snap package and I'm currently using v1.0.12
Please help.
