### ISSUE TITLE
Mailspring sync engine source?

### ISSUE THREAD

**Issue by kirbyfan64** [Foundry376/Mailspring#80]
Sorry, this is a really random "issue". However, I noticed that, when I click the *mailspring-sync* directory in the GitHub file browser, I end up at a 404. Is the repository private for some reason, or...?

I have to say, a maintained, lighter version of Nylas sounds awesome!

**Comment by Modelmat** [comment]
@kirbyfan64 See Issue #24

**Comment by bengotow** [comment]
Yep—we may open source the new sync engine in the future, but for now it's closed source - more info in the links above!
