### ISSUE TITLE
Right-hand Menu in Ubuntu theme is ugly

### ISSUE THREAD

**Issue by fcastilloec** [Foundry376/Mailspring#801]
##### Are there any related issues?
I couldn't find any other issues related to the Ubuntu theme

##### What operating system are you using?
Ubuntu 16.04 with Unity

##### What version of Mailspring are you using?
`1.2.0`

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
none

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no

##### Is the issue reproducible with a particular attachment, message, signature, etc?
no

Here's a screenshot of what the right-hand menu looks under Ubuntu 16.04:
![selection_003](https://user-images.githubusercontent.com/1280530/38298294-fed71cb8-37c4-11e8-92c1-590e6a8d50f1.png)
The colors of the 3 horizontal lines that represent the menu should be a different color, one that will contrast with the background (white?)
All other themes have this button's background and the horizontal lines with enough contrast to tell them apart.

**Comment by bengotow** [comment]
Hey! Good catch—this is pretty weird, but it definitely seems like it's a theme issue. If you have a few minutes and want to poke at the CSS, you can open the Chrome Developer Tools in the app by pressing Ctrl-Option-I, and the "inspect element" tool in the "Inspect" panel will help you see how the CSS is different. The ubuntu theme lives here, so we might just need to tweak that: https://github.com/Foundry376/Mailspring/blob/master/app/internal_packages/ui-ubuntu/styles/ui-variables.less

**Comment by bengotow** [comment]
This will be fixed in the next release 👍 stay tuned!

**Comment by fcastilloec** [comment]
This has been fixed in the latest release. Thanks!!!
Now I just have to open a new issue so the titlebar buttons are placed on the proper side, following my OS settings (i.e. right side, and not left as it currently is)
