### ISSUE TITLE
The e-mail doesn't appear completely

### ISSUE THREAD

**Issue by raulcraveiro** [Foundry376/Mailspring#802]
Some e-mails doesn't appear completely. I have to use the "Print thread" to see the full e-mail.

##### What operating system are you using?
Windows 10 Home

##### What version of Mailspring are you using?
1.2.1-7e7447b6

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![Mailspring](https://user-images.githubusercontent.com/5623492/38307158-36df5188-37e9-11e8-80b5-1befb2363de1.png)

I can't see the full e-mail there. But when I use the "Print thread":

![Print thread](https://user-images.githubusercontent.com/5623492/38307278-91410d92-37e9-11e8-946c-23d2a62f14be.png)

It shows the whole email.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this has finally been fixed in 4f1358905177ddda3eebf8b8ac076f6de81fcb9d and it should ship in the next day or two. Stay tuned!

**Comment by bengotow** [comment]
Hey folks—this shipped in version 1.3.0. The app should have auto-updated by now, but if not you can download the latest release from https://www.getmailspring.com/download. Enjoy!
