### ISSUE TITLE
Notify users about inconsistent fonts/font-sizes

### ISSUE THREAD

**Issue by colinking** [Foundry376/Mailspring#806]
**Feature Request**

I often see folks copy+paste text into an email and the pasted text ends up in a different font/font-size/color than the remainder of the email. Besides automatically updating pasted text to match the font settings of the email, it would be useful to notify users that the text in their email is not consistent (either directly in the editor or before sending the email).

F.e. "The text in your email is in various fonts, do you still wish to send this email?"

However, it would likely need to ignore the signature.

##### Does this feature exist in another mail client or tool you use?
No, not that I've seen. Some inspiration from Mailspring's notification when the recipient doesn't match the addressee.

**Comment by kirkbeard** [comment]
What about users who intentionally use different font colour/family/sizes throughout the email?

On macOS, when copying text from another source (i.e., a website), you can "Paste and Match Style" using <kbd>CMD</kbd> + <kbd>Shift</kbd> + <kbd>v</kbd>. Maybe other operating systems have a similar feature?

**Comment by jhult** [comment]
On Linux/Chrome: `CMD` + `Shift` + `v` = Paste as plain text
