### ISSUE TITLE
What domain should Message-ID contain?

### ISSUE THREAD

**Issue by jhult** [Foundry376/Mailspring#809]
In [app/src/flux/stores/draft-factory.es6](../blob/master/app/src/flux/stores/draft-factory.es6), Message-ID (headerMessageId) contains _@getmailspring.com_. Should this contain the domain used in the _from address_ instead?

##### Are there any related issues?

No that I found.

##### What operating system are you using?
Linux - 4.8.0-53-generic 16.04.1-Ubuntu SMP

##### What version of Mailspring are you using?
1.2.0-fdf53c79b

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes, any message.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Not sure

**Comment by bengotow** [comment]
Hey! So technically, according to the IMAP spec, I think this should actually be a machine address, like `bens-macbook-pro.local`. It was actually changed recently to deliberately obscure that hostname: https://github.com/Foundry376/Mailspring/commit/ed3f58d872528bf2a741eeab19672abfc2e2db59.

It looks like Apple Mail uses your sending domain (eg `foundry376.com`) and the Gmail web UI uses `mail.gmail.com`, even if you're using Google Apps for Business and are sending from a custom domain.

It might be preferable to use the sending domain to hide the fact the user is using Mailspring, but it seems pretty much any domain-looking string can be used. Gonna close this for now as a bit of a wontfix, but if we come up with more reasons to change it I'd definitely welcome a PR!

**Comment by chadadair** [comment]
Hi @bengotow I believe this issue is causing my emails to be placed into recipients junk/spam folders. Are you able to look at changing this to the sending domain? There is another thread that mentions this issue too. https://github.com/Foundry376/Mailspring/issues/284

Thanks
