### ISSUE TITLE
Simple composer issue with typing an email address

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#814]
##### Are there any related issues?

...

##### What operating system are you using?
MacOS 10.13.3

##### What version of Mailspring are you using?
1.2.1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

This is a simple composer bug
1. Type an email address like "john.doe@gmail.com" in the message body
2. What I expected: creates link to full email address
3. What happens: only the part after the period ("doe@gmail.com" in this case) gets linked

**Comment by bengotow** [comment]
Wow good catch—thanks for reporting this. It looks like this is most likely an RegEx error in the Slate plugin I built for linkifying text as you type. Will see if I can get this fixed for the next release.

**Comment by bengotow** [comment]
This has shipped today in 1.2.3. Thanks for reporting it! It looks like there may still be issues with the regular expressions we're using for link- and email- detection when it comes to non-latin characters. (It doesn't autolink domain names with Japanese characters, for example.) I'll see if I can address that separately.
