### ISSUE TITLE
Sync errors everywhere

### ISSUE THREAD

**Issue by WanderingRaven** [Foundry376/Mailspring#815]
So for some reason I am having terrible sync issues today with my IMAP emails.  Sometimes they work, sometimes they don't, and they worked fine previously, and with no current issues on the hosting side.  I can check these same email accounts from a webmail option, my iphone, and other email programs.

##### Are there any related issues?
Not sure what the exact issue is (no clear error message), so not sure if anything related has been posted.

##### What operating system are you using?
Windows 8.1 Pro 64-bit

##### What version of Mailspring are you using?
1.2.1-7e7447b6

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None that I know of.  Didn't even know you could install plugins.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Only thing I could possibly think of is it has to do with syncing existing folders.  In Thunderbird I previously had an archive system that was organized by year.  I was looking in one of my accounts for the corresponding Mailspring folders, and that seems to be when all the sync issues started.  Every time I reconnect, it says connection successful, but then it gets hung up on syncing some of those Inbox.FolderName folders, some of which I didn't create.  For example, I didn't see any Archive folders in there, so I tried to rename one from Inbox.Trash.2018 to Inbox.Archive.2018 and it auto named it Inbox.Trash.Archive.2018 which I thought was odd.  Now it seems like it's hung up on that and other folders (which I didn't change, but did go into the "Folders" settings and looked at things to see if I could match them to my IMAP folders).  Also, when it is trying to sync some of these folders, and it gets hung up, it renders the entire email account useless - can't check, write, or read any emails.  Not sure how else to report anything, but it does mention sending a "crash report" to Mailspring, so I am hoping you are getting some of that data.  Let me know if I can provide anything else.

**Comment by WanderingRaven** [comment]
Another update.  I reverted this machine to the above version and it seems like the sync issues are resolved.  So it's something in one of the newer updates that was causing my issue.

**Comment by lazylionca** [comment]
I'll second this. I downloaded the latest Mailspring (1.2.2 ?) two weeks ago and imap syncing rarely if ever worked. 

I've used it on 1 macbook running osx and two windows 10 machines.

The Imap servers are mail.webfaction.com and our own self hosted zimbra.

What version did you revert to that worked @WanderingRaven ?

**Comment by simplewebs13** [comment]
I downloaded Mailspring v1.4.1 this past weekend. It appeared to be find except it takes longer that it should to sync with my emails. I'm on a Mac so I tested my exchange, g suite, and imap emails using Outlook 2016 Mac, Mac Mail, Newton Email, Exchange Online, and Mailspring. All the email clients sync almost at the exact moment mail comes in or I update the email, except Mailspring. It takes Mailspring 4 to 7 extra minutes to get new mail in the inbox, same time delay for deleting, moving, reading, emptying trash or junk folders... or updating in general. Can't figure out why but, I can't use something that does work in real time.

All my Apple devices are up to date and working great. So, if you have any suggestions I will gladly look at them.

**Comment by bengotow** [comment]
Hey folks! Thanks for filing this - there have been a whole bunch of sync improvements since this ticket was filed last year, could you try downloading the latest release (1.5.6) and see if the problems here still apply?

Mailspring may be a little slower than other clients while it performs "initial sync" (it downloads the headers of your messages and builds a search index), but once that is complete and it's not showing "Syncing your mailbox..." in the bottom left, new mail / changes / etc. should appear basically immediately.
