### ISSUE TITLE
Autmatically making emails important

### ISSUE THREAD

**Issue by Dilliaglio** [Foundry376/Mailspring#818]
##### What operating system are you using?
macOS Sierra

##### What version of Mailspring are you using?
1.2.1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N/A

##### Description
Emails are automatically being highlighted as important as they hit the inbox. Synced with Gmail and not important in there. Would like to remove the important tag automatically happening.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—that's definitely interesting... Mailspring shouldn't be automatically adding the Important label ever. With Gmail accounts, it displays the important flag that Gmail applies automatically based on it's machine learning heuristics.

I have one email account where it's gotten a bit aggressive and marks almost 80% of my mail as "important". You can stop it from doing that by unmarking some messages (to train it, so to speak), or if you find them super unhelpful, you can disable them in Mailspring from Preferences > General. Hope that helps!

**Comment by bengotow** [comment]
I'm gonna go ahead and close this, but if you find this is definitely happening on the Mailspring side somehow, let me know and I'll re-open!
