### ISSUE TITLE
Still having error displayed randomy while clicking on mail

### ISSUE THREAD

**Issue by Lyptik** [Foundry376/Mailspring#819]
Hello guys I think you did fix this with a previous feedback, but there here it is still or back again :)

v 1.2.1-5f
win10
Dark theme

Happens randomly when clicking on a mail sometimes

![image](https://user-images.githubusercontent.com/5172593/38509706-ffac5a42-3c22-11e8-8b61-7f60334e60d2.png)

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
