### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#82]
##### Are there any related issues?
No.
...

##### What operating system are you using?
Windows 10
...

##### What version of Mailspring are you using?
1.0.2
...

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No
...

##### My Problem:

1. I was on 1.0.1, and updating to 1.0.2 wasn't working, so I downloaded the installer manually.
2. When running this installer, it seemed to delete most of Mailspring (in `%localappdata%`), and then fully erased the installer (not in trash or anywhere)
3. I redownloaded the installer (again), installed, and I got error #14 on every boot
4. I then used the installer again, and it did Step 2.
5. I redownloaded it again, and now it's not doing anything whatsoever.

So I can't install nor user mailspring.

**Comment by bengotow** [comment]
Hey @Modelmat —open the Task Manager and make sure no copies of Mailspring or `mailsync` are running. It probably still had the mail database open. If you're not sure you can log out and log back in to be safe.

**Comment by Modelmat** [comment]
@bengotow Nope, there is nothing there.

**Comment by Modelmat** [comment]
Nope, still not working. 

What's really irritating is it has LOCKED ME OUT OF THE FOLDERS I DOWNLOADED IT TOO. I now can't access Downloads, Desktop & Documenta. Please help.

**Comment by bengotow** [comment]
Can you elaborate? How did it lock you out of those folders? The installer is the same packager used for Slack and Atom—it shouldn't have any adverse effects. You should definitely try restarting and see if anything on your system (antivirus, etc.) is interfering. If you figure it out and it's a problem with Mailspring please let me know!

**Comment by Modelmat** [comment]
Actually, it only occurs when copying files. It just states "Require Admins" then says "Cannot Copy" and doesn't help. It's really weird.

**Comment by Modelmat** [comment]
Ummm.. I finally got v. 1.0.4 working. Started again, and what do you know, ran and then the entire thing broke again.

**Comment by bengotow** [comment]
Hmm how is it breaking exactly when you run it?

**Comment by Modelmat** [comment]
It deletes the start menu shortcut, deletes Update.exe (in %localappdata\Mailspring), and then I can't start it. No processes show in task manager

**Comment by bengotow** [comment]
Can you try installing it, and then doing nothing else, and waiting a minute or so to see if Update.exe and the other files disappear? This sounds like it could be an antivirus product doing a scan and wiping the new files.

**Comment by Modelmat** [comment]
Aaah. Yes. I had silent mode on Avast, and It is the problem. Antivrus was the problem all along, so you might want to get Avast notified.
