### ISSUE TITLE
Fails to move to application folder on it's own. Mac OS 

### ISSUE THREAD

**Issue by EdwardDeaver** [Foundry376/Mailspring#821]
What operating system are you using?
MacOS Sierra 10.12.6

##### What version of Mailspring are you using?

I don't know. I downloaded the app on April 9th, 2018
**Bug?**

Error: Command failed: mv /private/var/folders/fh/2bl9zc9s4rg77j6qh39mykjc0000gn/T/AppTranslocation/DAF5EDAC-633F-44FA-850A-59AACAEEDA42/d/Mailspring.app /Users/edward/Applications/Mailspring.app
Error: Command failed: mv /private/var/folders/fh/2bl9zc9s4rg77j6qh39mykjc0000gn/T/AppTranslocation/DAF5EDAC-633F-44FA-850A-59AACAEEDA42/d/Mailspring.app /Users/edward/Applications/Mailspring.app
##### Do you have any third-party plugins installed? If so, which ones?
No.

What I did:

- Downloaded the dmg from the website.

- Clicked the zip to unzip it to my downloads.

- Clicked the app to start it.

**Comment by bengotow** [comment]
Hey! Thanks again for reporting this. The fix for this shipped in v1.2.3 earlier today. Enjoy!
