### ISSUE TITLE
{Contact} just clicked undefined notification

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#827]
##### Are there any related issues?

No.
...

##### What operating system are you using?
Windows 10 EDU
...

##### What version of Mailspring are you using?
Latest (1.2.1.7e7 ... )
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not as far as I can tell.
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Any message without a subject line.

--

When a message is clicked upon by a message receiver, it returns an undefined message. This is a weird response.
![image](https://user-images.githubusercontent.com/25718989/38661822-7c460b3a-3e75-11e8-9c3e-36f76f902170.png)

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this has been fixed in c7868676f8bb066982e27ec48db00f133dd60ba0 (the `link.title || link.url`) bit. Will ship in the next day or so—stay tuned!

**Comment by bengotow** [comment]
Hey folks—this shipped in version 1.3.0. The app should have auto-updated by now, but if not you can download the latest release from https://www.getmailspring.com/download. Enjoy!
