### ISSUE TITLE
Systray icon is very hard to notice

### ISSUE THREAD

**Issue by kbumsik** [Foundry376/Mailspring#835]
##### What version of Mailspring are you using? - 1.2.1

It is very hard to notice if a new message arrives with the systray icon.

A few pictures are worth a thousand words:

![mailspring](https://user-images.githubusercontent.com/7823583/39010817-b604a760-43dd-11e8-924a-1c79ff67b675.png)

The small green circle indicates there is a new message.

![with_slack](https://user-images.githubusercontent.com/7823583/39010854-d03273ce-43dd-11e8-825c-4b7e4f8302e7.png)

Comparison with Slack icon.

![whole_screen_2](https://user-images.githubusercontent.com/7823583/39010883-e95e42ce-43dd-11e8-863c-2e056546ece2.png)
![whole_screen_1](https://user-images.githubusercontent.com/7823583/39010887-ec6bc496-43dd-11e8-88b7-69b6fe90df4f.png)

When you look at it in the whole screen it is even worse.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
