### ISSUE TITLE
Feature request : mailspring spanish translated

### ISSUE THREAD

**Issue by Lvaskz** [Foundry376/Mailspring#838]
Hi, I recently using mailspring and I consider usefull, but It comes in english.I can not set in the Spanish language, in other Words, mailspring has not support for languages.By that reason I request this feature.For me, you have mailspring in spanish is more comfortable, and many other languages ​​of course.
I am using linuxmint 18.3 64 bits , cinnamon desktop

**Comment by Aldo-f** [comment]
https://github.com/Foundry376/Mailspring/issues/226

**Comment by artus-lla** [comment]
I request this feature too.

**Comment by Lvaskz** [comment]
There is another tool free https://weblate.org/en-gb/. The community can help translate it into different languages

**Comment by bengotow** [comment]
Hey folks! This is coming very soon—check #226 for an update there. Stay tuned!
