### ISSUE TITLE
add ``` support

### ISSUE THREAD

**Issue by farfromrefug** [Foundry376/Mailspring#843]
could you add support for ``` while composing a mail?
I use all the time to mark commands to be run or code reference.

Right now we can add code but not in the middle of a sentence like ```that```

Thanks

**Comment by bengotow** [comment]
Hey! It looks like this is working now - I can't remember exactly when it was added, but I may have just forgotten to close this. Can you let me know if you're still not seeing what you're looking for? Thanks!
