### ISSUE TITLE
mailsmtp Last Error Code: 17 (OS: Ubuntu 18)

### ISSUE THREAD

**Issue by hamadazahera** [Foundry376/Mailspring#850]
----------SMTP----------
220 mail.uni-paderborn.de ESMTP Exim 4.89 (nylar) Mon, 07 May 2018 12:02:43 +0200
EHLO hzahera-Latitude-5580
250-mail.uni-paderborn.de Hello nb-zahera1.cs.uni-paderborn.de [131.234.250.67]
250-SIZE 78643200
250-8BITMIME
250-PIPELINING
250-STARTTLS
250 HELP
STARTTLS
220 TLS go ahead
EHLO hzahera-Latitude-5580
250-mail.uni-paderborn.de Hello nb-zahera1.cs.uni-paderborn.de [131.234.250.67]
250-SIZE 78643200
250-8BITMIME
250-PIPELINING
250-AUTH PLAIN LOGIN GSSAPI
250 HELP

SMTP Last Response Code: 250

SMTP Last Response: mail.uni-paderborn.de Hello nb-zahera1.cs.uni-paderborn.de [131.234.250.67]
SIZE 78643200
8BITMIME
PIPELINING
AUTH PLAIN LOGIN GSSAPI
HELP

mailsmtp Last Error Code: 17

mailsmtp Last Error Location: 10

**Comment by strepkov** [comment]
+1

**Comment by westr029** [comment]
This looks like the same problem in #341. However, this is still not solved.

**Comment by bengotow** [comment]
Merging this in to #620
