### ISSUE TITLE
Rich Contact Profile keeps filling with Tennis Round

### ISSUE THREAD

**Issue by heliostatic** [Foundry376/Mailspring#855]
I don't know anyone at Tennis Round, but about half my contacts now seem to work there (they don't)

##### What operating system are you using?
Mac OS 10.13

##### What version of Mailspring are you using?
Version 1.2.1 (1.2.1)
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
##### Is the issue reproducible with a particular attachment, message, signature, etc?
![image](https://user-images.githubusercontent.com/70898/39772966-9ead1444-52c4-11e8-8690-e7787d7f7577.png)

**Comment by bengotow** [comment]
Hey thanks for reporting this—it looks like a new feature we implemented last month to provide company info when we couldn't retrieve any info about the specific user is backfiring. Will get this fixed ASAP.

**Comment by bengotow** [comment]
Hey! Thanks again for reporting this. The fix for this was applied on the back-end last week and you shouldn't see this behavior anymore.
