### ISSUE TITLE
Tiny UI on HIDPI displays

### ISSUE THREAD

**Issue by freddiehaddad** [Foundry376/Mailspring#856]
##### Issue
On my 4k UHD monitor, the UI is very tiny.  Even the menu bar (File, Edit, View, Thread, ...) is very tiny and unaffected by the Scaling option.  I tried going into Edit > Preferences > Appearance and moving the Scaling bar all the way to the right.  It improved the UI slightly, but it's still very tiny and disproportionate to the Gnome UI with the scaling factor set to two.  It seems like the application doesn't honor the desktop scaling factor.

##### Are there any related issues?
Only found #176 and #563 -- not really related, but comes up when searching HIDPI issues.

##### What operating system are you using?
Ubuntu 18.04

##### What version of Mailspring are you using?
1.2.1-7e7447b6

##### Do you have any third-party plugins installed? If so, which ones?
Default install from .deb file -- no additional plugins.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

**Comment by ArchangeGabriel** [comment]
Can you try launching from the CLI with `--force-device-scale-factor=2` as arg?

**Comment by freddiehaddad** [comment]
That worked!

**Comment by sebastient** [comment]
This would be nice to have as a proper UI option since otherwise we need to launch Mailspring from the command line to get the proper scaling.

**Comment by alexsasharegan** [comment]
![screenshot from 2018-06-20 21-32-37](https://user-images.githubusercontent.com/16269252/41698229-096412fe-74d2-11e8-9429-dbf9c12e5287.png)
![screenshot from 2018-06-20 21-35-10](https://user-images.githubusercontent.com/16269252/41698230-0978cf64-74d2-11e8-9924-fce7b5f45f05.png)

**Comment by alexsasharegan** [comment]
This seems to be a non-issue using the `.deb` package. Bye bye snap :wave:

**Comment by ArchangeGabriel** [comment]
Assuming there is a desktop menu entry provided by a .desktop file, you could just edit this one and add the scale switch to the default command, thus avoiding the need to launch from CLI.
