### ISSUE TITLE
Restricting search inside subject. (search query like - subject:meeting)

### ISSUE THREAD

**Issue by patelom** [Foundry376/Mailspring#860]
Mailspring supports Gmail-style search queries, "from: ben@foundry376.com" and "to: ben@foundry376.com" but it does not support subject specific search query - "subject:meeting". 

It would be very helpful to have subject specific search. When you have tons of emails, its practially difficult to find to the desired email with the search that exists right now.

What operating system are you using?
macOS High Sierra v10.13.4

What version of Mailspring are you using?
Version 1.2.1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

<img width="1440" alt="screen shot 2018-05-10 at 1 13 06 pm" src="https://user-images.githubusercontent.com/5392699/39858342-e7d82c72-5453-11e8-9f62-f1897be2a505.png">

--

**Feature Request?**
Does this feature exist in another mail client or tool you use?
Yes, in Gmail.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - I'm hoping to overhaul the search UI next month and I'll see if I can fix this in the process. It looks like search-by-subject /should/ be working, but there might be a bug in the sync engine preventing the search index from being populated correctly. Stay tuned!

**Comment by bengotow** [comment]
Looks like this may be a quick fix to the sync indexer—after the next update, you'll need to visit Preferences > Accounts and click "Rebuild cache..." to re-index existing mail, but new mail will have subjects indexed properly, and we'll do a re-indexing for everyone when the new search UI lands.

**Comment by patelom** [comment]
Thanks @bengotow Much appreciated. Also, in general, finding an email is little difficult. I recommended Mailspring to a friend who receives around 100-200 emails a day. For him, the biggest challenge was to find the email he was looking for. Since ages, he is using Outlook, and Outlook provides great functionalities for searching emails.

**Comment by bengotow** [comment]
Hey @patelom thanks for the feedback—I'm gonna spend some time in June improving Mailspring's search UI, so I'll make sure I try out Outlook's search and see what can be pulled in from there. In the meantime, this fix shipped in 1.2.2. Enjoy!
