### ISSUE TITLE
Love Mailspring but need clarity on development roadmap

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#861]
Hi all - I *really, really like Mailspring* so far, despite some obvious bugs that need working out.

But the pace of development has been really variable lately, and for the past month or so at least for me, Mailspring has been unusable due to #829 

Especially for those paying for Mailspring, I think we deserve some clarity on whether this has a future as a constantly maintained product, and what would be a reasonable expectation for pace of development, etc.

**Comment by bengotow** [comment]
Hey! Thanks for posting this - I think that f65a27d77af19649443ed8abdd3c661e94078dce will fix #829 but I'll do some more testing and be sure. Sorry it's been blocking you from using Mailspring!

I'll put together an updated roadmap document today. The plan is to do one feature release a month and incorporate as many bug fixes as possible. April/May have definitely been a bit slow. Mailspring Pro subscriptions are on the up-and-up (thank you!) but I took on a bit of contract work to help balance the budget and spent some time implementing a new "delete all your data" feature for GDPR. There will be a new release this week, and the plan is to overhaul the search UI in June.

Hope that helps! Will link to the new roadmap doc when I get it added.

**Comment by palefire19** [comment]
Thanks @bengotow , appreciate it! Happy to hear paid subs are going up.

**Comment by bengotow** [comment]
Hey! Just a heads up, I've added a bit more detail to https://github.com/Foundry376/Mailspring/blob/master/ROADMAP.md - based on the feedback I've been getting, I think the most important project for June is better search UI and saved searches. I'm doing some design now and I think that can be shipped by July 1. From there, the plan is tentatively to bring back Mail Merge, but there are still a few open questions around the design there.

Stay tuned!

**Comment by DarkSpyro003** [comment]
Almost all dates on the roadmap are currently in the past. May I suggest a revision of the roadmap to make it more current?

**Comment by CodeMouse92** [comment]
@DarkSpyro003 We are on it! That's a goal for right now. Please join our awesome new Discourse community to get the latest about releases, roadmaps, and development discussions: https://community.getmailspring.com/
