### ISSUE TITLE
Editing in RTL but send the message in LTR direction

### ISSUE THREAD

**Issue by jimmyheller** [Foundry376/Mailspring#869]
##### Are there any related issues?

Yes there were and issue has been closed but the problem is still.
https://github.com/Foundry376/Mailspring/issues/399

##### What operating system are you using?
Mac OS X

##### What version of Mailspring are you using?
Version 1.2.1 (1.2.1)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes , The sample images are showing that if you write an email in right to left format, it will be sent in left to right mode no matter what. even in my inbox is in left to right mode. 
<img src="https://user-images.githubusercontent.com/14005313/35259083-df501022-0018-11e8-9aed-ce2e4bb2e585.png">

and the result is : 
<img src="https://user-images.githubusercontent.com/14005313/35259091-f64cb9e2-0018-11e8-9429-3fbcecf15922.png">

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
all the email clients has this feature!

**Comment by jimmyheller** [comment]
Thanks for your response , to be honest (if it helps) we tried to work on the composer component but it seems that the composer is making it rtl correctly but the problem is something after sending the mail and in the cloud. we could not find it by reading the source of composer.

**Comment by bengotow** [comment]
Thanks again for reporting this—it looks like a change in Slate required us to manually add the `dir=rtl` tag when translating the body of the message to HTML. I've fixed it and this will ship in the next release.

**Comment by jimmyheller** [comment]
Thanks, I'm waiting for it. after testing I will update the issue and close it.

**Comment by bengotow** [comment]
Hey! This has shipped in 1.2.2 - the app should auto-update in the next few hours, or you can download the new version directly from getmailspring.com. Thanks again for reporting this—I'm not sure how I missed this in the first round of testing.

**Comment by jimmyheller** [comment]
I'm thankful for your dedication and believe me I tested so many applications for mac but mailspring is by far the best! keep up the good work! I will continue to test and if I can I would contribute to the source.
