### ISSUE TITLE
Countdown in message "Sending in 5 seconds"

### ISSUE THREAD

**Issue by imbrn** [Foundry376/Mailspring#872]
##### What operating system are you using?
Ubuntu 16.04 (xenial) [KDE Neon 5.12]

##### What version of Mailspring are you using?
1.2.1

### Actual behavior:

When the user click to send an email, an **Undo option** is shown for 5 seconds, before the message is really sent, so the user can undo the sending within 5 seconds. Along with this option, a static message is displayed with the following content: _"Sending in 5 seconds"_:

![screenshot_20180515_214651](https://user-images.githubusercontent.com/1906977/40090705-e68b59a4-5889-11e8-9d8a-458c603a9ff7.png)

### Feature request:

I think that it would be great if this message was a kind of countdown, decreasing from 5 seconds to 0, and then the message was sent.

**Comment by bengotow** [comment]
I think this would be great - right now, this toast also disappears a little bit too soon because it's just the standard undo toast. Will see if I can fix this for the next release!

**Comment by bengotow** [comment]
![aug-05-2018 23-59-46](https://user-images.githubusercontent.com/1037212/43701608-a90e808e-990b-11e8-8b39-83757be89dce.gif)

Hey! In the next release I'm changing this to have a coutdown timer in it, and also make the undo button more apparent (it's a little unclear that just that region is clickable.) Stay tuned!

**Comment by bengotow** [comment]
Hey folks! This has shipped in 1.4.1. You can get the update automatically if you're using the Mac and Windows versions, or the Linux snapcraft release, and you can also download it from https://getmailspring.com/download.  I'm going to go ahead and close this and we'll re-open it if necessary. Thanks—enjoy the app!
