### ISSUE TITLE
Remove additional space after/before server setting

### ISSUE THREAD

**Issue by Aldo-f** [Foundry376/Mailspring#876]
##### What operating system are you using?
OS: Windows 10 Pro
version: 1709
build: 16299.431 

##### What version of Mailspring are you using?
1.2.1-7e7447b6

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![server settings](https://i.imgur.com/ug6HbxW.png)
When adding a space before or after the server settings there is not any kind of error, nor does it removes the additional space automatically

Log message:

     ----------IMAP----------

**Comment by bengotow** [comment]
Hey! This has shipped in 1.2.2 - the app should auto-update in the next few hours, or you can download the new version directly from getmailspring.com. Enjoy!
