### ISSUE TITLE
Link-tracking does not properly redirect to mailto: protocol handler

### ISSUE THREAD

**Issue by allanbreyes** [Foundry376/Mailspring#877]
##### Are there any related issues?

I searched on `mailto`, and there were no related issues.

##### What operating system are you using?
Ubuntu 18.04 LTS Desktop

##### What version of Mailspring are you using?
`1.2.1`

---

**Bug**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail, but I don't think it's relevant.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes:

```
curl -I https://link.getmailspring.com/link/redacted-email-id@getmailspring.com/0?redirect=mailto%3Auser%40example.com&recipient=redacted

HTTP/1.1 302 Found
cache-control: no-cache
Content-Length: 0
Date: [redacted]
location: https://mailto:user@example.com
Server: nginx/1.12.1
Connection: keep-alive
```

The `link.getmailspring.com` server is incorrectly redirecting `mailto:` links on HTTPS. This results in a URI that tries to auth with user `mailto` and password `user`.

When using Firefox, clicking on the email link results in a very jarring experience, raising the warning message:

![image](https://user-images.githubusercontent.com/7947900/40202105-dcd994d2-59d5-11e8-93ef-1e8ddc46cb37.png)

Tested in Chrome + Chromium, and it redirects the user to the email domain on HTTP. (But again, not the `mailto:` protocol handler.)

**Comment by bengotow** [comment]
Oh man I'm glad you caught this - it looks like this is definitely a backend bug with the open / link tracking service. I'll see if I can fix this (for links already sent this way) and we can disable tracking of mailtos via your PR.

**Comment by bengotow** [comment]
Ok - I've deployed a server fix to remove the https:// redirect. We may still want to merge your PR to stop the bounce out to the browser entirely.

**Comment by allanbreyes** [comment]
Thanks for the quick fix, @bengotow!

**Comment by allanbreyes** [comment]
Woops, accidentally closed. Didn't mean to mess with your workflow :scream_cat:
