### ISSUE TITLE
Mail not fully visible 

### ISSUE THREAD

**Issue by Aldo-f** [Foundry376/Mailspring#879]
##### What operating system are you using?
OS: Windows 10 Pro
version: 1709
build: 16299.431 

##### What version of Mailspring are you using?
1.2.1-7e7447b6

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

The only way to view the mail is by clicking on "print"... 
![not fully visible email](https://i.imgur.com/Q0N3TL8.png)

On this example, it's even not possible to view the text when clicking print.
![afbeelding](https://user-images.githubusercontent.com/5683799/40233554-c920cad6-5aa3-11e8-95b0-09a61be81164.png)

**Comment by brycefranzen** [comment]
I'm having the same issue on emails from "carfax" all other emails work correctly.

**Comment by bengotow** [comment]
Hey folks! Thanks for reporting this—this was fixed in 1.3.0 a week or two ago and your version of the app should have auto-updated. If not, you can get the new version at https://getmailspring.com/download. Enjoy!

**Comment by Aldo-f** [comment]
Tested

But not completely okay.

---------- Forwarded message ---------
From: Hackster.io <help@hackster.io>
Subject: 100 Free Kits from TI, Adafruit, Digilent + More! 🏆
Date: apr. 13 2018, at 7:08 am
To: aldo.fieuw@gmail.com

Unleash Invisible Intelligence with Maxim!

Maxim Integrated is challenging the Hackster community to come up with creative ways to infuse intelligence into a new application using the MAX32620FTHR rapid development platform. Enter the contest today for a chance to win one of these boards! Prizes include a HoloLens, an iPhone X, and a Nintendo Switch, among several other gadgets.

And more good news, we are giving away 100 FREE boards from TI, Adafruit, Arduino, Digilent, Seeed and others to anyone that signs up for our Google China-US Young Maker Contest (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=d7b680a5ea&e=7a4abac4eb). All you need to do is register, and we'll pick and mail your board in the coming days!

Get Your Free Board! (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=709a578766&e=7a4abac4eb)

Projects of the Week

See what's trending in the Hackster community.

DIY HomeKit-Enabled Devices by IoT_lover (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=8e53109648&e=7a4abac4eb)

This shows how to make smart home devices, which can be controlled/monitored via Siri or Home app.

Published in Apple (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=83d2d6deb6&e=7a4abac4eb), PHPoC (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=5a92b9c5eb&e=7a4abac4eb), Raspberry Pi (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=c2b5efdf04&e=7a4abac4eb)

Door Closer! by Arthur Guy (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=784b46e10a&e=7a4abac4eb)

Fed up of getting up to close the door? Want to be able to close the door by talking to the room? If you answered yes then read on!

Published in Amazon Alexa (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=ee09596e69&e=7a4abac4eb), Particle (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=4218edebea&e=7a4abac4eb)

Motion Activated Stairs by Dante Roumega (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=375214de69&e=7a4abac4eb)

Yes, it's overkill, but if walking up motion-activated light-up stairs is wrong, well then I don't want to be right.

Published in Arduino (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=1f1cbd365f&e=7a4abac4eb)

Make an RGB WiFi Torch by TechGuru (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=a19428e943&e=7a4abac4eb)

Ever get bored with static colors of traditional torches? There are RGB lamps but not seen much controlled by WiFi. So let's do it!

Published in Android (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=22954667b8&e=7a4abac4eb), Everything ESP (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=12f7628159&e=7a4abac4eb), Google (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=f5d045d3e1&e=7a4abac4eb)

Control Your Car with Alexa by Ihor Bodnarchuk (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=4c505be788&e=7a4abac4eb)

Add voice control to your car using Raspberry Pi and Amazon Alexa.

Published in Amazon Alexa (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=71a676040e&e=7a4abac4eb), Amazon Web Services (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=6abf962a52&e=7a4abac4eb), Raspberry Pi (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=c218846da4&e=7a4abac4eb), Sony (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=5a49f91df1&e=7a4abac4eb)

Water Level (Ultrasonic) Sensor with LoRaWAN by Nicole Jesse (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=97ca40a8b4&e=7a4abac4eb)

I live quite close to a local river and want to monitor its water level.

Published in Adafruit (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=59ff1f8730&e=7a4abac4eb), Arduino (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=7426a3c660&e=7a4abac4eb)

Localization Based on RF Modules Using FPGA by Szekely Istvan (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=3c836a0f7c&e=7a4abac4eb)

Find the location of a device, using multiple DWM1000-ESP8266 pairs, and an FPGA.

Published in Digilent (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=8cf76ee93b&e=7a4abac4eb), MATLAB (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=37b170c2ae&e=7a4abac4eb), Xilinx (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=233caa8a30&e=7a4abac4eb)

Windows 10 UWP Color Picker by Daniel Porrey (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=f35fdaab34&e=7a4abac4eb)

A hue based, touch enabled color picker control for your Windows 10 UWP applications. This projects has a full LIFX demonstration app.

Published in Microsoft (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=a425ec79c8&e=7a4abac4eb), Raspberry Pi (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=6bfcf739bd&e=7a4abac4eb)

UPDATED: Solar Power Station for Arduino by Patel Darshil (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=103f6435d0&e=7a4abac4eb)

This solar powering unit is a time-switching, battery-powered, solar-charged circuit for Arduino.

Published in Arduino (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=402fefc388&e=7a4abac4eb), Microchip (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=3aad5733d8&e=7a4abac4eb), SparkFun (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=335968151e&e=7a4abac4eb)

Use Python, Zynq and OpenCV to Implement Computer Vision by Alex and Adam (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=a345c4f5c2&e=7a4abac4eb)

Use Python, OpenCV libraries and the PYNQ frame to implement the computer vision on Arty Z7-20 Xilinx Zynq SoC platform.

Wireless SNES with nRF24 by James Lewis (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=220cec2033&e=7a4abac4eb)

Cut the cord and play retro games on your couch with an Arduino and nRF24 radios.

Published in Arduino (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=bd1949f5bb&e=7a4abac4eb), SparkFun (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=56f21b8e00&e=7a4abac4eb)

RetroPie in a Super Famicom by James Lewis (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=ffcf7ce522&e=7a4abac4eb)

Why 3D print a classic case when the classic SFC case is perfect for a RetroPie?.

Published in Adafruit (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=5836a0111e&e=7a4abac4eb), Raspberry Pi (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=59002e28d7&e=7a4abac4eb)

What's Happening?

New videos, interviews, contests + more.

W (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=7c981fe572&e=7a4abac4eb)in a Trip to Beijing, $15,000 + Global Bragging Rights! (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=f8d1eaf9b4&e=7a4abac4eb)

Google is calling upon makers in the U.S. to submit ANY project using ANY platform. 10 semi-finalists will fly to China to compete against other innovators from China for a chance at $15,000.

Solve an Everyday Problem with Particle (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=f2d8ad7056&e=7a4abac4eb)

Choose something in your daily life (or bigger!) that could benefit from the power of IoT. Then build a solution to make it a reality. Grand prize is a trip to San Francisco to meet the Particle team!

Arm Innovator Interview: Chelsea Klukas (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=f0478d940c&e=7a4abac4eb)

Next Wednesday, we'll be talking with Chelsea Klukas about technology’s role in high fashion, her experience in the industry with her company MakeFashion, and much more. Register now!

eTextile Spring Break: Sound Synthesis with Arduino (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=b7a277a884&e=7a4abac4eb)

Want to make music on Arduino? Here are a few tools Alex just picked up at a workshop in New York! Read all about her week on our blog and watch her video recap!

More News (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=5d607ecb28&e=7a4abac4eb)

ICYMI

Everything you may have missed from our blog.

Pi Console Pops into Place at the Push of a Button (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=231c1b0884&e=7a4abac4eb)

Hacker Michael Horne decided to build a portable Raspberry Pi workstation from a foldable 4.3" screen.

Convert a Vintage Tube Radio into a Music Streamer (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=699f3c51b7&e=7a4abac4eb)

YouTuber PC DOODLE upgraded an old Claratone tube radio into an Internet radio and podcast player with a LattePanda.

LED Matrix Top Hat Displays Your Favorite Characters (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=216840ed9d&e=7a4abac4eb)

Matthew Varas fused together four LED matrix displays to wrap around a hat, showing off images of famous 8-bit characters.

Turn a 3D Printer into a Manufacturing WorkHorse (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=add7640826&e=7a4abac4eb)

Swaleh Owais’ delta FFF 3D printer, the WorkHorse, replaces a traditional print bed with an automated conveyor belt.

See All Blog Posts (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=90d0409fdf&e=7a4abac4eb)

Startup Spotlight

Show your support for these hot hardware campaigns.

Goon Box: A Doctor Who DEF CON Badge Set (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=574b3928a9&e=7a4abac4eb)

Does it have Wi-Fi/Bluetooth? No, but it does have LEDs, sound, touch sensors, infrared, and it's a two-part badge!

Magus: A Modular Synthesizer Toolkit (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=bfa548c91f&e=7a4abac4eb)

The Magus is like having a compact modular synthesizer without being limited by the modules you've got in it.

Cubetto: Coding Adventures in the Savannah (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=844861843a&e=7a4abac4eb)

Exclusive to Kickstarter, Primo Toys is launching new adventures for Cubetto — a hands-on coding toy for kids 3+.

Across the Board

OSHW for your next design.

EDMINI: An Arduino Pro Mini Clone for $1.40 (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=367215d94e&e=7a4abac4eb)

The Revolve combines what would typically be a Raspberry Pi and an Arduino-based RepRap mainboard into a single unit.

Universal Chip Analyzer: FPGA-Based IC Tester (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=ec7ee45cd1&e=7a4abac4eb)

The UCA is built on an FPGA that actually emulates a motherboard that’s compatible with that CPU you’re testing.

Naked Mega 3: A Bare-Naked Arduino Mega (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=7875d30e14&e=7a4abac4eb)

An Arduino Mega 2560-compatible board based on the ATmega2560-16AU, with minimalist design and form factor.

Kite's Circuit Sword: Perfect for Retro Gaming (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=4ca649aa13&e=7a4abac4eb)

Kite’s new Circuit Sword board is ideal for fitting a Raspberry Pi Compute Module into an original Game Boy.

OSD3358-SM-RED: A BeagleBone-Like SBC (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=201f5b4a1d&e=7a4abac4eb)

The OSD3358-SM-RED is the reference, evaluation, and development board for the OSD335x-SM family of SiP devices.

There's a new channel on Hackster for FPGAs. Check out some of our latest projects and learn how to make that board do everything YOU want it to do!
Visit the New FPGAs Channel (https://hackster.us7.list-manage.com/track/click?u=3fd72855783c7f1a97812d84e&id=51ae8ac109&e=7a4abac4eb)

Hackster.io

531 Howard St, Fl 2

San Francisco, CA 94105

USA

Unsubscribe (https://hackster.us7.list-manage.com/unsubscribe?u=3fd72855783c7f1a97812d84e&id=6ff81e3e5b&e=7a4abac4eb&c=e8e44c3bac)

**Comment by Aldo-f** [comment]
Tested.
Not completely okay.
![afbeelding](https://user-images.githubusercontent.com/5683799/43731994-9802e6b8-99b0-11e8-96b3-cc3594fb4125.png)
