### ISSUE TITLE
Mail order

### ISSUE THREAD

**Issue by ASAPHAANING** [Foundry376/Mailspring#882]
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
I don't know if it exists, but I can't find it. Is it possible for the reading pane to support a reverse order of emails such that the newest email in a series of replies/forwards is the first one instead of the default last?

![selection_004](https://user-images.githubusercontent.com/6765179/40277956-6e92dc72-5c28-11e8-95eb-fcc0f8ad4ac1.png)

**Comment by emadow** [comment]
<img width="519" alt="screen_shot_2018-05-20_at_10_46_23_pm" src="https://user-images.githubusercontent.com/490190/40292351-ae93ee68-5c7f-11e8-91b7-505cb3f77961.png">

😄
