### ISSUE TITLE
Authentication Error - Check your username and password. (IMAP)View Log

### ISSUE THREAD

**Issue by Alculete** [Foundry376/Mailspring#885]
When trying to connect to my O365 I receive the error bellow

![image](https://user-images.githubusercontent.com/2129497/40357438-775cd930-5dbc-11e8-8249-df294d510a52.png)

---------IMAP----------
* OK The Microsoft Exchange IMAP4 service is ready. [TAPADIAUAAyAYANQBDAEEAMAAwADgANwAuAEcAQgSAFAAMgA2ADUALgBQAFIATBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
2 LOGIN "<my email>" "*********"
2 NO LOGIN failed.

**Comment by bengotow** [comment]
Hey! Thanks for reporting this - this looks like a standard incorrect password response though. Is there any chance you have your O365 settings configured to require an "Application Password" for IMAP clients? You might need to create one using these instructions: https://support.office.com/en-us/article/create-an-app-password-for-office-365-3e7c860f-bda4-4441-a618-b53953ee1183

**Comment by cihyboj** [comment]
@bengotow I've created Application Password but it doesn't work either... :/

**Comment by klainn** [comment]
I, too, am getting this on 2 of my office 365 accounts. Even if I copy and paste the password into outlook web and login with no issue, I can't then paste the same password in mailspring and get it to authenticate. My CAPABILITY string is a little different than the one previously posted.

----------IMAP----------
* OK The Microsoft Exchange IMAP4 service is ready. [UwBOADQAUABSADAAMgAwADEAQwBBADAAMAAyADcALgBuAGEAbQBwAHIAZAAwADIALgBwAHIAbwBkAC4AbwB1AHQAbABvAG8AawAuAGMAbwBtAA==]
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
2 LOGIN "first.last@company-name.com" "*********"
2 NO LOGIN failed.

**Comment by b00f** [comment]
change your password.

**Comment by alculete** [comment]
It is not related to password. The application needs to be allowed to run on your company. In my case this app is not listed. Go to [Office Page](https://www.office.com/?from=PortalHome) and see if Mailspring is listed in the apps that your have permission to use

**Comment by im007** [comment]
> It is not related to password. The application needs to be allowed to run on your company. In my case this app is not listed. Go to [Office Page](https://www.office.com/?from=PortalHome) and see if Mailspring is listed in the apps that your have permission to use

Where exactly are you looking? Mailspring is not a Microsoft app, so I don't think it would show up in the O365 Portal. Furthermore, doing a search for Mailspring [here](https://appsource.microsoft.com/en-us/marketplace/apps?src=Office&search=mailspring&page=1) returns nothing.

**Comment by alculete** [comment]
on the link I gave click sell all apps you will  see the list of all application you have permission to use for example for me hiri is listed 
![image](https://user-images.githubusercontent.com/2129497/83936912-82530c80-a7c8-11ea-882e-2181ac801443.png)

**Comment by meanmechanics** [comment]
I have the same issue here. maybe I should add that I am registered with my domain in outlook.

**Comment by co1ncidence** [comment]
This issue is still prevalent, same issue and logs as everyone else here, though, I would like to mention that I was logged in for quite a while before one day I got a "failed to authenticate to email@domain.com" which was my schools office365 domain, since then I have not been able to log into that specific email.

**Comment by Rahbaran** [comment]
Having out of the blue the same issue since today, it might be because our company now wants two-factor-authentication. yesterday evening, everything was working. macOS Cataline +++ Mailspring 1.7.8

**Comment by EzioRaison** [comment]
> Having out of the blue the same issue since today, it might be because our company now wants two-factor-authentication. yesterday evening, everything was working. macOS Cataline +++ Mailspring 1.7.8

Following this might work for you.
https://support.microsoft.com/en-us/account-billing/using-app-passwords-with-apps-that-don-t-support-two-step-verification-5896ed9b-4263-e681-128a-a6f2979a7944

**Comment by Melissa-Kay** [comment]
I haven't tried prior to our company enabling 2-factor but we do have 2-factor enabled and I am getting this same error message. I can't seem to find a way to add an app password but Mailspring is listed under my app permissions. On Ubuntu 20.04

**Comment by CodeMouse92** [comment]
We have migrated issue tracking to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

Please search for a related issue there, or else start a new thread in the appropriate category. https://community.getmailspring.com/

We hope to see you on Discourse soon!

-The Mailspring Team
