### ISSUE TITLE
Microsoft Exchange IMAP/SMTP Error

### ISSUE THREAD

**Issue by Vi1i** [Foundry376/Mailspring#890]
##### Are there any related issues?

#130 might be?

##### What operating system are you using?
Arch Linux

##### What version of Mailspring are you using?
1.2.1-7e7447b6

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Exchange

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Whenever I attempt to add our organizations Exchange server with smtp, I get a certificate error.
[Log](https://pastebin.com/8C6AahBu)
![mailspring_cert_error_redacted](https://user-images.githubusercontent.com/6485370/40452590-5ca35296-5eb0-11e8-8e76-3f3b9f24060c.png)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by Vi1i** [comment]
So I am now pretty sure it has to do with the #130 as when I check "Allow Insecure Connections" I get the same errors as reported in #130 .

**Comment by tanmayrajani** [comment]
Any updates on this?

**Comment by navennn** [comment]
I moved to TBSync, it works;
Thunderbird 60.2.1 (64-bit)
Lightning 6.2b6
TBsync 0.7.16
https://github.com/jobisoft/TbSync/wiki/How-to-get-started

My advice is to do the same.

**Comment by Vi1i** [comment]
At this point, I am willing to assume this isn't even going to be looked at.
What @navennn posted works well. I also moved off to Thunderbird that works well for the most part.

**Comment by maetthew** [comment]
For reference I had the same problem. Got it to work by checking "Allow insecure certificates". Not sure exactly what the difference is though. Might be something with self-signed certificates?

**Comment by maetthew** [comment]
I'm having the same problem here using ProtonMail Bridge Beta for Linux 1.1.0 and Mailspring 1.5.3-420ce003. For reference, when I check "allow insecure certificates" it takes me through the setup wizard and into the mailbox. It seems to find my folders and such but no e-mails are being downloaded. If I click "Show progress" in Mailbox all mailboxes sit at "Scanning (0%)" with no progress what so ever.

I'm thinking it has something to do with self-signed certificates?

This is the error log without "allow insecure certificates". I've redacted some personal information

----------IMAP----------
* OK [CAPABILITY IMAP4rev1 STARTTLS AUTH=PLAIN AUTH=LOGIN ID APPENDLIMIT] IMAP4rev1 Service Ready
1 STARTTLS
1 OK Begin TLS negotiation now
2 LOGIN "<REDACTED(e-mail address)>" *********
* CAPABILITY IMAP4rev1 AUTH=PLAIN AUTH=LOGIN ID XSTOP APPENDLIMIT
2 OK [CAPABILITY IMAP4rev1 IDLE MOVE SPECIAL-USE ID XSTOP QUOTA APPENDLIMIT=26214400 XFOCUS] LOGIN completed
3 LIST "" ""
* LIST (\Noselect) "/" "/"
3 OK LIST completed
4 LIST "" "*"
* LIST (\Noinferiors) "/" "INBOX"
* LIST (\Sent \Noinferiors) "/" "Sent"
* LIST (\Trash \Noinferiors) "/" "Trash"
* LIST (\Junk \Noinferiors) "/" "Spam"
* LIST (\Archive \Noinferiors) "/" "Archive"
* LIST (\All \Noinferiors) "/" "All Mail"
* LIST (\Noinferiors) "/" "Folders/<REDACTED>"
* LIST (\Noinferiors) "/" "Folders/<REDACTED>"
* LIST (\Noinferiors) "/" "Folders/<REDACTED>"
* LIST (\Noselect) "/" "Labels"
* LIST (\Noselect) "/" "Folders"
4 OK LIST completed


----------SMTP----------
220 127.0.0.1 ESMTP Service Ready
EHLO <REDACTED>
250-Hello <REDACTED>
250-PIPELINING
250-8BITMIME
250-STARTTLS
250 AUTH PLAIN LOGIN
STARTTLS
220 Ready to start TLS
QUIT

SMTP Last Response Code: 220

SMTP Last Response: Ready to start TLS

**Comment by maetthew** [comment]
This is my mailsync.log upon start of Mailspring with account setup with "allow insecure connections". Seems that Mailspring is trying to create folders but are not allowed to.

1443 [2018-12-18 14:02:28.273] [main] [info] ------------- Starting Sync (redacted@email.com) ---------------
1443 [2018-12-18 14:02:28.275] [background] [info] Marking all folders as `busy`
1443 [2018-12-18 14:02:28.275] [metadata] [info] Metadata delta stream starting...
1443 [2018-12-18 14:02:28.276] [background] [info] Syncing folder list...
1443 [2018-12-18 14:02:28.329] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorSubscribe
1443 [2018-12-18 14:02:28.330] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorSubscribe
1443 [2018-12-18 14:02:28.331] [background] [info] Syncing folder list...
1443 [2018-12-18 14:02:28.331] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorSubscribe
1443 [2018-12-18 14:02:28.331] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorSubscribe
1443 [2018-12-18 14:02:28.350] [foreground] [info] Idling on folder INBOX
1443 [2018-12-18 14:02:28.375] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1070 - 1820, Heavy: true
1443 [2018-12-18 14:02:28.379] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
1443 [2018-12-18 14:02:43.274] [metadataExpiration] [info] Scanning for expired metadata
1443 [2018-12-18 14:02:43.274] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec

**Comment by bengotow** [comment]
Hey folks! It's been a few years and there haven't been any more reports of this issue so I'm going to close this as probably-fixed. Feel free to bump or create a new issue referencing this one if you encounter this again!

For exchange support discussion: #34 
For protonmail integration: #429
