### ISSUE TITLE
Folder name with accented character render incorrectly

### ISSUE THREAD

**Issue by louim** [Foundry376/Mailspring#9]
Hi @bengotow, congrat on launching! 🎉 , Nylas has been my email client since it has been out, so I must say I was following the development in this repo closely! (I'm not even sure it's officially launched, but I found that the download links were up 😄 ).

The following a minor bug, I found when switching to Mailspring.

##### Are there any related issues?

No!

##### What operating system are you using?
Mac OS X Sierra 10.12.6 (16G29)

##### What version of Mailspring are you using?
Version 1.0.0 (1.0.0)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not really

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Accented characters in folder names are not rendered correctly, see screenshot:

<img width="113" alt="capture d ecran 2017-10-03 a 16 29 46" src="https://user-images.githubusercontent.com/923718/31147529-250922c0-a858-11e7-98ae-9802479795a5.png">

This should say "Message envoyés"

**Comment by bengotow** [comment]
Hey @louim — thanks for filing this! You found the download links quickly! :-) I was planning to let folks download it and try it out, and tell the mailing list if things seemed stable. Getting super close now.

I'll trying to reproduce this now -  could have sworn I checked this but it definitely needs to be fixed.

**Comment by bengotow** [comment]
Oooof - definitely happens for me too. Will fix this!
![image](https://user-images.githubusercontent.com/1037212/31148855-d7b98344-a842-11e7-8efa-af80fe5a7d74.png)

**Comment by bengotow** [comment]
Version 1.0.1 started shipping a few minutes ago, so this should be fixed now. Let me know if you still see this after updating!

**Comment by kometchtech** [comment]
@bengotow 
I checked it in 1.0.2, but it seems that it is not cured if the label of Japanese is not displayed.
Email cache has been deleted before this confirmation.
![label](https://user-images.githubusercontent.com/5137077/31304583-153afe54-ab5f-11e7-927c-dcb25c9565c9.JPG)
