### ISSUE TITLE
Wrote long email - then suddenly half the new text is GONE

### ISSUE THREAD

**Issue by creatrixtiara** [Foundry376/Mailspring#902]
##### Are there any related issues?

Potentially #43 #728 #531 #390 

##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?
v1.2.1
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Affects a Google Apps email address but I don't know if it's exclusive to that account

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Not sure

--

I was writing a pretty long email and as I was looking it over, half the text from the email just STRAIGHT UP DISAPPEARED. It's like Mailspring reverted to a super early draft and now I can't recover all my hard work.

The fact that Mailspring drafts don't sync to Gmail for some reason means that I can't continue that draft on webmail.

**Comment by bengotow** [comment]
Hey! Happy to report that this is fixed in the next release (/finally/) by a new version of the Slate text editor that is much more stable. Stay tuned.

**Comment by bengotow** [comment]
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!

**Comment by jsf15** [comment]
Ubuntu 19.10 here, the same thing just happened to me using an outlook account. I was writing a long email (twice) and as the mailbox updated everything when back to blank.
