### ISSUE TITLE
Can't connect Imap/smtp authentication failure (IMAP and SMTP are enabled and password and username have been entered multiple times)

### ISSUE THREAD

**Issue by Mar-tin-W** [Foundry376/Mailspring#904]
##### Are there any related issues?
currently no.
...

##### What operating system are you using?
Ubuntu 18.04 with Default Gnome desktop
...

##### What version of Mailspring are you using?
1.2.1-7e7447b6 (snap package)
...

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No plugins installed (freshly installed Mailspring)
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Probably not.
I have tried to connect my zoho and yandex account. Both didn't work.
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I don't think this is helpful but here is the log:
___________________________________________________________________________________
----------IMAP----------
* OK Yandex IMAP4rev1 at imap53p.mail.yandex.net:993 ready to talk with ::ffff:83.171.154.81:39078, 2018-May-29 10:37:40, ebI8JB0ug4Y1
1 CAPABILITY
* CAPABILITY IMAP4rev1 CHILDREN UNSELECT LITERAL+ NAMESPACE XLIST BINARY UIDPLUS ENABLE ID AUTH=PLAIN AUTH=XOAUTH2 IDLE MOVE
1 OK CAPABILITY Completed.
2 LOGIN "wi******r@yandex.com" "*********"
2 NO [AUTHENTICATIONFAILED] LOGIN Invalid credentials or IMAP is disabled sc=ebI8JB0ug4Y1_290737_53p
___________________________________________________________________________________

...

--

I can assure that Everything I have entered was correct. I added an account a few days ago and it worked just fine (maybe because of an update?).

**Comment by bengotow** [comment]
Hey! Thanks for reporting this—usually IMAP servers respond with `LOGIN Invalid credentials` and it looks like this one has a slightly different message: `LOGIN Invalid credentials or IMAP is disabled`. It might be that you need to explicitly enable IMAP for your Yandex account. I know for my test Yandex account, I had to link a phone number to the account and create an App Password (https://yandex.com/support/passport/authorization/app-passwords.html) to connect via IMAP. Hope that helps!

**Comment by Mar-tin-W** [comment]
Yandex seems to have worked. Thank you!
I'll report on zoho asap.

**Comment by Mar-tin-W** [comment]
zoho seemed to have also worked just fine.
Strange.
"Thanks for the quick response and tips!"
