### ISSUE TITLE
Can't connect though University Network

### ISSUE THREAD

**Issue by arifzeeshan** [Foundry376/Mailspring#910]
##### What operating system are you using?
Arch Linux

##### What version of Mailspring are you using?
mailspring --version
1.2.2-96fb3a99

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

 Mailspring fails to connect when I am on a University network.

Log -

```
{"debuginfo":"syncFoldersAndLabels - fetchAllFolders","key":"ErrorConnection","retryable":true,"what":"std::exception"}
14985 [2018-06-02 11:27:37.705] [foreground] [info] Encountered exception: {"debuginfo":"connectIfNeeded","key":"ErrorConnection","retryable":true,"what":"std::exception"}
```

**Comment by arifcatalyst** [comment]
I am adding a detailed logfile - 

```
357 [2018-06-19 13:24:23.200] [foreground] [info] --sleeping
1357 [2018-06-19 13:24:50.532] [background] [info] Syncing folder list...
1357 [2018-06-19 13:25:50.778] [background] [info] Sleeping after exception: {"debuginfo":"syncFoldersAndLabels - fetchAllFolders","key":"ErrorConnection","retryable":true,"what":"std::exception"}
1357 [2018-06-19 13:26:08.850] [metadata] [info] Metadata delta stream closed.
1357 [2018-06-19 13:26:08.857] [metadata] [info] Metadata delta stream starting...
```

**Comment by CodeMouse92** [comment]
If your university requires you to configure a proxy, as some do, then Mailspring would not be able to connect. See: https://community.getmailspring.com/t/mailspring-with-proxy/298

**If your university does not require a proxy, and you're still having this problem, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

---

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)
