### ISSUE TITLE
Desktop Notifications Not Working in the Linux Snap

### ISSUE THREAD

**Issue by etrigan63** [Foundry376/Mailspring#911]
The Mailspring Snap does not generate desktop notifications in Ubuntu Mate 18.04. The mail sound is heard, but no popup occurs. I have the latest version of `Zenity` installed. I do have the nVidia proprietary drivers installed on my system. If I install the deb version, notifications work as expected, but then I don't get the auto-update features of the snap.

##### Are there any related issues?
A search of related issues turned up nothing
...

##### What operating system are you using?
Ubuntu Mate 18.04

##### What version of Mailspring are you using?
1.2.2-96fb3a99

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No 3rd party plug-ins installed

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Happens with Gmail, Office365, and iCloud (I have not tested others)

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Any inbound message does not generate a desktop notification. Nothing to screenshot.
...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by etrigan63** [comment]
Sorry, I fat-fingered the title into something meaningless originally. It is correct now. Am I the only one having this issue?

**Comment by LogX7** [comment]
+1 but not all notiication, the message has been read notification is working, but the new received message notification isn't

**Comment by kevvvvyp** [comment]
Workaround: https://linuxconfig.org/how-to-install-mailspring-on-ubuntu-18-04-bionic-beaver-linux

**Comment by efirvida** [comment]
same issue here, the try ico chage its color to blue, but no notification. iḿ using ubuntu 18.04 too, and gmail

**Comment by Javinator9889** [comment]
Currently I'm having the same issue at the same version of Ubuntu

**Comment by Javinator9889** [comment]
> Currently I'm having the same issue at the same version of Ubuntu

Checked, now they are working
Looks like a Ubuntu missconfiguration

**Comment by bengotow** [comment]
Hey folks! Looks like the last post on this topic was a year ago, going to go ahead and close this!

**Comment by luizoti** [comment]
Same problem here, any solution? The notification sound works, but toast notification not.
