### ISSUE TITLE
1.2.2 no longer launching

### ISSUE THREAD

**Issue by ASAPHAANING** [Foundry376/Mailspring#912]
My mailspring suddenly started launching it seems to be immediately after an update to snap. Used that to install and has been running perfectly for a long time. Now when I run it it simply never launches (no process in the background either.) 

```

➜  bin mailspring
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
```

Also tried launching using --disable-gpu.

##### Are there any related issues?

Several. None of them resolved. The latest I found was 1.2.0.

##### What operating system are you using?
Ubuntu 18.04

##### What version of Mailspring are you using?
1.2.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

_________

IMPORTANT: Running: snap refresh mailspring --channel=edge
Updates mailspring and allows the software to run again.

**Comment by mkaz** [comment]
I had the same issue, I installed using snap, which you can revert to previous version using:
```
$ snap revert mailspring
mailspring reverted to 1.2.1
```

**Comment by ASAPHAANING** [comment]
Had the same problem again at 1.2.3.cxxxx. Reverted back and now running 1.2.3.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
