### ISSUE TITLE
Error messages appearing (apparently) randomly in the message panel

### ISSUE THREAD

**Issue by Bergg** [Foundry376/Mailspring#915]
##### What operating system are you using?
Fedora 27

##### What version of Mailspring are you using?
snap edge version

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no
![screenshot from 2018-06-04 13-02-37](https://user-images.githubusercontent.com/2852555/40914728-91aa24fe-67f9-11e8-9fba-1fd3d736080b.png)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by alenguav** [comment]
I am getting a similar error message in Ubuntu 

![image](https://user-images.githubusercontent.com/8136193/52293942-0a5fa280-2946-11e9-9efb-acee908c7e6c.png)

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
