### ISSUE TITLE
[Feature Request] Add a keyboard shortcut for adding an attachment

### ISSUE THREAD

**Issue by puterleat** [Foundry376/Mailspring#92]
I downloaded the latest release (yesterday). Lovely so far and a possible Mail killer for me but:

- No keyboard shortcut for adding an attachment in compose view(?) In apple mail this is Cmd+Shift+A
- On OSX clicking the "Edit Custom Shortcuts" button does nothing (although it does move the view of the prefs page by about 10 pixels)

**Comment by bengotow** [comment]
Hey! I actually didn't realize there was a shortcut for this in Apple Mail. We can definitely get this added. If anyone wants to take a stab at this, it'd be a great PR. 

We'd need to add a default shortcut here:
https://github.com/Foundry376/Mailspring/blame/master/app/keymaps/base.json#L60

And then implement it here:
https://github.com/Foundry376/Mailspring/blame/master/app/internal_packages/composer/lib/composer-view.jsx#L104

And make it viewable / editable by the user here: 
https://github.com/Foundry376/Mailspring/blame/master/app/internal_packages/preferences/lib/tabs/keymaps/displayed-keybindings.js#L32
