### ISSUE TITLE
Compose email windows hangs while writing a big email

### ISSUE THREAD

**Issue by anshuman73** [Foundry376/Mailspring#927]
##### Are there any related issues?

No

##### What operating system are you using?
...

##### What version of Mailspring are you using?
Ubuntu 18.04

--

**Bug?**

Mailspring compose window hangs on writing a big email. I'm writing a big email (about 3 pages on a word processor), and the compose window has just hanged, with the cursor not blinking. Pressing keys on the keyboard doesn't help, however, I opened a text editor and typed something on it while Mailspring was hanged, and it worked just as expected. The issues is only seen in Mailspring compose window. I can use the search bar, etc in the main mailspring app even when the compose window is hanged.

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Not sure

**Comment by anshuman73** [comment]
Update: The typed message appears after a while. Took me about 5-7 minutes.
Problems in scrolling through the email is also observed

**Comment by anshuman73** [comment]
Update: Window not responding message is shown by Ubuntu, and nothing can be performed on the compose window. I'm stuck with not being able to finish an important email, nor being able to select it and copy-paste somewhere else.

**Comment by owrede** [comment]
I can confirm this behavior on a Mac with OS 10.13.5 and MailSpring 1.2.2
Long message. Composer window gets unresponsive so that it is impossible to write.

**Comment by Chaupeter** [comment]
I also can confirm this with the Windows version 1.2.2  Windows 10 Build 17686  The fault can be triggered also by pasting a long weblink from a browser. The composer just becomes unresponsive and hangs after a couple of minutes.

**Comment by trappedinalift** [comment]
Seconding the Windows 10 report. 
Mailspring 1.2.2 on Windows 10 Build 17134 no plugins. Composer becomes unresponsive, maxes a couple of CPU cores and hangs for a minute or two before displaying input. I can type an email whilst it is unresponsive and then it begins to slowly display it character by character.

**Comment by appukuttan-shailesh** [comment]
Experiencing the same currently while composing a moderately long email. 
The email had several urls (hyperlinks)... if it helps diagnose the issue.

MailSpring 1.4.2
OS: Ubuntu 16.04 LTS 64-bit

**Comment by monkeydri** [comment]
Also happens to me, not necessarily on long emails but long threads (with many emails). If I restart mailspring it is then fine (it only happens after Mailspring has been running for a while).

MailSpring 1.4.2
Ubuntu 18.04 LTS 64-bit

**Comment by heliostatic** [comment]
Still hitting this issue today. Wondering if it's related to the URL regex on paste? https://github.com/Foundry376/Mailspring/blob/master/app/src/components/composer-editor/link-plugins.tsx#L16

cc @bengotow

**Comment by bengotow** [comment]
The infinite backtracking in that regexp is fixed by https://github.com/Foundry376/Mailspring/commit/1d2163c29a7466ac2126359dc500f192c84606c5 — I'm super hopeful that this was causing the hanging reported here, but it's possible there are other problems going on here so I'll leave this ticket open. In general long emails seem to be pretty performant, so if the composer totally freezes it's probably something specific to the content being entered.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
