### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by nunojesus** [Foundry376/Mailspring#934]
Hi, first congrats for your project.
I like to contribute with graphic designs, in opensource projects, so if you need something from me like a logotype or something else just say it, Im here ready to help you.
Greetings!
Nuno Jesus

**Comment by oxysoft** [comment]
A new logo would be great for MailSpring, it has no identity at the moment. Is 'Spring' like a mechanical spring, or rather more like the season?

**Comment by nunojesus** [comment]
Hi @oxysoft  do you have any request? colors? where can I get inspired?

**Comment by oxysoft** [comment]
No idea, I'm just a random passerby, not an actual contributor to this project.

**Comment by sNiXx** [comment]
I agree with @oxysoft that a new logo with at least some identity would be nice. What is your opinion on this, @bengotow?

**Comment by CodeMouse92** [comment]
Sorry for the delay, @nunojesus. This got rather lost in the GitHub Issues backlog.

Are you still interested in helping with graphics? I can't speak for Ben, but I think there's a good possibility he'd be open to a branding refresh. I know we plan to give the UI a new "coat of paint" at some point soon.

Please join https://community.getmailspring.com and post in the Development area if you're still interested!
