### ISSUE TITLE
Mailspring does not detect the devicePixelRatio when using a retina display on Gnome

### ISSUE THREAD

**Issue by franktopel** [Foundry376/Mailspring#939]
It looks like Mailspring is not applying Gnome scaling at all, making Mailspring unusable on a Macbook Pro running Gnome.

Also by the looks of it, CTRL + / - for Zooming In/Out has been disabled on Mailspring (which sucks by itself).

Last thing is the DEV tools in Mailspring say it's based off Chrome 59 (which seems like from the stone age) - Chrome 67 is the current Chrome version. Why is the underlying Chrome engine so old?

**Comment by bengotow** [comment]
Hey - if you go to Preferences > Appearance you can scale the UI from there. Mailspring is based on Electron which is a bit behind Chromium. Mailspring 1.3 will ship with Chromium 61, but Electron 3 (which targets the newer version of Chromium) is still in alpha.

I'm surprised it didn't pick up the display pixel density though. Is there any chance you also have an external display plugged in /sometimes/?

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved — I tested it myself on Ubuntu 20.04 and GNOME 3.36, and scaling works — so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
