### ISSUE TITLE
Memory leak on OS X

### ISSUE THREAD

**Issue by bynicolas** [Foundry376/Mailspring#94]
##### Are there any related issues?
These seem to be related 
#91 #89 
#87 ( I to have a crash upon syncing... might be related to the memory leak issue)

##### What operating system are you using?
macOS Sierra 10.12.6 (16G29)

##### What version of Mailspring are you using?
v.1.0.2-4eab3f85

--

**Bug?**
Crashes when trying to sync (or index) an IMAP account. Leaking memory
![Image of memory leak](https://imgur.com/KtmkLvs.png)

This brings up the OS X screen **Your system has run out of application memory** and pauses all other applications
![Image of memory leak](https://imgur.com/7Hpx5Qh.png)

**Comment by bengotow** [comment]
Thanks for reporting this - I'm gonna merge this into #91 and we'll keep debugging it there.
