### ISSUE TITLE
Setting up Mailspring requires an internet connection

### ISSUE THREAD

**Issue by wsidl** [Foundry376/Mailspring#946]
##### Are there any related issues?

#140 #161 

##### What operating system are you using?
Windows 7, Fedora 28

##### What version of Mailspring are you using?
1.2.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None, barely installed

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Can't get there yet

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Fresh computer with no access to internet, install Mailspring and start.

--

Problem I'm facing is with a new instance of Mailspring. I'm looking to switch out my current desktop mail client but installation stalls (no crashes) and force-closing and restarting it generates an error:

>  Could not reach Mailspring. Please try again or contact
>   support@getmailsping.com if the issue persists.
>   (https://id.getmailspring.com/onboarding?
>   utm_medium=N1&utm_source=OnboardingPage&N1_version=1.2.2-
>   96fb3a99@client_edition=basic: 403)
> 
>   [Try Again]

Workstation is on an offline, secured environment and cannot access the internet. All network services are hosted internally.

**Comment by bengotow** [comment]
Hey! Well, this is a bit awkward - Mailspring works fine offline but only AFTER you link your first email account. You'll need an internet connection to link the app to a Mailspring ID and also link it to an email account and get mail from somewhere, but then you can be offline all you want.

**Comment by MissLummie** [comment]
Why there is no option to use mailspring without mailspring id at all? If I use it offline I don't need nothing to be sync..

**Comment by Pidbid** [comment]
I agree with alumag.

**Comment by philippmatuschek** [comment]
**Yes, totally agree with alumag**. We don't have direct internet access at our workstations, so I am not able to install mailspring at all. That's so sad because it looks great!
