### ISSUE TITLE
Rebuild on fedora 26

### ISSUE THREAD

**Issue by tienhuynh5312** [Foundry376/Mailspring#95]
We encountered a problem with your local email database. Error: /usr/share/mailspring/resources/app.asar.unpacked/mailsync.bin: error while loading shared libraries: libsasl2.so.2: cannot open shared object file: No such file or directory

Error encountered on Fedora 26

**Comment by sthagedorn** [comment]
I also encounter this bug. 

I worked around it by linking libsasl2:
`sudo ln -s /usr/share/mailspring/resources/app.asar.unpacked/libsasl2.so.2 /usr/lib64/`

**Comment by bengotow** [comment]
Hey! Thanks for filing this - this should be fixed in 1.0.3 which will ship in an hour or two. Stay tuned! You can check out the full changelog here: https://github.com/Foundry376/Mailspring/blob/master/CHANGELOG.md

**Comment by tienhuynh5312** [comment]
Thanks. Mailspring will be dope 😁
