### ISSUE TITLE
Print window error

### ISSUE THREAD

**Issue by Blackphantom96** [Foundry376/Mailspring#958]
# Isue: 
In the printing window there is an error because the top bar shows several options that should not appear, apart from this when printing large threads (2 pages) does not print, but with short messages if it works.

##### Are there any related issues?

No

##### What operating system are you using?
Windows 10 
##### What version of Mailspring are you using?
1.2.2-96fb3a99
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
##### Is the issue reproducible with a particular attachment, message, signature, etc?

No
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No

**Comment by Blackphantom96** [comment]
![sin sdafasdfsadf](https://user-images.githubusercontent.com/19200060/42114066-4ffb373c-7bb3-11e8-94c2-a348a3e1e77d.png)

**Comment by bengotow** [comment]
Hey folks—this shipped in version 1.3.0. The app should have auto-updated by now, but if not you can download the latest release from https://www.getmailspring.com/download. Enjoy!
