### ISSUE TITLE
Erratic keymap behavior with search and focus-search keymappings

### ISSUE THREAD

**Issue by pdaniell** [Foundry376/Mailspring#960]
##### Are there any related issues?

...

##### What operating system are you using?
 use two OSes: Ubuntu 16.04 and MacOS 10.13.5

##### What version of Mailspring are you using?
In both cases Version 1.2.2 

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No.
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I can't say for sure because I use only one email provider.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

It is consistently reproducible.
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
This issue is a bug.

I try to use my email client with minimal use of the mouse. I changed my "core:focus-search" keymap to Cmd+P. When the search field has focus, it is not really possible to return to the resulting result list with the keyboard. There are really two cases of this bug:

(1) If you let the search field obtain focus and the search field is empty, then it does not appear anything you keypress allows you to return to the message list. If you type something, then escape returns focus to the message list. 

(2) If you execute a search, pressing escape returns you to the message list but clears the search result. Moreover it seems that the escape key is the only key that does this --- you cannot, for example, change "core:pop-sheet" (the key map which the keymaps tab in preferences says "returns you to the conversation list") to another key combination. Even if you do, you will still need escape to return.

**Comment by bengotow** [comment]
Hey folks—this shipped in version 1.3.0. The app should have auto-updated by now, but if not you can download the latest release from https://www.getmailspring.com/download. Enjoy!
