### ISSUE TITLE
[Feature request] "Apply mail rules" keyboard shortcut

### ISSUE THREAD

**Issue by phcorp** [Foundry376/Mailspring#963]
Since mail rules are not always working (see #605), it would be convenient to have a keyboard shortcut that applies mail rules as the "Process entire inbox" button located in "Preferences" > "Mail rules section". An application menu item may be added too.

**Comment by bengotow** [comment]
Hey! #605 will be fixed in the next release, going to merge this in to that since the shortcut won't be necessary once the rules are consistently applied.

**Comment by quixoticraindrp** [comment]
This issue was *not* fixed in 1.6.1. See https://github.com/Foundry376/Mailspring/issues/605#issuecomment-481102543
