### ISSUE TITLE
Facebook & Twitter Icons of Signature not loading

### ISSUE THREAD

**Issue by qadir5000** [Foundry376/Mailspring#968]
##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.2.2

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
G Apps

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Created my signature using the built-in signature creator, Facebook and Twitter icons aren't loading.

**Comment by bengotow** [comment]
Hey @qadir5000 thanks for filing this - it looks like those images are using `data:image/gif` URLs and we'll need to swap them out for standard HTTP/HTTPS URLs to make them work in both Outlook and Gmail. I'll get that changed!

**Comment by bengotow** [comment]
Hey folks—this shipped in version 1.3.0. The app should have auto-updated by now, but if not you can download the latest release from https://www.getmailspring.com/download. Enjoy!
