### ISSUE TITLE
Initial sync after waking from sleep is a little heavy on CPU

### ISSUE THREAD

**Issue by axfelix** [Foundry376/Mailspring#972]
My notebook is getting a little old (Haswell), so I can see how this might be a won'tfix, but I've been noticing that the sync Mailspring performs immediately after waking from sleep on my notebook pegs ~40% of my CPU for 3-4 minutes, which is pretty exceptional in the context of all the other programs I run and is "training" me to use my computer in a way I don't quite like (and generally doesn't compare favourably to webmail clients).

Is there any way this can be made a little lighter? It doesn't need to sync this hard when it fetches new email, so I'm a little skeptical...

This is on a ~12GB Gmail account, btw.

**Comment by bengotow** [comment]
Hey! I'll take a look at this but I'm not sure there's a good short-term fix. We periodically de-fragment the database, which helps keep some of the sync queries running fast, but I'm not sure there are any big quick wins left. Will do some profiling and see what's going on.
