### ISSUE TITLE
ReplyTo field doesn't show up unless replying

### ISSUE THREAD

**Issue by Draghmar** [Foundry376/Mailspring#973]
##### Are there any related issues?
I couldn't find any.

##### What operating system are you using?
Windows 10.

##### What version of Mailspring are you using?
1.2.2

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
When I receive an e-mail that was send through some webform it has ReplyTo set to the person who used the form and From to some "dummy" e-mail. For reason unknown to me when you open message details there is no ReplyTo visible there. Which means the only way I could know from who mail like that came from is to hit reply. Also when forwarding this info is also missing. And those two cases makes using Mailspring a little annoying in my day to day workflow.
Thunderbird has this feature.

**Comment by bengotow** [comment]
Hey! I get emails from a contact form that works that way and I'm able to reproduce this. Super weird it's missing. I'll see what's going on.

**Comment by bengotow** [comment]
It actually looks like the "detailed headers" area of the message view doesn't show Reply-To at all, ever. I'm not sure how this has been overlooked for 3+ years but it should be a quick fix. Stay tuned!

**Comment by Draghmar** [comment]
Thanks for the update! Works like a charm. :)
