### ISSUE TITLE
Tiny tiny text on a 4K monitor even at 200%

### ISSUE THREAD

**Issue by pnunn** [Foundry376/Mailspring#974]
##### Are there any related issues?

This looks horribly like error #563 (that was meant to be fixed).

##### What operating system are you using?
Ubuntu 18.04

##### What version of Mailspring are you using?
1.2.2 from the deb (I removed the snap version because of issues with wayland). I'm now back on X11

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Didn't know you could

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Nope

##### Is the issue reproducible with a particular attachment, message, signature, etc?
The laptop is a 13 inch 4K monitor. The text is so small it can't be read. 

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment]
Hey! I'm really curious to see this will be fixed in the next release which uses Electron 2.x - stay tuned.

**Comment by geoffgarside** [comment]
This appears to still be an issue with the latest snap version 1.7.4, the mouse pointer is tiny.

**Comment by Grawl** [comment]
The mouse pointer is tiny

Fedora 31
Snap,

**Comment by manuelfedele** [comment]
Still relevant in 1.7.8 (Ubuntu 20.04, 4k resolution and scale 200%)
Text is now ok, but poiner is very small.

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@Grawl or @manuelfedele Could you open a new issue on Discourse regarding the mouse pointer, if you're still having that problem in 1.8.0?

We hope to see you there soon!

-The Mailspring Team
