### ISSUE TITLE
remove Send and Archive button on new emails

### ISSUE THREAD

**Issue by PauloPeres** [Foundry376/Mailspring#980]
**Feature Request?**
It's not a bug per-say, and it's not a feature request, it's usability issue.
When you start drafting a new email, the "Send and archive" button is still there, but it does not make sense because i don't have anything to archive, we should remove the "Send and Archive" button on this case.

**Comment by bengotow** [comment]
Hey! The fix for this shipped in v1.5.4 this afternoon. Mailspring should auto-update in the next few hours and you can also download the update directly from https://getmailspring.com/download. Happy new years!
