### ISSUE TITLE
Mailspring does not open on Fedora 29 Rawhide

### ISSUE THREAD

**Issue by pbirkbeck** [Foundry376/Mailspring#982]
When running the latest version of mailspring from applications menu nothing happens. When running from terminal I get this -
Segmentation fault (core dumped)

Also snap package does not open either

**Comment by bengotow** [comment]
Hey thanks for reporting this—can you try running mailspring from the command line like this:
```
ELECTRON_ENABLE_LOGGING=true mailspring
```

I've seen this before specifically with the Snap package when it's getting AppArmor violations and needs additional permissions, but not in the un-snapped version.

**Comment by IgnusG** [comment]
I'm having the same problem. The above command unfortunately doesn't output any more information though.

Running:
- Linux Kernel 4.17.13 on Arch
- Mailspring version 1.3.0

Might be fixed by newest version but AUR package hasn't been updated yet.
The issues might be related to glibc according to the comment section on the [AUR repo](https://aur.archlinux.org/packages/mailspring/).

**Comment by mthomos** [comment]
The workaround is to update to Electron. The issue has been fixed

**Comment by el-psycho** [comment]
I'm still having this issue on Fedora 29 using the snap package. I get the following in the terminal:
```
$ ELECTRON_ENABLE_LOGGING=true mailspring
[11956:0201/084317.088215:WARNING:browser_main_loop.cc(269)] Gtk: cannot open display: :0
```

**Comment by avra911** [comment]
same here

**Comment by igornoberto** [comment]
> I'm still having this issue on Fedora 29 using the snap package. I get the following in the terminal:
> 
> ```
> $ ELECTRON_ENABLE_LOGGING=true mailspring
> [11956:0201/084317.088215:WARNING:browser_main_loop.cc(269)] Gtk: cannot open display: :0
> ```
> 
> mailspring snap info:
> 
> ```
> $ snap list mailspring
> Name        Version  Rev  Tracking  Publisher    Notes
> mailspring  1.5.5    309  stable    foundry376✓  -
> ```
> 
> snapd info:
> 
> ```
> $ snap version
> snap    2.36.3-1.fc29
> snapd   2.36.3-1.fc29
> series  16
> fedora  29
> kernel  4.20.4-200.fc29.x86_64
> ```

Exactly same issue.

**Comment by umuur** [comment]
> > I'm still having this issue on Fedora 29 using the snap package. I get the following in the terminal:
> > ```
> > $ ELECTRON_ENABLE_LOGGING=true mailspring
> > [11956:0201/084317.088215:WARNING:browser_main_loop.cc(269)] Gtk: cannot open display: :0
> > ```
> > mailspring snap info:
> > ```
> > $ snap list mailspring
> > Name        Version  Rev  Tracking  Publisher    Notes
> > mailspring  1.5.5    309  stable    foundry376✓  -
> > ```
> > snapd info:
> > ```
> > $ snap version
> > snap    2.36.3-1.fc29
> > snapd   2.36.3-1.fc29
> > series  16
> > fedora  29
> > kernel  4.20.4-200.fc29.x86_64
> > ```
> 
> Exactly same issue, but using version 1.6.1.

```
$ snap list mailspring
Name        Version  Rev  Tracking  Publisher    Notes
mailspring  1.6.1    346  stable    foundry376✓  -
```
Same here, Fedora 29 - Mailspring 1.6.1

**Comment by lwille** [comment]
Same on Fedora 30
```
$ ELECTRON_ENABLE_LOGGING=true mailspring
[14840:0522/112259.362701:WARNING:browser_main_loop.cc(269)] Gtk: cannot open display: :0
$ snap list mailspring
Name        Version  Rev  Tracking  Publisher    Notes
mailspring  1.6.1    346  stable    foundry376✓  -
$ snap version
snap    2.38-3.fc30
snapd   2.38-3.fc30
series  16
fedora  30
kernel  5.0.16-300.fc30.x86_64
```
