### ISSUE TITLE
SMTP error hostname while adding gmail account

### ISSUE THREAD

**Issue by zeratoss** [Foundry376/Mailspring#984]
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10N

##### What version of Mailspring are you using?
1.3

--

**Bug?**
I am unable to add a Gmail account via OAuth (fails with SMTP error or IMAP
The problem seems to be my hostname:

```
----------SMTP----------
220 smtp.gmail.com ESMTP j3-v6sm10173326wrt.70 - gsmtp
EHLO DerK�hlschrank
501-5.5.4 HELO/EHLO argument "DerK�hlschrank" invalid, closing connection.
501 5.5.4  https://support.google.com/mail/?p=helo j3-v6sm10173326wrt.70 - gsmtp
HELO DerK�hlschrank
QUIT

SMTP Last Response Code: 220

SMTP Last Response: 


mailsmtp Last Error Code: 3

mailsmtp Last Error Location: 2
```

I changed my hostname rebooted and reinstalled mailspring but still the same problem
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Everytime with my google account, other email accounts work

**Comment by bengotow** [comment]
Hey! This is pretty interesting - it looks like your hostname contains invalid characters that the Gmail server won't accept. I'm not sure how much control we have over this in Mailspring but I'll see if it's something I can address.

**Comment by zeratoss** [comment]
Thanks, the confusing thing is I changed my hostname and reinstalled mailspring but I still get the same error, is my old hostname saved somewhere?
