### ISSUE TITLE
Mailspring cannot be opened in background when launching from command line

### ISSUE THREAD

**Issue by krupenja** [Foundry376/Mailspring#989]
##### Are there any related issues?

No

##### What operating system are you using?
macOS 10.13.6

##### What version of Mailspring are you using?
1.3.0

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

##### Steps to reproduce:
1. Open Terminal.
2. Launch Mailspring using either `open -a /Applications/Mailspring.app --hide` or `open -g /Applications/Mailspring.app`

App launches above all other windows even though it should launch in background. works fine with other apps I have tried.

**Comment by bengotow** [comment]
Hey! Please try this instead:

```
open -a /Applications/Mailspring.app -g --args --background
```

Mailspring has it's own background flag (mostly for Linux) that takes precedence over the macOS version I think. Passing both seems to do the trick though.

**Comment by krupenja** [comment]
@bengotow Thank you! This helps.
