### ISSUE TITLE
Sent labels in inbox of one of 3 gmail accts, how to get rid of them?

### ISSUE THREAD

**Issue by EricZimmerman** [Foundry376/Mailspring#992]
no related issues that i could find

os == windows 10

version == 1.3.0

no 3rd party plugins

gmail related

unknown if reproducable.

so far i have compared the back end gmail.com settings for 2 accts. they match, so i do not know why i am seeing this in one gmail acct (expected):

![image](https://user-images.githubusercontent.com/4265254/43048725-672fa456-8dba-11e8-87d0-78107ff7d6f3.png)

and this for the other (not expected):

![image](https://user-images.githubusercontent.com/4265254/43048741-8ff8843e-8dba-11e8-9791-4b719b296e1c.png)

when i click on either the expected or the not expected acct, all the emails in the thread appear, but i cannot determine why only a single of the 3 accts i have added to mailspring is doing this.

**Comment by bengotow** [comment]
Hey! This is pretty odd, because Gmail's sent label is usually called `Sent Mail` not `Sent`. Is there any chance you have an actual label in that account called "Sent"? It may be that another mail client created this label.

**Comment by EricZimmerman** [comment]
ah, this was it it looks like. when i deleted that label, poof! fixed!
