### ISSUE TITLE
Preferences pages not rendering correctly in Ubuntu 18.04

### ISSUE THREAD

**Issue by ngBroken** [Foundry376/Mailspring#993]
The preferences pages are not rendering correctly in Ubuntu 18.04. This makes it impossible to update the signature (and probably lots of other things) See attachedscreenshot.
![mailspring](https://user-images.githubusercontent.com/7972783/43056145-e485f7c0-8e7d-11e8-9fde-47e92f5fdd93.png)

**Comment by bengotow** [comment]
Hey! I've seen some reports of this happening on Ubuntu - can you try running the app with `--disable-gpu` and see if that resolves the issue?

**Comment by liudas777** [comment]
I'm having the same problem with all windows. Can't use Mailspring anymore...

**Comment by ngBroken** [comment]
Hi, yes if I run it with that option it displays the settings properly

**Comment by CodeMouse92** [comment]
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
