### ISSUE TITLE
emails not moved to folder on server

### ISSUE THREAD

**Issue by Bergg** [Foundry376/Mailspring#995]
##### Are there any related issues?

#304

##### What operating system are you using?
...
Fedora28
##### What version of Mailspring are you using?
...
snap --edge on a Zimbra server.
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No

When moving an email to a folder, it appears to have moved on the MailSpring client but checking directly on the server it remains in the Inbox. Very likely to be connected to #304 . Not an issue on Nylas Mail.

**Comment by bengotow** [comment]
Hey! Yep it sounds like Mailspring is unable to perform actions on your server for some reason—I'm gonna merge this into #304 and we'll see if we can resolve that ticket soon.
