### ISSUE TITLE
[Feature request] Add a menu item for viewing the source code of a message

### ISSUE THREAD

**Issue by dimmuboy** [Foundry376/Mailspring#996]
**Feature Request?**
Please add option for show source code of message because sometime I need to see all message data for the highest level security.
##### Does this feature exist in another mail client or tool you use?
This option have Thunderbird, Outlook and probably others too.

**Comment by bengotow** [comment]
Hey! We really need to expose the option for this. Right now, there's a bit of a hack in the app - you can click in the empty space to the left of the "Reply/ Forward" button in a message to show a menu with advanced options, including Show Original:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/1037212/43607529-4dc67796-9653-11e8-9021-e23b72df81f3.png">

**Comment by bengotow** [comment]
Merging this in to #441
