### ISSUE TITLE
ppa for mailspring?

### ISSUE THREAD

**Issue by nazar2sfive** [Foundry376/Mailspring#999]
Any ppa available for easy install of mailspring in ppa. I want system update to also update my mailspring app.

**Comment by bengotow** [comment]
No - for auto updates on Linux please use the Snap release (via `snap install mailspring`)

**Comment by timgoodwin123** [comment]
Using the Snap package I am unable to attach files from a shared drive in Linux. The drive is mounted at /shared on boot. But attempting to attach a file from this drive results in 'file not found or insufficient permissions' error. Using the .deb I do not have this problem. Something to do with sandboxing? Makes the Snap unusable for me.

**Comment by timgoodwin123** [comment]
You can still install the .deb package - although you will not auto-update you are informed when new updates are available. The deb package is clearly shown for Linux installs.

Tim Goodwin
Actor, Presenter, Geek

timgoo@gmail.com (mailto:timgoo@gmail.com)
http://www.timgoodwin.co.uk

**Comment by murbanowicz** [comment]
@bengotow snaps are easy to use but they are definitely not lightweight which quickly become an issue when you have multiple snaps. PPA would be really nice to have.

**Comment by niksingh710** [comment]
Snap affects the startup time by a lot.
having a source for deb will be nice like chrome deb has. one install no headache to re-download.
